govuk-one-login/authentication-api

build.gradle
src/main/java/uk/gov/di/configuration/AuthenticationApiConfiguration.java
src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
src/main/java/uk/gov/di/entity/VcapServices.java
src/main/java/uk/gov/di/exceptions/InvalidClientException.java
src/main/java/uk/gov/di/helpers/AuthenticationResponseHelper.java
src/main/java/uk/gov/di/services/AuthenticationService.java
src/main/java/uk/gov/di/services/AuthorizationCodeService.java
src/main/java/uk/gov/di/services/ClientService.java
src/main/java/uk/gov/di/services/TokenService.java
src/main/java/uk/gov/di/services/UserService.java
src/main/java/uk/gov/di/services/ValidationService.java
src/main/java/uk/gov/di/validation/EmailValidation.java
src/main/java/uk/gov/di/validation/PasswordValidation.java
src/test/java/uk/gov/di/entity/VcapServicesTest.java
src/test/java/uk/gov/di/services/AuthorizationCodeServiceTest.java
src/test/java/uk/gov/di/services/ClientServiceTest.java
src/test/java/uk/gov/di/services/TokenServiceTest.java
src/test/java/uk/gov/di/services/UserServiceTest.java
src/test/java/uk/gov/di/services/ValidationServiceTest.java
src/test/resources/oidc-provider.yml

First pass at migrating the code from https://github.com/alphagov/di-auth-oidc-provider
Basic for the new API application.

LTG-202: migrate code from old to new repo

---

authentication-api.yml
src/main/java/uk/gov/di/AuthenticationApiApplication.java
src/main/java/uk/gov/di/configuration/AuthenticationApiConfiguration.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/resources/ClientRegistrationResource.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/LogoutResource.java
src/main/java/uk/gov/di/resources/RegistrationResource.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/resources/UserInfoResource.java
src/main/java/uk/gov/di/resources/WellKnownResource.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/ClientRegistrationResourceTest.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/RegistrationResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java
src/test/java/uk/gov/di/services/ClientServiceTest.java

Migrate OIDC provider code to a new API.
Remove all UI related code.
Separate the OIDC provider API from the registration and login UI.
https://github.com/alphagov/di-auth-oidc-provider

LTG-202: Migrate OIDC provider code to a new API

---

serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java

Add unit tests for the token lambda request handler.
Tests are good!

LTG-256: Write unit tests for the token handler Lambda

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/InMemoryUserInfoService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/main/java/uk/gov/di/services/UserInfoService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java
src/main/java/uk/gov/di/resources/ClientRegistrationResource.java
src/test/java/uk/gov/di/resources/ClientRegistrationResourceTest.java

Write unit tests for the `userinfo` lambda function
Minor refactoring of error messages and access token validation.
We need to ensure our lambda function is tested.

LTG-256: Unit tests for userinfo

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java

- Write the wellknown endpoint using AWS lambda with unit tests

LTG-265 - Port wellknown endpoint to Lambda function

---

ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
ci/terraform/localstack/site.tf
ci/terraform/localstack/variables.tf
ci/terraform/modules/api-gateway-root/api-gateway-root.tf
docker-compose.yml
docker/localstack.Dockerfile

Add Terraform and Docker config for Localstack
Able to run Terraform against Localstack to test API Gateway and Lambda

LTG-268: terraform and docker for localstack

---

serverless/lambda/src/main/java/uk/gov/di/helpers/RequestBodyHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ValidationService.java
serverless/lambda/src/main/java/uk/gov/di/validation/EmailValidation.java
serverless/lambda/src/main/java/uk/gov/di/validation/PasswordValidation.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

- Create a new handler which will handle and validate a signup request.
- If successful it will return 200 and if unsucessful it will return 400.
- Add unit tests for the handler

LTG-266 - Create Signup handler to run on AWS lambda

---

.gitignore
ci/terraform/aws/authorize.tf
ci/terraform/localstack/localstack.tf
ci/terraform/modules/authorise/api-gateway-token.tf
ci/terraform/modules/authorise/lambda.tf
ci/terraform/modules/authorise/variables.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

- Add Terraform for authorize endpoint
- Return the authorization response from the AuthorisationHandler
- Refactor the unit test to make sure we are sending the AuthCode in the response

LTG-257 - Deploy the authorisation endpoint to AWS Lambda 

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java

- Only call redirectResponse when there is definitely no errors present

LTG-257 - Refactor AuthorisationHandler

---

ci/terraform/modules/wellknown/api-gateway-token.tf

- The wellknown endpoint needs to be constructed of two nested resources in API gateway.

LTG-265: Nest the wellknown API gateway resources.

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java

- Check if the baseurl exists and if not throw an exception straight away instead of waiting for the first use of it

LTG-265 - Refactor wellknown handler

---

ci/pipeline.yaml
ci/terraform/aws/authorize.tf

- Correct Terraform variable names used in pipeline
- Correct stage name in authorise endpoint.

LTG-255: Fix pipeline and broken AWS terraform

---

ci/pipeline.yaml
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenResourceIntegrationTest.java

Run integration tests in the pipeline.
Ability to gate deployments to the next environment if tests fail.

LTG-275: run integration tests in the pipeline

---

ci/terraform/aws/outputs.tf
ci/terraform/aws/signup.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/SignupRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ValidationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

- Change payload from form post to JSON
- Remove parameter for confirmed password (this should be done by clients before calling the API).
- Refactor password validation and tests.
- Add the terraform to create the api gateway and Lambda required for the signup endpoint

LTG-264 - migrate signup endpoint to Lambda

---

ci/terraform/aws/redis.tf
ci/terraform/aws/vpc.tf

Added Elasticache redis cluster, including VPC and security group.
We need to store sessions.

LTG-191: Added Elasticache redis cluster

---

serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

Create a session object in the authorisation handler
Redirect to login UI passing session ID.
We need to create session when the users starts their login journey.

LTG-300: Create Session in authorisation handler

---

serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java

Attempt to connect to Elasticache from lambda.
To prove VPC configuration is correct.

LTG-300: Attempt Elasticache connection via lambda

---

.gitignore
ci/terraform/aws/outputs.tf
ci/terraform/aws/userexists.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/CheckUserExistsRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java

Add an API resource backed by a Lambda function to check whether a user exists.
Unit tests and an integration test.
For now a single test user is stubbed and there is no backing data-store.
UI flow changes depending on whether the user account exists or not.

LTG-301: lambda + api to check user exists

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java

Update header name.
Change test name.
AWS converts header names to uppercase first letter.

LTF-301: fix integration test header parameter

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/CheckUserExistsResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java

- Return 200 responses when a request is successful but a user has/hasn't been found.
- Return the response in a standard json format

LTG-301 - Return responses using the CheckUserExistsResponse object

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore

Add gitignore paths for vscode.
Add PR template

BAU: git and github tweaks

---

CODEOWNERS

Add CODEOWNERS to prompt for reviews
Prompt for reviews automatically in PRs

BAU: Add CODEOWNERS to prompt for reviews

---

serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java

Small refactoring.
Does exactly what it says on the tin.

BAU: StatefulRedisConnection implements AutoCloseable, use try-with-resource

---

ci/terraform/aws/sqs.tf
ci/terraform/localstack/sqs.tf
ci/terraform/modules/sqs-queue/lambda.tf
ci/terraform/modules/sqs-queue/outputs.tf
ci/terraform/modules/sqs-queue/sqs.tf
ci/terraform/modules/sqs-queue/variables.tf
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/NotificationCode.java
serverless/lambda/src/main/java/uk/gov/di/entity/NotificationType.java
serverless/lambda/src/main/java/uk/gov/di/entity/NotifyRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java

Add a lambda function to the Terraform SQS module that will process this module.
Only this lambda has permissions to receive messages from the queue.
Create a basic Lambda function, that will simply send an e-mail verification e-mail, this will be iterated.
We have a queue and we need something to process its messages.

LTG-228: Read from SQS

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/JwksHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/JwksHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/NotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendUserEmailHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java

- Write tests for the notification Lambda
- Reduce code duplication by making the most of the ApiGatewayResponseHelper class
- Keep the naming of final variables in the tests consistent
- The lambda didn't have any tests

LTG-228 - Write tests for the notification Lambda

---

ci/terraform/aws/vpc.tf

- We need to egress to the GOV.UK Notify API, so we need an Internet Gateway and NAT gateways.
- We should add an ACL to ensure that only Notify API can be called, but this is a starter for 10.
- Ensure we add appropriate tags to the resource to make them easy to find in the AWS console.
The lambda to send e-mails was unable call Notify as there was no route out.

LTG-342: Add Internet Egress to VPC

---

integration-tests/src/test/java/uk/gov/di/authentication/helpers/SessionHelper.java

- Include changed file that was inadvertently missed from previous PR.
Integration tests are failing in the pipeline.
#76

LTG-300: Include changes to SessionHelper class

---

serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

- Add the complete path to the redirect URI
- So it can be validated correctly

BAU - Add the complete path to the redirect URI

---

serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

- Store the authn request as a Map<String, List<String>> in the session
- So that we can deserialize the authn request

LTG-300 - Store the authn request as a Map<String, List<String>> in the session

---

.github/workflows/pre-merge-checks.yml
.gitignore
pre-commit.sh
scripts/functions.sh

Does exactly what it says on the tin  !

LTG-355: Run build and unit tests with GitHub Actions as a pre-merge check

---

.github/dependabot.yml

BAU: Add dependabot for dependency updates

---

serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

Just some tidying up from the stuff I've been working on today.

BAU: Refactor `SendNotificationHandler` tests

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/JwksHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/main/java/uk/gov/di/validation/PasswordValidation.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/JwksHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/TokenServiceTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ValidationServiceTest.java

- Add unit tests for TokenService and ValidationService
- Small refactor to pass in the ConfigurationService to the token service
- Move the Issuer variable into the method where it is only used
- To increase our code test coverage

BAU - Add unit tests for TokenService and ValidationService

---

build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/SessionHelper.java
serverless/lambda/src/main/java/uk/gov/di/Messages.java
serverless/lambda/src/main/java/uk/gov/di/helpers/HashHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/CodeStorageService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/CodeStorageServiceTest.java

This PR stores the email code in Redis, and then pulls it out again for validation

LTG-383: Store and validate against email code

---

ci/terraform/aws/redis.tf

Upsize Redis.
Seeing intermittent connection errors so seeing if this is a resource issue.

BAU: upsize Redis

---

serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/LoginRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/LoginResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LoginHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java

- Create a login request which consists of a email and password
- Validate the user credentials and return a 401 with a error response when they are invalid
- When the credentials are valid, update the state to Authenticated and send that back in the response.
- So we have an endpoint to allow users to login

LTG-397 - Create a Lambda for the login endpoint (Terraform to follow)

---

ci/terraform/aws/dynamodb.tf

- Create policy to allow Lambdas to work with Dynamo
- So that the Lambdas can communicate with Dynamo

LTG-403 - Create policy to allow Lambdas to work with Dynamo

---

ci/terraform/aws/signup.tf
ci/terraform/aws/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/UserCredentials.java
serverless/lambda/src/main/java/uk/gov/di/entity/UserProfile.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java

- Create DynamoService to talk to the DynamoDb tables
- Update SignupHandler to use DynamoService instead InMemoryUserService
- Amend Terraform to inject Dynamo endpoint for testing purposes
- Update integration tests to check that data is correctly to Dynamo
We have two shiny new DynamoDB tables, we need to start putting data in them,

LTG-403 - Write code so we can persist to Dynamo

---

serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

Update OIDC client registry to add in redirecturi
To add easier support when working locally with the frontend app.

Update redirect uri for client to support local dev

---

docker/localstack.Dockerfile
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/helpers/Argon2Helper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java

Hash passwords with Argon2 before storing.

LTG-404: Use Bouncycastle to hash passwords with Argon2

---

ci/terraform/aws/verify_code.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthenticationService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/NotificationServiceTest.java

- Update Dynamo when phone number code is valid
- Add terraform env vars to VerifyCode lambda
- Write tests for the NotificationService
- When the verify-code is called and determines that a phone number code is valid then update the UserProfile table and set the PhoneNumberVerified attribute to true.
- To allow the lambda to have the config available so it can communicate with dynamo.
- Write tests for the NotificationService

GOVSI-96 - Update dynamo when Phone Number code is valid

---

ci/terraform/aws/authorize.tf

BAU - Give Authorize lambda the env vars to talk to Dynamo

---

integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/LoginResponse.java
serverless/lambda/src/main/java/uk/gov/di/helpers/RedactPhoneNumberHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LoginHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java

- Add redacted phone number to login response
- We need a redacted number to the frontend so we can display it to the user

BAU - Add redacted phone number to login response

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java

Update well known endpoint.
To align the endpoint with what has been documented in the tech docs.

Update well known endpoint to be inline with tech docs

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

Return session cookie when authorising
Switch to server-side session management for SSO.

GOVSI-494: Return session cookie when authorising

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java

- Add extra integration test for UserInfo endpoint
- Better test coverage

GOVSI-610 - Add extra integration test for UserInfo endpoint

---

build.gradle
integration-tests/build.gradle
serverless/lambda/build.gradle

- Create variables for dependencies that share that same version 
- Remove a lot of stuff we don't need on the root build.gradle
- So it is clearer

BAU - Tidy up our build.gradles

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java

Additional integration test shouldPromptForLoginWhenPromptLoginAndUserAuthenticated
Increase integration test coverage.

GOVSI-495: additional integration test shouldPromptForLoginWhenPromptLoginAndUserAuthenticated

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java

- It can't find the session with the given sessionID so we need to check what it is
- So we can see what is going on

BAU - To see what the sessionID is

---

ci/terraform/aws/api-gateway.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java

- Enable logging of request in API gateway
- Add logging code to `token` endpoint
We are debugging the end to end journey.

BAU: Enable logging of request in API gateway

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java

Add logging into logout handler.
To help with debugging of issues.

Add logout logging to help debugging

---

integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

Update user state machine.
It was in the wrong state for when a user is trying to sign up and would cause an error.

Update state machine for signup lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java

Run Spotless over recent commits
Some recent commits did not have Spotless run on them.

BAU: Run Spotless over recent commits

---

serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistry.java

- Update `ClientRegistrationRequest` to initialise empty lists.
- Update `ClientRegistry` to initialise empty lists.
The spec states that these should always return empty lists rather than null values

BAU: Update models to ensure empty lists rather than null

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/helpers/CookieHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorizationService.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientSessionService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/AuthorizationServiceTest.java

- Send back the Errors as per the OIDC spec for when any of the validation fails.
- Move the validation into the AuthorizationService
- Add tests for the validation method
- So we are compliant with the OIDC spec

GOVSI-461 - Validate the Authn Request on the AuthorizationHandler

---

serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java

- At least until T&Cs and Consent are in
- Because otherwise we can't register a new user

BAU - Authenticated should be the next state after phone number verified for now

---

ci/terraform/aws/update_profile.tf
ci/terraform/aws/variables.tf

New env var into terraform to support updating Terms and Conditions

Terraform env var for terms and conds

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java

- We sign ID tokens with the ES256 algorithm

GOVSI-623 - Update Wellknown endpoint with algorithm

---

serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java

Does exactly what it says on the tin

BAU: Allow Authenticated -> Authenticated transition which was breaking SSO

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/auth-code.tf
ci/terraform/aws/authorize.tf
ci/terraform/aws/client-info.tf
ci/terraform/aws/dynamodb.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/login.tf
ci/terraform/aws/logout.tf
ci/terraform/aws/mfa.tf
ci/terraform/aws/outputs.tf
ci/terraform/aws/redis.tf
ci/terraform/aws/register.tf
ci/terraform/aws/sandpit.tfvars
ci/terraform/aws/send_notification.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/site.tf
ci/terraform/aws/stub-rp-clients.tf
ci/terraform/aws/token.tf
ci/terraform/aws/update.tf
ci/terraform/aws/update_profile.tf
ci/terraform/aws/userexists.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/variables.tf
ci/terraform/aws/verify_code.tf
ci/terraform/aws/vpc.tf
ci/terraform/aws/wellknown.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

Terrafom config to reduce / eliminate lambda cold start by using provisioned concurrency

Eliminate lambda cold start terraform config for provisioned concurrency

---

serverless/lambda/src/main/java/uk/gov/di/services/TokenGeneratorService.java

- Decode KMS signature using Nimbus
- As we are using EC to sign, KMS gives us the signature DER encoded. We need to decode this so it the signature can be validated by the clients

GOVSI-623 - Decode KMS signature using Nimbus

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientInfoResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistry.java
serverless/lambda/src/main/java/uk/gov/di/entity/ServiceType.java
serverless/lambda/src/main/java/uk/gov/di/entity/UpdateClientConfigRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientConfigValidationService.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ClientConfigValidationServiceTest.java

Changes to support the service type for clients (mandatory or optional) which will be used as part of the terms and conditions pages which are under development and need this data returning from the client info lambda

Back end changes to support service type for client

---

serverless/lambda/src/main/java/uk/gov/di/entity/ClientInfoResponse.java

Back end changes to support service type for client

Adding missed mapping param

---

account-management-api/build.gradle
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/HelloWorldHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
settings.gradle

- Add a new Gradle module for the account management API
- The module should produce a ZIP for lambda deployment
- Add a placeholder "Hello World" lambda function to aid building the infrastructure Terraform
We are implementing the API for account management as a separate deployable module. This PR lays the ground work for this new API.

GOVSI-715: Add module for Account Management API

---

serverless/lambda/src/main/java/uk/gov/di/entity/ClientInfoResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientInfoHandler.java

Client info lambda change to pass state to front end for use on terms and conditions pages

Passing state back from client info

---

serverless/lambda/src/main/java/uk/gov/di/domain/ClientRegistryAuditableEvent.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java

Add auditing on client registry
Continuing the rollout of the auditing functionality.
#312

GOVSI-712: Add auditing on client registry

---

serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LoginHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java

- Add Xray SDK dependency 
- Run spotless
- Add extra logging to the LoginHandler
- For greater insight into performance

BAU - Add Xray SDK to Lambdas

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/LoginHandler.java

-  Increase Lambda memory size to 1.5gb
- With hope that it increases performance

BAU - Increase Lambda memory size to 1.5gb

---

serverless/lambda/src/main/java/uk/gov/di/domain/AccountManagementAuditableEvent.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java

Add auditing for account management
This is the last area of existing code which needs to have auditing and doesn't have it yet.
#312

GOVSI-734: Add auditing for account management

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/hello-world.tf
ci/terraform/account-management/lambda-roles.tf
ci/terraform/account-management/sandpit.hcl
ci/terraform/account-management/sandpit.tfvars
ci/terraform/account-management/site.tf
ci/terraform/account-management/variables.tf
ci/terraform/account-management/vpc.tf
ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/outputs.tf
ci/terraform/modules/endpoint-module/variables.tf

- Add API gateway resources
- Add VPC and routing resources
- Add one "Hello World" endpoint using existing endpoint module
- Add simple lambda roles
- Ensure all resources are tagged with environment and application name
We are deploying a separate API for account management functions.

GOVSI-716: Add deployment of API gateway and test lambda for acct mgmt

---

ci/terraform/account-management/api-gateway.tf

Removing duplicate TF resource

Removing duplicate tf resource

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authorise-access-token.tf

Merging main and changing endpoint http method

Govsi 719 acc mgmt auth lambda

---

ci/terraform/account-management/lambda-roles.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/RedisConnectionService.java

- Create a lazier connection in the RedisConnectionService
- So it is less expensive

GOVSI-622 - Create a lazier connection in the RedisConnectionService

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/oidc/wellknown.tf
shared/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SnsService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Publish audit events to SNS
The SNS topic has been set up in Terraform so we can start publishing messages to it now.
#312
#361 
#392

GOVSI-735: Publish audit events to SNS

---

ci/terraform/oidc/events-sns.tf

- Attach SNS policy to IAM roles
- So that the Lambdas with them IAM roles have permissions to use SNS

BAU - Attach SNS policy to IAM roles

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

Reverts alphagov/di-authentication-api#410 - Whilst we demo the app

Revert "GOVSI-622 - Remove provisioned concurrency"

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

Reverts alphagov/di-authentication-api#414

Revert "Revert "GOVSI-622 - Remove provisioned concurrency""

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks.yml
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateInfoIntegrationTest.java

- Add update info integration test
- So we have good test coverage

GOVSI-628 - Add update info integration test

---

ci/terraform/account-management/sqs.tf

- Give the new IAM role permissions to write to SQS
- So it can write to SQS

BAU - Give the new IAM role permissions to write to SQS

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/UpdatePasswordRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
ci/terraform/account-management/update-password.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

Account management update password api.
So the user can update their password.

GOVSI-632: account management update password api

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotificationType.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/sqs.tf
shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java
shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java

New email template + adding notify request to sqsclient 
When a user deletes their account through we want to email them to confirm the action

Sending delete account confirmation email

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Validate access token signature in authorizer
- So we only accept access tokens we have issued

GOVSI-719 - Validate access token signature in authorizer

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Validate the access token signature
- To ensure that it has been issued by us

GOVSI-719 - Validate the access token signature

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java

- Add unit tests for authorizer
- To increase test coverage

GOVSI-719 - Add unit tests for authorizer

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java

Log session ID at entry and exit in the frontend lambdas (for happy path cases).
I missed the frontend lambdas when adding logging for errors under GOVSI-767 (#431); I will do that as a separate PR.
Will help us trace requests through the system.

GOVSI-770: Log session ID at entry and exit

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/modules/endpoint-module/warmer.tf
ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/localstack.tfvars
ci/terraform/oidc/logout.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/variables.tf
ci/terraform/oidc/wellknown.tf
lambda-warmer/build.gradle
lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/ConfigurationService.java
lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandler.java
lambda-warmer/src/main/resources/log4j2.xml
lambda-warmer/src/test/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandlerTest.java
lambda-warmer/src/test/resources/log4j2.xml
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
settings.gradle
shared/src/main/java/uk/gov/di/authentication/shared/helpers/WarmerHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Implement initial iteration of a LambdaWarmer function
- Add the warmer to the OIDC endpoints
We want to keep our Lambda's warm so they are responsive, but without the cost of the provisioned concurrency.
#448

GOVSI-622: Java Warmer for OIDC endpoints

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java

Add error logging in frontend lambdas.  I missed this in #431.
I've changed some existing messages to make things more consistent across classes.  It doesn't feel worth trying to share code for that though (but I'm open to suggestions).
Will make it easier for us to diagnose issues when the service is live.
#431

GOVSI-751: Add error logging in frontend lambdas

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java

Validate access token scopes in account management custom authorizer.
This change will restrict access to the account management api so that only clients with the 'am' scope will be able to use it.  It should only be merged with the 'am' scope has been added to the am frontend:
https://github.com/alphagov/di-authentication-account-management/commit/c1659e598f814716debb5417be3c350c6fdcb283
The token must contain the 'am' scope to allow access.

GOVSI-719: validate access token scopes in account management custom authorizer

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks-terraform.yml
.github/workflows/pre-merge-checks.yml
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authoriser-warmer.tf
ci/terraform/account-management/lambda-roles.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/site.tf
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf
ci/terraform/modules/dashboards/cloudwatch_dashboard.tf
ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/dynamodb.tf
ci/terraform/oidc/events-sns.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/kms.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/outputs.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/userinfo.tf

- Add Spotless code checking to Github actions
- Add Terraform validating and format checking
- Apply `terraform fmt` to all Terraform files
To keep our code clean and well-formatted

BAU: Add Spotless Check to pre-merge Github Actions

---

pre-commit.sh
scripts/functions.sh
startup.sh

Track duration of tasks in local startup and pre-commit scripts.
See how long the various things take to test optimisations.

BAU: track duration of tasks in local startup and pre-commit scripts

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

Log state transitions.
This will help us trace the progress of journeys when investigating issues.

GOVSI-768: Log state transitions

---

build.gradle

Remove AWS Xray as it is not used.

Remove xray

---

ci/terraform/oidc/trustmarks.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthenticationValues.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/TrustMarkResponse.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java

Add new Trust mark lambda returning static content + add to well known handler

GOVSI-813: Add new trust mark lambda + addition to well known handler

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/helpers/DynamoHelper.java
ci/terraform/oidc/signup.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Set terms and conditions version when a user signs up
- So we know what version of t&cs a user has signed up to

BAU - Set terms and conditions version when a user signs up

---

ci/terraform/oidc/dynamodb.tf

GOVSI-718 - Give permissions to perform query on UserCredentials table

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java

GOVSI-718 - Put parameters the correct way round when updating T&C

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

BAU - Set expiry to 15 minutes rather than 15 hours

---

ci/terraform/account-management/api-gateway.tf

- Ship authorizer logs to splunk
- So we can see the logs in splunk

BAU - Ship authorizer logs to splunk

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java

BAU - Add extra logging

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/helpers/DynamoHelper.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/TrustMarkResponse.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthenticationValues.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UpdateClientConfigRequest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java

Vectors of trust support for client registry + authorise endpoint

GOVSI-815: VTR work for auth endpoint + client registry

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java

- Use UTC timezome to validate the expiry of the access token
- The library we were using before was just using the current system date but we should always be explicit and use UTC

BAU - Use UTC timezome to validate the expiry of the access token

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java

- Small cleanup of SendNotificationLambda
- Add extra logging
- So it is a bit easier to read
- So we can track a session

GOVSI-668 - Small cleanup of SendNotificationLambda

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

Adding in missing state transition

Adding in missing state transition

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java

- Change update client details to put
- The update client details will now be a PUT on /connect/register/{clientId} which makes it consistent with register

BAU - Change update client details to PUT and change URL

---

ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/outputs.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf

- It's trying to create multiple register aws_api_gateway_resource which it cannot do. So add an extra variable so it doesn't create duplicate aws_api_gateway_resource for register.
- To fix the pipeline

BAU - Fix update endpoint

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/helpers/RedisHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java

Currently, the session duration is set to 1800sec (30mins). We need to change it to 3600sec (60mins).

Session time from 30 mins to 60 mins

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

Add 400 response code when verify code is blocked for the session

Add 400 resp for blocked codes

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

Return 400 if bad session action

Return 400 if bad session action

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

State handling for VERIFY_EMAIL_CODE_SENT on action USER_ENTERED_UNREGISTERED_EMAIL_ADDRESS

Adding transition to handle inital pre login back functionality

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

Additional state transition when looping acc creation

Additional state transition when looping acc creation

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

Needed state transitions for back button journyes

Needed state transitions for back button journyes

---

ci/terraform/oidc/authorize.tf

- Configure authorize with the terms and conditions version
- It is required for the state transition in the state machine

BAU - Configure authorize with the terms and conditions version

---

ci/terraform/shared/kms.tf

GOVSI-828: Attach KMS signing role to lambdas

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

BAU - Switch the check around

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Add missing state transitions
- To allow a user to start a new journey regardless of if they are blocked or not

BAU - Add missing state transitions

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Add missing state transition for when a user drops off, gets to verify phone and then clicks request a new code.
- Add extra logging to the logout handler and add null pointer checks
- For more visibility of what is going on in Logout 
- To fix state machine

GOVSI-892 - Add missing state transition

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

BAU - Add state transition required for verify email code resend

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineJourneyTest.java

GOVSI-892 - Add missing state transitions

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
ci/terraform/account-management/authenticate.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/update-password.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/BaseFrontendHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java

Logging optimisations
Reduce logging noise.

BAU: logging optimisations

---

audit-processors/build.gradle
build.gradle

Upgrade the following dependencies 
- protobuf-java
- protobuf-java-util
- gson:gson
- jakarta.el
- awaitility
- aws-java-sdk-dynamodb
- To move us on the latest and greatest

BAU - Dependency upgrades

---

kill-all-services.sh
scripts/functions.sh

- Tweak the startup and kill scripts to use docker tasks
- The project changed to use gradle tasks to start it up and run integration etc

BAU - Tweak the startup and kill scripts to use docker tasks

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java

Tidy logging in a couple of lambdas.
Keep logging clean.

BAU: log tidying

---

shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java

Optimise CodeStorageService logging.
Keep the logs clean.

BAU: reduce CodeStorageService logging

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/services/CodeStorageService.java

Account management log optimisations
Keep the logs as clean as possible.

BAU: account management log optimisations

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java

- Tidy up Account Management api logging
- Remove logging that is not required

BAU - Tidy up Account Management api logging

---

.github/workflows/pre-merge-checks-am.yml
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ConstructUriHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PhoneNumberHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/serialization/EmailDeserializer.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorisationCodeService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java

- Tidy up Shared logging
- Make changes to shared and build.gradle trigger AM github actions
- Remove logging that is not required
- AM uses the shared directory so any change to shared will change AM. We should ensure that the AM unit and integration tests run when such a change occurs.

BAU - Tidy up Shared logging

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java

Tidy frontend-api logs.
Keep the logs clean and minimal.

BAU: tidy frontend-api logs

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/helper/AuditEventHelper.java

Tidy logs in audit-processors
Remove logging that is not required.

BAU: tidy logs in audit-processors

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java

- Improve logging in OIDC and Client Registry modules
- Keep it clean

BAU - Improve logging in OIDC and Client Registry modules

---

lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandler.java

Tidy lambda warmer logs.
Remove logging that is not required.

BAU: tidy lambda warmer logs

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RequestParameters.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

Allow GA parameter to be passed to frontend via authorize
Allow GA parameter to be passed back to RP callback via authcode
This is to support cross domain tracking.

Govsi 1046

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authenticate.tf
ci/terraform/account-management/authoriser-warmer.tf
ci/terraform/account-management/lambda-roles.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/ssm.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf

This is a stepping stone to individual lambda roles in account management

GOVSI-1055: Replace account management shared roles with modularised roles

---

ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/token.tf
ci/terraform/shared/outputs.tf

Step 1 to break dependency on shared roles

GOVSI-1055: Create new base roles for `oidc` deployment

---

shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Bring our email validation inline with Notify by validating against their regex https://github.com/alphagov/notifications-utils/blob/c264fa9facedf721c8dd9cf8ee2766591e750e0c/notifications_utils/__init__.py#L14.
- Make use of the ParameterizedTest annotation to prevent repetition in Unit tests.
- This will prevent us sending emails to Notify which Notify are unable to send.

GOVSI-1111 - Validate email addresses against Notify regex

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java

- Use new test pattern for UserInfo handler integration tests
- Uncomment previously commented tests, these should now work
We're converting all integration to a new pattern

GOVSI-1105: Convert UserInfo integration tests to new pattern

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

- Convert the verify code handler integration test to new pattern
We are converting all integration tests to a more performant pattern

GOVSI-1105: Verify Code integration test

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java

- Use new test pattern for Update Profile handler integration tests
- Use new test pattern for Password Reset Request handler integration tests
We are converting all integration tests to more performant pattern
#1026
#1027 
#1031 
#1037 + more

GOVSI-1105: Integration test refactor

---

shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java

This was throwing off our error message observability

BAU: Downgrade "unknown client" to warning

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java

- Add ConfigurationService as a constructor parameter rather getting the default instance
This will be used to inject integration specific config

GOVSI-1114: Inject config into audit service

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandler.java

Log session-id using ThreadContext in client-info
- Session-Ids were being logged explicitly.
- Using ThreadContext is much neater as the value appears in a separate field.

GOVSI-1106: log session-id using ThreadContext in client-info

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java

We know the user that is interacting with the API.

BAU: Attach subject id to `VerifyCodeHandler` audit messages.

---

ci/tasks/deploy-oidc-api.yml

Deploy ipv-api in deploy oidc concourse task
ipv-api resource and zip missing from the task
#1171 
#1165

GOVSI-1165: deploy ipv-api in deploy oidc concourse task

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/AuthorisationResponseService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationResponseServiceTest.java

- Check the response contains both the state and code query parameters. Eventually we will be carrying out more checks on the state param.
- Check the if the response contains an error. If so, we'll need to treat this differently. Probably by returning it to the frontend.
- Add additional tests and integration tests
- To ensure that the response meets the validation requirements

GOVSI-1166 - Create service to parse and validate AuthorisationResponse from IPV

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/main/resources/log4j2.xml

- Add extra logging to debug state validation issue

GOVSI-1166 - Add extra logging to debug state validation issue

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java

GOVSI-1166 - Add extra logging for State

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java

Add integration test for IPVAuthorisationHandler
Increase test coverage.

GOVSI-1165: add integration test for IPVAuthorisationHandler

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java

- When claims exist in the original auth request from the Relying Party which will be supplied by IPV then we need to make sure that we pass these claims on to IPV in the Authorisation request
-  If no claims exist in the original auth request from the Relying Party then none will be included in the request to IPV
-  For now we will not use userinfo or token as the top level claims request parameter so the claims will fall directly under the claims key.
- The not including claims in the auth request when they don't exist behaviour may change in the future and we might decide that in this scenario we handle this differently as there could be little point in sending a request to IPV which contains no claims.

AUTH-1162 - Should add claims to IPV auth request when they exist

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InputSanitiser.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/InputSanitiserTest.java
shared/src/test/resources/log4j2.xml

We know the format of our ids, enforce them.

BAU: Validate base64 inputs

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/JsonArrayHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineJourneyTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/conditions/ClientDoesNotRequireMfaTest.java

This creates a helper for manipulating `JSONArrays` in the tests

BAU: Extract `JsonArrayHelper` to create and stringify arrays

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java

Do default logout when no query params present.
Support id_token_hint with or without post_logout_redirect_uri.
No query parameters are mandatory, so behave appropriately according to the parameters passed in.
Fixes NPE for when query params missing.

AUTH-1270: do default logout when no query params present

---

ci/terraform/shared/vpc.tf

- We need a VPC endpoint for S3 to allow writing to S3 buckets
We have restricted egress, but forgot to add a VPC endpoint for S3 so those things that write to S3 cannot succeed.

AUTH-1228: Add missing S3 VPC endpoint

---

ci/terraform/shared/vpc.tf

- Use Interface VPC endpoint for S3
It turns out S3 supports both Gateway and Interface style VPC endpoints, as such the Terraform is failing as it doesn't know which to select, lets use Interface style.
#1256

AUTH-1228: Use S3 Interface endpoint

---

audit-processors/build.gradle
shared-test/build.gradle
shared/build.gradle

Reverts alphagov/di-authentication-api#1252

Revert "Bump dependencyVersions.protobuf_version from 3.19.1 to 3.19.2"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

Remove things like session ids from the main log message in favour of key-value `ThreadContext` pairs.
Remove noise in logs.

AUTH-1263: Use context-based login in frontend-api

---

ci/terraform/account-management/vpc.tf

- The warmers in account management also need access to Lambda API.
The warmers are unable to contact the Lambda API to warm the account management API lambdas, this results in the latter running very slowly.

AUTH-1228: Add Lambda VPC endpoint to account management

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java

We were submitting the previous value of the field, not the updated value.

BAU: Submit current, not previous, values.

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java

- AUTH-1263: Prefer context-based logging in client registry API
- AUTH-1263: Prefer context-based logging in `MfaHandler`

AUTH-1263: Prefer context-based logging (3)

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambda.java
ci/terraform/audit-processors/performance_analysis.tf

This is the base setup to expose performance data to our PAs

AUTH-866: Create skeleton audit consumer for performance analysts

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambdaTest.java

This creates a JSON-shaped object with data for performance and insight analysis

AUTH-866: Log out fields for performance and insight analysis

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/variables.tf

Reverts alphagov/di-authentication-api#1428

Revert "Revert "BAU: add missing notify personalisation in am verify email payload""

---

ci/terraform/account-management/update-email.tf

- Give update email delete permissions

BAU - Give update email delete permissions

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java

Add integration tests for UpdatePhoneNumberHandler
Adds missing test coverage.

AUTH-1169: Add integration tests for UpdatePhoneNumberHandler

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java

Additional test coverage for UpdateEmailHandler
Adds missing test coverage.

AUTH-1169: Additional test coverage for UpdateEmailHandler

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthoriseAccessTokenIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java

- Add integration tests for the AuthorizeAccessTokenHandler
- To increase test coverage

AUTH-1169 - Add integration tests for the AuthorizeAccessTokenHandler

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java

- Print out isAuthenticated in Start lambda
- So we can see if the user is authenticated

BAU - Print out isAuthenticated in Start

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Add additional logging for debugging
- For debugging

BAU - Improve logging

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

BAU: update WAF configuration

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

Update api waf rates.
Additional headroom.

BAU: update api waf rates

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Pull password validation into static method
- We can avoid the need to create an instance of the ValidationService class by using a static method.

AUTH-1480 - Pull password validation into static method

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBItem.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBSchemaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientConsent.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/TermsAndConditions.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserCredentialsTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserProfileTest.java

Reverts alphagov/di-authentication-api#1541

Revert "Revert "AUTH-1397: use DynamoDB transactions for update email""

---

ci/terraform/oidc/variables.tf

- Increase amount of warmers to 20
- To speed up our lambdas

BAU - Increase amount of warmers to 20

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

This signs JWTs with the new hash-based keyid rather than the platform provided name

AUTH-1177: Sign token with new key id

---

account-migrations/build.gradle
frontend-api/build.gradle
oidc-api/build.gradle
shared/build.gradle

Reverts alphagov/di-authentication-api#1563

Revert "BAU - Remove Notify and client reg dependency from OIDC api"

---

delivery-receipts-api/build.gradle

- Remove compile only dependencies
- These are not required

BAU - Remove compile only dependencies

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/testsupport/helpers/SpotQueueAssertionHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/testsupport/matchers/SpotRequestMatcher.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java

- Write SPOT requests to our newly formed SQS queue
- Add tests to check that messages are correctly being written to the queue
- The SPOT payload will change going forward
- We will be passing messages to SPOT via an SQS queue

AUTH-1347 - Write SPOT requests to SQS queue

---

ci/terraform/oidc/alerts.tf

- Enable cloudwatch alerts on the SPOT request DLQ
- So we will receive a slack notification if a message ends up on the DLQ

BAU - Enable cloudwatch alerts on the SPOT request DLQ

---

ci/terraform/account-management/authorizer-warmer.tf
ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/sqs.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/warmer.tf
ci/terraform/oidc/sqs.tf

- Add the `JAVA_TOOLS_OPTIONS` environment variable as discussed in
this article:
https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
To improve cold start times of Java lambdas

BAU: Improve cold start time of Java lambda

---

ci/terraform/oidc/logout-sqs.tf
ci/terraform/oidc/logout.tf

This will create the SQS queue for the back channel message dispatcher to read from.

AUT-241: Create SQS queue for back channel logout messages

---

ci/terraform/shared/stub-rp-clients.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Validate claims are registered with the client
- Add Claims to the Stubs client registry
- When we receive an auth request with claims, ensure that all them claims have been registered with the client

AUT-190 - Validate claims are registered with the client

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IPVStubExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Integrate with IPV user-identity endpoint 
- So we can retrieve user identity information back from IPV

AUT-270 - Integrate with IPV user-identity endpoint

---

ci/terraform/oidc/backchannel-logout-request.tf
ci/terraform/oidc/logout-sqs.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java

Creates a noop lambda (except for logging) to subscribe to the backchannel logout queue
This listener will execute backchannel logout HTTP requests

AUT-241: Subscribe lambda to logout queue

---

ci/terraform/oidc/backchannel-logout-request.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

This PR sends a SignedJWT to the back_channel_logout_uri for a relying party

AUT-241: Send back-channel logout request

---

ci/terraform/oidc/backchannel-logout-request.tf

AUT-241: Set OIDC_API_BASE_URL for handler

---

ci/terraform/modules/lambda-role/role.tf
ci/terraform/modules/lambda-role/variables.tf
ci/terraform/oidc/backchannel-logout-request.tf

It needs this to launch payloads to Relying Parties.

AUT-241: Deploy backchannel-logout-request lambda in default VPC with internet access

---

build.gradle
doc-checking-app-api/build.gradle
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocDocAppAuthorizeHandlerTest.java
settings.gradle

- Create new gradle module which will contain the code for the doc-checking-app code
- Add 2 placeholder lambdas which will return hello world
- So app code is grouped together 
- So there is a starting place for the doc-checking-app lambdas

AUT-304 - Create new module for doc-checking-app

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars

Once this is confirmed to work, we will remove the original

AUT-268: Add second logging endpoint to build/integration

---

ci/terraform/shared/variables.tf

- Add new attributes to stub_rp_clients
- The build is currently failing due to this missing config

AUT-295 - Add new attributes to stub_rp_clients

---

ci/terraform/oidc/api-gateway-frontend.tf

- Add triggers to new doc app authorize endpoint
- So that the endpoint is deployed

AUT-295 - Add triggers to new doc app authorize endpoint

---

build.gradle
integration-tests/build.gradle

- Add v1 of the instrumentor
We use SDK v1 for some APIs
#1744

AUT-330: Add v1 of the Xray instrumentor

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java

We have an error that is possibly caused by closing the segment rather than the subsegment that we just created.

AUT-330: Close subsegment instead of segment

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java

This is a branch that is not currently instrumented

AUT-330: Create subsegment for refresh token creation

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java

This method is designed for resolving asynchronous subsegments.

AUT-330: Do not pass subsegment to `endSubsegment`

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

Does exactly what it says on the tin

AUT-330: Instrument reading and parsing of refresh tokens.

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java

- Remove XRay annotation code
This is causing failures, remove for the time being.
#1773

AUT-345: Remove annotation code

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java

Reverts alphagov/di-authentication-api#1779

Revert "AUT-345: Add XRay Segment annotations"

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java

- Add instrumentation segments around `processLogoutRequest`, `generateDefaultLogoutResponse`, `validateClientIDAgainstClientRegistry` and `isTokenSignatureValid`
There are a few big "gaps" in the X-ray timelines for `logout`, lets see if we can narrow down where the slower operations are.
#1784

AUT-345: Add further XRay subsegments to logout

---

shared/src/main/java/uk/gov/di/authentication/shared/services/RedisConnectionService.java

- Wrap calls to Redis in subsegments
- Use a separate subsegment for getting connection from pool
This will allow us to highlight where Redis is a choke point.

AUT-345: Add instrumentation to RedisConnectionService

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/WarmerHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java

- BAU: Annotate warmer requests in X-Ray so they can be excluded
- BAU: Wrap some JWKS method calls in subsegments for analysis

BAU: Instrument warmers and jwks handler

---

ci/terraform/oidc/ssm.tf

- Set overwrite to true
- Allow terraform to overwrite parameter

AUT-352 - Allow terraform to overwrite parameter

---

ci/terraform/shared/ssm.tf

- Delete ipv-capacity parameter in shared
- This has been moved to OIDC module

BAU - This has now moved to OIDC module

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java

We will keep a mapping of key name in AWS to the EC key created from the key we get back from KMS to reduce the number of lookups and creations.

BAU: Cache creation of public keys to avoid performance hit

---

ci/terraform/oidc/build-overrides.tfvars

- Add doc app config for build
- This will be used to communicate with the Stub CRI

AUT-328 - Add doc app config for build

---

ci/terraform/oidc/staging-overrides.tfvars

- Update IPV encryption key for staging
- It has recently been updated.

BAU - Update IPV encryption key for staging

---

ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Update IPV audience value
- We currently had the audience to include the path of the endpoint which the request was hitting. This is not what IPV were expecting. To fix the journey, change it to what is expected and we can agree what they should be later on

BAU - Update IPV audience value

---

ci/terraform/oidc/staging-overrides.tfvars

- Update doc app details for staging
- We can update the rest when they are known

BAU - Update doc app details for staging

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java

- Add NBF claim to secure Jar
- It is required

BAU - Add NBF claim to secure Jar

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java

Update well known endpoint

---

shared/src/main/java/uk/gov/di/authentication/shared/services/SerializationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java

This will allow us to easily swap in the Gson implementation

BAU: Make `SerialisationService` implement `Json` interface

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

Reverts alphagov/di-authentication-api#1870

Revert "AUT-332: Change sector ID"

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Enable SPOT in Integration and Staging
- So we can start sending messages to SPOT

AUT-381 - Enable SPOT in Integration and Staging

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java

Ignore client_id parameter in token.
- This is an optional parameter, completing the switch over from when it was mandatory.
- Remove our own validation and processing of the parameter, always get the value from the privateJWT.
- Nimbus will still validate that this value matches the one in the privateJWT if it is provided.
Our clients are 'authenticated' so according to the spec client_id is an optional parameter:
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3
#1867

AUT-363: ignore client_id parameter in token

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java

Additional logging for the doc app journey
Fuller view of pathway through the app.

AUT-382: Additional logging for the doc app journey

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java

Add exception to log line

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java

- Log the JSON out
We're just getting a memory address at the moment

BAU: Add decent debug of JSON received from IPV

---

ci/terraform/oidc/spot-sqs.tf

- Increase the visibility on the SPOT request queue rather than DLQ
Correcting an earlier error.

AUT-335: Increase vibility timeout on SPOT request queue

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java

- Break down the User start info test
- Break down the user start info test into smaller tests with less parameters as these were getting pretty large

AUT-384 - Break down the User start info test

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

- Add relevant dependencies for IPV on api-gateway*.tf
- Now that IPV will be deployed in each environment, add the IPV dependencies for the relevant aws_api_gateway_deployment resource
- Currently seeing a cycle error in the deploy-oidc-* jobs

AUT-385 - Add relevant dependencies for IPV on api-gateway*.tf

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Disable IPV in Staging and Integration
- This will make it easier when removing our IPV enabled feature flag.

AUT-385 - Disable IPV in Staging and Integration

---

ci/terraform/oidc/spot-response.tf

- Remove the feature flag from the SPOT response lambda.
- Keep the feature flag on the aws_lambda_event_source_mapping resource, as we haven't yet configured production with the relevant SPOT KMS and SQS queue ARNs.
- So we can start to deploy the SPOT response lambda and relevant policies to every environment.

AUT-385 - Remove feature flag from SPOT response lambda

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/CryptoProviderHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java

We shouldn't do the heavy lifting every time

BAU: Cache creation of BouncyCastleProvider

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java

- BAU: Attach client id to backchannel logout loglines
- BAU: Log out response from request as object message

BAU: Improve logging for backchannel logout

---

build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java

- AUT-412: Add embedded metrics library
- AUT-412: Create `putEmbeddedValue` using EMF
- AUT-412: Use `EMF` to measure backchannel logout response status codes

AUT-412: Spike AWS Embedded Metrics Format for publishing metrics

---

shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java

It's double counting a lot of the time.

AUT-412: Initialise metrics logger on each push

---

ci/terraform/oidc/production-overrides.tfvars

- Add the IPV Auth encryption key for production
- Add the IPV client ID for production
So we're ready to switch on production

BAU: Add IPV config for production

---

ci/terraform/oidc/production-overrides.tfvars

- Configure IPV config for Production
- So we can integrate with IPV in Production

AUT-376 - Configure IPV config for Production

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IdentityClaims.java

Update IPV claim names.
Read both credentialJWT and coreIdentity claims from IPV.

AUT-323: Update IPV claim names

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java

Log IPV response
Temporarily log ipv response so we know exactly what is being returned.

AUT-323: Log IPV response

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/processing-identity.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ProcessingIdentityRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ProcessingIdentityResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ProcessingIdentityStatus.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ProcessingIdentityHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ProcessingIdentityHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java

- This lambda is to let the frontend know the status of the credential and will return one of 3 statuses. COMPLETED, PROCESSING or ERROR.
- COMPLETED will be returned when there is a coreIdentityJWT in dynamo, PROCESSING will be returned when there is an entry in dynamo but no coreIdentityJWT and ERROR will be returned when there is no entry in dynamo.
- The request to SPOT is asynchronous and currently it is taking too long before we put the identity credential received from SPOT into our IdentityCredential database table. Therefore when an RP makes a request to userinfo no identity credential is present.

AUT-432 - Create lambda to be used by spinner

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/production-stub-clients.tfvars
ci/terraform/shared/staging-stub-clients.tfvars
ci/terraform/shared/stub-rp-clients.tf

Reverts alphagov/di-authentication-api#1997

Revert "BAU: Switch off ConsentRequired in stubs"

---

ci/terraform/oidc/integration-overrides.tfvars

- Enable Doc App in integration
- So we can run journeys in Integration

BAU - Enable Doc App in integration

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Add additional logging
- To establish if access tokens are populated with identity claims

BAU - Add additional logging

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java

- Add additional doc app logging for token request
- So we can see the structure of the token request

BAU - Add additional doc app logging for token request

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java

- Add additional logging to doc app callback
- To make it easier to debug the journey

BAU - Add additional logging to doc app callback

---

ci/terraform/oidc/integration-overrides.tfvars

- Add Doc App config for Integration
- So we can integrate with the Doc App service in integration

BAU - Add Doc App config for Integration

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/doc-app-authorize.tf
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/production-overrides.tfvars
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java

Reverts alphagov/di-authentication-api#2151

Revert "AUT-564 - Remove feature flag from Doc App lambdas"

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Renable doc app in build and staging
- To fix pipeline

BAU - Renable doc app in build and staging

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

This generalises the approach used to publish a doc-app-credential metric

BAU: Publish metrics for issued credentials

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambdaTest.java

It's no longer needed so we're minimising the amount of data in the index.

AUT-572: Stop pushing hashed user id to performance index

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/PerformanceAnalysisAuditLambdaTest.java

This isn't needed in the index either

AUT-572: Stop pushing session id to perf index

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java

- Log out state in auth request
- So we can debug an issue

BAU - Log out state in auth request

---

ci/terraform/oidc/production-overrides.tfvars
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java

- Add Doc App Prod Config
- Downgrade log messages from error to warn
- So we can connect to the doc app team in production

AUT-563 - Add Doc App Prod Config

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java

DCA - Redirect to RP with errors.
When the doc check app journey is abandoned or fails return the error back to the RP as per the connecting documentation:
https://docs.sign-in.service.gov.uk/integrate-with-integration-environment/integrate-with-code-flow/#error-handling-for-make-an-authorisation-request
At the moment an exception is being thrown which interrupts the user journey, rather than returning back to the RP.

AUT-543: DCA - Redirect to RP with errors

---

ci/terraform/modules/txma-audit-queue/key.tf

Terraform requires JSON in the policy field

AUT-584: Fix policy attribute by reading as JSON

---

ci/terraform/oidc/audit.tf

We can then cross-test with TxMA.

AUT-584: Deploy TxMA audit queue to staging

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppAuthorisationServiceTest.java

Makes it consistent with the existing IPV journey

AUT-617: Add journey id to doc app request JWTs

---

ci/terraform/oidc/userinfo.tf

Grant the userinfo lambda permission to publish to SQS

AUT-584: Grant send permissions to userinfo lambda

---

ci/terraform/oidc/userinfo.tf

This policy was bugged, removing until tomorrow

AUT-584: Remove broken policy

---

ci/terraform/oidc/audit.tf

Nothing is publishing to them yet, but this will simplify the Terraform

AUT-584: Deploy audit queues into all environments

---

ci/terraform/oidc/userinfo.tf

AUT-584: No need for conditional now that every environment has the queues

---

ci/terraform/modules/txma-audit-queue/output.tf
ci/terraform/modules/txma-audit-queue/policy.tf
ci/terraform/oidc/userinfo.tf

- AUT-584: Create and expose access policy ARN for consumers
- AUT-584: Attach access policy to userinfo lambda

AUT-584: Create SQS access policy and attach to userinfo lambda

---

ci/terraform/modules/txma-audit-queue/key.tf
ci/terraform/modules/txma-audit-queue/output.tf
ci/terraform/modules/txma-audit-queue/policy.tf
ci/terraform/modules/txma-audit-queue/queue.tf
ci/terraform/modules/txma-audit-queue/variables.tf
ci/terraform/oidc/audit.tf
ci/terraform/oidc/userinfo.tf

- AUT-584: Allow lambdas to encrypt the payload on the queue
- AUT-584: Enable TxMA audit in staging

AUT-584: Grant KMS permissions to lambda and enable in staging

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml

AUT-584: Put variable in wrong template

---

ci/terraform/shared/grafana-read-only-role.tf

We creatd the role but didn't attach the policies

BAU: Attach permissions to grafana role in staging

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java

Enrich audit events for UpdateProfile errors.
For errors in UpdateProfileHandler include:
- session id
- client id
- email
- persistent session id
in the audit event.
Not much information was being provided even though it is available.

AUT-580: Enrich audit events for UpdateProfile errors

---

ci/terraform/account-management/audit.tf
ci/terraform/account-management/authenticate.tf
ci/terraform/account-management/outputs.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf

* Trying to debug permissions issues with the existing queue

AUT-584: Use alternate TxMA queue in account management

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/entity/DocAppCredential.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

- Uplift Doc app credential table to Dynamo sdkv2
- So we can take advantage of the latest features and move away from AWS sdk version 1

AUT-398 - Uplift Doc app credential table to Dynamo sdkv2

---

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IdentityCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Uplift Identity credential table to Dynamo sdkv2
- So we move away from version1 of the SDK and take advantage of some of the latest features

AUT-398 - Uplift Identity credential table to Dynamo sdkv2

---

client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java

We were previously discarding them

BAU: Update claims for client config update endpoint

---

ci/terraform/account-management/build-overrides.tfvars
ci/terraform/account-management/integration-overrides.tfvars
ci/terraform/account-management/production-overrides.tfvars
ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/audit-processors/build-overrides.tfvars
ci/terraform/audit-processors/integration-overrides.tfvars
ci/terraform/audit-processors/production-overrides.tfvars
ci/terraform/audit-processors/staging-overrides.tfvars
ci/terraform/delivery-receipts/integration-overrides.tfvars
ci/terraform/delivery-receipts/production-overrides.tfvars
ci/terraform/delivery-receipts/staging-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/utils/build-overrides.tfvars
ci/terraform/utils/integration-overrides.tfvars
ci/terraform/utils/production-overrides.tfvars
ci/terraform/utils/staging-overrides.tfvars

BAU: Add logging_endpoint_arn overrides for all environments

---

ci/terraform/shared/production-sizing.tfvars

Reverts alphagov/di-authentication-api#2413

Revert "BAU: Toggle User Profile table streaming on"

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- BAU: Pass signing algorithm to `generateSignedJWT`
- BAU: Instruct TokenService to sign with specific signing algorithm

BAU: `TokenHandler` instructs `TokenService` with signing algorithm

---

ci/terraform/oidc/token.tf

This was missed in the previous PR

BAU: Grant /token access to RSA signing key

---

ci/terraform/oidc/logout.tf
ci/terraform/oidc/userinfo.tf

They need to check signatures of tokens passed in

BAU: Grant logout and userinfo endpoints read access to RSA signing key

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java

Use shared method to check for test client email in SendNotificationHandler
Messages were not being suppressed for regex format emails on the test client allowlist as the regex check was not included in the local method.
#2656

AUT-783: Use shared method to check for test client email in SendNotificationHandler

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-oidc-api.yml
ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/build-overrides.tfvars
ci/terraform/account-management/integration-overrides.tfvars
ci/terraform/account-management/localstack.tfvars
ci/terraform/account-management/production-overrides.tfvars
ci/terraform/account-management/s3-objects.tf
ci/terraform/account-management/sandpit.tfvars
ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/account-management/variables.tf
ci/terraform/delivery-receipts/variables.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/localstack.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/s3-objects.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/localstack.tfvars
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf

- Remove rest of lambda warmer terraform
- The lambdas are not dependent on any of warmers so we can remove the rest of the warmer terraform.

AUT-1010 - Remove rest of lambda warmer terraform

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/site.tf
ci/terraform/oidc/ssm.tf

Reverts alphagov/di-authentication-api#2735

Revert "AUT-834: WAF rules exception for the smoke test client"

---

ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

Reverts alphagov/di-authentication-api#2746

Revert "AUT-938: Point staging at One Login rename templates in prod Notify account"

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Disable Client Reg api in build and staging

BAU - Disable Client Reg api in build and staging

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf

Put an API key in front of non-prod client registry

BAU: Deploy API key for client registry

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

Reverts alphagov/di-authentication-api#2770

Revert "BAU - Disable Client Reg api in build and staging"

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

Log non-mobile phone type and country code for non-mobile validation errors.
Help understand why non-mobile phone type validation errors are happening.
#2776

BAU: Log non-mobile phone type and country code for non-mobile validation errors

---

ci/terraform/oidc/api-gateway-frontend.tf

- Increase the rate based limit for our Frontend API to 7200

BAU - Increase rate based limit from 3600 to 7200

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java

- Put PASSWORD_RESET_CONFIRMATION_SMS notify type on queue if applicable
- If a user has a verified phone number on record, then we will send the user a reset password confirmation SMS to their registered phone number

AUT-1079 - Put PASSWORD_RESET_CONFIRMATION_SMS on queue if applicable

---

.github/workflows/sonar-analysis-on-merge.yml

Update adopt to temurin in sonarqbue workflow.
File didn't get saved in original change.

Update adopt to temurin in sonarqbue workflow

---

.github/workflows/build-api-modules.yml

Waits for signing job to complete.
We should not continue until this has been finished.

Add wait command for signing job

---

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Switch reset password SMS on for Production

AUT-1079 - Switch reset password SMS on for Production

---

ci/terraform/shared/dynamodb.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountRecoveryBlock.java

- Create Account Recovery Block table
- This will be required for checking whether someone is permitted to perform account recovery or not

AUT-1155 - Create Account Recovery Block table

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml
ci/tasks/deploy-delivery-receipts-api.yml
ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml
ci/tasks/deploy-test-services.yml
ci/tasks/deploy-utils.yml

Add code to use state locking table in build, 
could add other environments later
Supporting dev platform work on terraform support.

Add code to use state locking table in build, 

---

ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Enable DCMAW error handling in Prod and Staging
- This will be ready for Production once we have received confirmation that testing in Integration was successful

BAU - Enable DCMAW error handling in Prod and Staging

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java

- Only add block if block does not already exist
- If a block already exists, then ensure that we don't add another block to the email. Otherwise the duration will keep extending rather than be fixed at 15 mins

AUT-1205 - Only add block if block does not already exist

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

- Remove VERIFY_PHONE_NUMBER support from VerifyCodeHandler
- The validation of the VERIFY_PHONE_NUMBER notificationType has been ported to the VerifyMfaCodeHandler

AUT-1208 - Remove VERIFY_PHONE_NUMBER support from VerifyCodeHandler

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidClaims.java

Adds missing data to well-known endpoint. This comes from a discussion with the adoption / onboarding team

BAU: Add missing data to well-known endpoint

---

ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf
ci/terraform/utils/variables.tf

The privacy policy has updated.

BAU: Bump Ts&Cs version to reflect new privacy policy

---

ci/terraform/oidc/production-overrides.tfvars

- Enable cross-browser solution for all RPs in Production
- We do not need to wait for IPV changes so we can go ahead and release this

AUT-1216 - Enable crossbrowser solution for all RPs in Production

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java

- Check if either SMS or Auth App is verified
- To improve the code readability

BAU - Check if either SMS or Auth App is verified

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Update userprofile in a one dynamo call from VerifyMfaCode
- Rather than making multiple calls to update the phone number and then update the verify status, we can update it all in a single call

AUT-1207 - Update userprofile in a one dynamo call

---

shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Use TransactWriteItems for updating phone number and verification status
- We are seeing via DynamoStreams that these attribute look to be updated concurrently rather than at the same time

AUT-1207 - Use TransactWriteItems for updating phone number and verification status

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

Enable this feature in all environments.

BAU: Enable Session IDs on all ID tokens

---

account-management-api/docs/account-management-api.md

Updated the content of the account management API after tech writer review.
Review was done https://docs.google.com/document/d/1k6ygRi5yevIBtxm1UQiwUzhO0FSkSAkFDrt-6gFA7DE/edit#

Updated account management API documentation

---

ci/terraform/modules/endpoint-module/lambda.tf

Only add Dynatrace vars if deploy_dynatrace is true

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/BaseDynamoService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAccountModifiersService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

This PR creates a base Dynamo class to wrap the AWS SDK, and uses this as a subclass in existing dynamo services to remove duplicated setup code.

BAU: Refactor Dynamo services

---

ci/terraform/oidc/userexists.tf

AUT-1183 - Add policy to end of list

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java

- Add RPPairwiseId to AUTH_CREATE_ACCOUNT audit event in the SignUp handler
- Required for auditing purposes

AUT-1183 - Add RPPairwiseId to AUTH_CREATE_ACCOUNT audit event

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java

- Add RP pairwise ID to AUTH_AUTH_CODE_ISSUED audit event
- Change the HTTP status of error responses from 200 to either 400 or 500.
- For auditing purposes 
- We were previously sending all error responses back to the frontend with a HTTP status of 200. These should either be 400 for client errors or 500 for unexpected server errors

AUT-1183 - Add RP pairwise ID to AUTH_AUTH_CODE_ISSUED audit event

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java

- Improve code request logging
- To make it easier to debug issues

BAU - Improve code request logging

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/LocaleHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java

Remove unnecessary log noise related to localisation.
The logging would only be useful when diagnosing an issue so is being downgraded to 'trace' or deleted.

BAU: Remove unnecessary log noise related to localisation

---

.github/workflows/deploy-account-managment-dev.yml
.github/workflows/deploy-delivery-receipts-dev.yml
.github/workflows/deploy-oidc-dev.yml
.github/workflows/deploy-test-services-dev.yml
ci/terraform/audit-processors/storage.tf
ci/terraform/delivery-receipts/dev.tfvars

- Fix for a few misconfigurations in dev env
- Added conditional statement to terraform to fix "existing bucket name" error
- These are adjustments to fully automate dev deployment

[Plat 1624] Adjust configuration for dev

---

.github/workflows/deploy-account-managment-dev.yml
.github/workflows/deploy-shared-dev.yml

- Changed zipped artifact's name to follow the same naming convention
- This will facilitate promotion logic
https://github.com/alphagov/di-infrastructure/pull/533

[PLAT-1664] Changed artifact name for promotion convention

---

ci/terraform/oidc/authorize.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf

Reverts alphagov/di-authentication-api#3070

Revert "AUT-1248: Initial terraform to set KMS signing key policy for auth handler"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java

Reverts alphagov/di-authentication-api#2930

Revert "AUT-1210: 'Double count' MFA code blocks"

---

ci/terraform/audit-processors/production-overrides.tfvars
ci/terraform/shared/staging-overrides.tfvars
ci/terraform/test-services/staging-overrides.tfvars
ci/terraform/utils/staging-overrides.tfvars

Fix typo in shared_state_bucket

---

.github/workflows/deploy-account-managment.yml
.github/workflows/deploy-audit-processors.yml
.github/workflows/deploy-delivery-receipts.yml
.github/workflows/deploy-oidc.yml
.github/workflows/deploy-shared.yml
.github/workflows/deploy-test-services.yml
.github/workflows/deploy-utils.yml

Add missing provenance metadata

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java

Reverts alphagov/di-authentication-api#3105

Revert "AUT-1349: Replace ATTEMPTS block with new code block prefix"

---

ci/terraform/account-management/staging-overrides.tfvars

Making a note to actually consolidate all the tfvars files at some point...

Add internal_sector_uri to staging-overrides.tfvars

---

shared/src/main/java/uk/gov/di/authentication/shared/services/NoSessionOrchestrationService.java

- Add null safety check in no session orch service
- NullPointerException was observed in production logs emanating from this line

BAU: Add null safety check in no session orch service

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java

Add log info to debug Password Reset code block

AUT-1274: Add logging to confirm OTP block is being validated during Password Reset journey

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java

This is a second PR to remove the old code block prefix for SIGN IN journey as the Redis cache should now be up to date with the new code block prefix.
The first change, which introduces the new code block prefix for MFA_SMS during Sign In
(https://github.com/alphagov/di-authentication-api/pull/3166)

AUT-1433-Part-2: Remove old SIGN IN code block prefix

---

ci/terraform/shared/kms.tf

Enable DynamoDB to use customer managed key for table encryption
This commit adds the necessary permissions to allow DynamoDB to use a customer managed KMS key for protecting AuthCodeStore DDB table. The KMS key permissions are granted to the principal making the selection. The permissions are provided through a key policy. 
[Creation of AuthCodeStore table](https://github.com/alphagov/di-authentication-api/pull/3194)

BAU: Enable AuthCodeStore DDB table to use customer managed key for table encryption

---

ci/terraform/shared/kms.tf

ENCRYPT_DECRYPT instead of SIGN_VERIFY
Key needs to be a symmetric encryption key!

ENCRYPT_DECRYPT instead of SIGN_VERIFY

---

build.gradle

- Exclude shared-test directory from Sonar code coverage
- Make small correction to syntax

BAU - Exclude shared-test directory from Sonar code coverage

---

ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf
ci/terraform/utils/variables.tf

⚠️ Do not merge before go live date (See Jira for details) ⚠️
Updates `terms_and_conditions` version
To reflect change to privacy notice coinciding with the introduction of Biometric Residence Cards (BRCs) and Frontier Worker Permits (FWPs) to the document checking journey
* https://github.com/alphagov/di-authentication-frontend/pull/1125 Updates the privacy notice

⚠️ Do not merge before go-live date ⚠️ AUT-1493: Update terms_and_conditions version

---

utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java
utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java

Only audit internal subject id if salt exists.
Calculating the internal subject id would usually create a salt for users not having one.  As we don't want to update the user-profile table only send the internal subject id to audit if the salt already exists.

AUT-1526: Only audit internal subject id if salt exists

---

ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf
ci/terraform/utils/variables.tf

Update to terms and conditions version following an [update to the privacy notice](https://github.com/alphagov/di-authentication-frontend/pull/1130).
Requires [PR to update the content](https://github.com/alphagov/di-authentication-frontend/pull/1130) to be merged first

AUT-1632: Update terms and conditions version

---

scripts/account-metrics.sh

Script to count verified accounts on a specific terms and conditions version.
Will be used to validate that the bulk email load job is loading the correct number of users.

AUT-1631: Script to count verified accounts on a specific terms and conditions version

---

ci/terraform/oidc/build.tfvars
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars
ci/terraform/oidc/staging.tfvars

- Remove redundant overrides
- This terraform variable no longer exists in the OIDC module

AUT-1645 - Remove redundant overrides

---

oidc-api/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

Reverts alphagov/di-authentication-api#3305

Revert "AUT-1253: orches modify userinfo and token endpoint"

---

.github/workflows/pre-merge-checks.yml

Reverts alphagov/di-authentication-api#3316

Revert "BAU - Exclude terraform changes from running the pre-merge checks"

---

ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf
ci/terraform/utils/variables.tf

Uplift terms and conditions version to 1.9
New version corresponds to content changes made to the privacy notice, see PR below.
https://github.com/alphagov/di-authentication-frontend/pull/1136

AUT-1634: DO NOT MERGE UNTIL WED 13 SEP 23: Uplift terms and conditions version to 1.9

---

ci/terraform/utils/production-overrides.tfvars

**Only merge once Notify incident is confirmed as fully resolved**

AUT-1472: Configure batches of emails to be sent between 11:00 - 12:00 BST on 23/09/2023

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Create new feature flag for enabling DOC APP decoupling in regards to Doc App callback and handoff

AUT-1746: Create new feature flag for DOC APP decoupling

---

ci/terraform/modules/endpoint-module/dynatrace.tf
ci/terraform/modules/endpoint-module/lambda.tf

Changes Dynatrace secrets to use the Observability secrets.
A few changes to fit in with recent learnings.
It is not in production, but this could be changed later!
Authentication Lambdas will be observed within Dynatrace with this.

Update Dynatrace integration to reflect changes upstream

---

ci/terraform/shared/code-signing-config.tf

Update the signing profile used by the DT lambda layer.
It changed since last time, and I forgot to update it, oops.

Update the signing profile used by the DT lambda layer

---

ci/terraform/modules/endpoint-module/lambda.tf

Remove DT from integration

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthRequestError.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RequestObjectService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java

This PR gives a bit of love to our `RequestObjectService`.
Reviewers are recommended to review each commit in isolation.

BAU: Refactor `RequestObjectService`

---

scripts/check-user-account.sh

Script to retrieve user information from user-profile.
- Requires access rights to the account and table being queried.
- Requires gds cli v5.70.1 (the exact version, not higher).
For when a record is required of user-profile information, or to see if a user acccount exists.

AUT-1808: Script to retrieve user information from user-profile

---

ci/terraform/modules/endpoint-module/lambda.tf

Deploy Dynatrace in all environments.
Tested in all environments except production.

Deploy Dynatrace in all environments

---

ci/terraform/delivery-receipts/notify-callback.tf
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Reverts alphagov/di-authentication-api#3459
Causes NPE.
`Cannot invoke "uk.gov.di.authentication.shared.services.SystemService.getOrDefault(Object, String)" because "this.systemService" is null: java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "uk.gov.di.authentication.shared.services.SystemService.getOrDefault(Object, String)" because "this.systemService" is null`

Revert "AUT-1467: Bulk Email switch for delivery receipts lambda"

---

build.gradle

Update Sonar organisation
The repository has been moved to a new organisation in Sonar

BAU: Update Sonar organisation

---

.github/CODEOWNERS
CODEOWNERS

Update CODEOWNERS for new org.
Team names have changed in the new org.

BAU: Update CODEOWNERS for new org

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java

Updating a log to the correct string

ATO-NONE: Fix email scope log in constructAdditionalAuthenticationClaims

---

ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf
ci/terraform/utils/variables.tf

DO NOT MERGE BEFORE 30 October
Reflecting a change in the privacy statement
Reflects update to the privacy statement.
Reflects launch of the contact centre
[Frontend change](https://github.com/alphagov/di-authentication-frontend/pull/1185)

AUT-1721: Uplift terms and conditions version number

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java

Add the nonce to AUTH_CODE_ISSUED logs
This is a HMRC requirement

ATO-93 add nonce to audit logs

---

.github/workflows/pre-merge-checks.yml

Run the two sets of integration tests in parallel to reduce time to production

BAU: split integration tests

---

.github/workflows/pre-merge-checks.yml
docker-compose.yml
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java

Upgrade the version of localstack used for integration tests
To take advantage of the bug fixes and performance improvments

BAU: Upgrade localstack

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java

Include the vtr in the JAR sent to IPV Core.
As we start to support additional levels of confidence, IPV will need to change their behaviour.

ATO-182: Pass vtr through IPV authorize request

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java

Accept a list of values in the vtr parameter for request object
At the moment, the vtr expects a string, and throws an error if you pass in a list (the expected format)

ATO-202: Accept list in vtr

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
ipv-api/src/test/resources/uk/gov/di/authentication/ipv/services/approvals/IPVAuthorisationServiceTest.shouldConstructASignedRequestJWT.approved.json
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java

IPV Core do not currently read this claim, so we are free to change it

BAU: Use spec compliant format for userinfo claims requests

---

ci/terraform/interventions-api-stub/interventions-api-stub-gateway.tf
ci/terraform/interventions-api-stub/lambda.tf
ci/terraform/modules/stub-endpoint-module/account.tf
ci/terraform/modules/stub-endpoint-module/alerts.tf
ci/terraform/modules/stub-endpoint-module/dynatrace.tf
ci/terraform/modules/stub-endpoint-module/lambda.tf
ci/terraform/modules/stub-endpoint-module/outputs.tf
ci/terraform/modules/stub-endpoint-module/variables.tf
deploy-sandpit.sh
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/services/AccountInterventionsDbServiceIntegrationTest.java
interventions-api-stub/build.gradle
interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/entity/AccountInterventionsStore.java
interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/entity/InterventionsApiStubResponse.java
interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandler.java
interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/services/AccountInterventionsDbService.java
interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandlerTest.java
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubStoreExtension.java

Aut 1865/add stub logic

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

We should not redirect to any url not configured in the client registry.
See https://datatracker.ietf.org/doc/html/rfc6749#section-10.15

ATO-209: Prevent open redirector

---

ci/terraform/oidc/identity-progress.tf

Fix reference to IdentityProgressFrontendHandler
Was not referencing lambda correctly

ATO-NONE: Refer to the correct handler name

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/identity-progress.tf
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java

A few small fixes to identity progress handler - adding better logging, making sure api gateway redeploys automatically on changes, adding kms key encryption policy
To allow the orch frontend to connect to the backend, and make debugging easier
https://github.com/govuk-one-login/orchestration-frontend/pull/67

ATO-145: Identity progress fixes

---

ci/terraform/interventions-api-stub/sandpit.hcl
ci/terraform/interventions-api-stub/site.tf

Fix interventions api stub tf

---

ci/terraform/auth-external-api/build.tfvars

Previous value was for sandpit

ATO-219: Set correct public key

---

orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ValidClaimsTest.java

ATO-132: Fix supported claims

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java

The changes have been made to reflect the specification of the US 2024.

Aut 2024/password reset attempts

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java

Set authenticated to true when login succeeds
Otherwise seamless login will not work.

ATO-221: Set authenticated when users sign in and auth/orch split enabled

---

ci/terraform/oidc/api-gateway.tf

Remove a waf rule blocking localhost requests for sandpit
To run a local instance of the rp stub against sandpit, we need to remove this rule

BAU: Remove waf rule for sandpit blocking requests from localhost

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java

Added metadata pair for old email address to reflect the changes requested in AUT 2043

Added Metadata pair for old email address.

---

ci/terraform/oidc/build-overrides.tfvars

Reverts govuk-one-login/authentication-api#3704

Revert "ATO-66: Turn on doc app decouple"

---

ci/terraform/oidc/api-gateway.tf

Add override for long query params in waf config
Request objects are starting to go over the waf maximum length - adding an override for the authorize endpoint only to let these long queries go through. Logic copied from below PR on auth frontend
https://github.com/govuk-one-login/authentication-frontend/pull/1217

ATO-208: Add an override for long query params for authorize endpoint

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

…ged in (password reset)
enhance verify code handler to retrieve subject identifier when user is not logged in (MFA password reset)
During integration of the backend MFA password reset backend changes in with the frontend changes we identified an issue where the subjectidentifier was not set as this is always set by the startservice when a user is logged in. We need this information for users that are going through MFA for password reset (not logged in yet).

AUT-2139 enhance verify code endpoint for SMS MFA PW reset journey

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthExternalApiStubExtension.java

Emit cloudwatch signin metrics on successful signin
These are used in several dashboards. We should keep them accurate post-split

ATO-222: Emit cloudwatch signin metrics on successful signin

---

ci/terraform/oidc/build-overrides.tfvars

Final step of enabling split in build

AUT-1764: Enable userinfo split in build

---

ci/terraform/oidc/staging.tfvars

Step 1 of 7 to enable phase 1 split in staging: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-64: Networking prereqs for docapp decouple in staging

---

ci/terraform/oidc/staging-overrides.tfvars

enable docapp decouple in staging
2/7 of enabling split in staging

ATO-64: docapp decouple in staging

---

interventions-api-stub/src/main/resources/log4j2.xml

Add log4j config for the interventions stub api.
The config is currently missing so nothing is being logged.

AUT-1847: Add log4j config for the interventions stub api

---

ci/terraform/auth-external-api/staging.tfvars

Step 4/7 enabling staging split: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

AUT-1762: Enable split in staging auth external API

---

ci/terraform/oidc/staging-overrides.tfvars

5/7 phase 1 staging split https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

AUT-1762: Enable split in staging except for userinfo

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java

This happens in the return code flow. Currently throws null pointer exception

ATO-134: handle missing or null core identity from IPV

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/LogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/LogoutServiceTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/CloudwatchMetricDimensions.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java

Revert changes from https://github.com/govuk-one-login/authentication-api/pull/3741
Causing deployment failure

ATO-171: Revert

---

ci/terraform/oidc/integration.tfvars

Step 1 of auth/orch split https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-257: Move authorize lambda to protected subnet in integration

---

ci/terraform/oidc/integration-overrides.tfvars

Step 2 of auth/orch split https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-257: Enable docapp decouple in integration

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java

Before this change, only escaped claims requests were accepted from JARs, like 
```
"claims": "{\"https:\\/\\/vocab.account.gov.uk\\/v1\\/passport\":{\"essential\":true},\"https:\\/\\/vocab.account.gov.uk\\/v1\\/coreIdentityJWT\":{\"essential\":true},\"https:\\/\\/vocab.account.gov.uk\\/v1\\/address\":{\"essential\":true}}"
```
After this change, JSON object are also accepted
OIDC spec compliance, and this is what HMRC are trying to do

ATO-263: support both string escaped and full json objects in JAR claims requests

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java

ATO-176: Add logging to debug AIS stub

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java

This reverts commit 3d8534b3682bf5e24b535fa66d15aa97d8576251.

Revert "ATO-176: Add logging to debug AIS stub"

---

ci/terraform/oidc/integration-overrides.tfvars

Step 7 of auth/orch split https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-257: Enable split for userinfo in integration

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java

New Metadata pairs on audit events have been added in order to comply with new HRMC requirements for more details please have a look at https://govukverify.atlassian.net/browse/AUT-2023
There are multiple user stories included in this PR, those that need to be checked have the status "In review" under the 2023 US

AUT-2023: Add metadata pairs to multiple audit events

---

ci/terraform/oidc/ipv-handoff-alerts.tf

Add a metric for ipv handoff errors after split
So we know if ipv handoff is failing after the auth/orch split

ATO-271: Add new metric for ipv handoff errors post split

---

ci/terraform/oidc/production.tfvars

Step 1 of auth orch split in prod: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-255: Production split 1

---

ci/terraform/oidc/production-overrides.tfvars

Step 2 of auth orch split in production: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-255: Production split 2

---

ci/terraform/auth-external-api/production.tfvars

Step 4 of the auth orch split in production: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-255: Production split 4

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

Increase WAF rate limits.
Provide an uplift in capacity.

BAU: Increase WAF rate limits

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

Reverts govuk-one-login/authentication-api#3844

Revert "BAU: Increase WAF rate limits"

---

ci/terraform/oidc/production-overrides.tfvars

Step 5 of the auth orch split in production: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-255: Production split 5

---

ci/terraform/oidc/production-overrides.tfvars

Step 7 of the auth orch split in production: https://govukverify.atlassian.net/wiki/spaces/Orch/pages/3872751749/Go+Live+Plan

ATO-255: Production split 7

---

ci/terraform/oidc/production-overrides.tfvars

Follow up manual actions to revert step 5 with code change

ATO-255: revert step 5 and cancel step of auth orch split

---

ci/terraform/oidc/production-overrides.tfvars

Step 5 of the auth orch split in production
(cherry picked from commit 97e4e31bf6b37edf61e176cb2a12715a0a507442)

ATO-255: enable the auth orch split for all except userinfo

---

ci/terraform/oidc/production-overrides.tfvars

Step 7 of the auth orch split in production
(cherry picked from commit b6a4fe5cf362cf9e2d10f1ccbfc1871758416156)

ATO-255: enable the auth orch split for userinfo

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/production-stub-clients.tfvars
ci/terraform/shared/staging-stub-clients.tfvars

Add the new stubs as relying parties
So that we can complete a full journey

ATO-159: Set up stubs as new relying parties

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DynamoServiceTest.java

- Deal with mapping error for if the session email is null
- Remove unused context parameters

ATO-213: Logout error handling

---

ci/terraform/oidc/api-gateway-frontend.tf

Build fix: fix to WAF rate limit
Build fix

fix to WAF rate limit

---

ci/terraform/oidc/api-gateway-frontend.tf

AUT-2307 new rate limit of prod for API waf 
Context https://govukverify.atlassian.net/wiki/spaces/COREVERIFY/pages/3921051794/Auth+team+mitigation+to+Veterans+RP+launch+risk+on+28th+Jan

Set new rate  limit on front API waf rule

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthenticateIntegrationTest.java

Added a new audit event for failed logins as required in AUT-2042

AUT-2042 adding new audit event for account management

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java

This allows users to be redirected to the RP when returning after having switched browser

ATO-341: Store client session ID against IPV Core state

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/InvalidRedirectUriException.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/TokenAuthUnsupportedMethodException.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/ClientSecretPostClientAuthValidator.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactory.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactoryTest.java

Client secret post looks logically sound so only refactoring
Refactor to make more readable

ATO-313: Review client secret post

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/entity/UserMfaDetail.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java

Reverts govuk-one-login/authentication-api#3799

Revert "add part phone number to user exists api"

---

ci/terraform/account-management/s3-objects.tf
ci/terraform/delivery-receipts/s3-objects.tf
ci/terraform/shared/s3.tf
ci/terraform/test-services/s3.tf
ci/terraform/utils/bulk_test_user_s3.tf
ci/terraform/utils/common_passwords_update_s3.tf
ci/terraform/utils/source_code_s3.tf

Added Public block to S3 bucket
Old bucket which were created before the public Block setting was enabled at account setting are getting flagged in CPC finding as Public block missing

AUT-2260 Added Public block S3 bucket

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java
shared/src/main/java/uk/gov/di/authentication/entity/Environment.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Log AIS response in test environments (configurable).
Provide visibility on the application behaviour in test environments.

AUT-1844: Log AIS response in test environments (configurable)

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java

Add some logging to the auth auth code handler
We've seen some of these errors, but have no details to investigate

BAU: Log error in auth auth code handler

---

ci/terraform/oidc/authorize.tf
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Removed doc app feature flag.
Flag is now redundant as it is effectively always enabled.

ATO-69: Removed Doc App Feature Flag

---

ci/stack-orchestration/README.md
ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/build/github-identity/parameters.json
ci/stack-orchestration/configuration/build/signer/parameters.json
ci/stack-orchestration/configuration/build/tags.json
ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/staging/tags.json
ci/stack-orchestration/provision_all.sh

New secure pipelines for orch backend.
Required for phase 3 of Orch/Orch split
[ATO-321](https://govukverify.atlassian.net/jira/software/c/projects/ATO/boards/390?selectedIssue=ATO-321)
[ATO-321]: https://govukverify.atlassian.net/browse/ATO-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATO-318: Provision Standard Dev Platform Stacks Into New Accounts

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/conditions/IdentityHelper.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/conditions/MfaHelper.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSessionService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/VectorOfTrustTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSessionServiceTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ClientSessionServiceTest.java

Return vtrList when parsing auth request
to handle multi-valued vtr
https://github.com/govuk-one-login/authentication-api/pull/3887
https://github.com/govuk-one-login/authentication-api/pull/3889

ATO-251: Return vtr list

---

ci/terraform/oidc/build-overrides.tfvars

This reverts commit db558275bba478bc6529c42b6039503e46b5e394.

Revert "BAU: Point build at the new DCMAW stub"

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java

Redirect to auth frontend in all environments 
To allow acceptance tests to pass in build

BAU: simplify account intervention redirect logic

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java

Add additional logging to the LoginHandler.
To have more granular logging of journeys.

AUT-2319: Add additional logging to the LoginHandler

---

ci/terraform/shared/build-stub-clients.tfvars

Add acceptance test client for new stub

ATO-383: Add acceptance test client

---

ci/terraform/modules/txma-audit-queue/queue.tf

Update queue configuration for all audit queues
Requested by TxMA

ATO-380: Update TxMA queue configuration to add 6 min visibility timeout

---

.github/workflows/build-api-modules.yml

Delete remaining audit processor workflow
Missed originally
https://github.com/govuk-one-login/authentication-api/pull/3909

BAU: Remove audit processors build workflow

---

.github/workflows/sonar-analysis-on-merge.yml

Apply changes from https://github.com/govuk-one-login/authentication-api/pull/3988 to main branch analysis

BAU: fix sonar analysis on main branch

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java

Adding metada pairs for journey type to audit events as per AUT 2433

Aut 2433/adding metadata pair journey type in audit events

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvUserIdentityTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

Update Pact requests 
Update states within pact test
Update Consumer and Provider name
Refactor pact test to call through service and test api call there
- there will be some work to pull out more logic from the lambda into service to create more pact tests
To unblock IPV

Update IPV contract test to build out the request fully

---

template.yaml

Add code signing to SAM template
This is causing Lambda to fail to deploy.

ATO-320: Add code signing to template

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Ask Auth for email in Identity flows
Face to face needs email address

ATO-420: Always fetch email from auth in ID flows

---

scripts/set-up-sso.py

This change makes it so that the `set-up-sso.py` script will not add
production account profiles to the AWS config file unless the
`INCLUDE_PROD` environment variable is set to `YES I AM SURE`.
This is to prevent accidental operations on production accounts.
Additionally, don't shell out to the AWS cli, instead use boto3 to create an OIDC session. This means we don't have to pull stuff out of arbitrary files, which is nice!
1. Run `scripts/set-up-sso.py`:
observe warnings that prod account profiles were not created
1. Confirm they do not exist in `~/.aws/config`
1. Run `INCLUDE_PROD="YES I AM SURE" scripts/set-up-sso.py`:
Observe that prod account profiles are logged as being added
1. Confirm they exist in `~/.aws/config`
1. Run `scripts/set-up-sso.py`:
Observe that prod account profiles …

AUT-2485: Skip prod config by default

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactory.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactoryTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/TokenClientAuthValidatorFactory.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/TokenClientAuthValidatorFactoryTest.java

Enable client secret post in all environments
We need to get this ready for fisheries, and have just got approval

ATO-422: Enable client secret post in all environments

---

ci/terraform/oidc/authentication-callback.tf
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCapacityHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
ipv-api/src/test/resources/uk/gov/di/authentication/ipv/services/approvals/IPVAuthorisationServiceTest.SignedJwtRequest.shouldConstructASignedRequestJWT.approved.json
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/HandlerIntegrationTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java

Reverts govuk-one-login/authentication-api#4057

Revert "ATO-95: Add storageAccessToken claim to JAR sent to IPV"

---

template.yaml

Implement Snapstart for new lambda
To reduce cold start time

ATO-419: Implement Snapstart

---

ci/terraform/shared/authdev1.tfvars
ci/terraform/shared/authdev2.tfvars
ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/dev-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/localstack.tfvars
ci/terraform/shared/production-stub-clients.tfvars
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/staging-stub-clients.tfvars

Reverts govuk-one-login/authentication-api#4085

Revert "ATO-404: Remove client registry entries for old stub"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java

Reverts govuk-one-login/authentication-api#4049

Revert "AUT-2480: separate 15min lockout for sms code entry during registration and 2fa account recovery"

---

integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

Integration test update was required as a result of conflicts between 2 PRs that were merged on the same day. The build was still deployed and the error was not picked up until pulling the main code

AUT-2543: test fix after merge conflicts

---

.github/dependabot.yml
.github/workflows/pre-merge-checks-python.yaml
pyproject.toml
requirements.dev.txt
scripts/_set-up-sso.py
scripts/_set_up_sso.py
scripts/set-up-sso.sh

Retry when attempting to fetch roles and accounts.
If you have lots of accounts, there can be too many requests to AWS, so errors occur. Instead, use botocore retry config to handle these
better.

AUT-2485: Enable retries for SSO Client

---

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/build/vpc/parameters.json
ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/staging/vpc/parameters.json
template.yaml

- Update Sam Template
- Order parameters.json alphabetically
See [here](https://github.com/govuk-one-login/observability-infrastructure/blob/main/lambdalayer/README.md#prerequisites) for additional info.

ATO-323: Integrate dynatrace

---

template.yaml

- Configure invoke permission on new lambda
- Rename Wellknown lambda to OpenIdConfiguration

ATO-326: Configure invoke permission on new lambda

---

template.yaml

- Set Lambda permissions per environment
- Remove APIGateway from lambda

ATO-326: Configure invoke permission on new lambda 

---

template.yaml

ATO-326: Fix SourceArn

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/oidc/wellknown.tf

- Configure old ApiGateway with new Lambda
- Enabled orch_backend_api_gateway_integration_enabled in sandpit
Ensure this only effect sandpit (feature flags are correct).

ATO-327: Configure old ApiGateway with new Lambda

---

ci/terraform/oidc/site.tf

AIS lambdas are being deployed to all environments. This is to be followed by feature flags being turned on in the front end and backend in PRs to come.
Code review

BAU: Deploy AIS to all environments

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java

Add instrumentation of response time for AIS calls. For use in monitoring dashboard during go-live

ATO-452: Instrument AIS calls

---

integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoAuthCodeService.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java

removed references to the auth orch split feature flag within the authentication auth code lambda.
Should the lambda switch over to using the orch shared service ?

ATO-408: remove feature flag in authentication auth code

---

ci/terraform/shared/authdev1.tfvars
ci/terraform/shared/authdev2.tfvars

Update the redirect URLs for the authdev stub clients

BAU: Update authdev urls for new stubs

---

template.yaml

Add alerting for lambdas to the cloudformation template; done for OpenIdConfigurationFunction - will be copied and pasted for others as they are moved across

ATO-322: Add alerting for lambdas

---

integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java

Refactor lambda and tests to allow expired sessions to redirect to RP
To allow logouts to redirect to RPs when session has expired
This has not been manually tested - ran integration tests

ATO-259/post logout redirect expired session

---

ci/terraform/auth-external-api/auth-ext-api-gateway.tf
ci/terraform/test-services/staging-overrides.tfvars

Log subscription for Auth ext API & test service API  (api Gateway )  not configured

AUTH-2643 log Subscription for API execution logs

---

ci/terraform/auth-external-api/auth-ext-api-gateway.tf

The TF file errored with index key been used removed index key as no count (local stack is used)

removed index key as we not using count to fix build

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java

Added fields for requested audit events.

Aut 2638/audit events part4

---

.github/workflows/contract-tests.yml
build.gradle
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/contract/ClientRegistryProviderTest.java
integration-tests/src/test/java/uk/gov/di/authentication/pact/ClientRegistryProviderTest.java
ipv-api/build.gradle
oidc-api/build.gradle
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/PactProviderTest.java

ATO-438: Publishing and verifying contracts with GHA

---

ci/terraform/auth-external-api/auth-ext-api-gateway.tf

AUTH-2643 Adding log subscription for existing API execute logs
API execute logs Subscription is missing for Auth ext API 
commit by commit

Adding log subscription for existing API execute logs
