shared-test/build.gradle, shared/build.gradle
- Remove aws-java-sdk-lambda from shared and shared-test
- The only other place the aws-java-sdk-lambda is used is in the lambda-warmer module. This will soon be deleted and therefore avoids the need to update the lambda sdk to version 2.
- It is not used so we can remove it.
=> BAU - Remove aws-java-sdk-lambda from shared and shared-test

ci/terraform/utils/account_metrics_lambda.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/AccountMetricPublishHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/AccountMetricPublishHandlerTest.java
- Refactor of CloudwatchMetricService
- Add a lambda, that will run on a schedule, to publish the total number of accounts and the number of verified accounts to Cloudwatch metrics.
- Create lambda with permission to describe the UserProfile table
- Schedule the lambda to run every hour
We want to show this metric in a Grafana dashboard.
#2271 
#2232 
#2233
=> AUT-661: New lambda to publish account metrics

build.gradle, doc-checking-app-api/build.gradle, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppAuthorisationServiceTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java, frontend-api/build.gradle, integration-tests/build.gradle, ipv-api/build.gradle, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java, shared-test/build.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/TokenSigningExtension.java, shared/build.gradle, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/JwksServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
- Upgrade aws kms sdk to version 2
- Previously kms was brought in by the dynamo dependency. Add KMS as its own dependency and set it to version 2 of the AWS sdk. This reduces the impact of uplifting both dynamo and KMS to version 2 at the same time.
=> AUT-398 - Upgrade aws kms sdk to version 2

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
- Record the requested credential trust level as new dimension to the `SignIn` metric.
We want to collate metrics based on whether the journey required an MFA check (i.e. low level of credential trust).
=> AUT-621: Add MfaRequired dimension to metric

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
- Add a `IsDocApp` dimension to indicate whether it is doc app journey
- Add a `RequestedLevelOfConfidence` so we can slice out how many identity journeys are being requested
- Only add the `MfaRequired` and `RequestedLevelOfConfidence` dimension if the journey is not a doc app journey
We wish to be identify the different types of journeys succeeding in Grafana dashboards, adding the dimension to the `SignIn` metric allows us to do that.
#2284
=> AUT-621: Add additional dimensions to sign-in metric

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/DynamoClientServiceTest.java
- Move the `isTestJourney()` method from the `AuthorizationService` (in the `oidc-api` module) to the `ClientService` (in the `shared` module)
We will be using this method in the `frontend-api` when publishing additional metrics (PR to follow).
=> AUT-621: Refactor `isTestJourney()` so available in all APIs

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LocaleHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/LocaleHelperTest.java
Support ui_locales in /authorize
- Check for the presence of the ui_locales paramater and set the 'lng' cookie if any of the supported languages are present.
- Creates two supported languages: English and Welsh.
- Only the primary languages part is processed and all other subtags are ignored, so 'en-US' will just map to 'en' and 'cy-AR' to 'cy'.
- If either of the supported languages en or cy are passed in ui_locales then the language cookie will be set to switch to the correct language.  
- If the parameter is missing, or no supported languages are provided then the cookie will not be set, and frontend user choices will continue to be respected.
- Adds a switch for the Welsh lanugage.  Welsh will only be set in the cookie if the switch is on.
- This PR switches Welsh on in Staging but …
=> AUT-590: Support ui_locales in /authorize

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/SMSCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/SMSCodeValidatorTest.java
Create new SMS validator and refactor UpdatePhoneNumber handler to make use of the sms validator. This is required to validate OTP code when invalid or code entered too many times. These codes will then determine the routes for error messages in the accounts management page
Required so that the error codes returned by the handler is reflected across pages for account management
[Build UI components](https://github.com/alphagov/di-authentication-account-management/pull/561)
=> AUT-607: Create SMS validator for updating phone number

ci/terraform/audit-processors/counter_fraud.tf, ci/terraform/audit-processors/storage.tf
This is the first step in decommissioning Auth's internal audit service in favour of the TxMA-supported audit service.
The lambdas will continue firing messages to SNS but they won't get consumed by either the logging lambda or the long-term storage queue.
Once this has landed, we can start dismantling the infrastructure.
=> AUT-584: Turn off auth's audit service by removing SNS subscription

build.gradle, shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoClientHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CommonPassword.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CommonPasswordsService.java
- Add the DynamoSDK2 dependency and the enhanced client. https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/dynamodb-enhanced-client.html
- Add a method to the dynamo client helper to create an enhanced client
- Uplift CommonPassword to use Dynamo version2 of the SDK
- Update CommonPassword bean with the Dynamo SDKv2 annotations.
- Ensure there is a default setter as if this is missing SDKv2 does not like it and will throw errors similar to `java.lang.IllegalArgumentException: Attempt to execute an operation against an index that requires a partition key without assigning a partition key to that index. Index name: $PRIMARY_INDEX`
- Update `setPassword` to `withPassword` so you can return an inctance of the object when setting attributes. 
- So we make use of the latest …
=> AUT-398 - Add Dynamo SDKv2 dependency

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/queuehandlers/NotificationHandlerIntegrationTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/NotificationServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/NotificationHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/RequestHeaders.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/DeliveryReceiptsNotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotifyRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/TemplateAware.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LocaleHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java, shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/NotificationTypeTest.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/LocaleHelperTest.java
Groundwork to choose Notify templates by language.
Put in place the infrastructure to be able to choose which Notify template to use by language, but do not make use of it.  Able to demonstrate that the new functionilty will work, and that the existing functionality is unchanged.
A subsequent PR will add the Welsh template ids to the right environment variables, and tweak the code to vary the template by language.
- Expect a new header in the frontend api endpoints containing the user language called 'User-Language'.
- Read the value of this new header in 'BaseFrontendHandler' to make it available in the UserContext, so available to all endpoints that use the base class.
- English is set to the default in all cases where the header is not 'cy' or 'CY', including when the header is …
=> AUT-639: Groundwork to choose Notify templates by language

client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java, shared/src/test/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/DynamoClientServiceTest.java
- Update client registry to Dynamo SDK v2
- So we can move away from AWS SDK v1 and take advantage of the new features in v2
=> AUT-398 - Update client registry to Dynamo SDK v2

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LocaleHelper.java
Additional logging for ui_locales parameter.
Use ignorecase when checking for language tag match.
Language is not being set anymore when launching from the stub, need more logging to see what's happening.
=> BAU: Additional logging for ui_locales parameter

ci/terraform/oidc/build-overrides.tfvars
Switch on Welsh in build in the backend.
So /authorize reads ui_locales.
Without this Sign In ignores any languages passed in ui_locales and defaults to en.
=> BAU: Switch on Welsh in build in the backend

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCapacityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
Add client session id to audit payloads and implement across all lambdas which have access to client session id.
We pass this value (client session id) up to IPV Core and the Document Checking App but don’t publish it to our own audit log.
=> AUT-708: Add client session id to audit payloads 

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
Set `govuk_signin_journey_id` in AuditService to empty string `""` for lambdas with no access to client session id. Mainly account management and client registry lambdas
We pass this value (client session id) up to IPV Core and the Document Checking App but don’t publish it to our own audit log.
[Change for IPV/CRI/DocApp lambdas](https://github.com/alphagov/di-authentication-api/pull/2326)
=> AUT-708-part-1: Add client session id to audit payloads

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
- Refactor `ClientSessionService.generateClientSession()` to just store the session rather than also generate the ID, the ID is now passed as a parameter. Also, make method `void`.
- Add a new method `ClientSessionService.generateClientSessionId()`
- Generate `clientSessionId` prior to validation in `AuthorisationHandler`
- Rename method `storeClientSession()` to more accurately reflect what it is doing.
- Move call to `attachLogFieldToLogs()`  to beginning of `AuthorisationHandler` just after ID has been generated.
We are using a common ID to represent the journey across the products, that is our client session ID.
#2336 
#2337
=> AUT-708: Add client session id to audit payloads in Authorise handler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java
Add client session id to audit payloads for lambdas in frontend-api
- Add `clientSessionId` to `UserContext` which is used in majority of the handlers
- Refactor `BaseFrontendHandler` to set the client session id in the user context in order for all handlers to have access to the `clientSessionId`
We pass this value (client session id) up to IPV Core and the Document Checking App but don’t publish it to our own audit log.
[Part 1](https://github.com/alphagov/di-authentication-api/pull/2336)
[Authorise Handler](https://github.com/alphagov/di-authentication-api/pull/2338)
=> AUT-708-part-2: Add client session id to audit payloads

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
- Send clientSessionId from `AuthCodeHandler`
- Send `AuditService.UNKNOWN` from `LogoutHandler` and `UserInfoHandler` as these are not client session aware (currently)
We wish to use clientSessionId to track journeys across the entire estate.
#2336 
#2337 
#2338
=> AUT-708: Update remaining OIDC handlers

integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
- Modify `accountVerified` field in `UserProfile` object to use an attribute type of Number
- Modify `UserStoreExtension` to include `VerifiedAccountIndex` as is in DynamoDB indexes for `user-profile`
- Validation failure when updating email using `accountVerified` type of boolean when it expects a Number type as declared in the `VerifiedAccount` index
`Transaction cancelled, please refer cancellation reasons for specific reasons [ValidationError, None, None, None] (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: TransactionCanceledException; Request ID: xxx; Proxy: null): `
=> Aut 705: Change accountVerified attribute item type to Number

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java
Ship client name in metrics to Grafana.
To be able to show a friendly readable name when grouping metrics by client in Grafana dashboards.
=> AUT-692: Ship client name in metrics to Grafana

shared/client-dynamo-tables.yaml, shared/common-password-dynamo-table.yaml, shared/user-dynamo-tables.yaml
- Add stack template for user tables
- Add stack template for client registry tables
- Add stack template for common password tables
- Ignore checkov rule `CKV_AWS_119` for the moment, this is scheduled as separate story.
We are migrating to the devplatform which means deploying resources with Cloudformation instead of Terraform. These templates have designed to import existing tables and have been tested and proved to produce no "drift" from current resources.
=> AUT-644: Dynamo table CloudFormation templates

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
We were claiming that we published this in the docs, but we actually don't.
=> BAU: Add `expiry_time` to access tokens

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java
- Add password max retries to account management during authentication
- Return error code 1028 when account is temporarily locked after 5 unsuccessful attempts
- Currently users are able to retry sign in even when their account is locked
- Users should be redirected to a `/account-locked` page instead of login page when they try to sign in again
=> AUT-389-backend-changes: Return password max retries error code

ci/terraform/account-management/authenticate.tf
- The `AuthenticateHandler` now uses `CodeStorageService` which needs to get Redis connection parameters from SSM. Add the required policy to the execution role.
The `AuthenticateHandler` is failing to start and as such provisioned concurrency is failing to deploy.
#2363
=> BAU: Add the parameter policy to the authenticate role

ci/terraform/account-management/authenticate.tf
- Add REDIS_KEY env variable to AuthenticateHandler
As the handler now needs to access Redis it needs to know the key of Redis connection parameters to get from SSM
#2370 
#2363
=> BAU: Add REDIS_KEY env variable to AuthenticateHandler

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
Add Client Name as a dimension for sign in metrics.
Covers metrics for both account creation and account reuse.
Allow reporting on sign ins and sign ups by client name in Grafana (rather then the client id which is less readable)
#2355
=> AUT-692: Add Client Name as a dimension for sign in metrics

ci/terraform/account-management/redis.tf, ci/terraform/shared/redis.tf
- Change elasticcache maitenance window
- Make the maintenance window earlier so that it still avoids high periods of traffic but so that it is not in the middle of the night should elasticcache maintenance caus e an incident.
=> BAU - Change elasticcache maitenance window

shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
Additional metrics for new and existing authentications.
Reduce number of dimensions in the metrics for easier reporting by client.
It's not possible to filter on a single metric (such as client) when reporting on cloudwatch metrics in Grafana, so separate metrics with only the required information are needed instead.
https://stackoverflow.com/questions/48443899/cloudwatch-does-not-aggregate-across-dimensions-for-your-custom-metrics
=> AUT-692: Additional metrics for new and existing authentications

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
Reduce number of dimensions in the metrics for easier reporting by client.
Additional metrics for new and existing signins.
This metric is reported from a single lambda so it will give meaningful counts in Grafana which aren't spilt by service.
Reduce number of dimensions in the metrics for easier reporting by client.
It's not possible to filter on a single metric (such as client) when reporting on cloudwatch metrics in Grafana, so separate metrics with only the required information are needed instead.
https://stackoverflow.com/questions/48443899/cloudwatch-does-not-aggregate-across-dimensions-for-your-custom-metrics
#2380
=> AUT-692: Additional metrics for new and existing sign ins

shared/src/main/java/uk/gov/di/authentication/shared/entity/MFAMethod.java
- In Version 1 of the SDK, booleans were stored in Dynamo by default as either 1 or 0. In SDK version 2, they are stored in either true or false. This will make the database inconsistent and we should look to get them the same.
- So booleans are still stored as either 0 or 1 to keep it consistent with what we currently have in the DB
=> AUT-398 - Use custom attribute converter when setting MFA method

.github/workflows/pre-merge-checks-terraform.yml, ci/terraform/utils/account_metrics_lambda.tf
- Add user-profile data resource to account_metrics_lambda
- Add validation to the terraform utils module
- Previously it was using the data resource from the verified_account_update_lambda.tf which has since been deleted
- The terraform issue did not get picked up until the pipeline. Adding a github actions will ensure we can capture any issues earlier
=> BAU - Add user-profile data resource to account_metrics_lambda

ci/terraform/oidc/integration-overrides.tfvars, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
- Log out AccessToken in IpvCallbackHandler in non-prod environments
- To help debug an issue between Auth and IPV - `Response from user-identity does not indicate success `
=> BAU - Log out AccessToken in IpvCallbackHandler in non-prod environments

account-management-integration-tests/build.gradle, build.gradle, doc-checking-app-api/build.gradle, frontend-api/build.gradle, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, integration-tests/build.gradle, ipv-api/build.gradle, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCapacityHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java, shared-test/build.gradle
- Remove AWS sdk v1 dependency
- Add apache dependency
- Now that we have uplifted everything to v2 of the AWS sdk dependency, we can remove the version1.
- Verson1 had a transitive dependency on apache that we were using in places (mainly tests) so explictly add the apache dependency.
=> ACI-84 - Remove AWS sdk v1 dependency

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotificationType.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/entity/NotificationTypeTest.java, ci/terraform/account-management/sqs.tf, ci/terraform/account-management/variables.tf, ci/terraform/oidc/sqs.tf, ci/terraform/oidc/variables.tf, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Switch off per language Notify templates
Create a switch to toggle this feature.
Switch it off: the default template will be used in all cases regardless of the user language.
We are switching to bilingual templates so the default can be used in all cases.
=> AUT-766: Switch off per language Notify templates

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Ship client name to the AUTHORISATION_INITIATED event.
The client name will eventually be added to all audit events.  As this is a fair amount of work which is not covered by 
AUT-692 it will be done under a separate ticket.
Starting with the most important one so that transactions can be associated with the client name if needed.
=> AUT-692: Ship client name to the AUTHORISATION_INITIATED event

shared/kms.yaml
- Add importable resources for KMS keys
- Add importable resources for KMS key aliases
- Add exports of key IDs and aliases so can be referenced from other stacks
We are migrating to CloudFormation for deployments, this CloudFormation creates keys as per our current deployment and also allows importing of existing keys into the stack.
#2352
=> AUT-644: Add CloudFormation for common KMS keys

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
Do not block email when validation code entered incorrectly max times for new account.
Do not ask user to re-enter email when they request another code having exceeded the maximum.
In 'verify-code' for email notification types, where the code is 1033 meaning that user has exceeded the maximum number of attempts to enter the code correctly, then don't block the email in Redis.
No reason to block the account if the account does not already exist, this just means the user has to wait 15 mins before they can create the account.
Make it easier for the user by not asking them to enter their email again.
https://github.com/alphagov/di-authentication-frontend/pull/784
https://github.com/alphagov/di-authentication-acceptance-tests/pull/147
=> ACI-7: Do not block email when validation code entered incorrectly max times for new account

ci/terraform/shared/dynamodb.tf, ci/terraform/shared/production-sizing.tfvars, ci/terraform/shared/variables.tf
- Add streaming to UserProfile DynamoDB table
- On by default but off for production
- Streaming events will be consumed by the Experian phone check lambda
- To keep costs down, the stream (and lambda subscription) will be conditional - as the lambda could be invoked unnecessarily in production before it is ready otherwise
=> AUT-663/turn on user profile streaming

shared/fargate-cluster.yaml, shared/sns.yaml
- Add a Cloudformation stack for an ECS fargate cluster
- Add a central SNS topic for slack alerts. This differs slightly from current configuration as it is encrypted (as recommended by Checkov)
- Create a managed policy for event publisher
- Add key for topic encryption (the key policy will change later once required permissions for deployments have been fully established)
These are shared resources that will be used by multiple deployments when we migrate to Cloudformation/Codepipeline. These resources will not be imported in production, just created fresh, so its OK that the config differs slightly from our current Terraform.
=> AUT-644: Templates for ECS Fargate Cluster and Slack Alerting SNS

ci/terraform/shared/production-sizing.tfvars
-  Toggle User Profile table streaming on
To resolve Terraform error that we cannot disable a stream that does not exist (yet)
=> BAU: Toggle User Profile table streaming on

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RequestObjectService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java
Add ui_locales claim to request object.
- Validates are reads the ui_locales claim if it is present.
- Follows the same behaviour as for the ui_locales query parameter: the cookie will only be set on authorisation if a language preference is specified, and the requested language is available, otherwise frontend (and user preferences) will be respected.
- Will be used initially be the doc app journey.
Support language preferences for services using the request object, who will be able to specify en or cy when Welsh is switched-on.
#2292
=> AUT-769: Add ui_locales claim to request object

.github/dependabot.yml
- Increase the dependabot PR limit to 100
- By default the limit is 5. We want to see all dependabot PRs which are raised
=> BAU - Increase the dependabot PR limit to 100

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, ci/terraform/account-management/build-overrides.tfvars, ci/terraform/account-management/sandpit.tfvars, ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/variables.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/mfa.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Decouple email OTP validity from SMS OTP validity (when signing up but NOT for reset password and NOT in account management as ticket suggests only sign-up non-reset should be affected)
- Increase email OTP default value to 2 hours (7200 seconds) - this is not currently overridden in any environment so is the active value being used in production
- This is greater than the 'other' OTP default (SMS OTPs and Email OTPs for Account Management), left at 15 minutes (900 seconds) - this is also not currently overridden in any environment
- Add variables to make all of this separately configurable in environments by passing a value as an environment variable (so 'default' in code should not in fact ever be the deciding factor as there is also a default in Terraform that will populate the …
=> ACI-76: Decouple email OTP validity from SMS OTP validity

ci/terraform/modules/txma-audit-queue/key.tf
- Add a aws_kms_alias for the txma audit encryption key. 
- This is required so that it can be referenced by a terraform data source for the phone number check.
=> AUT-809 - Add txma audit kms key alias

ci/terraform/modules/txma-audit-queue/key.tf
- Concat the serviceName to the audit kms key alias
- Each module will create a KMS key alias so we can't have them all called the same. Therefore, concat the service name to each alias.
=> AUT-809 - Concat the serviceName to the audit kms key alias

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UserStartInfo.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
- Return the MfaMethodType from the StartResponse
- The frontend uplift journey depends on what MFA type the user is configured with. The frontend does not currently know this so we need to return this information from start.
- Currently the frontend directs the user to the /uplift path when a user is configured with the Auth App MFA method, this is incorrect
=> AUT-802 - Return the MfaMethodType from the StartResponse

shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
- Allow the Identity Proofing `P` component to appear anywhere in the string.
- Allow the Credential Confidence `C` components to appear in anywhere and in any order (so, `Cl.Cm`, `Cm.Cl` and `Cm.P2.Cl` all resolve to medium level (`Cl.Cm`) level of credential confidence.
- Add `equals()` method to `VectorOfTrust` to facilitate testing.
We are currently not fully compliant with the spec as we expect the `P` component to be specified first, if supplied.
=> AUT-771: Allow VTR components in any order

ci/terraform/shared/production-sizing.tfvars
- Turn on Dynamo Stream for User Profile table in production
- The default is for this to be true, hence removing the 'false' from .tfvars
- Prerequisite for phone check lambda to work (under discovery implementation in Oct 2022 => full implementation expected to be different)
=> AUT-664: Turn on Dynamo Stream for User Profile table in production

shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
- Simplify the creation of `VectorOfTrust` class while parsing.
- Check that the vectors only contain ones identity proofing (`P`) component (previous test that checked this was only succeeding because invalid `P` values were used).
- Turn the all the `shouldThrow...` tests into a single, parameterised test (as per suggestion from Sonar)
- Add parameters to test the multiple, valid, `P` value scenario.
Simplifies code and ensures we only allow one `P` value in the vectors (as per [RFC](https://www.rfc-editor.org/rfc/rfc8485.html#section-2.4))
#2454
=> AUT-771: Refactoring and VTR parsing fix

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
- Add `isValid()` method to `VectorOfTrust` to determine validity of combination.
- Throw `IllegalArgumentException` when parsing the provided the `vtr` parameter if the result `VectorOfTrust` is invalid.
To stop clients requesting an invalid VTR as we require at least `Cl.Cm` for identity proofing (`P2`) journeys. An invalid request now results in the user being returned to the RP with the appropriate error message.
=> AUT-823: Return error if vector of trust is equivalent of `Cl.P2`

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
- Ensure that whenever a user successfully enters a auth app OTP, there credential trust level is set to Medium.
- Add extra checks in the auth app mfa unit tests to verify this
- Although it is not impacted by this, add additional checks to the verify code unit tests 
- When a user creates an account from a low level service, then they should be authenticated to a medium level. This is because all account creation journeys require MFA.
- Previously when a user created an account from a low level service, they were only authenticated to a low level so when they switched to a medium level service they were asked to enter the auth app OTP. This is not expected and is all different to the behaviour of a user creating an account via sms.
=> AUT-827 - Fix auth app uplift bug

ci/terraform/account-management/build-overrides.tfvars, ci/terraform/account-management/integration-overrides.tfvars, ci/terraform/account-management/production-overrides.tfvars, ci/terraform/account-management/staging-overrides.tfvars, ci/terraform/audit-processors/build-overrides.tfvars, ci/terraform/audit-processors/integration-overrides.tfvars, ci/terraform/audit-processors/production-overrides.tfvars, ci/terraform/audit-processors/staging-overrides.tfvars, ci/terraform/delivery-receipts/integration-overrides.tfvars, ci/terraform/delivery-receipts/production-overrides.tfvars, ci/terraform/delivery-receipts/staging-overrides.tfvars, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/utils/build-overrides.tfvars, ci/terraform/utils/integration-overrides.tfvars, ci/terraform/utils/production-overrides.tfvars, ci/terraform/utils/staging-overrides.tfvars
The new endpoint has superseded the old one
=> BAU: Remove deprecated logging endpoint from apps

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
Add `clientID` for DCMAW events to be audited
Needed for grouping and analysis
=> AUT-77: Add client ID to Doc App authorize

ci/terraform/oidc/integration-overrides.tfvars
Switch on Welsh in integration.
This is the backend switch that enables ui_locales.
DBS called-out that it was not switched-on.
=> BAU: Switch on Welsh in integration

ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/oidc/alerts.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf, ci/terraform/oidc/sns.tf, ci/terraform/oidc/variables.tf
- Update pattern for existing metric filter as we no longer perform state transitions in the backend
- The IPV handoff covers the IPVAuthorisation lambda
- The IPV handback covers the IPVCallback, SpotResponse and ProcessingIdentity lambda's
- The alarms are currently set to trigger when 20 errors have occured within a 10 minute period. This time period may need adjusting as needs be
- The alarms are currently set to generate a slack alert, however this is just to help us gauge how they behave over the next week or so before switching production over to use pagerduty p1 alerts.
- When we are happy with the alarms we can switch over the alarm_actions for production to use the pagerduty sns topic rather than the slack sns topic
- The alarms will give us out of hours alerting of any issues …
=> AUT-828 - Add 2 cloudwatch alarms to cover IPV handoff and IPV handback process

ci/terraform/oidc/sns.tf
- Only use pagerduty SNS topic in Production
- The Pagerduty sns topic is only created in production. Therefore we should only reference to it in production.
=> AUT-828 - Only use SNS topic in Production

ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf
- Filter pattern on log level rather than the word ERROR
- It was filtering on the message ERROR rather than logs which are set to the level of ERROR
=> AUT-828 - Filter pattern on log level rather than the word ERROR

ci/terraform/modules/endpoint-module/account.tf, ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/oidc/account.tf, ci/terraform/oidc/alerts.tf, ci/terraform/oidc/doc-app-alerts.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf, ci/terraform/oidc/variables.tf
- Include account alias in cloudwatch alarm descriptions
- Add P1 alerts for DocApp errors
- Add the account alias to the cloudwatch alarm descripton. The account will then be cut from the alarmDescription in the alerts.js lambda and set as it's own field. This will make it easier for those actioning the alert to identify what AWS account the alert impacts.
- Create a cloudwatch alarm which monitors both the DocAppAuthoize and DocAppCallback lambda's for any errors that occur. The alarm will be triggered when there has been 20 errors in 10 minutes. This can be tweaked as required.
- For now, we will use the slack SNS topic so that these alerts will only generate slack messages to the #di-2nd-line channel. When required, we can switch the SNS topic for production to use pagerduty so that …
=> AUT-830 - Add P1 doc app alerts and include account alias in cloudwatch alarm

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
1. Refactor `CheckUserExistsHandler` to include check for  when user account is locked/unlocked
2. Return a new error code `1045 - User account locked`
3. Revert changes from [PR](https://github.com/alphagov/di-authentication-api/pull/2363) as the changes required applies to global Sign In rather than Account Management module only.
This is required in the Sign-In journey when a user tries to enter their password after their account has been locked, the page needs to redirect to a new account locked page detailing why the user cannot sign in
[Backend changes](https://github.com/alphagov/di-authentication-frontend/pull/826)
=> ACI-115: Use CheckUserExists lambda to return user account status

ci/terraform/oidc/doc-app-alerts.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf
Reverts alphagov/di-authentication-api#2495
Reverting as the ok actions are resulting in lots of confusing alerts in slack for the OK status.  To be re-instated when alerts are sent to Pager Duty.
=> Revert "AUT-830/828 - Add ok_actions to P1 cloudwatch alarms"

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ClientStartInfo.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
- Add the new flag to the `ClientRegistry` class
- Default value should be `false`
- Add `oneLoginService` flag to `ClientStartInfo` class
- Set this value from the value that is returned from the client registry
We need to make the frontend aware of whether the RP is an internal One Login service so that we can display different content where necessary.
There is no corresponding Client Registry change to this as we will manually manage the flags for the relevant clients.
https://github.com/alphagov/di-authentication-frontend/pull/832
=> ACI-121: Add OneLoginService flag to client start info

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
- Add isPasswordResetRequired info to login handler response
- If true, then the frontend can route to the password reset page
- Pre-requisite for front end changes to allow user to be prompted to reset password when their existing password is detected as a common password.
- If this PR is approved I intend to use the new field in the frontend [here](https://github.com/alphagov/di-authentication-frontend/blob/66e206c80ee8b4d74530b3bc6d87082caa172d05/src/components/enter-password/enter-password-controller.ts#L92) by adding it to the state machine context, and from there saying that the next page if `resetPasswordRequired` is `true` on a `USER_JOURNEY_EVENTS.CREDENTIALS_VALIDATED` event should be to send the user to the normal Reset Password page, from where they would follow the state flow …
=> ACI-19: Add isPasswordResetRequired info to login handler response

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
Additional logging for reset password required.
Log whether a user is required to reset their password for debug and reporting purposes.
#2520
=> ACI-19: Additional logging for reset password required

ci/terraform/oidc/login.tf
Add common passwords dynamo read access to login.
Lambda cannot start due to missing access rights.
build-login-lambda is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:eu-west-2::table/ because no identity-based policy allows the dynamodb:DescribeTable action (Service: DynamoDb, Status Code: 400, Request ID: 
#2520
=> ACI-19: Add common passwords dynamo read access to login

ci/terraform/oidc/auth-code.tf, ci/terraform/oidc/authorize.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/doc-app-authorize.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/login.tf, ci/terraform/oidc/logout.tf, ci/terraform/oidc/mfa.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/signup.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/start.tf, ci/terraform/oidc/token.tf, ci/terraform/oidc/update_profile.tf, ci/terraform/oidc/userexists.tf, ci/terraform/oidc/userinfo.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf
- Add internal sector URI to all Lambdas sitting under the OIDC module
- So the Lambda have it available when required although for now it is only the IPV lambda using it.
=> AUT-796 - Add internal sector URI to all OIDC Lambdas config

ci/terraform/account-management/authenticate.tf, ci/terraform/account-management/build-overrides.tfvars, ci/terraform/account-management/integration-overrides.tfvars, ci/terraform/account-management/production-overrides.tfvars, ci/terraform/account-management/remove-account.tf, ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/staging-sizing.tfvars, ci/terraform/account-management/update-email.tf, ci/terraform/account-management/update-password.tf, ci/terraform/account-management/update-phone-number.tf, ci/terraform/account-management/variables.tf
- Make the InternalSectorUri available to all Account Management backend lambdas
- We will not use it until we're ready to switch over all lambdas 
- This is required to calculate the subjectID that we send to TXMA
=> AUT-796 - Add the Internal Sector URI to AM lambda config

ci/terraform/oidc/doc-app-alerts.tf
- Switch Doc App alerts to Pagerduty
- The Doc App will start to run from 8am - 8pm so we need to ensure that our alerting will reach the on-call engineers
=> AUT-876 - Switch Doc App alerts to Pagerduty

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthoriseAccessTokenIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/RemoveAccountIntegrationTest.java, ci/terraform/account-management/authorizer.tf, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UserNotFoundException.java
- Add logic to the account management lambdas to ensure a user exists 
- Remove logic to check whether a user exists from the account management authorizer.
- Previously we were checking whether a user exists by using the subject id in the access token and calling dynamo to see if there was a user account. As we look to change this subject ID from the public subject id to the common subject identifier, we will no longer be able to do this.
- We can do this check instead in the account management lambdas. This allows us to not need to rely on the Subject in the access token and removes a call to dynamo which should reduce latency.
=> AUT-796 - Add logic to the account management lambdas to ensure a user exists

account-management-api/src/main/java/uk/gov/di/accountmanagement/exceptions/InvalidPrincipalException.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/helpers/PrincipalValidationHelper.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/helpers/PrincipalValidationHelperTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-integration-tests/build.gradle, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/RemoveAccountIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePasswordIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestBodyHelper.java
- Validate the principalId against the Internal subject pairwise ID if the validation against the publicSubjectId fails
- Create a new PrincipalValidationHelper to soley focus on the principal validation and add unit tests
- Add extra unit tests so we cover both scenarios of when the principalId contains the publicSubjectId and when it contains the internal subject pairwise id
- We want to move from using the PublicSubjectId to the Internal Subject Identifier. This will help with this transition and ensures that no users will be impacted
=> AUT-796 - Validate principalId in AM lambdas against internal subject pairwise id

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java
- Retry Doc App Token and UserInfo request if the first request fails
- There is currently an issue on the Doc App API where 3 of their la,bdas start timing out after 3 seconds having logged nothing. This appears to be an issue with the AWS lambda environment rather than anything in the Doc App API.
- For an immediate workaround, retry the calls to the Doc App userinfo and token endpoints if the first request is unsuccessful.
=> BAU - Retry Doc App Token and UserInfo request if the first request fails

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
- Check to see if the scope in the request contains `am` and if so send back public_subject_id to AM as an additional claim.
- We will be replacing the sub sent to AM with the common subject identifier but account management still needs the public_subject_id for when it sends requests to the publishing service. This is for when a user changes email or deletes an account
=> AUT-796 - Send back 'public_subject_id' claim to account management

ci/terraform/oidc/api-gateway.tf
Some off-the-shelf OIDC providers or SaaS solutions choose not to send user agent data, and this is blocking some integrations
=> BAU: Allow requests without user agents

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
- Only log an ERROR once for a journey, so that we don't trigger false positives with our alerts and think more journeys are being impacted than were actually are.
- There were cases where we were logging an ERROR in the DocAppCriService, throwing the UnsuccesfulCredentialResponseException which was being caught in the DocAppCallbackHandler and we were handling that by logging another ERROR.
=> BAU - Only LOG at level ERROR once for a journey

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorisationCodeService.java
- Send SubjectID to audit payload in auth code
- Add additional logging in the auth code handler
- Add additional test coverage for doc app journeys
- Tidy up some of the if conditions in the auth code lambda
- We were previously not sending the subjectId to the audit payload in the auth code lambda. This change ensures the subject id is sent to audit for both normal journeys and doc app journeys.
- This will also make the change to send the common subject identifier to audit easier.
=> AUT-796 - Send SubjectID to audit payload in auth code

ci/terraform/shared/dynamodb.tf, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
- Add testUser flag to `UserProfile` and `UserCredential` objects
- Add global secondary indices to these Dynamo tables to allow faster finding and safe deletion
- Int used over boolean for consistency with accountVerified flag
- Will enable bulk upload and deletion of test users
=> AUT-804: Add testUser flags to DB

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, integration-tests/build.gradle, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/User.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
- Save common internal subject ID in session within signup and login lambdas, for users who successfully logged in or signed up.
- Generate and store the Salt to the userprofile when the user signs up 
- To avoid having to generate the common internal subject ID in every lambda, we can save this in the session within the login and signup lambas. We know all users who require the common subject ID will need to either login or sign up, so this should capture them all. For users who login to one service and then login into another using SSO, the common subject ID will already be in the session when the user gets to auth code so we don't have to generate it again. 
-  We were previously only generating the Salt as and when we needed it. As we will be using it more for generating the common …
=> AUT-796 - Save Internal Common Subject ID in user session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
- Add the internal subject id as an additional pair to the audit events in the login, sign up and auth code lambdas.
- In the auth code lambda, only add the internalSubjectId to all non doc app journeys. This is because doc app journeys don't technically have an internalSubjectId.
- This is currently a duplicate of the user id but the user id will soon be changing and it's important that we can still link audit events to an internal subject id. Adding this field to the signUp, login and auth code lambdas will allow for this to happen.
=> AUT-796 - Add internal subject id to specific audit events

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
- Protect against nullpointers and reuse audit event rather than duplicate it 
- If the user does not have an email address or is a doc app user, then the internal subject id should default to UNKNOWN.
=> AUT-796 - Protect against nullpointers

ci/terraform/test-services/s3.tf
Shorten test services lambda source bucket name.
In integration the name exceeds the maximum length.
#2556
=> AUT-829: Shorten test services lambda source bucket name

ci/terraform/test-services/dynamo-policies.tf
Prune and rename test-services dynamo policies.
- Remove dynamo access rights not required by the handler.
- Rename some policies.
Read access had rights that were not needed.
Update some copy and pasted policy names.
=> AUT-829: Prune and rename test-services dynamo policies

ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf
- Switch IPV production P1 alerts to output to pagerduty
- IPV now runs 24/7 so we need to be alerted if there is an issue
=> AUT-844 - Switch IPV production P1 alerts to output to pagerduty

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/main/resources/log4j2.xml, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/resources/log4j2.xml, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/resources/log4j2.xml, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/resources/log4j2.xml, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
- Log the govuk_signin_journey_id in Splunk
- Attach the clientSessionId to the govuk_signin_journey_id field in Splunk. The govuk_signin_journey_id is being used in other parts of the journeys IPV etc and there isn't currently a single field which can be searched on in Splunk. This will make debugging journeys easier across all of DI.
- We might want to remove the client_session_id field in from the logs but we can leave it in for now until all journeys in auth have a govuk_signin_journey_id attached for the entire user journey throught auth
=> AUT-740 - Log the govuk_signin_journey_id in Splunk

ci/terraform/oidc/rsa-signing-key.tf
Part 1 to supporting RSA in addition to EC for id token signing.
This PR creates the key in KMS and an alias for it.
=> BAU: Create RSA (4096) signing key for ID tokens

ci/terraform/oidc/jwks.tf, ci/terraform/oidc/kms-policies.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/JwksHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/JwksServiceTest.java
- BAU: Read RSA key from KMS
- BAU: Add RSA signing key to default kms access policy (used by jwks endpoint)
- BAU: Refactor JwksHandler to make adding new keys easier
- BAU: Add RSA key to /jwks.json in build and staging only
=> BAU: Add RSA signing key to jwks.json in build and staging

ci/terraform/oidc/jwks.tf
This configuration has been omitted for a while, we're only using it now
=> BAU: Add missing environment variable to JWKs lambda

.pre-commit-config.yaml, ci/terraform/precommit-validate.sh
- Run `terrraform fmt` on all Terraform files when Terraform files have changed (`.tf` or  `.tfvars`)
- Add a pre-commit hook to run a script to validate Terraform.
- Use a Docker image for Terraform rather than rely on local, working, installation
- Script should take in list of changed files and determine distinct Terraform directories, only running validate once per directory
Ensure that commits are validated to be, syntactically, correct and are formatted consistently.
(the validate rule takes about 20-30 seconds to run, so longer than you'd normally expect for a pre-commit hook, but not unusable).
=> FIREBREAK: Pre-commit hooks for Terraform

ci/terraform/oidc/token.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/TokenGeneratorHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
- BAU: Add `IdTokenSigningAlgorithm` capability to `ClientRegistry`
- BAU: Grant token lambda access to RSA signing key
- BAU: Use RSA if client has chosen it and environment is RSA-enabled
=> BAU: Sign tokens with RSA if client requests and environment enabled

shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/TokenAuthInvalidException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/ClientSecretBasicClientAuthValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/ClientSecretPostClientAuthValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PrivateKeyJwtClientAuthValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/TokenClientAuthValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/TokenClientAuthValidatorFactory.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/ClientSecretBasicClientAuthValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/ClientSecretPostClientAuthValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/TokenClientAuthValidatorFactoryTest.java
- Add additional fields to the client registry to allow us to determine the clients authentication method and the client secret. Is the client authentication method is null, we can assume it is private_key_jwt 
- Add additional classes to validate client_secret_post and client_secret_basic and ensure that for now we only support client_secret_post and client_secret_basic in local, build and staging environments
- These classes are not yet used by the **token endpoint** but this is to break down the size of the PR and to split out the validation
- We want to start supporting client_secret_post and client_secret_basic for RPs that are using 3rd parties which don't support the use of the private_key_jwt
- Create a factory class to calculate what client authentication method is used for the …
=> Firebreak 🔥  - Add classes to validate client_secret_basic and client_secret_post 

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
- This allows the token endpoint to determine what authentication method is used by the client and retrieve the correct validator. 
- Add additional integration tests to ensure that token works with client_secret_basic and client_secret_post
- Default the client registration endpoint to private_key_jwt
- Remove unused methods from the tokenservice
- To give /token the ability to support client_secret_basic and client_secret_post. Currently we only support client secrets in local, build and staging. But it will eventually be rolled out to other environments.
- Some 3rd party providers do not support private_key_jwt so this will make it easier for more client to onboard easier
https://github.com/alphagov/di-authentication-api/pull/2600
=> Firebreak 🔥  - Give /token the ability to support client_secret_basic and client_secret_post

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
=> BAU: Only use CONCAT format for EC signatures

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Make Nonce optional for the Staging environment
- Nonce is optional in the OIDC spec but we currently make it mandatory as it offers protection against ID token replay attacks.
- Not all OIDC providers make the Nonce parameter mandatory which makes it difficult for RPs to integrate.
- To allow us to be able to test with 3rd parties, we will make the Nonce optional in the Staging environment only.
- If the nonce is not present in the auth request, then we will not attempt to place it in the ID token
=> BAU - Make Nonce optional for the Staging environment

ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/start.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/Features.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/features/FeatureStrategies.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Return set of feature flags from 'start' lambda (if enabled).
Adds a facility to return variable per-session feature flags to the frontend.  The frontend can then read the feature flags into its session and make dynamic behavioural changes accordingly.
The example in this PR sets the value of a feature flag 'updatePasswordHintTextVersion' to either '1' or '2' split 50% across user sessions.
First deployed inactive and switched-off in all environments for regression, no flags will be returned to the frontend.
Provides a facility to do A/B testing based on assigning percentages of user sessions to different groups.  Strategies for user group assignment can be varied based on infomration available to Orchestration (if required).
Corresponding FE PR.
=> FIREBREAK: Return set of feature flags from 'start' lambda (if enabled)

ci/terraform/oidc/variables.tf
Switch on extended feature flags in all environments.
This will enable A/B testing on the frontend for the two versions of the password hint text. 
See the PRs below for the corresponding frontend and backend changes.
To be tested in build first.
#2610 
https://github.com/alphagov/di-authentication-frontend/pull/877
=> FIREBREAK: Switch on extended feature flags in all environments

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf
Switch on AB testing in build, integration and staging only.
Do further testing before releasing to prod.
#2614
=> FIREBREAK: Switch on AB testing in build, integration and staging only

.pre-commit-config.yaml, shared/client-dynamo-tables.yaml, shared/common-password-dynamo-table.yaml, shared/kms.yaml, shared/user-dynamo-tables.yaml
- Use `cfn-python-lint` to lint cloudformation files. Assume that all YAML files are potentially Cloudformation files except those in the exclusion list (we may want to refactor this later).
- Add a `UpdateReplacePolicy` where-ever we have a `DeletionPolicy`
To give us confidence that Cloudformation we're committing it sensible.
N.B. the first commit adds the functionality, the second commit makes existing files compliant with the linter rules.
=> FIREBREAK: Pre commit hooks for Cloudformation

.pre-commit-config.yaml
- Use the commit hooks shared in the `di-pre-commit-hooks` repository
These rules are going to be shared amongst multiple repos
=> FIREBREAK: Use shared pre-commit rules

.pre-commit-config.yaml
- Change prehook ID from `spotless-check` to `gradle-spotless-apply`
Pre-commit hook fails because of incorrect ID.
#2620
=> FIREBREAK: Fix rebasing error

.github/workflows/pre-merge-checks-terraform.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/sonar-analysis-on-merge.yml
- Upgrade GH actions to not use Node.js 12
- Node12 is out of support and any github versions running on Node will need to be upgrade - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- We are currently seeing messages such as `Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-java@v2, actions/cache@v2`
=> ACI-123 - Upgrade GH actions to not use Node.js 12

utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkTestUserCreateHandler.java
- When uploading an auth app secret to the UserCredentials DyanamoDB table, the variable which sets this value now references column 5 of the source CSV, which contains the actual auth app secret.
- Lambda was populating secret field with the wrong column of the CSV 
- Was referencing column 4 (values null or 1) which refers to whether auth app 2FA is enabled (this was not throwing any error as "1" was a valid value as far as DynamoDB was concerned)
- Amends: https://github.com/alphagov/di-authentication-api/pull/2571
=> AUT-941: Add correct Auth App secret for bulk users

shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/TestClientHelperTest.java
Only use email allowlist regex check on regex entries.
The regex only check was not matching against '+1' etc emails.
#2624
=> AUT-781: Only use email allowlist regex check on regex entries

utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkTestUserCreateHandler.java
- Make subject ID unique for each bulk-created user
- Was previously using a single ID per batch leading to non-unique subject IDs
- Could cause unexpected when these test users are used
- Amends original PR here: https://github.com/alphagov/di-authentication-api/pull/2571
- Also amends: https://github.com/alphagov/di-authentication-api/pull/2655
=> AUT-941: Make subject ID unique for each bulk-created user

shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkTestUserDeleteHandler.java
- Continue to query only `TestUserIndex` Global Secondary Index as part of scan operation
- However, add a filter that `testUser` attribute must equal `1` (Number data type in the table)
Note: I have also refactored `getTestUsers` function name to make it clear that the field specifically targets bulk-created users i.e. users who were created programmatically via the bulk creation lambda. The old name might have implied it included other test users e.g. those used for acceptance tests.
- Due to a change to `UserProfile` Java class, all new users will have a value of either 0 or 1 for testUser, even when not explicitly set
- This means that all new users will be part of the `TestUserIndex` GSI (but existing users, who do not have this attribute are not)
- This was overlooked in the …
=> AUT-941: Add filter to bulk test user Dynamo scan

shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java
- Auth app stub unit test was not working due to string being unmockable and config service missing a 'when/then'
- Add fixes for these two problems
- Note: This was not picked up automatically because the file is in shared-test, so is not treated as a 'real' test file
- Improve quality of tests
- Amends earlier work here: https://github.com/alphagov/di-authentication-api/pull/2046
=> BAU: Fix auth app stub test

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
- Add retries to IPV User Identity endpoint as well as to the (IPV Access) Token endpoint 
- Note: this follows the same pattern as already existed for DocApp callback: https://github.com/alphagov/di-authentication-api/blob/4df91fcdccc1458a1969fdca313f5187c525ed47/doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java#L89-L100
- The User Identity endpoint retry addresses a known issue where due to lack of read consistency at IPV side, sometimes the access token is not found and therefore rejected despite being valid
- The token endpoint was not an identified area of concern, but a more general lack of robustness to network glitches was raised during discussion about the other endpoint, so this retry was considered prudent for system resilience.
=> AUT-961: Add retries to IPV User Identity endpoint

shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/TestClientHelperTest.java
- Set testJourney to false in auth code handler if it is a doc app journey
- Currently all Doc App journeys using the stub are throwing a NullPointerException when checking if the journey is a test journey. The nullpointer is thrown because no user logs into auth for doc app journeys
- This is because the Doc App Stub is configured as a test client so we can send a property in the secure auth request to the doc app cri, informing them that the initial journey started at the stub.
- Make the check in the TestClientHelper nullsafe
=> BAU - Set testJourney to false in auth code handler if it is a doc app journey

ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars
Smoke test clients in build and integration.
Private keys will be retrieved and deployed in the smoke test pipeline using shared state.
In order to remove the smoke test dependency on AM separate clients are needed for the smoke testers.  Smoke tests are not actually deployed in build but the client will be used for local and sandpit testing.
=> AUT-834: Smoke test clients in build and integration

shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/TestClientHelperTest.java
- Return false if email address is null
- There is no email address during the doc app journey so this will throw a nullpointer. If the email address is null, return false
=> BAU - Return false if email address is null

ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars
Reverts alphagov/di-authentication-api#2677
Smoke test clients will instead be created in the smoke test pipeline.  This avoids creating dependencies between two pipelines in order to pass the client id and private key.
https://github.com/alphagov/di-authentication-smoke-tests/pull/61
=> Revert "AUT-834: Smoke test clients in build and integration"

ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/shared/staging-stub-clients.tfvars
Enable and add test client to staging for performance testing.
Performance testing in staging requires a test client and for test clients to be enabled to support OTP scenarios.
https://github.com/alphagov/di-authentication-frontend/pull/903
=> AUT-955: Enable and add test client to staging for performance testing

ci/terraform/shared/staging-sizing.tfvars
Align staging redis sizing with production for performance testing.
Staging will be used for performance testing so should match production sizing.
https://github.com/alphagov/di-authentication-frontend/pull/903
#2689
=> AUT-995: Align staging redis sizing with production for performance testing

ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/start.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/DocAppSubjectIdHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/DocAppSubjectIdHelperTest.java
- Add helper method to calculate and populate DocAppSubjectId
- We are going to be moving away from populating the DocAppSubjectId with the pairwise identifier and instead populate it with the sub from the Request Object contained in the original Auth Request.
- The helper class will help determine 2 things. Firstly, if the subject is present in the request object and secondly, whether or not we have enabled the system to start using it. To start with this will be disabled.
=> AUT-963 - Add helper method to populate DocAppSubjectId

ci/tasks/deploy-oidc-api.yml, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/ssm.tf, ci/terraform/oidc/variables.tf
- Read the Doc App Client ID evironment variable which is set in our deployment pipeline and set it to a terraform variable.
- Create a new SSM parameter which store the value of the doc_app_rp_client_id terraform variable.
- Create a new policy to read in the SSM parameter and attach this policy to the doc app callback lambda.
- Usually we retrieve the client id from the users session. However, AUT-936 is aimed at handling users who do not have a valid session and therefore we not have the users client id available to us. This means we need to store the client ID in config so it can be accessed by the lambda when needed.
=> AUT-963 - Store Doc App RP Client ID in parameter store

ci/terraform/oidc/token.tf, shared/src/main/java/uk/gov/di/authentication/shared/entity/CustomScopeValue.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
This was a temporary scope implemented to help in our SOLID discovery and is no longer needed.
=> BAU: Remove `resource-id` custom scope and code to add to tokens

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
- Tidy up phone validation logic
- We allow + to be used on both UK mobile numbers and International phone numbers so only checking the second part of the if statement if it doesn't contain an + doesn't make the validation easy to follow.
- The backend doesn't know what type of number it is validating but we should still protect it by enforcing a size limit.
=> AUT-969 - Tidy up phone validation logic

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/site.tf, ci/terraform/oidc/ssm.tf
WAF rules exception for the smoke test client.
This PR overrides a specific WAF rule for the smoke test client only.  The client id is added to SSM in the smoketest pipeline and retrieved when creating the OIDC api.
The smoke test microclient runs on localhost in the smoke test, however the WAF will block authorize requests containing a redircect_uri to localhost, so the smoke test will not run.
https://github.com/alphagov/di-authentication-smoke-tests/pull/69
https://github.com/alphagov/di-authentication-smoke-tests/pull/66
=> AUT-834: WAF rules exception for the smoke test client

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppAuthorisationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java
- Add retry policy when calling DCMAW JWKs endpoint
- Rather than adding in our own implementation of a retry policy I.E using a while loop. We can take advantage of the nimbus library and use the https://www.javadoc.io/doc/com.nimbusds/oauth2-oidc-sdk/5.10/com/nimbusds/oauth2/sdk/jose/jwk/JWKSource.html. This allows you to set certain properties such as retrying.
- By default set the cache and rate limited to false until we have a better understanding of how this might work via key rotations.
- When try to call the DCMAW JWKs endpoint we are seeing intermittent network errors. The JWKs is served out of an S3 bucket sitting behind an api gateway and is known to throw a 503. AWS suggests that the consumer adds in a retry policy - https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing- …
=> AUT-1065 - Add retry policy when calling JWKs endpoint

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
This implements ADR 0071 to expose our journey id to RPs on the ID token as session identifier
=> BAU: Include session id (`sid`) on ID tokens

ci/terraform/account-management/staging-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars
Point staging at one login rename templates in prod Notify account.
Draft templates for the name change have been updated in the Notify test account.  These templates have been copied to the Notify production account as release candidates.
This PR points staging at the release candidate templates so they can be tested in staging.
The configuration here (the new template ids) will be rolled out to prod at the required time so that the current templates are replaced with the new updated ones.
A new Notify production api key should be created and configured in the pipeline before merging so that message requests from staging are routed to the Notify production account.
Enable testing of the new release candidate templates in staging.
Test configuration of the new template ids before moving …
=> AUT-938: Point staging at One Login rename templates in prod Notify account

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
- Add new account status to auth code issued audit event. 
- **Note:** I have also added a new account status type relating to the Doc App Journey to make it clearer when a recurring sign-in is using this mechanism.
- Allows performance analysts to differentiate between sign in and account creation journeys for this event (broadly analogous to first point of handover back to RPs)
=> AUT-982: Add new account status to auth code issued audit event

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
Downgrade missing template messages from error to warn.
Avoid triggering an alert for missing template ids.
Staging templates are currently deployed to the prod notify account in order to facilitate an easier rollout from staging to prod for the GOV.UK One Login name change.
We don't want to include staging messages in message totals, but also don't want alerts to trigger.
#2746
=> AUT-938: Downgrade missing template messages from error to warn

ci/terraform/oidc/doc-app-callback.tf
Increase doc app callback alarm threshold to 10.
Reduce alert noise in the 2nd line channel.
=> BAU: Increase doc app callback alarm threshold to 10

ci/tasks/deploy-test-services.yml, ci/terraform/test-services/audit.tf, ci/terraform/test-services/variables.tf, test-services-api/src/main/java/uk/gov/di/authentication/testservices/domain/TestServicesAuditableEvent.java, test-services-api/src/main/java/uk/gov/di/authentication/testservices/lambda/DeleteSyntheticsUserHandler.java, test-services-api/src/test/java/uk/gov/di/authentication/testservices/DeleteSyntheticsUserHandlerTest.java
Add auditing to the test services api.
- Audit when a test user is deleted.
- Audit when an attempt is made to delete a test user, but the user does not exist.
The test services api is currently running in build and integration, and is consumed by the create account smoke test (which runs only in integration).  When auditing is in place the smoke test should be able to move to production.
Provide an audit record for whenever a test user is deleted.
Infrastructure PR
=> AUT-829: Add auditing to the test services api

ci/terraform/test-services/delete-synthetics-user.tf
Give delete synthetics user txma queue url.
Fix QueueDoesNotExistException.  Audit cannot currently post audit messages to the queue.
#2725
=> AUT-829: Give delete synthetics user txma queue url

ci/terraform/test-services/delete-synthetics-user.tf
Add txma queue access policy to test services execution role.
Fix 'Access to resource denied' errors.
Allows the lambda to post audit messages.
#2761 
#2725
=> AUT-829: Add txma queue access policy to test services execution role

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
Add smokeTest flag to client registry entry.
Accept test numbers in production for smoke tests only.
Add additional logging when validating phone numbers.
Provides ability to accept test numbers for smoke tests in production
Previously when validating phone numbers for new accounts we did not accept test numbers as valid in the production environment.  This PR adds an extra flag to a client registry entry to indicate whether the client is a smoke test client.  If so then test numbers are accepted so that the create account smoke test can succeed.
Additional logging added for phone number validation so we can see exactly which validation rule is failing for an invalid number.
https://github.com/alphagov/di-authentication-smoke-tests/pull/86
=> AUT-829: Add smokeTest flag to client registry entry

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
Log sms bucket error for smoke test.
Receiving an 'Exception thrown when writing to S3 bucket' bucket error so adding additional logging to understand the cause.
https://github.com/alphagov/di-authentication-smoke-tests/pull/86
https://github.com/alphagov/di-authentication-smoke-tests/pull/94
=> AUT-923: Log sms bucket error for smoke test

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
Log stacktrace for smoke test sms bucket exceptions.
The error message is null so need to log the stacktrace for more information
#2782
=> AUT-923: Log stacktrace for smoke test sms bucket exceptions

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
Only put otp in the test bucket for certain message types.
When running smoke tests (and test client tests) we put the otp in a bucket for the test client to retrieve.  However, not all Notify message types send an OTP, so there is no need to put the otp in the bucket for those messages.
Fixes an error when the create account smoke test runs.
=> AUT-923: Only put otp in the test bucket for certain message types

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
Accept FIXED_LINE_OR_MOBILE numbers.
Following IPN switch-on we are seeing traffic from countries where number ranges can either be fixed or mobile.  Add support for these numbers so that we accept them through phone number validation.
https://groups.google.com/g/libphonenumber-discuss/c/flHAmI5-1sw
=> BAU: Accept FIXED_LINE_OR_MOBILE numbers

.github/workflows/build-api-modules.yml
GitHub Actions to build and push modules:
- builds each module, packaging as a zip
- uploads built artifact to S3
- runs signing job against artifact
Supporting efforts to move off Concourse
Depends on https://github.com/alphagov/di-infrastructure/pull/471
=> GitHub Actions to build and push modules

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
- Add cloudwatch metrics to the DCMAW handoff and callback lambdas
- Ensure the state param is not empty before processing with the no session access denied response back to the RP
- This will enable us to determine how many users we send off to DCMAW and how many we receive back
- The DocAppCallback lambda metrics will track how many responses were - 
1. **Successful and returned to the RP**
2. **Had a valid session but unsuccessful and then returned to the RP**
3.  **Didn't have a session and was unsuccessful and then returned to the RP** 
4.  **Token response was unsuccessfu and saw our frontend error page**
5. **Userinfo response was unsuccessful and saw our frontend error page**
=> AUT-963 - Add metrics to the DCMAW handoff and callback lambdas

ci/terraform/oidc/doc-app-alerts.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/ipv-handoff-alerts.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java
- Build the entire wellknown string in the constructor.
- Make the alerts dependent on the module they are alerting on
- Previously we were creating an instance of the wellknown endpoint in the constructor but then setting everything in the handler. We can simplify this by setting all the attributes in the constructor and then just referencing the generated string in the handler itself.
- The attributes of the wellknown endpoint hardly change and when they do it usually forces a deploy of the handler anyway.
- It should have no real impact on cold starts as are already constructing the wellknown object inside the constructor itself
- The alerts use the cloudwatch log groups of certain lambdas so we need to make sure they are created before the alerts are
=> BAU - Refactor wellknown endpoint

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Put reset password SMS behind feature flag
- So it can be tested in lower environments whilst preventing other features from being deployed to production
=> AUT-1079 - Put reset password SMS behind feature flag

shared/src/main/java/uk/gov/di/authentication/shared/entity/NoSessionEntity.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/NoSessionException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/NoSessionOrchestrationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/NoSessionOrchestrationServiceTest.java
- The NoSessionOrchestrationService is called in the scenario where no session cookie is found for the user once the user returns from either DCMAW or IPV.
- The main method in this class is the `generateNoSessionOrchestrationEntity` which checks if the query parameters it receives contains an `access_denied` error response along with a `state` parameter. It will also check that this feature is enabled as to start with it will not be enabled across all environments to allow testing.
- If the access_denied error response and state parameter are both present, it will perform a lookup in Redis using the state to retrieve a client session id. It will use that client session id to perform an additional lookup in Redis to retrieve the client session of the user. The client session is required …
=> AUT-1125 - Create shared class for no session orchestration logic

.github/workflows/build-api-modules.yml, .github/workflows/pre-merge-checks.yml
AdoptOpenJDK is no longer maintained, it is now Temurin
See https://github.com/actions/setup-java#supported-distributions
=> AdoptOpenJDK is no longer maintained, it is now Temurin

ci/terraform/oidc/production-overrides.tfvars
Enable support for ui_locales parameter to choose Welsh language in production.
This parameter allows services to specify the user's preferred language for the journey (English or Welsh).
The parameter is currently enabled in all other environments but not in production.
=> BAU: Enable support for ui_locales parameter to choose Welsh language in production

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/AuthPolicy.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/exceptions/MissingConfigurationParameterException.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthoriseAccessTokenIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java, ci/terraform/account-management/send_otp_notification.tf
- Make OTP codes fixed in account management journeys
- Similar work has previously been performed for sign in journeys
Note: I considered making the changes to the lambdas that end up verifying a code (e.g. `UpdateEmailHandler`) instead of the one that writes the code (`SendOtpNotificationHandler`). The reason I did not take that approach was twofold:
- Writing a fixed OTP to the cache, although somewhat wasteful in terms of cacheing resource, is closer to the 'real' user flow, and therefore a legitimate part of performance testing
- Doing things this way meant that existing lambdas, apart from the OTP Notification lambda, could be left untouched, keeping them 'pure' in terms of not modifying them solely for testing purposes (and marginally more readable)
- To enable performance testing …
=> AUT-973: Make OTP codes fixed in account management journeys

ci/tasks/deploy-acct-mgmt-api.yml, ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/variables.tf
- Add params to Account Management deploy job
- Some environment variables were missing for configuration service in AM lambdas
- This affected fixed OTP functionality for test users
- Amends: https://github.com/alphagov/di-authentication-api/pull/2814
=> AUT-973: Add params to Account Management deploy job

.github/workflows/build-api-modules.yml, ci/tasks/build-api-module.yml, gradle/wrapper/gradle-wrapper.properties
Upgrade gradle to v7.6.1
We were using Gradle 7.0.2, which is a few years old now!
=> Upgrade gradle to v7.6.1

ci/tasks/build-api-module.yml
Revert Gradle version change
Docker image doesn't appear to work in Concourse
=> Revert Gradle version change

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
- Switch the DocAppCallback lambda to use the NoSessionOrchestrationService
- Switch the DocAppAuthorizeHandler to use the NoSessionOrchestrationService
- Remove redundant methods in the DocAppAuthorisationService
- Instead of having the logic within the DocAppCallback lambda we can switch this to use the shared NoSessionOrchestrationService class
- We can remove redundant unit tests which are no longer required as the logic is being tested in the NoSessionOrchestrationServiceTest.java
- The methods in the DocAppAuthorisationService have been moved to the NoSessionOrchestrationService
=> AUT-1125 - Switch Doc App lambdas to use shared NoSessionOrchestrationService class

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
Support 'verify change how to get security codes' email message types.
- Exposes the ability to send this OTP email to the frontend api
- To be consumed by frontend changes for when the user clicks the 'change how you get security codes' link on the 'Check your phone' page.
- Adds a case to handle VERIFY_CHANGE_HOW_GET_SECURITY_CODES in the SendNotificationHandler
- Add a new key type so that the OTP can be stored in Redis like the other OTPs.
- Follows the model for VERIFY_EMAIL with respect to blocking rules for failed OTP attempts.
- Update unit tests to test the new notification type.
Users will be required to enter an OTP sent by email in order to attempt to change how they get security codes.
#2811
=> AUT-1081: Support 'verify change how to get security codes' email message types

integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/NoSessionOrchestrationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/NoSessionOrchestrationServiceTest.java
- Update error_description of for access_denied no session error
- So it is clear to RPs what the error is and to differentiate between other access_denied responses
=> AUT-1125 - Update error_description of for access_denied no session error

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
- Put the users email address as an additional claim named 'email_address' in the signed and encrypted JAR
- This is required so IPV can pass this onto the F2F CRI
=> AUT-930 - Pass email address to IPV Core

shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
- Add a new field to the client registry called LandingPageUrl.
- This will be required for RPs that support identity verification and will be used specifically for when users participate in the face to face journey.
=> AUT-1139 - Add Landing Page URL to client registry

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
- Add client landing page url to the IPV_AUTHORISATION_REQUESTED audit event
- There are a couple of clientIds at play in the IPVAuthorisationHandler. The RPs clientID and the IPV client ID. Be explicit in the variable name for each clientID
- The clientLandingPage URL is required of the audit event as part of the face to face journey.
=> AUT-1121 - Add client landing page url to the IPV_AUTHORISATION_REQUESTED audit event

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/api-gateway-frontend.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountRecoveryRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountRecoveryResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountRecoveryIntegrationTest.java
- Create an account recovery lambda
- Logic will be added to this lambda which will help it make that decision
- Add the terraform to create the account-recovery lambda which will sit behind the frontend-api and therefore require api key authenticaiton
- This lambda will be responsible for informing the frontend whether a user is permitted for account recovery or not
=> AUT-1147 - Create account recovery lambda

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountRecoveryBlock.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountRecoveryBlockService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Update AccountRecoveryBlock table and set the timeToExist to the Long object type rather than the primitive. 
- Create a Dynamo service which will be used to write and read the AccountRecoveryBlock dynamo DB table.
- Ensure all reads to the the AccountRecoveryBlock table are consistent 
- Add a default TTL of 48 hours to the configuration service 
- Null values will sometimes be required for the timeToExists attribute and primitives do not allow nulls
- We will need to know pretty sharpish whether there is an entry in the table for a given email. The default is eventual consistency which will not promise this
- If required, we can lower the TTL for certain environments to make testing easier
=> AUT-1155 - Update AccountRecoveryBlock table and create new Dynamo service

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/dynamo-policies.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountRecoveryBlockService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountRecoveryIntegrationTest.java, shared-test/build.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountRecoveryStoreExtension.java
- Add logic to account recovery lambda
- Integrate the DynamoAccountRecoveryBlockService within the AccountRecoveryHandler
- Create a AccountRecoveryStoreExtension to enable us to add data to the table for the Integration tests
- Add new unit and integration tests to test various scenarios
- Give the account recovery lambda read permissions to the account-recovery-block dynamo table
- So the AccountRecoveryHandler knows whether account recovery is permitted or not
- The AccountRecoveryHandler only ever needs to read from the table so we can avoid giving it write permissions
=> AUT-1147 - Add logic to account recovery lambda

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/dynamo-policies.tf
- Ensure policy has been created before deploying lambda
- The deployment is erroring because it is saying the lambda does not have permissions to perform describeTable. This will ensure that the policy exists before deploying the lambda
=> AUT-1147 - Ensure policy has been created before deploying lambda

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/reset_password.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountRecoveryBlockService.java
- Create additional policies to the account recovery block table
- Assign the read and write policies to the reset password lambda role
- The reset password lambda will require permissions to read and write to the new table
=> AUT-1156 - Create additional policies to the account recovery block table

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, integration-tests/build.gradle, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountRecoveryStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- If a user resets their password with a verified SMS then set a block with a TTL.
- If a user resets their password with a verified Auth App then set a block with No TTL.
- Enable account_recovery_block for build only
- Required as part of the account recovery journey
=> AUT-1156 - Add block when user resets their password with verified MFA 

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf
- Give permissions to verify lambdas to delete and read from account recovery table
- Clear depends_on from account-recovery.tf as it is no longer needed
- Verify code lambdas require permissions to delete and read from the account recovery table
=> AUT-1156 - Give permissions to verify lambdas to delete and read from account recovery table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountRecoveryBlockService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
- Delete any block what exists when a user enters valid Auth App or MFA otp
- If there is any block present in the account recovery table and a users enters a valid SMS or Auth App OTP then ensure we remove the block
=> AUT-1156 - Delete block when user successfully enters sign in OTP 

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java
Send persistent id in the correct field in the audit api.
The persistent Id is currently in the wrong place.
=> BAU: Persistent Id in the wrong field in audit event

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordRequest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
- Remove legacy code from ResetPasswordRequest
- We don't use the useCodeFlow boolean passed into the request and assume it is always the code flow so we can remove this.
=> BAU - Remove legacy code from ResetPasswordRequest

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
- Attach the persistentSessionId to the log line in the BaseFrontendHandler to ensure every lambda that extends it automatically gets the ID attached. There were several lambdas which extended the BaseFrontendHandler that didn't have the persistentSessionId attached.
- Remove the manual attaching of persistentSessionId from any lambda that extends the BaseFrontendHandler.
- Ensure that any lambda that does not extend the BaseFrontendHandler attaches the persistentSessionId to the log line, when possible.
- So that we can track a persistentSessionId across all lambdas which reduce any gaps in our logging
=> BAU - Ensure persistent session ID is attached to log lines when available

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars
- Enable cross browser support in non prod for DCMAW
- To enable testing of the cross browser solution
=> BAU - Enable cross browser support in non prod for DCMAW

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
- Attach the client_id to the logs in the BaseFrontendHandler to avoid every lambda that extends that class to have to attach it. There were previously several lambdas not doing so which meant the client_id was missing
- Remove attaching the client_id to the logs from all lambdas that extend the BaseFrontendHandler
- Attach the RP client_id to the logs in the DocAppAuthorizeHandler instead of the Doc app client id
-  To give us more complete and accurate logging
=> BAU - Plug in missing client_ids into logs

ci/tasks/deploy-shared-api.yml, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/test-account-recovery-block.tf, ci/terraform/shared/variables.tf
Terraform to add test account-recovery-block to the database.
Adds a facility to set account-recovery-block for test users in the pipeline.
Will be used to setup test data for account recovery acceptance tests.
https://github.com/alphagov/di-infrastructure/pull/483
=> AUT-1182: Terraform to add test account-recovery-block to the database

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars
- Enable cross browser solution for IPV non prod only
- So the cross browser solution can be tested in non production environments
=> BAU - Enable cross browser solution for IPV non prod only

ci/terraform/account-management/api-gateway.tf, ci/terraform/account-management/dns.tf, ci/terraform/account-management/sqs.tf, ci/terraform/account-management/variables.tf, ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/authorize.tf, ci/terraform/oidc/dns.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/logout.tf, ci/terraform/oidc/outputs.tf, ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/sqs.tf, ci/terraform/oidc/variables.tf
Decouple usage of DNS, no longer using remote state
This will make things much simpler going forward with migrating away from Concourse/Terraform.
=> Decouple usage of DNS, no longer using remote state

ci/terraform/account-management/dns.tf, ci/terraform/oidc/dns.tf
DNS should be 'account.gov.uk', not 'production.account.gov.uk'
The previous change tried to overwrite the domain mapping for api gateway and failed catastrophically.
=> Fix production DNS name

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
- Explicitly clear the ThreadContext at the start of each lambda 
- We are finding that the ThreadContext is frequently retaining values of previous requests until either the value is overwritten or a new container is spun up.
=> BAU - Clear ThreadContext at the start of each lambda

ci/terraform/account-management/dns.tf, ci/terraform/oidc/dns.tf
Terraform will error instead of destroy zones
This will ensure hosted zones don't accidentally get deleted, as the name server values will be hardcoded in the root zone.
=> Terraform will error instead of destroy zones

ci/terraform/account-management/dns.tf, ci/terraform/oidc/dns.tf
Add existing APIGW custom domain and set up DNS records to point to it.
Final steps in separating DNS for Auth.
=>  Add (existing) custom domain and set up route53 to point to it 

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
This exposes the `sid` claim in ID tokens with the session ID for RP consumption
=> BAU: Enable session ids in ID tokens for all non-production environments

ci/terraform/oidc/wellknown.tf
The handler was crashing because it needs this environment variable set.
=> BAU: Well-known handler needs to know `FRONTEND_BASE_URL`

shared/src/main/java/uk/gov/di/authentication/shared/helpers/PhoneNumberHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java
This data is currently only available for sign-in journeys and we want to make it more available for analysis.
=> BAU: Add extension with country code to audit events with phone numbers

ci/terraform/shared/test-user.tf, ci/terraform/shared/variables.tf
Remove optional Terraform variable when creating test users with auth app credentials.
Optional is experimental in Terraform.  Checking for empty string instead.
#2914
=> AUT-1182: Remove optional Terraform variable.

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java
NOTE: This PR alone is not intended to change any business logic. It is just to 'fill' the cache with new prefix values so that a subsequent PR can change the business logic without any loss of continuity in production
- Add an MFA type-specific counter for incorrect MFA code inputs
- Currently we 'count' incorrect MFA code inputs in the cache, stored against email address
- However, there is only one counter for all MFA types
- We want to separate counters by MFA type so that e.g. incorrect auth app inputs will not reduce the number of attempts allowed for SMS OTP
- To do this we will introduce a new prefix approach which adds in the MFA Type in the prefix
- To ensure continuirty in prod, we will deploy this change first which duplicates the incorrect MFA counter, without changing any …
=> AUT-1209: Record new incorrect MFA input counter

ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars, ci/terraform/shared/production-stub-clients.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging-stub-clients.tfvars, ci/terraform/shared/stub-rp-clients.tf, ci/terraform/shared/variables.tf
Make stub client ServiceType configurable.
Add an OPTIONAL stub client in build.
Enable testing of the save and resume scenario which requires an OPTIONAL type client.
=> AUT-1138: Make stub client ServiceType configurable

ci/terraform/shared/test-user.tf
Assign T&C version from variable when creating seed test user.
Config that sets the version in the pipeline was being ignored.
https://github.com/alphagov/di-authentication-api/pull/2917
=> BAU: Assign T&C version from variable when creating seed test user

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java
- Auth app validator will increment a counter in code storage service cache which is specific to its MFA Type
- SMS will continue to use a generic (non-SMS-specific) prefix until the validation method can be switched out from using the static validation helper to using `MfACodeValidator`'s class methods
- This means that in the `VerfifyMfaCodeHandler`, we still need to delete the counter for both the MFA specific and generic prefixes, see: `blockCodeForSessionAndResetCountIfBlockDoesNotExist()` method for where this happens
- Note: The business logic change applies only to auth apps. SMS will continue to use the 'old' style prefix for now because it uses an older validator helper rather than the methods of the parent class whilst validating OTP correctness. This is deemed okay because the …
=> AUT-1209: Switch auth app validator to use independent counter

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/TermsAndConditionsHelper.java
- Even if the Smoke Test user hasn't accepted the latest terms and conditions we will bypass this in the login handler and return true to the frontend.
- This remove the dependency on the smoke test from when we update the terms and conditions
- We don't test the terms and conditions in the smoke test, we only check the minimal flow to ensure the service is working.
=> BAU - Return accepted terms and conditions for smoke test client

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
Set any existing auth app to not enabled when adding a phone number.
So that users can switch between 2fa types for account recovery
=> BAU: Set any existing auth app to not enabled when adding a phone number

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
- Record MFA code block twice with two different prefixes (one general, one that includes the MFA Method Type)
- The new prefix adds an extra qualifier for MFA Method Type, which will not be used yet
- This will allow us to switch the 'is blocked for MFA codes' checks to be specific to a single MFA type so that e.g. an SMS block does not prevent auth app use
=> AUT-1210: 'Double count' MFA code blocks

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/VerifyMfaCodeRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java, shared/src/main/java/uk/gov/di/authentication/entity/CodeRequest.java, shared/src/main/java/uk/gov/di/authentication/entity/VerifyMfaCodeRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidatorTest.java
- Update the users phone number or auth app secret in the VerifyMfaCodeHandler for registration requests
- Use the authAppSecret in the VerifyMfaCodeRequest to validate the code for AUTH_APP registration requests 
- We can leave the updating of the user profile in update-profile there for now as the call to the `/verify-mfa-code` endpoint will just overwrite it if it exists
- Validate Auth App secret in VerifyMfaCodeHandler
- Add audit events for when the profile is updated in VerifyMfaCodeHandler
- This is required so that we can retain the users existing MFA method until their new one has been confirmed during the account recovery journey.
=> AUT-1207 - Update the MFA Method for registration requests in the VerifyMfaCodeHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
- Port phoneNumber validation to send notification
- We will soon stop calling update-profile for phone numbers but we don't want to lose the backend validation.
=> AUT-1207 - Port phoneNumber validation to send notification

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
- Currently the behaviour is the same as VERIFY_CODE although additional functionality will be added shortly
- There will be further work to ensure it can support the additional error scenarios 
- So VerifyCode can support requests with the VERIFY_CHANGE_HOW_GET_SECURITY_CODES
=> AUT-1168 - Add support to verify code for notification type VERIFY_CHANGE_HOW_GET_SECURITY_CODES

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
- Remove support for ADD_PHONE_NUMBER and REGISTER_AUTH_APP from update-profile
- These two update profile types have been ported to the verify-mfa-code endpoint and are therefore redundant in update-profile so they can be removed
=> AUT-1207 - Remove support for ADD_PHONE_NUMBER and REGISTER_AUTH_APP from update-profile

ci/terraform/shared/dynamodb.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountModifiers.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountRecovery.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountModifiersService.java
- Create a new Dynamo table to track when an account is unable to perform account recovery
- The existing account recovery block table is not yet in production and is not scalable if we decide to add additional fields to the table etc. The Account Modifiers table isn't limited to account recovery and is able to scale if we decide to add additional features
=> AUT-1218 - Create Account Modifiers table

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/verify_mfa_code.tf
- Create Read, Write and Delete policies for the new Account Modifiers table.
- For now, give the 3 lambdas which will interact with this table Read permissions only. Additional permissions will be added as and when required.
- So the Lambdas are able to interact with the Account Modifiers table
=> AUT-1218 - Create Dynamo policies got Account Modifiers table

ci/terraform/oidc/verify_code.tf
- Give VerifyCode read and write access to account modifiers table
- The account modifiers table will replace the account recovery block table
=> AUT-1218 - Give VerifyCode read and write access to account modifiers table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java, shared/src/main/java/uk/gov/di/authentication/entity/VerifyMfaCodeRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/JourneyType.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidatorTest.java
Part 1 of AUT-1242 introduces `JourneyType` parameter in the `VerifyMfaCodeRequest` object for journey type values of:
-  Registration
- Account Recovery
- Sign In
- So that the VerifyMfaCode lambda is aware of what journey is being parsed in the request
- Break the work required for AUT-1242 into multiple PRs
=> AUT-1242-part-1: Introduce JourneyType parameter in VerifyMfaCodeRequest

ci/terraform/modules/lambda-role/role.tf
Use for_each instead of count for creating aws_iam_role_policy_attachment resources.
Following the incident today, it is clear that using for_each over count will be more deterministic and won't break if the order of policies changes.
=> Use for_each instead of count for creating aws_iam_role_policy_attachment resources

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/DynamoAccountModifiersService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
- Clear account modifiers block when user verifies their MFA SMS code
- The account modifiers table is replacing the account recovery block table. Instead of clearing the account recovery block table when a MFA SMS OTP has been verified, we will set the account blocked to false if it exists for that user in the account modifiers table.
=> AUT-1218 - Clear account modifiers block when user verifies their MFA SMS code

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
- Attach clientSessionId to SPOTResponseHandler
- So we have more visibility when debugging journeys
=> BAU - Attach clientSessionId to SPOTResponseHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java, shared/src/main/java/uk/gov/di/authentication/entity/VerifyMfaCodeRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/JourneyType.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidatorTest.java
Part 1 of AUT-1242 introduces `JourneyType` parameter in the `VerifyMfaCodeRequest` object for journey type values of:
-  Registration
- Account Recovery
- Sign In
- So that the VerifyMfaCode lambda is aware of what journey is being parsed in the request
- Break the work required for AUT-1242 into multiple PRs
=> AUT-1242: Add optional journey type parameter to VerifyMfaCode request

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
- Add audit event for when account recovery block is added
- When a user with a verified MFA method resets their password then a account recovery block will be added to the account modifiers table. Add an audit event for when this block is added
=> AUT-1180 - Add audit event for when account recovery block is added

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java, shared/src/main/java/uk/gov/di/authentication/entity/VerifyMfaCodeRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeValidatorTest.java
- Stop using the isRegistration and start using the JourneyType in the VerifyMfaCodeHandler
- Once the isRegistration stops being sent we can remove it completely
- Make JourneyType mandatory and isRegistration optional
- The JourneyType will support account recovery, registration and sign in so we no longer need the isRegistration attribute in the request
=> AUT-1242 - Start using journeyType in VerifyMfaCodeRequest

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeProcessor.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeProcessor.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeProcessorFactory.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeProcessor.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeProcessorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeProcessorFactoryTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PhoneNumberCodeProcessorTest.java
- Rename code validator classes to code processor
- We will want these classes to do more than just validate. Make them more generic by renaming the classes to processor instead
=> AUT-1242 - Rename code validator classes to code processor

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
- Ensure that the PhoneNumberCodeProcessor can process a code which has been sent in alongside JourneyType ACCOUNT_RECOVERY
- If the OTP code is valid, add logic to the PhoneNumberCodeProcessor to update MfaMethod and remove old MfaMethod if one exists
- Add a metadata pair to the update profile audit event to indicate whether the profile has been updated as part of the account recovery journey
- So the VerifyMfaCodeHandler can be used as part of the account recovery journey and update the MFA method
=> AUT-1242-1180 - Add support for SMS account recovery in the PhoneNumberCodeProcessor

ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactory.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java
- Add permissions to the verify-mfa-code lambda to write to the account modifiers table so that the lambda can set the block to false when a block is present and the code for the sign in request is valid.
- Add an audit event ACCOUNT_RECOVERY_BLOCK_REMOVED for when the block is present and has been removed.
- The account modifiers table has replaced the account recovery table 
- When a user has successfully verified their auth app during sign in, we can remove any block that is present. Note that this is only for Auth App sign in as SMS sign in verify code logic lives in the VerifyCodeHandler
=> AUT-1218 - Clear account recovery block if present for successful auth app sign in

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/shared/dynamodb.tf
- Remove account recovery block table
- This is the last part of the old account recovery block table which can now be removed
=> AUT-1218 - Remove account recovery block table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
- Add an `account-recovery` attribute to audit events which are generated when a user has entered either a valid or invalid OTP code
- Add extra unit tests to improve test coverage
- So we can clearly distinguish whether an OTP has been sent as part of the account recovery journey
=> AUT-1180 -  Add account recovery attribute to audit events for code verification 

ci/terraform/modules/endpoint-module/dynatrace.tf, ci/terraform/modules/endpoint-module/lambda.tf, ci/terraform/shared/code-signing-config.tf
Adds the Dynatrace OneAgent layer to our Lambdas.
This will instrument the API lambdas within Dynatrace.
=> Add OneAgent to apis

account-management-api/src/main/java/uk/gov/di/accountmanagement/helpers/PrincipalValidationHelper.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/helpers/PrincipalValidationHelperTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-integration-tests/build.gradle, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/RemoveAccountIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePasswordIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountModifiersStoreExtension.java
- When a users account is deleted ensure that we remove any entry from the account modifiers table by using the dynamo delete service to delete the account
- Remove the check of principal against public subject ID
- Always run `compose-down` after the Account Management Integration tests have run 
- It's important to clear up any data associated with that user 
- The public subject ID was swapped with the internal sub id in December last year so this check is redundant
=> AUT-1286 - Delete from Account Modifiers table when deleting users account

ci/terraform/oidc/wellknown.tf
AWS have recently released Java 17 as a default lambda runtime.
This only updates the runtime, not the build version.
=> AUT-1297: Upgrade build environment default lambda runtime to java 17

ci/terraform/oidc/wellknown.tf
This reverts commit 9aafd82ac8a9be09e892ac90fad1f7050ef9422a.
We need to upgrade our version of the AWS dependency first
=> Revert "AUT-1297: Upgrade build environment default lambda runtime to java 17"

ci/terraform/oidc/userexists.tf
- Give userexists lambda write permissions
- In case it needs to update the salt
=> AUT-1183 - Give userexists lambda write permissions

ci/terraform/oidc/sqs.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
Log smoke test otp and phone number in integration only.
Create account smoke tests are failing intermittently due to the test otp being incorrect.  Adding additional logging to help diagnose the issue.
=> BAU: Log smoke test otp and phone number in integration only

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
Store block with a new Redis key specific for Account Recovery Journey when notification type is `VERIFY_CHANGE_HOW_GET_SECURITY_CODES`
- Uses `account-recovery-code-blocked:` as new key
Minimise duplication of blocks so that it doesn't clash with other blocks for different notification types.
=> AUT-1292: Use new Redis key for account recovery when verifying OTP code

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
Add log info in `isCodeblockedForSession` method.
Visibility purpose to ensure OTP is blocked for account recovery
=> AUT-1281: Add log info for visibility purpose to ensure otp is blocked for account recovery

.github/workflows/build-api-modules.yml, ci/terraform/account-management/dev.tfvars, ci/terraform/account-management/read_secrets.sh, ci/terraform/audit-processors/dev.tfvars, ci/terraform/delivery-receipts/dev.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/read_secrets.sh, ci/terraform/shared/dev.tfvars, ci/terraform/shared/read_secrets.sh, ci/terraform/test-services/dev.tfvars, ci/terraform/test-services/read_secrets.sh, ci/terraform/utils/dev.tfvars
To make the `auth-deploy-pipeline` run terraform the following have been created for each component:
- `dev.tfvars` file containing the input vars
- A `read_secretes.sh` file to get any secrets from SM
[PLAT-1412: Create the configs for each terraform component](https://govukverify.atlassian.net/browse/PLAT-1412)
Passing build for all comps: https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/761723964695/projects/Deploy-auth-deploy-pipeline-dev/history?region=eu-west-2&builds-meta=eyJmIjp7InRleHQiOiIifSwicyI6e30sIm4iOjIwLCJpIjowfQ
=> Adding configuration files for all terraform components

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Bumps the `terms_and_conditions` version to `1.3`
To reflect changes to the Terms and Conditions that will be released on 22 May. The three PRs necessary to make this change will be merged on 22 May. 
* https://github.com/alphagov/di-authentication-frontend/pull/1010 changes the privacy notice text
=> AUT-1217: Bump Terms and Conditions minor version to reflect changes

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PasswordValidator.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/validation/PasswordValidatorTest.java
- Remove unused password validator method from ValidationHelper
- The method was only used by the unit test, so remove the validatePassword method from the ValidationHelper and remove the unit tests.
- Move the hasAtLeastOneDigitAndOneNonDigit method to the PasswordValidator and make it a private method as it is only used by the validate method in the PasswordValidator class
=> BAU - Remove unused password validator method from ValidationHelper

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
- The frontend needs a different error code for account recovery to verify email exceeded attempts so it can perform different behaviour and show the relevant screen. Therefore when a user has exceeded the amount of OTP attempts for account recovery or is already blocked we will return the ERROR_1048.
- Modify tests to ensure we have sufficient coverage and there are no duplications
- Users can be blocked when they exceed the number of OTP attempts for account recovery email OTPs. This is different to email OTPs for registration where users cannot be blocked when entering incorrect OTPs.
=> AUT-1281 - Return correct error when account recovery email OTPs are blocked

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
Only warn on sendCriDataRequest failure to reduce alerting fatigue.
An upstream issue with DCMAW is causing a very high error rate, leading to too much alerting noise.
=> Only warn on sendCriDataRequest failure to reduce alerting fatigue

ci/terraform/oidc/alerts.tf
Switch DLQ alarms to Avg rather than Sum.
Sum is adding up the number in the queue every minute for 5 minutes, instead of just seeing if the number in the queue is above the threshold.  For example, if there are 3 items in the DLQ the alarm value is currently 15 as it adds up the number in the queue every minute for 5 mins.
=> BAU: Switch DLQ alarms to Avg rather than Sum

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SendNotificationRequest.java
- Add JourneyType to SendNotificationRequest
- There are some scenarios where different journeys use the same notification type and there is no way to tell the difference which journey the user is going through. This can cause issues when applying blocks. An example of this is sending SMS otps for registration and sending SMS otps for account recovery.
=> AUT-1282 - Add JourneyType to SendNotificationRequest

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
- When a user has requested too many email OTPs for account recovery, save the block with a different prefix. 
- When checking if the code request attempt is valid, use the account recovery prefix to check if there is an existing block in place for when a user has entered the account recovery email OTP incorrectly too many times or has requested too many account recovery email OTPs.
- To ensure it doesn't interfere with other blocks in the user journey
=> AUT-1282 - Use different blocked prefix for account recovery

shared/src/main/java/uk/gov/di/authentication/shared/services/CommonPasswordsService.java
Don't log batch errors when error collection empty.
Errors are being logged for every entry added to the table, even though no errors have occured.
```
"loggerName": "uk.gov.di.authentication.shared.services.CommonPasswordsService",
"message": "Dynamo batch write returned failed batch, with 0 failed batches",
```
=> BAU: Don't log batch errors when error collection empty

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
Additional logging for the notifications sqs handler.
Recreate the 'notifyPersonalisation' map for each message so that it is clear for each message request.
- See how many messages are in the batch
- Log the message id for each message processed.  Will be able to track how many times it takes to process a message and when they are processed.
=> BAU: Additional logging for the notifications sqs handler

ci/terraform/account-management/sqs.tf, ci/terraform/oidc/sqs.tf
Set notification sqs message queue visibility_timeout_seconds to 180s.
Following guidance that this should be six times the lambda handler timeout.
There have recently been unexpected items on the DLQ which should not have been rejected and may be due to throttling.  Changing the config as recommended.
https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#events-sqs-queueconfig
> To allow your function time to process each batch of records, set the source queue's [visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) to at least six times the [timeout that you configure](https://docs.aws.amazon.com/lambda/latest/dg/configuration-function-common.html#configuration-common-summary) on your function. The extra time …
=> BAU: Set notification sqs message queue visibility_timeout_seconds to 180s

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/kms-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
- Initial terraform to set KMS signing policy for auth handler
- Prerequisite for auth handler to access keys for signing
- These will in turn allow OIDC/Orch API to 'communicate' with auth frontend in a secure way
=> AUT-1248: Initial terraform to set KMS signing key policy for auth handler

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Update `terms_and_conditions` minor version.
To reflect an update to the Privacy Notice that is scheduled for 15 June.
https://github.com/alphagov/di-authentication-frontend/pull/1065
=> [Do not merge before 15/6] AUT-1217: Bump Ts&Cs minor version

shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
- Initialize new OTP request counter in caches
- This is a hash map that will break up the existing single-integer counter for all OTP requests
- With the hash map, they will be divided by code request type
- Code request type is a function of notification and journey types
- Prerequisite to populating a new hashmap based counter safely 
- When we implement the counter methods, we want to know that all active sessions in production will contain the initialised hashmap to avoid null pointers
=> AUT-1347: Initialize new OTP request counter in caches

ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/modules/endpoint-module/variables.tf
- Create a new Cloudwatch alarm which triggers on the rate of errors which occur during a 60 second period. The rate is calculated by dividing the number of errors by the number of lambda invocations within a 60 second period. By multiplying this figure by 100, it will give us the rate of errors
- When the rate is greater than 10, then the alarm will trigger
- To ensure the alarm is configured correctly, we will only enable it in Integration to start with and output the alarm to slack
- We will monitor this against our existing alarm, which may be removed in the future if it becomes clear it no longer serves a purpose
- We currently have a Cloudwatch alarm which triggers when a log message at level ERROR is raised. This doesn't capture unhandled errors/exceptions within the lambda itself. …
=> AUT-1346 - Create new cloudwatch alarm to trigger on error rate of lambda

ci/terraform/oidc/authorize.tf
- Adjust error rate for authorize lambda
- Authorize is opened to the public so sometimes it is called without query parameters which causes the lambda to throw an exception and hence increase the amount of errors.
=> AUT-1346 - Adjust error rate for authorize lambda

ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/modules/endpoint-module/variables.tf, ci/terraform/oidc/authorize.tf
- Disable cloudwatch metric alarm for authorize lambda
- Threshold is reguarly getting breached in when the threshold is increased. Disable the alarm for now for the authorize lambda until we can prevent this from happening
=> AUT-1346 - Disable cloudwatch metric alarm for authorize lambda

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SendNotificationRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Add second counter for OTP requests
- Add second counter for OTP requests
- The existing counter is a single integer which counts all OTP requests
- The new counter breaks this count into sub-counters which are grouped by code request type
- In practice code request type is a function of notification type and journey type
- Every combination of notification type and journey type maps to a single code request type
- Increment and reset to zero the counter as required in response to each code request type.
This extended counter solution is first being run in parallel with the existing counters in live in order to allow enough time for the existing sessions using the old counter to drain.  When every user has both types of counters we will be able to remove the old counter method.
Each code …
=> AUT-1347: Add second counter for OTP requests

shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Remove duplicate variable created by merge.
When merging github created a duplicate variable rather than seeing it was the same thing.
#3076 
#3082
=> AUT-1347: Remove duplicate variable created by merge

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Remove old code request counter to use the new implementation where it passes in NotificationType and JourneyType 
Usage of passing in NotificationType and JourneyType in order to differentiate code request counters
[](https://github.com/alphagov/di-authentication-api/pull/3076)
=> AUT-1347: Replace code request count with new implementation

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SendNotificationRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SendNotificationIntegrationTest.java
- Add new prefix for code request block
- This will run alongside existing code request block until cache is filled with 'new style' prefixes
- We will then be able to replace the 'is user blocked for code requests' logic to rely on the new prefix only
- By doing this, we will decouple different types of request block e.g. if a user is blocked from requesting OTPs for email verification, this should not necessarily block them from requesting other OTP types
=> AUT-1348: Add new prefix for code request block

ci/terraform/modules/endpoint-module/alerts.tf
- Enable error rate alarm in Prod
- It's been running in Integration over the weekend so it can be monitored. It seems to be running at the right level now so can be enabled in Production.
=> AUT-1346 - Enable error rate alarm in Prod

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
- A previous commit introduced a new prefix style for OTP request blocking
- Historically, there was a single OTP code request block per session
- The new approach subdivides this by request type
- For example, a block for email OTP in registration does not mean the session is blocked for an SMS OTP request
- This commit builds on that change, by switching over business logic where the blocking status is checked
- It will now use the 'new' (compound) prefix and not the old prefix
- Avoids 'cross pollution' between different types of code request block
- New prefix style introduced here: https://github.com/alphagov/di-authentication-api/pull/3086
=> AUT-1348: Switch OTP request block check to new prefix

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
- Attach clientID to LogoutHandler logs
- This will help us in understanding what RPs are using the logout functionality
=> BAU - Attach clientID to LogoutHandler logs

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/kms-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
- Initial terraform to set KMS signing policy for auth handler
- Prerequisite for auth handler to access keys for signing
- These will in turn allow OIDC/Orch API to 'communicate' with auth frontend in a secure way
=> AUT-1248: Initial terraform to set KMS signing key policy for auth hander

shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/MFAMethodType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java
- CodeRequestType was keyed off NotificationType
- However, this is not universal
- All handlers either have direct access to an MFAMethodType or can infer it from the NotificationType
- The reverse is not true
- Making this change will therefore allow certain handlers e.g. VerifyMfaCodeHandler to use the getCodeRequestType static method
- This will in turn allow all handers to obtain CodeRequestTypes for the purpose of computing Redis prefixes on a per-OTP basis
- By using the same CodeRequestType class as the basis, this will be cleaner and more consistent than if we had two different bases - one for NotificationType and one for MFAMethodType
- Making this change will allow us to make changes to Redis prefixes for OTP/MFA attempts (which happens in the VerifyMfaCodeHandler amongst …
=> AUT-1349: Add MFAMethodType to CodeRequestType

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java
- Set a new prefix code block alongside the existing block when the user has entered the incorrect OTP too many times. During journeys involving `VerifyMfaCodeHandler` and `VerifyCodeHandler`
- The new code block prefix will include an appended `CodeRequestType` ENUM
- This will run alongside existing code request block until cache is filled with 'new style' prefixes
- To prevent code attempt blocks from interfering with one another
=> AUT-1349: Attempt Block

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
- A previous commit introduced a new prefix style for OTP attempts blocking whilst maintaining the existing key prefix 
- Remove the existing code blocked key prefixes in assumption that the Redis cache is now aligned with the new key prefix
- Avoids 'cross pollution' between different types of code block attempts
- Removes old code blocked key prefixes
- New prefix style introduced here: https://github.com/alphagov/di-authentication-api/pull/3101
=> AUT-1349: Replace ATTEMPTS block with new code block prefix

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
Sets session cookie max age to 1 hour (3600 seconds) from 2 hours.
Session duration has been reduced to 1 hour
Several PRs combine to introduce this change in functionality and content
* https://github.com/alphagov/di-authentication-frontend/pull/1078
* https://github.com/alphagov/di-authentication-frontend/pull/1077
* https://github.com/alphagov/di-authentication-frontend/pull/1076
* https://github.com/alphagov/di-authentication-api/pull/3109
=> AUT-1364: Set session cookie max age to one hour

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Reduce email OTP validity on registration journey
- Going from 2 hours to 1 hour
- This reflects that the session is now capped at 1 hour
=> AUT-1372: Reduce email OTP validity on registration journey

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/variables.tf
- Adjust environment values (variable default and Build env override) for OTP validity time
- Only relates to email OTP in account creation journey
- Note: Other OTPs are set separately; only this one varies independently
- We want to test in build
- Initial change was made here: https://github.com/alphagov/di-authentication-api/pull/3115
=> AUT-1372: Adjust env values for OTP validity time

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotifyRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotifyRequest.java
Add sessionId and clientSessionId fields to Notify request objects.
And provide additional constructors.
Groundwork for logging session ids in the Notify handlers when sending messages.
Changes are backwards compatible and introduce the new fields for a ZDD deployment.  This means that the new fields will already be available when the next PR starts to consume them, so there will be no failures related to the new fields being available in the producer before the consumer during a deployment.
=> BAU: Add sessionId and clientSessionId fields to Notify request objects

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/ssm.tf, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf
- Copy public encryption key for auth frontend into TF vars. This relates to KMS that was created in the frontend ([here](https://github.com/alphagov/di-authentication-frontend/pull/1067)) and which has been established in all environments.
- The KMS keypair has been created via Terraform in the frontend repo
- This simply copies the public values and makes them exist as SSM parameters, which are then available to the config service for the OIDC/orchestration authorize lambda
Note: This approach of hard-coding values into TF vars is somewhat brittle. If the KMS ever rotates, this would need to be updated manually, which would be difficult (impossible?) to achieve with zero downtime. And if the KMS is accidentally deleted or anything like that, this would break the entire decryption …
=> AUT-1248: Copy public encryption key for auth frontend into TF vars

ci/terraform/oidc/integration-overrides.tfvars
- Enable account recovery in Integration
- So that the account recovery journey can be performed in the integration environment
=> AUT-1222 - Enable account recovery in Integration

ci/terraform/account-management/variables.tf, ci/terraform/delivery-receipts/variables.tf, ci/terraform/oidc/variables.tf, ci/terraform/test-services/variables.tf
Reduce lambda defaults to sane levels.
20 is far too high and led to costs ballooning accidentally.
=> Reduce lambda defaults to sane levels

ci/terraform/oidc/staging-overrides.tfvars
- Configure staging to the same as production
- Required as part of the performance test initiative
=> AUT-1344 - Configure staging to the same as production

oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/InvalidJWEException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/InvalidPublicKeyException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/SSMParameterNotFoundException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Add auth request passthrough from OIDC API to Auth frontend
- Package certain parameters of auth request as signed and encrypted JWT to be decrypted by Auth frontend
- Currently only client name is being passed as a test field
- Will allow frontend to remove its dependency on client registry
=> AUT-1248: Add auth request passthrough from OIDC API to Auth frontend

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/exceptions/SerializationException.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
- `orElse` is always called regardless of whether the optional is present or not. This has meant that when validatePasswordResetCount has been returning an optional error response as the user is blocked, we are still sending a password reset OTP to the blocked user. We can fix this by using `orElseGet` which is only called when the Optional returned from that method is empty.
- Add extra conditions to our unit tests to ensure that messages are not placed on the SQS queue when the user is blocked.
- Create a custom exception for handling the JsonException checked exception which is thrown when serializing the notify request. We never expect an exception to be thrown here so it should be treated as a 500 if it is thrown.
- To prevent the application sending email OTPs to blocked users.
=> AUT-1402 - Use orElseGet instead or orElse when processing optional

ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IPVCallbackNoSessionException.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
IPVCallbackHandler redirects to a separate error page when there is no session (the session has timed-out).
To be depolyed after the corresponding frontend PR which creates the new error page.
The new page has been added as part of the work to reduce session timeout from 2hrs to 1hr.  Due to the decrease they may be people who land back in authentication having completed IPV after an hour when the session has expired.  The new screen is to provide more information in this scenario.
https://github.com/alphagov/di-authentication-frontend/pull/1081
=> AUT-1371: IPVCallbackHandler redirects to a separate error page when no session

shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
- Add logging to debug bug with email OTP limits for account recovery
- When a user has a verified SMS and performs the account recovery journey, the user is being blocked on the 5 request rather than the 6th request. This is only present when a user has a verified SMS and works as intended if a user has a verified auth app.
=> AUT-1282 - Add logging to debug bug with email OTP limits for account recovery

ci/terraform/utils/common_passwords_update_lambda.tf
Add source_account to invoke permission for common-passwords-update
Flagged as CRITICAL in Security Hub.
=> Add source_account to invoke permission for common-passwords-update

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Uplift terms and conditions version to 1.5.
To accompany the content release of the new terms and conditions for VCs and trigger the T&C acceptance page.
https://github.com/alphagov/di-authentication-frontend/pull/1097
=> AUT-1411: Uplift terms and conditions version to 1.5 [⚠️ Do not merge before 14 July] 

ci/terraform/shared/dev.tfvars
- Removed deprecated deployer role from dev.tfvars
- Part of the work necessary to complete PLAT-1954
- The deployer role assumed by codebuild has all the necessary permissions
=> Remove dev_deployer_role

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
- The verify code handler takes in the following notification types:
- `VERIFY_CHANGE_HOW_GET_SECURITY_CODES`
- `VERIFY_EMAIL`
- `MFA_SMS`
- `RESET_PASSWORD_WITH_CODE`
- Currently for Sign In journey or `MFA_SMS`, the journey type defaults to Registration which is incorrect
- Implement new code attempts block prefix for Sign In journey 
- This is a 2 part PR for bug fix regarding Sign In, first part is to store the new code blocked prefix for Sign In journey along with the old code blocked prefix in order to keep up with the Redis cache
- The second PR will be to remove the old prefix once the Redis cache is up to date
In the Frontend, when a user starts a new session after being blocked from a previous session and they attempt to Sign In, an SMS OTP code is being sent to the user even …
=> AUT-1433-Part-1: Implement new code attempts block for SIGN IN journey

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
- Check that the Doc app subject ID is present in client session
- To avoid nullpointers, check that the doc app subject id is present in the client session and if it isn't we can assume it isn't a valid client session and should redirect to the frontend error page
- We were seeing alerts being triggered due to a nullpointer being thrown
=> BAU - Check that the Doc app subject ID is present in client session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
Deletes MFA code for phone verification once it is entered successfully.
When creating an account, the same OTP can be reused again as the code is not cleared from the user session when it has been used successfully.  For sign in we clear the OTP from the session as soon as it has been used.
This seems to explain why there are intermittent failures in the create account smoke test (the OTP has been cleared from the session by the 15 minute validity period when the test tries to use it for the sixth time).
=> AUT-1333: delete otp code when it is correctly entered

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/JourneyType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
- Implement new code attempts block prefix for Password Reset journey in the Verify Code handler
- This is a 2 part PR, the first part is to store the new code attempts blocked prefix for Password Reset journey along with the old code blocked prefix in order to keep up with the Redis cache
- The second PR will be to remove the old prefix once the Redis cache is up to date
In the Frontend, when a user starts a new session after being blocked from a previous session and they attempt to reset their password, an EMAIL OTP code is being sent to the user even though they are blocked and the user is given another attempt to enter the code again.
=> AUT-1421-Part-1: Implement new code blocked prefix for Password Reset journey

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
This is a second PR to remove the old code block prefix for Password Reset journey as the Redis cache should now be up to date with the new code attempts block prefix.
- Implement code request block prefix for when a user has requested too many Password Reset OTPs
- Implement code attempts block prefix for when a user has requested too many Password Reset OTPs
The first change, which introduces the new code attempt block prefix for new journey type PASSWORD_RESET, where an OTP is validated via the Verify code handler and a block is being set when the user has entered an invalid OTP 6 times.
First PR (https://github.com/alphagov/di-authentication-api/pull/3170)
=> AUT-1421-part-2: Replace existing code attempts blocked prefix

ci/terraform/modules/endpoint-module/lambda.tf
Disables Dynatrace integration.
This will be rewritten, or instrumented automatically, soon.
=> Do not deploy dynatrace integration, pending rewrite

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Update Terms and Conditions version number.
To account for changes to the privacy notice arising from the F2F journey.
https://github.com/alphagov/di-authentication-frontend/pull/1086 makes corresponding changes to the privacy notice.
=> [Do not merge before go-live date] AUT-1370: Update Terms and Conditions version number

ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java, shared/user-dynamo-tables.yaml
- Create new Dynamo bean `AuthCodeStore`
- Create service for reading and writing to the store
- Create feature flag to enable storage of authorization code
- Implement integration tests to ensure service is able to execute read and writes
This is required in order to store the auth session when the /authroize endpoint is invoked
=> AUT-1487: Create new Dynamo table to store authorization code

integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Ensure scope is sent as a string in secure auth request
- Ensure claims are actually added to the secure auth request to authentication
- Remove duplicate Orchestration client_id
- Create integration test for the secure Auth request to Authentication
- Adding additional logging to assist with debugging
- Add additional checks to unit tests
- There were a few bugs in our secure auth request
- Increase testing coverage by validating the contents of what we are sending to Authentication in the secure Auth request
=> AUT-1492 -  Add integration tests and fix bugs for secure auth request to Authentication 

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
Add a CloudWatch metric to track the user sign out journey, and logouts by RPs.
Improve tracking of user journeys.
=> AUT-1289: Add CloudWatch metric to LogoutHandler

ci/terraform/auth-external-api/kms-policies.tf, ci/terraform/auth-external-api/sandpit.hcl, ci/terraform/auth-external-api/sandpit.tfvars, ci/terraform/auth-external-api/shared.tf, ci/terraform/auth-external-api/variables.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, deploy-sandpit.sh
- The corresponding public keys will be hardcoded into `.tfvars` files to be used by the auth callback lambda (this has been done only for sandpit so far as it is the only environment where we can deploy without merging code to main first)
Notes:
- This approach means that the public keys can only be populated after the KMS deployment happens
- As a result zero-downtime rotation would not be possible for this approach
- The auth token lambda, when created, will need a policy to access this KMS in order to sign the tokens
- Part of auth/orch split - the components will need to communicate over OAuth2 protocols in a way which hasn't been the case previously (due to sharing data sources directly)
=> AUT-1254: Add KMS signing key for use by auth token endpoint

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAccessTokenServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccessTokenStoreExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DynamoExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/token/AccessTokenStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AccessTokenService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/user-dynamo-tables.yaml
New access_token_store dynamodb table.
- Create a new table to store access tokens in authentication.
- New service, test extension and integration test to access the new table.
- The table will be created in all environments, but will only be used if a feature switch is on, so no data will actually be populated for the moment until changes using the table are tested and rolled-out.
This table will be used to store access tokens in authentication, replacing the use of redis.  Access tokens are stored so they can be validated against the access token provided by the client (orchestration).
=> AUT-1488: New access_token_store dynamodb table

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf
- Enable account recovery block in all environments
- Change default value and remove per-env overrides
- This is part of putting account recovery journeys live in production
- Corresponding PR for front end MUST NOT be merged until this PR is merged: https://github.com/alphagov/di-authentication-frontend/pull/1122
=> AUT-1223: Enable account recovery block in all environments

ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/site.tf, ci/terraform/utils/bulk_user_email_dynamo_access.tf, ci/terraform/utils/site.tf, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkEmailUsersIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/BulkEmailUsersExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/BulkEmailStatus.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/BulkEmailUser.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BaseDynamoService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BulkEmailUsersService.java
Adds bulk email users table and interface for retrieving and modifying data within it.
Includes:
* Terraform to create a new table.
* Test extension to create and test the table locally.
* Service with data access methods.
* Integration test to test the service
As part of sending a bulk email to update on terms and conditions, we need a new DynamoDB table to store all subject ids and their status (whether we've sent the email already or not).
=> Aut 1441/bulk email table

integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
- Add RP Client ID and Sector Host to secure Auth request to Orchestration
- The RP client ID is needed by Authentication for auditing purposes
- The RP sector host is required to calculate the RP pairwise ID which will be returned in the Authenticaiton userinfo response
=> AUT-1544 - Add RP Client ID and Sector Host to secure Auth request to Orchestration

ci/terraform/utils/production-overrides.tfvars, ci/terraform/utils/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailSenderScheduledEventHandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/NotifyStubExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UserNotFoundBySubjectIdRuntimeException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java, utils/build.gradle, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
Add bulk email sending lambda
Lambda triggered by a cloudwatch scheduled event which reads the contents of the bulk-user-email table, retrieves the email corresponding to the subject id, sends an email to the user, then updates the status for the user email in the table.
The table is read and the emails are sent in batches with a configurable size.  After a batch has been processed sending can be paused (sleeped) for a configurable period in order to throttle email sending if required.
Includes unit and integration tests for the handler.
'getUserProfileFromSubject' in the DynamoService has been updated to throw an exception when a user is not found by subject id.
This PR only adds the code for the lambda handler and tests it.  Infrastructure to deploy the handler will follow.
We want to …
=> AUT-1443: Add bulk email sending lambda

ci/terraform/utils/read_secrets.sh, deploy-sandpit.sh
Add read_secrets.sh script to the utils component.
Build is failing as terraform variables not being read from secrets.
`Error: No value for required variable`
#3227
=> AUT-1471: Add read_secrets.sh script to the utils component

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UnsuccessfulCredentialResponseException.java
In situation that DCMAW `/userinfo` endpoint responds with HTTP 404, DocAppCallbackHandler returns HTTP 302 to HMRC with redirect URI containing `error="access_denied"`, `error_description="Not found"`
Current functionality is to redirect to frontend error page on any error response (including 404) from `/userinfo` endpoint.
=> AUT-1546: Handle 404 responses received from DCMAW

gradle.properties
- Increase JVM memory for build in Github actions
- We are getting an out of memory error
=> BAU: Increase JVM memory for build in Github actions

build.gradle
- Exclude shared-test directory from Sonar code coverage
- As these classes are only used for the purpose of tests, they should not be included as part of the code coverage stats
=> BAU - Exclude shared-test directory from Sonar code coverage

gradle.properties
- Remove MaxPermSize from Gradle properties
- I introduced this in error when trying to increase JVM memory
- The -Xmx2g was to increase JVM heap memory
- However MaxPermSize refers to PermGen which was replaced in Java 8 by Metaspace (which cannot be controlled directly by such settings)
- Adjusts this PR: https://github.com/alphagov/di-authentication-api/pull/3233
=> BAU: Remove MaxPermSize gradle properties

ci/terraform/oidc/api-gateway.tf
Increase WAF rate limit of OIDC API for staging environment, from 3600 requests per 5 minutes to 600,000 requests per 5 minutes (equivalent to 2000 requests per second).
To prevent hitting the WAF rate limit (and requests failing with 403 response) when doing performance testing.
=> AUT-1401: Increase WAF rate limit of OIDC API for staging evironment

account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AwsSqsClient.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AwsSqsClient.java
- Remove sonar false positive from AwsSqsClient.java
- Sonar was flagging the FAKESECRETKEY as a real secret.
=> BAU - Remove sonar false positive from AwsSqsClient.java

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationUserInfoStorageServiceIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/domain/OrchestrationAuditableEvent.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthenticationUserInfo.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AuthenticationCallbackException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationTokenService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationUserInfoStorageService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthenticationTokenServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java, shared-test/build.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthExternalApiStubExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationCallbackUserInfoStoreExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/ClientRegistryValidationException.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/JwtParseException.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/TokenRequestException.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/TokenResponseException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorisationCodeService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
**Note to reviewer:** There are quite a few Sonar-flagged code smells that have been left 'as is'. This is something @billrdunn and I paired on, and we discussed all of them, but might be worth talking through them with whoever reviews this PR to ensure we are meeting code quality standards.
- Add auth callback handler
- This is the lambda that will be called by the authentication frontend (i.e. sign-in/account creation journey) at the end of its authentication flow
- Authentication will supply a code via this callback
- At this point, the lambda in this PR will need to exchange that code for an access token and use that token to obtain a userinfo response
- This will then be saved in Dynamo, and will be used by Orchestration to serve userinfo requests from Relying Parties
- Note: The …
=> Aut 1252/create orch callback handler

ci/terraform/utils/bulk_user_email_audience_loader_dynamo_access.tf, ci/terraform/utils/bulk_user_email_audience_loader_lambda.tf, ci/terraform/utils/bulk_user_email_dynamodb.tf, ci/terraform/utils/bulk_user_email_send_lambda.tf, ci/terraform/utils/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailAudienceLoaderScheduledEventHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BulkEmailUsersService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandlerTest.java
Bulk user email audience loader lambda.
A new lambda function that when triggered queries the user-profile table to retrieve the required audience for an email campaign, then loads those users in to the bulk-user-email table.
Includes both code and infrastructure, will deploy only to sandpit and build.
This is the first iteration of the loader, subsequent versions will refine the query to return a more specific audience based on a user's terms and conditions version, and potentially the ability to segment loads based on the account creation date so that loads can be split up into several runs rather than one.
This initial version will be used to do some performance testing to see how quickly the loads can take place, then subsequent versions will add improvements and batching if required. …
=> AUT-1567: Bulk user email audience loader lambda

ci/terraform/utils/account.tf, ci/terraform/utils/bulk-sending-alerts.tf, ci/terraform/utils/variables.tf
- Add a Cloudwatch alarm to trigger if the error rate of the bulk sending email lambda exceeds 10
- Error rate is calculated by dividing the number of errors in a lambda divided by the number of invocations in a 60 second period
- The output of this alarm will be a slack alert
- So we are alerted if there are any issues with the Lambda
=> BAU - Add alerting to the bulk sending email Lambda

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
- Don't increment the logout Cloudwatch metric if either no cookie is present or no session can be found.
- This will give us more accurate logout metrics
=> BAU - Only increment the logout cloudwatch metric if session is present

auth-external-api/src/main/java/uk/gov/di/authentication/external/validators/TokenRequestValidator.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/validators/TokenRequestValidatorTest.java
- Add token request validator
- This validator will check for the presence of required fields in requests to the authentication external API token endpoint (does not exist yet)
=> AUT-1249: Add token request validator

ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/authentication-auth-code.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/shared/dynamodb.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeStore.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java
- Create a new handler 'AuthorizationAuthCodeHandler'
- This is the lambda that will generate an OAuth authorization response to be passed back to Orchestration which will consist of:
- `code` the authorization code generated in the in the newly created lambda
- `state` present in the initial request `AuthCodeRequest`
- This lambda will use the newly created `DynamoAuthCodeService` which will save a new auth code amongst other fields in Dynamo
- The changes also includes the necessary terraform infrastructure to ensure the handler is connected to a corresponding lambda function
- Part of auth/orch split. Authentication will need to generate an OAuth authorization response to Orchestration
[Auth Code Store](https://github.com/alphagov/di-authentication-api/pull/3194)
=> AUT-1491: Create Authentication AuthCode lambda 

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
This was only used in localstack-based tests so we can remove it.
This PR overrides the return value to false.
There will be following PRs to incrementally remove usage of this configuration method before we can delete it.
=> BAU: Do not check header case

ci/terraform/utils/build-overrides.tfvars, ci/terraform/utils/integration-overrides.tfvars, ci/terraform/utils/oidc-audit.tf, ci/terraform/utils/production-overrides.tfvars, ci/terraform/utils/sandpit.tfvars, ci/terraform/utils/staging-overrides.tfvars, ci/terraform/utils/variables.tf
- Give the utils directory access to the OIDC txma module so we can use the OIDC TXMA audit queue instead of creating a new one for the purpose of the bulk email sending
- Add the internal sector URI to config as it is required for generating the internal pairwise subject ID
- So we can send audit events to TXMA using the OIDC audit queue and avoid creating a new one
=> AUT-1470 - Provide access to OIDC audit queue for Utils directory

ci/terraform/utils/bulk_user_email_send_lambda.tf, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailSenderScheduledEventHandlerIntegrationTest.java, utils/src/main/java/uk/gov/di/authentication/utils/domain/BulkEmailType.java, utils/src/main/java/uk/gov/di/authentication/utils/domain/UtilsAuditableEvent.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
- Add auditing permissions to bulk sending email Lambda
- Add a new audit event called `BULK_EMAIL_SENT`
- Add metadata pair to audit event to identify which bulk email is being sent
- Submit the audit event for each successful sent email
- Add relevant testing to ensure the audit event is submitted
- So we have an audit trail for successful emails sent
=> AUT-1470 - Submit audit events for bulk emails

shared/src/main/java/uk/gov/di/authentication/shared/services/LambdaInvokerService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/LambdaInvokerServiceTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandler.java
- Re-invoke audience load lambdas asynchronously
- Additional logging to record running totals of users loaded
Invocation was previously configured to be synchronous meaning that the first invocation did not terminate before all subsequent invocations.  If set to asynchronous then calling lambdas will terminate straight after the invocation, meaning that a single invocation can complete within the 15 min timeout window.
#3264
=> AUT-1526: Re-invoke audience load lambdas asynchronously

ci/terraform/utils/oidc-audit.tf
Use audit kms key alias target_key_arn
It is not possible to use kms key aliases arm in iam policy documents.
https://docs.aws.amazon.com/kms/latest/developerguide/cmks-in-iam-policies.html
=> AUT-1526: Use audit kms key alias target_key_arn

ci/terraform/utils/bulk_user_email_send_lambda.tf, ci/terraform/utils/shared.tf
Add bulk email send lambda to the security group with egress.
Enables the lambda to reach Notify to send messages.  Resolves Notify connection timeout issue in build.
=> AUT-1526: Add bulk email send lambda to the security group with egress

utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java
- Change dimension name so that it is different to the metric name
- When the dimension name was the same as the metric name, cloudwatch didn't bring through any of the dimensions. This is resolved by making the dimension name different
=> AUT-1406 - Change dimension name so that it is different to the metric name

ci/terraform/shared/site.tf
Deploy bulk email table in shared to integration and staging.
Components in utils depend on this table being created.
Fixes failed deployments of 'utils' in staging and integration.
#3276
=> AUT-1526: Deploy bulk email table in shared to integration and staging

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Reverting since we need to make the [change to the updated at date](https://github.com/alphagov/di-authentication-frontend/pull/1131) live first on the frontend - this commit will be reinstated after that. 
This is because we need to ensure that all frontend changes go live _before_ the backend update, since we want to ensure that no user can have a later terms and conditions version recorded against them than they actually accepted.
This reverts commit 9049bf5e808fee051833a88ed864d9be093896fc.
=> Revert "AUT-1632: Update terms and conditions version"

ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
We had to revert this temporarily to allow a change to the updated date to go live, but can now reinstate this version bump. This reverts commit a46eb6cb8f114dda229d1e0e1fac744cae94b8c4.
=> AUT-1632: Reinstate update to terms and conditions version

ci/terraform/utils/account_metrics_lambda.tf
Upgrade Account Metrics lambda runtime version to Java 17. 
After this upgrade deploys successfully, the other lambda runtimes will be upgraded to Java 17 in a separate PR.
As a first stage to upgrading to Java 17, run this single low-traffic lambda on Java 17 (but still compile it using Java 11).
=> AUT-1297: Upgrade Account Metrics Lambda runtime version to Java 17.

integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailSenderScheduledEventHandlerIntegrationTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
When we populate the table of users to send the bulk email to, we exclude those users on later versions of the T&Cs who have already accepted the retention period change, in order to not unecessarily email users.
However, it is possible for a user who was on an old version of the T&Cs when we populated the table, to have since accepted the updated T&Cs and so be on a different version to when we originally populated the table. Therefore, this commit adds an extra layer of filtering when we are sending the emails to ensure that we do not send emails to these users.
[Ticket](https://govukverify.atlassian.net/browse/AUT-1633)
=> AUT-1633: Do not send email to users who have accepted excluded T&Cs

integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkEmailUsersIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/BulkEmailUser.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BulkEmailUsersService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
This adds a timestamp when we update a bulk email user's status, which helps for audit purposes.
Also refactors some tests to make the setup less noisy.
=> Add bulk email timestamp

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
- Pass a Google Analytics parameter to the authentication frontend via OIDC/orchestration `/authorize` endpoint
- This is a Google Analytics value that needs to be picked up in the authentication frontend
- It originates in an email sent by the Face-to-Face service to let users know that their identity has been processed
- From there the IPV Return Relying Party passes this query param alongside its 'normal' authorize request
- In this commit, I have added the ability to pass through the value to the auth frontend
- A separate commit will be needed in the frontend repository to do anything with that value
- It should never change any system behaviour and is purely for analytics
- Frontend PR to follow
- A change has also previously been made in IPV Return RP to add this parameter to their …
=> AUT-1622: Pass Google Analytics parameter to auth frontend via `/authorize` endpoint

utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java
Inject SystemService to email sender lambda.
Fixes NPE when running the lambda as the SystemService is not currently set.
=> AUT-1468: Inject SystemService to email sender lambda

utils/src/main/java/uk/gov/di/authentication/utils/exceptions/ExcludedTermsAndConditionsConfigMissingException.java, utils/src/main/java/uk/gov/di/authentication/utils/exceptions/IncludedTermsAndConditionsConfigMissingException.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandler.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandlerTest.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
Adds a safety check to ensure that the bulk user email sender lambda cannot be misconfigured, ensuring that the environment variable that specifies the versions of the terms and conditions that we want to include as part of the bulk email have been set.
=> Aut 1633/fail if no env var

integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkEmailUsersIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailAudienceLoaderScheduledEventHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/BulkEmailUser.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BulkEmailUsersService.java
Add 'CreatedAt' timestamp when adding row to bulk-email-users table.
Adds ability to see when each row was loaded.
Makes it easier to differentiate if user loading takes place over several sessions.
#3293
=> AUT-1468: Add 'CreatedAt' timestamp when adding row to bulk-email-users table

ci/terraform/utils/bulk_user_email_send_lambda.tf
Set BULK_USER_EMAIL_INCLUDED_TERMS_AND_CONDITIONS in email sender lambda.
Otherwise the config will always be empty...
This configuration is used to determine whether a user has already accepted a version of the terms and conditions that would exclude them from receiving an email.
=> AUT-1468: Set BULK_USER_EMAIL_INCLUDED_TERMS_AND_CONDITIONS in email sender lambda

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
- Handle nullpointer when email address is not present in the session
- Rather than throw a nullpointer, check that the email is not null and return an error to the frontend if it is
=> BAU - Handle nullpointer when email address is not present in the session

oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
Instead of populating the userinfo response with data from the UserProfile table, Orchestration will use the information returned from the Authentication /userinfo endpoint. 
We want to restrict Orchestration having access to the User tables in DynamoDB.
https://github.com/alphagov/di-authentication-api/pull/3211 Orches: Create AuthCallbackHandler
=> AUT-1253: orches modify userinfo and token endpoint

ci/terraform/oidc/api-gateway-auth-external.tf, ci/terraform/oidc/s3-objects.tf, ci/terraform/oidc/variables.tf
- Create Private api gateway for Authentication external API which will only allow traffic routed through a specific VPC endpoint 
- Create new S3 bucket object to store the source code for the auth external API
- This will limit which traffic can hit the API based on whether it has been routed via the expected VPC endpoint
- This VPC endpoint currently lives in the same VPC as Authentication as Orchestration is still within this VPC. When Orchestration moves into a new VPC then there will be a new VPC endpoint that we need to permit traffic from
- The API can be called via the following - `https://{rest-api-id}-{vpce-id}.execute-api.{region}.amazonaws.com/{stage}`
=> AUT-1542 - Create Private api gateway for Authentication external API

.github/workflows/pre-merge-checks.yml
- Exclude terraform changes from running the pre-merge checks
- None of the pre-merge checks rely on terraform so we can bypass these checks when only terraform changes are made.
- This will make it quicker to merge terraform changes
=> BAU - Exclude terraform changes from running the pre-merge checks

ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/staging.tfvars
- Add shared state override
- Required so it can access the relevant state
=> AUT-1645 - Add shared state override

ci/terraform/utils/build-overrides.tfvars, ci/terraform/utils/bulk_user_email_audience_loader_lambda.tf, ci/terraform/utils/bulk_user_email_send_lambda.tf, ci/terraform/utils/production-overrides.tfvars, ci/terraform/utils/site.tf
Add default prod config.
Flick switch to deploy to prod.
Upgrade the lambdas from java11 to java 17.
Bulk email load and first batch send is coming soon.
Going to run a subset of the user load in production for proving purposes before the full load.
java17 seems to offer performance improvements vs java11
=> AUT-1474: Deploy bulk email components to production

ci/terraform/shared/site.tf
Deploy bulk email to production in shared component.
Bulk email components in 'utils' depend on components in 'shared' (database table for example).
Fixes a production deploy failure from merging this PR:
#3294
=> AUT-1474: Deploy bulk email to production in shared component

ci/terraform/auth-external-api/read_secrets.sh
- Add script to read secrets from secret manager
- So the terraform variables are overridden with the relevant value
=> AUT-1489 - Add script to read secrets from secret manager

integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidScopes.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidScopesTest.java
This will make it easier to work with on the authentication side, which needs to request claims.
Scopes have now been removed from the request.
Also contains some refactoring to make the tests easier to read by removing some of the noise
[Ticket](https://govukverify.atlassian.net/jira/software/c/projects/AUT/boards/193?modal=detail&selectedIssue=AUT-1648)
=> AUT-1648: Convert orchestration scopes to claims

ci/terraform/account-management/sqs.tf, ci/terraform/audit-processors/counter_fraud.tf, ci/terraform/audit-processors/performance_analysis.tf, ci/terraform/audit-processors/storage.tf, ci/terraform/modules/endpoint-module/variables.tf, ci/terraform/oidc/backchannel-logout-request.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/sqs.tf, ci/terraform/utils/bulk_test_user_create_lambda.tf, ci/terraform/utils/bulk_test_user_delete_lambda.tf, ci/terraform/utils/bulk_user_email_audience_loader_lambda.tf, ci/terraform/utils/bulk_user_email_send_lambda.tf, ci/terraform/utils/common_passwords_update_lambda.tf
Upgrades remaining lambda runtime versions to Java 17 (but they are still compiled on Java 11).
One step in process to fully upgrade all lambdas to Java 17.
[PR to upgrade the first lambda runtime version](https://github.com/alphagov/di-authentication-api/pull/3284)
=> AUT-1297: Upgrade remaining lambda runtime versions to Java 17

ci/terraform/account-management/authorizer.tf
- Bump to Java 17 on Authorizer Lambda
- Required to avoid initialization exceptions
- Modifies: https://github.com/alphagov/di-authentication-api/pull/3288
=> BAU: Bump to Java 17 on Authorizer Lambda

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java
Remove redundant email field from AuthCodeRequest as previously required to get Subject ID from UserProfile which is now provided by the BaseFrontendHandler extended by the AuthenticationAuthCodeHandler class"
Email in request is no longer required as the Subject ID can now be accessed from the Userprofile
=> BAU: Remove email field from AuthCodeRequest 

auth-external-api/src/main/java/uk/gov/di/authentication/external/exceptions/AuthCodeStoreRetreivalException.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/TokenService.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/validators/TokenRequestValidator.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/TokenServiceTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/validators/TokenRequestValidatorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/JwtHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PrivateKeyJwtAuthPublicKeySelector.java, shared/src/main/java/uk/gov/di/authentication/shared/validation/PrivateKeyJwtClientAuthValidator.java
- Add authentication token endpoint
- This is the endpoint used by orchestrator callback lambda to obtain a token in exchange for a code it receives from auth frontend
- The orchestrator can then use that token to obtain userinfo, which is temporarily stored in an orch datastore
- From that datastore, it can serve userinfo requests to relying parties
- This token endpoint is therefore an important part of the flow which allows orch to handle userinfo responses without direct recourse to user information tables on the auth side
=> AUT-1249: Add authentication token endpoint

oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java
Part one of AUT-1498. Move out the logic from IPVAuthorisationHandler lambda into a component that can be called from the AuthenticationCallbackHandler to trigger the IPV journey from Orchestration.
Not all logic copied since the service is called in orchestration now.
Regarding a code smell: Method has a lot of parameters, is there anyway of simplifying this ?
=> AUT-1498: Create service to initiate IPV journey

ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/dynamo-policies.tf, ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/sandpit.tfvars, ci/terraform/auth-external-api/staging.tfvars, ci/terraform/auth-external-api/token.tf, ci/terraform/auth-external-api/variables.tf, ci/terraform/oidc/authentication-auth-code.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/sandpit.tfvars
- Add terraform for auth token endpoint
- This is the token endpoint for orchestration<->authentication
- Not to be confused with the token endpoint for RP<->orchestration
- Required in order to deploy the new token lambda as part of auth-external-api module
- The code for the lambda which is being deployed via this terraform: https://github.com/alphagov/di-authentication-api/pull/3337
=> AUT-1489: Add terraform for auth token endpoint

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Configure Orchestration callback URL
- So Authentication can validate this and redirect the user back to Orchestration
=> BAU - Configure Orchestration callback URL

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/authentication-callback.tf
- Create new terraform template for the AuthenticationCallbackHandler
- Includes a new API Gateway and Lambda function for the handler
- The API endpoint uses `orchestration-redirect` path
- Implemented write and read permissions for `authentication-callback-userinfo` table
Endpoint required for redirection from orchestration
=> AUT-1490: Create API and Lambda for AuthenticationCallbackHandler lambda

ci/terraform/oidc/authentication-callback.tf
Attach `redis_parameter_policy` to the `oidc_api_authentication_callback_role` module
To fix error:
````
User: arn:aws:sts::xxxxxx:assumed-role/execution-role20230920085053532800000004/build-orchestration-redirect-lambda is not authorized to perform: ssm:GetParameters on resource: arn:aws:ssm:eu-west-2:761723964695:parameter/build-null-redis-master-host because no identity-based policy allows the ssm:GetParameters action (Service: Ssm, Status Code: 400, Request ID: a71296e6-c18c-48f3-8c6e-ae94cbba3fa6): 
````
https://github.com/alphagov/di-authentication-api/pull/3339
=> BAU: Attach redis parameter policy to authentication callback lambda 

ci/terraform/delivery-receipts/delivery-receipts-dynamo-access.tf, ci/terraform/delivery-receipts/notify-callback.tf, ci/terraform/delivery-receipts/sandpit.tfvars, ci/terraform/delivery-receipts/shared.tf
Grant dynamo access rights to delivery receipts for bulk email.
- Read access to the user-profile table
- Write access to the bulk-user-email table
Adding a facility for delivery receipts to update the Notify the delivery status in the bulk-user-email table.  Allows us to know and store the delivery status for each email sent.  For failed emails we would then be able to schedule an additional run if required.
See below for the PR changing the delivery receipts lambda to update the database.
#3343
=> AUT-1695: Grant dynamo access rights to delivery receipts for bulk email

ci/terraform/utils/production-overrides.tfvars
Switch on the Cloudwatch scheduled event trigger.
Set a cron expression for the scheduled event to triger every 10 mins between 14:00 and 17:00 UTC (15:00 - 18:00 BST) Switch sending on.
To trigger automated sending of the first production batch.
=> AUT-1472: Schedule first production batch of bulk emails

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java
- Store the state that Orchestration sends to Authentication
- We need to store so we can validate it against the state returned in the redirect back from Authentication to Orchestration
=> AUT-1717 - Store state that Orchestration sends to Authentication

ci/terraform/utils/production-overrides.tfvars
Tweak cron expression to use month name.
month 8 -> SEP
Using 8 as a month was not passing validation in the Cloudwatch console.
#3352
=> AUT-1472: Tweak cron expression to use month name

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java
Add two new params to the AuthCodeStore table `SectorIdentifier` (rp-sector-uri) and `IsNewAccount` as these parameters  are required to be reflected in the AuthCodeStore table parsed from `/userinfo` endpoint
- `SectorIdentifier` (rp-sector-uri): value already being passed as a claim from the OIDC API under the field name rp_sector_host
- Modify AuthCodeRequest to parse the new params
- Save the new params into the table via DynamoAuthCodeService
For the userinfo ticket `AUT-1250` there were a couple of fields were not reflected in anything passed by frontend to /orch-auth-code and therefore not stored in the auth code store
=> AUT-1689: Add rp-sector-uri and is-new-account params in AuthCodeStore table

ci/terraform/utils/production-overrides.tfvars
Modify cron expression to send two batches of emails - 15:30 and 15:36 on 21/09/2023
Previous run of sending emails ended 5,000 emails (two batches) short of 50,000 target. This was due to not all jobs being run.
[Previous scheduled run](https://github.com/alphagov/di-authentication-api/pull/3359)
=> AUT-1472: Send two extra batches of emails

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java
- Prior to the change, the handler returned the `authorization` response object
- The response now returns a json body with "location" denoting the redirect uri with appropriate query params
To behave similarly to the existing auth code handler, which returns the `authentication` response as a URI with the query params already constructed.
=> AUT-1707: Refactor AuthCodeHandler response to contain redirect URI

ci/terraform/oidc/authentication-callback.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java
Initiate IPV journey from the Orchestration callback lambda if a user requires identity verification.
The new service (`InitiateIPVAuthorisationService`) will eventually replace `IPVAuthorisationHandler`.
Authentication is being decoupled from Orchestration, so the Authentication frontend will no longer initiate the IPV journey. 
First part of AUT-1498 which is already merged: https://github.com/alphagov/di-authentication-api/pull/3334
=> AUT-1498: Initiate IPV journey from Orchestration callback Lambda

ci/terraform/utils/production-overrides.tfvars
Shouldn't be triggered anyway due to cron expression, so this is largely for peace of mind.
=> AUT-1472: Disable bulk send over the weekend

ci/terraform/utils/production-overrides.tfvars
TO BE MERGED MONDAY MORNING - shouldn't do anything bad before then since it's sending on a cron schedule for Monday, but I've disabled sending over the weekend for peace of mind so this will override that.
AUT-1472: Set up next batch of email sending
This should send 50,000 emails (a rate of 2,500 every 6 minutes between 11am and 1pm BST).
Cron expression breaks down as follows:
* 0/06 - run every 6 minutes with 0 offset (so on the hour, 6 minutes past, 12 minutes past etc)
* 10-11 - run on the hours of 10am and 11am UTC. This actually has a duration of two hours, so it'll run during the hours of 10 and 11. Since it's UTC and we're ccurrently on BST, this will actually be on the hours of 11am and 12pm, meaning that in effect we're running between 11am and 1pm in local time.
* 25 SEP ? …
=> AUT-1472: Set up next batch of email sending 

ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/token.tf, ci/terraform/auth-external-api/userinfo.tf, ci/terraform/auth-external-api/variables.tf, ci/terraform/oidc/authorize.tf
- Add auth-orch split env var (terraform) and enable in Build
- Needed for testing
- Amends: https://github.com/alphagov/di-authentication-api/pull/3367
=> AUT-1678: Add auth-orch split env var (terraform) and enable in Build

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Make `aud` value equal login URI value in the authorize lambda when it passes it within the JWT to authentication frontend
- These were previously two separate config values
- However, the Login URI is always an acceptable value for aud and it simplifies our configuration approach
=> AUT-1678: Make aud value equal login URI value

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/variables.tf
- Remove unused AUTH_AUDIENCE env var in authorize endpoint
- A previous commit decided to use the Login URI as the audience value
- We therefore no longer need to pass the environment variable separately as the ConfigurationService no longer tries to read it
- Cleanup after: https://github.com/alphagov/di-authentication-api/pull/3370
=> AUT-1678: Remove unused AUTH_AUDIENCE env var in authorize endpoint

ci/terraform/utils/production-overrides.tfvars, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
* Cache a parameter we read from ssm, so we do not hit aws rate limiting while processing delivery receipts, which we [saw today](https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?q=search%20index%3Dgds_di_production%20%22*exception*%22%20sourcetype%3D%22aws%3Alambda%3Aproduction%3Anotify-callback-lambda%22%20%7C%20sort%20-_time&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1695207600&latest=1695639900&sid=1695649750.684596)
* Also configure the next batch of emails for today and tomorrow
**Edit - I've fixed this now :-)** I did want to test the changes to the configuration service, but this would involve mocking a private method. If someone has a suggestion as to how to do this that is quick, I'd appreciate it (I saw some …
=> Cache SSM parameter and configure next email batch

ci/terraform/utils/production-overrides.tfvars
DO NOT MERGE before 3pm today as it will overwrite the run for today.
This will send emails every 6 minutes on the hours between 7 and 14 UTC (inclusive) on 28 September. This effectively means it will run between 8am and 4pm BST at a rate of 25,000 an hour. This should mean 200,000 emails sent.
=> AUT-1473: send next batch of 200,000 emails

.gitignore, Makefile, ci/terraform/account-management/read_secrets.sh, ci/terraform/auth-external-api/read_secrets.sh, ci/terraform/oidc/dns.tf, ci/terraform/oidc/read_secrets.sh, ci/terraform/oidc/sandpit.tfvars, ci/terraform/shared/read_secrets.sh, ci/terraform/test-services/read_secrets.sh, ci/terraform/utils/read_secrets.sh, deploy-sandpit.sh, scripts/create_update_sandpit_secret.sh, scripts/read_secrets__main.sh
- AUT-1678: If no secrets are found, exit with error
- chore: add Makefile for performing common tasks
- chore: add delete protection to auth. hosted zone
- chore: Pull sandpit tfvars from secrets manager
- chore: ignore files generated by terraform
This brings sandpit into alignment with the other environments.
Also, `auth.x` hosted zones should have deletion protection now we have dns correctly delegated to us.
=> AUT 1678 load secrets from secretsmanager in sandpit

ci/terraform/utils/production-overrides.tfvars
This will send emails every 6 minutes on the hours between 8 and 15 UTC (inclusive) on 2nd, 3rd and 4th October. This effectively means it will run between 9am and 5pm BST at a rate of 25,000 an hour. This should mean 200,000 emails sent on each day.
=> AUT-1473: Send 200,000 emails a day Mon - Weds next week

build.gradle, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
- Upgrade google-java-format from v1.13.0 to v1.18.0.
- Format existing code (`spotlessApply`) with new google-java-format version.
Fixes `spotlessApply` error due to `record` keyword in .../authentication/frontendapi/entity/AuthCodeResponse.java
=> BAU: Bump google-java-format

.pre-commit-config.yaml
- The `di-pre-commit-hooks` repo has now been migrated to the `govuk-one-login` org, update `.pre-commit-config.yaml` to reflect the change.
The `di-pre-commit-hooks` repo has now been migrated to the `govuk-one-login` org.
=> SPT-473: Update pre-commit reference to programme hooks

ci/terraform/auth-external-api/sandpit.hcl, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/shared.tf
Align sandpit auth-external-api terraform state key with the other environments to avoid build pipeline errors.
Pipeline is creating auth-external-api state keys as enn-auth-external-api-terraform.tfstate, whereas sandpit was using env-auth-ext-api-terraform.tfstate.
=> AUT-1678: Align auth external api state key in sandpit

ci/terraform/utils/production-overrides.tfvars
Should run a single batch of bulk emails at 10am UTC / 11am BST
We have about 1500 left to get through, so a single batch of max 2,500 will see us through.
=> Configure one more batch at 11am on 5th October

ci/terraform/utils/bulk_user_email_send_lambda.tf, ci/terraform/utils/production-overrides.tfvars, ci/terraform/utils/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailSenderScheduledEventHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, utils/src/main/java/uk/gov/di/authentication/utils/exceptions/UnrecognisedSendModeException.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
When sending the bulk T&C emails, we record a status against the user, noting whether:
* The email was sent (but we may still have received a failed delivery receipt): EMAIL_SENT
* The user is still pending to send to: PENDING
* There was an error in the notify client: ERROR_SENDING_EMAIL
* The user has recently accepted the latest T&Cs: TERMS_ACCEPTED_RECENTLY
* The account has been recently deleted: ACCOUNT_NOT_FOUND
In the cases where there was an error in the Notify client (ERROR_SENDING_EMAIL), we want to retry. This was the case, for example, during an incident where Notify was experiencing degraded api service. This adds the ability to resend to these users, based on the value of a feature flag being set to `NOTIFY_ERROR_RETRIES`
=> Aut 1768: Resend bulk email to users with notify errors

ci/terraform/account-management/build-overrides.tfvars, ci/terraform/account-management/integration-overrides.tfvars, ci/terraform/account-management/production-overrides.tfvars, ci/terraform/account-management/sandpit.tfvars, ci/terraform/account-management/staging-overrides.tfvars, ci/terraform/account-management/variables.tf, ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/sandpit.tfvars, ci/terraform/auth-external-api/staging.tfvars, ci/terraform/auth-external-api/variables.tf, ci/terraform/delivery-receipts/variables.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf
Increase default memory size to 1.5GiB to provide enough CPU for the Dynatrace instrumentation library.
The Dynatrace instrumentation library won't run if a Java Lambda function has less than 1500MB RAM because it requires enough CPU to run.
=> Increase default memory size to 1.5GiB

ci/terraform/modules/endpoint-module/lambda.tf
Switch off Dynatrace in build.
And keep switched-off in production.
To see if Dynatrace is causing acceptance test issues in build.
#3414
=> BAU: Switch off Dynatrace in build

oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
What?
Instead of populating the userinfo response with data from the UserProfile table, Orchestration will use the information returned from the Authentication /userinfo endpoint.
Why?
We want to restrict Orchestration having access to the User tables in DynamoDB.
Related PRs
https://github.com/alphagov/di-authentication-api/pull/3211 Orches: Create AuthCallbackHandler
=> Aut 1253/orches modify userinfo and token endpoint

auth-external-api/src/main/java/uk/gov/di/authentication/external/domain/AuthExternalApiAuditableEvent.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java
- Add audit event to auth external API token lambda
- This lambda issues a token to orchestration
- It is not meant for use by any RP (not to be confused with OIDC API token endpoint which is for RPs)
- There is a corresponding audit event on the orchestration side when the token response is successfuly received
- This is only code logic, but the Terraform work already seems to be in place ref getting SQS created and the relevant env var passed via the configuration service (see token.tf)
- It is inherently quite hard to test these as events need to pass via TxMA so the proof of the pudding is only much later when TxMA processes things (which involves some admin steps that haven't been done yet). However, I have deployed to sandpit and put a test event through which is showing in the …
=> AUT-1742: Add audit event to auth external API token lambda

ci/terraform/delivery-receipts/delivery-receipts-dynamo-access.tf, ci/terraform/delivery-receipts/site.tf, ci/terraform/shared/site.tf, ci/terraform/utils/site.tf
This sets the counts for:
* The bulk-email-users table;
* The bulk-email-sender;
* The bulk-email-loader
to 0 in build and sandpit. It also adds this count in for the delivery receipts api. This will mean that the lambdas are no longer deployed in these environments, and the table (including data) is destroyed.
This was previously reverted as we had pipeline failures due to not setting all the counts to 0 - I think this should fix.
=> AUT-1467: Remove bulk email infrastructure in build and sandpit

build.gradle
Upgrade to latest gradle docker-compose plugin.
docker-compose up fails when running integration tests on the latest version of Docker Desktop without this upgrade.
=> BAU: Upgrade to latest gradle docker-compose plugin

ci/terraform/shared/stub-rp-clients.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IPVStubExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/IdentityTestData.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidClaims.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidClaimsTest.java
Adding a new claim for NINO, so that HMRC can request it from One Login. 
So that they can see if the user has a HMRC account. It would prevent HMRC from having to collect the NINO from the user after creating a [GOV.UK](http://gov.uk/) One Login account
Orchestration
Dev Notes
Agree claim name and payload structure with Identity team, will be of the form https://vocab.account.gov.uk/v1/<something> 
[AUT-763 - Support drivingPermit claim · alphagov/di-authentication-api@2356517](https://github.com/alphagov/di-authentication-api/commit/23565179dd002f2224d00367c94e7420c8f87202) Previous pull request to add driving Permit
=> ATO-37: Add nino claim

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelperTest.java
Turned off X-XXS-Security protection header
The X XSS Protection header is designed to detect and assist in protecting against cross-site scripting (“XSS”) attacks. However, most modern browsers ignore this header now as having it on can introduce additional security issues.
=> AUT-1824: turned off xxs sec header

ci/terraform/modules/endpoint-module/lambda.tf
Deploy dynatrace to all environments but production.
Dynatrace java lambda layer issue has been resolved and testing in sandpit and staging. Now deploying to all environments apart from production.
=> Deploy dynatrace to all environments but production.

.github/workflows/pre-merge-checks.yml
Ensure the pre merge checks also run when a PR is added to the merge queue.
We want to make sure the code that ends up on main passes all the tests. Therefore we're going to try out merge queues. You must make this change to all required checks when enabling merge queues.
=> BAU: Make required checks run on merge queue

ci/terraform/account-management/variables.tf, ci/terraform/audit-processors/variables.tf, ci/terraform/auth-external-api/variables.tf, ci/terraform/delivery-receipts/variables.tf, ci/terraform/oidc/variables.tf, ci/terraform/shared/variables.tf, ci/terraform/test-services/variables.tf, ci/terraform/utils/variables.tf
Change default deploy role arn to null from empty string
New versions of terraform error on deployment if the deploy arn is empty string. This is backwards compatible with version 1.3.1
=> ATO-NONE: Fix default deployer role arn for newer versions of terraform

ci/terraform/delivery-receipts/notify-callback.tf, delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java, delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java, delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Bulk Email switch for delivery receipts lambda
Adds a switch to turn bulk email on and off in the NotifyCallbackHandler.
This PR should be merged before attempting to deploy #3431 again.
This is so the lambda does not try to describe the user-profile table when the bulk email deployment switch is off (deploy_bulk_email_users_count).  If the deployment switch is off the NotifyCallbackHandler does not have the iam rights to access the user-profile table, so the lambda fails to start and throws errors.
#3431
=> AUT-1467: Bulk Email switch for delivery receipts lambda

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
Add Auth_Code_Issued Audit Event to AuthCallBack Lambda
There is an audit event which is triggered when we generate an auth code for an RP - [https://github.com/alphagov/di-authentication-api/blob/main/oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java#L2[…]01](https://github.com/alphagov/di-authentication-api/blob/main/oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java#L287-L301)
We will also need this audit event on the AuthenticationCallbackHandler as the place where we will generate Auth Codes for RPs would have moved once we enable the split, so not to replicate it would mean the new journey is not fully equivalent in audit terms.
=> AUT-1767: Add Auth_Code_Issued Audit Event to AuthCallBack Lambda

.github/CODEOWNERS
Fix codeowners file to make all teams codeowners
Format of codeowners file was incorrect, so only orchestration team were codeowners
=> ATO-NONE: Fix codeowners file to make all teams codeowners

ci/terraform/delivery-receipts/site.tf, ci/terraform/shared/site.tf, ci/terraform/utils/site.tf
Set deploy_bulk_email_users_count to 0 in all environments -> destroy infrastructure
This sets the counts for:
* The bulk-email-users table;
* The bulk-email-sender;
* The bulk-email-loader
to 0 in all environments (this was already done for build and sandpit). This will mean that the lambdas are no longer deployed in these environments, and the table (including data) is destroyed.
Bulk email facility no longer in use so tearing down resources.
They can be brought back by reverting this PR and #3485
=> AUT-1467: Set deploy_bulk_email_users_count to 0 in all environments -> destroy infrastructure

ci/terraform/shared/kms.tf
Enabled key rotation for lambda_env_vars_encryption_key in kms.tf
Lack of key rotation primarily impacts the confidentiality and integrity of the tested AWS
environment. This is due to the possibility that aged customer managed keys are compromised,
due to the lack of rotation it could be possible that the compromised key is still functional.
Should these keys provide administrative access, data encrypted by said keys could be exposed
outside of their current, protected environment, exposing sensitive information to malicious
actors.
=> AUT-1855: Enable Key Rotation

ci/terraform/oidc/build-overrides.tfvars
Enable Doc App decouple enabled flag for build
To ensure everything is working as expected by performing a journey.
=> ATO-66: Enable Doc App decouple enabled flag for build

shared-test/build.gradle
Jetty security vulnerabilities in version 11.0.13 shown in [https://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server/11.0.13](url)
https://govukverify.atlassian.net/browse/AUT-1825
ITHC report identified vulnerabilities. Major version update to 12.0.2 was attempted but the change in functionality resulted in a refactor and unclear issues during integration testing.
=> Bump org.eclipse.jetty:jetty-server from 11.0.13 to 11.0.18

ci/terraform/oidc/build-overrides.tfvars
This reverts commit cc9cf13071c33b929dd623ee1ebaa08328790cd5.
=> Revert "ATO-66: Enable Doc App decouple enabled flag for build"

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java
Removing 'required' annotation from claims in AuthCodeRequest
These claims can be empty, if no scopes are requested. This causes the login flow to error after the user enters an auth code, since it validate the AuthCodeRequest object and expects claims to be required. This code is only currently used in sandpit, as it is behind the auth/orch split flag. Other instances claims do not have the required flag.
=> ATO-107: Remove required annotation from claims in AuthCodeRequest

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RequestObjectService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java
- unrevert changes for ATO-21
- Change JAR required check to test scopes in client registry
Previously this was checking the scopes inthe auth request. Change this to check the scopes in the client registry. This is because the acceptance tests do not send the doc check scope. It is unclear if the real requests contain this scope.
#3475 
#3504
=> ATO-121: Change JAR required logic

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Modify the request validation logic to enable clients who are not configured to require JAR to pass it in anyway
=> ATO-21: Permit unconfigured clients to make JAR requests

ci/terraform/account-management/authorizer.tf
In the case that `local.authorizer_provisioned_concurrency` is 0, don't try to provision `aws_lambda_provisioned_concurrency_config`
Fixes the following error when deploying to sandpit:
`Error: expected provisioned_concurrent_executions to be at least (1), got 0`
=> BAU: Don't provision concurrency if not needed

ci/terraform/account-management/production-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars
Dynatrace integration requires this as a minimum
=> BAU: Set production lambdas to 1.5GB mem

ci/terraform/account-management/remove-account.tf, ci/terraform/account-management/shared.tf, ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/authentication-auth-code.tf, ci/terraform/oidc/doc-app-authorize.tf, ci/terraform/oidc/ipv-authorize.tf, ci/terraform/oidc/login.tf, ci/terraform/oidc/mfa.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/shared.tf, ci/terraform/oidc/signup.tf, ci/terraform/oidc/update_profile.tf, ci/terraform/oidc/userexists.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms-policies.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
Implemented CMK encryption/decryption capability to account modifiers table and all lambdas that require access to the table.
The Fidus ITHC recommended adding CMK encryption to dynamodb tables. This is to improve confidentiality and integrity of dynamodb tables and improve control over encryption/decryption processes.
=> AUT-1826: added CMK encryption to account modifiers table

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Remove `isNonceRequired` method which permits nonce to be absent in staging environment.
- All requests to`/authorize` are now required to contain a nonce.
- The flag was used for a specific situation where nonces weren't being sent in staging. This situation is no longer relevant.
=> ATO-128: Remove isNonceRequired flag

delivery-receipts-api/README.md
README documentation for the notify callback handler.
Document basic information, including how the handler can be tested.
=> AUT-1467: README documentation for the notify callback handler

integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/JwksHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Remove `isDocAppApiEnabled()` from `ConfigurationService`.
Value is always `true` so method is redundant.
https://github.com/govuk-one-login/authentication-api/pull/3536
=> ATO-178: Remove isDocAppApiEnabled from ConfigurationService

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/jwks.tf, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, integration-tests/build.gradle
Remove `DOC_APP_API_ENABLED` environment variable
Value is always `true` so variable is redundant
https://github.com/govuk-one-login/authentication-api/pull/3535
=> ATO-179: Remove DOC_APP_API_ENABLED environment variable

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
Add auth code to AUTH_CODE_ISSUED audit event
HMRC requirements
=> ATO-91: Add auth code to AUTH_CODE_ISSUED audit

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/queuehandlers/NotificationHandlerIntegrationTest.java, ci/terraform/account-management/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/NotificationHandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/NotifyIntegrationTest.java
Change the urls that take users to the contact form from the emails and SMSs they receive when they create a [GOV.UK](http://gov.uk/) One Login, sign in, or reset their password or 2FA method (account recovery).
- Remove "referer"
- Modify contact us route from "contact-us" to "contact-gov-uk-one-login"
So that users go to the new ‘triage’ page rather than directly to the contact form.
=> AUT-1908: Update urls in the emails and SMS

.github/workflows/build-api-modules.yml, .github/workflows/deploy-account-managment.yml, .github/workflows/deploy-audit-processors.yml, .github/workflows/deploy-auth-external-api.yml, .github/workflows/deploy-delivery-receipts.yml, .github/workflows/deploy-oidc.yml, .github/workflows/deploy-shared.yml, .github/workflows/deploy-test-services.yml, .github/workflows/deploy-utils.yml
AUT-1947-Mask-the-AWS-credentials-in-GitHub-workflow
The GitHub Action have unmasked AWS credentials in GitHub workflow , This is security concern to have them unmasked credentials on GIT hub public repo authentication-frontend
=> Moving AWS credentials to Secrets

.github/workflows/build-api-modules.yml, .github/workflows/deploy-interventions-api-stub.yml, ci/terraform/interventions-api-stub/sandpit.tfvars, interventions-api-stub/build.gradle, interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/lambda/HelloWorldHandler.java, interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/HelloWorldHandlerTest.java, settings.gradle
- Create new stub lambda with HelloWorld lambda
- Note: Other tickets will flesh out the infrastructure as code as well as the 'real' code needed to simulate the Account Interventions API; this is purely placeholder material
- This provides a skeleton for building the actual code/logic to stub out another team's API (the 'Account Interventions API')
=> AUT 1851: Create new stub lambda (placeholder for Account Interventions API stub)

.pre-commit-config.yaml, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/PackageSettings.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, ipv-api/src/test/resources/uk/gov/di/authentication/ipv/services/approvals/IPVAuthorisationServiceTest.shouldConstructASignedRequestJWT.approved.json, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/TestClockHelper.java
Add an approvals test for the IPV request
Not only does this catch formatting issues (for example the `claims` claim is an escaped string rather than a JSON object), it also serves as self updating documentation. I've found it reasonably hard work to figure out what this request actually looked like, and was debugging tests.
=> ATO-182: IPV request testing

ci/terraform/auth-external-api/userinfo.tf, ci/terraform/oidc/userinfo.tf
Pass the the auth/orch split flag to the oidc userinfo lambda rather than the auth external one
This is the lambda which uses it
=> ATO-194: Pass split enabled flag to correct lambda

ci/terraform/interventions-api-stub/build.tfvars, ci/terraform/interventions-api-stub/hello-world.tf, ci/terraform/interventions-api-stub/interventions-api-stub-gateway.tf, ci/terraform/interventions-api-stub/s3-objects.tf, ci/terraform/interventions-api-stub/sandpit.tfvars, ci/terraform/interventions-api-stub/shared.tf, ci/terraform/interventions-api-stub/site.tf, ci/terraform/interventions-api-stub/variables.tf, deploy-sandpit.sh
Creates a new api gateway wired up with a placeholder hello world endpoint for the interventions stub. This will only be deployed in build (although we will ensure that via the pipeline rather than in this terraform - this work will follow).
This has been tested in sandpit.
We want something in build to replicate the Account Interventions API. We currently don’t have an API where these Stubs can live. This creates a new terraform module and create a new API gateway where these Stubs will sit behind. 
We introduced the new module [here](https://github.com/govuk-one-login/authentication-api/pull/3567).
=> Aut 1850/create interventions stub terraform

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelperTest.java
- Increase the max age of the `di-persistent-session-id` to 18 months rolling max-age
- For new cookies, append the timestamp to the end of the cookie value by using a double dash --
- For existing cookies, check whether it has a timestamp suffixed onto the cookie value, if not update the value by appending the timestamp
So that the max-age for `di-persistent-session-id` is 18 months rather than 13
=> AUT-1774: Add timestamp and extend di-persistent-session-id cookie

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/variables.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
Update the orchestration `ConfigurationService` to:
* add feature flags
* add URI required for integration with the Account Intervention Service.
Add terraform variables and pass through environment variables for the above.
Required for integration with the Account Intervention Service.
=> ATO-201: Update Configuration Service

ci/terraform/account-management/shared.tf, ci/terraform/account-management/update-password.tf, ci/terraform/oidc/login.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/shared.tf, ci/terraform/oidc/signup.tf, ci/terraform/shared/kms-policies.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, ci/terraform/utils/common_passwords_update_lambda.tf, ci/terraform/utils/shared.tf
Added CMK decryption capability to lambdas that interact with the common passwords table.
CMK encryption/decryption is being implemented in line with recommendations from the ITHC. Separate PRs are being made for the common passwords table's encryption and decryption capability. Decryption capability is being implemented first as when encryption and decryption capability are merged together there is down time as tables are encrypted before lambdas are able to decrypt them.
Another PR will follow encrypting the table after this has been merged
=> AUT-1826: Added Common Passwords Table CMK Policies

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/site.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java
- Create new AccountInterventionsAPI handler
- Create infra/terraform scripts to create API Gateway endpoint for the new lambda
- Create corresponding unit test to capture handler request & response
-  Add integration tests to the AccountInterventionsAPIHandler
- Enable deployment in build and sandpit only
This provides a skeleton for building the actual code/logic for the Account Interventions lambda
=> AUT-1843: Create code and infra for "HelloWorld" Account Interventions Lambda

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/variables.tf
Integrate existing API Gateway with Orch frontend Network Load Balancer (NLB)
- API Gateway does not support integration of private Application Load Balancer (ALB)
- NLB and VPC Link are used instead, which sit in between API Gateway and ALB.
[ATO-180](https://github.com/govuk-one-login/authentication-api/pull/3566) adds the ALB and NLB to the Orchestration frontend
[ATO-180]: https://govukverify.atlassian.net/browse/ATO-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATO-181: Integrate API Gateway with Orchestration frontend Network Load Balancer

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/variables.tf
Use local rather than variable for deploy_account_interventions_count.
Fixes failing build:
'Error: No value for required variable'
#3570
=> AUT-1843: Use local rather than variable for deploy_account_interventions_count

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AccessTokenStore.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/RefreshTokenStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
Best to review this one commit-wise. There's a bit of tidying to make the second part possible. 
The main change here is to persist the internal pairwise identifier in the access token store and the refresh token store. This is needed to retrieve the auth user info response from dynamo DB in order to service the RP's userinfo request.
=> ATO-196: Store internal pairwise identifier in access and refresh token stores

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
Pass through the correct redirect url for the orch->auth OAuth flow. The currently deployed code just has `orchestration-redirect` as a default, so the redirect goes to the `signin.` domain, which is not correct.
Draft until https://github.com/govuk-one-login/authentication-frontend/pull/1217 goes in
=> ATO-193: Set the Orch redirect url in all environments

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/CookieHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/CookieHelperTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/CookieHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelperTest.java
Note to reviewer: Please review this PR especially carefully. This has been deployed to Sandpit at the time of writing, so it should be possible to empirically compare behaviours between Sandpit and other environments. Please also treat the code logic with particular scepticism, as we are introducing changes on top of changes, and if we get this wrong, it will become very complex indeed to apply a fix that works for all possible users.
- Change the formatting behaviour around how we set `persistent-session-id`
- Amends changes introduced in 75a10df4376397d5a454b87b5cee689e13a71e20
- For a time, users have ended up with:
1. Double timestamps in the session ID
2. Losing the existing UUID-style IDs from the beginning of the existing session ID
- The changes in this commit attempt to resolve …
=> INCIDEN-542: Fix persistent session IDs

ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/shared.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/userinfo.tf, ci/terraform/shared/kms-policies.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
Added CMK decryption capability to lambdas that interact with the identity credentials table.
CMK encryption/decryption is being implemented in line with recommendations from the ITHC. Separate PRs are being made for the identity credentials table's encryption and decryption capability. Decryption capability is being implemented first as when encryption and decryption capability are merged together there is down time as tables are encrypted before lambdas are able to decrypt them.
Another PR will follow encrypting the table after this has been merged
=> AUT-1826: identity credentials CMK decryption

oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AccountInterventionResponse.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AccountInterventionStatus.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AccountInterventionException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccountInterventionService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccountInterventionServiceTest.java
Add AccountInterventionService and associated classes.
The AccountInterventionService is a proxy wrapper to the external Account Intervention Service. Our representation makes an HTTP call to the actual service and parses the result into our internal representation. At this stage we are only interested in a subset of the returned information, namely the account status.
If the Account Intervention Service is disabled our `AccountInterventionService` will return an AccountStatus with all false values, indicating there is no intervention.
If the Account Intervention Service is enabled, but we encounter an exception at any point when connecting to the service, we catch the exception and rethrow an "AccountInterventionException"
Required for integration with Account Intervention Service
=> ATO-175: Add AccountInterventionService

account-management-integration-tests/build.gradle, build.gradle, delivery-receipts-integration-tests/build.gradle, integration-tests/build.gradle, orchestration-shared-test/build.gradle, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/httpstub/HttpStubExtension.java, shared-test/build.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/httpstub/HttpStubExtension.java
Remove the glassfish depedencies
It seems that this dependency was only used to build out some URLs in tests, but was widely referenced. Fewer dependencies is almost always better
=> BAU: Remove unused dependencies on glassfish

ci/terraform/auth-external-api/userinfo.tf
Re-add the feature flag
I didn't think it was used, but it is
Partially reverts https://github.com/govuk-one-login/authentication-api/pull/3562
=> ATO-194: re add feature flag to userinfo

ci/terraform/oidc/userinfo.tf
The userinfo lambda needs access to the auth callback userinfo table key
=> ATO-210: Grant KMS access

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java
Use just the host of the internal sector uri to generate the internal pairwise identifier used in the authentication user info response
=> ATO-211: Generate the correct identifier

.github/workflows/pre-merge-checks.yml, docker-compose.yml
Version 3 supports latest AWS SDKs. This will unblock #3598 
Remove unused config params.
=> BAU: Upgrade localstack provider

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Include the `claims` claim when transforming a request object to an authentication request.
When a request object is present in a request to `/authorize`, it is transformed in order to generate a properly formed authentication request. The `claims` claim wasn't being handled in the `transform` method and so was missing from the authentication request.
=> ATO-203: Read 'claims' claim from JAR

oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java
Only read claims from JAR request if non-null
Otherwise error thrown on auth requests or when claims otherwise null
https://github.com/govuk-one-login/authentication-api/pull/3604
=> ATO-203: Only parse claims if non-null

ci/terraform/oidc/processing-identity.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ConfigurationServiceTest.java
Pass the AIS environment variables to the processing identity handler
For additional safety, make things work when they're not present.
As-was the processing-identity lambda could not start, as it had a dependency on AIS and the env vars were not being passed to the lambda
Trying to parse a null url throws an exception. We now default to an empty string, which is successfully parsed
https://github.com/govuk-one-login/authentication-api/pull/3610
=> ATO-47: Handle missing AIS URL

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java
Re-add removed handleRequest method
Dynatrace and other tracing relies on this via reflection
https://github.com/govuk-one-login/authentication-api/pull/3610/files#diff-4eaf51fdc1367b3d55185e1560bf5be8270db1c0ff27122192e5a6f187d09b72L74-L79
=> ATO-226: Re-add handle request method for tracing

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, ci/terraform/auth-external-api/token.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java
Updated the submitAuditEvent method calls used in the UserInfoHandler and TokenHandler to use the internal pairwise ID as a parameter instead of incorrectly passed subjectID. Also updated corresponding unit tests and integration test so that they match the audit event accepting the pairwise id and not the subject id.
The submitAuditEvent was previously incorrectly accepting the subject id for the internal pairwise ID argument.
=> AUT-1988: fixed audit event logging incorrect subjectID

ci/terraform/oidc/account-interventions.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsInboundResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/Intervention.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/State.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UnsuccessfulAccountInterventionsResponseException.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/serialization/Json.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SerializationService.java
Add the logic to the Account Interventions Lambda so it can accept a request, call out to the Account Interventions API, handle the response and then return it to the frontend. 
- Make the Account Interventions Lambda accept a request which contains email
- Create Account Interventions Stub Extension which can be used by the Integration test
- Uses existing `ACCOUNT_INTERVENTION_SERVICE_URI` in config
- Calculate the user’s internal pairwise ID required as `userID` 
- Make a GET request to the Account Interventions API using this Path `/v1/ais/{userId}`
- Return response to frontend
Implement Account Interventions backend tasks for scenarios where where account will need to be flagged, suspended or deleted.
=> AUT-1844:Implement Account Interventions Lambda to call the Account Interventions API

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/ipv-authorize.tf, ci/terraform/oidc/ipv-callback.tf
Added for requests to IPV Core:
- IPV_TOKEN_SIGNING_KEY_ALIAS
- IPV_AUDIENCE
- IPV_AUTHORISATION_CALLBACK_URI
Additionally sorted env var lists for easier comparison
These vars are required to generate and sign the request to IPV Core. This is done in the AuthenticationCallback lambda when the split is turned on
=> ATO-228: Add missing env vars to authentication callback lambda

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/LogoutService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/LogoutServiceTest.java
This PR is purely refactoring. There are no logical changes.
Move logic for destroying sessions and creating responses from `LogoutHandler` to new `LogoutService`. 
Allows greater control over the logout process, which is required to implement a back-channel logout if a suspended or blocked account status is received from Account Interventions.
=> ATO-229: Refactor LogoutHandler 

account-management-api/src/test/java/uk/gov/di/accountmanagement/DynatraceTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/DynatraceTest.java, build.gradle, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/DynatraceTest.java, delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/DynatraceTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/DynatraceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/DynatraceTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/DynatraceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/DynatraceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/DynatraceHelper.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/DynatraceHelper.java
- Add tests to ensure all lambda handlers define their own handleRequest method
- Fix AccountInterventionsHandler
We had an incident on Tuesday when this method was removed from a handler. This causes dynatrace to hang, which means all functions time out at 30 seconds. This dramatically increases cold starts, and means we lose observability.
=> INCIDEN-576: Add tests to check all handlers have handleRequest method

ci/terraform/shared/outputs.tf
Re-add the old exported name of the subnet
This is used by the experian check, defined in another repo
=> ATO-151: re-add exported subnet value

ci/terraform/oidc/api-gateway.tf
This reverts commit 28bfc8a62de5b47cd0e8283b586b2478ac5782f2.
Revert changes to WAF rules around localhost
We suspect these are causing prod smoke test failures
https://github.com/govuk-one-login/authentication-api/pull/3677
=> Revert "BAU: Remove leftover waf rule for sandpit blocking requests from localhost

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/variables.tf, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/audit/AuditContext.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/AccountInterventionsAuditableEvent.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/AccountInterventionException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Call the AuditService when we get a response from the AccountInterventionService.
Introduce an AuditContext object to carry information required for the audit event sent to TXMA. There is a significant overlap with the data contained in this object and TxmaAuditUser, however they are used for differnet things. The TxmaAuditUser is used to construct the user section of a TxmaAuditEvent, and therefor must match that exactly. The AuditContext is intended to represent the data that we understand about the user and this request that can be shared by multiple events. To make this useful in more places, more work should be done to understand event specific information, added as metadata pairs. Further work on that is out of scope for this ticket.
Added a new AccountInterventionsAuditableEvent to …
=> ATO-177: Audit calls to the Account Intervention Services (Manual Rebase)

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java
Added zero args constructor to the Account Interventions Handler.
A zero args constructor is required to instantiate the handler class.
https://github.com/govuk-one-login/authentication-api/pull/3593
=> AUT-1844: Added Zero Args Constructor For Account Interventions Handler

ci/terraform/oidc/build-overrides.tfvars
Turn on `doc_app_decouple_enabled`
To test alongside split in build
=> ATO-66: Turn on doc app decouple

ci/terraform/oidc/authorize.tf
When in the protected subnet, egress is restricted by the network firewall. Therefore we can safely enable the open egress security group.
=> ATO-151: Allow egress to the authorize lambda when it is in the protected subnet

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/sandpit.tfvars
Change the casing of client types from WEB to web for sandpit stubs
The correct casing is lower case - the upper case fail validation on the request object flow
=> ATO-208: Fix client types for sandpit stubs

ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/site.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java
- Create skeleton handler for new endpoint `/check-reauth-user`
- Create "HelloWorld" 200 response in new `CheckReAuthUserHandler` class
- Create infra API Gateway, Lambda
- Skeleton unit and integration tests
This provides a skeleton for building the actual code/logic for the Check ReAuth User handler
=> AUT-2115: Create skeleton handler for new endpoint /check-reauth-user

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/Features.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
Remove code that sets password hint version but retain the `Feature` class so that we have the facility to run these kind of experiments in future. 
The related code within `authentication-frontend` has been removed so there is now no need to set and provide this.
* https://github.com/govuk-one-login/authentication-frontend/pull/1257
=> AUT-1326: Remove code that sets password hint version

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/build-overrides.tfvars
Enable the docapp decouple in the build environment
Testing in preparation for rollout
=> ATO-66: Enable docapp decouple in build

ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/staging.tfvars
Set the correct public keys for the pair orch uses to sign requests to auth post-split. Previously all copies of the sandpit key.
Copied from the KMS console.
Build done previously.
=> ATO-220: Set correct public keys

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/UserMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java
[JIRA link](https://govukverify.atlassian.net/browse/AUT-2139)
We need to pass the users MFA type to the ui during password reset so the end user can navigate to the relevant MFA screen (auth app / sms).
User will not be logged in so the user context at this stage will not contain the required information, we need to expose the mfa type of the user prior to login so we can complete the password reset user journey.
=> AUT-2139: expose MfaMethodType in CheckUserExists API response

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java
New CodeRequestType added for the 2FA password reset journey using auth app notifications. 
The relevant processor was also enhanced to process requests for the 2FA password reset journey.
We maintain separate 2FA attempts counters for each journey type so that the user has the correct number of attempts before they are locked out.
A new counter type is required for Password Reset 2FA Auth App.
=> AUT-1998: Add new journey type to ‘VerifyMfaCodeHandler’ for auth app codes

integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
_This PR was co-authored by Isaac Au_
- Audit the Return Code claim when it is available.
- Add Return Code claim to existing integration tests.
Note that as Return Code is an additional claim, the functionality to include Return Code in the user info response is already handled.
Testing in sandpit will be done once all tickets in the [ATO-112 epic](https://govukverify.atlassian.net/browse/ATO-112) are ready.
RPs have requested more information about failures after we redirect back.
=> ATO-135: Add Return Code claim to integration tests and auditing

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/variables.tf, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/audit/AuditContext.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/AccountInterventionsAuditableEvent.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/AccountInterventionException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Call the AuditService when we get a response from the AccountInterventionService.
Introduce an AuditContext object to carry information required for the audit event sent to TXMA. There is a significant overlap with the data contained in this object and TxmaAuditUser, however they are used for differnet things. The TxmaAuditUser is used to construct the user section of a TxmaAuditEvent, and therefor must match that exactly. The AuditContext is intended to represent the data that we understand about the user and this request that can be shared by multiple events. To make this useful in more places, more work should be done to understand event specific information, added as metadata pairs. Further work on that is out of scope for this ticket.
Added a new AccountInterventionsAuditableEvent to …
=> ATO-177: Audit calls to the Account Intervention Services (Re-apply)

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
If this param is set to true, then the user is returned as not authenticated. This will form part of the reauthentication flow.
https://github.com/govuk-one-login/authentication-frontend/pull/1253
=> AUT-2113: Add reauthenticate param to buildUserStartInfo

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java
Log AIS service errors as errors.
Currently unable to see errors returned from the stub in the logs.
These messages should be logged as 'error'.
=> AUT-1847: Log AIS service errors as errors

interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandler.java, interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandlerTest.java
Updated stub handler to return 200 response in event of no matching account being found by account interventions service.
It was returning 404 when spec requires 200 for this case.
=> Update Stub Handler Response

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java
Remove the feature flag check from AuthenticationAuthCodeHandler
The feature flag check here does not serve a purpose as the endpoint is only called when the feature is enabled. It's presence makes rolling the feature out more complex.
=> ATO-252: Enable AuthenticationAuthCodeHandler

ci/terraform/oidc/ipv-callback.tf, ipv-api/src/main/java/uk/gov/di/authentication/ipv/domain/IPVAuditableEvent.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/ProcessAuthRequestException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/entity/AuthCodeResponse.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
ATO-133:
- Persist return codes in DynamoDB; as it is storing the valid claims, returnCode exists there and shall be saved in the case that a return code is present
ATO-134:
- If there is an error returned from IPV, make AIS call then return ACCESS DENIED
- If does not match requested level of confidence (`userIdentityError`) then make AIS call then check if `returnCode` is present
- If `returnCode` is present, process the return code:
- If clientRegistry does not contain `returnCode` or `returnCode` was not requested in the `authRequest`, bypass SPoT and return ACCESS DENIED
- Else save identityClaims, generate authCode and returned RP
- For generating the authCode, use similar process to the `AuthCodeHandler` to include all necessary logging etc (extract out to be used elsewhere)
=> ATO-133: Persist return codes in DynamoDB // ATO-134: Bypass SPoT

interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/entity/InterventionsApiStubResponse.java, interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandlerTest.java
- Switch intervention and state object content in stub AIS response
- Current setup holds intervention fields in state object in JSON and vice versa
- This cannot be correctly parsed by Account Interventions handler
=> BAU: Switch intervention and state object content in stub AIS response

integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/LogoutService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/LogoutServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/CloudwatchMetricDimensions.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java
If the account status received from Account Interventions is `suspended` or `blocked`, destroy all sessions and redirect to account suspended/blocked page.
This PR does not handle destroying the Authentication frontend session.
https://github.com/govuk-one-login/authentication-api/pull/3647
=> ATO-171: Perform back-channel logout if account status is suspended or blocked (v2)

ci/terraform/oidc/authentication-callback.tf
Give orchestration-redirect lambda permission to read user profile dynamo tables.
Fixes deployment error: `.../staging-orchestration-redirect-lambda is not authorized to perform: dynamodb:DescribeTable on resource: .../staging-user-profile`
https://github.com/govuk-one-login/authentication-api/pull/3741 failed during deployment with the above error.
=> ATO-171: Attach policy to give orchestration-redirect lambda read access to user profile dynamo tables

integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/LogoutService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/LogoutServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/CloudwatchMetricDimensions.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java
_This is a duplicate of https://github.com/govuk-one-login/authentication-api/pull/3741 which was reverted (https://github.com/govuk-one-login/authentication-api/pull/3765) due to a pipeline failure._
If the account status received from Account Interventions is `suspended` or `blocked`, destroy all sessions and redirect to account suspended/blocked page.
This PR does not handle destroying the Authentication frontend session.
Note that back-channel logout has not been implemented in `ProcessingIdentityHandler` and is marked as TODO. This will be done in a separate PR.
https://github.com/govuk-one-login/authentication-api/pull/3647
=> ATO-171: Perform back-channel logout if account status is suspended or blocked

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
This will enable us to test client_secret_post support in the integration environment
=> DOT-384: Enable support for client_secret_post token auth in integration

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientSession.java
Add `vtrList` field to `ClientSession` class and initialise it using the existing `effectiveVectorOfTrust` field.
The assumption that we are only returning one VTR is changing, and this is the first step to allowing multiple VTRs to be returned. This is a result of the inherit identities work.
=> ATO-249: Add field to store a list of VTRs in ClientSession

ci/terraform/oidc/build-overrides.tfvars
Remove AIS URI in build
Remove line as it is incorrect and stored in a secret instead.
=> ATO-176: Remove AIS URI in build

ci/terraform/oidc/api-gateway-frontend.tf
- Increase rate limit for the Frontend API in Staging environment
- Required for performance testing
- Accompanies relaxation of limits on accessing the frontend app (in that case for GDS IP addresses only) in the frontend repo: https://github.com/govuk-one-login/authentication-frontend/pull/1278
=> AUT-1958: Increase rate limit staging (frontend API)

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
Code added to retrieve subject identifier and update the session with it exists for the verify code handler (sms code verification). This code has been moved to a helper and is now also being used in the verify mfa code handler (auth app code verification).
The UI is unable to request auth code verification due to API failure with 1001 error returned. The issue is expected to be around the session not having a subject as experienced previously with SMS verification before user logs in.
=> AUT-2217: add subject to session for auth app MFA PW reset journey

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Fix how the AIS URI is resolved so that no part of the path is stripped.
Previously the call to AIS was stripping the environment part of the path, ie. giving
`https://some.uri.com/abc/id` instead of `https://some.uri.com/environment/abc/id`
=> ATO-176: Fix AIS URI

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/LevelOfConfidence.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java
Handle non-medium identities
To allow non-medium ID users to be passed back to the RP
https://github.com/govuk-one-login/authentication-api/pull/3755
=> ATO-27: Handle non-medium identities

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthenticationUserInfoStorageService.java
The Auth user info response is currently stored for one hour in a dynamo table. Increase this to 6 hours.
LITE (one of the RPs) use refresh tokens. We want to keep those working in mostly the same way after the split.
=> ATO-282: Extend auth user info ttl to 6 hours

ci/terraform/oidc/authorize.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
When the login prompt and id token are set, id token is valid and for the correct rp, we should send a reauthenticate claim equal to the rp pairwise id
To allow auth to reauthenticate the user
=> ATO-208: Generate reauthentication claim

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java
Adds a new journey type and code request type for reauthenticating with a two-factor mode of auth app.
This will ensure we have separate counters for the re-authentication journey, meaning that they cannot either request new codes more than the maximum limit, or enter the wrong code too many times.
To support the new re-authentication journey, requiring users to re-authenticate during a journey.
[Equivalent PR](https://github.com/govuk-one-login/authentication-api/pull/3720/files) that adds journey type for password reset (the current PR should look very similar to this)
[PR](https://github.com/govuk-one-login/authentication-api/pull/3738) that adds the a reauth journey for SMS
=> Aut 2122/new journey type for reauth auth app

ci/terraform/oidc/account-interventions.tf
Remove depends on for account interventions lambda.
The endpoint is being created but not deployed.
The code deleted is relevant only for endpoints in the oidc api, not the frontend api.
In staging the frontend call to the api is resulting in a '403 error', suggesting the api is not deployed.  In the console the endpoint is not part of the deployed stage.
https://repost.aws/knowledge-center/api-gateway-authentication-token-errors
=> AUT-1858: Remove 'depends on' for account interventions lambda

scripts/export-ics.sh
Script to calculate internal common subject id for a user.
For testing account interventions using either the stub or in staging, we need to know the internal common subject id for a user.
=> BAU: Script to calculate internal common subject id for a user

ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
Tidy test to use an existing common method and remove unnecessary code, making it more readable
=> ATO-NONE: Tidy test to use common method

ci/terraform/oidc/ipv-handoff-alerts.tf
Update alarm to use both post and pre split metric
So we can alarm on ipv handoff
=> ATO-271: Update alarm to use new metric

ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoEmailCheckResultServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/EmailCheckResultExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultStatus.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoEmailCheckResultService.java
Adds a dynamo table for storing an email check result, consisting of an email address, a status and a time to live.
Also adds read and write functionality (not yet used).
Part of the infrastructure and code that will be needed for adding the email checks - see the [epic ticket](https://govukverify.atlassian.net/jira/software/c/projects/AUT/boards/477?assignee=620a44d9a715c600691222f8&selectedIssue=AUT-2144) for the full architecture diagram.
=> Aut 2148/create email check dynamo

.github/CODEOWNERS
Restrict the codeowners file to just the leads groups
To avoid incompatible changes during the release of phase 1 of the auth orch split
=> ATO-255: restrict codeowners for the duration of the deployment

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/LogoutService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/LogoutServiceTest.java
Change how strings are compared which controls whether to redirect to auth or orch frontend.
`==` compares memory addresses whereas `.equals()` compares content (the intended functionality)
PR containing original change: https://github.com/govuk-one-login/authentication-api/pull/3820
=> ATO-176: Fix improper string comparison

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Pass the RP redirect URI to the auth frontend
Enables https://github.com/govuk-one-login/authentication-frontend/pull/1326
=> ATO-331: pass rp redirect uri to auth frontend

.github/CODEOWNERS
This reverts commit 7c9ad5de86f7b615119e8df0d4b347b7e5d4496c.
Phase 1 deployment is complete; restore original codeowners
=> Revert "ATO-255: restrict codeowners for the duration of the deployment"

ci/terraform/oidc/api-gateway-frontend.tf
Temporarily ignore changes to Frontend WAF acl
We have manually changed the rate limit, so need to stop terraform from trying
to change it back.
=> TEMPORARY: ignore changes to frontend waf acl

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Add metric for failed AIS call
So we can track when AIS calls are unsuccesful
=> ATO-310: Add metric for failed AIS call

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/conditions/UpliftHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientSession.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ClientSessionTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java
- Replace any usages of the old single VTR on `ClientSession` to the new list of VTRs.
- In the cases that our logic requires a single VTR, the VTR with the lowest credential trust value from the list is used.
- The VTR list is audited as a comma separated string.
Currently we assume that we only receive a single VTR, but as part of the inherited identities work we need to be able to handle a list of VTRs.
=> ATO-250: Use VTR list from Client Session where required

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/LevelOfConfidence.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ClientRegistryTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/LevelOfConfidenceTest.java
Update client registry (Java class) to have optional list of LoC and change code so it’s backwards compatible.
Needs to validate level of confidence being requested, as we will be accepting new levels. Different clients can request different levels.
Part of HMRC migration
[ATO-19](https://govukverify.atlassian.net/browse/ATO-19)
[ATO-19]: https://govukverify.atlassian.net/browse/ATO-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ato 23: Allow custom LoCs per RP

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/UserMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java
Added the phoneNumberLastThree field to the CheckUserExists API response.
Previously decided to user CheckUserExists API to present data for the new MFA PW reset journey as the user is not logged in before this journey so we require more information to proceed through the screens. This update adds the last 3 digits to API response so that the frontend can use it for the text 'We have sent a code to your phone number ending with XXX'.
=> add part phone number to user exists api

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java
When on an auth-only journey, and Account Intervention Service responds with `blocked = false`, `suspended = true`, `resetPassword = false`, `reproveIdentity = true`, continue to RP (without requesting user to reprove identity).
Updated requirement: see [slack thread](https://gds.slack.com/archives/C04N83W7V2N/p1706545004908939)
=> ATO-342: Update AIS logic to permit users to continue to Auth only services

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Improve coverage of error handling when making requests to and serialising the response from Account Intervention Service.
Refactor Account Intervention Service to improve readability.
Rename CloudWatch metric from `AISCallFailure` to `AISException` to better reflect it's usage.
In order to properly test the AIS connection timeout (https://github.com/govuk-one-login/authentication-api/pull/3862), additional error handling is required.
This work branched off https://github.com/govuk-one-login/authentication-api/pull/3850 and so will be merged into ATO-315.
=> ATO-334: Add additional error handling in Account Intervention Service

ci/terraform/shared/production-stub-clients.tfvars
Fix prod urls in terraform for stub clients
They were incorrect originally
=> ATO-159: Fix production urls in tf for stub clients

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java
Accept blank claims in authorize request
While helping an RP diagnose an integration issue we spotted some poor error handling around requests that don't perfectly match the documentation. We should be slightly more permissive in what we accept.
=> ATO-340: Accept blank claims in authorize request

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/variables.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
Configure timeout for requests to AIS as an environment variable with a default value of 5 seconds.
AIS should take no longer than 5 seconds to respond.
An environment variable is used to allow for experimentation in different envs.
Will require testing in staging to ensure the timeout functions correctly and that 5 seconds is an acceptable initial value.
=> ATO-316: Manually set connection timeout for request to Account Intervention Service

integration-tests/src/test/java/uk/gov/di/authentication/api/EmailCheckResultWriterIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoEmailCheckResultServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultSqsMessage.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultStore.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/EmailCheckResultWriterHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoEmailCheckResultService.java, shared/src/test/java/uk/gov/di/authentication/shared/lambda/EmailCheckResultWriterHandlerTest.java
- Add email check result handler 
- Also add a field to the expected SQS and Dynamo store as agreed schema changed since initial work was done on that (see "Related PRs")
- This extra field will allow us to trace a request from the point that it is triggered all the way through to the result storage
- Note: the extra DB field is kept separate in the first commit. Subsequent work to implement the handler (the main focus of the Jira ticket) is in the second commit
- This will record the results of a counter fraud check of emails (implementation details of that check are in a separate private repository)
- The results of that check can be used to block certain user journeys in case of a negative result (not currently implemented)
- As noted above, the work of this PR has been augmented to …
=> AUT-2149: Add email check result handler

ci/terraform/shared/staging-stub-clients.tfvars
Add performance testing stub to staging db
To allow performance testers to use the stub
=> ATO-159: Add performance testing stub to staging

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/UserMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java
Added the phoneNumberLastThree field to the CheckUserExists API response.
Previously decided to user CheckUserExists API to present data for the new MFA PW reset journey as the user is not logged in before this journey so we require more information to proceed through the screens. This update adds the last 3 digits to API response so that the frontend can use it for the text 'We have sent a code to your phone number ending with XXX'.
=> add last 3 of phone number to user exists api for sms pw reset journey

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CodeRequestType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/CodeRequestTypeNotFoundException.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/CodeRequestTypeTest.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/SessionTest.java
Prevent null data from being added to the client registry when invalid MFA and Journey combination sent.
This is causing `com.google.gson.JsonSyntaxException: duplicate key: null: java.lang.RuntimeException` in production. 
See: https://gds.slack.com/archives/C060UE8NSP4/p1704990806624429
[ATO-212](https://govukverify.atlassian.net/browse/ATO-212)
[ATO-212]: https://govukverify.atlassian.net/browse/ATO-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ato 270/authcodehandler throwing exception in prod

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckReauthUserRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
- Do a look up the user's profile via email in the input request
- Recalculate the RP pairwise ID, and compare pairwaise IDs of the signed-in user and user requesting re-authentication
- Return 200 http status code if there is a match, 400 http status code if no match or user not found
To verify if re-authentication request is valid by comparing signed in user and user requesting re-authentication
=> AUT-2127: Create CheckReAuthUser handler

ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/shared.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, ci/terraform/shared/sqs-policy.tf, ci/terraform/shared/sqs.tf, ci/terraform/shared/variables.tf
Adds sqs queue and dead letter queue to request an email check. This will be written to from the frontend as well as the account management api, and read from the email checking lambda.
Also adds an access policy for the account management api.
Support email checking as part of sign up / email changes.
=> Aut 2146/create email check sqs

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Adds an `isEmailCheckEnabled` flag, backed by `SUPPORT_EMAIL_CHECK_ENABLED` to the authentication `ConfigurationService`.
This allows the bypassing of the email checking logic in stable environments while the feature is being developed.
This will be used by:
- https://github.com/govuk-one-login/authentication-api/pull/3912
- https://github.com/govuk-one-login/authentication-api/pull/3891
=> AUT-2340: Add `isEmailCheckEnabled` flag to authentication `ConfigurationService`

ci/terraform/oidc/variables.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
Reduce Account Interventions Service call timeout from 5 second to 1 second
It should not take longer than 1s to receive a response from AIS. Orchestration should wait as little time as possible.
=> BAU: Reduce Account Interventions Service call timeout from 5 second to 1 second

ci/terraform/oidc/s3-objects.tf
Added Public block to S3 bucket.
Old bucket which were created before the public Block setting was enabled at account setting are getting flagged in CPC finding as Public block missing
=> AUT-2260 Added Public block S3 bucket

ci/terraform/shared/sandpit.tfvars
Add new sandpit stubs to client registry
So we can use sandpit stubs to enter the flow
Note: I've added a docapp stub here, but it won't work currently as we don't have a cri stub set up. The resources will be generated so that in future if we do set it up it will be available to us
=> ATO-350: Add new sandpit stubs to client registry

ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/ProcessingIdentityInterventionResponse.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/ProcessingIdentityStatus.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java
Return the intervention redirect url in a format useful to the auth frontend
We realised during testing that this intervention does not work
https://github.com/govuk-one-login/authentication-frontend/pull/1352
=> ATO-364: Return intervention response for action by auth frontend

.github/PULL_REQUEST_TEMPLATE.md
Checklist item for orch auth mutual dependencies.
Make PR authors and reviewers aware of mutual dependencies.
=> BAU: Checklist item for orch auth mutual dependencies

ci/terraform/oidc/account-interventions-alerts.tf, ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/variables.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
- Alarm triggers a Pager Duty alarm only in production and when `account_intervention_service_abort_on_error == true`.
- Otherwise a slack alarm is generated.
To quickly catch and resolve errors due to communicating with Account Intervention Service.
Values for threshold and period have been reused from the other alarms. Is this reasonable?
- Tested in sandpit (calling the Account Interventions stub) and alarm is correctly picking up AIS exceptions.
- Next test is in staging with a real error response from AIS.
=> ATO-317: Add CloudWatch metric alarm for Account Intervention Service exceptions

ci/terraform/oidc/account-interventions.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Added abortOnAccountInterventionsErrorResponse feature flag that when turned on and AIS returns an error, the lambda aborts and returns the error response. When turned off, if AIS returns an error response, a default error response is returned. A default timeout has been added for AIS to respond within.
Also in this PR, some refactoring for improved readability.
The purpose of this switch and associated logic is to handle errors that occur when AIS is not working as intended. 
In particular pay attention to classes representing Session data where changes need to be applied on both sides to avoid deserialization …
=> AUT-2295:  Added abortOnAccountInterventionsErrorResponse Flag and Refactored

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/VectorOfTrustTest.java
Update vtr validation to account for the new list format. 
- Vtrs must contain either all identity vectors (have P-values) or all non-identity vectors (do not have P-values)
=> ATO-248: Update vtr validation

ci/terraform/oidc/build-overrides.tfvars
Point build at the new DCMAW stub
We can no longer use the PaaS hosted stub
=> BAU: Point build at the new DCMAW stub

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvUserIdentityTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientSession.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/conditions/DocAppUserHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java
Remove instances of `effectiveVectorOfTrust` and tag deprecated field
To remove dead code and mark code for deletion for when auth no longer depends on it
https://github.com/govuk-one-login/authentication-api/pull/3887
https://github.com/govuk-one-login/authentication-api/pull/3889
https://github.com/govuk-one-login/authentication-api/pull/3897
=> ATO-251: Tidy and tag deprecated code

ci/terraform/shared/sandpit.tfvars
Use `dev` in domains for sandpit stubs
See note here: https://github.com/govuk-one-login/relying-party-stub?tab=readme-ov-file#deploy-to-dev
=> BAU: Use dev in domains for sandpit stubs

.github/workflows/checkov.yml, .github/workflows/deploy-orch.yml, .github/workflows/pre-merge-checks-sam.yml, template.yaml
New GitHub action that builds out the Java artefact and invokes the Dev Platform action for secure pipelines.
Require for phase 3 of orch/auth split.
[ATO-307](https://govukverify.atlassian.net/jira/software/c/projects/ATO/boards/390?selectedIssue=ATO-307)
[ATO-307]: https://govukverify.atlassian.net/browse/ATO-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATO-319: New GitHub Action to Trigger Orch Deployment in Parallel

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/TokenGeneratorHelper.java
- Add `getVtrList` to get the vtrList from either the authRequest or, if not present in request and reauth has been requested, from the `id_token_hint` (in which case the previously granted vot will be used)
- Add vot claim to `generateIDToken` in `TokenGeneratorHelper` for mocking in tests
In particular pay attention to classes representing Session data where changes need to be applied on both sides to …
=> ATO-332: Update where to get vtr on reauth

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
We think this is causing issues in build and staging
Bump default timeout from 1000ms to 3000ms for getting response from account interventions.
We believe this is causing acceptance tests to fail as the lambdas cold start and taking longer to respond.
=> AUT-2295: Bump account interventions timeout

ci/terraform/oidc/variables.tf
We think this is causing issues in build and staging
Bump default timeout from 1000ms to 3000ms for getting response from account interventions.
We believe this is causing acceptance tests to fail as the lambdas cold start and taking longer to respond.
=> AUT-2295: Bump account interventions timeout default

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/exceptions/AccountLockedException.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Create invalid email entered lock when during re-authentication
- Create a new lock when user has entered their sign-in details too many times
- Creates a new prefix value in Redis `multiple-incorrect-reauth-email`
- Prevents the user from attempting to sign in multiple times
=> AUT-2094: Create invalid email entered lock when during re-authentication

ci/terraform/interventions-api-stub/variables.tf
Set minimum provisionned concurrency for the interventions stub lambda.
There are intermittent failures in the build pipeline which look related to long cold starts for the lambda.
#3963
=> BAU: Set minimum provisionned concurrency for the interventions stub lambda

ci/terraform/modules/txma-audit-queue/key.tf, ci/terraform/oidc/spot-sqs.tf, ci/terraform/shared/kms.tf
AWS Customer Managed Keys Backing Key Rotation Enabled (CPC-221)
KMS key are missing Rotation Enabled enabling the same as they are getting Flagged as non compliance in CPC-221
=> AUT-2263 Enable KMS key rotation for kMS key

ci/terraform/oidc/ecc-signing-key.tf, ci/terraform/oidc/ipv-authorize.tf
- Create a new KMS key using the ES256 signing algorithm
- Create a new policy for use of the signing key
- Attach the policy to the Lambda role for IPVAuthorisationHandler
This will allow Orchestration to send a signed JWT in the JAR request to IPV
Tested in sandpit: new KMS key can be retrieved and used to sign a message, only by the lambda with the permission to do so
- [✓] Impact on orch and auth mutual dependencies has been checked.
=> ATO-97: Create KMS signing key for storage token sent to IPV

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UnsuccessfulAccountInterventionsResponseException.java
* Adds a specific log message for when the request to the Account Interventions Service times out
* Refactors the Account Interventions Service to use the standard java http library, rather than the OAuth library (since we're not making an OAuth request to the Account Interventions service). This also makes it easier to catch the specific timeout exception and log.
* Moves all the logic to call the account interventions api to the Account Interventions service, so it's all in one place.
We're seeing generic IOExceptions being thrown in build and staging, we think because the call to the API is timing out. It is useful for debugging purposes to specifically log when a request has timed out, since it's more difficult to know what happened with the more generic error.
=> Aut 2399/fix logging on timeouts

ci/terraform/oidc/account-interventions.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Adds two feature flags:
1. ACCOUNT_INTERVENTIONS_SERVICE_ACTION_ENABLED - when false,  we still make a call to the account interventions service, but we discard the result (whether a 4xx
or 5xx, or a successful response that may indicate interventions) and return the no interventions response.
2. ACCOUNT_INTERVENTIONS_CALL_ENABLED - when false, the account intervention handler takes no action (does not call the account interventions api) and just returns a no interventions response, so this has the effect of being a feature flag for all the behaviour.
This will allow us to validate the implement account interventions slowly, by adding a step where we can analyse the results of the interventions without having an impact on the user journey.
I've based this off the changes in [this …
=> AUT-2397: Add feature flags for auth account interventions

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
Always return false for client consent from client reg
Setting this value to true breaks the client
https://github.com/govuk-one-login/authentication-api/pull/3694
=> ATO-386: Always return false for consent required

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
Log reauthentication header in StartHandler.
Gain visibility on whether reauthentication is set.
=> BAU: Log reauthentication header in StartHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
The application will record the first instance of the AUTH_ACCOUNT_TEMPORARILY_LOCKED event on the login attempt where the user is locked out and not the subsequent attempt.
During investigation of https://govukverify.atlassian.net/browse/AUT-2316  it was found that there was less than 15 minutes between events AUTH_ACCOUNT_TEMPORARILY_LOCKED and  AUTH_LOG_IN_SUCCESS which lead to the belief that the 15 minute timeout was not working as expected. 
The application only records the AUTH_ACCOUNT_TEMPORARILY_LOCKED event if the user makes a subsequent attempt after being locked out so the lockout actually started on the last instance of AUTH_INVALID_CREDENTIALS prior to this.
=> AUT-2318: audit event and user feedback on 5th failed login attempt

ci/terraform/account-management/authorizer.tf
Revert the change to the account mgmt authorizer env var name.
It uses shared, not orch-shared, so needs the old name
https://github.com/govuk-one-login/authentication-api/pull/3981
=> INCIDEN-688: Fix environment variable name

ci/terraform/oidc/account-interventions-alerts.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Added alarm that goes off when receiving a specified amount of 4xx or 5xx responses from AIS
- Added an alarm that goes off when the auth AIS lambda fails specified number of times. This then notifies whoever is on pager duty.
Alarms needed to be implemented since it indicates issues with the interventions api, or our integration with it. 
=> AUT-2398: Raise alarm when receiving invalid AIS responses/auth AIS lambda fails

echo-int-test-vars.sh, integration-tests/build.gradle, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java, oidc-api/docs/AuthorisationHandler.md
Remove unnecessary references to old stub urls
Stub is now hosted on AWS
=> ATO-399: Tidy up references to stub

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java
Move AIS timeout from HttpClient config to HttpRequest config
Timeout was incorrectly configured to be on HttpClient; timeout on HttpRequest is the intended behaviour.
=> ATO-395: Move AIS timeout from HttpClient config to HttpRequest config

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
We should be passing the RP pairwise identifier from the id token hint to auth, not the audience
=> BAU: Fix reauthentication

.github/workflows/deploy-orch.yml, template.yaml
Get Orch's first backend lambda working
Orch be pipeline currently failing.
=> ATO-320: Fix lambda deployment

ci/terraform/oidc/production.tfvars, ci/terraform/oidc/variables.tf
Switch off account recovery block in all envs except prod.
The 2FA before password reset flow obviates the need for the recovery block.
=> BAU: Switch off account recovery block in all envs except prod

ci/terraform/oidc/account-interventions-alerts.tf
Adding resource dependencies for Account interventions Alarm
In future if we enable  Account interventions flag for Prod or Int env there needs a dependencies for data read for Alarm Creation if this is not done the Terraform plan will fails "
[3997](https://github.com/govuk-one-login/authentication-api/pull/3997)
=> Adding resource dependencies for Account interventions Alarm

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
Trigger lambda deploy with an extra newline.
A previous config change did not trigger a deploy to apply the config, so making a code change to do so.
#4030
=> BAU: Trigger lambda deploy with an extra newline

ci/terraform/oidc/production.tfvars, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
Switch off the account recovery block in prod.
The account recovery block is no longer needed given the 2FA before password reset flow
#4030 
Only to be merged with: https://github.com/govuk-one-login/authentication-frontend/pull/1412
=> DO NOT MERGE: BAU: Switch off the account recovery block in prod

template.yaml
- Set orch default lambda memory size
- Set orch default lambda timeout
- Update orch WellKnownFunction path
Lambda failing to run due to default settings.
=> ATO-320: Fix Orch well-known Lambda

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
We need to call ThreadContext.clearMap(); on every invocation
otherwise we log identifiers from the previous request
https://github.com/govuk-one-login/authentication-api/pull/2891
=> BAU: Clean logging context on lambda invocation

shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SnsTopicExtension.java
Increase SNS test fixture timeout from 1s to 2s.
We've been seeing some flakey tests where this timeout is being exceeded. Let's see if 2 seconds is enough, or if there's something more serious wrong
```
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a uk.gov.di.authentication.sharedtest.extensions.SnsTopicExtension 
Expected: a value greater than <0>
but: <0> was equal to <0> within 1 seconds.
at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
at …
```
=> BAU: Increase SNS timeout

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/dev-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars, ci/terraform/shared/production-stub-clients.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging-stub-clients.tfvars
Add the wallet-subject-id to scopes for the stubs so that they are added to the client registry and can be requested
=> ATO-361: Add wallet-subject-id scope to stubs allowed scopes

ci/terraform/account-management/account.tf, ci/terraform/account-management/authorizer.tf
Add alerting to AM API Gateway lambda authorizer
We had an incident where we were unaware that this was broken for approx 2 hours.
=> INCIDEN-702: Add alerting to AM API Gateway lambda authorizer

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, integration-tests/build.gradle, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCapacityHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, ipv-api/src/test/resources/uk/gov/di/authentication/ipv/services/approvals/IPVAuthorisationServiceTest.SignedJwtRequest.shouldConstructASignedRequestJWT.approved.json, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/StorageTokenService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/HandlerIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
- Add storageAccessToken claim to JAR sent to IPV
- Create a new service (StorageTokenService) to generate and sign the token.
- Feature flag the implementation and enable in sandpit, build, and staging envs.
- No unit test coverage for StorageTokenService as a subsequent PR will combine this service with the existing shared/TokenService.
- IPV need this token in order to request VCs from Bravo 
https://github.com/govuk-one-login/authentication-api/pull/3981
=> ATO-95: Add storageAccessToken claim to JAR sent to IPV

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/ipv-authorize.tf
Move storage token kms signing policy from ipv-authorize to authentication-callback
Policy mistakenly added to wrong lambda: ipv-authorize is deprecated, authentication-callback is the lambda which requries these permissions.
https://github.com/govuk-one-login/authentication-api/pull/3944
=> ATO-97: Move storage token kms signing policy from ipv-authorize to authentication-callback

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckReauthUserRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java
- Pass in `rpPairwiseId` from frontend request and compare the value with a calculated pairwise ID
- Add logs for debugging in build
=> bau-reauth-logs: Log rp IDs for verifying reauth journey in dev environments

ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/production-overrides.tfvars
Use new aud claim for docapp in int and prod
This has been tested in staging, this change rolls out to production and integration
https://github.com/govuk-one-login/authentication-api/pull/3967
=> ATO-385: update production and integration doc app audience claims

scripts/_set-up-sso.py, scripts/requirements.txt, scripts/set-up-sso.sh
To avoid dependency errors, enforce running the SSO setup script from the wrapper script.
This will ensure that the virtual environment is set up correctly and that the necessary dependencies are installed.
Also, remove the fixed versioning on the python dependencies - we are safe to use latest here as these are well-established APIs, and this increases the number of supported python versions.
1. Run the script with `python3 scripts/_set_up_sso.py`, observe that an error occurs and the script does not run.
1. Run the script with `scripts/set-up-sso.sh`, observe that the script runs as expected.
=> BAU: Enforce running SSO setup script from wrapper

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java
validateVerificationCode in the ValidationHelper class has been enhanced so that journeyType is passed in as well as notificationType. As this is where we pass the lockout duration to the codeStorageService it's the best place to check if we are dealing with SMS codes during registration or 2fa account recovery and pass a lower lockout duration of 15 mins.
From a review of existing OPT/MFA code attempts and retry functionality it was highlighted that SMS MFA code retry lockout duration should not be extended to 2 hours like other codes.
=> AUT-2480: separate 15min lockout for sms code entry during registration and 2fa account recovery

ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactory.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Email OTP code retry limit has been removed for registration journey. VerifyCodeHandler required updating and some minor refactoring elsewhere.
From a review of existing OPT/MFA code attempts and retry functionality it was highlighted that there is no security need for blocking users due to incorrect email OTP code entries for registration journey only.
=> AUT-2453: Increase retry attempt count for email OPT codes during registration journey

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordCompletionRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
Created PASSWORD_RESET_INTERVENTION_COMPLETE audit event to be submitted when the isForcedPasswordReset variable == true after receiving the request from the front end. 
Alongside this ResetPasswordCompletionRequest.java (and associated tests) has been refactored to use a record for brevity and readability.
1. Review alongside the associated PR for the frontend (https://github.com/govuk-one-login/authentication-frontend/pull/1443)
2. Check that the argument being passed in the frontend as part of the updatePassword method can be accessed in the backend
3. Check that the acceptance criteria outlined in the ticket have been met (see https://govukverify.atlassian.net/browse/AUT-2543)
https://github.com/govuk-one-login/authentication-frontend/pull/1443
=> AUT-2543: Created audit event for completing a password reset intervention

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java
This is returned to us by the account interventions api, but we do not pass it back in the api response to the frontend. Exposing this information to the frontend will enable us to add logic to ensure that people do not go through a password reset journey twice before the account interventions api has been updated with the fact that the user has reset their password, while also ensuring that newer interventions are respected.
1. Code Review should suffice
This PR has a do not …
=> AUT-2552: Add applied at timestamp to account interventions response

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
When a user is in the re-auth or the default sign-in journey, and they are entering their password they should hit a lockout when they enter the wrong password more than 5 times, on the 6th attempt
- The lockout is activated on the 5th attempt which is incorrect, it should activate on the 6th attempt
- This change will also apply to the standard sign-in journey
- Modify the `PASSWORD_MAX_RETRIES` env variable from 5 to 6 in the configuration service
1. Code Review
2. Test the default sign in journey in sandpit
3. After merge, test the reauth sign-in journey in build as reauth is untestable in sandpit at the moment
=> AUT-2530: Increase incorrect enter password max retries

integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
Update the client registry API to allow the backchannel logout URI to be configured. This is required by the self-serve interface
Code review only
=> ATO-439: Allow backchannel logout URI to be updated using the client registry API

ci/terraform/oidc/authdev1.tfvars
Switch on the auth orch split in authdev1.
Not having this switched on is stopping the local frontend connection to the backend in authdev1 from working
1. Deploy the oidc component to authdev1.
2. Open the AWS console and go to the 'authdev1-authorise' lambda.
3. Check that the environment variable SUPPORT_AUTH_ORCH_SPLIT is set to true.
=> BAU: Switch on the auth orch split in authdev1

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/CloudwatchMetricDimensions.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionResponse.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionState.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionStatus.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
_This PR is solely refactoring. It contains no logical changes._
- Rename `AccountInterventionStatus` --> `AccountInterventionState` to better reflect its purpose
- Create `AccountInterventionStatus` `enum` to hold list of possible account interventions
- Encapsulate logic, for determining which account intervention is applied, into `AccountInterventionState` class
To make the account intervention logic on return from auth (in `AuthenticationCallbackHandler`) easier to understand and maintain
=> ATO-347: Encapsulate account intervention logic

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAccessTokenServiceIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccessTokenStoreExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeStore.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/token/AccessTokenStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AccessTokenService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java
Adds the ability to send a "password reset time" through in the request to the auth code handler. 
If this is present in the request to auth code, we:
* Add it to the auth code table in the Authentication Auth Code Handler
* Add it to the access token table in the Token Handler (which reads from the auth code table)
* Send this back as a claim in the user info response.
This will enable orchestration to implement logic to ignore a password reset intervention when a password has been reset more recently than the intervention was applied. This makes our system more robust, meaning we're not reliant on the async process which updates the account interventions data when a password is reset.
This is very similar to what we did for `isNewAccount`.
We've deployed this to sandpit on its own, and …
=> Aut 2553/pass timestamp to orch

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java
- When a user attempts to reauthenticate with a different email that does not exist in the user profiles store, the user is allowed to make multiple attempts
- This gives the user a large number of tries and is also a backdoor way to find out which emails have accounts
- Verify if the account has been locked and return the appropriate error
1. Code Review
2. Test in build only as reauthentication journey unable to test in sandpit environments
=> AUT-2583: Verify account locked for user not found during reauthentication

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthExternalApiStubExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountIntervention.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionDetails.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionResponse.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccountInterventionState.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/AccountInterventionTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
- Redefined account interventions class structure. Two immutable classes are defined which hold the the raw response from AIS (`AccountInterventionState` and `AccountInterventionDetails`). A further class, `AccountIntervention`, handles account interventions logic applicable to Orchestration.  The idea is that in future, a developer should only need to use `AccountIntervention` and none of the other classes in production code.
- Updated codebase to use new structure.
- Serialised more of the response from account intervention service into `AccountInterventionDetails` which includes `appliedAt` value (the time that the intervention was applied).
- Read `password_reset_time` claim from Authentication
- Implement fix for race condition: if `password_reset_time` is after `appliedAt` then …
=> ATO-440: Account interventions reset password race condition

ci/terraform/shared/outputs.tf, ci/terraform/shared/stub-rp-clients.tf
We need to remove the old stub client registry entries. However we currently can't do this without causing stub downtime, as removing one entry will update them all, as they are generated using 'count'. I've a second set of entries indexed by the name of the stub, which means if we remove one from the list, it will only affect that entry (checked with a terraform plan).
=> ATO-404: Add new client registry entries for stub using for_each

ci/terraform/oidc/api-gateway.tf
Manually specify the API Key Source for API Gateway. It defaults to "HEADER" when no value is specified. SSE tool depends on this. This was manually changed in one environment, and lead to some hard to find issues
=> BAU: Explicitly specify the API Key Source for the API Gateway

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java
We will need this on the frontend to differentiate between a reprove identity temporary suspension (in which case certain actions are allowed, like resetting a forgotten password) and a suspension without actions (in which case certain actions are not allowed).
1. Code Review
[PR](https://github.com/govuk-one-login/authentication-frontend/pull/1468) that adds this to the response type on the backend (plan is to merge that first)
=> AUT-2623: Add reprove identity to account interventions service response

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Pass RP state to auth.
They need this to correctly return to the RP from ipv-callback in the event of an error.
https://github.com/govuk-one-login/authentication-frontend/pull/1472
=> ATO-449: Pass RP state to auth

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/exceptions/AccountLockedException.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
- During re-auth, when a user has been blocked for entering incorrect password too many times, the user is still able to proceed to complete the re-auth journey.
- The Reauth handler will now validate to check whether the user has been blocked from entering too many incorrect password
1. Code Review
=> AUT-2613: Check if account has been locked for entering max password attempts in re-auth journey

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java
Elements of the re-authentication journey need to be outlined and available for the analytics team ahead of go live in order to ensure reporting is available.
- Include AuditService to CheckReAuthUserHandler class
- Trigger audit event `ACCOUNT_TEMPORARILY_LOCKED` when user is locked from continuing the reauthentication journey
- Trigger audit event `REAUTHENTICATION_SUCCESSFULL` when reauthentication is successful
- Trigger audit event `REAUTHENTICATION_INVALID` when user not found or there's no match in the reauthentication check
- Update tests
1. Code Review
2. Verify Audit Events are being triggered in the environments when running the reauth journey
=> AUT-2431: Create audit events to indentify reauthentication start and end journeys

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/variables.tf
- Update orch frontend stack name to match updated name in orchestration-frontend repo
- Add comment about flag in orchestration-frontend (see PR below) which should be kept in sync with `orch_frontend_api_gateway_integration_enabled` flag
1. Check that stack names now match (see CloudFormation in AWS)
2. Does comment make sense?
PR which adds new flag to orchestration-frontend:
https://github.com/govuk-one-login/orchestration-frontend/pull/221
=> ATO-457: Fix deploying orchestration frontend to sandpit

template.yaml
Fix deployment of Orchestration CloudWatch alarms
- `ReturnData` defaults to `true`
- `ReturnData` must be `true` for exactly one of the list of metrics
- Therefore need to explicitly set `ReturnData` for every metric
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html#cfn-cloudwatch-alarm-metricdataquery-returndata
1. Code review only
This issue was noticed after adding the deploy dev script: …
=> ATO-480: Fix deployment of Orchestration CloudWatch alarms

oidc-api/build.gradle, oidc-api/src/test/java/uk/gov/di/authentication/oidc/contract/AccountInterventionServiceTest.java
- Add contract tests for communication with Account Intervention Service.
- Tests cover all the possible intervention outcomes based on the data in the response from AIS.
- Tests also cover error response statuses from AIS (from the spec [here](https://github.com/govuk-one-login/account-interventions-service/blob/main/src/specs/api.yaml)), and whether we abort or assume no intervention, depending on the value of the abort flag.
1. Code Review
2. Run the tests
3. Check the [AIS API spec](https://github.com/govuk-one-login/account-interventions-service/blob/main/src/specs/api.yaml) - are the tests missing anything?
=> ATO-359: Account Interventions contract tests

oidc-api/build.gradle
- Fix pact path for contract tests in OIDC API
- `/oidc/` doesn't exist, it should be `/oidc-api/`
- Code review only
=> BAU: Fix pact path for oidc-api contract tests

ci/terraform/oidc/doc-app-authorize.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/userinfo.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuditServiceTest.java
- Removed "/" from end of audit event component ID
- Add OIDC_API_BASE_URL env var to config for handlers emitting audit events with "UNKNOWN" component ID
See [here](https://govukverify.atlassian.net/wiki/spaces/~712020ca5ac93cd97f4e89b368ea8355f2af55/pages/3901685867/Component+ID+Analysis) for a breakdown of the known issues.
=> ATO-296: Fix Audit Event Consistency Issues

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Records metrics of the length of RP state parameter. In response to the attached incident, we may want to limit the length of RP state parameters. To do this with confidence, we should gather data on state lengths being sent currently.
=> INCIDEN-723: record rp state length

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Wrap non-essential metric in a try to ignore errors
=> BAU: defensive coding for non-critical metric

ci/terraform/test-services/integration.tfvars, ci/terraform/test-services/variables.tf
There is already a secret set for this that we read in as a terraform environment variable on deploy, but because we also set it to an empty string it overrides the variable we have for it set as a terraform variable.
This seems to be why the create account smoke test is failing, since it depends on deleting the synthetics user. At the moment, we don't set a synthetics user, meaning that the request to the test services api 404s (there is no user set in the environment variable to delete), and the smoke test fails as we attempt to create an account as a user where we have not deleted their account first.
I have also set a default on the variable in the case of it not being present in secrets.
1. Code Review
=> AUT-1506: Remove synthetics_users variable from integration tfvars

ci/terraform/test-services/build.tfvars, ci/terraform/test-services/dev.tfvars, ci/terraform/test-services/production.tfvars, ci/terraform/test-services/sandpit.tfvars, ci/terraform/test-services/staging.tfvars
This removes tfvars for synthetics users, which were overriding a value set in secrets, and causing the create account smoke test to fail. The test was failing as it it depends on deleting the synthetics user. At the moment, due to the overriding value being empty, we don't set a synthetics user, meaning that the request to the test services api 404s (there is no user set in the environment variable to delete). This causes the smoke tests to fail as we attempt to create an account as a user where we have not deleted their account first.
Note that this variable is set as a secret for sandpit, build and production. Staging does not have the variable, but smoke tests are not run in this environment and it's OK therefore for it to default to this empty string.
The equivalent change has worked …
=> Aut 1506: Fix create account smoke test in production and sandpit

ci/stack-orchestration/manual-stacks/txma/README.md, ci/stack-orchestration/manual-stacks/txma/template.yml
- TxMA infrastructure added as a manual stack - it is intended to be deployed to Orchestration accounts only once, and not as part of the pipeline.
- Note that the stack has already been deployed to all envs.
1. Code review
=> ATO-369: Add stack for deploying TxMA infrastructure to Orchestration accounts

build.gradle, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/ClientSessionServiceIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/build.gradle, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/JsonUpdateHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/JsonUpdateHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/build.gradle, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientSession.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/JsonUpdateHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/JsonUpdateHelperTest.java
- ClientSessionService now updates new / altered ClientSession fields without deleting existing fields if they are not maintained in both Orchestration and Authentication versions of ClientSession
https://github.com/govuk-one-login/authentication-api/pull/4039
=> ATO-98: Added JsonUpdateHelper class to avoid overwriting ClientSession fields in Redis

ci/stack-orchestration/configuration/dev/vpc/parameters.json, ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
- Change orch vpc cidr block
- Update api-gateway terraform to use new orch vars
Click-ops for orch side can be found at:
https://govukverify.atlassian.net/wiki/spaces/Orch/pages/4097867900/Enabling+vpc-peering|
Ensure orch account id's and vpc-id's are corrrect
Ensure feature flag is correctly set
[580](https://github.com/alphagov/di-infrastructure/pull/580)
This could be:
- PRs that depend on this one
- PRs this one depends on
- If this work is being duplicated in other …
=> ATO-442: Add support for vpc peering

ci/terraform/shared/kms-policies.tf, ci/terraform/shared/outputs.tf, ci/terraform/utils/email_check_results_writer_dynamo_access.tf, ci/terraform/utils/email_check_results_writer_lambda.tf, ci/terraform/utils/email_check_results_writer_sqs_permissions.tf, ci/terraform/utils/shared.tf, ci/terraform/utils/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/EmailCheckResultWriterIntegrationTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandlerTest.java
- Add terraform to deploy email check result writer lambda
As a prerequisite for the pipeline to deploy this successfully, we have populated a number of secrets:
- /deploy/sandpit/email_check_results_sqs_queue_arn
- /deploy/sandpit/email_check_results_sqs_queue_encryption_key_arn
- /deploy/build/email_check_results_sqs_queue_arn
- /deploy/build/email_check_results_sqs_queue_encryption_key_arn
- /deploy/staging/email_check_results_sqs_queue_arn
- /deploy/staging/email_check_results_sqs_queue_encryption_key_arn
- /deploy/integration/email_check_results_sqs_queue_arn
- /deploy/integration/email_check_results_sqs_queue_encryption_key_arn
- /deploy/production/email_check_results_sqs_queue_arn
- /deploy/production/email_check_results_sqs_queue_encryption_key_arn
- This will record the results …
=> AUT-2273: Add terraform to deploy email check result writer lambda

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
- Change default SUPPORT_AUTH_ORCH_SPLIT values to true.
- Update out of date integration tests that don't support post Auth/Orch split behaviour.
=> ATO-414: Default SUPPORT_AUTH_ORCH_SPLIT to true

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, ci/terraform/auth-external-api/token.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java
Remove usage of SUPPORT_AUTH_ORCH_SPLIT in Auth TokenHandler
=> ATO-413: Remove Usage SUPPORT_AUTH_ORCH_SPLIT - Auth - TokenHandler

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, ci/terraform/auth-external-api/userinfo.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java
Remove usage of SUPPORT_AUTH_ORCH_SPLIT in Auth UserInfoHandler
=> ATO-411: Remove Usage SUPPORT_AUTH_ORCH_SPLIT- Auth - UserInfo

.github/workflows/contract-tests.yml
Shorten branch name used on pact broker for better readability
https://github.com/govuk-one-login/ipv-core-back/pull/1824
=> ATO-NONE: Shorten branch name used on pact broker

.github/workflows/contract-tests.yml, ipv-api/build.gradle, oidc-api/build.gradle
- Automatically upload pacts to the broker using GHA
- Comment out the provider tests as we only want consumer tests at the moment
Ensure pipeline is running as expected and pacts are being uploaded to the broker
=> ATO-NONE: Turn on consumer test upload to the pact broker

ci/terraform/oidc/api-gateway-frontend.tf
Force redeploy of check_reauth_user in api gateway on changes
The endpoint is not being deployed in staging as it is missing these dependencies
Tested in sandpit to prove that the terraform works.
1. Code Review
#4229
=> BAU: Force redeploy of check_reauth_user in api gateway on changes

ci/terraform/.terraform.lock.hcl, ci/terraform/account-management/.terraform.lock.hcl, ci/terraform/account-management/dynamo-policies.tf, ci/terraform/auth-external-api/.terraform.lock.hcl, ci/terraform/delivery-receipts/.terraform.lock.hcl, ci/terraform/interventions-api-stub/.terraform.lock.hcl, ci/terraform/oidc/.terraform.lock.hcl, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/shared/build.tfvars, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/integration.tfvars, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, ci/terraform/shared/production.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf, ci/terraform/test-services/.terraform.lock.hcl, ci/terraform/utils/.terraform.lock.hcl, ci/terraform/versions.tf
Add resource policy to allow access from corresponding orchestration account and update terraform version to allow for this
For example:
1. Code Review
1. Check policy 
1. Check feature flagged for environments
1. Check account IDs are correct
https://github.com/govuk-one-login/authentication-api/pull/4225
=> ATO-472: Add dynamo cross account policy

ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/login.tf, ci/terraform/oidc/mfa.tf, ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java
Lockout duration and lockout count TTL were mixed up so they have been separated and a new environment variable _lockout_count_ttl_ has been introduced.
1. Code Review
2. Add _lockout_duration_ and _reduced_lockout_duration_ variables set
3. Deploy to sandpit with `./deploy-sandpit.sh -a`
4. Trigger lockout entering too many sms codes in account creation / mfa account recovery
5. verify time in _reduced_lockout_duration_ is used for lockout
=> AUT-2685: add ttl variable for lockout count and fix reduced lockout duration

ticf-cri-stub/build.gradle, ticf-cri-stub/src/main/java/uk/gov/di/authentication/ticf/cri/stub/lambda/TICFCRIStubHandler.java, ticf-cri-stub/src/main/java/uk/gov/di/authentication/ticf/cri/stub/lambda/entity/TICFCRIRequest.java, ticf-cri-stub/src/main/java/uk/gov/di/authentication/ticf/cri/stub/lambda/entity/TICFCRIStubResponse.java, ticf-cri-stub/src/test/java/uk/gov/di/authentication/ticf/cri/stub/lambda/TICFCRIStubHandlerTest.java
Created request and response classes for the TICF CRI Stub. Also added ability for the handler to to process requests, currently giving back a default response with logic to be implemented in future PRs.
1. Code Review
2. Check that the request and response bodies match those outlined in the following links respectively:
https://github.com/govuk-one-login/architecture/blob/main/rfc/0063-auth-ticf-risk-assessment-interface.md#authentication-risk-assessment
and 
https://github.com/govuk-one-login/architecture/blob/main/rfc/0063-auth-ticf-risk-assessment-interface.md#no-interventions-or-warnings-or-has-timed-out
=> AUT-2488: Create request & response for TICF CRI stub

template.yaml
Allow functions to deploy without VPC peering in build
=> ATO-534: temporarily disable snapstart

ci/stack-orchestration/manual-stacks/txma/template.yml, template.yaml
Add alarms based on the guidance from TxMA in their [onboarding documentation](https://govukverify.atlassian.net/wiki/spaces/TMA/pages/3603661028/2.+How+to+provision+the+infrastructure+on+your+end+and+understand+what+work+needs+to+happen+between+TxMA+and+your+team#Monitoring-and-Alerting)
- An alarm is triggered when there is at least one message in the audit queue for over 24 hours
- An alarm is triggered when there is at least one message in the dead letter queue at any time
Output the SlackEvents SNS topic ARN from the `{env}-orch-be-deploy` stack so it can be used in the `orchestration-{env}-txma` stack
The alarms are only provisioned in environments where TxMA ingest messages from the queue (staging, integration, and production).
The alarms have been tested in the dev environment …
=> ATO-520: Add CloudWatch alarms for TxMA failures

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
Refactors code relating to the verify mfa code handler audit events, as there is a good amount of repetition here that's ripe for a refactor. Removes noise from the code and the tests to aid readability.
1. Code Review commit by commit (tests and implementation refactoring done separately)
=> BAU: Refactor audit service code in verify mfa code handler

ci/terraform/oidc/build-overrides.tfvars
Update lockout and lockout count ttl in build.
To make it easier to test scenarios in build.  30s may be too quick to validate that a lockout has been applied.
A high lockout count ttl has been causing an issue with reauth tests in the pipeline, this needs to be fixed separately.
1.  Code review.  Check that the right values are being updated
=> BAU: Update lockout and lockout count ttl in build

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/dns.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/variables.tf
Add DNS for origin.oidc domain. This is needed for cloudfront
Ensure all resources feature flagged
=> ATO-511: Add DNS records for the origin oidc domain

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotificationType.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/NotificationService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/entity/NotificationTypeTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/NotificationServiceTest.java, ci/terraform/account-management/sqs.tf, ci/terraform/account-management/variables.tf, ci/terraform/oidc/sqs.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/NotificationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/NotificationType.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/TemplateAware.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/NotificationTypeTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/DeliveryReceiptsNotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/TemplateAware.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/NotificationTypeTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
cleanup of unused feature flag **isNotifyTemplatePerLanguage**. There are 2 commits. The first removes the dependency on the feature flag. The second is subsequent cleanup of language dependent template ids that we may or may not want to keep for additional language support in future.
Code Review
=> AUT-1709: cleanup isNotifyTemplatePerLanguage feature flag

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
After adding the new flow for the 2fa before password reset journey, we didn't have a place where we saved the internalPairwise id to a session. Thus, in VerifyCodeHandler.java and VerifyMfaCodeHandler.java we were auditing events without having a userId. This fixes it by adding it to the CheckUserExistsHandler, ensuring in the reset-password (and other journeys as well) we have the pairwiseId saved to the session
Cloudwatch log of pairwiseId being present in the resetPassword jouney:
1. Code Review
=> AUT-2679: add internalPairwiseId to the session

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java, ci/terraform/account-management/manually-delete-account.tf
This lambda is intended to me manually invoked from the AWS console, and provides a method to emit the correct audit events when actioning manual account deletions.
Pay particular attention to the error handling I think. We always want to know the IDs of the account being deleted.
The intended use of this is that it would be invoked manually from the console using the "test" functionality. The return value can then be copied into the account deletion ticket.
=> ATO-436: Add a lambda to manually delete accounts

ci/terraform/shared/site.tf, ci/terraform/shared/sns-cloudfront.tf
Create SNS topic to publish cloudfront alerts to
Must be in us-east-1 as this is where the metrics are emitted so where the alert will be
=> ATP-563: Create SNS topic to publish cloudfront alerts to

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
Add to use es256 in ec key pair generation instead of using system default.
Refactor the DocAppCriService test to use nesting
=> ATO-567/fix test not defaulting es256

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
Used a persistent session id that passed the regex checks in `PersistentIdHelper`
=> ATO-none: use correct persistent session id

ci/cloudfront-orchestration/tls-certificate/README.md, ci/cloudfront-orchestration/tls-certificate/deploy.sh, ci/cloudfront-orchestration/tls-certificate/dev/parameters.json, ci/cloudfront-orchestration/tls-certificate/dev/tags.json
Create a script to deploy the tls stack for cloudfront. Currently only configured for dev/sandpit, others will be added in a followup
=> ATO-541: scripts and configuration to deploy cloudfront tls stack

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationTokenService.java
Add logging for unsuccessful responses from Authentication token and userinfo endpoints
=> BAU: Add logging for unsuccessful responses from Authentication token and userinfo endpoints

ci/terraform/oidc/spot-sqs.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
We should move to identity policies for access to our queues. I have set up identity based access to the spot queue in the previous PR https://github.com/govuk-one-login/authentication-api/pull/4324 and this PR will start the rollout of removing the resource policies.
Check it's feature flagged, and the logic is the correct way around
=> ATO-554 Remove read permission from spot queue from resource policy 

ci/terraform/oidc/staging.tfvars
Set incorrect password lockout ttl to 2hrs in staging.
To test the value that will be used in live in staging.
1. Code review
#4337
=> AUT-2725: Incorrect password lockout ttl to 2hrs in staging

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/InvalidEncodingException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/AuditHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/AuditHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuditServiceTest.java
Add Txma-Audit-Encoded to audit event:
[example](https://govukverify.atlassian.net/wiki/spaces/DID/pages/4010017012/BE+TXMA+Audit+event+changes#A-worked-example-(needs-review))
=> ATO-529: Add TxMA header to Audit Event

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
We need to know if a user's mfa method is verified when we get the user exists response, because in the case of a password reset journey we want to ensure that the user is not prompted to enter their mfa code before password reset, since this will result in an error.
This property is currently unused on the frontend.
1. Code Review
=> Inc 760/add mfa verified to user exists

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java
contract test for DCMA user info 
Looked at error paths for userInfo Response
will need ATO-482 merged in first
=> Ato 483/dcmaw user info contract test

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
Pass txma-audit-encoded header in AuthenticationCallbackHandler, using attachTxmaAuditFieldFromHeaders()
=> ATO-524: Pass txma-audit-encoded header in AuthenticationCallbackHandler

ci/terraform/oidc/spot-response.tf
`SPOTResponseHandler` handles processing SPOT responses taken from an SQS queue. It does so in batches, and currently the handler is configured with a batch size of 10 (the Terraform default). However, the handler returns after processing the first item in the batch, which means responses may be lost. 
In order to prevent loss of responses, batch size is set to 1.
When load is increased, a batch size of 1 may create a bottleneck, in which case the handler can be modified to process larger batches of messages correctly. Care should be taken when increasing the batch size to ensure messages can be processed idempotently, as a failure in processing one message would cause the entire batch to be replayed.
1. Code review only
=> ATO-538: Reduce batch processing size of SPOT responses from 10 (default) to 1

ci/terraform/oidc/rsa-signing-key.tf, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf
One of the kms keys cross account access was behind the wrong feature flag, and there was also an unused feature flag in shared that has been removed
=> ATO-475: Tidying up use of cross account back channel logout feature flag

integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java
We were previously assuming in the mfa helper that a user had SMS mfa by default. This made sense at some point, since we were only using this method once a user had successfully logged in, so they must have had MFA. However, we're now returning this information from the check user exists endpoint, at which point a user might not have fully set up 2fa.
Basing the MFA method on whether a user has a verified phone number or not means that for users with no verified phone number, we return a none as a 2fa method. This fixes a bug in the password reset journey, where a user without a fully set up account cannot reset their password because they hit an error screen on the 2fa step. They were hitting this 2fa step since the backend was returning that they had SMS MFA setup, so we were routing …
=> INC-760 Do not return SMS mfa type if a phone number is not verified

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
Added new fields to audit events in line with TxMAs requirements. See ticket [AUT-2637](https://govukverify.atlassian.net/browse/AUT-2637) for details
1. Code Review
2. Check that audit events in handlers now have fields adder that are outlined in the ticket
[AUT-2637]: https://govukverify.atlassian.net/browse/AUT-2637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-2637: add new fields for audit events

ci/terraform/oidc/dns.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/variables.tf
Feature flag to toggle DNS record for OIDC between API gateway and Cloudfront. Tested in sandpit.
To review ensure that this will only affect sandpit right now.
=> ATO-517: Feature flag for Cloudfront DNS cutover

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/variables.tf
Once traffic is routed through cloudfront, all requests will be coming from a small pool of cloudfront IPs. It does not make sense to rate limit based on them. We are ratelimiting with a WAF at edge. This covers the origin for the transition to cloudfront.
I've set up deployment secrets in all environments for this
=> ATO-516: Bypass oidc origin rate limiting for requests containing cloudfront header

ci/terraform/oidc/authorizer-orch-frontend.tf
Shorten orch frontend authorizer lambda parameter names in order to not hit 140 character limit:
`InvalidParameterValueException: The function arn 'arn:aws:lambda:eu-west-2:761723964695:function:integration-orch-frontend-authorizer-lambda:integration-orch-frontend-authorizer-alias-lambda-active' exceeds the maximum length of 140 characters.`
=> ATO-430: Shorten orch frontend authorizer lambda parameter names 

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java
When an account intervention should not ignore the password reset flag, this is enforced by setting `passwordResetTime` to a small number. This works because `ignorePasswordReset` is `false` when the time that the intervention was applied is greater than or equal to `passwordResetTime` (comparison of unix timestamps).
Replace instances of `Long.MIN_VALUE` with `0L`, because it doesn't make sense to set `passwordResetTime` to a negative value, and it doesn't affect functionality.
Code review only
PR where `Long.MIN_VALUE` was introduced: https://github.com/govuk-one-login/authentication-api/pull/4108
=> ATO-440: Replace instances of `Long.MIN_VALUE` with `0L`

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
Pass txma-audit-encoded header in IPVCallbackHandler, using attachTxmaAuditFieldFromHeaders()
=> ATO-527: Pass txma-audit-encoded header in IPVCallbackHandler

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
Pass txma-audit-encoded header in docAppCallbackRequestHandler, using attachTxmaAuditFieldFromHeaders()
=> ATO-528: Pass txma-audit-encoded header in docAppCallbackRequestHandler

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
Add a check for the `clientID` in the AccessToken, to make sure that if it is `null` it throws an exception instead of querying the database with a null clientID and erroring.
https://gds.slack.com/archives/C02HCLREVV5/p1714570226681109
=> BAU: Add check for if clientID is null in the access token

ci/stack-orchestration/README.md, ci/stack-orchestration/configuration/dev/vpc/parameters.json, ci/terraform/auth-external-api/auth-ext-api-gateway.tf, ci/terraform/auth-external-api/sandpit.tfvars, ci/terraform/auth-external-api/variables.tf
Auth external api is a private api, so we need to add the orch vpc endpoint id to allow it access to call the api, but also with backwards compatibility
=> ATO-592: Add cross account access to the auth external api to orch in sandpit

template.yaml
Back channel logout lambda should not be in a vpc, because it requires open egress.
=> ATO-608: Move backchannel logout lambda out of VPC

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
This reverts commit 5a337ee8c0b0bdd0277c0b9eccc7b62636b6b60a.
This was introduced as a fix for an incident, but in the end we [didn't use this](https://github.com/govuk-one-login/authentication-frontend/blob/0af4c5ef7135bbf26f6c1edf71f865d707249657/src/components/enter-email/types.ts#L4-L8) (it would have needed a PR in authentication-frontend to use this response and there ended up being a simpler way) and fixed in a different way - see commit 19bcc8c35d48aa88942a4e0ceb4b18b91b50b446
Reverting this commit so as not to have additional unneeded code.
[PR](https://github.com/govuk-one-login/authentication-api/pull/4369) that contains the fix that we ended up using
=> Revert "INC-760: Add mfa method verified to Check User Exists response"

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LocaleHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelperTest.java
Refactors the request header helper to reuse common logic, and removes a method that checks whether a request contains a header, since it's always then proceeded by retrieving that header, so can be replaced with the new helper method.
=> Rff 3 request header helper

shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java
Changed componentId audit field assignment to have the value "AUTH".
Security require the component id field to be populated with a signifier that allows them to distinguish audit events from our service (or component) from audit events from other services. At least for the time being, "AUTH" has been chosen as an appropriate component id value.
Previously we were populating this field getting the env var OIDC_API_BASE_URL. This env var was not declared in our terraform and so was returning null anyway, but even if the correct value for OIDC_API_BASE_URL were returned, that would not be an appropriate componentId for auth as it is not our service uri.
1. Code Review
=> AUT-2640: Update audit event component id value to 'AUTH'

ci/terraform/account-management/api-gateway.tf, ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/api-gateway.tf
Auth-2737 change Waf log subscription default behaviour , ask from Security team DISEC-3686
<!-- Describe the steps required to review this PR.
For example:
1. Code Review
1. Deploy to sandpit with `./deploy-sandpit.sh -o -a -p
Look for three changes to WAF log Subscription Like below 
```
~ resource "aws_wafv2_web_acl_logging_configuration" "waf_logging_config_frontend_api" {
id                      = "arn:aws:wafv2:eu-west-2:761723964695:regional/webacl/sandpit-frontend-waf-web-acl/98d76397-08a0-4639-b5ca-4a678c144af7"
~ logging_filter {
~ default_behavior = "DROP" -> "KEEP"
}
}
```
=> Auth-2737 change waf log subscription default behaviour 

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/trustmarks.tf, ci/terraform/oidc/wellknown.tf
- Changing the endpoint-name causes the lambda to be deleted, which would cause downtime. We don't need this, just the path-part change
- Explicit depends on in the new resources because the existing module needs to update first to make the path available
- Explicit depends on in the gateway deployment because we want to ensure all gateway integrations have been finalised before deploying
=> ATO-564: Update lambda references to ensure zero downtime deployments

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/IpAddressHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/IpAddressHelperTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/IpAddressHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/IpAddressHelperTest.java
As part of setting common headers on all requests, we're going to start setting the forwarded for header from a common library instead of directly in our code, which uses lower casing. This commit allows case-insensitive retrieval of this header, to ensure that when we switch over our method of setting the method, we can still get the IP address from the header.
Depends on [refactor to request headers](https://github.com/govuk-one-login/authentication-api/pull/4406) - that needs merging first ✅
=> AUT-2578: Retrieve X-Forwarded-For header as ip regardless of case

ci/terraform/oidc/staging.tfvars
Create the `origin.oidc.staging.account.gov.uk` domain
=> ATO-618: Enable OIDC origin domain in staging

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java
Add facility to restrict audit metadata pairs.
Some information sent for audit needs to be restricted.
Apply this to the UPDATE_EMAIL event in account management.
1. Code Review
=> INCIDEN-763: Add facility to restrict audit metadata pairs

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/IpAddressHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/IpAddressHelperTest.java
Per https://github.com/govuk-one-login/architecture/blob/main/rfc/0072-assets-via-cloudfront.md#application-changes---client-ip-address, we need to change how we retrieve viewer IP address when we introduce cloudfront. Use the new header value preferentially.
This is based on #4414 as that introduces header case insensitivity to this helper
=> ATO-619: cloudfront viewer ip

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthRequestError.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
Mobile noticed that we do not include state in error responses from authorize made with JAR requests. This is not spec compliant. 
To review ensure no backwards incompatible changes have been made
=> ATO-624: Include State param in error response from JAR authorize request

ci/terraform/account-management/authorizer.tf, ci/terraform/modules/endpoint-module/lambda.tf, ci/terraform/modules/stub-endpoint-module/lambda.tf, ci/terraform/utils/email_check_results_writer_lambda.tf
Adding lifecycle ignore for provisioned_concurrent_executions
We are experiencing lambda throttling during lambda running in scaled   provisioned concurrent. while deployment in happing which is try to re provision  the provisioned concurrent from scaled 10 to 3 
Evidence below
=> Adding lifecycle ignore for provisioned_concurrent_executions

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
- Add user ID (`subjectId`), when it is available, to the `AUTH_LOG_OUT_SUCCESS` event
- Add RP pairwise ID, when it is available, to the `AUTH_LOG_OUT_SUCCESS` event
I'd like to spend some time in the near future refactoring the logout flows as they are quite convoluted.
1. Code review only, easiest commit by commit
=> ATO-585: Add information to the AUTH_LOG_OUT_SUCCESS audit event

ci/stack-orchestration/README.md, ci/stack-orchestration/configuration/dev/dev-orch-be-pipeline/parameters.json
Update the pipeline config so that we can access dynamo db's cross account - currently not permitted in permissions boundary
=> ATO-591: Implement access to auth dynamo db's in permission boundary 

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/contract/AccountInterventionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AccountInterventionsStubExtension.java
AIS may not send us all the fields under "intervention" in the response. This PR modifies the contract test to let AIS know we do not need these fields, and adds unit and integration tests to cover this situation.
=> ATO-627: Update AIS tests to cover case that fields are missing in AIS response

ci/stack-orchestration/configuration/dev/vpc/parameters.json
Turn on network firewall in dev. The suricata rules that we need are already included in the template by dev platform, but we need to provide a value for AllowedDomain or AllowRules for the network firewall to deploy. Documentation can be found [here](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3531735041/VPC)
=> ATO-610: Turn on network firewall in dev

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
Add journey ID to USER_INFO_RETURNED audit event
https://github.com/govuk-one-login/authentication-api/pull/4455 (adding journey ID to the access token store) to be merged first
=> ATO-595: Add journey id to USER_INFO_RETURNED audit event

build.gradle, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/shared.tf, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/PhoneNumberRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Update API to send message to SQS queue after sign up phone validation.
When the Experian Phone Checker service (owned by Experian) has an outage then checks against phone numbers fail and do not happen.  There is no failure or DLQ for the transactions, so we have no way of trying to run them again.  The service has failed a few times recently which generates alerts that we have to deal with, but we are unable to recover the transactions.
[AUT-2103](https://govukverify.atlassian.net/browse/AUT-2103)
[AUT-2103]: https://govukverify.atlassian.net/browse/AUT-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-2267: Update API to send message to SQS queue after sign up phone validation

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/VectorOfTrustTest.java
Reverts govuk-one-login/authentication-api#4350
Reverting this change as, due to broken acceptance tests, it cannot be tested in staging now. Will retry tomorrow
=> Revert "ATO-561: Enforce client registry permitted levels of confidence"

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java
Pass txma-audit-encoded header in ProcessingIdentityHandler, using attachTxmaAuditFieldFromHeaders()
=> ATO-526: Pass txma-audit-encoded header in ProcessingIdentityHandler

ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/security-groups.tf, ci/terraform/shared/variables.tf, template.yaml
Doc app callback needs to call out to dcmaw, so needs access to the internet through the firewall
=> ATO-611: Move doc app callback to protected subnet

build.gradle, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/shared.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/PhoneNumberRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Update API to send message to SQS queue after sign up phone validation.
When the Experian Phone Checker service (owned by Experian) has an outage then checks against phone numbers fail and do not happen.  There is no failure or DLQ for the transactions, so we have no way of trying to run them again.  The service has failed a few times recently which generates alerts that we have to deal with, but we are unable to recover the transactions.
[contra indicator PR](https://github.com/govuk-one-login/authentication-contra-indicators/pull/144)
[AUT-2103]: https://govukverify.atlassian.net/browse/AUT-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-2267: async Experian phone check is triggered after change of phone number

ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/check-email-fraud-block.tf, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/oidc/site.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckEmailFraudBlockRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckEmailFraudBlockResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckEmailFraudBlockIntegrationTest.java
- Create new `CheckEmailFraudBlock` handler that takes `email` as a request and returns a response containing the email check status
- The check status can either be `ALLOW`, `DENY`, `PENDING` 
- The email check status is stored in the `<env>-email-check-result` dynamodb table
- This lambda will be called during the Create Account journey
- Implement necessary Iac Terraform scripts to create CheckEmailFraud lambda
- Deployed and tested in `authdev1`
1. Code Review
=> AUT-2162: Part 1: Create Code for new endpoint CheckEmailFraudBlock

build.gradle, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/shared.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/PhoneNumberRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Update API to send message to SQS queue after sign up phone validation.
When the Experian Phone Checker service (owned by Experian) has an outage then checks against phone numbers fail and do not happen.  There is no failure or DLQ for the transactions, so we have no way of trying to run them again.  The service has failed a few times recently which generates alerts that we have to deal with, but we are unable to recover the transactions.
[contra indicator PR](https://github.com/govuk-one-login/authentication-contra-indicators/pull/144)
[AUT-2103]: https://govukverify.atlassian.net/browse/AUT-2103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-2367: async Experian phone check is triggered after change of phone number

template.yaml
Setup up subscription filter for token lambda logs as a test to pipe logs into splunk
setup for Build, integration, staging and production environments
=> ATO-324: setup subscription filter to pipe token logs to splunk

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/AuditHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/AuditHelperTest.java
Pick up the newly added CF encoded header in the account management api lambda handlers.  If present send to txma in each subsequent audit event submitted.
AuditHelper class was added. No information on validation however I expect there will be additional format rules that we should be adding in the future.
1. Code Review
=> AUT-2663: account management api consumes encoded txma audit header

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/NotificationServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java
We introduce `CommonTestVariables` in the `frontend-api` module to encapsulate frequently used test data like email, password, phone number.
This introduces an abstraction so that we can make future improvements such as randomly generated input data to prevent dependency on specific inputs, or specific test cases / personas for users.
This code is contained within the `frontend-api` module only.
=> RFF-4: Refactoring test data

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
In UpdateEmail lambda in the Account Management API, added a step check the status of the users fraudulent email check for the new email address that the user is proposing to update their profile to use and log the result.
Interim stage of email phone check process where we will log the status of the asynchronous request sent to Experian to get an idea of how long it takes
1. Code Review
=> AUT-2165: log the status of experian email check during update email process

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/entity/PendingEmailCheckRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultSqsMessage.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandlerTest.java
Add a Cloudwatch metric with a dimension of timeFromInitial request, which is the delta between TimeOfInitialRequest (as captured in the SQS message) and now().
The intent here is to be able to assess the length of time it has taken to get a result as a metric.
1. Code Review
=> AUT-2155: add cloudwatch metrics

ci/terraform/oidc/site.tf
Deploy reauth endpoint in integration.
The endpoint is not currently deployed.
1. Code Review
https://github.com/govuk-one-login/authentication-frontend/pull/1644
=> BAU: Deploy reauth endpoint in integration

ci/terraform/oidc/sandpit.tfvars, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/AuditHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/AuditHelperTest.java
- Enable TxmaEncodedHeader in sandpit
- Fix header naming
=> ATO-500: Enable txma encoded header

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/validators/TokenRequestValidator.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/validators/TokenRequestValidatorTest.java, ci/terraform/auth-external-api/token.tf, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
The URL of the private api gateway for the auth external api included the VPCE ID it is accessed through. That means when orch moves to a new AWS account, the audience in their client assertion changes. This change accepts either audience.
=> ATO-571: Accept a list of audiences in the auth external token endpoint

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
The StartHandler was attempting to retrieve the header from the user context.  For other lambdas the user context is created in the base class, BaseFrontendHandler, and the TxMA header added at that point.  The StartHandler does not extend BaseFrontendHandler and so does not benefit from its creation and population of the user context, instead it needs to retrieve the header itself.
Code review.
=> AUT-2264: Update StartHandler to correctly retrieve the TxMA header.

ci/terraform/oidc/api-gateway.tf
Add an origin WAF rule in count mode to count requests not coming via cloudfront.
This should give us the information we need to be confident in mandating cloudfront for requests.
=> ATO-650: Add a WAF rule to count origin requests via cloudfront

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
We should be sourcing the identifier from the ID token hint, not calculating it. Previously, we were also using the wrong identifier to look up the user profile.
=> ATO-585: fix rp pairwise ID in logout audit event

template.yaml
Add subscription filter for lambdas:
OpenIdConfiguration
Trustmark
BackChannelLogoutRequest
DocAppSubscription
JwksSubscription
=> ATO-324: subscription filter for lambda logs to splunk

ci/terraform/oidc/api-gateway.tf
Reverts govuk-one-login/authentication-api#4518
Missing observability config block
=> Revert "ATO-650: Add a WAF rule to count origin requests via cloudfront"

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/auth-code.tf, ci/terraform/oidc/backchannel-logout-request.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/userinfo.tf, ci/terraform/oidc/variables.tf, ci/terraform/shared/sandpit.tfvars, template.yaml
The remaining orchestration lambdas, and turn on orch lambdas in staging
=> Ato 656/merge remaining orch lambdas into staging

template.yaml
References were to the secret resource rather than the value of the secret
=> ATO-NONE: Fix spot response lambda secret references

template.yaml
SPOT is not in build, so we shouldn't deploy the lambda there
=> ATO-NONE: Do not deploy spot response lambda in build

.github/workflows/deploy-orch.yml, .gitignore
Use the caching built in to SAM build
Use the github actions cache to preserve the cache files between build. 
This should considerably speed up the deploy action for Orchestration
=> BAU: Cache output from AWS SAM

ci/terraform/oidc/build.tfvars
Enable identity in the build environment.
To facilitate testing of identity journeys in auth, where there are still identity specific pathways. Makes the build environment match production.
As there is no ipv stub in build it will not be possible to complete an identity journey back through orchestration, but it will still be possible to test the entire auth journey.
1. Code Review (identity is already switched on in the sandpits)
=> BAU: Enable identity in the build environment

ci/terraform/account-management/authdev1.tfvars, ci/terraform/account-management/authdev2.tfvars, ci/terraform/account-management/dev.tfvars, ci/terraform/account-management/staging-overrides.tfvars, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/dev-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/utils/build-overrides.tfvars, ci/terraform/utils/email_check_results_writer_lambda.tf, ci/terraform/utils/sandpit.tfvars, ci/terraform/utils/staging-overrides.tfvars, ci/terraform/utils/variables.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/EmailCheckResultWriterIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultSqsMessage.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandlerTest.java
As there is a one-to-one relationship between the authentication-check-experian dev environment and the authentication-api sandpit environment, no other API dev environment is supported as it confuses matters and breaks workflows when cross account communication occurs. This may be resolvable in the future, but for now we're disabling the integration for all but the sandpit development environment
Added `support_email_check_enabled` to the utils module so we only deploy the email writer result SQS event trigger in supported environments. Set those environments to sandpit, build and staging.
This is to avoid cross account confusion and user journey breakages when a user creates an account in sandpit, the risk assessment is received and the writer lambda in authdev* or dev writes to it's …
=> AUT-2779: Fix issues triggering EmailCheckResultWriterHandler

template.yaml
Remove reserved concurrency from lambdas
=> ATO-NONE: Remove reserved concurrency from orch lambdas

ci/terraform/auth-external-api/auth-ext-api-gateway.tf
Trigger auth external API redeployment when the VPCE list changes. This is required to propagate the change
=> ATO-656: Force redeploy of auth external API

ci/cloudfront-orchestration/cloudfront/README.md, ci/cloudfront-orchestration/cloudfront/deploy.sh, ci/cloudfront-orchestration/cloudfront/dev/parameters.json, ci/cloudfront-orchestration/cloudfront/staging/parameters.json, ci/cloudfront-orchestration/cloudfront/staging/tags.json, ci/cloudfront-orchestration/monitoring/staging/parameters.json, ci/cloudfront-orchestration/monitoring/staging/tags.json, ci/cloudfront-orchestration/tls-certificate/staging/parameters.json, ci/cloudfront-orchestration/tls-certificate/staging/tags.json, ci/cloudfront-orchestration/waf/staging/parameters.json, ci/cloudfront-orchestration/waf/staging/tags.json
Configuration details for cloudfront in staging. This has all been deployed already
=> Ato:618: Cloudfront configuration for staging

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
Switch the WAF on the OIDC API Gateway to the one provided by dev platform that just blocks everything without the secret header that cloudfront sets
=> ATO-518: Enforce cloudfront for OIDC in sandpit and staging

ci/terraform/oidc/api-gateway.tf
Do not read the WAF values where enforce cloudfront is not enabled. This will mean that the authdev environments keep working after this rolls out
=> ATO-518: Only read variable when enabled

.gitignore, ci/cloudfront-orchestration/waf/build/parameters.json, ci/cloudfront-orchestration/waf/build/tags.json, ci/terraform/oidc/build.tfvars
- Build settings for cloudfront WAF
- Enable origin.oidc.build.account.gov.uk
=> ATO-675: cloudfront build

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java
Some changes to orchestration-shared, but only to methods used in oidc-api; i.e., TokenService (in orchestration-shared) is only used in oidc-api
See all removal [here](https://github.com/govuk-one-login/authentication-api/pull/4080)
=> ATO-387: Remove consent from oidc-api

ci/cloudfront-orchestration/waf/integration/parameters.json, ci/cloudfront-orchestration/waf/integration/tags.json, ci/terraform/oidc/integration.tfvars
Just like https://github.com/govuk-one-login/authentication-api/pull/4594 but for integration. Doesn't affect anything until DNS cutover, just setting up prereqs
=> ATO-673: cloudfront integration prereqs

ci/cloudfront-orchestration/waf/production/parameters.json, ci/cloudfront-orchestration/waf/production/tags.json, ci/terraform/oidc/production.tfvars
Similar to https://github.com/govuk-one-login/authentication-api/pull/4594 but for production. Won't impact any traffic until DNS cutover tomorrow, just some prereqs
=> ATO-674: Cloudfront production prereqs

ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
Remove consent required from ipv-api module
=> ATO-387: Remove consent required (ipv-api)

.github/workflows/deploy-orch.yml
Reverts govuk-one-login/authentication-api#4497
From devplatform:
I can see that you merged in a dependabot PR yesterday to bump the devplatform-upload-action-3.9 . This was actually a pre-release for testing only. Looks like due to the lack of -beta tag dependabot picked it up. Its not breaking anything but when you get time could you please downgrade to the v3.8.1 version please? https://github.com/govuk-one-login/devplatform-upload-action/releases/tag/v3.8.1
We will be removing the 3.9 tag once you have moved onto v3.8.1
=> Revert "Bump govuk-one-login/devplatform-upload-action from 3.8 to 3.9"

account-management-api/docs/account-management-api.md
- Document the existing Account Management API along with the proposed 2 new API endpoints where one will retrieve the users MFA method and the other will allow the MFA method to be updated or changed. 
- Once the API endpoint to update the users MFA method is added, the update users phone number API endpoint can be removed 
- To clearly document what the Account Management API offers
- To document the proposed changes and adaptations to the Account Management API
=> AUT-1194 - Document Account Management API and include proposed changes

delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountRecoveryIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailAudienceLoaderScheduledEventHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailSenderScheduledEventHandlerIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ConfigurationServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
This PR removes unused methods from the `ConfigurationService` classes in the auth and orch codebases.
=> BAU: Remove unused configuration flags

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/dev/dev-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json
Need to allow cross account SQS access to access spot request queue in auth account
=> ATO-672: Allow for cross account access to SQS in permissions boundary

template.yaml
If the event mapping is not disabled, the lambda will pick up messages from the queue as soon as it's deployed
=> ATO-686: Disable spot response event mapping in int and prod

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ClientRegistryTest.java
- Map id token signing algorithm from RSA256 to RS256 in client registry table.
- Only allow RS256 value to be used in the client registry API.
Code Review
=> ATO-644: Fix RS256 vs RSA256 Issue

orchestration-shared/build.gradle, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/ConstructUriHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/ConstructUriHelperTest.java
Minor improvements to ConstructUriHelper:
- Able to contract a URI from an existing URI.
- Dedicated function to construct a URI with a query and no added path.
- Consistently returns URIs without trialing backslash.
- Able to chain calls to BuildURI (previously the first call would return a URI with a trailing slash and if the path being added in the subsequent call started with a slash then then returned URI would contain a double slash).
Code Review
=> BAU: ConstructUriHelper Improvement

ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json
This was set to the wrong account number
=> ATO-NONE: Fix auth account number for sqs permissions boundary

ci/terraform/ticf-cri-stub/build.tfvars, ci/terraform/ticf-cri-stub/dev.tfvars, ci/terraform/ticf-cri-stub/ticf-cri-stub-gateway.tf
We don't currently deploy the TICF CRI stub anywhere, but the intention is to update the pipeline so that we deploy it up to, but not beyond, build. This PR contains a couple of changes that were necessary to do this in the dev pipeline, and have been tested out there (and the stub lambda is successfully deployed there).
The changes were:
* Adding the relevant tfvars file
* Removing an incorrectly specified variable from the url defined in the terraform endpoint.
1. Code Review
2. Deploy this PR on the dev pipeline (which has had the pipeline change below applied to it) and see the "deploy TICF stub" stage pass successfully
This PR needs to be merged before the pipeline is updated - that pipeline update is [here](https://github.com/govuk-one-login/devplatform-deploy/pull/1867) (although …
=> AUT-2475: allow TICF CRI stub to be deployed by the pipelines

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
Add method to generate a signed storage access token. 
Authentication will send this storage token to IPV as a claim (named https://vocab.account.gov.uk/v1/storageAccessToken) in the JAR when identity re-verification is required. More details [here](https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/4188799112/Storage+access+token).
This is required as part of the MFA reset initiative.
1. Code review only
2. Confirm that sonarcloud analysis can be dismissed because:
- ConfigurationService tests are not required
- Code duplication is between authentication shared and orchestration shared which is expected
=> ATO-661: Add method to generate storage access token for Auth to send to IPV

template.yaml
Implement provisioned concurrency, and allow it to be configured per lambda if necessary. Note that cloudformation does not allow you to set it to zero, so had to do a bit of a hacky way around it! No settings for client config lambdas.
=> ATO-702: Implement provisioned concurrency

ci/terraform/oidc/build.tfvars
Mandate the use of CloudFront for the OIDC API in the build environment
=> ATO-675: Enable origin cloaking WAF build

template.yaml
As part of ff35f4d4e122980088593e269a465bf2ffa4dee8, the two policies were reversed
=> ATO-722: Correct backchannel queue policies

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java
AUT-2882: Add CHECK_BYPASSED audit event
- Apply BYPASSED block whenever the email checker status is still PENDING
- Event is triggered when updating email and registration for new account
1. Code Review
=> AUT-2882: Add EMAIL_FRAUD_CHECK_BYPASSED audit event

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java
This reverts commit a06985c4ed01c1c550a78b938cfd94818b064cc6.
This was failing acceptance tests in build due to the following error:
```java.lang.NullPointerException / Cannot invoke "java.util.Map.getOrDefault(Object, Object)" because the return value of "com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent$ProxyRequestContext.getAuthorizer()" is null```
, reverting while we investigate further.
=> Revert "AUT-2882: Add CHECK_BYPASSED audit event"

ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/kms-policies.tf, ci/terraform/oidc/mfa-reset-storage-token-jwk.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetStorageTokenJwkHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetStorageTokenJwkHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java, shared/src/test/java/uk/gov/di/authentication/shared/PackageSettings.java, shared/src/test/java/uk/gov/di/authentication/shared/services/JwksServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java, shared/src/test/resources/uk/gov/di/authentication/shared/services/approvals/TokenServiceTest.shouldGenerateWellFormedStorageTokenForMfaReset.approved.json
Create new well-known endpoint on auth frontend API for MFA reset storage token signing public key
After deploying to sandpit, key is available at https://auth.sandpit.account.gov.uk/.well-known/mfa-reset-jwk.json
Code review only
[ATO-661]: https://govukverify.atlassian.net/browse/ATO-661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATO-659: JWKS endpoint to publish MFA reset storage token public key

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
Switch on phone checks using SQS in all environments including production.
In effect this PR switches to SQS in build then production.  The changes have been running in integration since May 31.
Triggers a phone check in authentication-contra-indicators by putting a message on an SQS queue.
1. Code Review
#4608 
https://github.com/govuk-one-login/authentication-contra-indicators/pull/171
https://github.com/govuk-one-login/authentication-contra-indicators/pull/170
=> AUT-2814: Switch on phone checks using SQS in all environments including production

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, shared/src/main/java/uk/gov/di/audit/AuditContext.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java
Introduces a new way of calling the audit service, intended to limit the number of parameters we pass in and repeat in each handler, making handlers easier to read and making it easier to see, for each audit event, what the important information is.
The idea is to introduce an AuditContext object (see prior art/closed PRs [here](https://github.com/govuk-one-login/authentication-api/commit/c2b3169e191f997be84b7f67c0504e970493a20d), [here](https://github.com/govuk-one-login/authentication-api/pull/4292) and [here](https://github.com/govuk-one-login/authentication-api/pull/4434), reflecting multiple independent people thinking along the same lines) to capture the common things that are submitted on all audit events within a handler, and generally either don't change between audit events, or …
=> BAU: Refactor the audit service

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/ApiGatewayProxyRequestHelper.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
Refactors the MFA handler tests to reduce noise and make them more readable.
Includes extracting one common variable (IP address) to common variables, which I've then used in all handler tests where this is hard-coded, so contains a few more changed files than just this one, but should hopefully be OK to review commit by commit.
=> Bau: Refactor mfa tests

ci/terraform/oidc/reset-password-request.tf
Align OTP TTL with Count TTL where OTP TTL > Count TTL for  the Password Reset Check Email screen.
The ResetPasswordRequestHandler is the one that is generating and sending the Email OTP to the user. The default_otp_code expiry variable points out how long the email otp is available for. Because this variable was not included in the lambda environment variables, the otp was saved with the standard ttl value of 900.
1. Code Review
=> AUT-2879: Password Reset Align OTP TTL with Count TTL

ci/terraform/oidc/auth-code.tf, template.yaml
Set the OIDC BASE URL env var on the auth code handler. This is used to set the component ID on audit events, and it was raised that this was missing.
Check the value is set correctly, especially the template mapping
=> ATO-730: Fix missing component ID on events emitted from auth code handler

ci/terraform/oidc/build.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
Align OTP TTL with Count TTL.
As proposed in the description of [AUT-2816](https://govukverify.atlassian.net/browse/AUT-2816), when the count TTL is smaller than the OTP TTL, a user is able to send more than 5 attempts for one code. This PR is looking to fix that by introducing a new variable for the count TTL which is only used in the account creation journeys. 
For scenario 2, in build, the Default_Otp_Code_Expiry was not set in the tf file, making the ResetPasswordRequestHandler.tf use the standard 900 second value for the Otp Code Expiry. This would make the OTP TTL > Count TTL.
1. Code Review
[AUT-2816]: https://govukverify.atlassian.net/browse/AUT-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-2816: Align OTP TTL with Count TTL where OTP TTL > Count TTL

template.yaml
When an RP starts to share their signing key using a JWKS endpoint, Orchestration will need to retrieve and cache the key. This PRs adds a new DynamoDB table to store cached RP public keys. A key will be stored as a string in JWK format.
The table has a primary key schema with `clientId` as the partition key (HASH) and `keyId` as the sort key (RANGE).
A new KMS key is defined and used to encrypt the table.
TTL is enabled as keys will be fetched once per day.
=> ATO-688: Add DynamoDB table to cache RP public keys

template.yaml
_This PR fixes https://github.com/govuk-one-login/authentication-api/pull/4714 after it was reverted (https://github.com/govuk-one-login/authentication-api/pull/4740)_
When an RP starts to share their signing key using a JWKS endpoint, Orchestration will need to retrieve and cache the key. This PRs adds a new DynamoDB table to store cached RP public keys. A key will be stored as a string in JWK format.
The table has a primary key schema with `clientId` as the partition key (HASH) and `keyId` as the sort key (RANGE).
A new KMS key is defined and used to encrypt the table.
TTL is enabled as keys will be fetched once per day.
=> ATO-688: Add new DynamoDB table to store cached RP public keys

ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/update-email.tf, ci/terraform/oidc/check-email-fraud-block.tf, ci/terraform/oidc/send_notification.tf
Added SUPPORT_EMAIL_CHECK_ENABLED env var to lambdas. Lambdas were previously not having access to this environment variable, so email fraud check logic could never be executed.
1. Code Review
=> BAU: Added SUPPORT_EMAIL_CHECK_ENABLED env var to lambdas

ci/terraform/utils/email_check_results_writer_lambda.tf
If we reserve concurrency for Lambda other function cannot use it.
We have total full account concurrency of 3000, if this pool is used completely Lambda throttling will start causing errors.
See that `reserved_concurrent_executions` has been removed from the Terraform definition of the lambda.
Originally added in https://github.com/govuk-one-login/authentication-api/pull/4239
=> BAU: Remove `reserved_concurrent_executions` from `*-email-check-writer` lambda

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java
This commit ensures that the email fraud check result status is always populated with the default PENDING email check result status if a record for a given is not found in the email check store.
For example:
1. Code Review
=> BAU: Fix email fraud check result assignment

ci/terraform/shared/build-stub-clients.tfvars
Add new stub client for the acceptance test micro rp in build.
The micro rp has additional config for its own client that needs to be in place for it to run, and this needs a new client first.
1. Code Review
https://github.com/govuk-one-login/authentication-acceptance-tests/pull/328
=> BAU: Add new stub client for the acceptance test micro rp in build

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AccountInterventionsRequest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java
This will support the call to the ticf cri (which for now we will do from the account interventions handler, only in the case where the user is authenticated).
This field is currently unused - later work will implement logic based on this, so this is just to ensure that the frontend is making a compatible call to the backend.
1. Code Review
=> AUT-2908: Add optional authenticated parameter to account intervention request

ci/terraform/oidc/build.tfvars, ci/terraform/oidc/ecc-signing-key.tf, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/rsa-signing-key.tf, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/shared/build.tfvars, ci/terraform/shared/dev.tfvars, ci/terraform/shared/integration.tfvars, ci/terraform/shared/kms.tf, ci/terraform/shared/production.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf
Removing the feature flag for the auth orch split to all kms keys. I've done a tf plan against sandpit and can't see any changes
=> ATO-739: Remove kms cross account feature flag

ci/terraform/oidc/site.tf, ci/terraform/oidc/ticf-cri.tf, ci/terraform/oidc/variables.tf, ci/terraform/ticf-cri-stub/.terraform.lock.hcl, ci/terraform/ticf-cri-stub/sandpit.hcl, ci/terraform/ticf-cri-stub/versions.tf, scripts/dev_deploy_common.sh
Adds terraform to deploy the ticf handler in sandpit only.
A subsequent PR will deploy the handler in other environments.
Note that the permissions between the ticf handler and the ticf stub are not yet working, this will also be fixed subsequently, but getting this merged will allow for more parallel development.
1. Code Review
=> Aut 2851/deploy ticf handler

ci/cloudfront-orchestration/cloudfront/integration/parameters.json, ci/cloudfront-orchestration/cloudfront/production/parameters.json, ci/terraform/oidc/production.tfvars
Same as https://github.com/govuk-one-login/authentication-api/pull/4677 but for production. This changes the firewall on the API gateway to one which requires all traffic to have the secret header set by CloudFront.
I have:
- Checked all traffic is routed via CF: 
- Checked the WAF expects the correct values for the secret header
=> ATO-674: Enforce cloudfront in production

ci/stack-orchestration/configuration/dev/dev-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/dev/vpc/parameters.json, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/FetchJwksResponse.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/JwksResponse.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/JwksService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationServiceTest.java, template.yaml
We want to be able to fetch RP public keys from a JWKS endpoint that RPs own and publish, but lambdas in our existing VPC cannot call a public URL. The solution is to create a new lambda, outside our VPC, which can call public URLs. 
The new lambda (FetchJwksFunction) accepts two parameters, `keyId` and `url`, and returns a response object which will contain either a `JWK` or `ErrorObject` object. It will be directly invoked by AuthorisationHandler (implementation in a subsequent PR).
To allow communication between AuthorisationHandler (in our VPC) and FetchJwksHandler, a lambda VPC endpoint has been configured. As we use secure pipelines we don’t provision the VPC in our own template file - instead a parameter (LambdaApiEnabled) has been set in stack-orchestration VPC parameters. Note …
=> ATO-689: Create lambda to fetch RP JWKS

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/NowHelper.java
Previously, the timestamp was formatted 'yyyy-MM-dd'T'HH:mm:ss.SSSSSS'. This commit changes the format to unix timestamp, as is required by TxMA.
1. Code Review
=> AUT-2775: Fixed check email bypassed timestamp format.

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/dev.tfvars
This env variable is currently not set in authdev environments, so it may cause issues when the cross account flags are removed
=> ATO-738: Add orch account ids to dev environments

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
We were missing the "/auth" part from the URI, which was manifesting in 403 errors from the api gateway in sandpit.
This fixes this path, and also switches a config variable to being a string to stop unnecessary conversions.
1. Code Review
=> Aut 2851: Update ticf uri

scripts/dev_deploy_common.sh
This isn't fully set up in the auth dev environments yet so switching this off stops people having problems in testing envs. We can switch it back on when these are fixed
1. Code Review
=> BAU: Don't deploy the ticf stub by default

ci/terraform/oidc/site.tf, ci/terraform/ticf-cri-stub/authdev1.hcl, ci/terraform/ticf-cri-stub/authdev1.tfvars, ci/terraform/ticf-cri-stub/authdev2.hcl, ci/terraform/ticf-cri-stub/authdev2.tfvars, scripts/dev_deploy_common.sh
Deploys the ticf lambda to all environments, now the relevant variables have been set in aws.
Also ensures that the stub is deployed to the authdev environments, meaning we can test in these lower environments.
I have tested this in all test environments.
1. Code Review
1. If you like, you can deploy to one of the test envs, and test the ticf cri handler manually in the console (ping me and I'll walk you through it). Not vital though since I've tested in these envs already.
=> Aut 2851/deploy ticf to other envs

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
Uses our updated audit service method, using an audit context to share some common variables, in two more handlers.
Also refactors some of the audit service code in these handlers (construction of metadata pairs) to further tidy calls to the audit service up.
An [example PR](https://github.com/govuk-one-login/authentication-api/pull/4766) where we previously converted another handler
=> Bau: Use new audit service method in mfa handlers

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
When on the `ACCOUNT_MANAGEMENT` journey to update the user email, we have a user profile and should add the id to `PendingEmailCheckRequest`.
The current way of finding the userId in `SendOtpNotificationHandler` looks up the profile from the email address we are sending the OTP too.
This has an issue because the user does not have that email yet. Instead, this commit looks up the userId from the authorizer principleId.
This is used in the same file to tie the SEND_OTP audit event to the same user.
1. Code Review
- https://github.com/govuk-one-login/authentication-api/pull/4665
=> AUT-2775: Correct method to get userId for PendingEmailCheckRequest

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java
- returns storage token in claims request
- update test to assert claims
- add test to look at storage claim being passed through with test on flag
if storage token claim is being tested correctly
To thoroughly test will need to see if claim appears in IPV request in staging. Check with IPV for decrypted payload to see if storage token claim is there. Shouldn't have a need to pause to production as the storage token code exists there already.
=> ATO-726: fix storage token claim and update test

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
Previously it was possible for numbers to be sent to the email checker during registration. This stops that from happening by ensuring it's only emails that are checked during registration.
1. Code Review
https://github.com/govuk-one-login/authentication-api/pull/3912
=> AUT-2150: Ensure email request during registration only occurs for email notifications

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
Another PR to convert handlers to use the new way of calling the audit service. I had ambitions for this to be the final PR for frontend handlers but not quite there and didn't want to make this PR too big.
This simplifies call sites and tests by introducing a shared audit context object with common variables used across all events in a handler.
A previous PR where we've done this for some other handlers: https://github.com/govuk-one-login/authentication-api/pull/4794
=> Bau: Convert more handlers to use the new audit service method

ci/terraform/oidc/site.tf
A preparatory step for integrating with the ticf cri service in staging. These calls won't be being made yet as part of any journeys, but this will allow us to test manually in staging
1. Code review
PR where we deployed to all the test environments: https://github.com/govuk-one-login/authentication-api/pull/4809
=> AUT-2495: Deploy ticf handler in staging

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
PR to convert the last of the frontend lambdas to use our new method of submitting an audit event, using shared audit context.
This is a step towards retiring the old way - we still need to convert the code in other modules.
A [PR](https://github.com/govuk-one-login/authentication-api/pull/4817) where we did this for lots of other handlers
=> Bau: Convert last frontend lambdas audit calls
