govuk-one-login/authentication-api

ci/terraform/oidc/build.tfvars
ci/terraform/oidc/ecc-signing-key.tf
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf

Add orch account ids to variables, and added cross account access for storage token kms key

ATO-473: add orch account ids & cross account kms access

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

cleanup of unused feature flag ** isResetPasswordConfirmationSmsEnabled**
Code Review

AUT-1709: cleanup isResetPasswordConfirmationSmsEnabled feature flag

---

ci/terraform/oidc/site.tf

Deploy reauth endpoint in staging
1. Code Review

AUT-2115: Deploy reauth endpoint in staging

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/contract/AccountInterventionServiceTest.java

Modify AIS contract tests after sharing pact file with Bravo and receiving their feedback.
- Remove empty body from error pact. AIS actually send an error message in the body, but as Orchestration don't do anything with this, we can ignore it.
1. Code review
2. Check all tests pass locally
PR where contract tests were introduced: https://github.com/govuk-one-login/authentication-api/pull/4131

ATO-481: Make modifications to Account Interventions contract tests

---

ci/terraform/oidc/logout-sqs.tf

Setup kms key for back channel logout queue

ATO-475: Set up CMK key for back channel logout queue

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java

This is the PR from our first Refactoring Friday, taking a look at the `NotificationHandler` in Auth's codebase
Code review commit by commit

RFF-1: Notification Handler

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java

BAU: Refactor check user exists tests

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java

This will enable SPOT failures to be caught by our general alerting

ATO-508: Log at ERROR level on error response from SPOT

---

ci/terraform/oidc/ecc-signing-key.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf

ATO-473: Feature flag cross account kms access for storage token

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java

Adds various metrics to allow us to get better visibility of what is happening within the account interventions service.
1. Code Review

Aut 2688/add ais metrics

---

ci/terraform/oidc/logout-sqs.tf
ci/terraform/oidc/rsa-signing-key.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf

Set up cross account access for orch to back channel logout queue

ATO-475: Set up back channel logout SQS cross account access

---

.github/PULL_REQUEST_TEMPLATE.md

Created a single checklist of pre-submission items (including the orch/auth split item) and added one to ensure changes are reviewed by UCD if necessary.
Read the PR template and check the changes make sense.
[Same work in frontend repo](https://github.com/govuk-one-login/authentication-frontend/pull/1545)

Chore: Add to PR template to ensure UCD review performed as needed

---

ci/terraform/oidc/ecc-signing-key.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf
template.yaml

Set up the back channel logout lambda in orch account

ATO-514: Set up orch back channel request lambda

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/doc-app-alerts.tf
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/shared.tf
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/oidc/wellknown.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
template.yaml

Configure the doc app callback lambda for cross account access

ATO-514: Set up doc app callback lambda for cross account access

---

ci/terraform/oidc/staging.tfvars
ci/terraform/shared/staging.tfvars
template.yaml

Enable feature flags in staging for ITHC

ATO-534: Enable delegation to orchestration account in staging for ITHC

---

ci/terraform/oidc/staging.tfvars

Update staging orch doc app callback function name to correct value. This replaces the placeholder used while the function was deploying.

ATO-532: Staging orch function name

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

cleanup of unused feature flag ** doc_app_use_cri_data_v2_endpoint**
Code Review

AUT-1709: cleanup doc_app_use_cri_data_v2_endpoint feature flag

---

ci/terraform/shared/kms.tf

Correct feature flag. Key unused where flag disabled.

ATO-532: Update docapp key policy

---

ci/stack-orchestration/configuration/build/vpc/parameters.json
template.yaml

Undoes changes made in d7161c44016d7413960417c399d325425be1b9e6

ATO-532: Re-enable Orch VPC

---

README.md

Add information on setting up pre-commit hook to readme

ATO-NONE: Add pre-commit setup to readme

---

.github/workflows/sonar-analysis-on-merge.yml

Rename step in sonar analysis on merge, as it was inaccurate

ATO-NONE: Rename Run Unit Tests to Run Tests in sonar analysis on merge

---

ci/terraform/oidc/userinfo.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

Remove usage of SUPPORT_AUTH_ORCH_SPLIT in UserInfoHandler

ATO-411: Remove Usage SUPPORT_AUTH_ORCH_SPLIT - UserInfo

---

ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
integration-tests/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

cleanup of unused feature flag ** account_recovery_block_enabled**
Code Review

AUT-1709: cleanup account_recovery_block_enabled feature flag

---

ci/terraform/oidc/authdev1.tfvars
ci/terraform/oidc/authdev2.tfvars
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/start.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/Features.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

cleanup of unused feature flag ** extended_feature_flags_enabled**
Code Review

AUT-1709: cleanup extended_feature_flags_enabled feature flag

---

ci/terraform/account-management/staging-overrides.tfvars

Adding provisioned Concurrency Same as Prod to Staging authorizer lambda like a Like environment for perf test

adding provisioned Concurrency Same as Prod to Staging authorizer lambda

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java

Refactors tests for readability by:
* Introducing helper methods to remove noise
* Removing assertions that were unecessary
* Removing tests that were unnecessary (and adding some that were)
There's some more fertile ground to make these tests more readable (more assertions that can be removed, more noisy setup that can be extracted) but this is a good start.

BAU: Refactored LoginHandlerTest and added new test

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java

Added metadata pairs for requested audit events.

Aut 2639/audit events part5

---

ci/terraform/ticf-cri-stub/dynamodb.tf
ci/terraform/ticf-cri-stub/lambda.tf
ci/terraform/ticf-cri-stub/s3-objects.tf
ci/terraform/ticf-cri-stub/shared.tf
ci/terraform/ticf-cri-stub/site.tf
ci/terraform/ticf-cri-stub/ticf-cri-stub-gateway.tf
ci/terraform/ticf-cri-stub/variables.tf

- Create API Gateway for TICF-CRI Stub
- Create Lambda modul ticf-cri-stub
- Create required policies and attach it to the lambda
- Deployed in Sandpit
1. Code Review

AUT-2472: Create new stub terraform module with a new API gateway

---

ci/terraform/oidc/staging.tfvars

set 2hr lockout durations in staging

BAU: set 2hr lockout durations in staging

---

ci/stack-orchestration/README.md

Add information to orchestration README about manually managed SSM parameters

ATO-555: Add information to orch README about manually managed SSM parameters

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/spot-sqs.tf

Create read policy to add to lambda for spot queue

ATO-554: Create read policy for SPoT queue

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePasswordIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSessionIdHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSessionIdHelperTest.java

Updating email and password audit events

AUT-2636 Updating Update Email/Passwords events

---

ci/terraform/account-management/.terraform.lock.hcl
ci/terraform/account-management/dynamo-policies.tf
ci/terraform/account-management/shared.tf
ci/terraform/auth-external-api/.terraform.lock.hcl
ci/terraform/auth-external-api/dynamo-policies.tf
ci/terraform/auth-external-api/shared.tf
ci/terraform/delivery-receipts/.terraform.lock.hcl
ci/terraform/delivery-receipts/delivery-receipts-dynamo-access.tf
ci/terraform/delivery-receipts/shared.tf
ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/variables.tf
ci/terraform/test-services/.terraform.lock.hcl
ci/terraform/test-services/dynamo-policies.tf
ci/terraform/test-services/shared.tf
ci/terraform/utils/.terraform.lock.hcl
ci/terraform/utils/account_metrics_lambda.tf
ci/terraform/utils/bulk_test_user_create_dynamo_access.tf
ci/terraform/utils/bulk_test_user_delete_dynamo_access.tf
ci/terraform/utils/bulk_user_email_audience_loader_dynamo_access.tf
ci/terraform/utils/bulk_user_email_send_dynamo_access.tf
ci/terraform/utils/shared.tf

Add cmk permissions to iam policy, and feature flagged cross account access policies

ATO-544: User profile CMK permissions and cross account access

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java

Add new fields in the SEND_OTP audit event due to new HRMC requirements 
Code review the changed files

Aut 2635/audit events part1

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/trustmarks.tf
ci/terraform/oidc/variables.tf
template.yaml

Create trustmark lambda and feature flag the redirection

ATO-564: Create trustmark lambda

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/variables.tf

Added policies etc to allow for cross-account access to the identity credentials table

ATO-546: Allow cross-account access for identity credentials table

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java

Add new metadapair for ACCOUNT_TEMPORARILY_LOCKED due to new HMRC requirements
Code review

Aut 2635/audit events lockout

---

ci/terraform/shared/kms.tf

Add feature flag policy to allow cross account access to `IPV_Token' KMS signing key

ATO-553 Cross account IPV token signing key

---

ci/terraform/shared/kms.tf

Add feature flag policy to allow cross account access to `Orchestration_to_auth' KMS signing key

ATO-552 Cross account Orch to Auth signing key

---

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java

ATO-none: update user info pact test description

---

ci/terraform/oidc/build.tfvars

Shorter lockout required in build for automated tests
1. Code Review

Shorter lockout required in build for automated tests

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/build.tfvars

cleanup of lockout config as present in both build and build override files
1. Code Review

BAU: cleanup lockout and ttl config for build

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/VerifyCodeRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java

Refactored the VerifyCodeHandler to remove noise and make it more readable. Also refactored the VerifyCodeRequest class to be a record.
1. Code Review, going through commits one at a time

BAU: Refactored VerifyCodeHandler

---

.github/workflows/contract-tests.yml

Change the job to run on push to `main` rather than `merge_group` so that the contracts run against main/have the correct branch tag

BAU: Upload to pact broker from main

---

.github/workflows/contract-tests.yml

BAU: Fix uploading contracts to broker from main

---

ci/cloudfront-orchestration/cloudfront/README.md
ci/cloudfront-orchestration/cloudfront/deploy.sh
ci/cloudfront-orchestration/cloudfront/dev/parameters.json
ci/cloudfront-orchestration/cloudfront/dev/tags.json

Cloudformation to create a Cloudfront distribution for the OIDC domain

ATO-512: Create Cloudfront distribution for oidc domain

---

.github/workflows/contract-tests.yml

BAU: Fix consumer app version to use default

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java

Pass txma-audit-encoded header in logoutRequestHandler, using attachTxmaAuditFieldFromHeaders()

ATO-525: Pass txma-audit-encoded header in logoutRequestHandler

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

integration + production terraform config for 2hr lockout go live
1. Code Review

AUT-2461: increase lockout duration in integration and prod

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Amend tests to pimprove test coverage of handlers post Auth/Orch Split
Code Review

ATO-490: Improve Test Coverage In Handlers

---

.github/workflows/build-deploy-dev.yml

Adding manual workflow for DEV deployment

Adding manual workflow for DEV deployment

---

ci/cloudfront-orchestration/cloudfront/deploy.sh
ci/cloudfront-orchestration/monitoring/README.md
ci/cloudfront-orchestration/monitoring/deploy.sh
ci/cloudfront-orchestration/monitoring/dev/parameters.json
ci/cloudfront-orchestration/monitoring/dev/tags.json
ci/cloudfront-orchestration/tls-certificate/deploy.sh
ci/cloudfront-orchestration/waf/deploy.sh
ci/terraform/shared/sns-cloudfront.tf

- Deploy a cloudwatch monitoring stack
- Fix other cloudwatch deployment scripts
- Deploy cloudwatch alerts topic to correct region

ATO-526: cloudwatch monitoring

---

ci/terraform/shared/sns-cloudfront.tf

I had previously created this topic with the wrong provider (for eu-west-2 instead of us-east-1). Trying to fix this by adding the provider does not work, as the value in state is for eu-west-2, which cannot be read using the new provider. 
To fix this, we'll first remove the resources entirely (this PR), then create again (to follow)

ATO-562: Remove SNS alerts topic

---

ci/cloudfront-orchestration/cloudfront/dev/parameters.json

This has been changed by devplatform

ATO-512: Update cloudfront param name

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java

Remove capitalisation of audit metadata pair name
1. Code Review
#4436

INCIDEN-763: Remove capitalisation of audit metadata pair name

---

ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars

Perform the DNS cutover for the OIDC domain in staging from API gateway to Cloudfront

ATO-618: Perform DNS cutover for OIDC in staging

---

template.yaml

BAU: Fix DocApp AccountId typo

---

ci/terraform/shared/sandpit.tfvars

Add doc-checking-app scope to dev tfvars, this is needed to test doc-app journey

BAU: Add doc-checking-app scope to tfvars

---

ci/terraform/shared/dynamodb.tf

Turned on encryption with the new CMK
https://github.com/govuk-one-login/authentication-api/pull/4307

ATO-546: Cross account access identity credentials CMK encryption

---

template.yaml

Back channel logout function name was in the wrong place

BAU: Fix back channel logout function name location

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/token.tf
ci/terraform/oidc/variables.tf
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoService.java
template.yaml

Set up token lambda in orchestration

ATO-573: Create orch token lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/VectorOfTrustTest.java

Reverts govuk-one-login/authentication-api#4484

Revert "Revert "ATO-561: Enforce client registry permitted levels of confidence""

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ClientRegistryTest.java

Add P0 to requestable list of LoCs if clientLoCs are not specified and identity is required

ATO-561: Add P0 to default list of LoCs if IdentityVerificationSupported

---

template.yaml

Make the cloudformation template for orch more organised by adding regions for each lambda

BAU: Add regions to cloudformation template

---

ci/terraform/oidc/staging.tfvars

BAU: Disable orch docappcallback in staging

---

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json

Apply https://github.com/govuk-one-login/authentication-api/pull/4396 to the build and staging environments

ATO-591: Update permissions boundary in build and staging

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
template.yaml

Create Cross account JWKS lambda
Turn flag on in sandpit
Add to apigateway integration

Ato 566/create jwks lambda

---

template.yaml

BAU: Fix auth sandpit apiId

---

ci/terraform/shared/sandpit.tfvars

BAU: Add client registry cross account permissions

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
template.yaml

- Add dynamoDB prefix to Client Service
- Add HTTPS egress security group

ATO-570: Create Authorisation lambda

---

ci/terraform/oidc/build.tfvars

Enable phone checker with retry in build for testing
1. Code Review

AUT-2814: enable phone checker with retry in build

---

template.yaml

Adding missing txma permissions

ATO-NONE: Add permissions to txma queue to all lambdas that require it

---

template.yaml

Add missing user profile index permissions

ATO-NONE: Add permissions to user profile indices

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java

Reverts govuk-one-login/authentication-api#4481

Revert "AUT-2165: log the status of experian email check during update email process"

---

template.yaml

Add accounts interventions uri secret for ipv callback lambda. Deployment of lambda will fail if this secret is not already populated

ATO-577: Add account interventions uri secret

---

template.yaml

Add spot response queue secrets before spot response lambda

ATO-578: Add spot response queue secrets

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java

Add extra tests for client permitted LoC

ATO-561: Extra tests for client LoC enforcement

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
template.yaml

Create logout lambda in auth, and create back channel logout queue that is hooked up to new flow

ATO-575: Create logout lambda

---

ci/stack-orchestration/configuration/staging/vpc/parameters.json

Create vpc endpoint to allow calls to private api gateways

ATO-656: Turn on execute api gateway in staging

---

ci/terraform/oidc/staging.tfvars
ci/terraform/shared/staging.tfvars

Turn on cross account access to orch in staging

ATO-656: Turn on cross account access in staging

---

ci/terraform/auth-external-api/staging.tfvars

Add orch vpc endpoint id to auth external api, so that we can call private api from orch account

ATO-656: Add orch vpc endpoint id to auth external api

---

ci/terraform/shared/staging.tfvars

Add protected subnet cidr blocks to staging to allow redis connection to auth account

ATO-656: Add protected subnet cidr blocks to staging

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf
template.yaml

ATO-577: Create ipv callback lambda

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/staging.tfvars
template.yaml

Added Client Registration Handler
Code Review

ATO-580: Added Client Registration Lambda

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/entity/PendingEmailCheckRequest.java

Support distinction of performance tester users from other users for email address checking
1. Code Review

AUT-2786: add boolean to PendingEmailCheckRequest for testUsers

---

template.yaml

Fix Cloudformation import name

ATO-656: Fix Cloudformation import name

---

template.yaml

Reverts govuk-one-login/authentication-api#4562

Revert "ATO-656: Fix Cloudformation import name"

---

template.yaml

Fix hardcoded account ids to account id reference

ATO-NONE: Fix hardcoded account ids

---

template.yaml

Add permission for authorize lambda to get ipv capacity parameter

ATO-NONE: Add permission for authorize lambda to get ipv capacity param

---

template.yaml

Some lambdas were missing permissions to push to the audit queue

ATO-656: Add all missing txma permissions to orch lambdas

---

ci/terraform/oidc/api-gateway.tf

WAF rule to count requests which have not come via CloudFront
https://github.com/govuk-one-login/authentication-api/pull/4551
https://github.com/govuk-one-login/authentication-api/pull/4518

ATO-650: Count not-cloudfront requests

---

ci/terraform/interventions-api-stub/.terraform.lock.hcl
ci/terraform/interventions-api-stub/interventions-api-stub-gateway.tf
ci/terraform/interventions-api-stub/sandpit.tfvars
ci/terraform/interventions-api-stub/variables.tf

Configure the AIS stub to accept requests from orchestration vpce

ATO-571: Configure the AIS stub to accept requests from orchestration

---

template.yaml

ATO-656: Correct IPV auth url

---

template.yaml

Looks like a mistake was made in copying these

ATO-656: Correct environment variables for docapp

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java

See all removal [here](https://github.com/govuk-one-login/authentication-api/pull/4080)

ATO-387: Remove consent from client-registry-api

---

ci/terraform/oidc/integration.tfvars

Integration DNS cutover for Cloudfront

ATO-673: Integration DNS cutover

---

ci/terraform/oidc/production.tfvars

Production DNS cutover for Cloudfront

ATO-674: Production DNS cutover

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java

Populate missing fields ipAddress and persistentSessionId for DELETE_ACCOUNT event
1. Code Review

AUT-2849: Populate missing fields for AUTH_DELETE_ACCOUNT event 

---

template.yaml

Alias was referencing wrong account

BAU: Fix doc app callback env variables

---

ci/terraform/oidc/build.tfvars
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/staging.tfvars

send message to sqs to trigger experian phone check enabled in staging and integration for testing/monitoring

AUT-2814: enable sqs experian phone checker functionality in staging and integration

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthoriseAccessTokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/contract/ClientRegistryProviderTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java

Slight overlap with shared
See all removal [here](https://github.com/govuk-one-login/authentication-api/pull/4080)

ATO-387: Remove consent from integration-tests

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/domain/OidcAuditableEvent.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/TokenGeneratorHelper.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java

Add journeyId to the auditUser if present
Check that:
- If there is an IdToken present, the journeyId is taken from there
- If no IdToken, take the journeyId from the cookies
- If there is no journeyId in the cookies, return a null journeyId

ATO-655: Add journeyid mapping

---

ci/stack-orchestration/configuration/build/vpc/parameters.json

Add vpc endpoint interface in build orch account

ATO-NONE: Add vpc endpoint interface in build

---

template.yaml

Some filters had the word 'logout' in them which was copied from another lambda. Remove these

ATO-679: Remove extra logout's from error metric filter names

---

template.yaml

Some lambdas were missing subscription filters

ATO-681: Add missing subscription filters to pipe to splunk

---

ci/cloudfront-orchestration/cloudfront/integration/parameters.json
ci/cloudfront-orchestration/cloudfront/integration/tags.json
ci/cloudfront-orchestration/monitoring/integration/parameters.json
ci/cloudfront-orchestration/monitoring/integration/tags.json
ci/cloudfront-orchestration/tls-certificate/integration/parameters.json
ci/cloudfront-orchestration/tls-certificate/integration/tags.json

This was the configuration applied in int for cloudformation

ATO-673: cloudfront config integration

---

ci/cloudfront-orchestration/cloudfront/build/parameters.json
ci/cloudfront-orchestration/cloudfront/build/tags.json
ci/cloudfront-orchestration/monitoring/build/parameters.json
ci/cloudfront-orchestration/monitoring/build/tags.json
ci/cloudfront-orchestration/tls-certificate/README.md
ci/cloudfront-orchestration/tls-certificate/build/parameters.json
ci/cloudfront-orchestration/tls-certificate/build/tags.json
ci/terraform/oidc/build.tfvars

This was the configuration applied in build for cloudfront

ATO-675: cloudfront config build

---

ci/cloudfront-orchestration/cloudfront/production/parameters.json
ci/cloudfront-orchestration/cloudfront/production/tags.json
ci/cloudfront-orchestration/monitoring/production/parameters.json
ci/cloudfront-orchestration/monitoring/production/tags.json
ci/cloudfront-orchestration/tls-certificate/production/parameters.json
ci/cloudfront-orchestration/tls-certificate/production/tags.json
ci/cloudfront-orchestration/waf/deploy.sh
ci/cloudfront-orchestration/waf/template.yaml

These are the changes that were applied in production this morning as part of the go-live

Ato-674: Cloudfront config production

---

ci/stack-orchestration/configuration/staging/vpc/parameters.json

Turn on network firewall in staging

ATO-656: Turn on network firewall in staging

---

ci/terraform/oidc/authentication-callback.tf
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/processing-identity.tf
ci/terraform/oidc/production.tfvars
template.yaml

Enable the TXMA fraud header in all environments

ATO-499: Enable fraud header everywhere

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationResponse.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/contract/ClientRegistryProviderTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java

Exposing IdTokenSigningAlgorithm Client Registry API
Code Review

ATO-644: Expose IdTokenSigningAlgorithm In Client Registry API

---

ci/terraform/shared/authdev1.tfvars
ci/terraform/shared/authdev2.tfvars
ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/production-stub-clients.tfvars
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/staging-stub-clients.tfvars
ci/terraform/shared/stub-rp-clients.tf
ci/terraform/shared/variables.tf

See all removal [here](https://github.com/govuk-one-login/authentication-api/pull/4080)

ATO-387: Remove consent from terraform

---

ci/terraform/oidc/backchannel-logout-request.tf
ci/terraform/oidc/logout-sqs.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf

These flags aren't necessary, as back channel logout queue is now in the new account

ATO-685: Remove back channel logout flags

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/storage-token-jwk.tf
ci/terraform/oidc/variables.tf
template.yaml

ATO-684: Create storage token lambda in orch account

---

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json

Commit config for testing in the pipeline. This config has already been applied

ATO-700: Configure pipeline to run acceptance tests

---

template.yaml

ATO-580: fix api gateway arn for client registration function

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java

Add audit encoded header into mfa code processor

Aut-2848: Add audit encoded header into mfa code processor

---

template.yaml

Some lambdas were missing regions or region ends

BAU: Add regions for all lambdas

---

ci/terraform/interventions-api-stub/interventions-api-stub-gateway.tf

Correctly set the Orch VPCE in the interventions stub. Tested in sandpit

ATO-7: Fix the interventions stub for Orch

---

ci/terraform/oidc/ecc-signing-key.tf

Create kms signing key for MFA reset

ATO-658: Create kms signing key

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/entity/PendingEmailCheckRequest.java

- Required for audit event processing when AUTH_EMAIL_FRAUD_CHECK_COMPLETED is triggered
1. Code Review

AUT-2883: Add user id to Pending Email Check request

---

template.yaml

Apply KMS encryption to all lambda variables (tested in dev)

ATO-699: Apply KMS key to all lambdas

---

template.yaml

Set the default for orch lambda log retention to 30 days

ATO-none: update the log retention for orch lambdas to 30 days

---

.github/workflows/checkov.yml
.pre-commit-config.yaml
checkov-policies/log-retention.yaml

Create a custom checkov policy enforced by github actions to enforce the change made in https://github.com/govuk-one-login/authentication-api/pull/4669

BAU: checkov log retention

---

ci/terraform/oidc/staging.tfvars

ATO-656: Turn on trustmark lambda in staging

---

ci/terraform/auth-external-api/build.tfvars

ATO-707: Allow access to auth external api in build

---

ci/terraform/oidc/integration.tfvars

Mandate cloudfront in integration
Like #4675

ATO-673: Enforce cloudfront in integration

---

ci/terraform/oidc/build.tfvars
ci/terraform/shared/build.tfvars

ATO-707: Turn on kms cross account access in build

---

template.yaml

ATO-702: Feature flag provisioned concurrency

---

ci/terraform/shared/build.tfvars

ATO-707: Turn on doc app cross account access build

---

ci/terraform/shared/build.tfvars

ATO-707: Turn on user profile cross account access build

---

ci/terraform/shared/build.tfvars

ATO-707: Turn on client registry cross account access build

---

ci/terraform/shared/build.tfvars

ATO-707: Turn on auth callback userinfo cross account access build

---

ci/terraform/shared/build.tfvars

ATO-707: Turn on identity credentials cross account access build

---

template.yaml

ATO-722: Fix back channel logout queue policies

---

ci/terraform/oidc/build.tfvars

ATO-707: Turn on spot response cross account access build

---

template.yaml

ATO-707: Turn on provisioned concurrency in build

---

.gitignore
ci/stack-orchestration/configuration/build/build-notifications/parameters.json
ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json

Committing applied configuration

ATO-700: Enable notifications in orch pipeline

---

ci/terraform/oidc/build.tfvars

ATO-707: Enable storage token lambda in build

---

template.yaml

ATO-725: Add secret ids for ais uris

---

orchestration-alerting/slackNotifications.js
template.yaml

- Setup lambda subcribed to sns which posts to slack
- Update all metrics to be correct
- VPC changes required as some functions must not be in VPC for egress, and previous configuration did not work

ATO-446: Set up alerting

---

template.yaml

Fix client id in doc app callback lambda

ATO-707: Fix doc app callback client id

---

template.yaml

ATO-707: Fix AIS secret reference

---

ci/terraform/interventions-api-stub/build.tfvars

ATO-707: Allow ais stub to receive requests from build orchestration

---

ci/stack-orchestration/configuration/build/vpc/parameters.json

ATO-707: Turn on network firewall in build

---

template.yaml

ATO-707: Fix AIS secret id

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DynamoClientServiceTest.java

- Allow updating identityVerificationSupported in client registry
- Change identity_verification_required to identity_verification_supported
https://govukverify.atlassian.net/jira/software/c/projects/SSE/boards/222?selectedIssue=SSE-3447

ATO-708: Fix identityVerificationSupported for client registry

---

ci/terraform/oidc/build.tfvars

ATO-707: Turn on spot response, ipv callback and doc app callback

---

ci/terraform/auth-external-api/integration.tfvars
ci/terraform/auth-external-api/production.tfvars

ATO-7: Set up vpc endpoint ids in auth external api

---

ci/terraform/shared/integration.tfvars
ci/terraform/shared/production.tfvars

ATO-7: Set up cidr blocks

---

ci/terraform/shared/integration.tfvars

ATO-7: Turn on doc app table cross account access

---

ci/terraform/oidc/integration.tfvars
ci/terraform/shared/integration.tfvars

**Don't merge until wednesday**

ATO-7: Turn on dynamo/sqs cross account access in int

---

template.yaml

ATO-7: Fix environment variable values in template

---

ci/terraform/oidc/production.tfvars
ci/terraform/shared/production.tfvars
template.yaml

Also turns on provisioned concurrency in integration

ATO-7: Turn on dynamo sqs cross account in prod

---

template.yaml

Reverts govuk-one-login/authentication-api#4714

Revert "ATO-688: Add DynamoDB table to cache RP public keys"

---

template.yaml

ATO-7: Turn on provisioned concurrency in production

---

ci/terraform/oidc/integration.tfvars

ATO-7: Turn on trustmark lambda in integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on trustmark lambda in production, openid in integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on openid lambda in production, jwks in integration

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/reverification-result.tf
ci/terraform/oidc/staging-overrides.tfvars
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java

Add Base lambda
Add lambda infrastructure
Add api gateway endpoint on the fronted infrastructure
Policies and environment variables will need to be added as the lambda is developed.

ATO-666: Re-verification result from IPV

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

**Do not merge until thursday**

ATO-7: Turn on jwks lambda in production, authorisation in integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on authorise lambda in production, auth code in integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on auth code lambda in production, token in integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on token lambda in production, userinfo in integration

---

ci/terraform/interventions-api-stub/dev.tfvars

PR to enable Deployment of interventions-api-stub in DEV Env 
1. Code Review

Deploy intervention api in dev

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

ATO-7: Turn on ipv callback lambda in production, doc app callback integration

---

ci/terraform/oidc/spot-response.tf

ATO-7: Change auth_spot_response_disabled to disable not delete event mapping

---

ci/stack-orchestration/configuration/integration/integration-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/integration/tags.json
ci/stack-orchestration/configuration/integration/vpc/parameters.json
ci/stack-orchestration/configuration/production/production-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/production/tags.json
ci/stack-orchestration/configuration/production/vpc/parameters.json

Setting up stacks for int and prod deployments

ATO-7: Set up vpc and deploy stacks

---

ci/terraform/shared/dev-stub-clients.tfvars
ci/terraform/shared/dev.tfvars

AUT-2922 Enable rp stub client dev for Acceptance test RP creation
Code Review

Enable rp stub client dev

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars
template.yaml

ATO-7: Turn on logout and spot response event mapping in production, disable auth spot response integration

---

ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars

Also turns on storage token jwk int & prod

ATO-7: Disable auth spot response in production, turn on client registry int

---

.github/dependabot.yml

We're starting to enforce a commit message format

BAU: Prefix dependabot commit messages with BAU

---

ci/terraform/oidc/ecc-signing-key.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/mfa-reset-storage-token-jwk.tf

Adds a new KMS key for signing the JARs for MFA reset

ATO-736: Adds New Signing Key MFA Reset JARs

---

ci/terraform/oidc/ecc-signing-key.tf

Updates key alias name to fix build issues

ATO-737: Update alias name

---

ci/terraform/shared/dev-stub-clients.tfvars

BAU update dev RP stub
1. Code Review

BAU update dev RP stub

---

template.yaml

ATO-733: Remove client registry functions in prod

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/mfa-reset-authorize.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java

- Adding a new lambda `MfaResetAuthorizeHandler` with dummy implementation 
- Adds infrastructure to attach this to Auth frontend API-GW
- Deployed to sandpit - https://auth.sandpit.account.gov.uk/mfa-reset-authorize - Got expected "hello world" response

ATO-669: Infrastructure for MFA Reset Authorize Lambda 

---

.github/workflows/pre-merge-checks.yml

it was unable to properly compare branches

BAU: Fix sonar fetch depth

---

shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

I was pairing with Becka and noticed a few things that I could just make a small PR for.

BAU: Minor tidyings to AuditService (auth)

---

ci/terraform/shared/authdev1.tfvars
ci/terraform/shared/authdev2.tfvars

Enable test users for authdev1 and authdev2 stubs.
1. Code Review

AUT-2907: enable test users for authdev1 and authdev2 stubs

---

ci/terraform/oidc/authentication-callback.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/processing-identity.tf
ci/terraform/oidc/production.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuditServiceTest.java
template.yaml

Removed TXMA_AUDIT_ENCODED_ENABLED flag and related logic as flag value is always true.
Code Review

ATO-583: Remove TXMA_AUDIT_ENCODED_ENABLED Feature Flag

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java
shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java

* Updates the ticf request object to align field name with serialised name
* Adds some additional logging to the ticf handler.

Aut 2495/update ticf request

---

.github/workflows/deploy-api-modules.yml

switch back to envars from secrets.

AUT-2802: use envars for now

---

.git-blame-ignore-revs
ci/cloudfront-orchestration/waf/template.yaml
ci/stack-orchestration/manual-stacks/txma/template.yml
template.yaml

BAU: run prettier on template.yaml

---

template.yaml

Reverts govuk-one-login/authentication-api#4830

Revert "BAU: disable storage token in staging for testing"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java

Revert for PR as performance test has been finished

Revert "AUT-2701: Improve management of redis connection resources in lambdas."

---

ci/stack-orchestration/configuration/dev/cloudwatch-alarm-stack/parameters.json
ci/stack-orchestration/configuration/staging/cloudwatch-alarm-stack/parameters.json

ATO-826: Set up code storage alerts for staging and dev

---

template.yaml

Set an env var in order to vary the aud claim in the storage token by environment

ATO-880: Set aud per environment for vc storage token

---

ci/terraform/oidc/mfa-reset-jar-jwk.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetJarJwkHandler.java

Fixes incorrect class name, causing lambda to throw ClassNotFound exception upon invoke

BAU: Fix JWK handler class name

---

template.yaml

ATO-892: Change spot batch size to 1 to fix regression of ATO-538

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java

BAU: Updating logger to be called directly in function

---

template.yaml

Send storage token claim to IPV in integration
See https://github.com/govuk-one-login/authentication-api/pull/4067 for original implementation

ATO-893: Send storage token claim to IPV in integration

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java

- Fix updates to Client Reg without PK or JWKS_URL failing. Only need to enforce the presence of a public key source on creation.
Code Review

BAU: Fix Error On Update Client Without PK

---

template.yaml

This PR enables sending VC storage token claim to IPV in production
See https://github.com/govuk-one-login/authentication-api/pull/4067 for original implementation

ATO-894: Send VC storage token claim to IPV in all envs

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java

Refactors the login handler to reduce code complexity and make sonar cloud happy :-) 

Rff 6 login handler refactoring

---

shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java

Removes unused methods in the code storage service.
Also re-orders methods in the code storage service to be in a consistent order.

BAU: Remove unused code storage methods

---

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientSignatureValidationServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/api/OidcAPI.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuditService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuditServiceTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java

Added OidcAPI class for constructing relevant URIs
Code Review

ATO-631: Add OidcApi Class

---

ci/terraform/oidc/ipv-capacity.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf
template.yaml

Needed for audit service, they fail to start up without it

ATO-913: Pass oidc api base url to lambdas

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RpPublicKeyCacheService.java

Remove test logging and update logging when validating signature using RP public key
1. Code Review - double check that change to `getRpPublicKeyCacheData` doesn't affect logic

ATO-935: Remove test logging and update logging when validating signature using RP public key

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RpPublicKeyCacheService.java

Improve logging when validating signature using RP public key
Fixes a couple of issues in https://github.com/govuk-one-login/authentication-api/pull/4944

ATO-935: Improve logging when validating signature using RP public key

---

ci/terraform/shared/build-stub-clients.tfvars

AUT-3393: Adding new RP client  in  build for  secure Pipeline frontend  testing 
Code Review

AUT-3393: Adding new RP Client ID in  build for secure Pipeline

---

template.yaml

It's quite common for RPs to try integrating with back channel logout in integration and have issues, but leave the config in place so there are continual failures/alarms

BAU: Turn off noisy back channel logout alarms in int

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/dev-stub-clients.tfvars
ci/terraform/shared/staging-stub-clients.tfvars

Add am amongst the list of allowed scopes in the stub configuration
1. Code Review

BAU: add account management scope to stub clients

---

template.yaml

Enable fetching of RP public key from JWKS in staging

ATO-929: Enable fetching of RP public key from JWKS in staging

---

account-management-api/src/main/resources/log4j2.xml
auth-external-api/src/main/resources/log4j2.xml
auth-external-api/src/test/resources/log4j2.xml
client-registry-api/src/main/resources/log4j2.xml
delivery-receipts-api/src/main/resources/log4j2.xml
doc-checking-app-api/src/main/resources/log4j2.xml
frontend-api/src/main/resources/log4j2.xml
interventions-api-stub/src/main/resources/log4j2.xml
ipv-api/src/main/resources/log4j2.xml
oidc-api/src/main/resources/log4j2.xml
oidc-api/src/test/resources/log4j2.xml
orchestration-shared/src/test/resources/log4j2.xml
shared/src/test/resources/log4j2.xml
test-services-api/src/main/resources/log4j2.xml
utils/src/main/resources/log4j2.xml

Reverts govuk-one-login/authentication-api#4963

Revert "ATO-877: Update Log4j logging format to replace deprecated JsonLayout"

---

ci/terraform/shared/authdev1.tfvars

add account management scope to authdev1 stub
For example:
1. Code Review

BAU: add account management scope to authdev1 stub

---

docs/diagrams/orchestration/identity/identity.mmd

BAU: document identity flow

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java

This will give a correlation ID with RPs and help in debugging

ATO-961: Log backchannel logout jti

---

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java

Updated error code to 401
Removed 404 test

Ato 958/dcmaw contract test feedback

---

template.yaml

Enable fetching of RP public key from JWKS in integration

ATO-930: Enable fetching of RP public key from JWKS in integration

---

ci/terraform/oidc/check-reauth-user.tf
ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/authdev1.tfvars
ci/terraform/shared/authdev2.tfvars
ci/terraform/shared/dev.tfvars
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationAttemptsStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthenticationAttemptsService.java

Reverts govuk-one-login/authentication-api#4980

Revert "AUT-3370: Create `authentication-attempt` DynamoDB table, KMS key and access policies"

---

ci/terraform/oidc/staging.tfvars

Enable re-auth journey in staging.
Check the reauth feature flag is set to on for Staging.

bau-enable-reauth-in-staging

---

ci/stack-orchestration/configuration/build/build-notifications/parameters.json

https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3377168419/Slack+build+notifications+-+via+AWS+Chatbot#Enriched-notifications

BAU: enable enhanced build notifications

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java

State is set by the RP and may contain PII.
We should avoid logging it raw, but it is still useful for correlating requests with an RP when diagnosing issues.

ATO-988: Hash state before logging

---

ci/terraform/oidc/alerts.tf

Thresholds based on previous year of metrics. There was one P1 incident which should have triggered this alarm, then a couple of spikes to around 40 seconds which should have been investigated but not triggered pager duty.
1. Ensure metric queries and thresholds look right
2. Review linked runbooks

ATO-945: Create alarms for messages not being read from SPOT request queue

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/InstrumentationHelper.java

We now have Dynatrace in place

BAU: Default x-ray tracing to off

---

build.gradle

Bumps the notify client from 3.19.1 to 5.2.0
From [changelog](https://github.com/alphagov/notifications-java-client/blob/main/CHANGELOG.md):
* Breaking change for version 5 was a change to the "[NotificationClient.prepareUpload](https://github.com/alphagov/notifications-java-client/blob/7fb31e500667417b4d575efe78290c197c82f82b/src/main/java/uk/gov/service/notify/NotificationClient.java#L411)" method which we do not use
* Breaking change for version 4 was updating the [dateTimes used in the Template object](https://github.com/alphagov/notifications-java-client/blob/7fb31e500667417b4d575efe78290c197c82f82b/src/main/java/uk/gov/service/notify/Template.java#L73-L87), from a JodaTime DateTime to a ZonedDateTime. This is returned by the client in their [methods to get …

BAU: Bump notify client

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java

- Removes the `resource` field in the token request to IPV.
- Removes this field in the contract tests too
- This field is unused but we should double check before merging that this does not break any of IPV's contract tests

ATO-489: Remove resource field in token request to IPV

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java

Adds metrics logging for the browser session ID cookie. With this logging being deployed to prod, we can see the impact the browser session id cookie will have. In particular this PR adds logs to 
- see how many times this new cookie would sign users out
- see how many times this new cookie wouldn't sign users out, meaning we can see what proportion of previously signed in users now have to sign back in
- also log when the session has no browser session id. This occurs when we deploy this to prod, but a user has a valid session. We should see it spike initially, and gradually trend to 0. By logging, we can see how long this takes (expect to take ~day).
1. Code Review
1. Deploy to sandpit and see these logs being generated as expected

ATO-966: add metrics logging for browser session id

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java

Fix failing test by using latest changes from main.
This was a new test that didn't get updated to reflect the new name of the audit event it emits.  It made it onto main and was deployed to prod because failing tests weren't causing a drop-out for the checks on main.  We have added an additional check to the GH workflow to address this.
All checks on the PR should pass.

BAU: Fix failing reauth test.

---

build.gradle

BAU: Pin databind

---

build.gradle

BAU: Pin Netty correctly

---

build.gradle

BAU: Pin Commons Compress correctly

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java

This reverts commit b8ea41bf0504639ba8fbaabb7193276ec1d08144.
Pipeline is failing, this shouldn't be causing any problems, but out of superstition

Revert "AUT-3529: Delete email & password counts on authentication"

---

ci/terraform/shared/authdev2.tfvars
ci/terraform/shared/dev.tfvars
ci/terraform/shared/integration.tfvars
ci/terraform/shared/staging.tfvars

Reverts govuk-one-login/authentication-api#4704

Revert "AUT-2814: Switch off user-profile streaming in authdev2, dev, staging and integration"

---

template.yaml

Turns on cookie and metrics logging feature flag in integration and production
1. Code Review

ATO-966: turn on bsid cookie in integration and production

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

Aut 3530/reauth lockouts

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

To initiate reauthentication, an RP includes the ID token (returned by Orchestration) in the request to /authorize. This ID token contains govuk_signin_journey_id for the previous session. 
Authentication need this value in order to emit certain audit events. 
When reauth is requested,  pass the previous govuk signin journey id to Authentication as a claim.
Tested in dev and working as expected.
There is a minor refactor when extracting `idToken` from the authentication request. Check that I haven't changed any logic accidentally.

ATO-1038: Pass previous_govuk_signin_journey_id to Authentication when reauthentication is requested

---

ci/terraform/auth-external-api/staging.tfvars

AUT-3539-Add pub key for new orch_stub in staging , this is required for deploying orch Stub in Staging for new frontend
1. Code RevieW

AUT-3539-Add pub key for new orch_stub in staging

---

ci/terraform/shared/build.tfvars
ci/terraform/shared/iam.tf
ci/terraform/shared/staging.tfvars
ci/terraform/shared/variables.tf

AUT-3542: Cross account role for new Staging frontend
1. Code Review

AUT-3542: Cross account role for new Staging frontend

---

ci/terraform/shared/variables.tf

fixing small error in new frontend Account no variable 
1. Code Review

AUT-3542: fix the var input account no cross account role

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java
shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/cloudwatch/CredentialType.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/FraudCheckMetricsHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/FraudCheckMetricsHelperTest.java

Increments a new metric, UserSubmittedCredential, whenever a user is verifying a new email or phone number.
1. Code Review

Aut 3632/increment user submitted credential

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java

Refactored constructors containing duplicate logic. 
1. Code Review

BAU: Refactor and remove unused code in constructors

---

template.yaml

Turn on the feature to log out user on browser close in staging. This is to make sure the identity journey also works as expected, which I can't yet do, as it isn't hooked up on build.
1. Code Review

ATO-971: turn on logout on browser close in staging

---

build.gradle

This is a subdependency of pact, that needs to be increased due to a vulnerability

BAU: Pin protobuf dependency

---

ci/terraform/account-management/staging.tfvars

Configure the Home legacy deletion topic in staging for testing

OLH-2122: Configure manual account deletion topic in staging

---

ci/terraform/account-management/staging.tfvars

Reverts govuk-one-login/authentication-api#5289

Revert "OLH-2122: Configure manual account deletion topic in staging"

---

ci/terraform/account-management/openapi_v2.yaml

Updates the v2 method management schema as per the update to the open api spec.
[Update to open api specs](https://github.com/govuk-one-login/openapi-specs/pull/21) (at the moment we're keeping these in sync pending us being able to publish from this repo)

AUT-3722: Update method management v2 schema to latest

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Based off ATO-1060/add-channel-to-client-reg
Add channel claim to send to auth

Ato 1061: add channel claim

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java

Requests for refresh tokens are throwing 500's right now, because we set a null journey id. Set a placeholder for now whilst we deprecate

BAU: Fix refresh token null pointer

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java

Log a message when authentication successful.
So we can track successful authentications from the logs.  Metrics may not be ready for a while so this allows use to track successful authentications, as well as the completion rate in conjunction with logs showing a request for reauthentication.
1. Code Review

AUT-3749: Log message when authentication successful

---

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchSessionExtension.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/OrchSessionException.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java

Set up basic classes and methods for modifying and testing the new Orch session dynamo table.
Orch session table infrastructure: https://github.com/govuk-one-login/authentication-api/pull/5309

ATO-1075: Orch session table setup

---

ci/terraform/oidc/build-overrides.tfvars

Turn on reauth v2 in build
1. Code Review

BAU: Turn on reauth v2 in build DON'T MERGE

---

ci/terraform/oidc/build-overrides.tfvars

Reverts govuk-one-login/authentication-api#5312

Revert "BAU: Turn on reauth v2 in build DON'T MERGE"

---

ci/terraform/oidc/build-overrides.tfvars

Turn on reauth v2 in build
1. Code Review
https://github.com/govuk-one-login/authentication-api/pull/5312

BAU: Turn on reauth v2 in build

---

ci/terraform/oidc/production-overrides.tfvars

Switch on reauth v2 in production
1. Code Review

BAU: switch on reauth v2 in production DON'T MERGE

---

ci/terraform/oidc/site.tf

Deploy the check reauth user handler to production.
1. Code Review

BAU: deploy check reauth user handler

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchSessionExtension.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/LogLineHelper.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/LogLineHelperTest.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java
template.yaml

When there is no existing session, create a new Orch session and add to the Orch session Dynamo table.
When there is an existing session, update Orch session with a new session ID.
Review commit by commit
Tested in dev:
- On first login, a new Orch session is saved to dynamo with same sessionId as in shared session
- On return, sessionId is updated in dynamo
- Doc app testing in progress

ATO-1076: Create / update Orch session

---

template.yaml

Turns on the feature flag for signing out on browser close in production and integration.
1. Code Review

ATO-1014: turn on signout on browser close in prod and integration

---

ci/terraform/account-management/manually-delete-account.tf
ci/terraform/account-management/staging.tfvars

Second attempt at https://github.com/govuk-one-login/authentication-api/pull/5289. Change tested in sandpit

OLH-2122: Configure staging with Home's legacy account deletion topic

---

ci/terraform/account-management/manually-delete-account.tf
ci/terraform/oidc/authorizer-orch-frontend.tf
ci/terraform/oidc/processing-identity.tf
template.yaml

This was only updated in non prod, now updated in all environments

ATO-1029: Update java tool options in all environments for dynatrace

---

.github/dependabot.yml

Add a dependabot group for GHA and pip updates to reduce the number of PRs generated.
1. Code Review

BAU: Add dependabot group for github actions.

---

ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/sqs.tf
ci/terraform/modules/endpoint-lambda/lambda.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/oidc/sqs.tf
ci/terraform/utils/email_check_results_writer_lambda.tf

Update java tools option for  Prod also 
1. Code Review

AUT-3666: Update java tools option for All Env

---

http/account-management.http

Added account-management.http containing request templates where after populating values appropriately, requests can be made through IntelliJ. Follow the guidance here to use:
https://govukverify.atlassian.net/wiki/spaces/LO/pages/4606132332/Manually+Testing+Account+Management+API
1. Code Review
2. Review guidance [here](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4606132332/Manually+Testing+Account+Management+API)
3. Populate the request templates with values and see expected responses and effects (e.g. changed email for /update-email

AUT-2874: Added .http file containing request templates to hit Account Management API

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java

Removes temp logging from this PR https://github.com/govuk-one-login/authentication-api/pull/5407

ATO-979: Remove temp logging for testing ATO-979/d in staging

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Ato 975/pass current credential strength to auth

---

ci/terraform/shared/dynamodb.tf

- Temporarily disables the TTL configuration of the Auth session table so that in a subsequent PR we can rename the attribute_name to use the existing `ttl` attribute
- The overarching plan for fixing the TTL configuration on this table is the following:
1) Disable the TTL configuration on the table (This PR)
2) Enable it again (after > 1 hour of the following being deployed) with the `attribute_name` renamed to `ttl`
- Code review commit by commit 
- Review plan above
- Test in a dev environment:
- I have deployed both step 1 and then 2 to a dev environment (sandpit) and they deploy successfully
- Start a session before deploying this
- Deploy this change 
- Continue with session unaffected (no session timeout is seen whilst the session is still considered active) 
- This needs to be …

ATO-1104: Temporarily disable TTL configuration

---

ci/terraform/shared/dynamodb.tf

Reverts govuk-one-login/authentication-api#5438

Revert "ATO-1104: Temporarily disable TTL configuration"

---

build.gradle
init-script-dependency-graph.gradle

This supports triage of vulnerability reports as it can be used in conjunction with dependencyInsight to determine what is causing the dependency to be included if it is transitive.  See the Security Vulnerabilites Runbook (https://govukverify.atlassian.net/wiki/spaces/LO/pages/4164649233/BAU+Daytime+Support+Hygiene+and+Optimisation+Rota#SEC-1%3A-Dependabot-Vulnerability-Alerts)
Also added a task to all projects that outputs all the resolved dependencies for all projects.
Tasks added to gradle build file and updates to the vulnerability runbook.
1. Code Review
2. Follow the changes in the runbook to confirm functionality.

BAU: Add a task to search all projects for a dependency.

---

template.yaml

Supplies splunk query to quickly check if it's the same RP that's causing alarms

BAU: Add runbook to authentication callback lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java

Reverts govuk-one-login/authentication-api#5429

Revert "ATO-1088: Set authenticated flag in all cases a user is handed back from Auth"

---

template.yaml

Add link to Confluence runbook on AIS P1 alarm

BAU: Add link to runbook on AIS P1 alarm

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/sandpit.tfvars

Since we added the dropdown for the rp stub, you can request a doc app client from the standard rp stub

BAU: Set up redirect urls for doc app clients correctly

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java

Reverts govuk-one-login/authentication-api#5396

Revert "ATO-983: Set InternalCommonSubjectIdentifier In AuthSession (Auth ICSID 1/3)"

---

ci/terraform/interventions-api-stub/acceptance-test-values.tf
ci/terraform/shared/acceptance-test-values.tf
scripts/acceptance-test-params-for-secure-pipelines.sh

- **AUT-3870: Add dynamodb table arns to SSM for ATs**
- **AUT-3870: Helper script for AT SSM param creation**
Descriptions in the commit messages.
Code review

AUT-3870: Add dynamodb ARNs to SSM for acceptance testing

---

ci/terraform/interventions-api-stub/lambda.tf
ci/terraform/modules/endpoint-lambda/lambda.tf

Having an issue with terraform where it's not doing things in the
right order. A followup PR will turn snapstart back on.
Code Review

AUT-3845: Turn off Snapstart + PC for AIS

---

ci/terraform/interventions-api-stub/lambda.tf

Enable snapstart for AIS stub
Code Review

AUT-3845: enable snapstart for ais stub

---

ci/terraform/oidc/dev.tfvars

BAU: Add cloufront flag to Dev Tf vars
1. Code Review
2. Deploy to dev

BAU: Add cloufront flag to Dev Tf vars

---

template.yaml

- Enables setting the attribute IsNewAccount in the orch session 
- Turning on after running through:
- Identity Journey in staging
- Doc App Journey in build 
- Run through the journeys listed above

ATO-981: Enable setting in Orch Session for Int and Prod

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
template.yaml

- Feature Flag cleanup for the work in ticket ATO-1088. 
- Removes feature flag logic from handler 
- Removes unused config method to fetch flag
- Removes feature flag from IaC
- Deployed to orch dev 
- Run auth acceptance tests against sandpit

ATO-1088: feature flag cleanup

---

ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/mfa-reset-authorize.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/exceptions/MissingEnvVariableException.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Set up dev environments for MFA reset with IPV
1. Code Review
https://github.com/govuk-one-login/authentication-frontend/pull/2245

AUT-3823: Set up dev environments for MFA reset with IPV

---

template.yaml

Added to lambdas that are part of the main journey

BAU: Add runbook to the orchestration lambdas 

---

template.yaml

BAU: Add runbook to backchannel logout alarm

---

auth-external-api/src/main/java/uk/gov/di/authentication/external/entity/AuthUserInfoClaims.java
auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthUserInfoClaims.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Orch need this value to determine whether to set auth time in the Orch session.

ATO-1236: Always request "uplift_required" claim from Auth

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java

Reverts govuk-one-login/authentication-api#5561

Revert "BAU: Refactor Auth session setting in Start handler"

---

build.gradle

Review commit by commit. Adds new pinned dependency and removes some unncessary ones

BAU: Update pinned dependencies

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
template.yaml

- Feature flag cleanup for getters for IsNewAccount 

ATO-981: Getter feature flag cleanup

---

ci/terraform/shared/dynamodb.tf

- Comments out ttl config. 
- Will be followed up by another PR which re-enables this with the renamed attribute.
- Code review commit
- Deployed to sandpit:
- Deployed changes in https://github.com/govuk-one-login/authentication-api/pull/5572
- Deployed this 
- Observed a no-op update to shared module
- Subsequent no-op deployments did not fail 
- Branches off of https://github.com/govuk-one-login/authentication-api/pull/5572 so must be merged first

ATO-1104: comment out ttl config

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/CredentialTrustLevel.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/CredentialTrustLevelTest.java

Add in credential trust levels to a couple of audit events to make analysis easier.

INCIDEN-954: audit credential trust

---

ci/terraform/modules/endpoint-lambda/lambda.tf
ci/terraform/modules/endpoint-lambda/variables.tf
ci/terraform/modules/endpoint-lambda/wait-for-alias.sh
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/modules/endpoint-module/wait-for-alias.sh

- **AUT-3872: Wait for alias to reassign**
Details in the individual Commits.
- Code Review
1. Deploy `main` to a dev environment
2. Deploy this branch to the environment (without rebuilding the zips)
3. Observe that a no-op occurs (resources are marked as moved, not deleted and recreated)
4. Observe that the `wait` resources are created.

AUT 3872/do alias things better

---

ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/stub-rp-clients.tf
ci/terraform/shared/variables.tf

Reverts govuk-one-login/authentication-api#5609

Revert "ATO-1255: Update sandpit client reg entry to have MaxAgeEnabled=true"

---

ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/reverification-result.tf

Add missing environment variable for reverification-result lambda
Code review.

Bau configure ipv backend uri for dev

---

template.yaml

- After testing in staging by running through:
-  Identity journey in staging 
- Doc app in build (Shouldn't really affect this, more checking there is no weirdness)
- Code review the commit
- Branches off of https://github.com/govuk-one-login/authentication-api/pull/5542 so must be merged first

ATO-980: switch on int prod

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/test-services/api-gateway.tf

Access logs were accidentally sent to the execution logs log group
- Code Review
- Confirm that this change reverts a flub in 158c817b4ae2e140a03f59f04f103fe1663870d3

BAU: fix log destination flub

---

ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/auth-external-api/auth-ext-api-gateway.tf
ci/terraform/interventions-api-stub/interventions-api-stub-gateway.tf
ci/terraform/ticf-cri-stub/ticf-cri-stub-gateway.tf

We've changed the tagging for 'core', so when we search for resources by tag, we need to use these new tag values.
1. Ensure core from https://github.com/alphagov/di-infrastructure/pull/607 is deployed in an environment
2. Deploy this pr
3. If it doesn't error, all is good
Required to deploy at same time as https://github.com/alphagov/di-infrastructure/pull/607

BAU: Update tags for 'core' data sources

---

ci/terraform/account-management/site.tf
ci/terraform/auth-external-api/site.tf
ci/terraform/delivery-receipts/site.tf
ci/terraform/interventions-api-stub/site.tf
ci/terraform/oidc/site.tf
ci/terraform/shared/site.tf
ci/terraform/test-services/site.tf
ci/terraform/ticf-cri-stub/site.tf
ci/terraform/utils/site.tf

I ignored my own naming scheme when creating the tags. This is how they
should be.
Code Review

AUT-3906: Fix System tag values

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/domain/CloudwatchMetrics.java

Requested by TSD, tested in sandpit

ATO-1258: Add user info returned metric

---

ci/terraform/modules/txma-audit-queue/variables.tf

The tag was somehow ServiceName. It should be Service
Code Review

AUT-3906: Fix the Service tag in txma-audit-queue

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java

These logs are all a result of bad requests, so we should be logging them as warns rather than errors
Check that all updated logs are in fact a result of a bad request, and not an error our side

BAU: Change error logs to warn

---

scripts/lambda-function-pruner.sh

This a function to remove old lambda versions from aws. Login with sso in the command line, then run this script with the number of versions you'd like to keep as the first argument, eg `bash scripts/lambda-function-pruner.sh 5`. The minimum number of versions to keep is 3.

BAU: Add lambda function pruner for orchestration lambdas

---

frontend-api/build.gradle
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ReverificationResultService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/ReverificationResultServiceTest.java
frontend-api/src/test/resources/log4j2-test.xml

Made the initial call to IPV, to the /token, endpoint more resilient to errors.  Improved the tests by introducing wiremock to allow behaviour testing rather than implementation testing.  This allowed a couple of public methods on the ReverificationResultsService to be made private.
This is the first step.  Once this is done the code that calls the /userinfo endpoint can be refactored in the same way.  And then, finally, the lambda can be refactored so that it doesn't need to handle exceptions and not to have to understand the nimbusds response classes.
1. Code Review
2. All unit and integration tests pass.

Bau resilience improvements

---

template.yaml

We're getting a lot of invalid redirect URIs from RPs - this runbook instructs how to deal with them

ATO-1299: Add a specific runbook for authorisation handler

---

docs/diagrams/orchestration/auth-only/auth-only.mmd
docs/diagrams/orchestration/identity/identity.mmd

Sequence diagrams updated to show where AIS is called in the auth-only and identity journeys.
Has the happy-path AIS call been documented correctly?
Do you agree that AIS calls should be represented in these happy-path diagrams?
N/A

ATO-1036: Update sequence diagrams to show AIS calls

---

.pre-commit-config.yaml
template.yaml

We're getting a lot of users of one RP pressing the back button, causing an error and this to alarm. We've raised this with the RP, but will slightly increase this count for now to try and minimise the number of alarms on this endpoint.

BAU: bump auth callback alarm error rate

---

orchestration-canary-alarms.template.yaml

Taking a look to see if this makes the data less spikey

BAU: Change stat to Average on orch canary alarms

---

.pre-commit-config.yaml
ci/terraform/oidc/mfa-reset-jar-jwk.tf
ci/terraform/oidc/mfa-reset-storage-token-jwk.tf
scripts/authetication.http
scripts/http-client.env.json

The MfaResetStorageTokenJwkHandler should correctly serve the public key of the private key used to sign the storage token during a re-verification.
Added first version of http file to call the JWKS endpoints.
1. Code Review

AUT-3894: Serve storage token signing key.

---

.github/PULL_REQUEST_TEMPLATE.md

The current PR template is more relevant to Authentication than it is to Orchestration, for example the section on UCD. In addition, there are some questions that are frequently asked during reviews, such as what testing has been done in dev, and whether changes are needed to the simulator / contract tests / stubs.
- Add "Wider context of change" section to allow the reviewer to put the change into context.
- Add "Manual testing" section to allow the reviewer to explicitly record the testing completed.
- Add additional Orch specific checkboxes.
- Remove Auth specific sections.
N/A
None

ATO-1260: Update PR template to include section for Orchestration

---

ci/terraform/oidc/staging.tfvars

The name of the terraform variable used to populate the environment variable that contains url for IPV to callback to auth on was named incorrectly resulting in an undefined callback uri.
1. Code Review

AUT-3894: Rename IPV to auth callback for staging.

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java

The claim set we are sending to IPV isn't verifying successfully and we can't see what the problem is from the response we get from IPV or the logs.  Adding this logging will help triage.
1. Code Review
---

AUT-3894: Add debug logs for staging.

---

ci/terraform/oidc/mfa-reset-authorize.tf

The issuer claim for reverification requests to IPV should be the client-id see this comment thread in confluence:
https://govukverify.atlassian.net/wiki/spaces/Architecture/pages/4171989119/Authentication+Interface+with+IPV?focusedCommentId=4730290247
1. Code Review

AUT-3894: Provide client-id for issuer

---

ci/terraform/oidc/authdev1.tfvars
ci/terraform/oidc/authdev2.tfvars

AUT-3982: IPV Stub setup for Authdev's env
1. Code Review
2. deploy to Authdevs ./deploy-authdevs -o -p

AUT-3982: IPV Stub setup for Authdev's env

---

ci/terraform/oidc/account-interventions-alerts.tf

INCIDEN-934: Add AIS runbook to alarm

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/mfa-reset-authorize.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/MfaResetRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/IDReverificationStateServiceIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IDReverificationStateExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IDReverificationState.java
shared/src/main/java/uk/gov/di/authentication/shared/services/IDReverificationStateService.java

Create a Dynamo table and store relevant information in it when generating the IPV authorize URL for MFA reset with ID reverification. 
Best reviewed commit-wise

Aut-3924: Store state for cross browser

---

ci/terraform/oidc/reverification-result.tf

The ReverificationResultHandler was using the orch teams client id rather than the agreed auth team client-id.
1. Code Review

DO NOT MERGE UNTIL FRI 17 JAN: AUT-3895: Use auth specific client-id.

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
template.yaml

This feature has been turned on in production for quite some time[1], however we (I 😅 ) forgot to clear up the feature flag
[1] - https://github.com/govuk-one-login/authentication-api/pull/5596

BAU: feature flag cleanup

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/VectorOfTrust.java

Our VTR parsing is quite relaxed. It would be useful to know if an RP is sending invalid JSON just in case this parsing gets tighter in the future

BAU: Add logging of the VTR before parsing

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java

Small refactor to make code more readable and remove duplicated code.
Make use of the method `updateWithNewSessionId(session, newSessionId)` in the method with the interface `updateWithNewSessionId(session)`, where the only difference is that instead of passing in a new sessionId, the method generates a new one.
None

BAU: make use of the new method to remove duplicated code

---

template.yaml

This needs to be turned on before max_age
It's been in integration for a while with no issues
---

ATO-1301: Return auth time in id token in prod

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java
orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java

This test class was flaky possibly because it was using NowHelper.now() in seconds, which sometimes could change the test result.
We are now using an instance of NowClock instead of NowHelper. The advantage of this is that now we can use fixed times in the tests, which should make them more reliable/less flaky. 
I've also refactored the constructors in LogoutService so they delegate instead of having 3 of the same implementation with slight variations of how services are created.

ATO-1356: Use fixed times in LogoutService test

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/DeletedAccountIdentifiers.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandlerTest.java

A couple of quality of life improvements to the manual account deletion process:
- Change the format of the output following a request from TSD
- Clean the input to prevent common issues

BAU: manual deletion improvements

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java

Part of the migration work for sessionId to OrchSessionItem.
We're no longer using the shared session getter for sessionId, we're using the session ID from the cookie (which already existed in the handler, it just wasn't used everywhere)

ATO-1363: Remove use of session id getter from AuthenticationCallbackHandler

---

ci/terraform/oidc/authdev1.tfvars
ci/terraform/oidc/authdev2.tfvars

Update the configuration to provide a redirect uri to the IPV stub that points to the new frontend deployed secure pipeline in the `.dev.account.gov.uk` subdomain.
1. Code Review
2. Deploy to either authdev 1 or 2 and test with the TO-BE orchestration stub.

BAU: Point IPV stub to new sp domain in authdevs.

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/build.tfvars

Adding the configuration required by the backend to interact with the IPV stub in the build environment.
1. Code Review
2. Deploy to build and test with IPV stub.

AUT-3822: Add MFA reset config to build.

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java

Reverts govuk-one-login/authentication-api#5855, so we can unblock the pipeline

Revert "ATO-646: Log warning if client id in auth code does not match request params"

---

ci/terraform/oidc/staging.tfvars

IPV would like to test the JWKS endpoint functionality in staging.
This PR configures the api gateway to allow forwarding to the orch JWKS endpoint in staging

ATO-1423: Turn on orch_ipv_jwks_enabled in staging

---

ci/stack-orchestration/configuration/staging/cloudwatch-alarm-stack/parameters.json

Update Cloudwatch template stack to include runbook in description for staging
deployed successfully to staging

ATO-1354: update cloudwatch alaram template with runbook in description

---

ci/terraform/interventions-api-stub/dynamodb.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/ticf-cri-stub/dynamodb.tf

AUT-4046 :  Backup tags are case Sentive as per dev platform team, so changing the tags value
Code Review

AUT-4096: change the value of tags Backup frequency as its case Sensitive

---

ci/terraform/interventions-api-stub/authdev1.tfvars
ci/terraform/interventions-api-stub/authdev2.tfvars
ci/terraform/interventions-api-stub/build.tfvars
ci/terraform/interventions-api-stub/dev.tfvars
ci/terraform/interventions-api-stub/sandpit.tfvars
ci/terraform/interventions-api-stub/variables.tf

- **AUT-4030: set `var.environment` via envar**
- **AUT-4030: ias: Dedup and tidy variables**
- Check I've not missed anything
- check it deploys sensibly

AUT-4030: Un-split ias tfvars

---

ci/terraform/ticf-cri-stub/dev.tfvars

Fix Dev TICF deployment
Code Review
Deploy to DEV env

BAU: Correct the terraform state bucket name for Dev

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/IpvReverificationFailureCode.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/MfaResetAuthorizeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ReverificationResultHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/TxmaAuditHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/TxmaAuditHelperTest.java

Final changes to the happy path audit events for MFA reset with IPV re-verification:
AUTH_REVERIFY_AUTHORISATION_REQUESTED 
AUTH_REVERIFY_SUCCESSFUL_TOKEN_RECEIVED
AUTH_REVERIFY_VERIFICATION_INFO_RECEIVED
The content of these events now matches the design and schemas in the event catalogue.
Also removed the call to the new TxmaAuditHelper from the Sign-up handler as it caused the rpPairwiseId to be missing from the AUTH_CREATE_ACCOUNT event.  I haven't removed the helper class, even though its only used in one place now, so we can look to address the parameters that we are passing to it.
1. Code Review

AUT-3974: Final changes to the happy path audit events for MFA reset with IPV re-verification

---

template.yaml

BAU: Temporarily increase threshold for backchannel logout alarms

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AuthCodeException.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java

Reverts govuk-one-login/authentication-api#5953

Revert "ATO-1123: migrate email in AuthCodeHandler"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java

Swaps getter for internalCommonSubjectId for auth session

ATO-1322: swap getter for auth session

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java

Swaps getter for internalCommonSubjectId for auth session

ATO-1322: swap getter for auth session in mfaResetAuthorize

---

ci/terraform/oidc/build.tfvars

- RSA key pair
- The matching secret has been updated in di-authentication-build

AUT-4064: add IPV public encrypting key

---

ci/terraform/oidc/build.tfvars

Add ipv_audience to authentication API
1. Code Review

AUT-4064: add ipv_audience

---

ci/terraform/oidc/integration.tfvars

MFA Reset with IPV config for integration environment.
1. Code Review

AUT-4047: MFA reset with IPV integration config

---

ci/terraform/oidc/production.tfvars

New production config for MFA reset with IPV.
I've grouped all the config together in the main production.tfvars file to make it easier to review.
1. Code Review

AUT-4047: MFA reset with IPV prod config

---

ci/terraform/oidc/mfa-reset-authorize.tf

The MfaResetAuthorizeHandler needs the internal sector uri to calculate the internal subject id for users originating in the OneLogin Home RP.
1. Code Review

AUT-4047: Add internal sector id for MFA reset

---

template.yaml

Reverts govuk-one-login/authentication-api#6032

Revert "ATO-1469: rename table with Orch prefix"

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java

We were logging the claim set which was useful in lower environments and initial production checking but not needed long term.
1. Code Review

AUT-4047: Remove additional logging.

---

ci/terraform/account-management/.gitignore
ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/mfa-methods-create-backup.tf
ci/terraform/account-management/mfa-methods.tf
ci/terraform/account-management/openapi_v2.yaml

Adding the MFA create lambda.  The initial version is a hello world and is deployed using terraform to the new version of the API gateway being built for account management.
1. Code Review
2. Deploy to a dev environment and verify the lambda can be invoked from the API gateway.
1. Code Review

Aut 3485/mfa methods post

---

ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/mfa-mm-create-backup.tf

The name that we were using for the MFA Methods create backup lambda was exceeding the maximum length when it was being generated in the highest environments (integration and production) but not in lower environments as they all have shorter names.
1. Code Review

AUT-3484: Reduce length of MFA create lambda name

---

shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/MfaHelperTest.java

We want to check whether users can actually get into the state whereby an auth app method exists but is neither verified nor enabled  as it's not currently clear how this would happen
Logging added for the other cases for completeness.
We can probably remove this logging once we've had a look at the data

BAU: Add logging for mfa cases

---

ci/terraform/account-management/openapi_v2.yaml

Currently, we have two versions of the spec, one in this repo and one in and internal repo.  This PR simply re-syncs this repos copy with the one in the internal repo.
1. Code Review

BAU: Re-sync MFA Methods openapi spec

---

ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/mfa-mm-create-backup.tf

Partial revert #6062 - terraform changes created cycle issue
Check this makes sense

AUT-3848: Revert terraform changes from #6062

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java

Reverts govuk-one-login/authentication-api#6069

Revert "Reapply/ato 1462 basefrontendhandler email address authsessionitem"

---

ci/terraform/account-management/integration.tfvars

By providing an openapi spec for the
api-gateway-method-management module API Gateway will configure the endpoints according to the spec thus allowing us to test in integration.
1. Code Review

AUT-3485: Enable MFA Methods API in integration

---

python-utils/.gitignore
python-utils/README.md
python-utils/pyproject.toml
python-utils/requirements.txt
python-utils/scripts/create_encrypting_key_from_jwks.py
python-utils/scripts/create_signing_key_from_jwks.py
python-utils/scripts/generate_ec_signing_key.py
python-utils/scripts/generate_rsa_encrypting_key.py

We needed to create a key from IPVs JWKS endpoint to add to our static
configuration as we haven't implemented the code that will retrieve it
automatically yet. The scripts to do this are included in this commit.
Additionally, we needed to create a key pair for our lower environment
deployments where we use the IPV stub.  The scripts used to generate
those keys are also included.
1. Code Review
2. Use uv to build and run the scripts following the instructions in the readme.

AUT-4047: Add scripts used to create keys.

---

template.yaml

Reverts govuk-one-login/authentication-api#6093

Revert "BAU: Turn back on backchannel logout alarms"

---

ci/terraform/oidc/api-gateway.tf

There is an ongoing initiative (FMS) to migrate WAF to be centrally controlled. This tag lets the team doing the migration know that this API Gateway is behind cloudfront, so does not need WAF to be applied directly in front of it. 
TF plan against sandpit to make sure the API Gateway is not recreated:

BAU: Add tag for firewall migration

---

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java

Ensure no error will be thrown: no behaviour should be changed

AUT-2909: Add logging to compare new account values from frontend and backend

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsDeleteHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsDeleteHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java
ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/mfa-methods-delete.tf
ci/terraform/account-management/mfa-methods-update.tf
ci/terraform/account-management/openapi_v2.yaml
ci/terraform/modules/api-gateway/api-gateway.tf

Implements basic hello world put and delete endpoints for the new method management api (basic handler and infrastructure).
This will form the basis for the logic to be implemented as part of AUT-3486 and AUT-3487.
1. Code review

Aut 3486/hello world put and delete

---

ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authdev1.tfvars
ci/terraform/account-management/authdev2.tfvars
ci/terraform/account-management/dev.tfvars
ci/terraform/account-management/variables.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/authdev1.tfvars
ci/terraform/oidc/authdev2.tfvars
ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/variables.tf

Migrate authdev{1,2} and dev Account API gateways to FMS WAF.
Code Review

BAU: Migrate Auth WAFs to FMS

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

As part of splitting off the session store, we started passing Auth the previous session id when sending a user to them. This is fine but this did not take into account whether the use had recently logged out, and therefore there was no orchestration session. 
- Sets previous session id to an empty optional in the case a new orch/shared session is created
- Deployed to dev and ran through a journey
- Ran auth acceptance tests against this in sandpit, some failures but these did not look related to this change
- Tested some silent login and uplift journeys to ensure they are not broken by this change

ATO-1522: Only pass previous session id if session present

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java

This is for debugging and should be removed shortly

AUT-2912: add log line to record payload to TICF

---

shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java

The array is not being correctly deserialised, and I don't see any reason to use an array over list

AUT-2912: Change type of mfaMethod

---

ci/terraform/auth-external-api/dev.tfvars

AUT-4162: Allow lambda to access orch stub api using vpce endpoint **( DEV)** 
1. Code Review

AUT-4162: Allow lambda to access orch stub api using vpce endpoint

---

ci/terraform/account-management/staging.tfvars
ci/terraform/oidc/staging.tfvars

Enable FMS in api staging
- Check I've enabled it
- Check I've enabled it in staging

BAU: enable FMS in staging

---

ci/terraform/oidc/staging.tfvars

The variable name was changed, but the tfvars file was not
updated.
Check that the variable is actually being set now

BAU: fix FMS tag variable name

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java

We've migrated this value to the auth session, and these methods were never used in orch code
- Removed some unused session methods
- N/A dead code

BAU: Remove code request count methods

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/api-proxy.sh
ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/mm-api-dev-access.tf
ci/terraform/modules/api-gateway/api-gateway.tf
ci/terraform/modules/private-api-gateway/README.md
ci/terraform/modules/private-api-gateway/output.tf
ci/terraform/shared/session-manager.tf
scripts/_generate-auth-token.js
scripts/api-proxy.sh
scripts/export-ics.sh
scripts/generate-auth-token.sh

All details on the individual commits!
- Code Review
- Check for anything dumb

AUT-4125: MM API Dev Access

---

docs/adr/0001-local-adrs.md
docs/adr/0002-reauthentication-error-counts-table-design.md

An ADR to record how we designed the new DynamoDB table for holding the error counts for re-authenticaiton.
1. Confirm chosen design is accurately reflected in the table and how the re-authentication code uses it.
2. Confirm supporting files, template and index, are correct.

BAU: Add ADR for re-authentication DynamoDB table design

---

ci/terraform/account-management/mm-api-dev-access.tf
ci/terraform/modules/is-this-the-primary-environment/README.md
ci/terraform/modules/is-this-the-primary-environment/main.tf
ci/terraform/shared/acceptance-test-values.tf
ci/terraform/shared/session-manager.tf

Details in the commits
Code review

BAU: MM Proxy improvements

---

ci/terraform/account-management/mm-api-dev-access.tf
ci/terraform/modules/is-this-the-primary-environment/README.md
ci/terraform/modules/is-this-the-primary-environment/main.tf
ci/terraform/shared/acceptance-test-values.tf
ci/terraform/shared/session-manager.tf

Details in the individual commits
:eyes:

BAU: Method Management proxy improvements

---

ci/terraform/account-management/build.tfvars
ci/terraform/account-management/sandpit.tfvars
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/sandpit.tfvars

BAU: Enable fms for build & sandpit
For example:
1. Code Review

BAU: Enable fms for build & sandpit

---

ci/terraform/account-management/integration.tfvars
ci/terraform/oidc/integration.tfvars

BAU: Enable FMS waf on integration Env
For example:
1. Code Review

BAU: Enable FMS waf on integration Env

---

ci/terraform/shared/dynamodb.tf

This has been successfully tested in staging

BAU: Deploy the count users index to production

---

template.yaml

ATO-1573: Turn on PKCE in integration

---

ci/terraform/account-management/production.tfvars
ci/terraform/oidc/production.tfvars

Enable FMS waf on production  Env
For example:
1. Code Review

BAU: Enable FMS WAF flag for Prod acct mgmt & Frontend API

---

.gitignore
http/README.md
http/client-registry.http
http/http-client.env.json
http/http-client.private.env.json.template

Add example HTTP requests to allow testing the client registry API

ATO-1576: Client registry api http examples

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/LogMessageTemplates.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java

Refactor NotitificationHandler prior to adding the test feature of storing the security code on an S3 bucket.
1. Code Review
2. Run tests via gradle
3. Deploy to a dev environment and check both emails and text are sent.

Aut 2200/refactor am notification handler

---

ci/terraform/utils/authdev1.tfvars
ci/terraform/utils/authdev2.tfvars
ci/terraform/utils/dev.tfvars
ci/terraform/utils/mfa_method_analysis_lambda.tf
ci/terraform/utils/sandpit.tfvars
ci/terraform/utils/staging.tfvars
ci/terraform/utils/variables.tf
utils/src/main/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandler.java

Merging this will end up deploying the lambda to production and log the result so it can be seen after execution.
1. Code Review

AUT-4123: Release MFA method analysis lambda to prod

---

ci/terraform/utils/mfa_method_analysis_lambda.tf

We want this lambda to be invoked out of hours, so we're going ot use EventBridge scheduler to do a one of invocation.
This adds a role we can use for the schedule to give it permission to invoke the lambda.
1. Code Review

AUT-4123: Create role for EventBridge scheduler

---

ci/terraform/account-management/staging.tfvars

Enable Home access to the Account Management MFA Methods API in Staging.
1. Code Review

BAU: Allow Home access to MM API in Staging

---

backend-template.yaml

Initial backend template. This is just a skeleton. A POC that works to deploy a single AWS component thru secure pipelines.
Issue: [AUT-4214]
[AUT-4214]: https://govukverify.atlassian.net/browse/AUT-4214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4214: Initial backend template

---

ci/terraform/shared/migrate-redis-state-authdev2.sh
ci/terraform/shared/redis.tf
ci/terraform/shared/security-groups.tf

AUT-4133: move frontend redis to Shared resource in API repo
1. Code Review

AUT-4133: move frontend redis to Shared resource in API repo

---

ci/terraform/shared/integration.tfvars
ci/terraform/shared/production.tfvars

AUT-4133: Add Auth New Account CIDR range to prod & integration env
1. Code Review

AUT-4133: Add Auth New Account CIDR range to prod & integration env

---

ci/terraform/account-management/alerts.tf
ci/terraform/account-management/api-gateway-method-management.tf
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authdev1.tfvars
ci/terraform/account-management/authdev2.tfvars
ci/terraform/account-management/build.tfvars
ci/terraform/account-management/dev.tfvars
ci/terraform/account-management/integration.tfvars
ci/terraform/account-management/production.tfvars
ci/terraform/account-management/sandpit.tfvars
ci/terraform/account-management/staging.tfvars
ci/terraform/account-management/variables.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/authdev1.tfvars
ci/terraform/oidc/authdev2.tfvars
ci/terraform/oidc/build.tfvars
ci/terraform/oidc/dev.tfvars
ci/terraform/oidc/integration.tfvars
ci/terraform/oidc/production.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging.tfvars
ci/terraform/oidc/variables.tf

AUT-4229 remove-fms-feature-flag-and-auth-managed-waf
1. Code Review

Aut 4229 remove fms feature flag and auth managed waf

---

ci/terraform/account-management/s3.tf
ci/terraform/account-management/sqs.tf

The new bucket for storing otps during acceptance testing has been created in production and integration but we aren't going to use it there at the moment so removing them.
The new bucket for storing otps during acceptance testing has been created in production and integration but we aren't going to use it there at the moment so removing them.
1. Code Review

BAU: Remove bucket from prod/int

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/MfaDetailDeserializer.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/MfaMethodCreateOrUpdateRequest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/RequestAuthAppMfaDetail.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/RequestSmsMfaDetail.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/MfaMethodResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/ResponseAuthAppMfaDetail.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/ResponseSmsMfaDetail.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
shared/src/test/java/uk/gov/di/authentication/shared/serialization/MfaDetailDeserializerTest.java

Refactor the request/response classes for the MFA Method Create and Update endpoints.
Added OTP verification to the Create and Update handlers.
1. Code Review
2. Deploy to an environment and test.

AUT-4134/add otp checks

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java

This code is currently quite fragile, as we enter into another method with a defined orchSession when we know bsid means the user should be logged out. Nothing breaking yet, but it is fragile to breaking.
Set `existingOrchSessionOptional` to `Optional.empty()` when we know the user should be logged out
Deployed to dev and
- Completed an auth-only journey
- Verified that on doing another auth-only journey, I am logged in silently
- Closed my browser
- Verified that I had to login again.

BAU: set existingOrchSessionOptional to empty for new sessions

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java

We recently started sending claims through from orch to auth backend, to replace the need for the client session. We are logging whether the new claims are the same as the equivalent fields on the client session. We have noticed a few differences in the logs indicating they are not in sync, but its hard to tell where to start looking.
This PR refactors the sync logging a bit, outputting whether either field is null. This should help narrow down where to look to fix the sync issues.
Just logging changes, no new functionality added that needs testing.

ATO-1435: Improve logging for new claim equality

---

template.yaml

ATO-1465: Turn on PKCE in prod

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

Make sure the correct MFA type is stored when updating the Default method to another type of MFA.
1. Code Review

AUT-4320: Ensure MFAMethods type updated correctly

---

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java
auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java
auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java

Updates the rules for what phone number we send back in the Auth <-> Orch UserInfo response. 
See https://govukverify.atlassian.net/browse/AUT-4315 for more details
1. Code Review
2. TBD: deploy to sandpit and test

AUT-4315: update rule for phone number in userinfo

---

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java
auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java
auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java

Reverts govuk-one-login/authentication-api#6483

Revert "AUT-4315: update rule for phone number in userinfo"

---

account-management-integration-tests/build.gradle
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java

Increasing test coverage and re-working the integration test in preparation for refactoring the business logic for MFA methods having a credential or a destination but not both.
1. Code Review

AUT-4320: Update MM Put handler tests

---

ci/terraform/account-management/build.tfvars
ci/terraform/account-management/staging.tfvars

…g envs
enable ais_call_in_authenticate_enabled in build and staging env
Terraform var updates

OLH-2690: enable ais_call_in_authenticate_enabled in build and staging env

---

client-registry-api/build.gradle

Bump commons-validator
1. Code Review

BAU: bump commons-validator

---

.github/workflows/deploy-api-modules-sp-dev.yml
.github/workflows/deploy-api-modules-sp.yml
backend-template.yaml
sam-deploy-authdevs.sh
scripts/dev-samconfig.toml

Deploy Frontend API and account-interventions function via secure pipelines
POC: setting up GHA + Frontend API + One of the lambda endpoints activated should suffice
Issue: [AUT-4376]
Deploy using sam-deploy-authdevs.sh to authdev1, authdev2. Tested deployment. Output in the jira ticket. 
[AUT-4376]: https://govukverify.atlassian.net/browse/AUT-4376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4376: Deploy Frontend API and account-interventions function via secure pipelines

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

Update the check that a phone number, used for 2FA, is not already being used.  
1. Code review
2. Deploy to dev and run frontend and backend acceptance tests.

Aut 4320/check phone number not in use

---

ci/terraform/account-management/build.tfvars

This will allow the MM API acceptance tests to be run.

BAU: Enable test clients in build

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

Re-instate reverted changes.
Add User Profile write permission
1. Code Review
2. Deploy to dev and run acceptance tests.

Phone Number In Use Check

---

ci/stack-orchestration/configuration/integration/integration-orch-be-pipeline/parameters.json
ci/stack-orchestration/configuration/production/production-orch-be-pipeline/parameters.json
orchestration-canary-alarms.template.yaml
template.yaml

Reverts govuk-one-login/authentication-api#6717

Revert "ATO-1485: Turn on canary deployments"

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsDeleteHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsDeleteHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/MFAMethodsServiceTest.java

Added metrics for create, delete and update MFA methods cases
For update and delete case I found it cleaner to do this inside `MFAMethodsService` but for create kept it in the `MFAMethodsCreateHandler` 
1. Code Review

AUT-4372: Add new metrics for MFA Methods success cases

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java
shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Add `mfa-method` and `journey-type` to the AUTH_UPDATE_PROFILE_PHONE_NUMBER and AUTH_UPDATE_PROFILE_AUTH_APP audit events.
1. Code Review.  Note Q was used to write the commit message, do some refactoring and add a couple of test cases.

AUTH-4368 and AUTH-4383 Audit Event Updates

---

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java
auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java
auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java

Reverts govuk-one-login/authentication-api#6518

Revert "AUT-4315: update rule for phone number in userinfo response"

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java

Add audit event for successful MFA method addition
1. Code Review

Olh 2693/auth mfa method add completed

---

ci/terraform/account-management/mfa-methods-create.tf

The create MFA lambda needs privs to access the TxMA queue.
1. Code Review
Tested in dev and failing tests now pass.

OLH-2693: Add privs to TxMA queue

---

ci/terraform/account-management/openapi_v2.yaml
ci/terraform/account-management/production.tfvars

Reverts govuk-one-login/authentication-api#6702

Revert "AUT-4466: Enable AM API V2 in Production"

---

.github/PULL_REQUEST_TEMPLATE/auth_template.md

In order to raise awareness and checks of existing journey impacts as a result of a code change, a checkbox is added to the auth template to remind developers to check for this issue.
A longer term solution with canary deployments is in the work.
1. Code Review

BAU: Include active user journey impact check in PR template

---

ci/cloudformation/auth/function/check-reauth-user.yaml
ci/cloudformation/auth/function/login.yaml
ci/cloudformation/auth/function/mfa.yaml
ci/cloudformation/auth/function/orch-auth-code.yaml
ci/cloudformation/auth/function/send-notification.yaml
ci/cloudformation/auth/function/verify-code.yaml
ci/cloudformation/auth/function/verify-mfa-code.yaml
ci/cloudformation/auth/parent.yaml

BAU: replace resolve:ssm dynamic references with static mappings

BAU: replace resolve:ssm dynamic references with static mappings

---

.editorconfig

BAU: disallow wildcard imports in editorconfig
1. Code Review

BAU: disallow wildcard imports in editorconfig

---

ci/cloudformation/auth/function/account-interventions.yaml
ci/cloudformation/auth/function/account-recovery.yaml
ci/cloudformation/auth/function/auth-token.yaml
ci/cloudformation/auth/function/auth-userinfo.yaml
ci/cloudformation/auth/function/check-email-fraud-block.yaml
ci/cloudformation/auth/function/check-reauth-user.yaml
ci/cloudformation/auth/function/email-notification-sqs.yaml
ci/cloudformation/auth/function/login.yaml
ci/cloudformation/auth/function/mfa-reset-authorize.yaml
ci/cloudformation/auth/function/mfa-reset-jar-jwk.yaml
ci/cloudformation/auth/function/mfa-reset-storage-token-jwk.yaml
ci/cloudformation/auth/function/mfa.yaml
ci/cloudformation/auth/function/orch-auth-code.yaml
ci/cloudformation/auth/function/reset-password-request.yaml
ci/cloudformation/auth/function/reset-password.yaml
ci/cloudformation/auth/function/reverification-result.yaml
ci/cloudformation/auth/function/send-notification.yaml
ci/cloudformation/auth/function/signup.yaml
ci/cloudformation/auth/function/start.yaml
ci/cloudformation/auth/function/ticf-cri.yaml
ci/cloudformation/auth/function/update-profile.yaml
ci/cloudformation/auth/function/user-exists.yaml
ci/cloudformation/auth/function/verify-code.yaml
ci/cloudformation/auth/function/verify-mfa-code.yaml
ci/cloudformation/auth/parent.yaml

Change did not produce the expected outcome. Rolling back. 
This reverts commit 98681037f1f0c3ccdd0d0a98bdd6be58eb410062.
Test the changes by deploying to dev envs

Revert "AUT-4533: Split one CodeDeployServiceRole into three"

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/DocumentAppCredentialStoreExtension.java
template.yaml

Reverts govuk-one-login/authentication-api#6808

Revert "ATO 1745: Swap reads to new doc app cred table"

---

.pre-commit-config.yaml

BAU: bump go & tflint in pre-commit

---

ci/terraform/oidc/sqs.tf

AUT-4435: Change Smoke test code bucket & update lambda permission
1. Code Review
1. Deploy to authdevs with `./deploy-sandpit.sh -o -p`

AUT-4435: Change Smoke test code bucket & update lambda permission

---

ci/terraform/account-management/authdev3.hcl
ci/terraform/account-management/authdev3.tfvars
ci/terraform/account-management/dns.tf
ci/terraform/auth-external-api/authdev3.hcl
ci/terraform/auth-external-api/authdev3.tfvars
ci/terraform/delivery-receipts/authdev3.hcl
ci/terraform/delivery-receipts/authdev3.tfvars
ci/terraform/interventions-api-stub/authdev3.hcl
ci/terraform/interventions-api-stub/authdev3.tfvars
ci/terraform/oidc/authdev3.hcl
ci/terraform/oidc/authdev3.tfvars
ci/terraform/oidc/dns.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/authdev3.hcl
ci/terraform/shared/authdev3.tfvars
ci/terraform/shared/dynamodb.tf
ci/terraform/test-services/authdev3.hcl
ci/terraform/test-services/authdev3.tfvars
ci/terraform/ticf-cri-stub/authdev3.hcl
ci/terraform/ticf-cri-stub/authdev3.tfvars
ci/terraform/utils/authdev3.hcl
ci/terraform/utils/authdev3.tfvars
deploy-authdevs.sh
deploy-dev.sh

AUT 4391 New authdev3 env to replace sandpit env 
1. Code Review
1. Deploy to sandpit with `./deploy-authdevs

AUT 4391 new authdev3 env to replace sandpit

---

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawTokenTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java

Updating the pact provider for DCMAW so they can run through verification.
https://gds.slack.com/archives/C05EW21TW3A/p1753178963994169

BAU: update the pact provider for DCMAW

---

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/CookieHelper.java

We look for values for both headers, then perform a cookie lookup only against one of them. This is easily simplified and means we can drop the null check because the empty value falls out of the stream.

BAU: Radically simplify `getHttpCookieFromMultiValueResponseHeaders`

---

ci/cloudformation/auth/parent.yaml

Switch off provisioned concurrency in integration env
[AUT-4538]
[AUT-4538]: https://govukverify.atlassian.net/browse/AUT-4538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4538: switch off provisioned concurrency in integration env

---

ci/cloudformation/auth/parent.yaml

Configuring Integration auth-internal-api to link with apitest frontend and orchstub

AUT-4538: Integration env apitest frontend and orchstub configs

---

template.yaml

To allow for perf tests
> [!TIP]

BAU: Turn on RP rate limiting in staging

---

template.yaml

We previously introduced some changes to handle some cross browser behaviour. This was feature flagged up to staging - we will now turn it on in integration and production.
- Enables previously introduced changes in integration and production
- N/A for this set of changes but the changes have been tested in staging before enabling this
- Previous PR which added the bulk of this work and the feature flag: https://github.com/govuk-one-login/authentication-api/pull/6889
- Previous PR which extended the checking to all cases where possible: https://github.com/govuk-one-login/authentication-api/pull/6894

ATO-1865: Turn on enhanced Cross Browser handling in int and prod

---

ci/stack-orchestration/configuration/dev/dev-orch-be-pipeline/parameters.json
template.yaml

Revert dev to use sandpit instead of authdev3

BAU revert to sandpit

---

ci/terraform/oidc/mfa-reset-authorize.tf
ci/terraform/oidc/reverification-result.tf

Reverts govuk-one-login/authentication-api#6941

Revert "AUT-4287: Rotate MFA reset signing key to secondary on staging and below"

---

.github/workflows/pre-merge-checks.yml
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
docker-compose.yml
integration-tests/src/test/java/uk/gov/di/authentication/utils/JwksUtilsIntegrationTest.java

- Updated github action docker configuration to match docker-compose.yml
- Made a tweak to each test suite to prompt github to run the tests
1. Code Review
1. Observe GHA integration tests still pass

BAU: Update GHA container definitions to match docker-compose.yml

---

.github/workflows/deploy-api-modules-sp.yml

Trigger secure pipeline api deploy if openAPI specs change

AUT-4539: Trigger secure pipeline api deploy if openAPI specs change

---

ci/cloudformation/auth/parent.yaml

Updated Auth API CloudFormation template description

AUT-4539: Updated Auth API CloudFormation template description

---

template.yaml

Reverts govuk-one-login/authentication-api#6984

Revert "ATO-1866: Add resource policies to PII containing tables"

---

ci/terraform/oidc/sqs.tf

AUT-4694: Switch Smoke test code bucket in prod
1. Code Review

AUT-4694: Switch Smoke test code bucket in prod

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/GlobalLogoutHandler.java

Noticed inconsistencies with global logout log levels, made both WARN.
Global logout ERROR log updated to WARN.
N/A

BAU: update global logout log level

---

ci/cloudformation/auth/parent.yaml

[AUT-4700]: Hardcode Dynatrace layer ARN and remove lambda concurrency
[BAU]: remove Lambda provisioned concurrency 
Note: These lambda are not live still in build phase 
1. Code Review 
[AUT-4700]: https://govukverify.atlassian.net/browse/AUT-4700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AUT-4700: Hardcode Dynatrace layer ARN and remove lambda concurrency

---

ci/cloudformation/auth/parent.yaml

BAU: Remove lambda concurrency from not live lambda
These lambda are not live 
1. Code Review

BAU: Remove lambda concurrency from not live lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java
template.yaml

Bug fix for multiple journey
No need for flag any more as its in production
Deploy to dev and ran through an identity journey

ATO 1909/clean up feature flag cross browser

---

orchestration-alerting/slackNotifications.js
template.yaml

Reverts govuk-one-login/authentication-api#7093

Revert "ATO-1941: Send slack alerts to orch prod channel"

---

ci/cloudformation/auth/function/email-notification-sqs.yaml
ci/cloudformation/auth/parent.yaml

BAU: update email sqs lambda to sent Smoke test code to new bucket
1. Code Review

BAU: update email sqs lambda to sent Smoke test code to new bucket

---

ci/cloudformation/auth/parent.yaml
template.yaml

Post testing in staging reverting the changes Reverts govuk-one-login/authentication-api#7117

Revert "AUT-4710: Staging authExternalApiId & Auth Internal Api ID temporary …"

---

ci/cloudformation/auth/parent.yaml

BAU: Fix deployment failure in Build SP Api
1. Code Review

BAU: Fix deployment failure in Build SP Api

---

ci/cloudformation/auth/parent.yaml
template.yaml

AUT-4711: Switch internal Api on Build
1. Code Review

AUT-4711: Switch internal Api on Build

---

ci/cloudformation/auth/function/processing-identity.yaml

Add Dynamo db env variable to Lambda config
1. Code Review

BAU: Add Dynamo db env variable to Lambda config

---

ci/cloudformation/auth/function/processing-identity.yaml

BAU: fix processing lambda error
1. Code Review

BAU: fix processing lambda error

---

.github/workflows/deploy-api-modules-sp-stubs.yml
ci/cloudformation/stubs/parent.yaml

[AUT-3816 ]:  Sp TICF cri stub changes
1)  Removing not used lambda role 
2) Adding Authdev3 env mapping 
1. Code Review

AUT-3816 :  Sp TICF cri stub changes

---

ci/cloudformation/stubs/function/ticf-stub-interventions.yaml
ci/cloudformation/stubs/parent.yaml
sam-deploy-authdevs.sh
scripts/dev-samconfig.toml

AUT-3816 enable snapstart on SP ticf lambda
1. Code Review

Enable snapstart on SP Ticf lambda

---

ci/cloudformation/stubs/parent.yaml

BAU: Add missing dynamo Table resource to fix Lambda
1. Code Review

BAU: Add missing dynamo Table resource to fix Lambda
