govuk-one-login/authentication-api

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/ticf-cri.tf, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/BulkUserEmailAudienceLoaderScheduledEventHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/LambdaInvoker.java, shared/src/main/java/uk/gov/di/authentication/shared/services/LambdaInvokerService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/LambdaInvokerServiceTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailAudienceLoaderScheduledEventHandlerTest.java
The Account Interventions Handler has been modified to invoke the TICF Lambda dependent on the value of a feature switch.
1. Code Review
2. Deploy to sandpit with `./deploy-sandpit.sh -a`
=> Aut 2490/make lambda invoker more generic

ci/terraform/account-management/authdev1.tfvars, ci/terraform/account-management/authdev2.tfvars, ci/terraform/account-management/build-overrides.tfvars, ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/sandpit.tfvars, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
Add a lockout type for incorrect password attempts in redis and use during sign in journey.
The lockout duration for invalid password attempts during the sign in journey is linked to the ttl duration. This is believed to be because this was one of the first components to introduce lockout and at the time there was no distinction between tt and lockout duration.
We need to remove this dependency and implement lockout using redis in line with the rest of our lockout processes.
1. Code Review
2. Deploy to dev/authdev
3. QA to test acceptance criteria from the [JIRA ticket](https://govukverify.atlassian.net/browse/AUT-2833)
=> AUT-2833: implementation of lockout for too many incorrect passwords instead of the dependency on ttl duration

template.yaml
To allow IPV to test their code to read the token when it is not present
=> BAU: disable storage token in staging for testing

ci/terraform/oidc/staging.tfvars
This turns on the call to ticf, which is currently called asynchronously and has no effect on user journeys
=> AUT-2495: Call ticf in staging

ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/ticf-cri.tf
Bumps the lambda timeout for ticf, and also the http timeout in staging.
These are temporary measures while we ensure that the integration with the ticf cri in staging is working. Once we're happy with this, we can tune these variables back down.
1. Code Review
=> Aut 2495/bump lambda timeout for ticf

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawTokenTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/api/DocAppCriAPI.java
Added DocAppCriAPI class for constructing relevant URIs
=> ATO-630: Add DocAppCriAPI Class

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountRecoveryHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, shared/src/main/java/uk/gov/di/audit/AuditContext.java
In most handlers, half of the fields in the audit context come from the user context. Therefore, creating a constructor which handles the retrieval of values from the user context makes the handler code less verbose.
I used my editor to optimise the imports in some handlers, which also reversed some wildcard imports, which we should be avoiding.
1. Code Review
=> BAU: Introduce constructor method for audit context

.github/workflows/deploy-api-modules-dev.yml, .github/workflows/deploy-api-modules.yml, .gitignore
As-per https://ordinaryexperts.com/blog/2019/04/27/better-codepipeline-metadata
This extra metadata is shown in the codepipeline UI and will allow better identification of where the artifact has come from.
- Code review
- Deploy to dev from this branch (`./scripts/trigger-gha-current-branch.sh`) and confirm that the resulting pipeline run has the sensible metadata
Unfortunately the pr merge one is untestable without merging a pr. I guess 'trust me'?
=> BAU: add metadata that codepipeline understands

.github/workflows/deploy-api-modules-dev.yml, .github/workflows/deploy-api-modules.yml
AWS can't handle non-ascii characters in S3 metadata, so strip them out
- Code review
=> BAU: strip non-ascii characters from metadata

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
The lambdas create a lot of new redis connections each time they are invoked.  These conections are not closed explicitly.  We can improve the management of these connections by moving their creation to the lambda runtime init phase.
=> AUT-2701: Improve management of redis connection resources in lambdas.

template.yaml
Added kms key for sns topic, and added permissions for cloudwatch to decrypt it so alarms can trigger the lambda
=> ATO-851: Add kms key for sns events

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
Clear internal user id when switching users mid-journey.
When starting a sign-in journey with one email, then abandoning and switching to another email in order to create an account, the user id for the first email rather than the second email is recorded in an audit event.
1. Code Review
Steps to reproduce the issue in staging:
1. You need an existing account and an email that doesn't have an account so you can set one up.
2. Start a journey from the stub and enter the email for the existing user.
3. Stop on the enter password screen and do not enter a password.
4. Go back using the 'back' link.
5. Enter the new email to create an account and then continue.
6. Create a password then continue.
7. Add an mfa to complete creating the account.
Before the fix in this scenario the …
=> AUT-2903: Clear internal user id when switching users mid-journey

ci/terraform/oidc/api-gateway-frontend.tf, ci/terraform/oidc/kms-policies.tf, ci/terraform/oidc/mfa-reset-jar-jwk.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetJarJwkHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetJarJwkHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/JwksService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/JwksServiceTest.java
Adds a new JWKs endpoint to the Auth frontend API for the re-authenticate JAR signing key for MFA reset. 
- Deployed to sandpit, endpoint at https://auth.sandpit.account.gov.uk/.well-known/reverification-jwk.json, all looks fine
=> ATO-737 jwks endpoint for jar signing

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientSignatureValidationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/ClientSignatureValidationException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtAuthPublicKeySelector.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidator.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactory.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactoryTest.java
- Added ClientSignatureValidationService to validate RP signed JWTs
- Refactored RequestObjectAuthorizeValidator and PrivateKeyJwtClientAuthValidator to use ClientSignatureValidationService
Code Review
=> ATO-693: Refactor Client JWT Signature Validation Into Service

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, shared/src/main/java/uk/gov/di/audit/AuditContext.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java, test-services-api/src/main/java/uk/gov/di/authentication/testservices/lambda/DeleteSyntheticsUserHandler.java, test-services-api/src/test/java/uk/gov/di/authentication/testservices/DeleteSyntheticsUserHandlerTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
Conversion of all remaining authentication code to use the new method of calling the audit service, which gets an audit context passed through to it in order to clean up some of the calling code and tests.
Removes the old method, as our conversion is now complete!
An example PR where we've done this conversion most recently: https://github.com/govuk-one-login/authentication-api/pull/4848
=> BAU: Final conversion of all handlers to the new audit service method

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/ClientRedirectUriValidationException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/ClientRegistryValidationException.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/ClientRedirectUriValidationException.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/ClientRegistryValidationException.java
We're getting a lot of alarms go off in integration due to invalid redirect uri's being provided - we should return 400 rather than 500. Also renamed exception to make it clearer what case we are returning 400 in.
=> ATO-887: Return bad request when redirect uri is invalid

ci/terraform/account-management/read_secrets.sh, ci/terraform/auth-external-api/read_secrets.sh, ci/terraform/oidc/read_secrets.sh, ci/terraform/shared/read_secrets.sh, ci/terraform/test-services/read_secrets.sh, ci/terraform/utils/read_secrets.sh, scripts/read_secrets__main.sh
This reverts commit 74bc0c90b78415912b48e414a2fe8c8e9f321a07.
We think this might have broken the acceptance tests in the pipeline, so this is an attempt to see if it fixes.
=> Revert "BAU: use batch-get-secret-value in read_secrets.sh"

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/DeletedAccountIdentifiers.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/LegacyAccountDeletionMessage.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AwsSnsClient.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/ManualAccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/ManuallyDeleteAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/ManualAccountDeletionServiceTest.java, ci/terraform/account-management/manually-delete-account.tf, ci/terraform/account-management/variables.tf, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
We need to post a message to the SNS topic owned by the Home team when an account is manually deleted so other programme components can action it, e.g. EVCS and AIS.
=> ATO-824: Update manual account deletion lambda to send message to SNS

ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/staging.tfvars
Switches on calls to the TICF CRI in integration.
Note that since this is done in a "fire and forget" way (async lambda invocation), there should be negligible impact on user journeys.
Also reduces the http timeout for the call to the TICF CRI in staging. We're working on bringing this down further, but we no longer need it to be this high. Note that the integration timeout will be the default of 2 seconds so we can observe behaviour (but again, these timeouts will not affect user journeys).
=> Aut 2498/switch on ticf feature flag

ci/terraform/oidc/variables.tf, ci/terraform/utils/variables.tf
Bumps the Terms and Conditions version number for changes relating to Dynatrace. 
1. Code Review
This bump is in relation to updates in the following PRs:
- https://github.com/govuk-one-login/authentication-frontend/pull/1704
- https://github.com/govuk-one-login/authentication-frontend/pull/1784
=> AUT-2906: Bumps Terms and Conditions version number

.github/workflows/deploy-orch.yml, template.yaml
Before SAM was in charge of building the gradle project. This mean that no caching was done, and dependencies were downloaded and compiled multiple times. This change manually compiles all of then required modules which gives us more control over the process and takes several minutes off a deploy. This is significant in all envs, but most of all in dev where this should really shorten the feedback cycle
=> BAU: use gradle build raher than SAM controlled to improve caching and speed

ci/terraform/shared/sqs.tf
During deployments of `authentication-check-experian` we sometimes see warnings when deploying a SQS Lambda trigger from this queue. The error warns that the lambda timeout is more than the visibility timeout of the queue.
For example `Resource handler returned message: "Invalid request provided: Queue visibility timeout: 30 seconds is less than Function timeout: 45 seconds`
The visibility timeout should be more than the lambda timeout, to prevent a second lambda being triggered by the same message while the first is still processing it.
This increases the queue visibility timeout past the lambda timeout of 45 seconds.
See the value is more than is set as the lambda timeout at https://github.com/govuk-one-login/authentication-check-experian/blob/f4319a15cebeff8299c4d1e5fb9ba778cd00c02d/dep …
=> BAU: Increase visibility timeout for pending_email_check_queue

ci/terraform/shared/variables.tf
Bumps Ts and Cs version in shared variables. This variable should have been included with the PR #4889 but was missed. I have updated the guidance for updates to include this specific file and to explain it's worth searching for the variable name when making updates.
1. Code Review
2. Review the guidance for deploying a new Ts and Cs version to confirm updates make sense
https://github.com/govuk-one-login/authentication-api/pull/4889
=> AUT-2906: Bump Ts and Cs version in shared variables

account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java
We were not correctly sending the persistent session ID in the audit context. This is because persistentSessionId was never being reassigned after initially being assigned to null, instead incorrectly calling the extractPersistentIdFromHeaders and assigning the result to ipAddress var.
This fixes that and makes sure that they are tested in the audit context
1. Code Review
=> AUT-3373: Fixed incorrect DELETE_ACCOUNT audit context

oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AuthenticationCallbackValidationException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/LogoutReason.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
- Refactored Logout Service / Logout Handler to destroy session in Logout Service rather than Logout Handler.
- Pass Reauthentication Failures To RP
- Add "logout reason" extension to LOG_OUT_SUCCESS audit event.
Code Review
=> ATO-732: Pass Reauthentication Failures to RP

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java
Back channel logout failures to POST do not record the error message, and also do not end up on the DLQ since the exception is not thrown. This PR reverses this.
=> INCIDEN-869: Add more information to backchannel logout failures

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/NotifyDeliveryReceipt.java, delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
Change the `NotifyDeliveryReceipt` `completedAt` and `sentAt` fields to not required, allowing for `null` values that are can be sent by Notify.
https://docs.notifications.service.gov.uk/rest-api.html#delivery-receipts
We do not use the values anywhere, but errors were being thrown by the object mapper when values were expected but not found.
1. Code Review
=> AUT-3412: Ensure null values in Notify Delivery Receipts are handled correctly

.github/workflows/call_build-single-api-module.yml, .github/workflows/contract-tests.yml, .github/workflows/dependency-review-on-pr.yml, .github/workflows/dependency-submission.yml, .github/workflows/deploy-api-modules-dev.yml, .github/workflows/deploy-api-modules.yml, .github/workflows/pre-commit.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/sonar-analysis-on-merge.yml
Improve dependency caching across our GHA workflows.
This will hopefully ensure that we retain a slightly more stable set of transitive dependencies and will reduce the number of unexpected rebuilds. Additionally, it will ensure that all subprojects receive the same set of cached dependencies.
Additionally, i've introduced dependency submission / review workflows - details in the commit.
Finally, use corretto instead of temurin, to ensure we are replicating the runtime environment as closely as possibly.
- Ensure workflows have all successfully run on this branch
- Ensure that `deploy-api-modules-dev` workflow runs successfully against this branch. [I've already run this](https://github.com/govuk-one-login/authentication-api/actions/runs/9892363244), but it would likely be worth running …
=> BAU: Better GHA gradle caching

scripts/export-ics.sh
Updated export-ics.sh script to only run when the email address specified exists in the database. Previously the script would generate the same pwid whenever an email address did not exist.
1. Code Review
2. Pull down export-ics.sh script
3. Run the script with an email address that is known to exist in the environment db
e.g. gds aws digital-identity-dev/scripts/export-ics.sh existing-email-address build
ID generated
4.  Run the script with an email address that does NOT exist in the environment db
e.g. gds aws digital-identity-dev/scripts/export-ics.sh unknown-email-address build
ID not generated
=> AUT-2298 - updated script to only run when email address exists in db

.gitignore, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/RpPublicKeyCacheServiceIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientSignatureValidationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RpPublicKeyCacheExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/RpPublicKeyCache.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/JwksException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RpPublicKeyCacheService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidator.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java, template.yaml
Enable fetching, caching, and retrieval of an RP public key that is served on a JWKS endpoint.
The first several commits are for setup.
The actual code to fetch / cache / retrieve the key is introduced in 1ab172b.
1. For now code review only, easiest commit-by-commit
Has been tested in dev with a dummy JWKS URL and a hard-coded `kid` value. Validation obviously fails but keys can be fetched from the URL, and cached and retrieved from the DB successfully.
I wanted to raise this PR now, but still have a few things to do:
PR which introduced FetchJwksFunction: https://github.com/govuk-one-login/authentication-api/pull/4747
=> ATO-694: Fetch and cache RP public key from JWKS URL

template.yaml
This was previously applied but [reverting](https://github.com/govuk-one-login/authentication-api/pull/4937) back to provisioned concurrency caused the orch pipeline to fail
=> BAU: Enable snapstart on FetchJwksFunction

.gitignore, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/RpPublicKeyCacheServiceIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/FetchJwksHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientSignatureValidationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RpPublicKeyCacheExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/RpPublicKeyCache.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/JwksException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RpPublicKeyCacheService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidator.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java, template.yaml
_Note this is a follow-up PR after the original was reverted: https://github.com/govuk-one-login/authentication-api/pull/4937_
Enable fetching, caching, and retrieval of an RP public key that is served on a JWKS endpoint.
The first several commits are for setup.
The actual code to fetch / cache / retrieve the key is introduced in [dcb3675](https://github.com/govuk-one-login/authentication-api/pull/4939/commits/dcb367564625e0b0e20e887f734a434bc57a81bc).
1. For now code review only, easiest commit-by-commit
Has been tested in dev with a dummy JWKS URL and a hard-coded `kid` value. Validation obviously fails but keys can be fetched from the URL, and cached and retrieved from the DB successfully.
PR which introduced FetchJwksFunction: …
=> ATO-694: Fetch and cache RP public key

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/build/vpc/parameters.json
Set parameters to allow (in build env):
- communication with AWS Lambda API
- Lambda as a service in the permissions boundary
Note that merging this PR will not trigger deployment of these stacks as that is handled manually. In this case the stacks will be updated in the AWS console, and this PR is just to keep the code up to date.
https://github.com/govuk-one-login/authentication-api/pull/4939
=> ATO-694: Set build VPC and pipeline parameters

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationServiceTest.java
Previously, when PublicKeySource = static and PublicKey is not provided, a NullPointerException was thrown. Instead throw more useful ClientSignatureValidationException with error message.
1. Code Review only
=> ATO-694: Throw ClientSignatureValidationException when PublicKeySource is static but PublicKey is null

ci/stack-orchestration/configuration/integration/integration-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/integration/vpc/parameters.json, ci/stack-orchestration/configuration/production/production-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/production/vpc/parameters.json, ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/staging/vpc/parameters.json
Set parameters to allow:
- communication with AWS Lambda API
- Lambda as a service in the permissions boundary
Note that merging this PR will not trigger deployment of these stacks as that is handled manually. In this case the stacks will be updated in the AWS console, and this PR is just to keep the code up to date.
https://github.com/govuk-one-login/authentication-api/pull/4939
=> ATO-928: Set staging, integration, production VPC and pipeline parameters 

pyproject.toml, scripts/_set_up_sso.py
Our AWS accounts are commonly created with the roles
`AWSAdministratorAccess` and `ReadOnlyAccess`. The script will now
preferentially create profiles with these roles if they exist, and
ignore the 'old' role naming.
If these new roles do not exist, the script will fall back to the old
'does role end with xxx' logic.
- Code review
- Run the script, ensure that the roles you expect are present afterwards
- Attempt to use one of the modified profiles, ensure that it works.
=> BAU: Update set-up-sso with new role names

ci/terraform/oidc/auth-code.tf, ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/authorize.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/jwks.tf, ci/terraform/oidc/logout.tf, ci/terraform/oidc/register.tf, ci/terraform/oidc/storage-token-jwk.tf, ci/terraform/oidc/token.tf, ci/terraform/oidc/trustmarks.tf, ci/terraform/oidc/userinfo.tf, ci/terraform/oidc/wellknown.tf
Disable provisioned concurrency of old lambdas.
This a quick way to reduce running costs on lambdas that are no longer in use
=> ATO-911: Disable provisioned concurrency of old lambdas

.github/workflows/call_get_pr_data.yml, .github/workflows/deploy-api-modules-dev.yml, .github/workflows/deploy-api-modules.yml
Rather than duplicating the same step in both prod and dev workflows,
move it to a reusable workflow instead.
Also, use the short commit sha in the summary, to reduce the length of
the string in AWS - it is annoying when it's truncated. For the same
reason, swap the order of PR number and repository name - so we
front-load as much 'useful' stuff as possible.
- Code Review
- Run the dev deploy pipeline from this branch and ensure that the metadata is present. [done once here](https://github.com/govuk-one-login/authentication-api/actions/runs/10110652880).
=> BAU: Move pr-data to reusable workflow

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/build.gradle, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/IncorrectRedirectUriException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/InvalidAuthenticationRequestException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/MissingClientIDException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/MissingRedirectUriException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorisationServiceTest.java
We are currently throwing exceptions when a user sends a bad request to the authorise endpoint that can't be parsed properly. This PR classifies the parse exceptions, and then returns a bad request which is what the OIDC spec recommends when there is not enough information to redirect back. 
I've tried to make the changes commit by commit, so probably worth checking these
=> ATO-917: Return bad requests in authorisation handler for incorrect requests

account-management-api/src/main/resources/log4j2.xml, auth-external-api/src/main/resources/log4j2.xml, auth-external-api/src/test/resources/log4j2.xml, client-registry-api/src/main/resources/log4j2.xml, delivery-receipts-api/src/main/resources/log4j2.xml, doc-checking-app-api/src/main/resources/log4j2.xml, frontend-api/src/main/resources/log4j2.xml, interventions-api-stub/src/main/resources/log4j2.xml, ipv-api/src/main/resources/log4j2.xml, oidc-api/src/main/resources/log4j2.xml, oidc-api/src/test/resources/log4j2.xml, orchestration-shared/src/test/resources/log4j2.xml, shared/src/test/resources/log4j2.xml, test-services-api/src/main/resources/log4j2.xml, utils/src/main/resources/log4j2.xml
Update Log4j logging format to replace deprecated JsonLayout.
This needs to be tested in build, so deployment promotions to higher envs will be paused.
Documentation 
https://docs.powertools.aws.dev/lambda/java/core/logging/#upgrade-to-jsontemplatelayout-from-deprecated-lambdajsonlayout-configuration-in-log4j2xml
https://logging.apache.org/log4j/2.x/manual/json-template-layout.html
=> ATO-877: Update Log4j logging format to replace deprecated JsonLayout

.gitignore
Gitignore file entry added to ignore pact test outputs was ignoring java class files in `orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/pact/`.
Code Review
=> BAU: Fix Lambda HTTP Server Git Ignored

integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthenticationAttemptsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationAttemptsStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthenticationAttempts.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthenticationMethod.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthenticationType.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthenticationAttemptsService.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/AuthenticationAttemptsTest.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/AuthenticationMethodTest.java
AUT-3368 and AUT-3369.
Transitioned the storage medium for TTL variables from Redis to DynamoDB. This required introducing the DynamoAuthenticationAttemptsService class and creating new DynamoDB tables to handle authentication codes and counts with TTL constraints.
Added logic for CRUD Operations: 
- Create: Add new codes and counts.
- Read: Retrieve codes and counts.
- Update: Modify existing codes and counts.
- Delete: Remove codes and counts.
Added a new integration test class to verify the functionality of CRUD operations and TTL management with DynamoDB.
=> Aut 3368/auth attempts store

ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
In the reauth journey, we want to redirect the user to the client redirectUri when he enters six invalid otp codes, instead of locking them out for six hours. This requires the BE not to implement a 2hr lock in the BE after 6 incorrect attempts.
1. Code Review
https://github.com/govuk-one-login/authentication-frontend/pull/1829
=> AUT-2788: implement logout instead of lockout for mfa in reauth

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Replaces [this PR ](https://github.com/govuk-one-login/authentication-api/pull/4952) (I was having some gnarly git issues attempting to push to that branch)
Fixes a field on audit events for mfa codes which was always set to zero.
We were previously setting the "loginFailureCount" field based on a field on the session that is no longer used: https://github.com/govuk-one-login/authentication-api/commit/924bff0fdc2d4d793143df6f59f019b01cdf3caa. This meant that the count stayed at zero on audit events, despite repeated failures.
This fixes this, and also removes the getter so that this cannot cause future confusion.
I'm not sure about the implications of removing the field entirely from the session - will this cause any deserialisation errors?
1. Code Review
=> Bau: fix login attempts in audit events

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java, ci/terraform/account-management/send_otp_notification.tf, ci/terraform/oidc/check-email-fraud-block.tf, ci/terraform/oidc/send_notification.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
We currently send email check requests when a user enters a new email address in both account creation and account management (in practice this happens when we send the OTP email to the user).
We now check to see if we already have a result cached from a previous recent check, and if so we do not raise another request.
Only when no cached result exists for the email address do we request a new check.
This means allowing the notification lambdas access to the table. This is done by giving the lambda roles access to read, encrypt and decrypt the email check result table:
- Encrypt is given in this policy, but no ability to write.
- Policies:
- `local.email_check_results_encryption_policy_arn`
- `aws_iam_policy.check_email_fraud_block_read_dynamo_read_access_policy.arn`
A lambda role was …
=> AUT-3500: Use cached email check results

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/NotifyDeliveryReceipt.java, delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java, delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
It's useful for us to be able to see the length of time it's taken notify to successfully send out emails and texts as it gives us visibility as to whether there are any widespread issues when reports of slow sms / emails come to us, and notify already give us this information via their delivery receipts. This will also aid us in identifying, in the case of a widespread issue, whether the problem is on our side (e.g. delayed async processing) or on Notify's.
Notify send us ([docs link](https://docs.notifications.service.gov.uk/java.html#delivery-receipts)):
* created at timestamp
* completed at timestamp
* sent at timestamp
I think the relevant time difference here is the duration between created at (when notify sends the request to its deliverer partners) and updated at (which for a …
=> Bau: add metric for notify delivery durations

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/LogoutRequest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/entity/LogoutRequestTest.java
An invalid URL should be handled like any other input error.
It would have likely been sufficient to keep the url empty on the request object in the case the provided value did not match the client registry, but the chosen approach also protects against bad values in the client registry.
=> ATO-952: Parse post logout url as part of validation

ci/terraform/account-management/build-overrides.tfvars, ci/terraform/account-management/sandpit.tfvars, ci/terraform/account-management/send_otp_notification.tf, ci/terraform/account-management/staging-overrides.tfvars, ci/terraform/account-management/variables.tf, ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/site.tf, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/utils/build-overrides.tfvars, ci/terraform/utils/sandpit.tfvars, ci/terraform/utils/staging-overrides.tfvars, ci/terraform/utils/variables.tf
Enables the `support_email_check_enabled` feature switch in all environments which enables the API side logic for handling email checks during account creation and email address updates.
1. Code Review
https://github.com/govuk-one-login/authentication-frontend/pull/1898
=> AUT-2932: Enable email address checks

ci/terraform/interventions-api-stub/dynamodb.tf, ci/terraform/interventions-api-stub/variables.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/variables.tf, ci/terraform/ticf-cri-stub/dynamodb.tf, ci/terraform/ticf-cri-stub/variables.tf
Enable deletion protection for all dynamodb tables. This is configured
via variables, which default to true (enabled) for all service tables,
and false for stub tables.
Previously, we had terraform's lifecycle.prevent_destroy set for all tables, but this wouldn't prevent accidental deletion from the API or console (ie. outside of terraform).
- Code review
- Sanity check if a variable makes sense here, or if it should be hardcoded.
=> BAU: Enable DynamoDB deletion protection

integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
Added `isActive` property to `ClientRegistry`, which defaults to true if it is null.
If an RP is not active, redirect back to RP with unauthorised user error.
1. Code Review
2. Deploy and check that the authentication journey is unchanged by default and when `isActive` is true, but fails with a redirect and descriptive message when `isActive` is false.
=> ATO-522: add ability to disable RPs

docs/diagrams/orchestration/identity/identity.mmd
`/useridentity` is incorrect, should be `/user-identity`
=> BAU: Correct user identity path in mermaid diagram

utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java
The duration sent to cloudwatch is incorrect so this is some temp logging to debug.
=> AUT-3523: Add temporary logging for initial request time

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandlerTest.java
We record how long an email request takes and record this as a cloudwatch metric, so we can monitor performance.
This is currently logging incorrect durations. This is because we [currently treat the value we put on the initial event as seconds](https://github.com/govuk-one-login/authentication-api/blob/31f4300b17b7d029d632fa3391cb02a17b3642ba/frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java#L323), but when we work out the duration when it comes back, it is [compared to a time in milliseconds](https://github.com/govuk-one-login/authentication-api/blob/31f4300b17b7d029d632fa3391cb02a17b3642ba/utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java#L70) (getTime returns milliseconds since 1970). This …
=> Aut 3523/fix duration metric

integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthenticationAttemptsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationAttemptsStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthenticationAttempts.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BaseDynamoService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthenticationAttemptsService.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/AuthenticationAttemptsTest.java
Add dynamoDb range key to the AuthenticationAttempt table. This way, the primary key of the table will be composed of 
a partition key: internalSubjectID
and a composite range key: mfaMethd + journeyType
1. Code Review
=> AUT-3497: primaryKey refactoring to use partition and sort keys

utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java
This reverts commit 61c9886b23750697050437a7842cd1c48cf39e31.
Reverts some temporary logging that we added to debug why we were getting odd looking request durations for a cloudwatch metric. This was fixed [here](https://github.com/govuk-one-login/authentication-api/pull/5026), and so the logging can now be removed.
=> Revert "AUT-3523: Add temporary logging for initial request time"

ci/terraform/oidc/check-reauth-user.tf
A lambda role was declared for the lambda, but was not in use. This corrects the role used by the lambda and adds the required missing policies to the existing role:
- Access to read, encrypt and decrypt the client registry table.
- So client session data can be added to logs and audit events
- Encrypt is given in this policy, but no ability to write.
- Policies:
- `aws_iam_policy.dynamo_client_registry_read_access_policy.arn`
- `local.client_registry_encryption_policy_arn`
1. Code Review
1. Deploy to a dev environment
1. Follow ["How to trigger reauthentication" guidance](https://govukverify.atlassian.net/wiki/spaces/LO/pages/4317446229/How+to+trigger+reauthentication)
1. See you can successfully reauth
=> BAU: Correct access lambda role for `check-reauth-user`

ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/dev.tfvars, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/variables.tf, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationAttemptsStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthenticationAttemptsService.java
Being able to control where the upcoming reauth changed to the shared module gets deployed to will be important. Upcoming database and service changes should only be deployed to dev environments for the time being.
We will need to encrypt data stored in the upcoming `authentication-attempt` table. This is outputted in terraform state so it can be used by the OIDC module.
For the reauth work we are refactoring how we store auth codes and counts. This table will store them going forward.
- It is encrypted and has a ttl attribute defined (allowing DynamoDB native record removal once a code or count has expired).
- We pay per request for this table until we know our workload. Then we can think on moving to provisioned capacity.
- The `InternalSubjectId` attribute is the hash key for the …
=> AUT-3370: Create `authentication-attempt` DynamoDB table, KMS key and access policies

ci/terraform/oidc/mfa.tf, ci/terraform/oidc/send_notification.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
- Remove user's lockout action from requesting too many sms code
=> Aut-3046: Remove user lockout from requesting too many sms code

ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthenticationAttemptsStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthenticationAttemptsService.java
We will need to encrypt data stored in the upcoming `authentication-attempt` table. This is outputted in terraform state so it can be used by the OIDC module.
For the reauth work we are refactoring how we store auth codes and counts. This table will store them going forward.
- It is encrypted and has a ttl attribute defined (allowing DynamoDB native record removal once a code or count has expired).
- We pay per request for this table until we know our workload. Then we can think on moving to provisioned capacity.
- The `InternalSubjectId` attribute is the hash key for the table.
- The `AuthMethodJourneyType` attribute is the range key for the table.
- Point in time recovery is also enabled, with the consideration that while this table holds temporary data, the counts specifically form …
=> AUT-3370: Create authentication-attempt DynamoDB table, KMS key and access policies

ci/stack-orchestration/configuration/dev/dev-orch-be-pipeline/parameters.json
Configure dev-orch-be-pipeline for all-at-once lambda canary deployment. See [guide](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3823436177/Lambda+-+Canary+Deployment+Migration+Guidance#Pipeline) (under Pre-requisites heading) which describes this config. 
Currently the value is "none":
Note that merging this won't actually update the pipeline with the new parameter as deploying the pipeline is done manually. This code change is just for reference.
A further PR will configure dev Orch lambdas to use all-at-once deployment.
Check I've followed the guide correctly.
=> ATO-954: Configure dev-orch-be-pipeline for all-at-once lambda canary deployment

template.yaml
Configure Orchestration dev lambdas to use AllAtOnce canary deployment. This has been deployed to Orchestration dev successfully, and the deployments for each lambda are visible in CodeDeploy:
The dev-orch-be-pipeline has been updated so parameter `LambdaCanaryDeployment = AllAtOnce`. This sets the value of `LambdaDeploymentPreference` in template.yaml `Parameters` via [parameter overrides](https://github.com/govuk-one-login/devplatform-deploy/blob/9f9661351d8c3ff32afc9f6ad40888b050fbc0a6/sam-deploy-pipeline/template.yaml#L5425). 
Note that `LambdaCanaryDeployment = None` does **not** feature flag canary deployments, ie. canary deployments will be enabled when `LambdaCanaryDeployment = None` and `canaryDeploymentEnabled: true` (defaulting to `AllAtOnce`).
This has also been deployed to …
=> ATO-990: Configure Orchestration dev lambdas to use AllAtOnce canary deployment

template.yaml
- The parameter needs to be set, otherwise deployments fail with `Parameters: [LambdaDeploymentPreference] must have values`
=> ATO-954: Set default value for LambdaDeploymentPreference

shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java
Delete the unused method in shared authentication `createSession`. This should only be called in Orchestration, so this PR deletes it for clarity that this should not be used by authentication.
This is raised now, as `createSession` in orchestration would be out of sync with authentication's version as a result of https://github.com/govuk-one-login/authentication-api/pull/5053. Instead of updating it, we delete it instead.
1. Code Review
=> BAU: delete unused auth createSession

ci/stack-orchestration/configuration/build/build-orch-be-pipeline/parameters.json
Configure build-orch-be-pipeline for all-at-once lambda canary deployment.
Note that merging this won't actually update the pipeline with the new parameter (deploying the pipeline is done manually), this is just for reference.
Equivalent PR for dev: https://github.com/govuk-one-login/authentication-api/pull/5052
=> ATO-991: Configure build-orch-be-pipeline for all-at-once lambda canary deployment

template.yaml
Enable canary deployments in build
Build pipeline parameter has been updated (LambdaCanaryDeployment: AllAtOnce), see https://github.com/govuk-one-login/authentication-api/pull/5075/files
=> ATO-991: Enable canary deployments in build

integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/CookieHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/CookieHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SessionServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java, template.yaml
Adds a browser session id to cookie, and stores it in Redis. This can be used to check that a user hasn't closed their browser, and use this to have them only signed in with that browser.
Currently nothing is done with the browser session id, so there is no functional change. It is also feature flagged to true only on dev.
1. Code Review
=> ATO-964: create new browser session cookie

ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json
Configure staging-orch-be-pipeline for all-at-once lambda canary deployment.
Note that merging this won't actually update the pipeline with the new parameter, this is just for reference. Deploying the pipeline is done manually, and will be done after this is merged.
Equivalent PR for:
- dev: https://github.com/govuk-one-login/authentication-api/pull/5052
- build: https://github.com/govuk-one-login/authentication-api/pull/5075
=> ATO-992: Configure staging-orch-be-pipeline for all-at-once lambda canary deployment

build.gradle
Addressed vulnerabilities that have been raised by dependabot for netty, Guava and Apache Commons
1. Code Review
=> AUT-3433: Depandabot vulnerabilities addressed

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/ClientRegistryTest.java
Make nonce optional for auth only rps. This is because several RPs identity platforms don't support Nonce out of the box.
=> ATO-936: Make nonce optional for auth only rps

template.yaml
Enable canary deployments in staging
Build pipeline parameter has been updated (LambdaCanaryDeployment: AllAtOnce), see https://github.com/govuk-one-login/authentication-api/pull/5079
=> ATO-991: Enable canary deployments in staging

ci/stack-orchestration/configuration/integration/integration-orch-be-pipeline/parameters.json
Configure integration-orch-be-pipeline for all-at-once lambda canary deployment.
Note that merging this won't actually update the pipeline with the new parameter, this is just for reference. Deploying the pipeline is done manually, and will be done after this is merged.
Equivalent PR for:
- dev: https://github.com/govuk-one-login/authentication-api/pull/5052
- build: https://github.com/govuk-one-login/authentication-api/pull/5075
- staging: https://github.com/govuk-one-login/authentication-api/pull/5079
=> ATO-993: Configure integration-orch-be-pipeline for all-at-once lambda canary deployment

template.yaml
Enable canary deployments in integration
Integration pipeline parameter has been updated (LambdaCanaryDeployment: AllAtOnce), see https://github.com/govuk-one-login/authentication-api/pull/5084
=> ATO-993: Enable canary deployments in integration

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
Reverts govuk-one-login/authentication-api#5041
=> Revert "ATO-489: Remove resource field in token request to IPV"

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
- Added a null check for the session's `browser-session-id`, so that if it's null, nothing is sent back in the cookies. This means if a user is already in an existing session when this change is deployed, their journey will continue unaffected - only new journeys will have a browser session id be created.
- Added tests for expected journeys through `/authorize` for specifically browser session ids. Currently, browser session id has essentially no effect on the journey, so these will need updating in ATO-967
1. Code Review
=> ATO-964: add tests for different journeys

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
Re-applies  https://github.com/govuk-one-login/authentication-api/pull/5041 which was initially reverted out of caution, due to not being able to run through the identity journey in staging. However this issue was unrelated and the logs indicated the token request to IPV was successful
=> Re-apply: ATO-489: Remove resource field in token request to IPV

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/CookieHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/CookieHelperTest.java
Replaces the header cookie 'browser-session-id' with 'bsid', to match other gov.uk cookie names and to make it less obvious what its role is.
1. Code Review
=> ATO-964: replace 'browser-session-id' with 'bsid' in cookies

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
Instead of setting the bsid cookie domain to `account.gov.uk`, we set it to `oidc.account.gov.uk` so we're not passing it around to services that don't need it.
Deployed to dev and tested: `configurationService.getOidcDomainName()` gives the domain `oidc.sandpit.account.gov.uk` as expected.
1. Code Review
=> ATO-964: set domain of bsid cookie to be OIDC specific

build.gradle
Use JRE to get optimisations not available in android. Use version notation to capture intent: we don't want to constrain the version of transitive dependencies down, just ensure they are more recent than the vulnerable version
=> BAU: Update guava to JRE version

template.yaml
Enable canary deployments in production
Production pipeline parameter has been updated (LambdaCanaryDeployment: AllAtOnce), see https://github.com/govuk-one-login/authentication-api/pull/5124
=> ATO-994: Enable canary deployments in production

template.yaml
Canary deployments are now enabled in all envs, so:
- Remove default value of `LambdaDeploymentPreference` so that this value is controlled by the pipeline parameter `LambdaCanaryDeployment`.
- Remove redundant `canaryDeploymentEnabled` feature flag.
This will be checked in build before promotion to higher envs.
=> ATO-995: Canary deployments cleanup

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Adds a condition to bsid metrics logging to only do when the session already exists. This means we're only checking journeys affected by the feature, not new ones that won't be changed.
1. Code Review
=> ATO-966: only log bsid metrics when session exists

doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/contract/DcmawUserInfoTest.java
`unorderedMinArray` was causing problems in the doc-app pact test as it is a V4 matcher when the pact specifies V3
=> BAU: update array matcher in doc app pact test

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
This PR adds logic that deletes email and password authentication attempt counts when a user goes through the normal sign in journey. Previously, authenticating in this way would not effect counts when they should have been being reset.
The ticket states there was an issue with users being able to use silent logins to reset their email and password counts without re-authenticating, however when testing this was not a problem and counts were not being reset.
For silent log in (to check the issue outlined in the ticket is not there, no code changes in this PR associated with silent login):
1. Go through sign in journey with isAuthenticationAttemptsServiceEnabled == true
2. Go through re-authentication journey up to enter password screen
3. Enter wrong password X number of times and check …
=> AUT-3529: Delete email & password counts on authentication

build.gradle
Guava is referenced from several configurations, including build environment configurations via plugins. Pin it everywhere.
=> BAU: Pin Guava correctly

ci/terraform/shared/iam.tf
Cross account role for new build aws account to access dynamo db table only for Build Account 
Solution to allow new SAM pipeline to access Dynamo DB table for acceptance test 
1. Code Review
=> Cross account role for new build aws account to access dynamo db table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
This PR adds logic that deletes email and password authentication attempt accounts when a user
goes through the normal sign in journey. Previously, authenticating in this way would not effect
counts when they should have been being reset.
The original PR was reverted to rule it out as a cause for pipeline flakiness. Since it has been ruled out as a cause we are going to merge again
=> Revert "Revert "AUT-3529: Delete email & password counts on authentication""

ci/terraform/oidc/start.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UserStartInfo.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelperTest.java
Returns reauth lock information from the start handler if the feature flag to use the new authentication attempts service is on.
Also removes the existing deletion of the counts, since we are going to retain these in order to return blocked information.
This is currently unused on the frontend, but a subsequent PR will respond on the frontend in the case of a reauth journey where someone is blocked.
How I've tested this (you can choose to do the same or trust me):
1. Deploy to a test env, with the relevant reauth feature flags on
1. Open two different browsers. Log in in both
1. Start a reauth journey in one. Enter the wrong email or the wrong password to the point where you're logged out
1. Start a reauth journey in your other browser, just to the point …
=> Aut 3613/return reauth lock info from start handler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReauthUserHandlerAuthenticationAttemptsIntegrationTest.java
Currently, we only read from redis to get an incorrect password count in the reauth handler. As we switch over to dynamo, this will not be where we store this information. So this makes sure we read from the correct place, based on the feature switch
=> AUT-3613: Retrieve incorrect password count from auth attempts store when feature flag on

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AccessTokenService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/BaseDynamoService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AccessTokenServiceTest.java
Added a consistent read retry when querying the access token store. This is to remedy a suspected race condition where the access token store was not being populated before the query was happening. 
This retry strategy aims to fix this by performing a second query with strongly consistent reading (as opposed to eventually consistent reading). This second query happens with a higher latency and cost but ensures up to date DB data.
Have also added cloudwatch metrics incrementing a counter for attempted and successful access token queries for both standard initial reads (eventually consistent reads) and the consistent reads, allowing us to see how often queries are failing. 
See docs here: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html
1. …
=> AUT-3583: Added consistent read retry to access token store query

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
This PR implements the create or increment count logic into the verify code handler, incrementing the count for
ENTER_SMS_CODE in the authentication attempts table for a reauth journey when a user fails to enter the correct SMS MFA. If there is a count for a user having failed to enter the right sms mfa code and they then succeed, the count will be deleted.
A PR will follow implementing the corresponding logic for the auth app MFA in the verifyMfaCodeHandler.
1. Code Review
2.  Deploy changes to authdev1
3.  Go through reauth journey successfully up to entering SMS MFA
4. Enter an incorrect MFA and see the count in the authdev1-authentication-attempt table
5. Enter the correct MFA code and see that the count clears
=> AUT-3529: Added SMS code reauth attempt count

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
Create a new DynamoDB table which will be used to store the Auth session.
- Ensure table is setup correctly
- Ensure kms key is setup correctly
- Ensure policies allow correct access (and only from auth)
=> ATO-1005: Create dynamo table for auth session

ci/terraform/oidc/start.tf
- Orchestration will need to pass more information to Auth via API as part of splitting the shared session. Using POST means information can be passed in the body instead of headers.
- In order to safely switch from the auth frontend sending GET to sending POST, /start needs to accept both for a while. This is a temporary measure and will eventually be set to just POST.
This has been tested in dev / sandpit. 
ATO-984 incremental deployment:
1. https://github.com/govuk-one-login/authentication-api/pull/5171
2. https://github.com/govuk-one-login/authentication-frontend/pull/2006
3. https://github.com/govuk-one-login/authentication-api/pull/5172
4. https://github.com/govuk-one-login/authentication-api/pull/5174
5. Make /start only POST (PR todo)
=> ATO-984 (1/5): Configure /start to have GET and POST methods

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
We want users to be logged out on the 6th attempt at an incorrect email in reauth. This is currently happening, but the count in the database is stopping at 5, which means that eventually the data we put into audit events will be confusing.
In this change, we increment the count of failed emails regardless of whether the current incorrect attempt logs someone out or not. We also set the configured value of max retries to 6, rather than 5. Together, these changes should not change the behaviour observed (a user should still be logged out on the 6th incorrect attempt), but should:
a) make the logic more consistent - currently max email attempts is configured to 5, but max passwords is configured to 6, but in both cases we only get locked out on th 6th incorrect attempt
b) make sure the …
=> Aut 3613: Increment incorrect email count up to 6 in reauth

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Implemented the create or increment count logic into the verify mfa code handler, incrementing the count for ENTER_AUTH_APP_CODE in the authentication attempts table for a reauth journey when a journey with MFAMethodType.AUTH_APP fails. If there is a count for a user having failed to enter the right auth app mfa code and they then succeed, the count will be deleted.
This PR follows the related PR implementing the equivalent logic into the VerifyCodeHandler. This PR has also fixed an issue with the VerifyCodeHandler using the internal subject ID instead of the subject ID when interacting with the authentication attempts table.
Following this PR we will look to improve the robustness of the lambdas by implementing error handling, such as in the case of receiving a reauth request when reauth …
=> AUT-3529: Added Auth App reauth attempt count

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationAttemptsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationAttemptsService.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelperTest.java
Contains a refactor to the way we retrieve and check reauth counts, in order to:
* Make our code more flexible - this way, the calling code can decide what to do in the case of different exceeded counts, and later on it'll make life easier when we want to populate audit events with all counts.
* Make helpers contain static methods
Then, it updates the check reauth user handler to ensure that we're checking all reauth counts, and log a user out in the case of any that exceed the configured maximum.
=> Aut 3530: check all reauth counts in reauth handler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
When the User enters a MFA code in a re-authentication journey we should check that they are not locked out re-authenticating by checking their error counts.
We also check if a UserProfile is available and error out if not.
1. Code Review
=> Aut 3530/check reauth counts mfa

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Include `previousSessionId` as a claim in authorize request to Authentication. If there is no `previousSessionId`, no claim is added.
This is required in order to break session dependencies between Authentication and Orchestration. When Auth has its own session store, the hash key for the session will be `sessionId`. When `sessionId` gets updated, the record will need to be recreated, and in order to do this, Auth need to map the previous session ID to the new one (which will be extracted from the gs cookie).
Has been deployed to sandpit / dev along with the changes below. On first journey `previousSessionId` is `null` in StartHandler. On second journey it is the previous value of `sessionId`.
ATO-984 incremental deployment:
1. https://github.com/govuk-one-login/authentication-api/pull/517 …
=> ATO-984 (3/5): Add previousSessionId claim to authorize request to Authentication

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
- Sends the session id in the headers of the `/userinfo` request from orchestration to auth
- Adds some logging to log this sessionId if present in the headers of the request
- Tested by sequentially deploying in Orch dev, running through a journey and then deploying auth sandpit and running through again, all went fine!
=> ATO-981: Send sessionId to Auth `/userinfo` endpoint 

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/NotificationServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/BulkUserEmailSenderScheduledEventHandlerTest.java
The Notify API allows users to attach a [`reference`](https://docs.notifications.service.gov.uk/java.html#reference-required) to each API call.
We currently default this to an empty string but we can attach a journey id to it so that we are able to link delivery receipts to individual journeys.
This will help us diagnose when users are having issues such as SMS not being delivered.
This PR also adds some refactoring of the NotificationServiceTest.
=> BAU: Attach journey id to Notify messages as a reference

ci/terraform/oidc/start.tf
Remove GET method from Start lambda
GET is no longer in use. Authentication frontend is now POSTing to /start (see 2/5 below) so that session information can be transferred from Orchestration to Authentication in the request body.
Tested in sandpit and functioning as intended.
ATO-984 incremental deployment:
1. https://github.com/govuk-one-login/authentication-api/pull/5171
2. https://github.com/govuk-one-login/authentication-frontend/pull/2006
3. https://github.com/govuk-one-login/authentication-api/pull/5172
4. https://github.com/govuk-one-login/authentication-api/pull/5174
5. https://github.com/govuk-one-login/authentication-api/pull/5215
=> ATO-984 (5/5): Remove GET method from Start lambda

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
When a user makes an `/auth`, their bsid cookie must match the session id cookie, else the session is invalid. This means users are signed out on browser close. 
This feature is hidden behind a feature flag `isSignOutOnBrowserCloseEnabled`, which is different from the bsid cookie feature flag `isBrowserSessionCookieEnabled`, which will be rolled out ahead. `isSignOutOnBrowserCloseEnabled` is only turned on in dev and build (build so we can run the acceptance tests against it).
Using the metrics logging of  https://github.com/govuk-one-login/authentication-api/pull/5104, I have tested that on browser close, the `bsid` cookie does not persist on the user machine. When I attempt to sign back in, my cookie and the session's `bsid` therefore do not match, and I have to sign back in as …
=> ATO-967: new session on browser close using bsid

ci/terraform/oidc/ipv-handback-alerts.tf
Set treat missing to not breaching for ipv_handback alarm.
Having triggered the alarm has not resolved automatically even though there are no longer any errors.
See: https://governmentdigitalservice.pagerduty.com/incidents/Q1WNAUE0C0BA8O?utm_campaign=channel&utm_source=slack
1. Code Review, review of deployed branch in the dev environment
https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#alarmsV2:alarm/dev-P1-ipv-handback-alarm
=> INCIDEN-927: Set treat missing to not breaching for ipv_handback alarm

ci/terraform/oidc/build-overrides.tfvars
Switch off account_intervention_service_abort_on_error in build.
Matches production.  May fix the symptom of a failing flakey acceptance test.
1. Code Review
=> BAU: Switch off account_intervention_service_abort_on_error in build

ci/terraform/oidc/authentication-auth-code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/domain/FrontendAuditableEvent.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/AuthCodeRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java
Emits the AUTH_REAUTH_SUCCESS event in the case of a reauth journey that has reached the point of the authentication auth handler, with metadata of the pairwise id.
Note that this PR does not contain all the extensions required by the event schema - adding the incorrect counts will be done in a subsequent PR, since we'd like to do this by way of the new session stored in dynamo.
1. Code Review
This event will not be emitted until [this PR](https://github.com/govuk-one-login/authentication-frontend/pull/2067) is also merged on the frontend that adds the necessary information to the auth code request to indicate the journey is a reauth journey. This PR is safe to merge first.
=> Aut 3601/emit basic auth reauth success event

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/ReauthMetadataBuilder.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java
If the authentication attempts service is turned on, the reauth_failed audit event will
send in the event that a user has failed to reauthenticate successfully and has been
locked out of their account. This happens both in the case that a user has just been
locked out, or they have already been locked out and have failed to reauthenticate.
1. Code Review
=> AUT-3602: Add reauth_failed audit event in login handler

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, ci/terraform/auth-external-api/shared.tf, ci/terraform/auth-external-api/ssm.tf, ci/terraform/auth-external-api/userinfo.tf, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
- We're now setting the value of `isNewAccount` in the Auth userInfo lambda. This is a pre-requisite to splitting this value from the shared session store as currently Auth rely on Orchestration to update this in `AuthenticationCallBack` handler and `IPVCallBack` handler. We're setting it here as Auth need to start independently setting this value, and this point is closest to the end of the handoff between Auth and Orch, and closest to when it would be set by Orch.
- Soon we will co-set this value in the new Auth session store, before eventually migrating to the auth only store.
For example:
- Deployed to sandpit and ran through a journey, confirmed that the session is updated in the userinfo handler
=> ATO-981 set is new account in userinfo

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java, delivery-receipts-api/src/main/resources/log4j2.xml, delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
This follows from #5206 by using the reference ID in the log lines so we can match up deliveries with One Login journeys.
=> BAU: Add journey IDs to callback log lines

build.gradle
Since these child dependency versions were pinned, parent dependencies that used them have been updated to include the updated child dependencies.
They were pinned in the first place because they address vulnerabilities that were fixed in the child, but not the parent.
Removing the pinned versions when no longer needed improves maintainability.
1. Code Review
2. See the "Dependency review for pull requests / dependency-review" PR check is successful
=> BAU: Remove unneeded pinned child dependencies

ci/terraform/oidc/processing-identity.tf, template.yaml
Add JAVA_TOOL_OPTIONS environment variable to all lambdas, with the value:
- `-XX:+TieredCompilation -XX:TieredStopAtLevel=1` in production
- `-XX:+TieredCompilation -XX:TieredStopAtLevel=1 '--add-reads=jdk.jfr=ALL-UNNAMED'` in all other envs.
This is required for updating the dynatrace lambda layer version.
Note that the production value is the default (and current) value.
=> ATO-1029: Set JAVA_TOOL_OPTIONS env var in all Orchestration lambdas

.github/workflows/pre-merge-checks.yml, .github/workflows/sonar-analysis-on-merge.yml, build.gradle
PR to use 'sonar' instead of 'sonarqube' in pre merge checks. Sonarqube has been deprecated and it was complaining when pre-merge checks were running.
1. Code Review
=> BAU: Use sonar instead of sonarqube

template.yaml
The secret [had to be changed](https://govukverify.atlassian.net/browse/ATB-1835), which created a new version of the secret, which means the secret ID needs to be updated.
=> ATO-1045: Use new AIS URI secret ID in staging

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java
Adding timestamps to our existing logs for the start and end of the async email check process to help diagnose a potential issue on the `EmailCheckDuration` metric.
We're currently seeing 10 unaccounted for seconds in the async journey. After some analysis we're leaning to an issue with the `EmailCheckDuration` metric rather than those 10 seconds actually existing.
Adding these will allow a comparison with the value of the start and end times as recorded in the metric vs when the time the logs are recorded.
Once we're satisfied with the data gathered here in our logs this could be reverted.
1. Code Review
=> BAU: Add timestamps to bookend email check logs

integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
- Adds new attribute to session table, isNewAccount
- This is set with a default value of `UNKNOWN` when a session is created for the first time
- Have tested in the following way
- Deploy to a dev account (I did sandpit)
-  Go to the RP stub and make it to the login page (you can go further but the only backend lambda which write to the  
new session store is the start handler)
- Find your sessionId
- Have a look in the session table, you should see the value of `isNewAccount` set to unknown
- Come back again via the RP stub and observe the sessionId is updated and the isNewAccount state remains unknown
- Ran through a sign in journey because I'm paranoid
=> ATO-981: Set is new account at session start

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/AuthSessionException.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
In order to break the shared session dependency between Auth and Orch, session data are being moved to an Auth owned Auth session table.
There are three parts to breaking the `verifiedMfaMethodType` dependency, this PR is part a:
- ATO-979/a: VerifyCode & VerifyMfaCode: Set in Auth session
- ATO-979/b: UserInfoHandler: Get from Auth session and include in userinfo response
- ATO-979/c: AuthenticationCallbackHandler: Take from userinfo response and set in Orch session
This PR sets `verifiedMfaMethodType` in the Auth session, in the VerifyCode and VerifyMfaCode lambdas.
Note that we exceeded the quote of 20 policies per role, so as a workaround the read and write policies have been combined. Ticket to track requesting a quota increase: https://govukverify.atlassian.net/browse/ATO-1056
=> ATO-979/a: Set verifiedMfaMethodType in Auth session

ci/terraform/auth-external-api/authdev1.tfvars, ci/terraform/auth-external-api/authdev2.tfvars, ci/terraform/auth-external-api/dev.tfvars
orchstub to auth public signing key for authdev1, authdev2 and dev environments
Auth external API to trust the orch stub as well as the main orchestration
After deployment, callback journey from orchstub will be successful
=> AUT-3745 - New orch stub signing keys for development environments

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
Emit reauth_failed audit event in verifyMfaCodeHandler when user has too many pre-existing authentication attempts for any count.
Also tested that we return the correct error in the case that a user has pre-existing auth attempt counts of any kind, and that there are no interactions with the authentication attempts service when it is not turned on.
1. Code Review
=> AUT-3602: Emit reauth_failed audit event in verifyMfaCodeHandler when user has too many pre-existing authentication attempts for any count

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
- Emits the AUTH_REAUTH_FAILED audit event from the VerifyCodeHandler when a user has exceeded the max number of authentication attempts for any count type.
- Also verified in tests that there are no interactions with the authentication attempts service when it is not turned on.
1. Code Review
=> AUT-3602: Emit reauth_failed audit event in VerifyCodeHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
The event is emitted when a user has had too many pre-existing reauthentication attempts and is blocked from reauthentication.
Also refactored the start handler and service so that the counts from the authentication attempts service are only queried
once from the handler. The query in the start service has been removed with the handler query passing the isBlockedForReauth value through to the service to be user in the UserStartInfo.
1. Code Review
=> AUT-3602: Add reauth_failed audit event to StartHandler

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationResponse.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/contract/ClientRegistryProviderTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Channel.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
Add `channel` field to client registry. The possible values are "WEB" (default) and "STRATEGIC_APP".
The handlers to register / update a client in the client registry have also been updated.
`channel` will be passed to Authentication via the authorize request. "STRATEGIC_APP" is a request for mobile view.
Once this is deployed to integration, I'll test adding a new client and check it sets the value of `channel` to "WEB".
=> ATO-1060: Add channel field to client registry which can be WEB or STRATEGIC_APP

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Adds audit log for a user needing to authenticate as a result of having an invalid "bsid". This is only logged if the "bsid" is the _only_ reason for a new authentication journey, so not logged if both "gs" and "bsid" are missing, for example. This means only the journeys affected by this change will be logged.
Original ticket to make a decision on this auditting: https://govukverify.atlassian.net/browse/ATO-969
Event catalogue update: https://github.com/govuk-one-login/event-catalogue/pull/234
Slack discussions: https://gds.slack.com/archives/C021FD820N6/p1724763497125069 and https://gds.slack.com/archives/C05811D4JMR/p1724766923917489
1. Code Review
=> ATO-1064: add audit log for bsid sign out

template.yaml
This table will be used to store Orchestration session data once we have migrated from the existing shared redis store. DynamoDB is more scalable than redis and will allow us to do proper Orchestration performance / scaling testing.
This PR is very similar to https://github.com/govuk-one-login/authentication-api/pull/5125 which set up the equivalent Auth session table.
Note that point in time recovery is currently enabled, but we may disable in future based on the outcome of [ATO-1073](https://govukverify.atlassian.net/browse/ATO-1073).
Deployed to Orch dev and the table is created successfully.
[ATO-1073]: https://govukverify.atlassian.net/browse/ATO-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATO-1072: Create Orch session dynamo table

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
To break the session depency between auth and orch, auth need to be able to determine if a user is authenticated without accessing the shared session store, and store this information in their own session store.
Here orchestration will pass this information in as a claim in the JAR to authentication, for authentication to be able store this in their own session store
=> ATO-980: Pass new claim authenticated to auth

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
Adds `.withBrowserSessionId(session.getBrowserSessionId())` to the session refresh in the `validateSession` function. This was causing sessions to be overwritten without a bsid, and the log "Session has no browser session id" to be seen, despite those sessions previously having browser session ids.
1. Code Review
=> ATO-965: add browserSessionId to fresh session creation

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
- We've [now started](https://github.com/govuk-one-login/authentication-api/pull/5280) storing the value of isNewAccount in the new session store. 
- Given we've left the above PR enough time for the new session store to normalise with respect to the shared one, we should be able to seamlessly move the getting of this value to the new session store.
- This also deprecates a couple of methods in the `AuthSessionService` class to simplify some of the code and make things more consistent
- Deploy to an auth dev environment 
- Run through a login journey 
- Check cloudwatch metrics
- Do the same for a signup journey
- Branched off of https://github.com/govuk-one-login/authentication-api/pull/5280, so must be merged first. Given this relies on the setting of …
=> Ato 981 move getters over to new session store

auth-external-api/src/main/java/uk/gov/di/authentication/external/entity/AuthUserInfoClaims.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java
Before, claims were set on the userinfo response using data from the access token only. 
Now, as part of splitting the shared session, some Auth session data needs to be sent to Orch. The way we are doing this is by including session data as claims in the userinfo response.
This PR sets up a method (`addClaimsFromSession`) to add additional claims to the userinfo response from the Auth session. For now only `"verified_mfa_method_type"` claim is added, but more will follow in future as more of the shared session gets split.
=> ATO-979/b: Add verifiedMfaType to userinfo response

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
Ensure we log an error and re-throw AuthSessionException when any call to the Auth session DynamoDB table throws an exception.
Extract logic to a private method for maintainability.
=> BAU: Standardise Auth session service exception handling

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
- Removed unused field _browserSessionId_ from Auth Session Class
- Removed unused field _processingIdentityAttempts_ from Auth Session Class
- Removed unused field _passwordResetCount_ from Orch Session Class
- Removed unused method _updateWithNewSessionId_ (formerly named _updateSessionId_) from Auth SessionService
- Replaced AuthOrchSerializationServicesIntegrationTest with SessionServiceIntegrationTest - The former tested only serialisation / deserialisation between Auth and Orch without simulating Redis.
Note: This is the second of two PRs and will require a rebase once the first goes in.
Code Review
Part 1: https://github.com/govuk-one-login/authentication-api/pull/5133
=> ATO-1006: Remove Unused Fields From Session Classes (2/2)

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
- This sets isNewAccount in the authentication callback handler using the UserInfo response from auth, regardless of whether this is an auth or identity journey. This is needed because when a user is returned from the identity journey (IPV callback handler) we need to emit metrics on this session field, and we can no longer rely on auth setting it.
- 
Deploy to a dev environment 
- Run through a journey, check all is fine
=> Ato 981 set is new account from auth user info response

orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchSessionExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, template.yaml
Failing to deploy: 
`"CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename <env>-OrchSession and update the stack again"`
A subsequent PR will change the table name back to <env>-OrchSession
=> ATO-1076: Temporarily change Orch session table name

build.gradle
To resolve the [Apache Commons IO: Possible denial of service attack on untrusted input to XmlStreamReader](https://github.com/govuk-one-login/authentication-api/security/dependabot/24) vulnerability.
1. Code Review
=> BAU: Update commons-io to 2.17.0

shared/src/main/java/uk/gov/di/authentication/shared/services/AccessTokenService.java
Fix NullPointerException in incrementCloudwatchCounter
'configurationService' is not being set in the 'AccessTokenService' constructor. 
Removes 'Unable to increment access token service cloudwatch counter' from the logs and allows the counter to be set.
https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?q=search%20index%3D%22gds_di_production%22%20source%3D%22*%3A%2Faws%2F*%2Fproduction-*%22%20%20%20%20%22Unable%20to%20increment%20access%20token%20service%20cloudwatch%20counter%22&earliest=1727967000&latest=1727967300&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&sid=1727972385.369674
1. Code Review
1. Deploy to a test environment, run a journey and check that the error is missing from the logs.
=> BAU: Fix NullPointerException in incrementCloudwatchCounter

build.gradle
`notifications-java-client` currently uses 2.8.0 which has the issue [Apache Commons IO: Possible denial of service attack on untrusted input to XmlStreamReader ](https://github.com/advisories/GHSA-78wr-2p64-hpwj).
Here we ensure that the minimum `commons-io` version we use is patched while we await a bump release of `notifications-java-client`.
1. Code Review
- https://github.com/govuk-one-login/authentication-api/pull/5353
- https://github.com/alphagov/notifications-java-client/pull/247
=> BAU: Constrain commons-io to minimum 2.14.0

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Instead of creating a new `AUTHORISATION_INITIATED` event with a `new_authentication_required` pair, just append it onto the existing event.
1. Code Review
=> ATO-1064: append audit log to existing event

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java
- Turns on the bsid feature in integration tests
- Updates current tests accordingly
- Adds new test for the new route bsid introduces: valid "gs" cookie, but invalid "bsid" cookie
1. Code Review
=> ATO-965: add bsid integration tests

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
- We've now moved the [getters](https://github.com/govuk-one-login/authentication-api/pull/5303) and the [setters](https://github.com/govuk-one-login/authentication-api/pull/5280) for `isNewAccount` to the new session store. This means Auth no longer need to set this value in the shared redis session. This PR removes the redundant setting of these values.
- I've left reading the redis session in the `UserInfo` handler as we may need to set values in the shared session as an interim step when transitioning (like we did [here](https://github.com/govuk-one-login/authentication-api/pull/5219))
- There is some [future work to clean up the session class](https://govukverify.atlassian.net/jira/software/c/projects/ATO/boards/390?selectedIssue=ATO-982) so will clean that up as part of this 
- Code …
=> ATO-981: Remove auth setter from shared session

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
The email is added to the session in `CheckUserExistsHandler` in authentication, so in a doc app journey, this should be null. If it is, we can remove the use of email in the doc app journey.
1. Code Review
=> ATO-922: add logging to verify if session email is null in DocApp

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/ReauthMetadataBuilder.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java
- Add `ReauthRequested` metric
- Metric raised when the reauth journey is started. 
- Add `ReauthSuccess` metric
- Metric raised when the reauth journey is successfully completed. 
- Add `ReauthFailed` metric
- Metric raised when the reauth journey has failed.
- With this, also create `getReauthFailureReasonFromCountTypes()` method
- The logic for deciding the reason from count types is extracted into it's own method so it can be used by both metric and audit event code.
These metrics are raised next to corresponding audit events for. They will allow us to chart this metric in dashboards and establish a pattern of use that will could spot issues.
1. Code Review
=> AUT-3749: Add reauth metrics

ci/terraform/account-management/manually-delete-account.tf, ci/terraform/account-management/staging.tfvars, ci/terraform/account-management/variables.tf
Add permissions for KMS key on SNS topic, follow up to https://github.com/govuk-one-login/authentication-api/pull/5364
=> OLH-2122: Permit access to the KMS key for the account deletion topic

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthUserInfoClaims.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthExternalApiStubExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, template.yaml
This is the third part of splitting verifiedMfaMethodType session data. 
Now that Auth send the value in the userinfo response (https://github.com/govuk-one-login/authentication-api/pull/5301), and Orch have a dedicated session (https://github.com/govuk-one-login/authentication-api/pull/5326), this PR actually adds the value to the Orch session.
Once this is deployed, Auth and Orch will have access to verifiedMfaMethodType via their individual sessions, as well as the shared session (for now).
Manually tested in dev and functions as intended: 
- When there is no existing session, verifiedMfaMethodType is added to the Orch session (with a value either AUTH_APP or SMS). 
- When there is an existing session, the value of verifiedMfaMethodType persists to the updated session (with a new …
=> ATO-979/c: Add verifiedMfaMethodType to Orch session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SessionServiceTest.java, template.yaml
Both feature flags relating to browserSessionId have been turned on all the way to prod, and are working as expected, so we have no need for the feature flags anymore. This PR deletes both the overarching `isBrowserSessionCookieEnabled` and the `isSignOutOnBrowserCloseEnabled` flags.
1. Code Review
2. Search codebase for any instance of these flags
=> ATO-1084: bsid feature flag cleanup

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java
sessionId is the primary key of the table, so any OrchSessionItem must have a sessionId associated with it. By removing the OrchSessionItem constructor with no arguments, we insist that any OrchSessionItem will have a sessionId.
1. Code Review
=> BAU: update OrchSessionItem item to always require a sessionId

ci/terraform/oidc/account-interventions-alerts.tf, oidc-api/src/test/java/uk/gov/di/authentication/oidc/contract/AccountInterventionServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AccountInterventionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AccountInterventionServiceTest.java, template.yaml
- A pager duty (P1) alarm shouldn't be triggered in the case that communication with Account Intervention Service fails open (ie. assumes no intervention). To ensure this, a dimension has been added to the AISException metric, which is used to determine the type of alarm
- `env-P1-account-interventions-alarm` alarm is renamed to not include "P1" in the case that AIS fails open. This alarm shouldn't be triggered, as its metric monitors a deprecated log group (orchestration_redirect_lambda_log_group).
- Setting up a pager duty alarm for the P1 AIS error
- Adding alarms for the other lambdas which call AIS (IpvCallback and ProcessingIdentity). This isn't too bad as AuthenticationCallback calls AIS first in all journeys.
These will form part of a wider piece of work to audit and improve the …
=> ATO-1049: Improvements to Account Intervention Service alerting

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
Orch needs this so it can be added to the orch session. We need email because a client's list of test emails is in the client registry, which we need to compare against. 
Note that this is only an internal endpoint (orch<->auth). When an RP makes a UserInfo request, we still check they're allowed to (see `UserInfoService` in `oidc-api`). 
1. Code Review
I have deployed to Dev and tested that the email is sent to orch even when I set the claims to not include email. In that case, the RP still doesn't get the email, because that list of claims is still used in the RP<->orch UserInfo request.
=> Ato 922: add email to all auth user info responses

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java, template.yaml
Now that `verifiedMfaMethodType` is passed as a claim in the userinfo response from Auth and stored in the Orch session, we can get and use the value from the Orch session instead of the shared session.
This needs to be tested in staging as it affects IpvCallback and AuthCode lambdas.
=> ATO-979/d: Get verifiedMfaMethodType from Orch session instead of shared

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
Adds email to the orch session. The orch<->auth userInfo request now always returns email, as of https://github.com/govuk-one-login/authentication-api/pull/5403
1. Code Review
=> ATO 922: set email in orch session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
This pair had a key 'rpPairwiseId' and value userInfo.getClaim(‘rp_client_id’). rp_client_id is a claim added in AuthorisationHandler, but nowhere else. ClientId is already associated with the submitAuditEvent, and the internalPairwiseId is also already on the event as the subject of the user. So I’m assuming this was trying to add the rpPairwiseId, as rp_pairwise_id is a claim on the userInfo response from authentication.
This will change what is being logged in this audit event, but to me, this change seems like the intended behaviour
1. Code Review
=> BAU: use different value in audit event

ci/terraform/account-management/acceptance-test-values.tf, ci/terraform/shared/acceptance-test-values.tf, ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/dev-stub-clients.tfvars, ci/terraform/shared/dns.tf, ci/terraform/shared/integration-stub-clients.tfvars, ci/terraform/shared/production-stub-clients.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging-stub-clients.tfvars, ci/terraform/shared/stub-rp-clients.tf, ci/terraform/shared/variables.tf, scripts/fix-lambda-aliases.sh
Create SSM parameters with values required by the acceptance tests.
This allows us to provide the acceptance tests with the actual configured values,
rather than manually duplicating the configured values in each environment
- Code review
- test deploy in authdev / sandpit environments and ensure that the right values are created.
=> AUT-3800: Add values required by acceptance tests into SSM

ci/terraform/shared/build.tfvars, ci/terraform/shared/integration.tfvars, ci/terraform/shared/production.tfvars, ci/terraform/shared/staging.tfvars
non-dev envs all use the old stub still.
=> BAU: set orch_stub_deployed=false in non-dev-envs

.github/dependabot.yml
Attempt to configure dependabot security updates to group minor and patch changes into one PR.
The only reason for trying this is after reviewing the documentation at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups & https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates it seems to infer that groups are nessesary to have the security updates configured as we'd like.
In this case it is to resolve an issue where BAU is not prefixed on security update PRs, e.g. https://github.com/govuk-one-login/authentication-api/pull/5387
1. Code Review
=> BAU: Group minor and patch gradle dependabot security updates

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/AccountDeletionReason.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/AccountDeletionService.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/services/ManualAccountDeletionService.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/AccountDeletionServiceTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/services/ManualAccountDeletionServiceTest.java
Replaces #4901 
This will allow us to distinguish between a user deleting their own account, and support deleting an account on behalf of a user.
=> AUT-3767: Add account_deletion_reason extension to AUTH_DELETE_ACCOUNT

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthUserInfoClaims.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
Adds rpPairwiseId to the Orch session. This field is already being sent in the auth userinfo response. This is needed because in `AuthCodeHandler`, there is a function `getRpPairwiseId`, which uses the userProfile table to get the `rpPairwiseId`. We instead want to get it from the orch session here, so we can remove orch's use of the userProfileTable
=> ATO-922: add rp pairwise id to orch session

ci/terraform/account-management/manually-delete-account.tf
Configure log subscription filter. Tested in sandpit. Splunk doesn't route sandpit logs, so they didn't appear there, but the subscription filter was correctly created.
=> BAU: Ship logs for manually delete account lambda to splunk

build.gradle, settings.gradle
This offers a number of advantages as the dependencyResolutionManagement configuration is set to fail the build if a repositories declaration is found on any project and moving configuration out of the root build.gradle makes the build follow the gradle standards and prepares the scripts for upgrading to the next version of gradle.
1. Code Review
=> BAU: Centralize gradles repository declaration in settings.

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactory.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/VerifyMfaCodeRequest.java
- Moved the error handling and audit event emission out of the processCodeSession method. This means that error handling (predominantly) happens in one place, followed by processing a successful code request, followed by audit event emission. This gives the processSuccessfulCodeSession (successor to processCodeSession) method a single purpose and makes the logic easier to follow..
- Stopped passing unnecessary audit context through to verify code method.
- Replaced switch with enhanced switch in the MfaCodeProcessorFactory
- Throw and catch exception when the client is not present in the VerifyMfaCodeHandler
- Delete unused empty constructor in the VerifyMfaCodeRequest
1. Code Review
2. Deploy to dev and run through auth app journey successfully
=> BAU: refactor verify mfa code handler

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchSessionExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java
- Sets isNewAccount in the new Orch session to UNKNOWN at session start
- Deploy to a development environment 
- Run through a jorney 
- Check session now contains UNKNOWN in the isNewAccount field
=> Ato 981 set is new account in new orch session start

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
Removes email from the orch session. We actually already have a means to get this data via the UserInfo table, and because it isn't session-specific, it makes more sense for this info to live in the UserInfo table.
Nowhere uses this yet, so no danger in just removing it.
1. Code Review
=> ATO-922: remove email from orch session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Orch needs access to a user's phone number only within identity journeys, so following the pattern of email and local_account_id, we add phone number as a claim for all identity journeys.
I've decided to follow this pattern, instead of adding phone number to all UserInfo requests, as we explicitly only need it in identity journeys.
This PR also adds a low-level trust journey test to verify that specifically for high-trust identity journeys, we add in a number of scopes, which now includes phone number.
1. Code Review
=> ATO-1118: add phone number to auth UserInfo response for all identity journeys

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
We need these claims in every UserInfo response, so we always adds these claims.
Currently, we always add these within the auth UserInfo response, but (taken from the ticket description),
> _For authentication to be truly separate from orch and for their interaction to be a by-the-book oidc flow, auth should not be at all aware of what orch is using the data for - it should just provide whatever data the consuming service asks for (and is allowed). Currently, authentication code has been changed to send back email and verified mfa method. Instead, we should change orch code to always request these claims. Else, the two services remain coupled._
This shouldn't make any functional difference, as currently, both of these are always sent back (auth code has been changed such that this is the …
=> ATO-1129: add email and verified MFA claims to all userinfo requests

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
This is used alongside https://github.com/govuk-one-login/authentication-frontend/pull/2164/files to take the `currentCredentialStrength` from the `start` frontend and set it into the auth session.
The `currentCredentialStrength` is passed to the frontend through the authorize request and set in the auth session so it can be taken and passed on in the userinfo back to orch.
Noted: in later lambdas we do null checks for this value.
=> ATO-975: Add current credential strength into the auth session

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Changes the way json objects are compared to in tests - they are compared as JSON objects now, rather than Strings. This reduces stochastic flakiness about the order of the json when compared as a string.
1. Code Review
2. Tests pass consistently
=> BAU: compare json objects rather than strings to negate flakiness

ci/terraform/oidc/localstack.tfvars, ci/terraform/oidc/variables.tf, ci/terraform/shared/localstack.tfvars, ci/terraform/shared/variables.tf, ci/terraform/utils/variables.tf
Bumps Terms and Conditions version number to reflect a change in the personal data retention period. As suggested in the guidance, I've searched for instances of `terms_and_conditions` and updated these to reflect the new version too.
1. Code Review
Privacy notice updates to reflect the changed retention period are made in https://github.com/govuk-one-login/authentication-frontend/pull/2252
=> AUT-3828: Bump terms and conditions version number

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
- We now set the user as authenticated in the session when they are handed back from Auth regardless of whether they are on an identity or auth-only journey. 
- The practical effect of this on a User's journey is that now if they abandon an identity journey from a fresh session, they will pass through Auth as logged in when they return if their session has not expired. The current behaviour is that they would be prompted to log in before being passed to back IPV.
- There is a second part of this change which involves removing the redundant setting this field in IPV callback handler in this PR https://github.com/govuk-one-login/authentication-api/pull/5430, however this change is the part that will have a user facing change. 
- Deploy to a dev environment
- …
=> ATO-1088: Set authenticated flag in all cases a user is handed back from Auth

ci/terraform/oidc/alerts.tf, ci/terraform/shared/sqs.tf
Added the relevant runbook to the alarm message for the [production-pending-email-check-dlq](https://uk-digital-identity.awsapps.com/start/#/console?account_id=172348255554&destination=https%3A%2F%2Feu-west-2.console.aws.amazon.com%2Fsqs%2Fv3%2Fhome%3Fregion%3Deu-west-2%23%2Fqueues%2Fhttps%253A%252F%252Fsqs.eu-west-2.amazonaws.com%252F172348255554%252Fproduction-pending-email-check-dlq%2Fdlq-redrive) and [production-email-notification-dlq](https://uk-digital-identity.awsapps.com/start/#/console?account_id=172348255554&destination=https%3A%2F%2Feu-west-2.console.aws.amazon.com%2Fsqs%2Fv3%2Fhome%3Fregion%3Deu-west-2%23%2Fqueues%2Fhttps%253A%252F%252Fsqs.eu-west-2.amazonaws.com%252F172348255554%252Fproduction-email-notification-dlq%2Fdlq-redrive) alarms.
Took inspiration from how runbooks …
=> AUT-3750: add relevant runbook to DLQ alerts

auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AccountInterventionsDbServiceIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
Copy Internal Common Subject Identifier From User Info Subject To Orch Session
1. Code Review
Next PR: https://github.com/govuk-one-login/authentication-api/pull/5452
=> ATO-983: Copy InternalCommonSubjectIdentifier From UserInfo Response Subject To OrchSession (Orch ICSID 1/3)

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
- Sets up a feature flag `SET_AUTHENTICATED_FOR_IPV` which controls whether we enable Authenticated in the session once a User is handed back from Auth in all journeys
- Feature flag is set to true for `dev` , `build` and `staging` but turned off for `integration` and `production`
- Deploy to dev, I did sandpit:
- Run through a journey - done
- Run Auth acceptance tests against the deployed environment - Ran against sandpit, did have 9 failing tests but these also failed when ran on main in sandpit so writing off as noise in sandpit. These were all lockout tests which failed at the  6 wrong MFA code step
=> Ato 1088 set autnethicated flag for all journeys

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
Currently, email and verified_mfa_method_type are sent in all responses. Instead, I'm updating orch code so we always request these claims https://github.com/govuk-one-login/authentication-api/pull/5451. 
Authentication shouldn't know that we always want it as the provider of this data - it should just provide whatever orch asks for. From ticket description:
> _For authentication to be truly separate from orch and for their interaction to be a by-the-book oidc flow, auth should not be at all aware of what orch is using the data for - it should just provide whatever data the consuming service asks for (and is allowed). Currently, authentication code has been changed to send back email and verified mfa method. Instead, we should change orch code to always request these claims. Else, the two …
=> ATO-1129: move claims to be conditional

ci/terraform/shared/sandpit.tfvars
- This enables the sandpit RP stub as a test client, which will allow running the fully automated acceptance tests against sandpit environment. This brings sandpit inline with the other auth dev environments
- Code review commit by commit 
- Deploy to sandpit (sandpit is the only dev environment that makes sense here)
- Check the client registry entry for the stub and observe this flag is set to the same value as the terraform
- Run the acceptance tests against sandpit - all but 9 should pass. (The 9 that don't pass will be ones which enter an incorrect OTP code, which will pass if you modify the acceptance test code not to use the in main) 
-
=> BAU: Set sandpit stub to be test client

template.yaml
The IPV Callback Handler needs access to this so that instead of the UserProfile table, it can make use of the UserInfo table to get details about a user (eg phone number).
1. Code Review
=> ATO-1117: grant access to auth user info table

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
This email is sent back in the UserInfo response from auth on every request, so we can safely use this to get email instead ot the session ([see logs here](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20(index%3D%22gds_di_production%22%20message%3D%22is%20email%20attached%20to%20auth-external-api%20userinfo%20response*%22)&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=-7d%40h&latest=now&display.page.search.tab=events&display.page.search.patterns.sensitivity=0.866&sid=1730127482.802442)).
1. Code Review
1. Deployed to dev, and ran through a journey. Working as expected
=> ATO-1115: get email from userinfo response instead of session

auth-external-api/src/main/java/uk/gov/di/authentication/external/entity/AuthUserInfoClaims.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthUserInfoClaims.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Following https://govukverify.atlassian.net/browse/ATO-1129 , adding the currentCredentialStrength to always be requested in the userInfo.
This is to allow auth to be able to send back the currentCredentialStrength from to userInfo to orch.
=> ATO-975: add currentCredentialStrength claim to all userinfo requests

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
This value changes depending on the RP currently interacting with orch. This means if a user gets part way through a journey, then starts a new one, the rpPairwiseId will become out of sync with the first journey. RpPairwiseId therefore must be robust to this. Currently, we calculate it using the client sector Id. Another solution is having it live in the ClientSession. But it cannot live on the session.
This property on the orch session is currently only used in logs, so no impact on removing it.
1. Code Review
=> BAU: remove rpPairwiseId from orchSessionItem

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsService.java, interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandler.java, interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
We have a sporadic issue with our Accounts Intervention stub failing during parallel acceptance tests runs, however we do not have any ids logged that can be used to corrolate the logs between the backend and stub.
Here we modify the logging of both the `AccountInterventionsService` and `AccountInterventionsApiStubHandler` to log the only common identifier, `internalPairwiseId`.
This only happens in lower environments. Staging, Integration and Production do not have these logs turned on.
As an abundance of caution, this will be reverted when we determine the cause of the issue.
1. Code Review
=> AUT-3845: Temporary logging of `internalPairwiseId` in lower envs

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
- Uses the `authenticated` field from the start request body to determine whether a user is authenticated
- Removes looking in the shared session store for this value and instead relies on [orchestration to pass this](https://github.com/govuk-one-login/authentication-api/pull/5310) to Auth
- Deployed to sandpit
- Ran through a sign in journey from the stub
- Did not log out 
- Went through the stub again
- Observe being redirected to RP without sign in as expected
- Ran Auth acceptance tests against sandpit - all passed fine 
-  Followed the instruction in the commit https://github.com/govuk-one-login/authentication-api/commit/3a3752321071e6398b6ea7031bb58486d66b5016 to ensure no regression on the bugfix:
- Signed in and had an authenticated session in …
=> ATO 980 use authenticated claim in backend

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
This is a requirement as part of supporting max_age. Previous session ID will be used to fetch client session IDs from the old session.
=> ATO-1098: Add previous session ID attribute to the Orch session table

template.yaml
After testing in staging, we are now confident this feature can be enabled in higher environments (Integration and Production). This will mean that users' sessions will now have the authenticated flag set when handed back from auth, regardless of which journey type they're on (auth or identity)
=> ATO-1088 turn flag on integration and production

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/AccountInterventionsService.java, interventions-api-stub/src/main/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandler.java, interventions-api-stub/src/test/java/uk/gov/di/authentication/interventions/api/stub/lambda/AccountInterventionsApiStubHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
We can now remove these additional logs now that we know the source of the error (cold start of the stub meant the response took longer than the configured client timeout).
PR to revert: https://github.com/govuk-one-login/authentication-api/pull/5502
=> Revert "AUT-3845: Temporary logging of `internalPairwiseId` in lower envs"

ci/terraform/interventions-api-stub/lambda.tf, ci/terraform/modules/endpoint-lambda/lambda.tf, ci/terraform/modules/endpoint-lambda/variables.tf
The AIS stub is causing acceptance tests to fail when run in parallel. This happened because the stub lambda cold started another instance during the run, meaning the response took longer than the client configured timeout.
Here we remove the provisioned concurrency for the stub lambda, replacing it with snapstart. We also switch the architecture for this lambda to arm64 for the snapstart support.
1. Code Review
1. Deploy to sandpit with `./deploy-dev.sh sandpit -b -c -s -o -i`
1. Run though sign in journey
1. See no error
=> AUT-3845: Enable snapstart for AIS stub

auth-external-api/src/main/java/uk/gov/di/authentication/external/entity/AuthUserInfoClaims.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthUserInfoClaims.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthExternalApiStubExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
- Sets the value of isNewAccount in the Orch session at the same point as it is set in the regular session
- This includes updating:
-  Authentication Callback Handler to update this using Auth's userinfo response
- Updates the AuthCodeGenerationService to update the Orch session alongside the redis session
- Deploy to orch dev environment
- Run through a journey 
- Check all is well
- Ran auth acceptance tests against deployed env (sandpit), tests passed
- Once deployed:
- Run through journey in staging as feature will be enabled 
- Verify that in the case of a return code this value is set  
- Check doc app journey
- Enable feature flag in higher environments in future PRs
=> ATO-981: set is new account in orch session

template.yaml
Create a SPOT request SQS queue in dev and build for use with the SPOT stub. The real queue is created in terraform in the old account. Once the real queue is moved to the Orch account this stub queue can be removed and the same queue resource can be used in all environments.
Ensure there will be no changes beyond build
=> ATO-871: Create spot request queue for use with stub

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
Last steps on the Auth side for the current credential strength:
- Sets`currentCredentialStrength` as `medium` on the `verifyMfaCode` handler in the auth session
- Takes the `currentCredentialStrength` from the auth session and passes it through the userInfo response
Run acceptance test
Tested on Sandpit
=> Ato 975/add current credential strength to user info response

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
- Removes feature flag setup from handlers as this is now enabled in production - https://github.com/govuk-one-login/authentication-api/pull/5527
- Deployed to dev 
- Run Auth acceptance tests against it, all but one passed (Assuming test flakiness)
=> ATO-981: Setting feature flag cleanup

template.yaml
Adds r+w permissions to OrchSession table for LogoutHandler. 
AuthenticationCallbackHandler and IPVCallbackHandler already have the required permissions.
ProcessingIdentityHandler permissions are being addressed in https://github.com/govuk-one-login/authentication-api/pull/5511 and https://github.com/govuk-one-login/authentication-api/pull/5512, as it is a bit more complex.
Nothing specific to test here. This work is needed for https://github.com/govuk-one-login/authentication-api/pull/5482, which will be tested thoroughly.
1. Code Review
=> ATO-1134: add policies to read and write to orchSesssionItem table

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/dev-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars, ci/terraform/shared/production-stub-clients.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging-stub-clients.tfvars, ci/terraform/shared/stub-rp-clients.tf, ci/terraform/shared/variables.tf
Set up all stub clients to support identity, in preparation for the IPV and SPOT stubs
=> BAU: Enable identity for all stub clients

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
While working on setting auth_time in AuthenticationCallback, it was becoming a bit complex and hard to read. For maintainability, this PR contains two small refactors:
1. Where possible, separate setting to the session objects, and updating the database.
2. Use private method to separate logic from main handler.
No changes to tests required, so I'm confident this is OK, but I will
=> ATO-1182: Refactor sessions setting in AuthenticationCallback

ci/terraform/modules/endpoint-module/alerts.tf, ci/terraform/modules/endpoint-module/variables.tf, ci/terraform/oidc/processing-identity.tf
This change allows you to easily add runbooks to any authentication lambda alarm. I have run a tf plan, and checked that it does not affect any other alarms.
=> BAU: Add orchestration runbook to processing identity alarms

template.yaml
Hook up the IPV and SPOT stubs in the dev and build environments
- Have set spot response queue and key arns in secretsmanager
- Have set IPV encryption public key in parameter store
**Please review to ensure this change has no effect beyond build**
I will pause promotions from staging to check we've not broken anything there
=> ATO-871: Configure dev and build for SPOT and IPV stubs

shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
The value of `UpliftRequired` will be stored in the Auth session at the point it is determined (StartHandler), so that it can be returned to Orch later on in the userinfo response. Orch need this value in order to determine whether to set auth time in the Orch session.
=> ATO-1228: Add `UpliftRequired` attribute to the Auth session

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/authdev2.tfvars, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dev.tfvars, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
Adds policy for ProcessingIdentityHandler to access the Orch Session table on Orch AWS accounts for logout (resource policy for the DynamboDb table here https://github.com/govuk-one-login/authentication-api/pull/5511)
1. Code Review
2. Deployed to dev (along with https://github.com/govuk-one-login/authentication-api/pull/5512 to sandpit). I was able to describe the table when I sign into the Auth dev account from command line. I also created a lambda in Auth dev and verified that I wasn't able to access the orch session table. I then added the policies in https://github.com/govuk-one-login/authentication-api/pull/5512, and verified I was able to both describe and delete an item from the orch session table.
=> ATO-1147: add IAM policy to access orch session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
The `addOrUpdateSessionId` method is specifically for updating the sessionId of the Auth session. Instead the Auth session is built with certain fields (including currentCredentialStrength) and then updated in Dynamo later in the handler.
=> BAU: Refactor Auth session setting in Start handler

ci/terraform/oidc/processing-identity.tf
We have already swapped them over on all other environments without issue here https://github.com/govuk-one-login/authentication-api/pull/5548, so here, we swap the role on production too.
1. Code Review
=> ATO-1147: swap roles over in production

ci/terraform/shared/dynamodb.tf
To be able to modify the `attribute_name` field we firstly need to disable[1] the TTL configuration first to then be able to enable the renamed attribute, which we will set to the existing attribute `ttl`.
The plan: 
1) Merge this PR, this will disable the TTL config. Any changes merged before step 2 is merged will fail at the deploy shared module stage.  (This PR)
2) [Merge the PR which comments out](https://github.com/govuk-one-login/authentication-api/pull/5576) the ttl config block. Deploying this will result in a no-op update to the shared module but allow subsequent deployments to succeed. (Tested in sandpit)
3) After an hour, merge the [PR re-enabling the ttl config with the renamed attribute](https://github.com/govuk-one-login/authentication-api/pull/5439)
> [!NOTE]  
>  Once this …
=> ATO-1104: Temporarily disable TTL configuration

ci/terraform/shared/dynamodb.tf
- Follow up PR from https://github.com/govuk-one-login/authentication-api/pull/5572,  this now re-enables the TTL config with the renamed attribute
- Must merge the previous PR first, otherwise this will fail to deploy
- There must be at least 1 hour after the previous PR hits prod to merge this one 
- https://github.com/govuk-one-login/authentication-api/pull/5572 must be merged first
=> ATO-1104: turn ttl back on with renamed attribute

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java
Include uplift_required in userinfo response if Orch have requested it (Orch will [always request it](https://github.com/govuk-one-login/authentication-api/pull/5558)). 
If true, Orch will set auth time in the Orch session
=> ATO-1230: Include uplift_required in userinfo response

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
- The metric was incorrectly using clientSessionId instead of clientId
=> BAU: Fix metric

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java
- Switches an increment sign in method to one that uses the Orch account state not the shared session one.
- This should make no difference as they're effectively the same 
- Removes an unused method
=> BAU: switch metric to orch account state

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthExternalApiStubExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
As part of the max_age initiative, Orch are to begin setting `authTime` in the Orch session. This needs to happen in two situations:
1. When the user is authenticated (ie. when the `authenticated` session field goes from `false` to `true`).
2. When the user has had their credential strength uplifted (eg. from LOW to MEDIUM), which happens when a user with an existing session authenticates with a higher trust level on a second journey. This information is [passed as a claim ("uplift_required")](https://github.com/govuk-one-login/authentication-api/pull/5580) to Orch in the Auth userinfo response.
- 1st journey 2FA
- 2nd journey 2FA
---
- 1st journey no-MFA
- 2nd journey 2FA
=> ATO-1096: Add auth time to Orch session

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationServiceTest.java, template.yaml
Creating the current credential strength value in Orch session.
- Setting it the lowest requested credential trust
- Added a check on the orch to see if the currentCredential strength in the session is less than the lowest requested credential strength and if so update.
Included the getters of the orch session since they are just used for comparison.
Feature flagged in AuthCode to test in staging
Tested in Dev 
Acceptance test past 
Check commit messages to make sure they make sense. Tried to record the reason for implementing the logic. 
Make sure no logic is missing from the shared session.
=> Ato 975/setting current credential strength orch session

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationServiceTest.java
Move current credential strength setting from service to the auth code lambda as it was also setting it in the ipvCallback lambda, which the shared session does not do.
=> ATO-975: move setting the current credential strength in identity journey

template.yaml
Turn on setting current credential strength in the orch session in Prod and Int.
This shouldn't affect any flows or behaviours.
=> Ato 975/turn on current credential strength auth code setting

.github/workflows/call_get_changed_files.yml, .github/workflows/checkov.yml, .github/workflows/contract-tests.yml, .github/workflows/dependency-review-on-pr.yml, .github/workflows/dependency-submission.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/require-pinned-github-actions.yml, .github/workflows/sonar-analysis-on-merge.yml
We run a lot of unnecessary tests. This is a horrible experience when your PR doesn't touch anything that the tests are testing.
Filter runs using the built-in `paths` specifier in the `on:` event specifier
Filter runs using `tj-actions/changed-files`:
1. Get the list of changed files
2. If the files are not java'y, add a comment to the PR explaining that the checks have been skipped, but they still show as passed
3. If a java file is subsequently added, modify the comment to say that the tests are now meaningful.
4. In the actual test, use `if` statements to only run specific steps if java files are present (there is no way with GHA to exit early and mark the test as passed.
I've chosen to detect java changes rather than terraform ones because this logic is to control whether or not we …
=> BAU: Target which tests should run depending on changed files

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/variables.tf
Conditionally create and add the IAM policies for accessing the orch session table based on `is_orch_stubbed`.
For `authdev1`, `authdev2` and `dev`, orch is stubbed, so these environments don't need access to the orch session table. Currently however, the policies and roles enabling access are still being created, even if they're never used. However, there is some validation occurring on these policies and roles which are failing, because for example there isn't an encryption key arn (it defaults to an empty string).
1. Code Review
2. Tested the deployment for environments with `is_orch_stubbed == false`:
i. deploy edsandpit from main
ii. deployed sandpit from BAU/fix-cross-account-errors-in-auth-dev
iii. observed that the roles policies were moved, but none were destroyed nor added. This …
=> BAU: fix cross account errors in auth dev

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java
Refactor session setting in AuthorisationHandler
Modifying the Orch session for the max_age initiative (https://github.com/govuk-one-login/authentication-api/pull/5589/commits/97db69292517a83df7b444df43efc0fe69863d28) was becoming very cumbersome and the code was becoming unreadable and difficult to maintain. With this refactor, it is easier to:
- Understand how the Orch session is set 
- Modify the Orch session in future
I've deliberately not touched the Doc App journey to keep changes to a minimum, but as the journeys are similar a similar pattern can be applied there.
Each commit explains the refactoring done.
=> ATO-1252: Refactor Orch session setting in AuthorisationHandler

ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/stub-rp-clients.tf, ci/terraform/shared/variables.tf
Update sandpit client reg entry to have MaxAgeEnabled=true. This will allow testing of the max age initiative in dev / sandpit without always having to manually update the client reg entry.
=> ATO-1255: Update sandpit client reg entry to have MaxAgeEnabled=true

.github/workflows/dependency-review-on-pr.yml, .github/workflows/dependency-submission.yml
These were switched to be java-only checks, but this is bad behaviour: it's not just java files which can be scanned, and this makes the dependency graph weird and can cause spurious workflow failures
Code review
=> BAU: reinstate global dependency workflows

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
##What
There were some difference in CCS value between the shared session and Orch session. This means we cannot just rely on Orch to calculate the value but have to take it from auth.
Tested in dev
=> ATO-975: use CCS value from userInfo from auth

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
- Adds a feature flagged behaviour for using the orch session to attach the `authenticated` claim in the JAR sent to authentication instead of the shared session store
- Flag is turned on in dev, build and staging but not integration or production
- Deployed Dev:
- Run auth acceptance test against dev (sandpit) to ensure no regression - all passed
- Branches off: https://github.com/govuk-one-login/authentication-api/pull/5543, so must be merged first
=> ATO-980:  Switch getter to Orch session

ci/terraform/account-management/core.tf, ci/terraform/account-management/shared.tf, ci/terraform/auth-external-api/shared.tf, ci/terraform/delivery-receipts/core.tf, ci/terraform/delivery-receipts/shared.tf, ci/terraform/interventions-api-stub/shared.tf, ci/terraform/modules/dns/dns.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/core.tf, ci/terraform/test-services/shared.tf, ci/terraform/ticf-cri-stub/shared.tf, ci/terraform/utils/shared.tf
This was missed when upgrading the providers. If `role_arn` is null,
`terraform_remote_state` will fail to initialise.
This fixes that by conditionally building the object value for the
`assume_role` property.
- Code Review
- Maybe attempt to deploy to a dev environment locally?
=> BAU: Fix remote_state assume_role configuration

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
##What
Pass the current credential strength from the start request instead of using the userContext.
This will be the final change to allow all the current credential strength be moved to split sessions.
Tested in sandpit
Auth Acceptance tests pass
Tested it deploys to authDev
=> ATO-975: update uplift to use the current credetial strength from the start request.

ci/terraform/oidc/authdev1.tfvars, ci/terraform/oidc/dev-overrides.tfvars, ci/terraform/ticf-cri-stub/authdev1.tfvars, ci/terraform/ticf-cri-stub/authdev2.tfvars, ci/terraform/ticf-cri-stub/dev.tfvars, ci/terraform/utils/authdev1.tfvars, ci/terraform/utils/authdev2.tfvars, ci/terraform/utils/dev.tfvars
[AUT-3909]
remove lambda provisioned from dev account 
we are incurring total **USD 1,664.66** monthly for lambda  , which includes only concurrency cost in DEV account ( di-auth-development ) , concurrency is not required in non performance dev account 
1. Code Review
2. Deploy to sandpit with `./deploy-authdevs -p`
[AUT-3909]: https://govukverify.atlassian.net/browse/AUT-3909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-3909: remove lambda provisioned from dev account

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientSession.java
Adds rpPairwiseId to the client session in the authentication callback handler. There is a one-to-one mapping of rpPairwiseId to ClientSession, and we can always get the clientSession via the clientSessionId in the request cookies.
By defining it here, we gain a number of benefits:
- Calculate once, use many times. Currently, it is calcuated in lots of places.
- By calculating once, we define one name for this particular value, and remove opportunities for naming it differently when calculated.
- We don’t need to get subject, sector uri and salt everytime we want to get rpPairwiseId.
- We won’t have to be getting salt from the authUserInfo table - we can just use it immediately in the authenticationCallbackHandler, set it in the client session and use that.. This means we avoid the …
=> ATO-1259: add rpPairwiseId to client session

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/ticf-cri.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java
Invokes the TICF lambda via an alias rather than directly by name. Updates the policy to ensure that the lambda cannot be invoked by name.
This brings us in line with a programme-wide drive to invoke via aliases: see [here](https://govukverify.atlassian.net/browse/PROBLEM-130) for details.
1. Code Review
1. Deploy to a dev env.
1. Run through a sign-in journey in that environment. In a normal sign-in journey, the TICF lambda is invoked directly by the account interventions lambda. So to check this works correctly you should a) see that the TICF lambda has been successfully invoked, and b) that there are no error logs in the account interventions lambda related to not being able to invoke the TICF lambda. (Note that even if it wasn't able to invoke, there would be no difference in the user …
=> Aut 3903/invoke ticf via alias

orchestration-shared/src/main/java/uk/gov/di/orchestration/metrics/MetricValidationWarningLogger.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CloudwatchMetricsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/main/java/uk/gov/di/metrics/MetricValidationWarningLogger.java
The version bump of `aws-embedded-metrics` from v2 to v4 [1] introduces validation of metrics that thow errors on failure.
This commit brings in the same validation methods implemented by AWS [2] but instead of throwing an error it logs a warning with stacktrace.
The intention is to let this run in environments for a time period and assess any warnings logged before continuing with the version bump. The data gathered will help us make the nessessary modifications across orch and auth.
This would be reverted when we upgrade the library.
[1]: https://github.com/govuk-one-login/authentication-api/pull/4993
[2]: https://github.com/awslabs/aws-embedded-metrics-java/pull/119/files#diff-95ba60790f295fcb1d765c68bd8876c4722e13ef3fd5a34c6965b5fe1b393786R1
1. Code Review
2. Run the …
=> AUT-3929: Warn when metrics would fail validation

.github/dependabot.yml
The latest versions of `com.nimbusds:oauth2-oidc-sdk` introduce many changes that need to be comprehensively evaluated for impact internally and RPs.
ATO-1268 tracks this work.
We do not want Dependabot to be raising PRs to update this dependency until ATO-1268 is complete.
1. Code Review
=> ATO-1268: Dependabot ignore `com.nimbusds:oauth2-oidc-sdk`

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidator.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java
Clock skew was the wrong way around - it should give 30 seconds leniency in the expiration date, and instead it was rejecting tokens that were valid, but within 30 seconds of the expiration date https://javadoc.io/doc/com.nimbusds/nimbus-jose-jwt/9.7/com/nimbusds/jwt/util/DateUtils.html#isAfter-java.util.Date-java.util.Date-long-
=> ATO-1270: Fix the direction of clock skew

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/dynatrace.tf, ci/terraform/oidc/ticf-cri.tf
Add provisioned concurrency and scaling policy for ticf lambda.
This involved migrating the lambda to use the shared endpoint module.
Also adds dynatrace layer for OIDC.
1. Code Review
1. Deploy to sandpit
1. Check performance parameters have been successfully applied
Relies on https://github.com/govuk-one-login/authentication-api/pull/5624 being merged first [**DONE**]
=> Aut 3902/add provisioned concurrency

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/LogEventMatcher.java
We want to prevent potentially leaking sensitive information should the TICF CRI API response change in the future
Using our existing alerts infrastructure, should several timeouts or 4xx responses happen in a window we should be told about it.
We get the alerts by treating a timeout as an error to log.
1. Code Review
=> AUT-3900: Logging tweaks to TICF CRI handler

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
Removing feature flag that was used for testing the authCode in staging.
=> ATO-975: remove feature flag for current credential strength in AuthCode

ci/terraform/modules/endpoint-lambda/README.md, ci/terraform/modules/endpoint-lambda/alerts.tf, ci/terraform/modules/endpoint-lambda/variables.tf, ci/terraform/oidc/ticf-cri.tf
Like 1e50cc8f75ab5e7f22bddcbb45bedae6e8eb4a60, add support for appending runbook links to CloudWatch Alarm descriptions.
This link holds a page that will help triage and resolve alarms related to the TICF CRI handler.
1. Code Review
=> AUT-3900: Add runbook link to TICF CRI handler alerts

ci/terraform/account-management/manually-delete-account.tf
Replace the environment specific naming with a generic name to let CT roll out the role more easily. This also means that wn need to restrict which envs it is created in to prevent collision
=> BAU: Rename manual account deletion policy to be consistent across accounts

ci/terraform/account-management/manually-delete-account.tf, ci/terraform/shared/iam-ct.tf
The name needs to be known exactly
=> BAU: Use name instead of name_prefix in policies referenced by CT

ci/terraform/oidc/site.tf
This simply deploys the lambda - it does not enable any calls to be made. So is a prepartory step in turning on calls in production, but is not the turning on itself :-)
1. Code Review
=> AUT-3904: Deploy ticf lambda to production

ci/terraform/oidc/build.tfvars
This is a preparatory step before turning the calls on in production, which will follow subsequently. In build we call the ticf stub.
=> AUT-3904: Turn on calls to ticf in build

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java
As an error it raises several alerts, which gets noisy fast. We don't yet need alerting on timeouts, so disabling by changing the level to warn.
1. Code Review
=> AUT-3900: Downgrading TICF CRI timeout logging level

.github/PULL_REQUEST_TEMPLATE.md
Checklist item for changes needed to stub-orchestration in the PR checklist.
There was recently an error where acceptance tests started failing when running against stub-orchestration as the interface between Orch and Auth had changed but the stub had not been updated.
This is to remind us that changes may be required to the stub.
1. Template review
=> BAU: Checklist item for changes needed to stub-orchestration in the PR checklist

ci/terraform/oidc/processing-identity.tf, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/TableNameHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/TableNameHelperTest.java
- Pulls out the table name definition into a helper
- Defines a new table name for when in an auth account accessing an orch table (this should only be for ProcessingIdentityHandler)
This updates code that is only turned on up to staging.
1. Code Review
=> ATO-1134: add prefix for orch resources env variable

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationUserInfoStorageServiceIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthenticationCallbackUserInfoStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthenticationUserInfoStorageService.java
Adds `authUserInfo` to the IPVCallbackHandler. Read access has been added here https://github.com/govuk-one-login/authentication-api/pull/5475. 
I first want to verify that authUserInfo is both defined, and that the values are as expected. This PR therefore just adds some logging to compare the values used in this handler and the corresponding values in the orchSession and the authUserInfo table entry.
1. Code Review
2. Deploy to dev to make sure permissions are set up ok
=> ATO-1117: add authUserInfo to IPV callback handler

orchestration-shared-test/build.gradle, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/httpstub/HttpStub.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/httpstub/RecordedRequest.java, shared-test/build.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/httpstub/HttpStub.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/httpstub/RecordedRequest.java
This involves changing some implementation details for methods that have been removed with the bump.
Also took the opportunity to simplify `RecordedRequest` as it contained methods and properties that were not used.
This change is duplicated across auth and orch `shared-test` packages.
1. Code Review
2. See tests pass
=> AUT-1933: Upgrade `jetty` to 12.0.15

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AuthCodeExchangeData.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeServiceTest.java
Worked on with: @cearl1
- Updates the AuthCodeExchageData to include the auth time from the session, as the token request is a server-to-server interaction and therefore does not have access to the user's session.
- This is added in all cases we generate an authorisation code, except the doc app journey. This is because we do not want to return an `auth_time` claim in the ID token for doc app. 
- Deployed to dev:
- Ran through a journey - all fine
=> Ato 1280/save auth time in auth code exchange data

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, template.yaml
There is a specific set of updates required to the Orch session in relation to max age when all the following conditions are true:
- There is an existing Orch session
- Max age is enabled for the client
- Max age has expired
The updates to the Orch session are:
- Update the session ID of the existing (previous) Orch session. The session ID is updated as a security measure. Note that the previous session is not deleted (contrary to the non max age session update journey) because it is required after Authentication. The value of internalCommonSubjectIdentifier from the previous session will be compared against the value in the userinfo response, to confirm that the reauthenticated user is the same as the original user. Also the TTL of the previous session is bumped to ensure it is …
=> ATO-1099: Update session when max age has expired

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java, template.yaml
As part of the max age initiative, Orch need to return the auth_time claim in the ID token to RPs. The claim is retrieved from the auth code exchange data store, and then added to all token responses (not just when the RP includes max age in the authorize request).
Implementation is feature flagged and enabled in all envs except production. As this change is RP facing, it needs to be tested in integration and RPs made aware of the changes before releasing to production.
=> ATO-1097: Return auth_time in ID token

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, template.yaml
- Adds max age handling to the authentication callback handler behind a feature flag
- This adds handling for the case in which the internalCommonSubjectIds match (ie we return the same user) after a max age journey
- This involves re-attatching the client sessions to their shared session 
- We also remove the previous session id from their session as this prevents subsequent journeys from having the same check the same check - we only want to do this if they have been on a max age journey
- Deploy to dev and test:
- A journey without max age (establish an existing session)
- A journey forcing max age re-auth (max_age =0) 
- Observe logging around same user signed in 
- Do the same as above but sign in as different user
- Branches off of …
=> ATO-1100: copy client sessions

ci/terraform/shared/build-stub-clients.tfvars
Enable `max_age` for `relying-party-stub-build-acceptance-test` client. This is so that we can test the scenario that when the client has a `max_age_enabled`, and the user attempts to log in with an expired `max_age`, they are logged out. 
PR on orchestration-acceptance-tests here: https://github.com/govuk-one-login/orchestration-acceptance-tests/pull/53
1. Code Review
=> ATO-1310: enable max_age for stub-build-acceptance-test client

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
- Adds logging to check whether the doc-app request contains claims. We're not expecting this to contain claims so this logging will help us confirm whether our assumptions are true.
=> ATO-1328: Add logging to check if docApp contains claims

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
In a previous PR, I had assumed orchSession.getInternalCommonSubjectId() would be a defined string, but it seems this is not the case. When I tried to use it to get from the dynamodb table, it threw the error Supplied AttributeValue is empty a few times in 4 hours. Here, I add a small subset of the logs I added there to see what is going on.
1. Code Review
=> ATO-1117: add temporary logging to verify values

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
Upgrade pre-commit hooks.
antonbabenko/pre-commit-terraform no longer ships `terraform`, so we
now need to use `hashicorp/setup-terraform` to install it.
Code review
=> BAU: Update pre-commit hooks to latest versions

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
- Adds claim validation to the request object flow, meaning requested claims are now validated against the clients configuration.
- Deployed to dev and tested the following cases using the stub:
- Checked with valid claims -> As usual 
- Removed a claim from the client config and requested it -> got expected invalid claims error
- Made a request object request with no claims -> As usual  
- Deployed alongside this: https://github.com/govuk-one-login/relying-party-stub/pull/417 to ensure the claims were properly formatted when testing. Preferably we should merge this PR after that one, to ensure the stub stays fully working
=> ATO-1329: add claim validation to request object

ci/terraform/account-management/authdev1.tfvars, ci/terraform/auth-external-api/authdev1.tfvars, ci/terraform/delivery-receipts/authdev1.tfvars, ci/terraform/interventions-api-stub/authdev1.tfvars, ci/terraform/shared/authdev1.tfvars, ci/terraform/test-services/authdev1.tfvars, ci/terraform/test-services/authdev2.tfvars, ci/terraform/test-services/variables.tf, ci/terraform/ticf-cri-stub/authdev1.tfvars
[AUT-3954] Migrate Authdev1 to run  shared Dev VPC
Code Review
Deploy to authdev2 with `./deploy-authdevs.sh -p
[AUT-3954]: https://govukverify.atlassian.net/browse/AUT-3954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-3954: Move Authdev1 env to run on Shared VPC

shared/src/main/java/uk/gov/di/authentication/shared/services/AccessTokenService.java
When we added the cloudwatch metrics service to this class ([here](https://github.com/govuk-one-login/authentication-api/pull/5090/files#diff-a7e7ff7cedcd463c93c40cd203dbd387c691f3b0c10e64496f1021040d94c3d2)), we did not initialise it in all constructors. This constructor is being used by the token handler in the auth external api, meaning that when the access token service was being used by this lambda it was unable to increment the relevant counter and was raising an error in logs
=> BAU: Initialise cloudwatch metrics service in access token service constructor

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
We have discovered that in our new structure, it is possible for a user to have an undefined internalCommonSubjectId here. In this cases, it was because the user had skipped authenticationCallbackHandler. However, there were 2 cases where internalCommonSubjectId was defined and matched the calculated value, but rpPairwiseId didn't. With this log, I want to check if the values actually don't match, or if the value is just undefined.
The journey in question:
https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20%22persistent-session-id%22%3D%22NpetkOCgg3FVY_gsDotLanZ8pNo--1720278504017%22&earliest=-7d%40h&latest=now&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=&sid=1736511865.615899
1. Code Review
=> ATO-1117: check if rpPairwiseId is not blank

ci/terraform/oidc/integration.tfvars, template.yaml
Turns on destroying the orch sesion in integration. This was tested successfully in integration, but I the spinner page was broken. While the logs suggest the orch session was deleted, I want to see that the error isn't cascaded down and missed because of the broken page.
Integration added to feature flag
Tested in staging, now I want to manually test it in integration
=> ATO-1134: turn on destroy orch session on logout in integration

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
- The DocApp journey is currently not deleting sessions once the journey finishes. 
- This is leading to the auth journey reusing DocApp journeys, which do not generate browserSessionIds for orch sessions. 
- This is a temporary fix.
=> ATO-1331: Set browserSessionId on orch session in docapp journey

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountInterventionsHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AccountRecoveryIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/TxmaAuditHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
This will allow it to be reused more easily outside of the base frontend handler, which is required in an upcoming change
This should be a pure refactor, no change to functionality
=> AUT-3924: Extract TXMA header method

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
As part of the max_age feature, RPs can provide the `max_age` claim in the request object. Our previous code assumed that this would be a string integer (ex: "123") , however it is plausible this could be a integer claim too, and we should support both. The OIDC spec includes an integer max_age in the [example for request objects](https://openid.net/specs/openid-connect-core-1_0.html#:~:text=The%20following%20is%20a%20non%2Dnormative%20example%20of%20the%20Claims%20in%20a%20Request%20Object%20before%20base64url%2Dencoding%20and%20signing%3A), however is not specific on [max_age being a number.](https://openid.net/specs/openid-connect-core-1_0.html#:~:text=OPTIONAL.%20Maximum%20Authentication,prompt%3Dlogin.)
Previously the code would throw if the request object included a number for …
=> BAU: fix integer max age in request object

ci/terraform/oidc/production.tfvars, template.yaml
Turns on the feature flag `is_destroy_orch_session_on_sign_out_enabled` in production.
This was successfully tested in staging and in integration, so it is safe to turn this on in production.
1. Code Review
=> ATO-1134: turn on destroy orch session on logout in prod

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
- Added new feature flag: `USE_BROWSERSESSIONID_STORED_IN_ORCH_SESSION`
- If enabled, the browserSessionId from the previous orch session will be used in the auth journey (if present).
- If disabled, the browserSessionId from the previous shared session will be used in the auth journey (if present).
- Only enabled for dev and build environments.
=> ATO-1332: Use browserSessionId in OrchSessionItem if feature flag enabled

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java, template.yaml
- Sends backchannel logout notifications if the internalCommonSubject Id does not match the previous session after a max_age reauthentication
- Also removes the previous shared session and orch session as these no longer have any value
- Future work will include sending audit events 
- All changes are behind the MAX_AGE_ENABLED feature flag 
- Deploy to dev
- Run through a normal journey followed by a max_age re-authentication as same user
-  Run through a normal journey followed by a max_age re-authentication as with different users
=> ATO-1113: Send backchannel logouts if different user post `max_age`

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationUserInfoStorageServiceIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthenticationCallbackUserInfoStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthenticationUserInfoStorageService.java
In the `authentication-callback-userinfo` table, the UserInfo data is stored as a stringified JSON block. In code, we need to parse it. Currently, we parse it inline within the the Handler. In this PR, I've added a method `getAuthenticationUserInfo` which gets the data as a UserInfo object, and makes the dynamodb getter a private method, so in the handlers, we're always using the parsed data, and never the raw string.
- Adds method `getAuthenticationUserInfo`, and makes the dynamodb getter `getAuthenticationUserInfoData` private.
- Migrates the use of `getAuthenticationUserInfoData` to `getAuthenticationUserInfo`.
- Normalises the error messages, so this fails with the same error message.
=> ATO-1339: type authuserinfo to userinfo

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/LogoutReason.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
As part of the max age initiative, we are now adding more fields to our the LOG_OUT_SUCESS audit event and emitting one when a max_age logout is triggered. 
- Emits LOG_OUT_SUCCESS event when max_age logout occurs
- Adds new extension for logoutReason -> "max-session-age"
- Adds new extension for sessionAge ->  derived from current time - auth time of previous session
- Changes are behind MAX_AGE_ENABLED feature flag
Not required
=> Ato 1179/ato 1180 max age log out success event changes

ci/terraform/oidc/reverification-result.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ReverificationResultService.java
The request for a token to access the result of a re-verification should contain the original redirect_uri provided in the authorise request.  We were providing the redirect_uri that belongs to orch rather than the auth one.
This was causing the IPV token endpoint to not respond to requests. The ReverificationResult lambda did not have any timeout configuration on the token request and was hanging.  The frontend does have a timeout so we were seeing a timeout error in the frontend.  The Nimbus library httpRequest method defaults to not having a timeout for connect or read so an over-ride has been added to timeout connections and reads if IPV does not respond.
1. Code Review
=> AUT-3895: Correct and improve IPV token call.

template.yaml
As part of the migration from auth to orch, we would like to remove the getter for browserSessionId from the shared session. We've already added a feature flag to enable using the orch session to store the browserSessionId, and have tested it works in dev and build.
This PR enables the feature flag mentioned above in staging, integration, and production.
=> ATO-1332: Enable feature flag for getting browserSessionId from orch session up to production

shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java
The `CloudwatchMetricsService` is used to publish metrics, unsurprisingly, to Cloudwatch from our applications.
Almost every consumer invocation of this functionality passes in an `Environment` dimension, despite the service itself already knowing what environment it is running in.
This PR does two things:
1. Retrofits tests (which did not exist) onto the service
2. Adds a default `Environment` dimension 
These changes are not in the hot path yet, so this PR is something of a noop, but there's no reason not to [land this in main now](https://gds-way.digital.cabinet-office.gov.uk/standards/breaking-down-work.html#breaking-down-work)
=> BAU: Refactor CloudwatchMetricsService to prepare for default dimensions

orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SerializationServiceTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SerializationServiceTest.java
Needed to see if removing a field from the shared session would cause issues when retrieving existing sessions from redis.
Added tests for the orch SerializationService, which is used by the SessionService to retrieve and deserialise sessions from Redis.
=> BAU: Add unit tests for SerializationService

ci/terraform/oidc/build-overrides.tfvars, ci/terraform/oidc/dev-overrides.tfvars, ci/terraform/oidc/integration-overrides.tfvars, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/production-overrides.tfvars, ci/terraform/oidc/staging-overrides.tfvars, ci/terraform/oidc/variables.tf, doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java, template.yaml
Auth are doing some work to allow users to reset their MFA using their identity. As a result, there's a potential to see the same cross browser issue we see with IPV in our interactions with Auth. We need to be able to return a user to the RP they came from with the correct state value, even when they have lost their cookies. This will mean reusing some of the code we have for IPV. This is a bit of prep work to make that reuse easier.
Remove a feature flag that's been on for a long time. 
None
=> BAU: Remove feature flag for cross browser response

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/build.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/variables.tf, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IpvJwksHandler.java, template.yaml
Added a new lambda to be used for hosting IPV JWKs. 
Tested in sandpit, can hit the new orch lambda at `/.well-known/ipv-jwks.json`
=> ATO-1144: Add infrastructure for new IPV JWKS endpoint

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SessionServiceTest.java, template.yaml
As part of the linked ticket, we are aiming to move the browserSessionId to be stored in the OrchSessionItem. We have introduced a feature flag called `UseBrowserSessionIdStoredInOrchSession`, and it has been enabled in production for a couple of days now. We have monitored logging and have ensured that the bsid stored in the orch session is identical to the bsid stored in the shared session.
This PR removes the getter for the browserSessionId in the shared session, as well as the feature flag mentioned above.
=> ATO-1332: Remove shared session browserSessionId getter

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
The log message here was incorrect and was not logging the previous session id, just the updated one twice.
- Fixed log message
- N/A
-
=> BAU: Fix log message

ci/terraform/shared/stub-rp-clients.tf
=> ATO-1069: Add simulator acceptance test email to test client allow list

integration-tests/src/test/java/uk/gov/di/authentication/api/IpvJwksHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IpvJwksHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/IpvJwksHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/JwksService.java
In a previous PR we added the infrastructure for a new lambda that will serve public JWKs for IPV that will support key rotation. The endpoint did nothing but the infrastructure was added and worked.
This PR adds code to the IpvJwksHandler. It currently serves the `IPV_TOKEN_SIGNING_KEY_ALIAS` public key, but is configured to allow more keys to be served by the endpoint.
Tested in sandpit/dev. Can see a list of keys containing the `IPV_TOKEN_SIGNING_KEY_ALIAS` at that endpoint
=> ATO-1318: Add code for IpvJwksHandler

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
We previously added incrementing a logout metric as part of this functionality. Incrementing this metric for a max_age logout does not align with how it is used, so we're removing it.
=> BAU: Remove incrementing metric on max_age logout

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java
We have been working on migrating `browserSessionId` to be stored in the orch session. The latest PR for this change got rid of the getter for `browserSessionId` on the shared session, and got rid of the feature flag we used in the migration process. 
Now we are certain that the `browserSessiondId` field is not used at all in the shared session, we can safely remove the setter and builder method for the field, as well as the field itself. Tests added in https://github.com/govuk-one-login/authentication-api/pull/5765 ensure that if we remove a field from an object we save to redis, the extra field will be ignored, so this wont be a breaking change.
Tested in dev
- Sending a request after opening new browser prompts you to login.
- Sending a request with a previous session does not prompt …
=> ATO-1333: Remove browserSessionId from shared session

integration-tests/build.gradle
Remove guava library as it is not in use.
1. Code Review
2. Check that code compiles and all github actions complete.
=> BAU: Remove guava library

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This was previously merged here https://github.com/govuk-one-login/authentication-api/pull/5491, but it caused some errors. I've investigated it here https://github.com/govuk-one-login/authentication-api/pull/5716 and here https://github.com/govuk-one-login/authentication-api/pull/5730 and have discovered the issue, and importantly _why_ it happens. It is not a problem with our code - is it the new structure we have, combined with users trying to access parts of the journey they shouldn't be. The second to last commit fixes the issue, and the final commit removes the investigation logs.
Adds authUserInfo to the IPVCallbackHandler. Read access has been added here https://github.com/govuk-one-login/authentication-api/pull/5475.
I first want to verify that authUserInfo is both defined, and …
=> ATO-1117: add user info to ipv callback handler

ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/authentication-auth-code.tf, ci/terraform/oidc/check-email-fraud-block.tf, ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/mfa-reset-authorize.tf, ci/terraform/oidc/mfa.tf, ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/reset_password.tf, ci/terraform/oidc/reverification-result.tf, ci/terraform/oidc/send_notification.tf, ci/terraform/oidc/update_profile.tf
- This PR adds read access to the auth session table for all lambdas which inherit from the `BaseFrontendHandler` class. 
- Some already had read access so this is only the ones which did not already have the read permissions
- This is preparatory work to ensure we can add the `AuthSession` to the user context
- Double check all the handlers which inherit from the `BaseFrontendHandler` have read access to the auth_session table
- Deploy to sandpit to validate we're not hitting any policy limits - done!
Checking which handlers inherit from `BaseFrontEndHandler`: 
` grep --include=\*.java -r '.' -e 'extends BaseFrontendHandler'  -l | sort`
Checking which terraform files include the read permission:
`grep --include=\*.tf -r '.' -e …
=> ATO-1248: add read access to all auth lambdas

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/dev-stub-clients.tfvars, ci/terraform/shared/integration-stub-clients.tfvars, ci/terraform/shared/production-stub-clients.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/staging-stub-clients.tfvars, template.yaml
=> ATO-1360: enable max age

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
This is part of the migration work. Salt on authUserInfo is null a few times a day, so we only want to log here if it's not null. This is a temporary fix. An additional PR will be needed to figure out why it is null, but we don't want journeys to be interrupted due to non essential logging.
Adds null check around a log
=> BAU: add null check to logs, as salt is sometimes null

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java
This PR removes usage of `Session.getSessionId()` from `RedisExtension`. In most cases, the sessionID was already available, so we did not need to call the getter. The method signature for adding a new session had to be updated to pass in the session ID in addition to the session.
=> ATO-1378: Remove use of session id getter from RedisExtension

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/LogoutRequest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helper/TestIdGeneratorHelper.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helper/TestIdGeneratorHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/CookieHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/CookieHelperTest.java
This PR removes usage of `Session.getSessionId()` from `AuthorisationHandler`. To achieve this, we get the session ID from the cookie first, instead of getting the session directly from the cookie. We can then pass this sessionId variable around and use it where `Session.getSessionId()` was used.
The tests for this handler were also slightly inaccurate. In most cases, they were mocking `generateSession()` with the same session that you already had at the start of the workflow. Instead, I've created a new variable …
=> ATO-1362: Remove use of session id getter from AuthorisationHandler

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This PR removes usage of `Session.getSessionId()` from IPVCallbackHandler`. The session id was already available , so we did not need to call the getter.
=> ATO-1376: Remove use of session id getter in IPVCallbackHandler

ci/terraform/oidc/account-interventions-alerts.tf
I forgot to remove a `moved` block, left over from the localstack removal. That causes terraform to get in a tizzy.
Code review
=> BAU: Fix account interventions alarm

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
This PR removes usage of `Session.getSessionId()` from `DocAppCallbackHandler`. The session id was already available , so we did not need to call the getter.
=> ATO-1365: Remove use of session id getter from DocAppCallbackHandler

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
This PR removes usage of `Session.getSessionId()` from `AuthCodeHandler`. The session id was already available in the request headers, so we did not need to call the getter.
=> ATO-1364: Remove use of session id getter from AuthCodeHandler

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/contract/IpvTokenTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
In order to support key rotation easier in the future, we have introduced a jwks endpoint that serves the signing key for IPV requests. We need to let IPV know what key we have used to sign the request though. 
This PR adds the signing key ID to the IPV auth request and the IPV token request.
=> ATO-1319: Include signing key id  in JWS header of IPV requests

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
We're logging these on the other side of the queue but not actually putting the values in the payload.
=> BAU: Attach session ids to notify payloads

template.yaml
This table will replace the table of the same name that exists on Auth accounts. This table will store the UserInfo that Auth sents to Orch. Auth don't need to know about the table. In this migration, we also fix an issue with the current table, which is only indexed by internalCommonSubjectId. If a user has multiple client sessions, the authUserInfo entry gets overwritten. Hence, we have clientSessionId as a sort key as well. We keep ICSID as the partition key so we can still easily delete user data on request.
Add infrastructure for AuthUserInfo DynamoDb table 
Deployed to Dev. Built successfully, and saw that ICSID was the partitian key and ClientSessionId the sort key
=> ATO-1389: add infrastructure for AuthUserInfo DynamoDb table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordCompletionRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
Adds a new optional field to the json request to the reset password handler, that allows the frontend to control whether or ot we allow mfa reset after password reset. If this field is omitted, the behaviour will default to current (not allowing this).
Currently, when a user resets their password, we don't want them to immediately also be able to reset their MFA for security reasons. However, when we switch on the new mfa reset journey which goes via IPV, there is sufficient security to not need this block. Therefore, when this feature is switched on, we no longer need to add an account modifiers block for the user.
We've made a decision here not to introduce a separate feature flag on the backend that reflects whether the new support mfa journey is on or not. Instead the behaviour is …
=> Aut 3993/feature flag writing to account modifiers

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AuthenticationCallbackException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java
This should make most sense commit-wise. I've tried to keep all the refactor to a separate commit, but I'm afraid a little has leaked. Happy to split it out if it's confusing, but the refactor is contained to tests.
As part of their work around resetting MFA with ID re-verification (https://govukverify.atlassian.net/browse/DCP-3200 ), Auth are sending users to IPV on a re-verification journey. This means that users may experience the same cross browser issue as in a standard proofing journey. Orchestration needs to handle the return from Auth in the same way as from IPV: namely returning the user to the RP with an error and the correct state value.
Reuse code from the IPV and docapp solution to store and retrieve client session ID when cross browser issue occurs.
Return user to RP with …
=> ATO-1358: orch cross browser

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build.tfvars, ci/terraform/shared/dev.tfvars, ci/terraform/shared/iam.tf, ci/terraform/shared/security-groups.tf, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf
AUT-4048: Allow ingress access to session store redis from new Auth account to Deploy ORCH Stub in new Account 
Current ORC stub for Build & Staging are deployment in old Aws account , we will me migrating the signin Zone ID to new Auth AWS account , this is cause issue in Deployment of ORCh Stub.
So to Move the ORCH Stub to new Account we need to allow ingress Access in Redis session store.
Note : we only allowing this access in Devs, Build, Staging only  
=> AUT-4048: Allow ingress access to session store redis

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java
As part of the session migration work, we'd like to remove usages of `getInternalCommonSubjectIdentifier` from the shared session and instead use the orch session where appropriate. In Authentication Callback handler, we have the Auth's userinfo response, we we'll replace the usage with the subject field from this. This is fine as this is the field we use to derive the value we set on the orch session anyway
- Pulled the subject getting from Auth's userinfo response into an appropriately named variable `internalCommonSubjectId` to reduce some repetition in the handler
- Removed a `session.getInternalCommonSubjectIdentifier()` call and replaced it with using the subject from Auth's userinfo response
-  N/A minor changes
=> ATO-1321: Remove shared session `getInternalCommonSubjectIdentifier` from authentication callback handler

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/LogoutRequest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/entity/LogoutRequestTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/DestroySessionsRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/LogLineHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/LogLineHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
This PR removes usage of Session.getSessionId() from LogoutService. I've introduced a new data class `DestroySessionsRequest`, which is used in the `LogoutService.destroySessions()` method, and requires setting the session ID directly on creation. This is used by all LogoutService methods that call `destroySessions` .
LogoutRequest was also the last place that `LogLineHelper.attachSessionIdToLogs(Session session)` was used, so I've updated it to use the version of the method where you provide the sessionId …
=> ATO-1366: Remove use of session id getter from LogoutService

orchestration-canary-alarms.template.yaml
This means there must be errors in 3 consecutive minutes to alarm. It should be a better mechanism to look for anomalies.
=> BAU: Increase evaluation period on canary alarms

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
As part of the session migration work, we'd like to remove usages of getInternalCommonSubjectIdentifier from the shared session and instead use the orch session where appropriate. This updates the code in the AuthCodeHandler to use the already retrieved OrchSession instead of the previous share session.
- Renames internalCommonPairwiseSubjectId to the name we've decided to adopt -> internalCommonSubjectId
- Uses orch session instead of shared session to derive this value.
- Minor change, N/A
=> ATO-1321: Auth Code handler - use OrchSession InternalCommonSubjectId

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AuthCodeExchangeData.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeServiceTest.java
We would like to validate the client ID provided to the /token endpoint is valid for the current journey. To do this we need a way of associating an auth code with a client.
This PR adds the `clientId` field to the auth code exchange data, and updates the method signature so the `clientId` is always set.
=> ATO-1402: Store client ID in auth code exchange data

ci/terraform/oidc/reverification-result.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ReverificationResultRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaResetAuthorizeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ReverificationResultHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
Validate the state we send IPV (via the user) for MFA reset journeys is the same state IPV send when they redirect the user back to us. This helps prevent cross-site request forgery attacks.
Also clean up some unnecessary state storage.
1. Code Review
1. Deploy to an environment
1. See a successful MFA reset with IPV journey
1. Start the journey again, pause while on IPV stub page
1. Change the value of the `ClientSessionId` field value in the DynamoDB table `*-id-reverification-state` to something else (probably the latest record).
1. Continue the journey, see "Something went wrong" error
1. Start the journey again, pause while on IPV stub page
1. Change the value of the `AuthenticationState` field value in the table (will require recreating the record, AWS Console will help do this)
1. …
=> AUT-3910: Validate state back from IPV

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java
We'd like to validate whether the client id in the auth code exchange data matches the client id in the request params in the TokenHandler. 
This PR adds a log line to warn if the client ids mismatch. This is to make sure we dont have any requests currently using the wrong auth code. Once we are certain that nobody is currently breaking this validation, we can make this generate an error.
=> ATO-646: Log warning if client id in auth code does not match request params

ci/terraform/oidc/identity-progress.tf, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/lambda/BaseOrchestrationFrontendHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/state/OrchestrationUserSession.java
As part of the session migration work, we'd like to remove usages of getInternalCommonSubjectIdentifier from the shared session and instead use the orch session where appropriate. This updates the code in the IdentityProgressFrontendHandler to remove the use of the shared session getInternalCommonSubjectIdentifier. Currently this lambda is **unused** and as far as I can tell **not deployed** to the orchestration account. I have added the appropriate policy and environment variable to allow cross account access, just to ensure this lambda is not in a broken state
- Updates BaseOrchestrationFrontendHandler to ensure it has the OrchSession attached
- Updates the unused  IdentityProgressFrontendHandler to replace a reference to the shared session `getInternalCommonSubjectIdentifier`
- Not …
=> ATO-1321: Remove shared session getInternalCommonSubjectIdentifier from IdentityProgressFrontendHandler

integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SessionServiceTest.java
This PR removes usage of `Session.getSessionId()` from `SessionService`. 
There were also a few methods in `SessionService` that were only used in tests, so I've removed them and their associated tests. These were `SessionService.generateSession` and `SessionService.getSessionFromRequestHeaders`
I've also removed some getters from a test that I forgot to remove in another PR for removing session id getters (https://github.com/govuk-one-login/authentication-api/pull/5816)
Tested in dev:
- Performed a full login …
=> ATO-1367: Remove session id getter from SessionService

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
Implements logging we already have in OAuth requests to authentication, so we can see the content of the http response
=> ATO-1404: Improve logging around IPV/Doc app request failures

template.yaml
We are migrating the authUserInfo table from auth accounts to orch accounts. We want to minimise code change, so we're keeping the change within the service.
Adds policies to read and write to the new AuthUserInfo table on orch accounts, and adds those policies to the same lambdas the old AuthUserInfo table needs them for.
Successfully built and deployed to dev.
=> ATO-1389: add access policies for auth user info table

ci/terraform/oidc/identity-progress.tf
Conditionally attach the orch session cross account read role depending on the variable `is_orch_stubbed`
- Code review commit and message 
- Deploy to an orch stubbed env and confirm this deploys successfully
=> BAU: Don't attach policy when orch stubbed

integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/LogoutRequest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/entity/LogoutRequestTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/lambda/BaseFrontendHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/state/UserContext.java
As part of the session migration work, we'd like to remove usages of getInternalCommonSubjectIdentifier from the shared session and instead use the orch session where appropriate. This replaces it's usage with the logout service when handling account interventions
- Updated `handleAccountInterventionLogout` call sites to replace `session.getInternalCommonSubjectIdentifier()` calls with `OrchSession.getInternalCommonSubjectId()`
- Updated Orch owned BaseFrontendHandler to include the OrchSession on the UserContext (not related to the Auth equivalent). This is used in the ProcessIdentityHandler
- Deploy to dev and run through an identity journey using the stubs:
- Deployed to dev and go to the spinner page
- Saw logs that the ProcessingIdentityHandler executed successfully
=> ATO-1321:  Logout Service - replace getInternalCommonSubjectIdentifier from shared session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/ClientNotFoundException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/TestClientHelper.java
We would like to migrate to using the orch session for storing the session ID. Previous PRs have been slowly removing usages of the shared session sessionId getter.
This PR removes the final usages of the sessionId getter (ClientNotFoundException and InitiateIPVAuthorisationService) and removes the sessionId getter once there were no usages of it in the code.
=> ATO-1395: Remove session id getter for shared session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
This is part of the work to scope out the ClientSession table migration. See epic here: https://govukverify.atlassian.net/browse/ATO-1106
Adds logging to check if docAppSubjectId is defined. This is the only place any setter on Auths ClientSession Class is called. Orch already sets it in AuthorisationHandler, so we should be able to safely remove this. If this assumoption is correct, then we can safely just pass the client session from orch to auth, and orch can forget about it. Ie, we don't need any info from Auth to set on the ClientSession.
=> ATO-1169: check if docAppSubjectId is defined in logs

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationUserInfoStorageServiceIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthenticationCallbackUserInfoStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthenticationUserInfoStorageService.java
We are migrating the authUserInfo table from auth accounts to orch accounts. We want to minimise code change, so we're keeping the change within the service.
The first commit adds clientSessionId to the method interface, as that is the sort key on the new table. The second commit swaps to read from the new table instead of the old table
Deployed to dev. Tested several journeys and all worked ok.
=> ATO-1390: read from new auth user info table

template.yaml
The JWKS URL was incorrect for staging, this fixes it.
=> ATO-1412: Use correct JWKS endpoint URL in staging

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/ClientNotFoundException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
- Refactors how the session is setup in the StartHandler to remove the use of `addOrUpdateSessionIncludingSessionId` 
- Replaces its usage in the StartHandler with `getUpdatedPreviousSessionOrReturnNew` and removes it's usage in the integration tests.
-  Deploy to dev env (sandpit)
- Run auth acceptance tests against changes (passed)
=> ATO-1245: refactor session setting in start

template.yaml
We have migrated the Auth callback user info table to Orch accounts. The old table is no longer read from or written to, so we can safely remove these permissions. Before deleting the table on Auth accounts, I'll delete permissions on Orch's side, so the table itself has no policies attached to either the table arn or encryption key arn.
Delete the policies which give orch access to the AuthUserInfo table that lives on Auth accounts.
None
=> ATO-1391: remove old userinfo table permissions from orch

ci/terraform/auth-external-api/token.tf
AUT-4048: Updating  Auth backend url env variable in Auth token lambda for new orch stub work , This change will break the Existing orch stub we need to update the RP usr for SP acceptance test in build & Staging 
1. Code Review
2. deploy to Authdevs ./deploy-authdevs.sh -x -p     
check the env variable for auth-token-lambda is getting updated 
```
~ environment {
~ variables = {
~ "AUTHENTICATION_BACKEND_URI"                 = "https://8yikw2kek6-**vpce-01a1f8e880d273ec6**.execute-api.eu-west-2.amazonaws.com/authdev2/" -> "https://8yikw2kek6-**vpce-0b907325ae3bfe3ce.**execute-api.eu-west-2.amazonaws.com/authdev2/"
}
}
```
=> AUT-4048: Updating Auth backend url env variable in Auth token lambda

ci/stack-orchestration/configuration/integration/build-notifications/parameters.json, ci/stack-orchestration/configuration/integration/integration-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/production/build-notifications/parameters.json, ci/stack-orchestration/configuration/production/production-orch-be-pipeline/parameters.json, ci/stack-orchestration/configuration/staging/build-notifications/parameters.json, ci/stack-orchestration/configuration/staging/staging-orch-be-pipeline/parameters.json, ci/stack-orchestration/provision_all.sh
=> ATO-1413/set up build notifications

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java
For audit events in the reverification handler, add:
* phone number; and
* subject id
To ensure events emitted from here have this information populated in the relevant place in the event.
=> AUT-3976: Add missing user information to audit context

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/IpvReverificationFailureCode.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ReverificationResultHandlerIntegrationTest.java
Updates the reverification info received event with the extensions [defined in the event catalogue](https://github.com/govuk-one-login/event-catalogue/blob/main/schemas/AUTH_REVERIFY_VERIFICATION_INFO_RECEIVED.yaml) (note that the phone number country code should already be populated by the audit service for users with phone numbers).
=> Aut 3976/add details to reverification info received event

build.gradle
[CVE-2025-24970](https://github.com/govuk-one-login/authentication-api/security/dependabot/30) exposes that io.netty:netty-handler has a vulnerability
> SslHandler doesn't correctly validate packets which can lead to native crash when using native SSLEngine
This is patched in version 4.1.118.Final, which we pin as this is a transitive dependency of a few other direct dependencies we use. Over time our direct dependencies will release patched versions. At such time this pin can be removed.
1. Code Review
1. Deploy to an env and run though a sign in journey (already done)
=> BAU: Pin io.netty:netty-handler version

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
Previously, it was possible for a client to use another client's valid auth code. We want to add validation for this to prevent this from happening.
If the client id in the auth code does not match the client id in the request parameters, then a 400 `invalid_client` response will be generated.
=> ATO-646: Add client id authcode validation to token endpoint

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/IDReverificationStateHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/IDReverificationStateHandlerTest.java
Add journey-type to this event, which will only be called in the event of an mfa reset via ipv flow.
This reflects the [event schema](https://github.com/govuk-one-login/event-catalogue/blob/af0e3aacde13ba06ea5a3586ec496512d415f3e1/schemas/AUTH_REVERIFY_AUTHORISATION_ERROR_RECEIVED.yaml), although note that not all user fields have been added here, as there is some discussion as to whether they're relevant in this case.
=> AUT-3977: Add extra metadata to reverify authorisation error received audit event

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
=> ATO-1322: swap getter in reset password request

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
Part of the session id migration to AuthSessionItem.
This PR avoids using `sessionService.getSessionFromRequestHeaders()` in favor of getting the sessionId from the request headers, reusing that variable later in the handler, then getting the session using `sessionService.getSession()` to get the actual shared session.
=> ATO-1428: Remove use of session id getter in StartHandler

ci/terraform/auth-external-api/authdev1.tfvars, ci/terraform/auth-external-api/authdev2.tfvars, ci/terraform/auth-external-api/dev.tfvars
BAU: Remove the cross account Api access will add later when orch stubs are migrated to new account
1. Code Review
=> BAU: Remove the cross account Api access

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/JwkCacheEntry.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/JwkCacheEntryTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/JwksServiceTest.java
Previously, the JwkCache did not consider the algorithm of the keys. We use the cache to get an pubic encryption JWK and expect it to be using the algorithm `RSA-OAEP-256`, so if we get an encryption key with a different algorithm, the code would likely break. 
This PR adds an `algs` field to the JwkCacheEntry, which is used to fetch keys with the right algorithms. 
It's worth noting that this just ensures that if a key with a different algorithm is added, then the code wont break. This PR does not add support for encryption keys using a different algorithm to `RSA-OAEP-256` or `RS256`.
This PR also temporarily looks for encryption keys with the `RS256` alg and the `RSA-OAEP-256` alg. Currently IPV are sending us encryption keys with the `RS256` alg, so once they fix this and send us …
=> ATO-1450: Filter keys by algorithm in JwkCache

ci/terraform/ticf-cri-stub/authdev1.tfvars, ci/terraform/ticf-cri-stub/authdev2.tfvars, ci/terraform/ticf-cri-stub/build.tfvars, ci/terraform/ticf-cri-stub/dev.tfvars, ci/terraform/ticf-cri-stub/sandpit.tfvars, ci/terraform/ticf-cri-stub/variables.tf
- **AUT-4030: set `var.environment` via envar**
- **AUT-4030: tifc: Organise tfvars**
- check i've not missed anything
- check it deploys sensibly
=> AUT-4030: Un-split ticf-cri-stub tfvars

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
- Uses the auth session getter for `getInternalCommonSubjectId` to get the value instead of the shared session one
- Also updated a common test variable name 
- Code review commit 
- Branches off of https://github.com/govuk-one-login/authentication-api/pull/5810 so must be merged first
=> ATO-1322: Swap getter in AccountInterventionsHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/ClientNotFoundException.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/LogLineHelperTest.java
Part of the session id migration to AuthSessionItem
Removes the final few uses of the sessionId getter:
- Removes method signature for `attachSessionIdToLogs` that used the session Id getter
- Use existing sessionId parameter in `RedisExtension` methods.
- Replaces `UpdateProfileHandler` usage of getter with auth session id getter
- Removes the constructor for `ClientNotFoundException` which calls the session id getter.
=> ATO-1447: Remove remaining uses of session id getter

template.yaml
Part of the work to migrate the client session store to orch accounts.
This PR creates a new dynamo table for storing ClientSessions, keyed by ClientSessionId. We will use this table in subsequent PRs.
Have deployed to dev and checked the new table exists.
=> ATO-1169: Create new dynamo table for storing ClientSessions

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
=> ATO-1322: swap getter in send notification

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java
=> ATO-1322: swap getter in start handler

auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
Part of the session id migration to auth session item
`SessionService.storeOrUpdateSession` no longer calls `Session.getSessionId()`. Instead it supports passing in a session ID.
=> ATO-1429: Remove use of session id getter in SessionService

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java
The claimsRequest object is checked to be not null but an RP could attach a claim with a null userinfo, which causes a null pointer exception to be thrown.
Added a check to ensure the userinfo field is not null before calling it.
=> ATO-1405: check userInfo from claimsRequest is not null

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
This is part of the email migration work. In order to stop using UserProfile, we need to have the subjectId on the authUserInfo, even for auth-only journeys.
Always add local_account_id claim to request
n/a
=> ATO-1123: always add local_account_id claim

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
Part of work to migrate sessionId to AuthSessionItem
Removes usages of the session id getter from tests. In a lot of cases, the shared session was being mocked, so I've replaced the mocked session with a real session.
=> ATO-1430: Remove use of session id getter in tests

ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/id-reverification-state.tf, ci/terraform/oidc/mfa-reset-authorize.tf, ci/terraform/oidc/mfa-reset-jar-jwk.tf, ci/terraform/oidc/mfa-reset-storage-token-jwk.tf, ci/terraform/oidc/reverification-result.tf
These lambdas are used as part of the MFA reset journey. They are all linked to the same runbook, which 2nd-line can use to determine what to do when alarms are raised for the lambdas.
1. Code Review
2. Read the linked runbook
=> AUT-4001: Add runbook links for MFA reset alarms

shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Part of the work to migrate to using AuthSessionItem for getting the session ID.
There are now no more usages of the session ID getter in the auth shared session. This (tiny) PR is for removing the getter.
=> ATO-1431: Remove auth shared session id getter

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
=> ATO-1322: swap getter in mfa handler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
=> ATO-1322: swap getter in update profile handler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
This is part of the session migration work, specifically the email migration. User is fetched from the email address, meaning we need to have the email address to check the user, to then check the email address.
Added email address to AuthSessionItem
TBD
=> ATO-1456: add email address to AuthSessionItem

ci/terraform/auth-external-api/authdev1.tfvars, ci/terraform/auth-external-api/authdev2.tfvars, ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/dev.tfvars, ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/sandpit.tfvars, ci/terraform/auth-external-api/staging.tfvars, ci/terraform/auth-external-api/variables.tf
- **AUT-4030: set `var.environment` via envar**
- **AUT-4030: xapi: tidy up variables.tf**
- **AUT-4030: xapi: Deduplicate and tidy devenv tfvars**
- **AUT-4030: xapi: Tidy and deduplicate tfvars files**
- Check it deploys without weird changes
- check I've not missed anything
=> AUT-4030: Un-split auth-ext-api tfvars

ci/terraform/test-services/authdev1.tfvars, ci/terraform/test-services/authdev2.tfvars, ci/terraform/test-services/build-overrides.tfvars, ci/terraform/test-services/build.tfvars, ci/terraform/test-services/dev.tfvars, ci/terraform/test-services/integration-overrides.tfvars, ci/terraform/test-services/integration.tfvars, ci/terraform/test-services/production-overrides.tfvars, ci/terraform/test-services/production.tfvars, ci/terraform/test-services/sandpit.tfvars, ci/terraform/test-services/staging-overrides.tfvars, ci/terraform/test-services/staging.tfvars
- **AUT-4030: set `var.environment` via envar**
- **AUT-4030: ts: Unsplit and organise tfvars**
- check i've not missed anything
- check it deploys sensibly
=> AUT-4030: un-split test-services tfvars

shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
Adding logging to check the auth session email address migration is working as expected.
Added a log.
TBD
=> Ato 1462 add email address logging

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/IDReverificationStateHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/IDReverificationStateHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
Added metrics for MFA reset with IPV:
- Metric in ReverificationResultHandler to count the different responses returned from IPV.
- Metric in IDReverificationStateHandler to count the number of error responses returned from IPV.
Following this PR being merged an additional panel will be added on the ‘Sign In/Sign Up’ [dashboard](https://bhe21058.live.dynatrace.com/#dashboard;gtf=-7d%20to%20now;gf=all;id=1588f7b7-0df7-4730-b726-6b9320bc7cc7) to track these metrics
1. Code Review
2. Go through mfa reset journey, see metrics in cloudwatch: 
- "MfaResetIpvResponse" for regular journey and "MfaResetError" for cross brower journey
=> Aut 4062/mfa reset metrics

shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
Remove logs after check.
Checked splunk
=> ATO-1456: remove AuthSessionItem email address migration log check

template.yaml
Part of the migration of the IdentityCredentials table to Orch accounts. We are using clientSessionId (aka journeyId) as the sort key.
Added new table in IaC.
n/a
=> ATO-1469: create new identity credentials table

ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, template.yaml
Part of the work to migrate to storing client sessions in an orch dynamo table
This PR adds the relevant permissions to lambdas so they can access the new ClientSession dynamo table. Note that the lambdas aren't using the new table yet this is just for adding permissions so they can use it.
=> ATO-1418: Add permissions to access new dynamo table

ci/terraform/oidc/production.tfvars
Switch on calls to the TICF CRI in prod.
The call is enabled in all other environments and has been running without issue for many weeks.
Switching on as requested by TICF.
1. Code Review
=> AUT-2913: Switch on calls to the TICF CRI in prod

ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/userinfo.tf
We are deleting the authUserInfo table. In order to remove it, we need to delete the polices associated with it, but these exist part way through `policies_to_attach` already. Hence, we first need to define and deploy a new role first.
Creates a new role for each lambda that needs it
tbd: deploy to auth dev
https://github.com/govuk-one-login/authentication-api/pull/5928
=> ATO-1391: duplicate roles to remove auth user info policies

.pre-commit-config.yaml
=> BAU: pin golang to 1.23.6 in pre-commit

template.yaml
Part of the migration of the IdentityCredentials table to Orch accounts. I'd like to keep the names of these variables and policies, which means we need to safely rename the old ones while they're still in use.
Adds new policies and uses them.
Importantly, we don't remove/ rename the old policies. We have to keep the old policy around, as AWS might delete the policy while the new lambda version is being built. This would put the old version out of action, but the alias would still point to that version.
n/a
=> ATO-1469: rename old identity credentials table policies

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/AuthCodeException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java
This is part of the session migration work; specifically the email migration. 
Remove use of `session.getEmailAddress()`, and by extension, use of the UserProfile table.
Also has some performance improvements, as we previously made several dynamoDb calls.
Tbd: deploy to dev
=> ATO-1123: migrate email in AuthCodeHandler

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
It is conceivable that a user may be redirected with max_age at their first authorize request or, having a previous session in which they did not finish authenticating. So logging an error here is a fale positive and can be quite noisy. Downgrading to a warn
- Error log when auth_time is null is now a warn
=> BAU: Change error to warn when auth_time null

template.yaml
They are currently very noisy due to an RP erroring
=> BAU: Temporarily turn off backchannel logout alarms in prod

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
Work has started on PKCE. We wish for this work to remain behind a feature flag.
- Added new condition (`PkceEnabled`) - enabled on dev, build, and staging
- Added new env var `PKCE_ENABLED`, dependent on condition
Deployed to Orch dev, `PKCE_ENABLED` env var set to `true` (as expected)
=> ATO-1371: add PKCE feature flag

template.yaml
Part of the migration of email work
Adds permissions for the AuthCodeHandler to read from the AuthUserInfo table
n/a
=> ATO-1123: add permissions to access AuthUserInfo for AuthCodeHandler

.github/PULL_REQUEST_TEMPLATE/orch_template.md
Code wasdeployed to main where a lambda didn't have the right permission. Among other actions, this is a small one to point out to devs that careful consideration must be taken when accessing resources within a lambda.
Added a checkbox in the PR template
n/a
=> BAU: add check in PR template for correct permissions

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
Part of the identity credentials migration
Adds a log to verify that clientSessionId is always defined. We need it to access the entry in the IdentityCredentials table
N/A
=> ATO-1469: add log to verify if clientSessionId is defined

.pre-commit-config.yaml, .tflint.hcl, scripts/tflint.py
- Actually use the .tflint.hcl configuration file
- Run tflint explicitly on each directory with changed files, which
reduces the runtime significantly when oidc hasn't changed
- Filter the files to validate, to emulate the 'normal' pre-commit
behaviour - if a file hasn't been changed in a commit, it won't cause
a linting failure
- only fail on warning and above - no need to fail on notices
- Remove the tflint init hook, as it's not needed anymore
1. Introduce a linting error into a terraform file (eg. remove a type from a variable), and try to commit it - if pre-commit complains, this confirms that it's running properly
2. commit the change (`git commit -m 'test' --no-verify`)
3. Change another terraform file (eg. add an extra `\n` between two `resource` definitions), and try to commit …
=> AUT-4069: Improve tflint pre-commit hook

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
We wish to add PKCE support to the `/authorize` endpoint behind a feature flag.
PKCE should be optional to be backward compatible.
If a code challenge is provided, we wish to perform validation on both it and the code challenge method.
Code challenge validation:
- Non-blank if provided
- (We'll perform additional validation on the code verifier - not implemented at present)
Code challenge method validation:
- We wish to only support the "S256" code challenge method as "plain" offers lower security.
- A value must be provided if a code challenge value is provided
- (Otherwise the method will default to "plain" if not in the request - which we don't want to support (https://datatracker.ietf.org/doc/html/rfc7636#section-4.3))
Validation needs to be performed on the query params (if the …
=> ATO-1371: validate pkce challenge code and method on the `/authorize` endpoint

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java, oidc-api/src/test/resources/uk/gov/di/authentication/oidc/lambda/approvals/WellknownHandlerTest.shouldReturnExpectedResponseBody.approved.json
We wish to add PKCE support behind a feature flag.
The discovery endpoint needs updating to list the PKCE code challenge methods supported by this auth server.
`S256` is the only code challenge method supported.
- Supported code challenge methods now returned by discovery endpoint
- Expected endpoint response body updated to include expected `code_challenge_methods_supported` value.
Deployed to Orch dev visited `/.well-known/openid-configuration` on `oidc` subdomain, config contained expected value (below):
```json
"code_challenge_methods_supported": [
"S256"
],
```
=> ATO-1388: add supported code challenge methods to discovery endpoint

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchClientSessionServiceIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchClientSessionExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/converters/VtrListConverter.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchClientSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/OrchClientSessionException.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchClientSessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchClientSessionServiceTest.java
In a previous PR, we added a dynamoDB table for storing client sessions. We would like to migrate away from using redis to store client sessions and use this dynamo table in the orch account.
This PR creates a DynamoDB version of `ClientSession` called `OrchClientSessionItem`, and also creates a service to store, retrieve, and delete instances of `OrchClientSessionItem` to the DynamoDB table, called `OrchClientSessionService`.
=> ATO-1417: Add code to write to new client session store

template.yaml
As part of supporting PKCE, we should advertise the code_challenge_methods we support on our discovery endpoint. 
- Adds a feature flag to the lambda
- Missing feature flag defaulted to false, so no change occurred.
=> ATO-1388: Add feature flag to wellknown handler

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/GetMfaMethodsHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/helpers/CommonTestVariables.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/GetMfaMethodsHandlerTest.java
Implements a basic handler in the account management api. In this PR, we just implement a basic hello world dummy lambda. This is also not deployed anywhere at the moment, so actual logic and infrastructure to follow in subsequent PRs.
* Code review
Similar change done already for the post endpoint: https://github.com/govuk-one-login/authentication-api/pull/5992
=> Aut 3848/mfa methods retrieve hello world

deploy-dev.sh
Previously, the deploy script would error if you provided the `-c` or `--clean` flag. 
The part where the script was erroring was not actually needed anyway, so this PR removes the block and updates the usage options.
=> BAU: Fix problem with running deploy-dev script with clean flag

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ReverificationResultHandlerTest.java
We were incrementing success as well as failure metrics in the case of failure codes coming back from ipv.
Also adds some logging for visibility of the code coming back
=> BAU: Correct metrics for ipv reverification result

template.yaml
Part of the identity credentials table migration
Deleting these now unused policies.
Deployed to dev
=> ATO-1469: delete now unused policies

template.yaml
Part of the identity credentials table migration
Previously, I had planned to just name the table <env>-Identity-Credentials. However, in tests, this overlaps with the auth table. There is an urgency to get this migrated, so rather than bothering with figuring out a clever fix in tests, just rename this table to have orch prefix
Successfully deployed the dev. Deleted the old table and created a table called `dev-Orch-Identity-Credentials`
=> ATO-1469: rename table with Orch prefix

template.yaml
Part of the identity credentials migration
Refactors the now unused identity credentials policies to instead access the table on Orch accounts, and adds those policies to the lambdas in the same places the Auth equivalent currently exist
Deploying to dev now
=> ATO-1469: add policies for new identity credentials table

template.yaml
This is part of the identity credentials migration work.
In this PR, we add a resource policy onto the table to allow cross account access to it
Deployed to dev successfully
=> ATO-1469: add resource policy for cross account access

template.yaml
We had some dynamo policies in cloud formation that, when used without any other related policies, did not have enough permissions to use the AWS managed key associated with the table.
This PR ensures all dynamo policies have the minimum required permissions as defined by AWS [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/encryption.usagenotes.html#dynamodb-kms-authz):
- `kms:Encrypt`
- `kms:Decrypt`
- `kms:ReEncrypt*`
- `kms:GenerateDataKey*`
- `kms:DescribeKey`
- `kms:CreateGrant`
I've also renamed some of the policy statement `Sid`s to better describe the new permissions changes
Deployed to dev and did a full auth journey
=> ATO-1491: Add missing key permissions to dynamo policies

ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf
This is part of the identity credentials migration work.
In this PR, we add a new policy to processing identity handler to access the identity credentials table in orch accounts
TBD: deploy to sandpit
=> ATO-1469: add cross acount access to identity credentials

ci/terraform/account-management/mfa-mm-create-backup.tf, ci/terraform/account-management/openapi_v2.yaml
The OpenAPI spec needs updating to use the names changed in the previous change for this ticket.
1. Code Review
=> AUT-3484: Update the openapi spec with new names

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/IdentityStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AuthIdentityCredentials.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchIdentityCredentials.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoIdentityService.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IdentityStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthIdentityCredentials.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java
This is part of the identity credentials migration work.
In this PR, we write to the new table.
I've done some logging here to verify clientSessionId is always defined:
https://github.com/govuk-one-login/authentication-api/pull/6013
Testing in dev:
- I've ran through an identity journey in dev and have confirmed that this works
- Saw the identity credentials in the new table
=> ATO-1469: write to new identity credentials table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
- Swaps the shared session getter for internalCommonSubjectId for the AuthSession one in the verifyCode and VerifyMfaCode lambda
- Renames some variables and re-jigs some test setup to make clearer that reauth counts are stored against RP pairwise id, not internalCommonSubjectId (Auth dev confirmed this makes sense)
- These lambdas are done together as they shared a service which used a getter
- Deployed to sandpit and ran auth acceptance tests
- I borked my last branch, so this one replaces it 😆
=> ATO-1322: swap getter in verifycode/verifyMfa code handler

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java
As part of the session migration we're removing the now redundant getter for internalCommonSubjectId from the orchestration version of the shared session object
- Removes getterForInternalCommonSubjectId from the Orchestration Session object
- N/A getter was unused
=> ATO-1324: Remove Orch getter for internalCommonSubjectId

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, ci/terraform/account-management/api-gateway-method-management.tf, ci/terraform/account-management/mfa-methods-retrieve.tf, ci/terraform/account-management/openapi_v2.yaml
The openapi spec describes the endpoints with an operation id that takes the format mfa-methods-<action>.  `mfa-methods` is the endpoint name and `action` is the business name for what the User wants to do.
The operation id for retrieving an MFA Method is mfa-methods-retrieve.
The HTTP method currently being used to retrieve an MFA Method is GET as per convention.  However, this could change to a POST and search pattern in the future.  As GET is an implementation detail we have decided to avoid using it and keep our names abstract.
To ensure that the terraform modules and the Java code are grouped together in the project we will follow this style of naming.
For terraform this means all the resources created will either start with or contain `mfa-methods-retrieve`.  The terraform file that …
=> AUT-3484: Deployment of MFA Methods Retrieve

ci/terraform/shared/build-stub-clients.tfvars, ci/terraform/shared/stub-rp-clients.tf, ci/terraform/shared/variables.tf
Currently none of our stub clients have backchannel logouts enabled, however the stub does expose an endpoint to handle these. 
The build rp stub and build acceptance test rp stub now have a BackChannelLogoutUri configured. This points to the rp stub backchannel logout endpoint. 
I couldn't find another instance of an optional field being used in a type, so I added a backchannel logout uri to the sandpit stub client (`relying-party-stub-sandpit`) and ran a `terraform plan`, to check if the logic was correct. The plan finished successfully and indicated that the only change was updating the client registry to add a backchannel logout uri to the client we expected.
I also updated the build client registry to add the backchannel logout uris to the appropriate clients, and did a simple auth …
=> ATO-1373: Add backchannel logout config for build stubs

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
A previous PR added a new dynamo client session store, as well as a service to interact with the store. We would like to migrate away from using the shared redis store and use this dynamo store instead.
This PR writes to the dynamo client session store wherever we write to the redis client session store. Since there was only 1 instance of the delete method being used, i've also included deleting from the dynamo client session store in this ticket.
Deployed to dev and sandpit:
- Did a basic auth journey, saw the client session was created in the new dynamo table. 
- Logged out and saw the client session was deleted from the new dynamo table.
=> ATO-1472: Write to and delete from new client session store

ci/terraform/oidc/build.tfvars
AUT-3689: Update the IPV call backup URl for Build env post migration to new frontend 
1. Code Review
=> AUT-3689: update the IPV call backup URl for Build

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/IdentityStoreExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoIdentityService.java
This is part of the identity credentials migration work.
In this PR, we read from the new table. We continue to write to the old table
I've done some logging here to verify clientSessionId is always defined:
https://github.com/govuk-one-login/authentication-api/pull/6013
Deployed to dev:
- Ran through an identity journey - no issues observed
- Rebased main to ensure this had the latest changes in
=> ATO-1470: read from new identity credentials table

template.yaml
This PR adds missing cross-account policies for accessing the new Client Session dynamo table.
=> ATO-1415: Add missing cross-account policies on new table

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MfaMethodsRetrieveHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoMfaMethodsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthAppMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/MfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/MfaMethodData.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/SmsMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoMfaMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/MfaMethodsService.java
Implements the substantive logic for the mfa methods get endpoint. Currently, we only support non-migrated users (i.e. users with a single mfa method at most, with sms mfa details stored in the user profile table, and auth app details stored in the user credentials table.)
As part of the initiative to enable back up mfa methods, we need to implement a new api for home to use in their account management flow. This new GET endpoint supports returning multiple MFA methods for a user.
1. Code review
1. Deploy to a test environment (currently in authdev1)
=> Aut 3848/return mfa methods from new get endpoint

ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/entity/LogoutRequestTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
- We've migrated all the getters for InternalCommonSubjectId to use the OrchSession so now we need to remove any orch setters for this value 
- Removed all the setters for InternalCommonSubjectId for the Orch version of the shared session (turns out it's all test code)
- N/A: setter was only used in test code
=> ATO-1326: Remove orch setters for internalCommonSubjectId

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in StartService.
=> ATO-1467 StartService use email address from AuthSessionItem

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java
We make requests to TICF CRI, but currently do not log any helpful data for debugging and assessing requests unless they error.
Here a log is added before a request is made, dumping the payload to logs.
1. Code Review
=> AUT-2469: Log TICF CRI request payload

template.yaml
The RP causing noise has fixed their integration
We don't have these turned on in int because RPs generally struggle to integrate with this and we get a lot of alarms
> [!TIP]
=> BAU: Turn back on backchannel logout alarms

template.yaml
Due to the way we handle failed requests, this lambda errors at quite a high rate. We're going to improve the error handling, but for a temporary fix for the alarms, increase error rate
> [!TIP]
=> BAU: Increase backchannel logout error rate to 25

integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java
As part of the max age initiative we added this parameter to the client registry API, so that the SSE tool could eventually control the update of this field for clients in integration. However the current implementation is overwriting the configured value to false on any update.
- Makes the max age field on an update request a boxed boolean to stop defaulting to false.
- Code review commit
- Have added a new integration test to assert this
=> ATO-1102: Make max_age_enabled a boxed boolean

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/UpdateClientConfigRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java
- When updating the client registry this field would always default to false, so it would  always disable it
=> ATO-1521: Make jar Validation a boxed boolean

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
- Logs response mode if present, to ensure any validation we enforce won't break existing RPs
=> ATO-1020: Log response mode if present

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/MfaMethodCreateRequest.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/serialization/MfaDetailDeserializer.java, shared/src/test/java/uk/gov/di/authentication/shared/serialization/MfaDetailDeserializerTest.java
- Created MfaMethodCreateRequest object
-- Added deserializer to know which MFADetail implementation to use when reading json
- Return already existing MfaMethodData response object
1. Code Review
=> AUT-3485: Create request and response for Create MFA

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MfaMethodsRetrieveHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoMfaMethodsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UnknownMfaTypeException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoMfaMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
Updates the mfa methods dynamo service to handle returning methods for migrated users (those with all their mfa details stored in the user credentials table and the possibility for a backup method).
This necessitated adding a flag to the user profile table to indicate whether or not a user has been migrated yet.
No users will currently be in this migrated state.
Code review will be fine, when we've implemented the post endpoint we can round-trip test this.
=> Aut 3714: Mfa method management retrieve for migrated users

template.yaml
When transitioning to the new AuthUserInfo table in the orch account, the TTL attribute on the dynamo class was set to a different value to the table configuration. This was disabled in a prior PR (#6103). We now wish to update the attribute name (so that the table and class match) and reenable TTL.
- Updated the TTL attribute name on the config to match that of the class.
- Reenabled TTL on the `AuthUserInfo` table.
Deployed on dev, expired items were deleted as expected once the change was applied:
Previous PR to disable TTL: #6103
=> ATO-1507: update and reenable AuthUserInfo TTL

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java
Using the `AccountState` from the users session we determine if the authenticated session represents a new account and use that to populate the `initial_registration` field to the TICF CRI.
1. Code Review
2. Run though sign in and create journey on an environment and see that when filtering logs for the `*-account-interventions-lambda` with "Invoking TICF CRI with payload" that payload contains `\"authenticated\":\"Y\"}` for the create journey but not for sign in
=> AUT-2909: Add `initial_registration` to TICF CRI payload

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MfaMethodsRetrieveHandlerIntegrationTest.java, ci/terraform/account-management/authdev1.tfvars, ci/terraform/account-management/authdev2.tfvars, ci/terraform/account-management/build.tfvars, ci/terraform/account-management/dev.tfvars, ci/terraform/account-management/integration.tfvars, ci/terraform/account-management/mfa-methods-create.tf, ci/terraform/account-management/mfa-methods-retrieve.tf, ci/terraform/account-management/production.tfvars, ci/terraform/account-management/sandpit.tfvars, ci/terraform/account-management/staging.tfvars, ci/terraform/account-management/variables.tf, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Introduce terraform feature flags for the new mfa method management api endpoints. This replaces logic to look up the environment and disable based on that, and brings us more in line with how we do feature flags elsewhere.
The switch is off in integration and production.
1. Code review
1. If you like, you can also deploy to an env toggling the relevant tf var for that environment on / off, and test that api via api gateway. You should immediately get a 400 for either the get or post endpoint (no need to construct a body) when the flag is off, and a relevant response when the flag is on. I've already done this bit of testing so up to you if you'd also like to see.
=> Bau: move method management feature flag to terraform

orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/AuthenticationCallbackUserInfoStoreExtension.java
AuthUserInfo migration
I missed this table creation in the extension. It isn't used anywhere, so it's just an unused mock table.
n/a
=> ATO-1391: delete old table in code from extension

template.yaml
We had a specific runbook referring to one RP who had an issue with their integration. This has been fixed, so now we should use the generic runbook
> [!TIP]
=> BAU: Remove specific auth callback runbook

ci/terraform/oidc/reset-password-request.tf, ci/terraform/oidc/reset_password.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
When a user has attempted to reset their password and when they successfully reset their password it is now recorded in their session. This is then used, in combination with their authenticated state, to determine if the `password_reset=Y` attribute should be added to the payload to the TICF CRI API at the end of the users sign in journey.
This happens if either:
- the user is authenticated and has successfully reset their password
- the user is failed to sign in but attempted to reset their password
At this point the TICF CRI API is not called outside of a successful sign in, so while the code is configured for the attempted password reset, it won't be sent to TICF until we support the CRI API for non-successful sign in journeys.
1. Code Review
1. Deploy to a dev environment
1. Sign in …
=> AUT-2910: Send `password_reset` to TICF CRI API

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchClientSessionServiceIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchClientSessionService.java
We have a dynamo client session store that we are currently writing to. We are also getting from it to compare the dynamo client session to the redis client session. There have been a couple of log messages indicating that the TTL had expired for the orch client session.
We weren't updating the TTL whenever we were calling `updateStoredClientSession`. This PR updates the TTL based on the configured session expiration, just like we do when we store the client session.
Added an integration test scenario for this situation.
=> ATO-1415: Update TTL when updating orch client session

ci/terraform/oidc/api-gateway-frontend.tf
This `moved` was previously added when localstack was removed.
Now it's needed in the opposite direction for FMS migration.
Code review
=> BAU: reverse moved block

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
This is a temporary solution, replicating the logic for enabling doc app in build. This should allow us to test doc app journeys in dev.
Removes some validation on dev so we can run doc app journeys.
tbd: deploy to dev
=> BAU: enable doc app in dev

template.yaml
- Added new CMK for the new table
- Added new `OrchAuthCode` DynamoDB table
Deployed to orch dev, located the two new resources and checked their configurations against the ticket - these were as expected.
=> ATO-1184: create new orch auth code table

integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/converters/CodeRequestCountMapConverter.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
We're migrating fields from the redis session to dynamoDB, this migrates another field CodeRequestCountMap
- Adds a convertor which converts the CodeRequestCount type of `Map<CodeRequestType, Integer>` to something dynamo can store easily
- Adds the field to the session class along with the minimum required getter/setter methods. I have chose to omit the builder `withXX` method as the Auth session is instantiated with a default code request count map upon creation.
- Lifts and shifts the increment and get methods from the Session class itself, so interfaces and logic are all the same.
- Deployed to Authdev1 
- Came off the stub and saw my auth session contained a CodeRequestCount map with all keys initialised to 0
=> ATO-1511: add code request count map to auth session

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/exceptions/InvalidResponseModeException.java
There is an optional response_mode parameter that can be attached in the `/authorize` request which dictates how we format the response with the RP's redirect_uri.  This value is often confused with response_type and we see RPs accidentally set this field to invalid values in the integration environment. This causes an error at the point at which we try to redirect to the RP and does not provide any useful information as the error is unhandled. 
This PR adds validation in the authorize request that this value is either query or fragment. 
- Updates the query params validation and request object validation to explicitly validate this field is query or fragment
- Left some logging in over the weekend to validate if this field is being attached, it is not
=> ATO-1020: validate response mode if present

integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
- Adds password reset count to auth session item 
-Deployed to auth dev1
- Come off the stub, and look up your session. It has the new attribute set to 0
=> ATO-1512: Adds password reset count to auth session

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeService.java
Part of the email migration work.
Removes email address from the DocAppCallbackHandler
TBD: Deploy to dev and test a DocApp journey
=> ATO-1530: migrate doc app callback handler email on session

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
Part of the email migration work on IPVCallbackHandler
The SpotRequest object holds salt as byte[], but in this ticket, I want to refactor it to use base64EncodedSalt instead. This is because the salt on the AuthUserInfo table is stored as a base64 string, and the way we send salt on to SPOT is also as a base64 string. I'm adding this test here to verify the raw string we send to Spot is the same thing now as it is with the new refactor. The one piece of nuance is that the `writeValueAsString` method changes the "=" to "\u003d". That happens currently, and this test proves that it will continue to happen when we pass in a string rather than a byte[].
n/a
Created this test after a comment on https://github.com/govuk-one-login/authentication-api/pull/5804. I checked manually that my …
=> ATO-1117: add test for base64EncodedSalt in spot queue

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SendNotificationIntegrationTest.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in SendNotificationHandler.
=> ATO-1473 SendNotificationHandler read email from AuthSession

auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/entity/TICFCRIRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
When a user submits a MFA method code it is recorded in their session. This is then used to determine if the `2fa_method=[SMS]` or `2fa_method=[AUTH_APP]` attribute should be added to the payload to the TICF CRI API in sign in, sign up and account recovery journeys.
1. Code Review
1. Deploy to a dev environment
2. Do the following journeys (in this order helps assuming you start with an account that has `AUTH_APP` MFA method type set up)
```
sign in AUTH_APP submitted
account recovery new SMS submitted
password reset SMS submitted
sign in SMS submitted
account recovery new AUTH_APP submitted
password reset AUTH_APP submitted
sign up SMS submitted
sign up AUTH_APP submitted
Password only sign in
```
4. Filtering CloudWatch logs in the `*-account-interventions-lambda` with "Invoking TICF …
=> AUT-2912: Send `2fa_method` property to TICF CRI 

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
We would like to migrate away from the current auth client session and use the new orch client session stored in dynamo. To start, we need to remove usages of the `authRequestParams` on the auth clientSession.
This PR passes fields that are accessed on the authRequestParams as claims in the request to the auth frontend. This means that we do not need to access the authRequestParams field on the client session, and will eventually be able to get rid of it, and store these fields elsewhere.
This wont do anything at the moment, as the new claims that have been added are not being used, they will be available to the auth frontend to pass on to the auth backend though.
=> ATO-1432: Add new claims for auth frontend

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AuthCodeExchangeData.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeServiceTest.java
We recently added a new client session store to save client sessions to a dynamo table, in addition to redis, and started writing to the new store wherever we were writing to the old one. We also added logging to check whether the 2 sessions were in sync.
We found that if a user hit the `TokenHandler` endpoint multiple times, it would use an outdated view of the `clientSession`. In `AuthenticationCallbackHandler`, the `AuthCodeExchangeData` is saved with the current `clientSession`. The `TokenHandler` uses this `AuthCodeExchangeData` to get the `clientSession`, then updates the `clientSession` with an `idTokenHint` later on. 
This PR updates the TokenHandler to use the `clientSessionService.getClientSession()`, using the `clientSessionId` already in the `AuthCodeExchangeData`.
Since that …
=> ATO-1533: Get client session from clientSessionStore in TokenHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in ResetPasswordHandler
=> ATO-1479 resetpasswordhandler read email from authsessionitem

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
- We're migrating the Reset password count to the auth session from the shared session. This involves incrementing and reseting in the same places as the shared session
- Increments the password reset count in same place as shared session
- Resets the password reset count in same place as shared session
- Deployed to authdev2  
- Went on a reset password journey and repeatedly request a reset password code
- Saw count incremented and reset when hit the too many codes screen
- https://github.com/govuk-one-login/authentication-api/pull/6158
=> ATO-1512: set password reset count auth session

ci/terraform/oidc/mfa.tf, ci/terraform/oidc/send_notification.tf
- We're migrating the CodeRequestCount map to the new auth session store, as opposed to storing in the redis session store. In a previous PR we started initialising sessions with this new map, here we start writing to it by incrementing and resetting in the same places as previously.
- Adds write permissions for auth session for mfa handler 
- Adds write permissions for auth session for send notification handler
- Deployed to dev as part of https://github.com/govuk-one-login/authentication-api/pull/6142
- 
- Branches off of: https://github.com/govuk-one-login/authentication-api/pull/6141 so must be merged first
=> ATO-1511 add new write perms

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/MfaMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/exceptions/InvalidMfaDetailException.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaCreateFailureReason.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaMethodsService.java
Implements the success scenario P2 and error scenarios E2, E5, and E6
- P2: Migrated user with sms mfa only adds an auth app mfa (no OTP presented)
- E2: Migrated user with auth app mfa only attempts to add a second auth app mfa
- E5: Already have 2 MFAs
- E6: Client attempts to add an SMS MFA with the same number as an existing SMS MFA
Error scenario E1 and success scenarios P1 and P3 were implemented in a [previous pull request](https://github.com/govuk-one-login/authentication-api/pull/6121) (albeit for P1 and P3 without OTP handling).
This leaves error scenarios E3 and E4 unimplemented at the time of writing as they are based around the user having provided an invalid OTP when OTP handling has not yet been implemented.
See scenarios …
=> AUT-3485: Add scenarios for MfaMethodsCreateHandler

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/lambda/BaseOrchestrationFrontendHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchClientSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/utils/ClientSessionMigrationUtils.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchClientSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/utils/ClientSessionMigrationUtilsTest.java
We recently added logging to determine if the redis client session was in sync with the dynamo client session. We saw a few instances where the orch client session was out of sync, having null fields where it should have fields set. We wondered if this was related to the requests being eventually consistent.
If the client sessions are not in sync, we will try to fetch the orch client session from dynamo again with strongly consistent reads.
=> ATO-1419: Fetch orch client session with strong consistent reads if not in sync

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SendNotificationIntegrationTest.java
- We're migrating the CodeRequestCount map to the new auth session store, as opposed to storing in the redis session store. In a previous PR we started initialising sessions with this new map, here we start writing to it by incrementing and resetting in the same places as previously.
- Increments the map counts in the same place as the one on the shared session
- Resets the map counts in the same place as the one on the shared session
- Deployed to dev  
- Run through a signup journey 
- Saw email code incremented
- Ran through a sign in journey with auth app after this
- Branches off of: https://github.com/govuk-one-login/authentication-api/pull/6174 so must be merged first
-
=> ATO-1511: write to new code request map

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in VerifyCodeHandler.
=> ATO-1474 verifycodehandler read email from authsessionitem

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java
- Added missing assertion on JSON returned from the MFAMethodsCreateHandler
1. Code Review
=> BAU: Assert on JSON in MFAMethodsCreateHandlerIntegrationTest

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
As part of the session migration we migrated these fields from the shared session object, however there were some methods left behind. This PR cleans them up
- Removed setter/getter methods for isNewAccount
- Removed test usages
- N/A just used in test code
-
=> BAU: remove is new account methods from auth shared session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java
This is part of the session migration work, specifically the email migration. Use AuthSessionItem email address instead of Session's email address.
VerifyMfaCodeHandler uses AuthSessionItem. Minor refactoring in code and tests.
Ran tests and checked logs
=> ATO-1468 VerifyMfaCodeHandler read email AuthSessionItem

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
We migrated this field off of being used on the shared session and therefore can remove the methods from the session class for the `authenticated` field
- Removes getter and setter for authenticated which was only used in test code
- N/A just test code
=> BAU: remove authenticated shared session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
- We've started incrementing and resetting the password rest count on the auth session. Now we can swap the getter for this value to no longer use the auth sessio
- Swaps shared session `getPasswordResetCount` for Auth session equivalent
-Deployed to a sandpit:  
- Went on a reset password journey and repeatedly request a reset password code
- Saw count incremented and reset when hit the too many codes screen
- https://github.com/govuk-one-login/authentication-api/pull/6160
=> ATO-1512: get password reset count auth session

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, template.yaml
As part of the PKCE work , at the token endpoint we take the code challenge from the authRequestParams and validated by the code verifier passed through the request
Added logic in Validating code challenge and verifier
Wrapped in feature flag and code verifier non null check
Ran through RP stub 
- Look at validation logic
- Error response
- enabling PKCE logic
=> Ato 1372/update token endpoint support pkce

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SendNotificationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java
- We're migrating the CodeRequestCount map to the new auth session store, as opposed to storing in the redis session store. In a previous PR we started writing to the new Code Request map, so now we can read from it when fetching a code request count
- Replacing any calls to shared session method `getCodeRequestCount` with the auth session equivalent.
- Deployed to sandpit:  
- Run through a signup journey 
- Saw email code incremented
- Ran through a sign in journey with auth app after this
- Branches off of: https://github.com/govuk-one-login/authentication-api/pull/6174 so must be merged first
-
=> ATO-1511 read code request count  from auth session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java
We have been logging whether the redis client session has been in sync with the dynamo client session. There was one service where this logging check was missing though.
We were getting the client session in NoSessionOrchestrationService, but not logging and comparing with the new dynamo client session. This PR updates the service to compare both client sessions, also updating the tests so the logs are accurate. 
This service is not used in any handlers where we aren't already checking if the client sessions are in sync, so should not be a problem in terms of lambda permissions
=> ATO-1419: Add missing client session sync check

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/TicfCriHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/entity/ExternalTICFCRIRequest.java, shared/src/main/java/uk/gov/di/authentication/entity/InternalTICFCRIRequest.java, shared/src/test/java/uk/gov/di/authentication/entity/ExternalTICFCRIRequestTest.java, ticf-cri-stub/src/main/java/uk/gov/di/authentication/ticf/cri/stub/lambda/TICFCRIStubHandler.java
The TICF CRI API specification is fairly non-standard, and we need to do unusual things like represent booleans as strings. We should capture all of this weirdness right as the edge, and represent requests in a way that matches our domain model everywhere else.
There are some additional challenges around lambda deserialising request objects: if the keys are not camel case then lambda will not deserialise by default and you need to provide a custom mapper. We can avoid all of that complexity by simply using a sensible object internally.
1. Code review
2. Deploy to dev and give a basic test
3. Pay particular attention to ticf stub
=> AUT-2912: Introduce an internal representation for TICF CRI requests

template.yaml
Currently RP issued auth codes are stored in Redis. We are migrating away from Redis to DynamoDB. The auth code store is being migrated under the parent ticket. The lambdas writing and reading the auth code need permissions on the DynamoDB table added under #6146.
Handlers requiring write access (calls from `generateAndSaveAuthorisationCode`):
- DocAppCallbackHandler
- IPVCallbackHandler
- AuthCodeHandler
- AuthenticationCallbackHandler
Handlers requiring read access:
- TokenHandler
- Added two new policies for the OrchAuthCode table - one read, one write.
- Added policies to the lambdas above.
Note that these lambdas do not make use of these permissions yet (will be covered by a subsequent ticket under ATO-937).
Deployed to orch dev.
Checked both policies have been added. Checked the …
=> ATO-1196: add OrchAuthCode table policies

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in BaseFrontendHandler
=> Ato 1462 basefrontendhandler authsession email address

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
We're migrating the Reset password count to the auth session from the shared session. 
- Removes session getter method 
- Removes any test usages
- N/A just test code changes
=> ATO-1512: Remove getter from shared session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
We have started passing new fields to the auth frontend, with the intent of replacing the calls to ClientSession.getAuthRequestParams. They will be passed into the auth backend in this PR: https://github.com/govuk-one-login/authentication-frontend/pull/2666
We would like to consume these new fields from the frontend, and log whether they match the fields in the client session authRequestParams. They will be added to the AuthSessionItem in a later ticket.
Should merge https://github.com/govuk-one-login/authentication-frontend/pull/2666 before merging this one
=> ATO-1435: Consume new fields from auth frontend and log if they are in sync

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessorFactoryTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/TestClientHelperTest.java
Change all instances of session.getEmailAddress to authSession.getEmailAddress in some of the smaller files left with email address getters.
=> Ato 1482 misc email address authsessionitem

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/StorageTokenJwkHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
Attach the AWS request ID to the logs. This makes is easier to correlate logs for a request when no journey ID is set, and also to find the corresponding API Gateway logs. 
I've only done the OIDC API. I can follow up with the others, but that will involve changing the log template so want to separate the changes.
Deployed to dev and spot-checked a couple
=> BAU: log AWS request ID per RFC30

ci/terraform/oidc/authentication-auth-code.tf
Add Auth Session DynamoDB table write permissions to authentication-auth-code for the PreservedReauthCountsForAudit migration.
Add write permissions to authentication-auth-code for Auth Session DynamoDB table.
https://github.com/govuk-one-login/authentication-api/pull/6200
=> ATO-1513: add Auth Session DynamoDB table write permission to authentication-auth-code

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
- We've now migrated the getters and setters to use the value of `ResetPasswordCount` from the auth session. We've also removed the getters for this value so we can now stop setting it
- Removes the increment and reset calls from the ResetPasswordRequest handler 
- Removes the methods from the session class
=> ATO-1512: remove setters for ResetPasswordCount

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/TestClientHelper.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/TestClientHelperTest.java
Part of the email migration work
Deletes an unused method that was only used in tests. Those tests only verified that method worked as expected.
This was copied directly over from Auth when we initially split. It hasn't been unused or updated since.
n/a
=> ATO-1121: delete the unused isTestClientWithAllowedEmail method

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
We recently merged a PR that will accept new claims from the auth frontend, and compare them with the claims on the client session authRequestParams, logging if they are different. 
We had some trouble with the frontend part of the issue, so we had to revert those changes. However, while testing the new frontend changes I spotted an issue with the format of the `vtr_list` parameter we are expecting in the auth backend:
The format of the `vtr_list` passed from orch (in the AuthorisationHandler) is a space separated list 
e.g `"Cl.Cm P0.Cl.Cm"`
but the format of the parameter we are expecting in the auth backend (in StartHandler) is a jsonArray 
e.g `["Cl.Cm", "P0.Cl.Cm"]`
It's slightly confusing because the parameter we are looking to replace (`vtr` on the authRequestParams) is stored as a …
=> ATO-1435: Fix type of expected vtr_list parameter in StartHandler

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/converters/PreservedReauthCountsForAuditMapConverter.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
Moving PreservedReauthCountsForAudit from shared session to AuthSessionItem. Part of the session split.
Created PreservedReauthCountsForAuditMap on AuthSessionItem and set it in the same places as PreservedReauthCountsForAudit on Session.
Tested reauth journey on authdev
=> ATO-1513 set PreservedReauthCountsForAudit on AuthSessionItem

orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchAuthCodeExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeServiceTest.java
To perform consistency checks (ATO-1198), Redis and DynamoDB will need to use the same auth code when storing the data. We will use the auth code the "authorisation code service" generates, so the generation method in the "orch auth code service" needs to accept this as a parameter.
These changes can be reverted after this consistency check has been completed.
- Extracted auth code generation from the new orch auth code generation function, now accepted as a parameter
- Updated related tests.
Deployed to Orch dev without any issues. These methods aren't used at present so shouldn't have any effect.
- #6220
=> ATO-1188: accept auth code as a param to enable consistency checks

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
One of the final pieces of the email migration. Validates the email address on the auth session instead of the shared session.
Validating the email address on the auth session instead of the shared session.
Logs for the initial email migration.
=> ATO-1480 validate session auth session

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
Part of email migration
Adds temp logging for rpPairwiseId. I belive this might return false for "PUBLIC" clients (goc.uk)
n/a
=> ATO-1117: tmp log to check rpPairwiseId is the same

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java
=> ATO-1514: Add processing identity attempts to orch session

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BackChannelLogoutService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/BackChannelLogoutServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
Part of the email migration work
This PR adds rpPairwiseId to the sendLogoutMessage method interface to verify the value matches the subjectId calculated in the method. This will eventually replace calculating subjectId, which will remove the need to get UserProfile via email address, hence removing this need for session.getEmailAddress().
n/a
=> ATO-1116: verify subjects are the same

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
We recently added a vtr_list parameter, to be passed from orch to auth backend. The format of this parameter was a space separated string (e.g `"Cl.Cm P0.Cl.Cm"`). This decision was made because deserialisation of a list of strings was initially failing. We identified the cause of this failure, which was due to incorrectly serialising the list in orch.
We already use `vtr` as a custom parameter, which is in the format of a list of strings (e.g `["Cl.Cm", "P0.Cl.Cm"]`). It would be nice to keep consistent with the existing parameter, so as to not confuse us in the future. 
We have merged PRs for sending these fields from orch, and receiving these fields in auth backend, but we have not merged in the PR to pass the fields on in the auth frontend. This means that the fields are not doing …
=> ATO-1435: Make vtr_list custom param consistent with vtr custom param

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BackChannelLogoutService.java
Part of email migration
rpPairwiseId is out of sync, but the logs don't make it clear when. I'm almost certain now it's just for one clientId, but the attached client-id is misleading. If I trigger the logout from one client-id, that client-id remains attached to the logs even as I backchannel logout of another RP. 
n/a
=> ATO-1116: add more logs to verify what subjectId by clientId

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
We've migrated the getters to the auth session for this value a while ago. This removes any getters in test code and replaces them with the auth session
- Removes usages of the getter for the verifiedMfaType from the shared session 
- N/A Just test code
=> ATO-1564: cleanup verified mfa type getters

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java
We have been asked to ensure that AUTH_CODE_VERIFIED is emitted before AUTH_UPDATE_PROFILE_PHONE_NUMBER. 
This change should do that, and nothing else.
This does not change the principle that the order of audit events within a lambda function holds no meaning.
- Ensure tests prove that audit events are now emitted in the correct order
- Ensure no other functionality has changed
=> AUT-4185: Reorder audit events

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
We migrated the usage of this field to the auth session a while ago, but have kept the getters around. This removes them
- Removes any usage of the`getCurrentCredentialStrength` getter
- Removes the getter itself
- N/A just test code
=> ATO-1565: cleanup current credential strength getters

notifications/templates/account-management/en+cy/di-account-management-en-cy-added-backup-method.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-changed-authenticator-app.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-changed-default-mfa.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-changed-email.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-changed-password.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-changed-phone-number.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-confirm-your-email.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-confirm-your-phone-number.sms.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-delete-account.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-removed-backup-method.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-report-confirmation.email.notify, notifications/templates/account-management/en+cy/di-account-management-en-cy-switched-mfa-methods.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-account-created-confirmation.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-change-how-get-security-codes-confirmation.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-confirm-your-email.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-confirm-your-phone-number.sms.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-mfa-sms.sms.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-password-reset-confirmation.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-reset-password-confirmation.sms.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-reset-password-with-code.email.notify, notifications/templates/frontend/en+cy/di-authentication-en-cy-verify-change-how-get-security-codes.email.notify
Keep a copy of the notify templates
Maintains an offline backup of the templates.
The code that populates the templates is in this repo so you can trace the path of the templates variables in the code.
1. Code Review
=> BAU: Keep a copy of the notify templates

.github/workflows/pre-commit.yml
pre-commit's tools will now be cached correctly with a more lenient
cache key, allowing for partial cache reuse when dependencies change.
Also, pip caching is now enabled for pre-commit, which should speed up
the installation of pre-commit itself.
Additionally:
- Force pre-commit to run on pushes to main, to ensure the cache is
populated and kept up to date. This is required because although
branch actions can access `main`'s cache, they cannot update it.
This means that if we only run pre-commit on PRs, the cache will never
be populated or updated.
- Allow pre-commit to run on merge groups, but skip the actual checks.
This is to allow us to set 'Run pre-commit' as a required status for
PRs, but not block merges if weirdness happens - we don't want to
gate code post-merge because the …
=> BAU: pre-commit caching

ci/terraform/shared/session-manager.tf
- Resources were being created in all accounts - this was a dev setting
that wasn't removed before merging.
- The SSM alias was looking for the wrong key, because of a rename that
was only half completed.
Code review
=> AUT-4125: Sensibly create the ssm resources

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
We've migrated the getters to the auth session for this value a while ago. We've removed any usages of the getters so this removes the setters and methods from the auth copy of shared session
- Removes the setters for verifiedMfaType 
- Value is unused on the shared session
=> ATO-1564 cleanup verified mfa type setters

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java
- We've removed setting this value in auth and the setters and getters were unused in orchestration. This removes them
- Removes setter usages from tests 
- Removes methods from session class
- Just test code
=> ATO-1564: remove methods from Orch shared session

ci/cloudfront-orchestration/cloudfront/build/tags.json, ci/cloudfront-orchestration/cloudfront/dev/tags.json, ci/cloudfront-orchestration/cloudfront/staging/tags.json
=> BAU: Add tags to cloudfront template to allow WAF migration

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java
Part of the split session work. Migrating PreservedAuthCountsForAudit onto AuthSessionItem from shared Session.
PreservedAuthCountsForAudit is now gotten from AuthSessionItem.
Ran a reauth journey on dev env
=> ATO-1513: get PreservedAuthCountsForAudit from AuthSessionItem

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/testsupport/helpers/OrchAuthCodeAssertionHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java
~~NOTE: This is dependent on #6221 being merged first.~~ - merged
A new entity and service has been previously added under #6220. Write policy was added to this lambda under #6190.
This work stores the auth code in DynamoDB for the Authentication Callback lambda using the new service. Note that we do not wish to remove the Redis setter call - this will be done under ATO-1218.
- Added call to the `generateAndSaveAuthorisationCode` method on the orch auth code service
- Added test stubs for the new orch auth code service
Deployed to Orch dev, ran through an auth only journey on sandpit. Observed a request being made to the …
=> ATO-1188: set orch AuthCode in Authentication Callback lambda

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/processing-identity.tf, template.yaml
We're planning to start writing the value of processing identity attempts in the orch session in the processing identity handler (and identity progress frontend handler, but unused). This requires us to setup the permissions to be able to do the cross account write for these lambdas
- Adds new role with cross account write permissions for processing identity handler 
- We will swap to the unused role in a subsequent PR
- Deployed to sandpit and ran through identity journey
=> ATO-1514: add cross account write policy

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
A new entity and service has been previously added under #6220. Write policy was added to this lambda under #6190.
This work stores the auth code in DynamoDB for the Doc App Callback lambda using the new service. Note that we do not wish to remove the Redis setter call - this will be done under ATO-1218.
- Added call to the `generateAndSaveAuthorisationCode` method on the orch auth code service
- Added test stubs for the new orch auth code service
Deployed to Orch dev, ran through a valid doc app journey (doc app sandpit, selected valid passport). Observed a request being made to the `doc-app-callback` endpoint (for this Doc App …
=> ATO-1190: set orch AuthCode in Doc App Callback lambda

ci/terraform/shared/outputs.tf, ci/terraform/utils/authdev1.tfvars, ci/terraform/utils/authdev2.tfvars, ci/terraform/utils/dev.tfvars, ci/terraform/utils/mfa_method_analysis_lambda.tf, ci/terraform/utils/sandpit.tfvars, ci/terraform/utils/shared.tf, ci/terraform/utils/staging.tfvars, ci/terraform/utils/variables.tf, utils/src/main/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandlerTest.java
We need to assess MFA property values across two DynamoDB tables in production to be confident we have not missed any combinations in our understanding before continuing part of the method management work.
Here this initial lambda will be tested in staging. It contains the logic for the more complex data fetch we'll need to do. After testing we can expand on what the lambda is doing with the data.
This lambda exists so we do not need to access any prod data directly. The lambda is expected to return the analysis results, not the source data itself.
1. Code Review
=> AUT-4123: Initial mfa property analysis lambda

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/testsupport/helpers/OrchAuthCodeAssertionHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
A new entity and service has been previously added under #6220. Write policy was added to this lambda under #6190.
This work stores the auth code in DynamoDB for the AuthCode lambda using the new service. Note that we do not wish to remove the Redis setter call - this will be done under ATO-1218.
- Added call to the `generateAndSaveAuthorisationCode` method on the orch auth code service
- Added test stubs for the new orch auth code service
- Added unit and integration tests for checking we are (or are not) writing to the new DynamoDB table
- Added method overload to test assertion helper to accept a response location header string …
=> ATO-1215: set orch AuthCode in AuthCode handler

ci/terraform/oidc/processing-identity.tf
- In a previous PR we created a new role, now we can swap to it. This gives the processing identity handler write access to the orch session. 
- The previous PR also added the resource policies to the CMK and table to make these cross account actions possible
- Swaps to new role `ipv_processing_identity_role_with_orch_session_table_read_write_delete_access` for processing identity handler
- Deployed to sandpit and ran through an identity journey
- https://github.com/govuk-one-login/authentication-api/pull/6211
=> ATO-1514: Swap to new role

ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchClientSessionItem.java
We need to have access to the publicSubjectId in Orchestration. This is currently done by getting it from UserProfile, which we won't have access to. Hence, we need to add it onto the OrchClientSession. It is currently a claim we request from Auth if the "am" claim is present ("Account Management").
Added a field to OrchClientSession and set to it AuthenticationCallbackHandler
n/a
PR to always request publicSubjectId for clients with a PUBLIC subjectType https://github.com/govuk-one-login/authentication-api/pull/6271
=> ATO-1567: add public subject id to orch client session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
Part of the session migration. Removing preservedReauthCountsForAudit from shared session
Remove all instances of preservedReauthCountsForAudit from Session.
Ran reauth journey and checked logs from previous PRs. Checked this isn't used in orch (which it isn't).
=> ATO-1513: remove preservedReauthCountsForAudit from Session

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
A new entity and service has been previously added under #6220. Write policy was added to this lambda under #6190.
This work stores the auth code in DynamoDB for the IPV Callback lambda using the new service. Note that we do not wish to remove the Redis setter call - this will be done under ATO-1218.
- Added call to the `generateAndSaveAuthorisationCode` method on the orch auth code service
- Added test stubs for the new orch auth code service
- Added unit and integration tests for checking we are (or are not) writing to the new DynamoDB table
- Fixed broken unit test - see d92fc3b76b463cdbdd5d2b4f516d2eb3304f8c52
Deployed to Orch …
=> ATO-1189: set orch AuthCode in IPV Callback lambda

utils/src/main/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandlerTest.java
Last commit was an improvement, but we're being throttled by running a single BatchGetItem request at a time.
Here we use a ForkJoinPool to allow some parallel requests.
1. Code Review
=> AUT-4123: Use ForkJoinPool to parallel BatchGetItem

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchAuthCodeExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java
~~Note: Wait for #6250 to be merged~~
We're now writing to the new DynamoDB table using the new service in the four lambdas: #6278, #6250, #6244, #6223.
We wish to read from the DynamoDB table, using the new service, in the TokenFunction lambda. The DynamoDB table read policy was added to the `TokenFunction` CloudFormation under #6190.
We wish to check the consistency of this data compared to that retrieved from the Redis store. Note that we do not wish to remove the Redis getter call (as this should remain the primary) - this will be done under ATO-1205.
- Added call to the `getExchangeDataForCode` method on the orch auth code …
=> ATO-1198: add orch AuthCode consistency checks

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java
- We're now migrating the processing identity attempts field to the orch session from the redis one. We have previously setup the new field on the Orch session object and added the cross account write permissions. We can now increment and reset this value in the same places as the redis one. 
- Processing Identity Handler now increments and resets the `ProcessingIdentityAttempts` field and writes the value to the Orch session store
- Same for Identity Progress Frontend Handler - although is unused in production
- Noticed when handling a copying a max_age session we're not resetting the processing identity attempts value on the shared session, see commit: [ef2ace2](https://github.com/govuk-one-login/authentication-api/pull/6212/commits/ef2ace243efe818d7b2b0e0469a35e6656cf3e12). I've …
=> ATO-1514: increment and reset processing identity count

ci/terraform/account-management/mfa-methods-retrieve.tf
Needed in order to add an mfa identifier for a non-migrated user on get
=> AUT-4122: Add write permissions for the mfa methods retrieve handler

utils/src/main/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/MFAMethodAnalysisHandlerTest.java
One statistic we need to check is if there are any users that have enabled an AUTH_APP MFA method but with no verified AUTH_APP or SMS MFA methods.
This commits updates the query to only return the data we need to do that calculation from the user-credentials scan and user-profile batch get items.
A new class `MFAMethodAnalysis` is used to collate the statistic across forked batches and is returned by the handler as a string.
1. Code Review
=> AUT-4123: Count AUTH_APP enabled users with no verified MFA methods

ci/cloudfront-orchestration/cloudfront/build/tags.json, ci/cloudfront-orchestration/cloudfront/dev/tags.json, ci/cloudfront-orchestration/cloudfront/integration/tags.json, ci/cloudfront-orchestration/cloudfront/staging/parameters.json
=> BAU: Disassociate staging WAF

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
We previously added this field to the orch session and incremented and reset it's value in the appropriate handlers. However we forgot to reset it in the case of returning users
Our previously introduced consistency logs indicated these values were out of sync some of the time. This was because we did not reset the value when updating an existing orch session in the same way we do in the `UpdateWithNewSessionId` method. This meant that for users returning after an identity journey did not have this value reset when updating their existing Orch session
- Added a unit test to ensure this is now covered
=> ATO-1514: Reset attempts when updating existing session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
We would like to eventually remove the auth client session. To do so we need to send fields from orch to the auth backend in order to replace the auth client session usages.
We initially replaced the whole `vtr` list in the client session auth params with a field in the auth backend. However, we had a couple of issues when testing and deploying it. We also realised that we dont really need the whole vtr list, as auth only need it for the MfaHelper and the IdentityHelper.
The MfaHelper only needs the credential trust level (which we already send through to the auth backend in the `confidence` field). 
The IdentityHelper uses the vtr to calculate whether identity is required. This uses the level of confidence on the lowest requested vtr. We need this level of confidence in some cloudwatch …
=> ATO-1422: Receive new claims in auth backend

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchSessionServiceIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java
- We're migrating this field to the orch session item, and therefore we need to add the attribute to the dynamo object
- Adds Client Sessions to the OrchSessionItem
- N/A just adding new attribute to item
- Sonar is complaining about low coverage of unused methods
=> ATO-1515: Add client sessions to orch session item

integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java
Wider context of change:
We're now migrating the processing identity attempts field to the orch session from the redis one. We have previously setup the new field on the Orch session and have been incrementing and resetting in the same places. We also added consistency logging to ensure the values were the same. 
What’s changed:
- Swaps to using the orch session for this value instead of the shared session
- Removes setting as this is only done in one handler
- Added logging in a previous PR and can see the values are now in sync
- Deployed to dev and ran through an identity journey
=> ATO-1514: get processing identity attempts orch session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
We introduced validation of the response_mode previously, to align with the OIDC spec and handle an exception that was being thrown.
However, we added this to the end of the of the respective validation which mean that when we redirected in any other invalid request error cases we were not handling the invalid response mode. The spec says we should return a Bad Request in any cases we don't understand this field, and therefore we need to validate it first given it dictates __how__
we should return responses to the RP.
- Moves response_mode validation to before redirecting errors 
- Removes an unused test method
- N/A
=> BAU: move response_mode validation earlier

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
We have started to send fields to the frontend to replace the need for the client session. We have been sending the level of confidence of the requested VTR, but were mapping a `null` level of confidence to `NONE`. I don't think it makes much of a difference at the moment, however it makes sense to send the exact value of this field, to differentiate an RP sending us a request with no LOC, from an RP sending us a request with a P0 LOC.
This PR makes the claim `requested_level_of_confidence` an optional claim. The tests have also been updated to reflect this
=> ATO-1422: Pass exact value for LevelOfConfidence to auth frontend

integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
Following on from an investigation we have determined that we need to ensure only verified AUTH_APP MFA methods are returned. We had previously determined that we have no way to allow users to get into this state in our existing application (AUTH_APP records are only added after being verified).
However, an analysis of prod data with the MfaMethodAnalysisHandler shows we have some users in this state. Without this change those users could get locked out of their account.
1. Code Review
=> AUT-4245: Only return AUTH_APP method when verified

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeServiceTest.java
We're now writing to the new DynamoDB table using the new service in the four lambdas: https://github.com/govuk-one-login/authentication-api/pull/6278, https://github.com/govuk-one-login/authentication-api/pull/6250, https://github.com/govuk-one-login/authentication-api/pull/6244, https://github.com/govuk-one-login/authentication-api/pull/6223.
Redis is still the primary, but we are now reading from the DynamoDB table, using the new service, in the TokenFunction lambda to check data consistency (#6287). There are a very small number of instances where no item is found in the DynamoDB table, despite the item being stored. This is …
=> ATO-1205: fallback to strongly consistent reads during orch auth code retrieval

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/TokenHandler.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/TokenHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationAuthCodeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationTokenHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoAuthCodeServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthCodeExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeStore.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoAuthCodeService.java
- Front end sends journey ID in request headers
- This is saved to the auth code store
- Used in the TokenHandler to populate client session ID in Audit Context
1. Code Review
2. Deploy to dev, run through a sign in journey and see the new journey ID field populated against your email in the auth code store
=> AUT-2138: Add journey ID to AUTH_TOKEN_SENT_TO_ORCHESTRATION audit context

integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IdentityProgressFrontendHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java
We are in the process of migrating this field from the shared redis session to the Orchestration only DynamoDB session. Now that we're reading the value in the processing identity handler from the new session store, we can remove other usages of methods which set this value. This removes usages of the reset method and any test usages of the increment methods
- Removes resetting the value in the authorise handler, given we're not reading it anymore in processing identity handler, we can remove resetting it here. 
- Removes test usages of the increment methods
- Removes the session class methods as they're now unused.
- N/A just removes setting a now unread field
=> ATO-1514: remove processingIdentity attempts methods from shared session class

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchAuthCodeExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthorisationCodeServiceTest.java
**NOTE:**
- Merge dependent on results of consistency checks (#6287)
- Merge dependent on results of #6316
- Might be easiest to review this PR commit by commit
We're now writing to the new DynamoDB table using the new service in the four lambdas: https://github.com/govuk-one-login/authentication-api/pull/6278, https://github.com/govuk-one-login/authentication-api/pull/6250, https://github.com/govuk-one-login/authentication-api/pull/6244, https://github.com/govuk-one-login/authentication-api/pull/6223. We are reading from the DynamoDB table, using the new service, in the TokenFunction lambda (#6287), but not using the retrieved …
=> ATO-1205: use orch auth code store in token handler

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This is part of the session migration work. Here, we begin the migration of IPVCallbackHandler away from using UserProfile and to using AuthUserInfo instead. A lot has needed to happen before this PR can be raised, from destroying orch session on logout, to migrating the AuthUserInfo table itself to orch. There is still some uncertainty with rpPairwiseId, but I want to get some of this over the line.
In a nutshell, move from using UserProfile to using AuthUserInfo. That required a lot of detangling, as a lot of properties on UserProfile are used. Here, we migrate internalCommonSubjectId and move getting authUserInfo to higher in the handler, throwing if we can't find it.
**TBD**: Deployed to dev and tested an identity reuse journey worked
The original PR with all the change in one: …
=> ATO-1117: add auth user info and migrate icsid

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/DocAppJwksExtension.java
The Authorisation handler tests were a bit hard to read so I've moved them into feature specific nested test classes to make them more readable
- N/A just moving some tests around
=> BAU: Group Authorisation Handler tests by feature

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java
~**MERGE NOTE: ATO-1205 (#6308) must be merged before this work as this Redis will still be the primary at that point and there is no fallback in place.**~ - merged
In prior work, we are writing and reading to the new DynamoDB table (using the new orch auth code service) alongside the Redis calls.
Following consistency checks, added in #6287, we now wish to remove the Redis setter call from the handlers, so we're only writing to the DynamoDB.
This PR removes the Redis references in the auth callback lambda.
- Replace call to the `authorisationCodeService` with a call to the `orchAuthCodeService`
- Remove references to …
=> ATO-1218: remove Redis auth code setter in auth callback

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaCreateFailureReason.java
The rule that you cannot create a new DEFAULT MFA Method is only true in account-management api.  The MFAMethodsService can be used to create a new DEFAULT method, for example during sign-up.
Moving this check into the MFAMethodsCreateHandler enforces the rule for updates to existing Users who must already have a DEFAULT method.
1. Code Review
2. Deploy to a dev environment and use the http file to try to create a DEFAULT method.
=> BAU: Move cannot create default MFA rule

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
~**MERGE NOTE: ATO-1205 (#6308) must be merged before this work as this Redis will still be the primary at that point and there is no fallback in place.**~ - merged
In prior work, we are writing and reading to the new DynamoDB table (using the new orch auth code service) alongside the Redis calls.
Following consistency checks, added in #6287, we now wish to remove the Redis setter call from the handlers, so we're only writing to the DynamoDB.
This PR removes the Redis references in the auth code lambda.
- Replace call to the `authorisationCodeService` with a call to the `orchAuthCodeService`
- Remove references to …
=> ATO-1218: remove Redis auth code setter in auth code handler

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java, ci/terraform/account-management/mfa-methods-create.tf, ci/terraform/account-management/mfa-methods-update.tf, integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/MfaDetailDeserializer.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/MfaMethodCreateOrUpdateRequest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/RequestAuthAppMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/request/RequestSmsMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/MfaMethodResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/ResponseAuthAppMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/response/ResponseSmsMfaDetail.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/test/java/uk/gov/di/authentication/shared/serialization/MfaDetailDeserializerTest.java
Reinstates changes made in this [pull request](https://github.com/govuk-one-login/authentication-api/pull/6349) that implements OTP verification to the MFA methods put and create handlers. This pull request also adds permissions to get parameters from SSM.
=> AUT-4134: Add redis SSM policy

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
Part of the rpPairwiseId migration work. There are currently no clients that have a "public" subjectType that also go to identity, so this is not a bug. However, it is fragile, as if that were turned on, this would be the wrong value. I also want to make orchClientSession.getRpPairwiseId() to be private if possible so no dev uses it accidentally.
The log being removed here showed these two values are always the same, see [logs here](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20message%3D%22is%20rpPairwiseId%20the%20same%20as%20pairwiseIdForClient*%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=1744239600&latest=1744758000&display.page.search.tab=events&display.page.search.patterns.sensitivity=0.866&displ …
=> ATO-1596: migrate authcode to get correct pairwise

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This is part of the rpPairwiseId migration work. 
Swap to getting rpPairwiseId from the orchClientSession instead of calculating it.
Deployed to dev and tested:
- a full identity reuse journey
- a silent login identity reuse journey
I have verified that rpPairwiseId's are in sync in the logs [here](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20message%3D%22is%20rpPairwiseId%20the%20same%20on%20clientSession%20as%20calculated%3A*%22%20AND%20loggerName%3D%22uk.gov.di.authentication.ipv.lambda.IPVCallbackHandler%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=1744239600&latest=1744758000&display.page.search.tab=events&display.page.search.patterns.sensitivity=0.866&display.general.type=events&display.visualiza …
=> ATO-1596: migrate ipv callback to get pairwise id from client session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/CommonTestVariables.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/test/java/uk/gov/di/authentication/shared/conditions/MfaHelperTest.java
Allow a user with migrated mfa methods (i.e. methods stored under the new structure in user credentials, supporting multiple methods for a user) to sign in with their default method, by returning the correct method in all the places we respond from the frontend api with this information. No change for non-migrated users.
How to review:
1. Code review
=> Aut 4205/migrated user default method signin

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/testsupport/helpers/SpotQueueAssertionHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTRequest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/entity/SPOTRequestTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This is part of the session migration work. Here, we begin the migration of IPVCallbackHandler away from using UserProfile and to using AuthUserInfo instead. A lot has needed to happen before this PR can be raised, from destroying orch session on logout, to migrating the AuthUserInfo table itself to orch. There is still some uncertainty with rpPairwiseId, but I want to get some of this over the line.
In a nutshell, move from using UserProfile to using AuthUserInfo. That required a lot of detangling, as a lot of properties on UserProfile are used. Here, we just migrate salt.
Deployed to dev and tested an identity reuse journey worked
Verified values are in sync in logs [here](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20message%3D%22is%20s …
=> ATO-1117: migrate salt

client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Channel.java
Auth can only process this in lower case
---
=> BAU: Call to lower case on channel

ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/DestroySessionsRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BackChannelLogoutService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/BackChannelLogoutServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
Part of the email migration work
This PR replaces the calculation for rpPairwiseId with its value on the orchClientSessionItem. This removes the need to get UserProfile via email address, hence removing this need for session.getEmailAddress().
This got blocked for a while, as there were 3 issues with rpPairwiseId being out of sync that needed addressing:
1) [rpPairwiseId isn't always rpPairwiseId - it is sometimes publicSubjectId](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20message%3D%22subjectId%20is%20publicSubjectId*%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=1743375600&latest=1744066800&display.page.search.tab=events&display.page.search.patterns.sensitivity=0.866&display.general.type=events&disp …
=> ATO-1116: get rpPairwiseId from client session in logout helper

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/logging/LogEventMatcher.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RedirectService.java, template.yaml
We don't always log at error level when we redirect to the frontend error page. This PR moves the error logging into the method itself, so we're consistently logging when a user sees an error.
This PR also increased the threshold for auth callback logging alarms, as we've added additional error logs in this lambda, and adds doc app callback error alarms. I've check the logs and this level should be above the baseline but low enough to spot any issues.
How the new logs look in cloudwatch:
=> ATO-1588: Update frontend error redirect logging

template.yaml
SpotResponseFunction is one of our few lambdas which doesn't use redis and therefore is a good candidate for testing out snapstart. We'd like to sequentially enable this per environment to test out the effect of cold starts vs restores on this function. Looking in our logs we can see the average [INIT_DURATION for the SPOT response handler is approx ~3.5 seconds.](https://gds.splunkcloud.com/en-GB/app/gds-050-digital-Identity/search?q=search%20index%3D%22gds_di_production%22%20%22*Init%20Duration*%22%20%20di_account_name_enriched%3D%22di-orchestration-production%22%20log_group%3D%22%2Faws%2Flambda%2Fproduction-spot-response-lambda%22%20%20%7C%20rex%20field%3D_raw%20%22Init%20Duration%3A%20(%3F%3CcoldStart%3E.*%3F)%20ms%22%20%7C%20stats%20avg(coldStart)&display.page.search.mode=verbose&disp …
=> ATO-1535: Enable snapstart on spot response in some envs

ci/terraform/shared/iam.tf
We allow cross account roles for build and staging to allow our acceptance tests to run (as they need to touch both accounts while we are in a partial secure pipeline migration).
Here dev support is added so we can run the acceptance tests against it too.
1. Code Review
=> BAU: Allow dev cross account role

account-management-api/src/main/java/uk/gov/di/accountmanagement/helpers/MfaMethodResponseConverterHelper.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/helpers/MfaMethodResponseConverterHelperTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/MFAMethod.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaRetrieveFailureReason.java
We currently have two ways of representing an mfa method in the shared project:
* MFAMethod - which represents the item stored in the database; and
* MfaMethodResponse - which is a representation of the response we return for mfa methods in the method management api.
Originally this second object was introduced as a generic representation of the mfa method that could be used in both the account management api and the frontend api, but:
* we want to decouple these apis as much as possible; and
* there are slight differences in the data required by them (for example, the frontend api only ever returns a partially obscured phone number)
This PR, therefore, is the first step in moving the MfaMethodResponse from shared into the account management api. It focuses on the retrieve mfa methods …
=> Bau: Return MFA Method from getMfaMethods, rather than response data object

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
We're migrating the Client Session list away from the redis session in Orchestration. Authentication should not be concerned with the Client Session and therefore we will not be adding this field to new Auth dynamo session. Here we're removing some previous behaviour in the start handler that _reset_ the shared session and added the current client session back to it. This behaviour is also becoming increasingly redundant as we move away from the shared session.
- Removes the method `createNewSessionWithExistingIdAndClientSession` which previously handled resetting the shared session when there was no user profile present.
- Removes the methods for client session on the auth session class
- Repeated the steps outlined in commit: https://github.com/govuk-one-login/authentication-api/commit/3 …
=> ATO-1515: remove auth setter for client session

oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/PostRequestFailureException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java, template.yaml
We want to improve the back channel logout logic to send an alarm if it fails.
New cloudwatch alarm and HttpRequestService now throws if status isn't 200
Tested on dev with a stub with backchannel logout url. Also removed authorize lambda to test it passes too.
=> ATO-1481: improve back channel logout

integration-tests/src/test/java/uk/gov/di/authentication/services/OrchClientSessionServiceIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchClientSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/utils/ClientSessionMigrationUtils.java
Part of the rpPairwiseId migration. This was an offshoot of ATO-1117, the email migration. RpPairwiseId got complex enough that it deserved it's own ticket and PRs.
- Replaced the remaining uses of `getRpPairwiseId` and `getPublicSubjectId` on the orchClientSession with `getCorrectPairwiseIdGivenSubjectType`. These were in tests and a temporary log helper.
- Add a comment to the `getRpPairwiseId` and `getPublicSubjectId` methods to not use them directly. If we still want to access each individual one, this should be done  by passing in the necessary subjectType into `getCorrectPairwiseIdGivenSubjectType` (eg to get exactly rpPairwiseId, can get it via `getCorrectPairwiseIdGivenSubjectType("pairwise")`, as I have done in the first commit on this PR). 
tbd: depoy the dev. I am 99% confident …
=> ATO-1596: migrate in tests and add comment to not use methods directly

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Much like a previous change: 2f76c04469f94ae10f0fb40c57f1acdae9f9514a it would be nice for us to organise tests in a more readable fashion by grouping relevant tests in nested test classes. 
- Just re-organises the authorisation handler tests file. Might be nice to look at locally as the total diff is a bit gnarly
- N/A just test code reorganisation
=> BAU: reorganise authorisation unit tests

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This is part of the session migration work. Here, we continue the migration of IPVCallbackHandler away from using UserProfile and to using AuthUserInfo instead. A lot has needed to happen before this PR can be raised, from destroying orch session on logout, to migrating the AuthUserInfo table itself to orch. There is still some uncertainty with rpPairwiseId, but I want to get some of this over the line.
In a nutshell, move from using UserProfile to using AuthUserInfo. That required a lot of detangling, as a lot of properties on UserProfile are used. Here, we continue the migration and move LOCAL_ACCOUNT_ID over to using AuthUserInfo
Deployed to dev and tested an identity reuse journey worked
Verified in logs that LOCAL_ACCOUNT_ID and UserProfile.getSubject() are in sync …
=> ATO-1117: migrate LOCAL_ACCOUNT_ID

template.yaml
We previously enabled SnapStart on the SpotResponse handler and we are now happy with the results and therefore will enable this in integration and production.
- Enables SnapStart on SPOT response handler in integration and production envrionments
- Reviewed the logs in staging before and after this feature was enabled and asserted a restore is much faster than a cold start
=> ATO-1535: Turn on snapstart for spot response in int and prod

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/LogoutRequest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java
We're migrating this field from the shared session to the Orch session. We want to check these values are in sync, and previously added logging in the authorisation handler. This adds some additional logging in other handlers.
- Adds logging to Auth callback handler
- Adds logging to logout handler
- N/A just logging
=> ATO-1515: add more logging client sessions

template.yaml
Failed POST requests for the back channel logout get added to a DLQ. Current retention period for the DLQ is 6hrs. We want to increase it to 3 days. Minor issue of time spent in the queue before moving to the DLQ is included in the retention period (and the queue's retention period is 14 days) but we don't expect the message to stay in the queue for that long. It's also not a huge issue if we do miss the back channel logout due to logs and this being mostly for awareness than action.
Retention period has changed from 6hrs to 3 days.
N/A
=> ATO-1481: increase back channel logout DLQ retention period to 3 days

ipv-api/src/main/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelper.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/helpers/IPVCallbackHelperTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
This is part of the session migration work. Here, we continue the migration of IPVCallbackHandler away from using UserProfile and to using AuthUserInfo instead. A lot has needed to happen before this PR can be raised, from destroying orch session on logout, to migrating the AuthUserInfo table itself to orch. There is still some uncertainty with rpPairwiseId, but I want to get some of this over the line.
In a nutshell, move from using UserProfile to using AuthUserInfo. That required a lot of detangling, as a lot of properties on UserProfile are used. Here, we continue the migration and move email and phone number over to using AuthUserInfo.
This is the final property that needs migrating in IPVCallbackHandler, so we also do some cleanup to remove UserProfile.
Deployed to dev and tested an …
=> ATO-1117: migrate email and phone number

account-management-api/src/main/java/uk/gov/di/accountmanagement/helpers/MfaMethodsMigrationHelper.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/helpers/MfaMethodsMigrationHelperTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
We have four new endpoints in the the account management api for managing mfa methods, which map to the basic CRUD operations.
Whether or not these work on non migrated users differs by endpoint. A non-migrated user is a user who can only have at most one mfa method, and where that method is stored - user credentials table or user profile table - varies on what type of MFA method that is.
* CREATE migrates[1] users before acting on them
* GET works on migrated and non migrated users
* DELETE will return a failed http status if attempting to act on a non migrated user. (This makes sense since you can't delete if you only have a default method, which is what non-migrated users have)
[1] By migration, we mean that we move any sms mfa methods into the user credentials table, remove traces of …
=> Aut 4234/migrate users before put

ci/terraform/oidc/processing-identity.tf
Clean up for ATO-1514, where we migrated the processingIdentityAttempts to orch session. This required access to write to the orch session.
Deleted the unused module
n/a
=> ATO-1514: remove old unused duplicated role

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/mfa/AuthAppMfaMethodResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/mfa/MfaMethodResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/mfa/SmsMfaMethodResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/MfaMethodResponseConverterHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/serialization/MfaMethodResponseAdapter.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/helpers/MfaMethodResponseConverterHelperTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/serialization/MfaMethodResponseAdapterTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/SerializationService.java
`LoginHandler` now returns an array of `MfaMethodResponse` as `mfaMethods`. This is a list of active MFA methods the user has set up, whether they have added a backup MFA or not.
This will be used by the frontend to show the user their options when choosing a different MFA method.
1. Code review, commit-by-commit
=> AUT-1416: Return `mfaMethods` in `LoginHandler`

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java
Part of the email migration work. If these values are in sync, then we don't need to replace UserProfile with anything, and can just migrate to using these values already present in the handler.
Just some logging to check some values.
N/A
=> ATO-1128: add logs to verify values are in sync

ci/terraform/oidc/alerts.tf, ci/terraform/oidc/variables.tf
Add a separate alert threshold for the notifications DLQ
There is no need to trigger an alert for each individual message on the DLQ.  Three attempts are made to send the message before it ends up on the queue.  Action should only be taken if there is another indication of an issue.
See https://govukverify.atlassian.net/wiki/spaces/LO/pages/4164649233/BAU+Daytime+Support+Hygiene+and+Optimisation+Rota#SUP-7%3A-Resolve-DLQ-messages
1. Code Review
1. Deploy to a test environment.
1. Run a test and try to send messages to an invalid number at least 10 times.  You can do this by updating the number for your account in the database and trying to sign in.
1. Check that the alarm is triggered in cloudwatch.
=> Alert0010983: Add a separate alert threshold for the notifications DLQ

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/entity/LogoutRequestTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/OrchSessionExtension.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/SessionServiceTest.java
We previously swapped over to using the Client Session list from the Orch session instead of the shared session. This is the final PR in the migration removes setting the value on the shared session.
- Removes addClientSession call in authorisation.
- Removes resetClientSessions call in handling a max age session in authorise.
- Removes test usages of the methods 
- Removes methods from session class
Deploy to dev
- Run through a full journey + logout 
- Run through a max_age journey and logout
=> ATO-1515: Stop setting client session list on shared session

integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/lambda/BaseFrontendHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/state/UserContext.java
Final migration in the email migration work. Migrates ProcessingIdentityHandler.
- Swaps getting email from the session to the request. 
- Swaps getting internalCommonSubjectId from calculating via UserProfile to getting from the orchSession.
- Removes the now unused UserProfile from the handler
TBD: Deploy to dev and test
[Logs to verify email is in sync](https://gds.splunkcloud.com/en-GB/app/search/search?q=search%20index%3D%22gds_di_production%22%20message%3D%22is%20email%20in%20sync*%22&display.page.search.mode=smart&dispatch.sample_ratio=1&workload_pool=&earliest=1745920800&latest=1746021600&display.page.search.tab=events&display.page.search.patterns.sensitivity=0.866&display.general.type=events&sid=1746018261.60231)
[Logs to verify internalCommonSubjectId is in …
=> ATO-1128: migrate away from using user profile

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
We currently do some amount of logging inside the isPKCEValid method for invalid cases. However we don't log if there is a mismatch in the auth request and computed code challenge. It would also be easier to track one single log message when PCKE fails with a returned error
- Adds a log message before returning invalid_grant when PKCE failed
- N/A just logging
=> BAU: Log a message when PKCE fails with error

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java
Final PR on orch's side for email migration
- deletes session.getEmailAddress and remaining test uses
- deletes session.setEmailAddress and remaining tests uses (Auth aren't reliant on orch setting email)
N/A
=> ATO-1125: remove email from orch shared session

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf
Give dynamo user roles access to the user-credentials customer managed encryption key
- When encryption of the user-credentials table is switched to the CMK the lambdas accessing the table will have rights they need to access it.
- The required lambdas will first be given the rights they need before switching over encryption to the CMK.
- Changing the role causes an update in place rather than a destroy and recreate, so this is a zero downtime operation
1. Code review
2. Apply to a dev environment to observe terraform plan
=> AUT-4196: Give dynamo user roles access to the user-credentials customer managed encryption key

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java, shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
Final PR on auth's side for email migration
- deletes session.getEmailAddress and remaining test uses
- deletes session.setEmailAddress and remaining uses (no live uses of getEmailAddress anymore, so no need to keep it consistent).
N/A
=> ATO-1570: remove email from auth shared session

build.gradle
Context: Dependabot suggested update to dependencyVersions.junit from 5.11.4 to 5.12.2. Tests failed to build due to unaligned versions of the junit-platform-engine and junit-platform-launcher.
- add junit-platform-launcher to tests configuration to align with JUnit 5.12 requirements.
- update JUnit to 5.12.2
NB: I've closed the [original dependabot PR](https://github.com/govuk-one-login/authentication-api/pull/6336) because of problems rebasing.
=> ATO 1619/Update JUnit to 5.12.2

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Previously we had an incident where a new field was included in the JAR sent from orch to auth, which caused the query parameters of the redirect to auth to exceed the limit of our WAF. We did increase the query params limit in the WAF, however we will be adding new claims to this JAR and need a way of telling how close we are to the limit.
This PR adds a new metric called "AuthRedirectQueryParamSize", which is the length of all query parameters in the redirect to auth. Tests have also been updated to assert on this metric being set.
Deployed to sandpit. Saw new metric in CloudWatch after being redirected to the login page.
=> ATO-1616: Emit metric for auth query param size

ci/terraform/shared/iam.tf
Allow user-credentials CMK cross-account access
The corresponding IAM role is assumed by acceptance-tests container running from the new SP accounts
=> Allow user-credentials CMK cross-account access

ci/terraform/interventions-api-stub/authdev1.tfvars, ci/terraform/interventions-api-stub/authdev2.tfvars, ci/terraform/interventions-api-stub/build.tfvars, ci/terraform/interventions-api-stub/dev.tfvars, ci/terraform/interventions-api-stub/dynamodb.tf, ci/terraform/interventions-api-stub/variables.tf, ci/terraform/shared/dynamodb.tf, ci/terraform/ticf-cri-stub/authdev1.tfvars, ci/terraform/ticf-cri-stub/authdev2.tfvars, ci/terraform/ticf-cri-stub/build.tfvars, ci/terraform/ticf-cri-stub/dev.tfvars, ci/terraform/ticf-cri-stub/dynamodb.tf, ci/terraform/ticf-cri-stub/variables.tf
[AUT-4213]
PR to add policy to dynamo DB for cross account table access
1. Code Review
2. Deploy to Dev env and verify the Dynamo DB tables permission to all table in Dev environment
3. Deploy Account invention stub  &  TICF stub in authdevs 
./deploy-authdevs.sh -i -p   ( deploy the account interventions API stub)   verify the Dynamo DB tables permission for stub table 
./deploy-authdevs.sh --ticf-stub -p   ( deploy the TICF CRI stub) verify the Dynamo DB tables permission for ticf stub table 
[AUT-4213]: https://govukverify.atlassian.net/browse/AUT-4213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4213: Give cross account access to dev dynamo DB table

ci/terraform/test-services/dynamo-policies.tf, ci/terraform/test-services/shared.tf
Grant delete synthetics user access to the user-credentials-cmk.
Create Account smoke test is currently failing as the delete synthetics lambda does not have the rights to the user-credentials CMK
https://github.com/govuk-one-login/authentication-api/pull/6459
=> AUT-4196: grant delete synthetics user access to the user-credentials-cmk

ci/terraform/test-services/dynamo-policies.tf, ci/terraform/test-services/shared.tf
Update to the synthetics user delete policy to access user-credentials CMK
Previous PR did not add the actual key to the policy
#6473
=> AUT-4196: update to the synthetics user delete policy to access user-credentials CMK

ci/terraform/oidc/mfa-reset-authorize.tf, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/IPVReverificationServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaResetAuthorizeHandlerIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
Makes the IPV reverification service call the IPV JWKS endpoint to get their public encryption key. This is then used to encrypt the JWT send over in the MFA reset authorize handler.
Also a small refactor (courtesy of @andrew-moores)
1. Code Review
- Take particular care to check that the new logic is only used in staging. Lower environments should still grab the key from 
the configuration service
=> Aut 4159/use ipv jwks endpoint

ci/terraform/oidc/mfa-reset-authorize.tf
- This is required so that the lambda can hit an endpoint outside of the VPC. Required for hitting IPV's public JWKS endpoint.
1. Code Review
=> AUT-4159: Add egress security group to mfa-reset-authorize lambda

shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
We're planning to migrate away from using CurrentCredentialStrength on the Auth session in favour of a new field. We're doing this in this manner to allow us to be able to set this value in additional places before we swap over. This will allow us to check the value is what we expect before we swap over any usages. The plan is for this to be a value auth derive itself instead of partially requiring Orchestration (as it currently does).
- Adds a new attribute to the Auth session `AchievedCredentialStrength`
- N/A just adding a new unused attribute to the session
=> ATO-1621: Add AchievedCredentialStrength to Auth session

ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/build.tfvars, ci/terraform/shared/dev.tfvars, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/integration.tfvars, ci/terraform/shared/kms.tf, ci/terraform/shared/production.tfvars, ci/terraform/shared/security-groups.tf, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf
1. Session redis access from new_auth private subnets - required by lambdas deployed to new auth accounts
2. Allow cross-account access upto staging environment for dynamodb tables and customer managed keys associated with the tables
Issue: [AUT-4302] [AUT-4213]
Deployed and tested in authdev1, dev. Terraform apply logs in the jira ticket
[AUT-4302]: https://govukverify.atlassian.net/browse/AUT-4302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AUT-4213]: https://govukverify.atlassian.net/browse/AUT-4213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4302: Session redis and dynamodb cross-account access for auth-ext-api

ci/terraform/oidc/api-gateway.tf
This is to stop the API gateway being picked up by FMS - it only receives requests from cloudfront so a WAF is not necessary
Planning to do a TF plan against sandpit
=> ATO-1614: Add FMS tag to API gateway stage

build.gradle, ci/terraform/oidc/authentication-callback.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/outputs.tf, ci/terraform/oidc/shared.tf
Previously, orch was signing requests to IPV with a key that resides in the `gds-di-*` AWS accounts. The signing key resources have been moved to the `di-orchestration-*` AWS accounts (#6387) and publishing has been enabled on all environments (#6387, #6394, #6396, #6397) and we are now signing requests with this new key on all environments (#6405, #6412, #6414, #6415). We have also stopped publishing the old key on the IPV JWKS endpoint and cleaned up the infrastructure controlling deployment (#6425).
At this point, we are happy that things are working as expected on production.
We now need to remove the references to the old key pair before finally removing those resources.
- Removed OIDC Terraform references for old IPV key
Deployed to sandpit using the deploy shell script (deployed …
=> ATO-1585: remove IPV key pair TF references

oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java
In future, we may support login_hint. We should log if this value is already being passed to us.
- Logs if login_hint in query params 
- Logs if login_hint in request object and the **length** of the value if present
- N/A just logging
=> ATO-1631: log if login hint present

template.yaml
We previously developed a feature which allowed us to fetch an RP's public key from a jwks_uri. This has been enabled in all environments except production and we've seen RPs use this feature successfully. This now turns the feature flag on in production.
- Enables `EnableFetchJwks` in the production environment
- N/A
=> ATO-1645: Turn on RP Jwks Fetch in production

backend-template.yaml, scripts/dev-sam-deploy.sh, scripts/dev-samconfig.toml
Deploy auth-ext-api cloudformation template to dev and authdevs
Changes in backend-template.yaml to support SubEnvironments i.e. authdev1, authdev2
The script supports similar functionality as deploy-dev.sh
```
$ ./scripts/dev-sam-deploy.sh -h 
Usage:
./scripts/dev-sam-deploy.sh [options] <environment>
Options:
-b, --build                 run gradle and buildZip tasks
--no-build                  do not run gradle and buildZip tasks
-p, --prompt                prompt for confirmation before sam deploy
-c, --clean                 run gradle clean before build
-h, --help                  display this help message
-x, --auth-external         deploy the auth-external API
Arguments:
environment                 the environment to deploy to. Valid environments are: authdev1 authdev2 dev
```
=> AUT-4305: Deploy auth-ext-api cloudformation template to dev and authdevs 

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
We should now have fields available in the auth backend we can use to replace usages of the clientSession.getAuthParams() method. Some of these usages are outside of the StartHandler however, so we need to add these to the auth session so we can keep track of them.
This PR adds 3 new fields to the AuthSessionItem: `requestedCredentialStrength`, `requestedLevelOfConfidence` and `clientId`. These fields are also set in the StartHandler.
Added tests coverage for new fields being set.
Deployed to sandpit, verified that new fields were set on AuthSessionItem in dynamo
=> ATO-1436: Add new properties onto AuthSessionItem

ci/terraform/oidc/kms-policies.tf, ci/terraform/oidc/shared.tf
**MERGE NOTE: Dependent on #6451 being merged**
Previously, orch was signing requests to IPV with a key that resides in the `gds-di-*` AWS accounts. The signing key resources have been moved to the `di-orchestration-*` AWS accounts (#6387) and publishing has been enabled on all environments (#6387, #6394, #6396, #6397) and we are now signing requests with this new key on all environments (#6405, #6412, #6414, #6415). We have also stopped publishing the old key on the IPV JWKS endpoint and cleaned up the infrastructure controlling deployment (#6425).
At this point, we are happy that things are working as expected on production.
We now need to remove the old key pair resources.
- Removed Terraform key resources and access policies
- #6387 - generate new signing key pair
- #6405 - sign on …
=> ATO-1585: remove permissions for old orch to IPV key pair from auth

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
We previously added this logging to check enabling PKCE was backwards compatible. Now this feature is enabled we can remove the logging.
Removes the logging
- N/A just deletes the logging
-
=> BAU: Remove temporary logging

template.yaml
Cloudformation does not pick up on changes to secrets, and won't modify the value if changed directly from the secret to the target, so we have to deploy the current value first.
Nothing yet, this is the groundwork for actually upgrading
Deployed to dev
=> ATO-1648: Hardcode current dynatrace layer arn to allow us to force the upgrade

ci/terraform/shared/kms.tf, ci/terraform/shared/outputs.tf
Previously, orch was signing requests to IPV with a key that resides in the `gds-di-*` AWS accounts. The signing key resources have been moved to the `di-orchestration-*` AWS accounts (#6387) and publishing has been enabled on all environments (#6387, #6394, #6396, #6397) and we are now signing requests with this new key on all environments (#6405, #6412, #6414, #6415). We have also stopped publishing the old key on the IPV JWKS endpoint and cleaned up the infrastructure controlling deployment (#6425).
At this point, we are happy that things are working as expected on production.
We now need to remove the references to the old key pair before finally removing those resources.
- Removed OIDC Terraform references for old IPV key
Deployed to sandpit using the deploy shell script (deployed …
=> ATO-1585: Remove old IPV key from terraform deployment

template.yaml
Will follow up with production shortly. Auth have been running this version since it was released without issue
=> ATO-1648: Upgrade dynatrace in all environments except production

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/RedirectService.java
- We're getting multiple production-authentication-callback-alarms which can be attributed to there being no session cookie. There is no value in continuing to receive these alarms.
- To reduce alarm noise, stop logging no session cookie as ERROR, instead log as WARN
This is limited to logging - no testing carried out.
=> ATO-1649 Move no session cookie logs to warn

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
As part of the client session migration work, we spotted the claim `confidence` that we send from orch to auth frontend doesn't represent a levelOfConfidence as the name suggests, but instead a credentialTrustLevel. We introduced a new claim with a better name (`requested_credential_strength`) to replace this confidence claim.
We removed the confidence claim from the list of required claims in the auth frontend, and the claim is no longer used in the frontend. This means we can now safely stop sending this claim in the JAR.
This PR stops sending the `confidence` claim from orch to auth. It also adds some missing assertions on the claims we send to auth.
Tested in sandpit with several journeys. Auth frontend didn't complain about the claim not being sent
=> ATO-1650: Stop sending confidence claim from orch to auth

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
We would like to stop using clientSession and instead use the values of claims we send from orch to auth. By this point, we have claims available in auth backend that can replace the use of the auth request parameters on the clientSession.
We are storing the claims `levelOfConfidence`,`credentialTrustLevel`, and `clientId` in the auth session, as these are used outside of the StartHandler. The rest of the claims (`cookieConsent`, `_ga`, `state`, `scope`, `redirect_uri`) are only used in the StartHandler.
This PR uses the following claims from orch, instead of the auth request parameters in the client session:
- `cookieConsent`
- `_ga`
- `state`
- `scope`
- `redirect_uri`
These claims are only used in the StartHandler, so the scope of these changes are quite small.
Tested in sandpit and …
=> ATO-1437: Swap to using remaining claims from orch instead of client session

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevel.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevelTest.java
As we're in the process of migrating from using CurrentCredentialStrength to Achieved Credential strength, we need to set this value in all places where we're certain a user has achieved a level of credential trust. This means we'll set it in some places where we previously set CurrentCredentialStrength and some new places.
- Sets Achieved Credential Strength to low in Login Handler when MFA is not required and user has not previously achieved a higher level of strength (**NEW**)
- Sets Achieved Credential Strength  to medium in VerifyMfaCode in the same place Current Credential Strength is set
- Sets Archived Credential Strength to medium in VerifyCode Handler when on a SMS MFA journey (**NEW**)
- Deployed to sandpit and test the following:
-  Saw a couple of failures related which look …
=> ATO-1621: set achieved credential strength on auth session

backend-template.yaml, sam-deploy-authdevs.sh
Staging auth-ext-api EnvironmentConfiguration
Additional tweaks in the deploy-authdevs equivalent script that deploys auth-external-api in authdevs using the new cloudformation template.
For the staging EnvironmentConfiguration, observe deployment in staging (kicked off by artifact promotion from build).
Deploy scripts, run as usual
```
$ ./sam-deploy-authdevs.sh -h 
Usage:
./sam-deploy-authdevs.sh [options] <environment>
Options:
-b, --build                 run gradle and buildZip tasks
--no-build                  do not run gradle and buildZip tasks
-p, --prompt                prompt for confirmation before sam deploy
-c, --clean                 run gradle clean before build
-h, --help                  display this help message
-x, --auth-external         deploy the auth-external API …
```
=> AUT-4303: Staging auth-ext-api EnvironmentConfiguration

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
Logging an ERROR state every time a user ends at IPV callback with no session cookies is quite noisy. Given how we already try to gracefully recover this in the case of cross browser we can log a warning here instead
- Use the new warn logging-method `redirectToFrontendErrorPageForNoSessionCookies` instead of the error logging one
=> ATO-1649: Swaps the ipv no session cookie logs for a WARN

auth-external-api/src/main/java/uk/gov/di/authentication/external/entity/AuthUserInfoClaims.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java
We're migrating away from using Current Credential strength towards using Achieved credential strength. We send Orchestration the current credential strength value and we should send this new value to Orchestration in the userinfo response.
- Optionally sends the achieved credential strength value if it is included in the claims from Orchestration 
- Deploy to sandpit
- Run through a journey - shouldn't see anything massively different given Orchestration need to start requesting the claim
- No errors observed
- Branches off of: https://github.com/govuk-one-login/authentication-api/pull/6438 so must be merged first
=> ATO-1621: send achieved credential strength in userinfo

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
We should consistently redirect with a WARN log for no session cookies instead of an ERROR log. This NoSessionException is thrown after we attempt the graceful handling of no cookies present. Otherwise these ERROR logs create noisy alerts
- DocApp Callback handler now logs a WARN instead of an ERROR in the case of no session cookies
=> ATO-1649: Redirect with WARN log for no cookies DocAppCallback

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationServiceTest.java
Remove getters of the authenticated flag from tests, and the getter itself from the shared session
Tested in dev
=> ATO-1651: Remove authenticated getters

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AccountInterventionsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/conditions/MfaHelperTest.java
We would like to stop using clientSession and instead use the values of claims we send from orch to auth. By this point, we have claims available in auth backend that can replace the use of the auth request parameters on the clientSession.
We are storing the claims `levelOfConfidence`,`credentialTrustLevel`, and `clientId` in the auth session, as these are used outside of the StartHandler. The rest of the claims (`cookieConsent`, `_ga`, `state`, `scope`, `redirect_uri`) are only used in the StartHandler.
This PR swaps to using the `credentialTrustLevel` we are storing on the auth session from orch, instead of parsing the VTR from the client session auth request params.
Tested in authdev and sandpit
- Both 2fa and no 2fa journeys worked
=> ATO-1437: Swap to using credentialTrustLevel from orch instead of client session

client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Channel.java
Added "mobile" to orch's Channel enum. Orch doesn't do much with this value - they just get it from the ClientRegistry and pass it to Auth. The only use of the enum is in `ClientRegistrationRequestHandler`, which checks if that channel is valid.
The default value is still `web`, as a number of clients don't have a channel property, and only a single client will use the new `mobile` channel. 
Currently, no clients use this channel. To complete this work, a client registry change should be made for gov.uk app integration client, client-id `5o5i_n_2oBqvrAiy6f0JW_jzUBE`, and any future client registry entries for gov.uk app. This won't happen until the parent ticket is complete.
1. Code Review
Change to orch stub: https://github.com/govuk-one-login/authentication-stubs/pull/349
=> AUT-4297: add mobile as enum on orch

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/RedisExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/SessionService.java
Remove authenticated setters. This flag is not used from the shared session in orch
Will test in dev
=> Ato 1651/remove authenticated setters

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/CredentialTrustLevel.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/CredentialTrustLevelTest.java
We're requesting this value and now auth are sending it to us. We can now do some logging and check the value is as expected. 
- Adds some logging to auth callback to check this value. This logging is wrapped in a wide catch so shouldn't create a problem.
-  Deployed to dev
- Ran through a journey and checked logging was present 
- Inadvertently tested the case where the achieved credential strength was null because sandpit was not up to date with main 😄  - logging handled this gracefully as expected
- Also handled the comparison as expected
=> ATO-1621: log achieved credential strength from userinfo response

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaRetrieveFailureReason.java
This pull request implements changes related to storing and verifying SMS One-Time Passcodes (OTPs) using both the user's email address and phone number as identifiers.
Previously, SMS OTPs were identified solely by the user's email address. With the introduction of support for multiple SMS MFA methods, it is necessary to uniquely identify OTPs for each phone number associated with a user. This includes a migration fallback to ensures a smooth transition for users during deployment.
1. Code review, commit-by-commit
1. Deploy
1. Run though all account creation, sign in, password reset and MFA reset with SMS MFA methods
=> AUT-4248: SMS OTP identification using email and phone number

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/Session.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationServiceTest.java
Session cleanup
Remove getters for is new account. It was just being used in tests still.
Tested in dev
=> ATO-1652: Cleanup is new account getters

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java
We are now confident that this value is set appropriately for all journey types and reflects when a user achieves the requested level of credential trust. We can now swap to using this value and ignoring the value of CurrentCredentialStrength, which is reliant on Orchestration to send in the JAR.
- We've swapped where we derive the current level of credential trust a user has achieved from the something Orch sends 
us to something we now derive from the session. 
- This means the logic is no longer reliant on something Orchestration attach in the JAR
- Deployed to dev 
- Run acceptance tests against it - all passed bar one - this was related to MFA MM and is under development
- Run through an uplift journeys - low then medium -> Prompted for MFA code
=> ATO-1621: Swap to using achieved credential strength when making uplift decisions

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/conditions/DocAppUserHelper.java
We have verified that the orch client session is in sync with the client session previously, and in most places we have been using the orch client session instead of the redis client session for some time now. There were a few prod places where its still using the redis client session though.
This PR updates the remaining few places to use the orch client session instead of the redis client session. After this PR, the only uses of the redis client session in orch would be in tests, or in the client session service (which will also be removed)
Deployed to sandpit, tested a few auth and identity journeys. All seemed fine.
Also did a docapp journey to check nothing has broken there
=> ATO-1420: Swap to using orch client session in remaining places

auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthExternalApiUserInfoIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthSessionService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/AuthSessionServiceTest.java
We're migrating away from using the field CurrentCredential Strength on the new separate sessions we've setup, as we're aiming to make this a solely authentication owned value, which is given to Orchestration. Now we've migrated the main usage of this value to AchievedCredentialStrength, we can now remove getting and setting it.
- Stops sending orchestration the value of Current Credential Strength - because this value was previously null in _some_ cases, the orchestration side of the code is set up to be able to handle this being null - so it's safe to remove this now.
- Stop setting it in VerifyMfaCode handler 
- Stop setting it initially in the start handler based on the Orchestration derived value -  we're removing this value completely so we can remove this.
- Deployed to authdev2 
- …
=> ATO-1621: remove ccs auth session

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchClientSessionItem.java
We have pretty much finished the client session migration to orch. There was a getter on the dynamo client session that we were not sure if we would need during the migration - `getEffectiveVectorOfTrust`. Turns out we didn't need it, as we've swapped to using a vtrList instead. This getter than therefore be removed.
This PR removes an unused getter in the dynamo client session.
Removing unused code, so not necessary
=> ATO-1421: Remove unused getter after migration

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/PhoneNumberCodeProcessorTest.java
While making changes to how codes are stored, we added logic to handle existing sessions where users had codes stored against just their email, not email + phone combo. 
For that period if time the previously generated OTPs will no longer be valid and users would have to request new OTPs.
Since previous OTPs will now have been invalidated due to TTL or deleted we can now revert this migration.
This reverts commit 96282beb1d2bfef618d50873299cad94f270f5c6.
1. Code Review
=> Revert "AUT-4248: Handle migration to phone + email OTP identifiers"

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
Part of the `login_hint` work. This sends the email to auth from login_hint only from the request object.
Gets the `login_hint` from request object, validates it's less than 256 (auth's validation limit) and passes it to auth. Removes it from it's come from the query param.
I've tested with the RP stub change. The login hint is null if not given or gotten from query params.
=> ATO-1625: send email from login_hint

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AuthUserInfoClaims.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/AuthCodeResponseGenerationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/entity/AuthUserInfoClaimsTest.java
Previously we migrated this field to the Orch session from redis. This was done as the existing logic between Authentication and Orchestration required both sides to determine this value, as it was previously not set in all cases. However this left some circular and fairly fragile logic between the components. Given Authentication should be the sole component concerned with this value, we have swapped to a new value called AchievedCredentialStrength which is more reliable and only set by Auth. 
This has meant there is no need currently for Orchestration to keep this value in it's own session store. We have some logging in place 
- Orchestration no longer set the value of current credential strength on it's session
- Removes it from the Authentication claims 
- Stops sending Current …
=> ATO-1621: Remove Current Credential Strength Orch session

shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
We have now established the value Achieved Credential Strength as the replacement for Current Credential Strength. I have added some javaDoc style code comments to each of the methods for this value.
- Adds method comments to explain the what this value represents and any context that might need to be considered when using these methods
- N/A just code comments
=> ATO-1621: Adds method comments

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/shared/services/AuthOrchSerializationServicesIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
We're now content with having migrated current credential strength to a new field on the auth session and the logic is clearer. We can now remove the redis session setting of this value.
- Remove setting CurrentCredentialStrength from redis session from auth side
Deploy to sandpit:
- Ran through a journey, no issues
=> ATO-1565 remove setting ccs shared session

ci/terraform/oidc/reset-password-request.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordRequestHandlerResponse.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/FrontendApiPhoneNumberHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
Our reset password journey needs to know which MFA methods a user has in order to present them as choices after entering their email OTP successfully.
Here we add the `mfaMethods` to the `ResetPasswordRequest` handler, as we do with the LoginHandler.
Existing returned attributes remain the same, but the data source is updated to use the same `MFAMethodsService` response that is needed for getting the `mfaMethods`.
Permission is given to the lamda to write user data as it now needs write generated MFA IDs for MFA methods that don't have them (`MFAMethodsService` handles that specifically).
1. Code Review
=> AUT-4256: ResetPasswordRequest now returns mfaMethods

build.gradle, client-registry-api/build.gradle, doc-checking-app-api/build.gradle, ipv-api/build.gradle, oidc-api/build.gradle, template.yaml
We would like to instrument our lambdas with Open Telemetry (OTel) so that we can see more detailed traces in Dynatrace. The OTel libraries have auto-instrumentation for most of the stuff we need, so just installing it and setting an env var is enough to give us 90%.
- Install the OTel packages in all Orch modules
- Set the environment variable to enable lambda tracing conditionally
Tested in dev, including a function without otel (slack notifications)
=> ATO-1440: Basic OTel configuration

auth-external-api/src/test/java/uk/gov/di/authentication/external/lambda/UserInfoHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/SessionHelper.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java
We are now ready to remove the redis session from authentication. The first part of this requires us to remove any leftover writing to redis. We are now sure these are redundant writes as this object is no longer updated.
- Removes any calls to StoreOrUpdateSession in the authentication code.
- Deploy to auth dev
- Run acceptance tests - all passed but there were a couple of undefined steps - assuming these are related to work currently under development
- Ran through a couple of journeys manually:
- 2FA 
- No 2FA
- Uplift
All as expected
=> ATO-1643 remove any writes to redis session auth

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java
We are now sending the `client_name` claim from the frontend to the backend. We would like to use this claim instead of using the ClientRegistry.getClientName() method. To do this, we will need to add this claim to the auth session
The `clientName` field has been added to the auth session. We are also setting this field in the StartHandler, using the claim we get from the frontend.
Deployed to sandpit. Started a journey and checked the AuthSession dynamo table in AWS. Confirmed that the ClientName field was set there.
Finished a couple of journeys and they all passed successfully.
=> ATO-1670: Set client_name on auth session in StartHandler

build.gradle, client-registry-api/build.gradle, doc-checking-app-api/build.gradle, ipv-api/build.gradle, oidc-api/build.gradle, template.yaml
Reverts govuk-one-login/authentication-api#6582
This was reverted to try to diagnose an unrelated issue with gradle dependency submissions
=> Revert "Revert "ATO-1440: Basic OTel configuration""

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java
We've seen a couple of RP's attach empty strings in the auth code field, which causes our DynamoDB query to throw an exception as the AttributeValue cannot be an empty string.
To fix this, we can add another condition to our validation which checks the auth code is not empty
We now return an `invalid_request` error when the auth code is an empty string.
- I don't think this needs manually testing but happy to be challenged on it!
=> ATO-1684: Validate auth code is not empty string

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
We would like to move authentication away from using the ClientRegistry. To do this we need to pass information about the client from orch to auth, and store them on the auth session. A few fields we need have already been added as part of the client session migration.
This PR swaps to using the cookie_consent_shared claim sent from orch instead of the ClientRegistry.isCookieConsentShared() method.
Tested in authdev2, did a couple of journeys and all got the cookie from the frontend.
=> ATO-1676: use cookie_consent_shared instead of client registry

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/OrchSessionItem.java, template.yaml
As part of the global logout initiative, we would like to have the ability to logout of all sessions based on an internal common subject identifier. To do this, we need to update the orch session table to add a secondary index on internalCommonSubjectId
This PR adds a new global secondary index for the `OrchSession` table, on the field `internalCommonSubjectId`.
Deployed to orch dev. Ran a query against the new secondary index and confirmed the index worked.
=> ATO-1657: Add secondary index on internalCommonSubjectId for OrchSession

scripts/dev-samconfig.toml
Update `dev-samconfig.toml` with new authentication-api-pipeline params. 
This specific toml configuration file is being used, in conjunction with `sam-deploy-authdevs.sh` to deploy Cloudformation templated auth-api to the `di-authentication-development` account. 
Steps:
1. Deploy to one of the authdevs i.e. `./sam-deploy-authdevs.sh -b -c -p -x authdev1`
2. Deployment should be successful, specifically the lambda code signing part
3. Test signin user journey with the corresponding orchstub i.e. https://orchstub.signin.authdev1.dev.account.gov.uk/
=> AUT-4407: Update dev-samconfig.toml with new authentication-api-pipeline params

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
We would like to move authentication away from using the ClientRegistry. To do this we need to pass information about the client from orch to auth, and store them on the auth session. A few fields we need have already been added as part of the client session migration.
This PR gets subject_type from the frontend and sets it on the AuthSession. It also adds a console log to check the value
Ran on authdev2 with frontend change
=> ATO-1688: set SubjectType on AuthSessionItem

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java
We would like to move authentication away from using the ClientRegistry. To do this we need to pass information about the client from orch to auth, and store them on the auth session. A few fields we need have already been added as part of the client session migration.
This PR swaps to using the subject_type claim sent from orch (that's then set on AuthSession) instead of the ClientRegistry.getSubjectType() method for ClientSubjectHelper
Tested in authdev2, did a couple of journeys and all got the cookie from the frontend.
=> ATO-1689: use AuthSession subjectType instead of client registry

oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
We would like to start accepting `channel` in the authorise request to orch. Before we add validation for this we need to check if any RPs are already sending `channel` in the request, and if this will cause the validation to fail.
This PR checks if the `channel` parameter exists on the authorise request. If it does, it will log the value, and also log whether the claim is considered valid (`web` or `generic_app`)
Updated a test to send `channel` in the auth request. Saw the logs appear in the test log. I think this should be enough?
=> ATO-1705: Add logging for invalid channel values

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/BaseAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/QueryParamsAuthorizeValidator.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/RequestObjectAuthorizeValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java
Paired on this with @james-peacock-gds 
We would like to support RPs providing us with a channel claim, that will be used instead of the channel defined in the client registry. We have already checked with logs that there are no clients sending us this claim at the moment.
This PR makes AuthorisationHandler return a bad request if the RP sends us an authorisation request that has an invalid channel (not `web` or `generic_app`). The claim is optional, so if not provided, the validation will still succeed.
Tested in sandpit
Validation succeeded after hitting /authorize with:
- No channel value provided in the query params
- Channel value of `web`
- Channel value of `generic_app`
Received an invalid request after hitting /authorize with
- Channel value of `strategic_app`
- Channel value of …
=> ATO-1692: Add validation to channel claim

oidc-api/src/main/java/uk/gov/di/authentication/oidc/helpers/AuthRequestHelper.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/AuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
Paired on this with @james-peacock-gds 
We would like to support RPs providing us with a channel claim, that will be used instead of the channel defined in the client registry. We have already checked with logs that there are no clients sending us this claim at the moment, and we are validating that the channel we receive from the RP is a valid one (not present, `web`, or `generic_app`)
This PR changes what channel we send based on the claim we get from the RP in the authRequest.
- If the channel is present in the auth request, and it is valid, then it used as the channel value in the JAR we sent to auth.
- If the channel is not present, it will fall back to using the client registry
- If there is no channel set in the client registry, then a default of `web` is used (note this was …
=> ATO-1693: Pass channel claim to auth

ci/terraform/oidc/dev.tfvars, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/helpers/ReauthMetadataBuilder.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessor.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/validation/MfaCodeProcessor.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/validation/AuthAppCodeProcessorTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthSessionServiceIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/AuthenticationAttemptsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/CountType.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationAttemptsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java, shared/src/test/java/uk/gov/di/authentication/shared/entity/AuthenticationAttemptsTest.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ReauthAuthenticationAttemptsHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java
Going forward we will be merging the separate counts for uses of SMS and AUTH_APP MFA into a single count to support simple lockout logic when a user has multiple MFAs.
Here the `CodeStorageService` and `AuthenticationAttemptsService` and their uses are updated to reflect this. They recorded separate redis and DynamoDB records for the counts.
Note that currently the `AuthenticationAttemptsService` is only used for count when a user is on a REAUTHENTICATION journey.
As this change will affect the uses of existing counts, we need to make sure the now deprecated count records are included in lockout logic until the deprecated count records expire.
This means the inclusion of temporary code that can be removed later to ensure a zero-downtime deployment with no user facing changes.
1. Code …
=> AUT-4426: Increment MFA uses in single count

ci/cloudformation/auth/api/auth-internal-api.yaml
Manage dependency between api exec logs creation and subscription
`API-Gateway-Execution-Logs_${AuthInternalApi}/${StageName}` CloudWatch log group gets created automatically by Serverless::Api. Though not quick enough (during the first ever deployment) for the SubscriptionFilter, and the deployment fails with dependency issues. 
Tried and tested solution: Creating the log group explicitly to workaround the dependency issue.
Issue: [AUT-4408]
Test this in authdevs via either CLI (`./sam-deploy-authdevs.sh`) or GHA [deployment](https://github.com/govuk-one-login/authentication-api/actions/workflows/deploy-api-modules-sp-dev.yml) 
[AUT-4408]: https://govukverify.atlassian.net/browse/AUT-4408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4408: Manage dependency between api exec logs creation and subscription

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/GlobalLogoutMessage.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/GlobalLogoutHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/GlobalLogoutHandlerTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/SqsTestHelper.java
We have previously created a lambda to be used for global logout. At the moment, the lambda does nothing. We would like to start by adding validation for the message we get from SQS to make sure all the fields we need are present.
This PR adds validation for the message we get from SQS in the GlobalLogoutHandler. The fields we require are:
- `internal_common_subject_id`
- `session_id`
- `client_session_id`
Deployed to orch dev. Tested by sending 5 messages
- Valid message
- Message with missing ICSID
- Message with missing session ID,
- Message with missing client session ID
- Message with invalid JSON
The first one was successful, the last 4 failed as expected.
=> ATO-1658: Add validation to global logout lambda

template.yaml
We would like to enable SnapStart on most of our lambdas, to decrease response time.
This PR turns on SnapStart for the `UpdateClientConfigHandler` lambda
Tested by updating client config with and without snapstart
Without snapstart: Took **4.9 seconds** for the lambda to initialise
With snapstart:      Took **1.1 seconds** for the lambda to initialise
=> ATO-1720: Enable SnapStart for UpdateClientConfigHandler

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
We've now stopped reading the shared session in Orchestration, so we can stop two things:
- No longer deleting  the Redis session on logout - these will expire in an hour, so we no longer need to delete them 
- Stop setting an initial session at /authorize for both Doc app and Auth journeys. The redis session is no longer read anywhere so we can stop setting it finally!
- Deployed to dev
- Run through an auth only journey
- Run through a max_age=0  journey
- Run through an identity journey
- Test a logout journey
=> ATO-982: Remove setting and deleting

ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/ipv-callback.tf, ci/terraform/oidc/ipv-handback-alerts.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/spot-response.tf, ci/terraform/oidc/userinfo.tf
In previous work, we migrated this table to the Orchestration account. Now we've done so, we can clear up the old table. Now we've duplicated the roles, we can swap over to the new ones without the roles. This is done to ensure there is no downtime during deployment.
- Swaps to all previously duplicated roles
Deployed to sandpit:
- Run through an identity journey and all was fine
=> ATO-1471: Swap roles to ones without old table policies

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/GlobalLogoutMessage.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/GlobalLogoutValidationException.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/GlobalLogoutHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/validators/GlobalLogoutValidator.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/GlobalLogoutHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/validators/GlobalLogoutValidatorTest.java
We are using the SerialisationService in the GlobalLogoutHandler to check if required fields are provided, but we are not checking if the string fields are empty or not. This is mainly a problem for internalCommonSubjectId, as we query dynamo using this field, and dynamo doesn't like empty strings.
This PR adds GlobalLogoutValidator, that checks that all String fields on a GlobalLogoutMessage are not empty strings. I've also added tests for this new validator.
This PR also uses this new validator in GlobalLogoutHandler, after deserialising the message, to check that all the fields  are not empty strings.
=> ATO-1658: Add validation for empty strings for global logout

ci/terraform/oidc/api-gateway.tf, ci/terraform/oidc/authorize.tf, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, template.yaml
Support for POST authorise requests was added in 2023 as it was anticipated that this would be required by HMRC. This is no longer the case so there is no requirement to support POST authorise requests. 
- update terraform for API gateway and authorize endpoint to only allow authorise requests with GET
- In AuthorisationHandler, only support authorise requests with GET
- update unit test for allowed http methods
- remove redundant unit tests for POST requests
Deployed terraform changes to sandpit and observed the following:
- POST request from RP stub is not permitted (403 response)
- GET request from RP stub remains successful
=> ATO-1637 Disallow POST authorize requests

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
- We are now allowing RPs to specify `channel` in the auth request and if they do so, this overrides the value in the client registry.
- When RPs specify `channel` in the auth request, include `channel` when submitting the request parsed event to audit 
- Refactored authoriseRequestHandler to improve readability: extracted a method to sendAuthRequestParsedAuditEvent.
=> ATO-1696/Add channel to audit event

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/shared.tf, ci/terraform/shared/kms-policies.tf, ci/terraform/shared/outputs.tf
In previous work, we migrated this table to the Orchestration account. Now we've done so, we can clear up the old table. Now we can remove the table policies that are unused 
- Deletes unused table policies 
- Deletes table CMK policies 
- Deletes table CMK ARN output
Deploy to sandpit (both shared and oidc)
- Removed the expected policies
- Also ran through an ID journey just in case (wasn't expecting this to affect anything) and was fine
=> ATO-1471: remove table policies

ci/terraform/account-management/production.tfvars
Deploy the MM V2 API to production
This is to support connectivity configuration in Home.
The API is private and cannot be used externally.
It is also still switched-off so cannot accept traffic.
1. Code Review
#6698 
#6603
=> AUT-4466: Deploy the AM V2 API to production

ci/terraform/shared/dynamodb.tf
In previous work, we migrated this table to the Orchestration account. Now we've done so, we can clear up the old table. To remove the old table we need to disable delete protection
- Sets delete protection to false for the old table
Deploy to sandpit 
- check output of plan is as expected: delete protection was disabled for the table
=> ATO-1471: Set delete protection to false

ci/terraform/auth-external-api/authdev1.tfvars, ci/terraform/auth-external-api/authdev2.tfvars, ci/terraform/auth-external-api/build.tfvars, ci/terraform/auth-external-api/integration.tfvars, ci/terraform/auth-external-api/production.tfvars, ci/terraform/auth-external-api/sandpit.tfvars
AUT-4449: Enable SnapStart on Auth external api lambdas
1. Code Review &  deploy in dev environment 
2. lambda  Auth-user and Auth-token lambda should show SnapStart enabled in lambda configuration on console
=> AUT-4449: Enable SnapStart on Auth external api lambdas

ci/terraform/account-management/integration.tfvars, ci/terraform/account-management/production.tfvars, ci/terraform/account-management/staging.tfvars
Configure Home vpc endpoint ids for MM V2 API
Method Management is not currently live.  This configuration is to support dormant testing of the API.
1. Code Review
#6701
=> AUT-4466: Configure Home vpc endpoint ids for MM V2 API

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
VerifyMfaCodeHandler wraps the logic for verifying codes in a try/catch, but does not log the exception thrown.
This makes it difficult to diagnose errors. A lot happens within the try catch that could be failing.
1. Code Review
=> BAU: Log exception thrown when verifying code

template.yaml
We currently store state for our Auth and IPV redirects in redis. We want to remove usages of redis, so we need a new dynamo table to store these in instead
- Adds a new dynamoDB table for storing state
Deployed to dev, saw new table and key deployed
=> ATO-1748: Add State storage table

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/StartRequest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationRedisTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaResetAuthorizeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckUserExistsIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/MfaResetAuthorizeHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/AuthSessionExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthSessionItem.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java
We have been calculating the `rpSectorIdentifierHost` in orch and have started to send the claim from orch to auth backend. By this point auth frontend should be sending this claim to auth backend as `rp_sector_identifier_host`. 
This claim is currently being calculated in auth, but the calculation is the same as the one in orch. We want to set this new claim on the auth session and use that instead of calculating the `rpSectorIdentifierHost` a second time. This is mainly to remove usages of the auth client registry, so we can rely on orch's client registry instead.
This PR sets the rpSectorIdentifierHost on the auth session, and also adds logging to check whether the calculation using the client registry is the same as the one using the pre-calculated auth session field. 
I've also added …
=> ATO-1770: Set rpSectorIdentifierHost on auth session and add logging

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
This is attempt two of this work. The first attempt failed the acceptance tests in build:
https://github.com/govuk-one-login/authentication-api/pull/6483
This still hasn't been fixed, so this PR is not ready to merge.
The tests that failed were:
- User successfully registers with auth app 2FA and login with 2fa-on
- User successfully registers using sms
- Partial registered user is able to complete registration when they restart journey and select forgotten password for sms user (edited) 
Updates the rules for what phone number we send back in the Auth <-> Orch UserInfo response. 
See https://govukverify.atlassian.net/browse/AUT-4315 for more details
1. Code Review
2. TBD: deploy to sandpit and test
=> AUT-4315: update rule for phone number in userinfo response

template.yaml
Migrating the docApp credential table from auth to orch account. It is a dynamo to dynamo migration
created to the dynamo and CMK for docApp credential
deployed to dev
=> ATO-1743: create a doc app credential dynamo table and CMK

auth-external-api/src/main/java/uk/gov/di/authentication/external/lambda/UserInfoHandler.java, auth-external-api/src/main/java/uk/gov/di/authentication/external/services/UserInfoService.java, auth-external-api/src/test/java/uk/gov/di/authentication/external/services/UserInfoServiceTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java
Update rules for phone number in userinfo response
This PR redeploys #6518 with an additional change in eff1bffe2fd57f6717f03d059f51dc462575afcc which extends the readOnly flag in 'getMfaMethodForNonMigratedUser' to auth apps for non migrated users.
1. Code Review
1. Deploy to a test environment
Test cases (using orch stub to view the userinfo json)
- Sign in a non-migrated user with an SMS MFA.  Check that the phone_number is correct and phone_number_verified is true
- Sign in a non-migrated user with an Auth App MFA.  Check that the phone_number is missing and phone_number_verified is false
- Sign in a migrated user with a default SMS MFA and a backup Auth App.  Check that the phone_number is the default and phone_number_verified is true
- Sign in a migrated user with a default Auth App …
=> AUT-4315: update rules for phone number in userinfo response

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java
OLH-2692: Send AUTH_MFA_METHOD_ADD_FAILED event
- Created new buildAuditcontext method that returns Result<ErrorResponse, AuditContext>
- Added error handling for AuditContext creation
- Updated method call site to handle potential failures
- Improved error handling by returning appropriate error response when audit context creation fails
1. Code review
=> OLH-2692: send AUTH_MFA_METHOD_ADD_FAILED event

template.yaml
We will eventually implement rate limiting for our clients. This table will store temporary information about Client Rate limits, eg counts, buckets etc whatever we decide to potentially implement.
We don't know exactly what the implementation will be here so things will remain a bit generic
- Adds new Client Rate Limit table 
- Adds a CMK for the rate limit table encryption   
- Deployed to dev:
- New table was created with expected config
=> ATO-1871: Add Client Rate Limit table

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ClientRegistry.java
We want to add rateLimit to the client registry to be able to add rate limiting.
Rate limit has been added to the client registry. It's been made an `Integer` so it allows null as not all client registries will have rate limiting. I've made all instances as `Integer` unlike `pkceEnforced` which is only `Boolean` for some and `boolean` for the rest as I wasn't sure we'd want `0` as the default if the rate limit is null.
Ran journeys on sandpit and all good
=> ATO-1779: add ratelimit to client registry

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationServiceTest.java, template.yaml
We would like to migrate away from redis and use a dynamo table in orch to store state by session ID. We have already created a dynamo table in orch, as well as a service class to interact with this table.  
This PR starts writing to the dynamo table in all places where we are saving the state by session ID in redis. This is only in `OrchestrationAuthorizationService`, `DocAppAuthorisationService`, and `IPVAuthorisationService`. 
Tested in sandpit. Performed:
- an auth only journey
- a doc app journey
Checked the dynamo table afterwards and saw both state values in the table stored against the prefixed session ID (with the correct prefix)
Stacked on https://github.com/govuk-one-login/authentication-api/pull/6747
=> ATO-1749: Write state to dynamo alongside redis

shared/src/test/java/uk/gov/di/authentication/entity/CodeRequestTypeTest.java
Adds a small test which contains a static list of existing enum values, which is seperate from the values defined on the enum class. This test has a small warning about ensuring the deployment is ZDD compatible as removing an enum value whilst it is still serialized in existing sessions will throw an error and kill existing sessions
- Pull the branch and delete a value from the CodeRequestType enum
- Run the test and see it fail
=> BAU: Add a test for enum removal

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaUpdateFailure.java
Introduces a new `AUTH_MFA_METHOD_SWITCH_FAILED` audit event which is triggered when a user's attempt to switch their backup method for their default fails unexpectedly.
To support this `MfaUpdateFailure` has been created. This class now includes the reason for the failure and the MFA method that was being updated, providing essential context for the new audit event.
1. Code Review
- This extends work from https://github.com/govuk-one-login/authentication-api/pull/6778
=> OLH-2696: Add `AUTH_MFA_METHOD_SWITCH_FAILED` audit event

ci/cloudfront-orchestration/cloudfront/build/parameters.json, ci/cloudfront-orchestration/cloudfront/integration/parameters.json, ci/cloudfront-orchestration/cloudfront/production/parameters.json, ci/cloudfront-orchestration/cloudfront/staging/parameters.json
Updating cloudfront to latest v2.3
Updating the parameters for env other than dev for cloudfront
Deployed to each env. Checked logs for traffic through waf.
=> ATO-1697: update cloudfront to other envs from build upwards

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthenticationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationServiceTest.java
We would like to store state in a dynamo table in orch instead of storing state in redis. By now we should be confident that the dynamo state is always the same as the redis state. We can now safely swap to using the dynamo state instead of the redis state.
This PR swaps to using the dynamo state for state-related operations instead of using the redis state. Now the redis state will not be read, and we can remove the writing of this state in the next PR
Tested in sandpit. Performed the following journeys:
- Auth only
- Doc app
- Identity
All 3 journeys completed successfully.
Have checked the logs over the weekend and they are all in sync (1 was out of sync but we suspect that is a dynamo read consistency issue)
=> ATO-1751: Swap to reading state from dynamo

template.yaml
We seem to be seeing a fair number of users get to IPV callback in a weird state. Whilst we investigate why we're seeing an issue here - let's bump the threshold to reduce noise. 
- Bumps alarm threshold to 20 whilst we investigate
=> ATO-1974: Bump IPV callback alert threshold

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/ClientRequestInfo.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RateLimitAlgorithm.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RateLimitDecision.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RateLimitService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RateLimitServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/Constants.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, template.yaml
As part of adding RP rate limiting to the Authorization handler, we now need to create a RateLimit Service. This PR adds that. The service is quite generic right as we have not yet implemented the algorithm which will be used for rate limiting.
- Adds a rateLimitService which has a No Action outcome if the client does not have a rate limit configured
- Delegates to the algorithm if the client does have a rate limit configured
- Adds a RateLimitDecision class to represent the state (has or hasn't exceeded limit) and the action (what we do about it) 
- Adds a feature flag to the authorization handler 
- Adds feature flagged call to rate limit service - right now this is hardcoded to a no op implementation
- Deployed to dev 
- Check feature flag is false
- Hit authorize just to check nothing …
=> ATO-1780: create rate limit service

template.yaml
We would like to consume TXMA events from Home to do a global logout for a user. Home has now configured this event in the event catalogue, and we have configured consuming this event. We now need to configure the event source mapping and policies for this new queue.
This PR adds the TXMA queue ARN and the KMS key needed to decrypt messages on the queue, to the environment config. It then uses these ARNs to configure the policy permissions for these queues, as well as the event source mapping for the GlobalLogoutHandler.
Note that this is currently feature flagged and enabled for staging only at the moment.
Tested in sandpit. Deployment was ok and could complete an auth only journey
=> ATO-1810: Consume from global logout txma queue in staging

ci/terraform/account-management/mfa-methods-create.tf, ci/terraform/account-management/mfa-methods-delete.tf, ci/terraform/account-management/mfa-methods-retrieve.tf, ci/terraform/account-management/mfa-methods-update.tf
Set lambda_log_alarm_threshold to default 5 for mfa-methods lambdas
We have a couple of days of data now and the alerts are proving too sensitive at 1.  Alerts to 2nd line should only be triggered when some kind of action or investigation is required by TSD, indicating that there is a significant issue or outage.
The 25% error rate threshold is still in place and will alert.
Errors will continue to be monitored offline to see if any fixes are required.
=> BAU: Set lambda_log_alarm_threshold to default 5 for mfa-methods lambdas

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java
Error level changes for NotifyCallbackHandler and CheckReAuthUserHandler
- Fixes an issue where "Account is unable to reauth due to too many failed attempts" is logged as an error when it is actually a valid alternative scenario and not a failure.  This is causing unecessary alerts: https://gds.slack.com/archives/C02HCLREVV5/p1752004116511279
- Fixes an issue with NotifyCallbackHandler where 'No template found with template ID' errors were logged as 'warn', making the issue more difficult to detect and diagnose.
1. Code Review
#6804
=> BAU: Error level changes for NotifyCallbackHandler and CheckReAuthUserHandler

ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IpvCallbackValidationError.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/LogoutService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/LogoutServiceTest.java
IPV will be returning a special oAuth error to Orchestration to convey some when a user's session should be invalidated. We should respond to this error by logging a user out and sending them to a generic `You've been signed out page`
- Tweaks our validation to add a new case for this session_invalidated case
- Adds handling of this which destroys a user's session, audits the logout, and redirects them to the generic "You've been Signed Out" page
- 
- Deployed to dev 
- Deploy this branch to ipv stub dev: https://github.com/govuk-one-login/orch-stubs/pull/322
- Run through an identity journey
- When you reach the stub, configure it to return the `session_invalidated` oAuth error
- See you are redirected to a generic "You've been signed out" page 
- Run through another authorize journey to …
=> ATO-1795: Add session invalidation handling ipv callback

template.yaml
Staging authExternalApiId temporary switch for testing
Plan is to switch staging to new APIs for a day and run a series of tests. New auth-external-api is running from the new auth di-authentication-staging account, deployed via secure pipelines.
Staging authExternalApiId
https://github.com/govuk-one-login/authentication-frontend/pull/2876
=> AUT-4544: Staging authExternalApiId temporary switch for testing

template.yaml
The backchannel logout alarm for failed requests has a low threshold of 1 and is going off semi-frequently.
Upping the DLQ alarm threshold to 5 to ignore one offs.
N/A
=> ATO-1793: update backchannel logout DLQ alarm threshold from 1 to 5

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsRetrieveHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsCreateHandlerTest.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsCreateHandlerIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java, integration-tests/src/test/java/uk/gov/di/authentication/services/MFAMethodsServiceIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditEventExpectation.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/mfa/MFAMethod.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MFAMethodsService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/mfa/MfaRetrieveFailureReason.java, shared/src/test/java/uk/gov/di/authentication/shared/services/MFAMethodsServiceTest.java
This introduces the `AUTH_CODE_VERIFIED` audit event to the `account-management-api` which is raised when a user successfully verifies an OTP via the `MFAMethodsCreateHandler` and `MFAMethodsPutHandler`.
- A new `getMfaMethod` function was created to fetch a specific MFA method's data before it is updated.
- The `updateMfaMethod` function was refactored to no longer fetch the MFA method itself. The method must now be provided.
- The audit context construction in the `MFAMethodsCreateHandler` and `MFAMethodsPutHandler` was refactored for clarity and consistency.
1. Code Review
=> AUT-4526: Raise AUTH_CODE_VERIFIED in account management

ci/cloudformation/auth/function/mfa-reset-authorize.yaml
mfa-reset-authorize lambda egress setup for accessing identity api
As devplatform VPC is used, it requires
1. the lambda to be deployed to protected subnets
2. to attach the egress security group
=> AUT-4565: mfa-reset-authorize lambda egress setup for accessing identity api

account-management-api/src/main/java/uk/gov/di/accountmanagement/domain/AccountManagementAuditableEvent.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/MFAMethodsPutHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/MFAMethodsPutHandlerIntegrationTest.java
Add AUTH_UPDATE_PROFILE_AUTH_APP event.
Branched off AUT-4245 which needs to be on main before this change can be merged.
1. Code Review
2. Deploy to dev and run acceptance tests
=> Aut 4529/auth update profile auth app

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
Previously, if a client was disabled, and sent us an auth request with an invalid redirect URI (one that was not configured for them in the client registry), the redirect would succeed.
This PR moves the `client.isActive()` check to after the validation of the query parameters / request object. These validators check if the redirectUri is valid for a client, and exit early if the client has an invalid redirectUri. We can therefore be confident that the redirectUri is valid once the validators have exited without throwing an exception. 
This is covered by an existing unit test (`shouldReturn400WhenAuthorisationRequestContainsInvalidRedirectUri`)
=> ATO-1842: Validate redirectUri before client isActive check

ci/terraform/account-management/build.tfvars
BAU: temporarily increase lambda concurrency in Build for APi 429 Error
=> BAU: temporarily increase lambda concurrency in Build for APi 429 Error

build.gradle, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/pact/LambdaHandlerConfig.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/ConstructUriHelper.java
CVE-2025-48924 is fixed in org.apache.commons:commons-lang3:3.18.0 and higher. Had to update our use of the strings library.
1. Code review
=> BAU: Pin minimum org.apache.commons:commons-lang3

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RateLimitService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RateLimitServiceTest.java
- We want to add a metric for when a rate limit has been exceeded
- Adds a new metric RpRateLimitExceeded
- N/A just emitting a metric
=> ATO-1782 add metric for request blocked

ci/terraform/account-management/build.tfvars
Reverts govuk-one-login/authentication-api#6865
=> Revert "BAU: temporarily increase lambda concurrency in Build for APi 429 Error"

ci/terraform/account-management/authenticate.tf, ci/terraform/account-management/mfa-methods-delete.tf, ci/terraform/account-management/mfa-methods-retrieve.tf, ci/terraform/auth-external-api/userinfo.tf, ci/terraform/oidc/account-interventions.tf, ci/terraform/oidc/account-recovery.tf, ci/terraform/oidc/auth-code.tf, ci/terraform/oidc/authentication-auth-code.tf, ci/terraform/oidc/check-email-fraud-block.tf, ci/terraform/oidc/check-reauth-user.tf, ci/terraform/oidc/identity-progress.tf, ci/terraform/oidc/ipv-capacity.tf, ci/terraform/oidc/logout.tf, ci/terraform/oidc/processing-identity.tf, ci/terraform/oidc/reverification-result.tf, ci/terraform/oidc/signup.tf, ci/terraform/oidc/start.tf, ci/terraform/oidc/update_profile.tf
TL;DR: remove redis configuration from lambdas that no longer use redis (in theory).
- **AUT-4449: Remove REDIS_KEY envar in non-prod envs**
- **AUT-4449: Remove redis policies in non-prod envs**
- **AUT-4449: Remove redis sg from non-prod envs**
In future, we'll enable snapstart on these lambdas, but we can only do that if they definitely don't use redis.
Removing access to redis is a nice way to test if it's needed (via ATs).
This is all ternary'd to prevent the changes from hitting production.
- check the methodology is sound
- check that the ternaries are:
- correct
- actually in place
- check I've done nothing dumb
=> AUT-4449: Redis non-prod scream test

ci/cloudformation/auth/parent.yaml, ci/terraform/oidc/integration.tfvars, ci/terraform/shared/dynamodb.tf, ci/terraform/shared/kms.tf, ci/terraform/shared/sqs-policy.tf
New auth integration env gaining access to old env resources
[AUT-4538]
On the terraform side, several policy changes were not applied to integration before. Those will now be applied since the `var.environment != "integration"` condition has been removed. 
https://github.com/govuk-one-login/authentication-infrastructure/pull/87
https://github.com/govuk-one-login/authentication-contra-indicators/pull/367
[AUT-4538]: https://govukverify.atlassian.net/browse/AUT-4538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4538: New auth integration env gaining access to old env resources

integration-tests/src/test/java/uk/gov/di/authentication/api/GlobalLogoutIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/GlobalLogoutMessage.java
We have previously configured a TxMA consumer to consume Global Logout events, and we are deserialising them using the class `GlobalLogoutMessage`. We have just received a message from TxMA and have noticed one of the field mappings is incorrect for our class. Its worth noting that there was no test coverage for this too.
This PR modifies the existing GlobalLogoutIntegrationTest to not use `GlobalLogoutMessage` objects to populate the fake TxMA queue, but instead use a basic Map. This way we can copy the example from the TxMA consumer config and paste it into the tests. 
This PR also fixes a bug where the mapping for internalCommonSubjectId was wrong. TxMA were sending us `internal_common_subject_identifier`, and `GlobalLogoutMessage` was expecting `internal_common_subject_id`. I've added …
=> ATO-1658: Fix incorrect global logout field name

ci/cloudformation/auth/parent.yaml
Integration dataStoreAccountId and lambda concurrency configs in mappings
[AUT-4538]
[AUT-4538]: https://govukverify.atlassian.net/browse/AUT-4538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4538: integration dataStoreAccountId and lambda concurrency configs in mappings

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java, template.yaml
We have uncovered that our handling of concurrent client sessions is currently not the best. In the cross browser scenario  IPV may return the user back to us with an access_denied error code. This PR aims to resolve the concurrent client session issues in the case we get an access_denied from IPV and ensure we use the correct client session.
- Adds a new method to the `NoSessionOrchestrationService` which handles the mismatch behaviour - we will rename this service shortly in a future PR to make the code clearer
- Currently only handles this in the case we get an access denied error with state
- The usage of this method is feature flagged in the handler, I've turned the feature flag on in **dev**, **build**, and **staging**.
This is not the neatest implementation - and I think our …
=> ATO-1856: Handle cross browser access_denied with concurrent client sessions

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
We have a service that soon will determine if a client has exceeded their configured rate limit. At the moment if they have exceeded their rate limit nothing happens. We would like to redirect them back to the RP with the error `TEMPORARILY_UNAVAILABLE` if they are being rate limited.
The actual implementation of the algorithm is being handled in other tickets. However, since we've configured the service to use an algorithm interface, we can work on this ticket independently, and mock the result of the RateLimitService to check that the redirect works.
When the `RateLimitService` returns an `OVER_LIMIT_RETURN_TO_RP` decision, the user will be redirected to the RP, using the redirectURI in the auth request. 
Tested in authdev3 by setting a rate limit for the dev RP. Hit the authorize …
=> ATO-1783: Redirect to RP if client is rate limited

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationServiceTest.java
We have uncovered that our handling of concurrent client sessions is currently not the best. This PR aims to resolve the _"happy path"_ case in which we don't get a cross browser error from IPV, but we *do* have a different client session  id in the cookie from the one that initiated the IPV authorisation. We can correlate this using the state parameter.
- Tweaks the previously added method in `NoSessionOrchestrationService` to ensure we apply this check in all cases we are able to - ie the state value is present - which is the minimum amount of information we need to handle this. 
- This change will me almost all requests to this callback endpoint will go through this validation as opposed to just cross browser ones which we added previously.
- This also has the effect of now redirecting …
=> ATO-1857: Apply CSID mismatch checks in all cases where possible

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationService.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthenticationCallbackHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/InitiateIPVAuthorisationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/CrossBrowserEntity.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/NoSessionOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationServiceTest.java
We've added new functionality to the `NoSessionOrchestrationService` which means it no longer just represents the _no session_ handling.  This renames the service and entity.
- Renames NoSessionEntity to CrossBrowserEntity
- Renames NoSessionOrchestrationService to CrossBrowserOrchestrationService
- N/A just a straight rename of existing classes
=> ATO-1858: rename no session service

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckReAuthUserHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/OrchestrationToAuthenticationAuthorizeIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/helpers/RequestObjectToAuthRequestHelperTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/OrchestrationAuthorizationServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/QueryParamsAuthorizeValidatorTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectAuthorizeValidatorTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/ClientStoreExtension.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/helper/KeyPairHelper.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/utils/KeyPairUtils.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/conditions/DocAppUserHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/ClientSubjectHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/DocAppSubjectIdHelperTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/PrivateKeyJwtClientAuthValidatorTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/validation/TokenClientAuthValidatorFactoryTest.java
This helper class had a few problems: 
- It has a public static method for generating key pairs, which is named like a static constant using  `UPPER_SNAKE_CASE` instead of `camelCase`, which is inconsistent with other public static methods 
- The method for generating key pairs caches the first key it generates, then reuses this key if multiple calls are made to this method. This functionality wasnt actually used anywhere, and it means that for some tests like `AuthorisationIntegrationTest`, its using the same key for the RP signing key and the internal auth encryption key - which is unrealistic. It’s also hard to tell if the right key is being used!
- There are a lot of cases where an identical method to generate the key pair is defined locally in tests.
This PR removes the key caching …
=> ATO-1868: Refactor and rename orch KeyPairHelper

build.gradle, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/DynamoExtension.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/KmsKeyExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/dynamodb/DynamoClientHelper.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/KmsConnectionService.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DynamoExtension.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java, shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoClientHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java, shared/src/main/java/uk/gov/di/authentication/shared/services/LambdaInvokerService.java
Dependabot couldn't do this automatically because there's a static constructor `DefaultCredentialsProvider.create()` we are currently using that has been deprecated. This PR uses the builder method for `DefaultCredentialsProvider` to create an instance of it, then bumps the AWS SDK version to 2.32.10.
Tested in authdev3 and performed a few different journeys, all worked fine.
=> BAU: Bump aws sdk v2 to version 2.32.10

build.gradle
The previously added constraint did not apply to the plugins so adding a constraint in the root buildScript that applies to the plugins.
1. Code Review
2. Build and check lan3 is forced to v3.18.0
=> BAU: Fix CVE-2025-48924 in gradle plugins

ci/terraform/account-management/sqs.tf, ci/terraform/oidc/sqs.tf
Reduce maxReceiveCount to 1 for notification queues.
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#policies-for-dead-letter-queues
This reduces the number of times failed notifications are retried before they are moved to the DLQ.
Delegates retrying delivery failures to the user who has an option to request a resend.
Deployed and tested in authdev1
1. Code Review
=> BAU: Reduce maxReceiveCount to 1 for notification queues

.pre-commit-config.yaml, build.gradle, deprecation-checker/build.gradle, deprecation-checker/src/main/java/uk/gov/di/deprecationchecker/DeprecationChecker.java, deprecation-checker/src/test/java/uk/gov/di/deprecationchecker/DeprecationCheckerTest.java, deprecation-config.json, settings.gradle
Introduces a new automated tool to prevent the accidental removal of code without proper deprecation. In this iteration only enum value checks are supported.
Configured enums should have values marked as `@Deprecated` on the main branch before they can be removed, otherwise the precommit configuration will prevent a commit being made.
This exists to encourage safe two-stage deployment practices as described in https://github.com/govuk-one-login/authentication-api/pull/6785.
1. Code Review
1. Checkout locally
1. Remove a value from one of the enums configured
1. Commit the change
1. If you have precommit installed locally, see the commit fail 
1. Otherwise you could push a new branch and make a PR and see the GitHub action checks fail
- …
=> INCIDEN-1031: Introduce DeprecationChecker

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/utils/JwksUtilsIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/extensions/JwksExtension.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/JwkCacheEntry.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/utils/JwksUtils.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/JwkCacheEntryTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/JwksServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/utils/JwksUtilsTest.java
We have an in-memory cache for storing JWKs retrieved from a JWKS endpoint. At the moment, the logic to select the relevant key is in the implementation of the caching code. If we were to move away from using an in memory cache it would be a bit messy to untangle the logic.
This PR moves the key selection logic out of `JwkCacheEntry` into `JwksUtils`, as well as creating a unit test class for `JwksUtils` and moving the relevant tests into it
I've also added test coverage for `JwksUtils.retrieveJwksFromUrl`, and created an extension which sets up a stubbed JWKS endpoint (`JwksExtension`)
Covered by existing tests
Stacked on this PR: https://github.com/govuk-one-login/authentication-api/pull/6901
=> ATO-1860: Refactor JWKS caching code

template.yaml
Migrate doc app table from Auth to Orch
Remove old policies usages in lambdas
Deployed to Dev
=> Ato 1746/remove cloudformation doc app policy usage

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/IntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java, template.yaml
We have a bunch of feature flags that are always true for all envs. This is starting to remove these flags.
Removes IsReturnAuthTimeInIdTokenEnabled feature flag.
TODO: test on dev
=> ATO-1883: refactor is return auth time in id token enabled

orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/ClientSignatureValidationServiceTest.java, template.yaml
We have a bunch of feature flags that are always true for all envs. This is starting to remove these flags.
Removes EnableFetchJwks feature flag.
TODO: test on dev
=> ATO-1876: refactor enable fetch jwks

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
We would like to migrate away from using auth's UserProfile table in orch. In UserInfoHandler, we use the user profile to calculate the internalCommonSubjectIdentifier (ICSID). We already have the ICSID available on the access token info store, so we should be able to swap to using that instead. Before we do that we want to make sure these 2 fields are in sync.
This PR adds logging to UserInfoService to compare the ICSID calculated from the user profile with the ICSID from the access token info store. 
Deployed to dev and performed an auth only journey. I saw the log message indicate the fields are equal.
=> ATO-1918: Add logging to compare internal subject ID values

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/helpers/ClientSubjectHelper.java
We would like to move away from using the user profile table in orch. We can start by using the access token to get the internal common subject ID (ICSID) instead of calculating this using the user profile.
We merged a PR in last week to log whether these values are the same. Over the weekend there was no logs to show that they were not equal so we can be confident they are the same. 
This PR swaps to using the ICSID from the access token instead of calculating the ICSID from the user profile. This also means we can remove some now unused helper methods.
Tested in dev. Did an auth only journey and an identity journey. Both journeys ended with the correct user info subject displayed.
Also did a docapp journey which also finished successfully.
=> ATO-1919: Swap to using ICSID from access token

account-management-integration-tests/build.gradle, build.gradle, delivery-receipts-integration-tests/build.gradle, docker-compose.yml, echo-int-test-vars.sh, integration-tests/build.gradle
- Updated mock access key to be alphanumeric (see https://repost.aws/articles/ARc4hEkF9CRgOrw8kSMe6CwQ/troubleshooting-the-access-key-id-or-security-token-is-invalid-error-after-upgrading-dynamodb-local-to-version-2-0-0-1-23-0-or-greater)
- Updated localstack config to include SNS which is required for orch tests
1. Code Review
1. Run integration tests locally
=> BAU: Use mock access key adhering to local dynamo restrictions

deprecation-checker/src/main/java/uk/gov/di/deprecationchecker/DeprecationChecker.java, deprecation-checker/src/test/java/uk/gov/di/deprecationchecker/DeprecationCheckerTest.java, deprecation-config.json
Optimises the DeprecationChecker by:
• Only checking protected files instead of all Java files for better performance
• Skipping checks when file content is identical to avoid unnecessary processing
• Comparing against merge base with main to prevent false positives when branches aren't rebased after new enum values are added to main
These changes make the deprecation checker more efficient and eliminate false violations that occur when PRs haven't been rebased against the latest main branch.
1. Code Review
<!-- UCD Re
=> BAU: Improve DeprecationChecker

ci/cloudformation/auth/parent.yaml, ci/terraform/oidc/shared.tf, ci/terraform/shared/authdev1.tfvars, ci/terraform/shared/authdev2.tfvars, ci/terraform/shared/authdev3.tfvars, ci/terraform/shared/build.tfvars, ci/terraform/shared/dev.tfvars, ci/terraform/shared/integration.tfvars, ci/terraform/shared/production.tfvars, ci/terraform/shared/sandpit.tfvars, ci/terraform/shared/secrets-manager.tf, ci/terraform/shared/staging.tfvars, ci/terraform/shared/variables.tf
We are aiming to move the test client lists into secrets manager and out of the client registry - so this does the first step of this - provisioning an empty secret which we will populate manually.
- Adds feature flagged infra for creating a new secret 
- Also added the new secret in the cloudformation - not sure how to test this so will defer to someone from Auth
- Deployed to sandpit and saw infra created
- Set flag to false for sandpit and saw that the resources were destroyed on re-deployment. 
- Once merged I will need to manually deploy these changes to all the dev environments. Once deployed to all envs I will need to manually update each value.
=> ATO-1609: add secret for test client

account-management-api/api-contract/README.md, account-management-api/api-contract/mock/rest-plugin-config.yaml, ci/terraform/account-management/openapi_v2.yaml, shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
Updates the update-email OpenAPI documentation and Imposter mock support to match the current implementation and upcoming changes for email blocks.
1. Code Review
=> AUT-4210: Enhance update-email API specification and mock support

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/AccessTokenStore.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/RefreshTokenStore.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/TokenService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/TokenServiceTest.java
We would like to remove the use of user profile in TokenHandler. The user profile was used to get the internalSubjectId to set in the tokenService.generateTokenResponse. The internalSubjectId isn't actually used anywhere, so we can safely remove it.
This PR removes the `internalSubjectId` field from `AccessTokenStore` and `RefreshTokenStore`. There are quite a few commits in this PR mainly to ensure we do not cause errors (as the `RefreshTokenStore.internalSubjectId` was used to create new access tokens and refresh tokens)
Paired on this with @james-peacock-gds 
Deployed and tested this in dev. Made a refresh token request and saw new access and refresh tokens were generated and returned to us.
Also tested that users in the middle of a journey when this was deployed were not affected.
=> ATO-1903: Remove internalSubjectId from access token store and refresh token store

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotificationType.java, account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/entity/Application.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotifiableType.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java
Adds two new methods which collectively emit four new metrics when either emails or sms are sent via Notify, and also when client errors happen when sending.
emitMetricForNotification
- SmsNotificationSent
- EmailNotificationSent
emitMetricForNotificationError
- SmsNotificationError
- EmailNotificationError
At the moment Notify metrics are only created on the back of delivery receipts received from Notify (and the networks).  As there is no guarantee that we’ll get a delivery receipt the metrics are not a true reflection of the number of messages actually sent.
=> AUT-4569: Emit notification metrics

ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/login.tf
AWS IAM has a hard limit of [20 policies per role](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#:~:text=Managed%20policies%20per%20role). The login handler is at this limit, and we need to free up some slots for future work. To achieve this we can combine the `authentication_attempts-*` policies into one policy. This role starts that by duplicating the original role and then combining these policies into one. This is the first part of a series of changes - done in this order to ensure no re-ordering of policies in an existing role and that this change is ZDD compatible .
- Adds a new duplicate login role - with the combined  `authentication_attempts-*` read/write/delete into one policy instead of three
- Deploy to sandpit:
- Saw new policy created
=> ATO-1878: Duplicate role in login handler with condensed policies

ci/terraform/shared/dynamodb.tf
Migrate doc app table to orch
Turn table protection off on doc app table in auth so it can be deleted
Deploy to sandpit
=> ATO-1746: disable table protection on doc app table so it can be deleted

ci/terraform/oidc/authorize.tf, ci/terraform/oidc/doc-app-callback.tf, ci/terraform/oidc/jwks.tf, ci/terraform/oidc/shared.tf, ci/terraform/oidc/userinfo.tf
Migrate Doc App table to Orch
Remove Auth Doc App table policy usages
Deploy to sandpit and run through doc app journey
=> ATO-1746:remove policy usage on auth doc app table

audit-events/build.gradle, audit-events/src/main/java/uk/gov/di/authentication/auditevents/entity/AuthEmailFraudCheckBypassed.java, audit-events/src/main/java/uk/gov/di/authentication/auditevents/entity/ComponentId.java, audit-events/src/main/java/uk/gov/di/authentication/auditevents/entity/StructuredAuditEvent.java, audit-events/src/main/java/uk/gov/di/authentication/auditevents/services/StructuredAuditService.java, audit-events/src/test/java/uk/gov/di/authentication/auditevents/services/StructuredAuditServiceTest.java, docker-compose.yml, docs/adr/0003-structured-audit-service.md, frontend-api/build.gradle, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckEmailFraudBlockHandlerTest.java, integration-tests/build.gradle, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckEmailFraudBlockIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/StructuredAuditServiceIntegrationTest.java, local-running/Dockerfile, settings.gradle, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java, shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java
This PR introduces a new `StructuredAuditService` that provides audit event submission using strongly-typed event classes, replacing the previous unstructured approach for audit events.
An ADR is drafted for this approach and an initial implementation in `CheckEmailFraudBlockHandler` is done. This brings `AUTH_EMAIL_FRAUD_CHECK_BYPASSED` to spec based on the event catalogue.
1. Code Review
1. Deploy and see the `AUTH_EMAIL_FRAUD_CHECK_BYPASSED` audit event is raised as expected in the audit queue after entering email OTP during account creation.
=> AUT-4580: Implement `StructuredAudit*` for typed events

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/AuthenticationAuthCodeHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckReAuthUserHandlerTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerReauthenticationUsingAuthenticationAttemptsServiceTest.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
A user being able to reauthenticate is predicated on the principle that we know their internal common subject (ICS) ID. To verify that a user is who they say they are we compare the user credentials associated with an ICS derived from the user context against the user credentials of the email entered during reauth. As such, we should emit the ICS as the user_id for all reauth audit events.
The ICS is not to be confused with the subject ID on the user profile. The subject ID on the user profile is a raw UUID subject. The ICS, however, takes this value with a salt and the internal sector URI and hashes the concatenation of these values.
1. Code Review
=> AUT-4543: Use internal common subject in reauth audit events

ci/terraform/oidc/build.tfvars, ci/terraform/oidc/dynamo-policies.tf, ci/terraform/oidc/integration.tfvars, ci/terraform/oidc/production.tfvars, ci/terraform/oidc/sandpit.tfvars, ci/terraform/oidc/staging.tfvars, ci/terraform/oidc/variables.tf, template.yaml
We would like to move the client registry into the orch account. We created a dynamo table with an encryption key in a previous ticket. We would like to make sure all handlers that access the auth client registry can access the orch client registry.
This PR adds the new client registry table to the existing client registry access policies. 
Tested in sandpit by adding 2 new methods to the ClientService interface for testing reading and writing to the new orch client registry table, and implemented them by adding a new reference to the orch client registry table in DynamoClientService.
I then updated the implementation of ClientRegistrationHandler at the very start to check that calling write and read on the new table would not throw any access errors
I also updated the …
=> ATO-1921: Update client registry policies to allow access to new table in orch

ci/terraform/oidc/alerts.tf, frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java, frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetricDimensions.java, shared/src/main/java/uk/gov/di/authentication/shared/domain/CloudwatchMetrics.java, shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java, shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java
When the international SMS quota is exceeded we start to get 429 responses from Notify.
This change adds two alarms for exceeding the international quota and the domestic quota.  In production the alarms with trigger PagerDuty.
This is part one of two changes.  The next change will be an early warning alarm when the number of messages being sent looks like the daily quota will be exceeded.
1. Deploy to a dev environment.
2. Check the metrics and alarms are created.
3. Use the aws cli to emit updates to the metric and check the alarm is activated.
4. Optionally create a subscription on the SNS topic to confirm the alarm is emitting a notification.
I have already tested this in authdev1 and confirmed the alarms are activated and received notifications from SNS.
=> AuUT-4633 Add daily sms limit reached alarms

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java, account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckEmailFraudBlockIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoEmailCheckResultServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/NowHelper.java
Move the `unixTimePlusNDays` into the shared `NowHelper`
Return a 403 in the `UpdateEmailHandler` if the `PendingEmailCheckResultStatus` is `DENY`
1. Code Review
2. Tested by @alhcomer and I and it passed
=> AUT-4210: UpdateEmailHandler should reject block email addresses

ci/terraform/shared/integration.tfvars, ci/terraform/shared/production.tfvars, ci/terraform/shared/variables.tf
Switch off Dynamo streaming on user-profile in non-prod environments
Dynamo streaming was originally used to trigger an Experian phone check when a phone number was added to the database.  This is now deprecated and has been replaced by an SQS message instead, but streaming is still switched on.
Proves the switch off in all test environments.
1. Code Review
1. Deploy to a test environment and run journeys to prove that the application is still working correctly.
Configuration equivalent to integration and production here has been tested in a test environment to prove that streaming will be maintained in those environments (for the moment)
=> BAU: Switch off Dynamo streaming on user-profile in non-prod environments

ci/terraform/shared/integration.tfvars, ci/terraform/shared/production.tfvars
Switch off Dynamo streaming on user-profile in prod environments
Dynamo streaming was originally used to trigger an Experian phone check when a phone number was added to the database.  This is now deprecated and has been replaced by an SQS message instead, but streaming is still switched on.
Following the switch-off in test environments this change switches off in integration and production.
#7059
=> BAU: Switch off Dynamo streaming on user-profile in prod environments

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
We would like to add a new dashboard to measure the requests to orch's /authorize endpoint by client name. 
This PR emits a new cloudwatch metric `orchAuthorizeRequestCount`, every time a client makes a valid /authorize request. 
This PR also adds the `clientName` to the `rpStateLength` metric, as there was only the `clientId` on it before, which made it harder to identify which client was nearing the state length limit at a glance.
Deployed to dev, saw the new metrics appear in cloudwatch
=> ATO-1944: Emit new metric for valid /authorize request

ci/terraform/shared/kms.tf, ci/terraform/shared/sqs-policy.tf, ci/terraform/shared/sqs.tf
- Sets the retry policy to what is outlined in AUT-4197
- Sets permissions to allow the email check account to send SQS messages to the pending email check DLQ. These permissions are the allowance of ingress of SQS messages from the email check account to the pending email check DLQ, and the allowance of the email check account to use the pending_email_check_queue_encryption_key to encrypt those messages.
1. Code Review
2. Deploy to dev with the associated PR. Send a message to the lambda in the AWS test area with the email 'stubemailassessmentfailure@example.com'. See that this SQS message appears in the pending email check DLQ.
https://github.com/govuk-one-login/authentication-check-experian/pull/514
=> AUT-4197: Set email check retry policy

template.yaml
We currently cache JWKS keys in memory, which works for when the lambda runs with provisioned concurrency at the moment. However, we would like to turn on SnapStart for lambdas to improve response time. The downside to this is that we wont be able to use an in-memory cache.
Instead of storing the cache in memory, we can use DynamoDB to store public keys we are caching. The logic for caching will remain mostly the same, and we can even delegate to DynamoDB to invalidate cache entries with a TTL (we are currently doing this manually).
Created an empty dynamoDB table with JwksUrl partition key and KeyId as sort key. Also the read/write policy has been created.
Ran on dev
=> ATO-1849: add JwksCache table and policies

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java, account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/CheckEmailFraudBlockIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/EmailCheckResultWriterIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoEmailCheckResultServiceIntegrationTest.java, shared/src/main/java/uk/gov/di/authentication/shared/converters/ObjectConverter.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultSqsMessage.java, shared/src/main/java/uk/gov/di/authentication/shared/entity/EmailCheckResultStore.java, shared/src/main/java/uk/gov/di/authentication/shared/helpers/CommonTestVariables.java, shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoEmailCheckResultService.java, shared/src/test/java/uk/gov/di/authentication/shared/converters/ObjectConverterTest.java, utils/src/main/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandler.java, utils/src/test/java/uk/gov/di/authentication/utils/lambda/EmailCheckResultWriterHandlerTest.java
Updates the email check result cache writing process to handle additional data sent by the service; journey IDs and structured response data required the later `_DECISION_USED` audit event.
1. Code Review
1. Deploy along with matching PR from checking repo
1. Submit an email address though account creation
1. Wait and see in the cache DynamoDB table that a new record is added for the email with the expected properties and values
=> AUT-4557: Support enhanced email check audit data

template.yaml
We want to add an alarm to know when a rate limit has been hit for a client.
A new cloudwatch alarm triggered on the `RpRateLimitExceeded` metric
Tested in dev
=> ATO-1892: add rate limit alarm

orchestration-alerting/slackNotifications.js, template.yaml
We would like to make the orch-nonprod-alerts slack channel less noisy. We already have a prod-alerts slack channel for build notifications. 
This PR creates a new version of the `SlackNotificationsFunction` specifically for production alerts. This involves creating a new encrypted SNS topic. All the new Prod specific infrastructure is only deployed in the prod environment. This new version (ProdSlackNotificationsFunction) is only used in the back channel logout DLQ alarm at the moment.
It's best to review this commit-by-commit, as the penultimate commit applies our JS linting rules to the whole `slackNotifications.js` file and makes the diff look awful :smile:
I've also added the new SSM params needed for the prod alarms to work
Tested in dev by temporarily adding the dev environment to …
=> ATO-1941: Send slack alerts to orch prod alerts channel

template.yaml
Roles outside of admin TEAM roles should not have access to these tables
Retrying https://github.com/govuk-one-login/authentication-api/pull/6984 with a slightly different If syntax - have retested
=> ATO-1866: Add resource policies to PII containing tables

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
We recently added a metric to measure when an RP makes a valid authorize request. The next 2 graphs we want to add is for number of successful auth and number of successful identity journeys. We have no way of distinguishing between a request for auth or a request for identity at the moment, so we need to add a new dimension to the metric we added in the previous PR. 
This PR adds the `isIdentityJourney` dimension to the `orchAuthorizeRequestCount` metric.
=> ATO-1945: Add isIdentityJourney dimension to existing metric

ci/terraform/oidc/verify_code.tf, ci/terraform/oidc/verify_mfa_code.tf
AWS IAM has a hard limit of [20 policies per role](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#:~:text=Managed%20policies%20per%20role). The verify code and verifyMfaCode handlers are at this limit, and we need to free up some slots for future work. To achieve this we can combine the `authentication_attempts-*` policies into one policy. This role starts that by duplicating the original role and then combining these policies into one. This is the first part of a series of changes - done in this order to ensure no re-ordering of policies in an existing role and that this change is ZDD compatible .
- Removes unused role
- Deploy to sandpit:
- Saw old role removed
=> ATO-1878: remove old roles

docker-compose.yml, local-running/README.md, local-running/docker-compose.yml
Orch and Auth integration tests both use this dockerfile for their core dependencies. Even though they don't use the orch-stub and auth-frontend containers, it still validates that the env files exist - meaning that you need to check out those repositories to run the tests.
By separating the docker compose files, we can keep the core dependencies separate.
=> BAU: Separate local running dockerfile

orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/matchers/ResultMatcher.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/result/Err.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/result/Ok.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/result/Result.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/result/ResultTest.java
This introduces a `Result<T,U>` type with accompanying test and matcher. We will expand on this in the future as we wire it into our handlers.
=> BAU: Result type for Orchestration

.github/workflows/dependency-review-on-pr.yml, build.gradle
Jetty is only used by local running, but must be pinned to v11 because Javalin does not yet have support for v12. See https://github.com/javalin/javalin/issues/2067 - it is planned for Javalin 7, but there is no clear release date.
It is not used in any deployed services and does not expose us to risk when used locally, so the CVE can be safely dismissed:
- CVE-2024-6763 could cause misinterpretation of maliciously crafted URLs
If additional/higher severity CVEs appear, we may need to consider migrating to a different framework.
=> BAU: downgrade Jetty for local running

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
Reverts govuk-one-login/authentication-api#7091
Adding the clientName dimension to the successfulTokenIssued metric broke some RP Dashboards.
After reverting this change, if necessary we'll add a new metric.
=> Revert "ATO-1946: Add clientName to token metric"

template.yaml
[AUT-4708] : give access to orch owned resource to new Auth AWS account ID
This change is to give Access to orch dynamo db table and Kms key to new Auth Aws account ID , where processing identity lambda will access these table data 
https://github.com/govuk-one-login/authentication-api/pull/7103
[AUT-4708]: https://govukverify.atlassian.net/browse/AUT-4708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AUT-4708: give access to orch owned resource to new Auth AWS account ID

ci/terraform/account-management/manually-delete-account.tf
Increase memory for the manually-delete-account lambda
Some deletions failed due to out of memory errors
1. Code Review
1. Deploy to a test environment with `./deploy-authdevs.sh -b -a`
1. Go into the lambda console and find the lambda so it can be tested
1. Follow the [instructions](https://govukverify.atlassian.net/wiki/spaces/OPS/pages/5032673281/TSD+Account+Deletion+Process#Part-Three---TSD-Engineer-processing-account-deletions) to test deleting an account 
Tested in authdev1
=> AUT-4714: Increase memory for the manually-delete-account lambda

ci/terraform/shared/sqs.tf
- The AWS default is 0 seconds
- The 10s delay was causing unnecessary latency
1. Code Review
=> AUT-4207: Delete delay_seconds

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java, doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java, oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DocAppAuthorisationServiceTest.java, template.yaml
We currently cache JWKS keys in memory, which works for when the lambda runs with provisioned concurrency at the moment. However, we would like to turn on SnapStart for lambdas to improve response time. The downside to this is that we wont be able to use an in-memory cache.
Instead of storing the cache in memory, we can use DynamoDB to store public keys we are caching. The logic for caching will remain mostly the same, and we can even delegate to DynamoDB to invalidate cache entries with a TTL (we are currently doing this manually).
Setting the JWKSCacheItem and added logs to check.
Tested DocApp journey in dev. TODO: test IPV journey in dev
=> ATO-1851: set JWKSCache

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/ClientRateLimitDataService.java, oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientRateLimitDataServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/BaseDynamoService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ConfigurationService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/JwksCacheService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchClientSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/OrchSessionService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/StateStorageService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchClientSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/StateStorageServiceTest.java, template.yaml
We have recently started seeing issues possibly related to not using strongly consistent reads in production. We currently have a feature flag that enables strongly consistent reads up to staging
This PR removes the feature flag for enabling strongly consistent reads, and instead always enables strongly consistent reads in all environments.
=> ATO-1975: Enable strongly consistent reads in all orch environments

orchestration-alerting/slackNotifications.js, template.yaml
We currently have pagerduty alarms configured in auth, but not in orch.  We should move the pagerduty alarms that are orch-related into orch too.
This PR creates 2 new cloudwatch alarms:
- One will alarm if more than 20 errors appear in the IPV callback handler and SPOT response handler over 10 mins. 
- One will alarm if more than 20 errors appear in the DocApp callback handler over 10 mins.
Both these alarms are configured to publish the alarm event on a new SNS topic: `${Environment}-pagerduty-alerts `. There is also a subscription to this topic configured in the template file, which uses the PagerDuty URL defined in a secret. 
These alarms will only be created if the environment is production and there is a `pagerDutySecretId` defined in the environment configuration for production. …
=> ATO-1777: Setup PagerDuty alarms in orch

utils/build.gradle
- This is so that the email check results writer can autoconfigure, allowing shared trace context to link up spans from the results writer to traces from calling services
1. Code Review
=> BAU: add open_telemetry dependency to utils

orchestration-alerting/slackNotifications.js
For some reason we are filtering out the build env when sending slack alerts to our channels. We should allow for alerts to be sent from the build environment
This PR sends slack notifications from all environments, instead of just dev, staging, integration and production
=> ATO-1979: Allow orch slack alerts to be send from build environment

oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/ClientRateLimitDataServiceTest.java, orchestration-shared-test/src/main/java/uk/gov/di/orchestration/sharedtest/basetest/BaseDynamoServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DynamoClientServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/JwksCacheServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchAuthCodeServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchClientSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/OrchSessionServiceTest.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/StateStorageServiceTest.java
While adding a new dynamo service, we noticed there is a lot of duplication across the dynamo service tests, mainly for setting up mocks.
This PR extracts an abstract class `BaseDynamoServiceTest`, which takes a dynamo bean as a generic type, and sets up the relevant mocks. It also adds a helper method to create a get request for a given partition key (as we have to specify `consistentReads(true)` every time now we're always using consistent reads.
Refactoring existing tests, so not needed.
=> BAU: Refactor orch dynamo tests

orchestration-alerting/slackNotifications.js
We recently added PagerDuty alarms that, when triggered, notify PagerDuty and send a slack message to the `pagerduty-slack-channel-id`. We would also like to send this slack message to `production-slack-channel-id` for increased observability. 
This PR does a bit of refactoring in `slackNotifications.js`, allowing for you to send multiple slack messages in one invocation of the lambda. If a pagerduty alarm is triggered, it will send a slack message to the `pagerduty-slack-channel-id` channel first, then it will send a slack message to `production-slack-channel-id`
Tested by enabling the pagerduty alarms in dev. Saw 2 slack messages get sent to 2 different channels from the lambda.
=> ATO-1777: Send Slack messages to 2 channels for orch PagerDuty alerts

shared/build.gradle, shared/src/main/java/uk/gov/di/authentication/shared/helpers/TestClientHelper.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/TestClientHelperTest.java
- Adds a method to get a secret value from secrets manager
- Method is currently only implemented in tests 
- Method not yet used so no manual testing required
=> ATO-1875: Add method to get list from secrets manager

.github/workflows/call_get_changed_files.yml, .github/workflows/pre-merge-checks.yml, .pre-commit-config.yaml, orchestration-alerting/babel.config.json, orchestration-alerting/jest.config.json, orchestration-alerting/package-lock.json, orchestration-alerting/package.json, orchestration-alerting/slackNotifications.js, orchestration-alerting/slackNotifications.test.js
We didn't have any test coverage for the code that sends slack notifications to orch. 
This PR adds some jest tests to verify the slackNotifications code works. I've also updated the github actions configuration so that if any of these files are changed, then the new tests will run. If none of the files in `orchestration-alerting` have changed, then the tests will not run.
=> ATO-1978: Add unit tests for orch slack notifications

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthenticationCallbackHandlerIntegrationTest.java, integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationServiceTest.java
At this point we should be confident that the cross browser data stored in dynamo is the same as data stored in redis (from the logs we added in the previous ticket). Now we can safely remove redis from the CrossBrowserOrchestrationService, starting with removing the reads from redis.
Tested in dev by forcing cross browser errors (clearing cookies and hitting the callback endpoints directly with the correct query params). All 3 types of journey (auth only, identity, docapp) got the clientSessionId from the state successfully.
This PR stops reading from redis in CrossBrowserOrchestrationService. It also removes unused test assertions and setup.
A follow-up PR will remove the instances where we are writing to redis.
=> ATO-1985: Stop reading from redis in CrossBrowserOrchestrationService

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ManualUpdateClientRegistryHandler.java, template.yaml
For TSD to be able to update the client rate limit, we need a new lambda to manually update the client registry.
New lambda
Deployed to dev
=> ATO-1993: create Manual Update Client Registry Lambda

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java, ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/CrossBrowserOrchestrationServiceTest.java
The cross-browser issue has a variant scenario for V2 App where the callback is for a different client session, but both are still valid.
This log should provide some indication as to how frequently this happens, which can be used to prioritise a more substantial change to attempt recovery on those journeys.
=> BAU: Additional logging for possibly recoverable cross-browser scenarios

orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/helpers/PersistentIdHelperTest.java, shared/src/test/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelperTest.java
`IdGenerator.generate()` can generate an ID with double dashes in it (`--`). This caused the `Base64.getUrlDecoder().decode()` call to throw an `IllegalArgumentException`, as only part of the ID was included as a parameter.
I've static mocked the `IdGenerator` here and made it return an example ID I generated previously.  I've updated auth's test for this too as it would impact both of our builds :)
=> BAU: Fix flaky test in PersistentIdHelperTest

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ManualUpdateClientRegistryHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java, client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ManualUpdateClientRegistryValidationService.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ManualUpdateClientRegistryHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java, client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ManualUpdateClientRegistryValidationServiceTest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/entity/ManualUpdateClientRegistryRequest.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/ClientService.java, orchestration-shared/src/main/java/uk/gov/di/orchestration/shared/services/DynamoClientService.java, orchestration-shared/src/test/java/uk/gov/di/orchestration/shared/services/DynamoClientServiceTest.java
For TSD to be able to update the client rate limit, we need a new lambda to manually update the client registry.
Lambda logic and validation added.
Tested on authdev3
- no `rate_limit` or `rate_limit = null` does not break and does not turn off rate limit
- only whole numbers are accepted
- `rate_limit = "''"` will turn off rate limit
=> ATO-1995: update rate limit from ManualUpdateClientRegistryHandler
