govuk-one-login/authentication-api

ci/terraform/modules/api-gateway-root/api-gateway-root.tf
ci/terraform/modules/api-gateway-root/variables.tf

add omitted terraform module for api-gateway-root
fix broken build
#6

LGT-267: add omitted terraform module for api-gateway-root

---

ci/pipeline.yaml

update lambda.zip path in the build
relative path has changed due to terraform modules
#6 
#8

LTG-267: update lambda.zip path in the build

---

ci/pipeline.yaml

update relative path for terraform plan
root module has moved so relative path to plan file has moved too
#9

LTG-267: update relative path for terraform plan

---

ci/terraform/aws/outputs.tf

add url outputs to the top level
outputs from modules not being displayed

LTG-267: add url outputs to the top level

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java

- Add simple authorize endpoint lambda
- Currently, does not know about user state, and will just succeed if correctly formed request is received.
We're porting OIDC endpoints from a DropWizard app to Lambda.

LTG-257: Add authorize endpoint lambda and tests.

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

- AWS lambda has deprecated the use of accepting multiValueQueryStringParameters so therefore refactor to accept query string params.
- https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

LTG-257 - Use the non-deprecated way of accepting query params

---

ci/terraform/aws/wellknown.tf
ci/terraform/localstack/localstack.tf
ci/terraform/modules/wellknown/api-gateway-token.tf
ci/terraform/modules/wellknown/lambda.tf
ci/terraform/modules/wellknown/variables.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java

- Get the BASE_URL environment variable by using System.getenv and move this to a separate configuration service
- Add the required terraform for the wellknown lambda and apigateway
- Amend the unit tests to mock out the configuration service

LTG-265 - Add terraform to create wellknown lambda

---

ci/pipeline.yaml
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenResourceIntegrationTest.java
pre-commit.sh
scripts/functions.sh
settings.gradle

Add basic integration test to run locally.
Create integration-tests module.
Run integration tests from pre-commit.
Exclude from running in the build pipeline pending work to add into the build.
Ability to write tests calling the api in API Gateway connected to the Lambda functions.

LTG-275: add basic integration test to run locally

---

ci/terraform/aws/jwks.tf
ci/terraform/aws/outputs.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
ci/terraform/modules/endpoint-module/lambda.tf
scripts/functions.sh
scripts/test-api.sh
serverless/lambda/src/main/java/uk/gov/di/lambdas/JwksHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/JwksHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java

- Some client libraries require this endpoint when integrating so we need to have this run as a lambda function.
- The signing key is currently generated on the fly in the token service but eventually this will be swapped out with something more permanent
- Add terraform for jwks lambda and api gateway
- The jwks endpoint will use the well-known base path
- Amend the api_gateway_root_id to use snake case and fix the integration tests
- When constructing the lambda function_name remove any full stops. This is because we are currently using the endpoint name and the jwks endpoint is 'jwks.json' which terraform will not like.
- Rather than constructing the URL manually for the integration tests we can use the URL generated from outputs.tf

LTG-266 - Create Lambda for /jwks.json endpoint

---

ci/terraform/aws/outputs.tf
ci/terraform/aws/register.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
ci/terraform/modules/api-gateway-root/api-gateway-root.tf
ci/terraform/modules/api-gateway-root/outputs.tf
serverless/lambda/src/main/java/uk/gov/di/entity/Client.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/SignupRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java

- Create a new Lambda handler which will handle POST requests when a Client is registering their software
- Remove Scopes for the Client class as it is not part of the Dynamic Client Registration spec https://openid.net/specs/openid-connect-registration-1_0.html
- Add the ability to serialize and deserialize the Client class
- Write terraform for API Gateway and Lambda for Dynamic Client reg

LTG-284 - Migrate dynamic client endpoint to Lambda

---

serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

- It was previously immutable so we couldn't add a new client to the list.

LTG-284 - Instantiate a new Client array list

---

ci/terraform/aws/authorize.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/redis.tf
ci/terraform/aws/register.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/wellknown.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/vpc.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

In previous PR we created a VPC and security group for Elasticache, lets now associate our lamdas and Elasticache with it.
We want to secure access to the session data in the Redis cluster.

LTG-191: Add Lambdas and Elasticache to Security Groups

---

ci/terraform/aws/authorize.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/redis.tf
ci/terraform/aws/register.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/vpc.tf
ci/terraform/aws/wellknown.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/site.tf
ci/terraform/localstack/vpc.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
docker-compose.yml

- Add subnets, one per AZ, to the VPC
- Allow the lambda function to use these subnets
- Convert the Redis instance to a cluster with replicas in each AZ/subnet.
- Ensure VPCs are created using "localstack" aws provider
- Enable EC2 service in localstack to enable use of VPCs and subnets
To provide access to Redis by Lambdas and to provide fault tolerance

LTG-300: Add subnets and convert Redis instance to cluster

---

ci/terraform/aws/redis.tf

- Need to lock in version 6.0.5 rather than "6.x" or Terraform will try and re-create.
We are getting failures in the pipeline.

LTG-300: Fix Redis deployment engine version

---

serverless/lambda/build.gradle
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/JwksHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/matchers/APIGatewayProxyResponseEventStatusMatcher.java

This PR pulls in Hamcrest 2.2 (latest) to improve the way we write our test assertions.
Additionally, this PR includes an example custom Matcher for APIGatewayProxyResponseEvent, as we'll be asserting on this _a lot_ in our tests.

BAU: Integrate Hamcrest and create custom Matchers

---

ci/pipeline.yaml

Remove app deployment from the pipeline.
The api is no longer an app but is built on API Gateway and Lambda.

LTG-301: stop deploying api app

---

ci/terraform/aws/authorize.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/redis.tf
ci/terraform/aws/register.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/userexists.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/vpc.tf
ci/terraform/aws/wellknown.tf
ci/terraform/localstack/localstack.tf
ci/terraform/modules/endpoint-module/lambda.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

- Set all Lambdas to use the default security group for the VPC
- Set timeout of the Lambdas to 30 seconds
- Increase the memory of the lambdas from default to 512. We were unable to connect to Redis with 128 mb.
- Configure the LOGIN_URI to the frontend client which runs in PaaS
- Add environment variable for Redis endpoint by using the primary endpoint address

LTG-300 - Connect authorize lambda to Redis

---

ci/terraform/aws/authorize.tf

The redis URL expects the redis:// prefix

BAU - Fix Redis URL

---

ci/terraform/aws/authorize.tf
ci/terraform/aws/redis.tf
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java

- Add encryption to Redis cluster
- Use "6.x" as engine version and ignore changes to work around Terraform provider issue.
- Open secure connection to Redis from Lambda
- Refactor Redis connection 
To provide secure connection and storage in Redis

LTG-300: Secure Redis Cluster

---

serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java

Change the error handling to log and re-throw rather than default print stack trace which was inadvertently left in.
Correct error handling is a good thing.

LTG-300: Improve error handling in session save

---

ci/terraform/aws/sqs.tf
ci/terraform/localstack/site.tf
ci/terraform/localstack/sqs.tf
ci/terraform/modules/endpoint-module/outputs.tf
ci/terraform/modules/sqs-queue/sqs.tf
ci/terraform/modules/sqs-queue/variables.tf
docker-compose.yml

- Create an SQS queue module to build a queue and related policies
- Add module to localstack Terraform
- Enable SQS in localstack
- Enable SQS in AWS 
- Restrict access to the SQS queue for a specific Lambda. It is currently the userexists Lambda as the Lambdas which will talk to it haven't been built yet.
- So it can be used by the Lambda to put messages on the queue for when a user doesn't have an account. Another Lambda will read from the queue and be responsible for using Notify to send an email.

Ltg 313 create sqs queue

---

serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java

- A copy and paste error meant we were serialising the wrong object.
The lambda is not executing due to a serialisation error.
#51

LTG-300: Serialise the session object

---

.gitignore
ci/terraform/aws/outputs.tf
ci/terraform/aws/sqs.tf
ci/terraform/aws/verify_email.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
ci/terraform/localstack/site.tf
ci/terraform/localstack/variables.tf
ci/terraform/modules/sqs-queue/outputs.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/NotificationType.java
serverless/lambda/src/main/java/uk/gov/di/entity/NotifyRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/UserWithEmailRequest.java
serverless/lambda/src/main/java/uk/gov/di/helpers/ApiGatewayResponseHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendUserEmailHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AwsSqsClient.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendUserEmailHandlerTest.java

- Add a simple lambda to put a message on the queue. Lambda accepts e-mail in body of request and passes on to queue. No validation against session at this time.
- Write terraform to create verify-email lambda. This terraform will create a lambda which can be accessed via api-gateway using the 'verify-email' path. The verify-email uses the SendUserEmailHandler to put a message on the SQS queue.
- So we have a Lambda to put messages onto a queue

Ltg 313 - Create lambda to populate queue

---

serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java

- We only need the SQS_ENDPOINT set if we are using localstack so it is fine to be null when running in AWS.
- So we don't get a null pointer when running in AWS

LTG-313 - Make the SQS_ENDPOINT config Optional.ofNullable

---

ci/terraform/aws/vpc.tf

- Add SQS as an endpoint to our VPC.
Connection to SQS is timing out.
#57

LTG-313: Add VPC endpoint for SQS

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorizationAPIResourceIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenResourceIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java

Add scope to /authorize redirect.
Refactoring of existing integration test to reduce duplication of variables.
Integration test not provided as we don't currently have a local Redis which is making the test fail.
So that the scope can be stored in a client session.

LTG-35: scope on auth redirect

---

ci/terraform/aws/verify_email.tf
ci/terraform/localstack/localstack.tf
ci/terraform/modules/sqs-queue/outputs.tf
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java

- Pass the queue URL (Terraform `id`) to lambda rather than just the name.
- Rename the environment variable for the queue URL to acurately represent what it contains.
Lambda is failing to connect to the queue to send messages.

LTG-313: Pass full queue URL to lambda

---

ci/pipeline.yaml
ci/terraform/aws/sqs.tf
ci/terraform/aws/variables.tf
ci/terraform/localstack/sqs.tf

- Read the API key from parameter store when deploying the lambda and assign it to a terraform variable.
- Read the terraform variable in sqs.tf so it can be assigned to the variable in the config service and then used by the Notification Lambda.
- So we can make the Notification Lambda use Notify to generate an Email

LTG-342 - Read the Notify API key from the concourse pipeline

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java

- Instantiate config service before using it
- Otherwise the Lambda will not work and there will be null pointer exceptions

LTG-342 - Instantiate config service before using it

---

ci/terraform/aws/outputs.tf
ci/terraform/aws/send_notification.tf
ci/terraform/aws/sqs.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

- Update the VerifyEmail Lambda so it can handle all requests that need to use Notify.
- Rename verify-email api endpoint to send-notification
- The Lambda behind this endpoint will handle all notifications so we need to give it a more generic name

LTG-315 - Refactor and rename verify-email lambda

---

serverless/lambda/src/main/java/uk/gov/di/entity/SendNotificationRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/UserWithEmailRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

- Create a new `SendNotificationRequest` object which contains e-mail address and notification type.
The `NotifyRequest` object has the concept of `destination` which can be either an email address or a telephone number. This won't be known by the frontend. The frontend will know the session ID (which it provides as a header) and the e-mail address, which is used to validate against the session ID provided. The actual email address and/or phone number for notifications will be pulled from the user storage before passing onto SQS to deliver to Notify.
#68

LTG-315: Don't expose NotifyRequest to API

---

docker-compose.yml
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsResourceIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/SessionHelper.java
pre-commit.sh
scripts/functions.sh
serverless/lambda/src/main/java/uk/gov/di/entity/BaseAPIResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/CheckUserExistsResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/entity/SessionState.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java

- Add `SessionState` enum
- Add `SessionState` to the session
- Ensure a session starts in the `NEW` state
- Add Redis to docker-compose to allow integration testing
- Add a helper to allow creation of a Session in integration tests
- Add session validation to CheckUserExists lambda (further PR to follow for other lambdas).
We need to track the state of a session during the user journey.

LTG-300: Add Session State

---

ci/terraform/aws/userexists.tf

- Add the required environment variables to allow the lambda to connect to Redis
In previous PR we omitted to add the configuration to the `userexists` lambda.
#70

LTG-300: Inject Redis configuration into userexists lambda

---

ci/terraform/aws/signup.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupResourceIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/Messages.java
serverless/lambda/src/main/java/uk/gov/di/entity/SignupResponse.java
serverless/lambda/src/main/java/uk/gov/di/helpers/ApiGatewayResponseHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

- Validate session exists before attempting to create user
- Update session with relevant state and username before returning success
- Add integration test
- Create constants for repeated text strings.
We need to validate that we are in a valid session before we create a user.

LTG-300: Add session handling to `SignupHandler`

---

ci/terraform/aws/send_notification.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

- Run Spotless on previous PR
- Add environment variables required for Redis connection to the SendNotification handler Terraform
Require connection to Redis to validate session
#74

LTG-300: Spotless and missing environment variables

---

serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/helpers/IdGenerator.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

- Change the query variable name used to pass the session ID to the frontend
- Use a session ID generator better with more entropy than a UUID
- Refactor Session constructor
More randomness should be used for generating session IDs to reduce the chances of a rogue actor guessing and manipulating session.

LTG-300: Re-factor session ID generation

---

serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

- Update in memory client redirect URIs
- So that the Stub RP in the Build PaaS space is configured to talk to it

BAU - Update in memory client redirect URIs

---

serverless/lambda/src/main/java/uk/gov/di/entity/Session.java

- Add json property annotation to attributes in the Session
- So that the object uses the same property names to de-serialized as it does to searlize

LTG-300 - Add json properties to attributes in Session

---

serverless/lambda/src/main/java/uk/gov/di/services/InMemoryClientService.java

- Add Redirect URI of the Local Stub RP to the in memory client
- So we can run a journey against the Lambdas locally

BAU - Add Redirect URI of the Local Stub RP

---

ci/terraform/localstack/sqs.tf
ci/terraform/localstack/variables.tf
docker-compose.yml
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/helpers/httpstub/HttpProxyExtension.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/httpstub/HttpStub.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/httpstub/HttpStubExtension.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/httpstub/RecordedRequest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/httpstub/RegisteredResponse.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendEmailNotificationIntegrationTest.java
pre-commit.sh
scripts/functions.sh
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java

- Add the HttpStub extension (this was originally developed for the doc-checking project).
- Use HttpStubExtension to listen for a GOV.UK Notify request from the Lambda
- Allow passing in of Notify API URL, to override the default in tests, via environment variables.
- Wait for Lambda to call (the fake) Notify and verify the payload.
- Pad generated code with zeros to fix the test case when generated code is < 100000.
We wish to test that the lambda is correctly calling Notify with the correct parameters.

LTG-342: Integration tests for SQS & Notify

---

serverless/lambda/src/main/java/uk/gov/di/entity/VerifyCodeRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java

- Create a generic Lambda which will expect a notificationType and a code. This will allow this lambda to be used for multiple purposes including verify-email and verify-2fa.
- Eventually this Lambda will be responsible for validating the code.
- Add some tests to test a happy and sad path until more functionality is added.
- So we can validate the code which is sent to the user via Notify

LTG-282 - Create Lambda for validating code

---

ci/terraform/aws/outputs.tf
ci/terraform/aws/verify_code.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IntegrationTestEndpoints.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendEmailNotificationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/VerifyCodeRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java

- Write terraform for verify-code lambda and api gateway
- Add integration test for verify-code endpoint
- Refactor Integration tests
- To create an api-gateway endpoint called 'verify-code' which calls the VerifyCodeHandler, for both localstack and aws 
- Add an integration test for the verify-code endpoint so we can be confident that the endpoint is working as required 
- To make the naming consistent and clear for the Integration tests

LTG-282 - Create terraform for verify-code lambda and api-gateway

---

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendEmailNotificationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/NotifyRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/CodeGeneratorService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/NotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

This PR moves the six-digit code generation from taking place in the SQS-receive lambda to taking place in the `SendNotificationRequest` handler in the API Gateway
We want to store and validate against this code but the SQS lambda (rightly) has no access to any of the storage.

LTG-386: Generate six-digit code in API Gateway handler

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

-  Retrieve email code expiry time from config and give it a default value of 15 minutes if the env var is not set
- We may want to make this config value more generic if we want to reuse the value for others codes as well. 
- So it can be dynamic

LTG-374 - Retrieve email code expiry time from config

---

integration-tests/src/test/java/uk/gov/di/authentication/helpers/SessionHelper.java
serverless/lambda/src/main/java/uk/gov/di/services/CodeStorageService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/services/CodeStorageServiceTest.java

This removes all non-Redis logic and configuration from the `RedisConnectionService`
It knew too much.
...
That is to say, logic specific to session storage and code storage belongs in their respective services, not within this one. The sole responsibility of the `RedisConnectionService` is handling API calls to Redis

BAU: Refactor `RedisConnectionService`

---

serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

Add more tests for `SessionService`
We missed adding tests during the spike-and-stabilise period

BAU: Add tests for `SessionService`

---

integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/CodeStorageService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/CodeStorageServiceTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

-  Delete email code after it has been used
- The code is a one time code so once it has been used successfully we should delete it from redis.
- If the code fails to delete we don't want to the user to fail as the code will disappear after a certain time period but we should be aware when it does fail to delete so log out a message for now.
- Add an integration test to ensure that a code can't be used again by a user
- Refactor the VerifyCodeIntegrationTest to reduce a lot of duplication
- The code is a one time code so once it has been used successfully we should delete it from redis.

LTG-374 - Delete email code after it has been used

---

ci/terraform/aws/userexists.tf
ci/terraform/localstack/localstack.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java

Change 'userexists' endpoint to user-exists.
Keep API resource path names consistent.
https://github.com/alphagov/di-authentication-frontend/pull/58

BAU: change userexists endpoint to user-exists

---

serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ValidationService.java
serverless/lambda/src/main/java/uk/gov/di/validation/EmailValidation.java
serverless/lambda/src/main/java/uk/gov/di/validation/PasswordValidation.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ValidationServiceTest.java

- Add the relevant validation errors to the ErrorResponse so validation errors will be generated the same as all other errors
- Make the validateEmail and validatePassword methods return an Optional<ErrorResponse>
- Refactor other error responses to use the generateApiGatewayProxyErrorResponse method.
- Delete the PasswordValidation and EmailValidation enums as these errors are no in ErrorResponse
- So we have a standard way of returning errors to the client

LTG-374 - Return validation errors as a standard ErrorResponse

---

serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java

- By default Jackson will represent Java Enums as String and just return the value of the enum. I.E - ERROR_1000.
- We want to ensure that the error object is returned to display the code and message so we need to add the @JsonFormat(shape = JsonFormat.Shape.OBJECT) annotation for this to happen.
- So it is returned as {"code": 1000, "message": "Session-Id is missing or invalid"} instead of just ERROR_1000

LTG-274 - Fix ErrorObject json response

---

ci/terraform/aws/login.tf
ci/terraform/aws/outputs.tf
ci/terraform/localstack/localstack.tf
ci/terraform/localstack/outputs.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java

- Write terraform for Login apigateway and lambda
- Write integration test for the Login endpoint
- Add terraform to create a api gateway using the 'login' endpoint name which will forward a request to the LoginHandler lambda function.
- Add a happy path integration test to ensure we can call the Login endpoint and get a successful response
- Rename the SignupIntegrationTest

LTG-397 - Write terraform for Login apigateway and lambda

---

ci/terraform/aws/dynamodb.tf
ci/terraform/aws/vpc.tf

- Create a new DynamoDB table resource to create a User Credentials table with the Email being the partition key.
- Make the SubjectID a global_secondary_index on user credentials to allow the application to find a user using the SubjectID.
- Create a VPC endpoint and route table entries so that we can access DynamoDB from our VPC.
- Create a new DynamoDB table resource to create a User Profile table with the Email being the partition key.
- Make the SubjectID a global_secondary_index on user profile table to allow the application to find a user using the SubjectID.
We need to store the users data so once they've registered they can come back and re-use their account.

LTG-402: Create DynamoDb Tables

---

ci/pipeline.yaml

- The Terraform now requires at least v1.0 of Terraform, we forgot to bump it in the pipeline.
The pipeline is failing to execute the Terraform
#118

LTG-354: Bump Terraform image version to 1.0

---

ci/terraform/aws/dynamodb.tf
ci/terraform/aws/localstack.tfvars
ci/terraform/aws/site.tf
ci/terraform/aws/variables.tf
docker-compose.yml
pre-commit.sh
scripts/functions.sh

- Add the AWS provided DynamoDB image to Docker Compose
- Enable DynamoDB Terraform when using Localstack pointing it at the local DynamoDB endpoint.
We need to be able to test DynamoDB functionality locally
#120 
#117

LTG-403: Add DynamoDB to Docker Compose

---

ci/terraform/aws/userexists.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthenticationService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java
serverless/lambda/src/main/java/uk/gov/di/services/UserService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

- Check if user exists before calling signup
- Change the return type of SignUp to void
- Hook up the UserExist lambda to Dynamo
- So we can use Dynamo to check if a user exist rather than checking in memory
- Before signing up a user we should double check to make sure that user doesn't exist. Although this should not happen it will prevent any edge cases of trying to sign up a user who already has an account.
- We don't return anything from the SignUp method so it can just be void.

LTG-403 - Hook up UserExist lambda to DynamoDB

---

ci/terraform/aws/login.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LoginHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java

- Switch the Login lambda to use the DynamoService rather than the in memory UserService.
- Check if a user has an account before attempting to login 
- Because we need to use a database than rely on in-memory storage 
-  So we can send back a more accurate error message

LTG-403 - Hook up Login lambda with DynamoDB

---

pre-commit.sh

The login was incorrect, we only want to stop the `funky_success` banner not the exit code check.
We need to stop mis-reporting the errors.

BAU: Stop Github Actions from passing when integration tests fail

---

ci/terraform/aws/sqs.tf
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendEmailNotificationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/NotificationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/NotificationHandlerTest.java

- Check for the VERIFY_PHONE_NUMBER notificationType in the notification Lambda and use Notify to send a text message using the number supplied in the destination.
- Add a new template ID to the sqs.tf which will be used to send to notify so it can use the template we have created for text messages.
- So we can use Notify to send text messages so a user can confirm there phone number

LTG-386 - Modify the Notification Lambda to send texts

---

serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ValidationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ValidationServiceTest.java

- We must check that any phone number is a valid British number before we send it over to Notify.
- We can use the https://github.com/google/libphonenumber lib to do some checking but before we use it, explicitly check that there is at least 10 characters that consist of all numbers.
- Notify strip any whitespace when validating the number.
- When a phone number is invalid we will send the appropriate Error response back.
- To ensure that anything we put on the SQS queue is a valid number. This will ensure we only ever send valid numbers to Notify.

LTG-409 - Validate phone number

---

serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java

- Call .save when updating Dynamo
- We are only setting it in memory rather than updating Dynamo. To update Dynamo we need to call save

BAU - Call .save when updating Dynamo

---

ci/terraform/aws/api-gateway.tf
ci/terraform/modules/endpoint-module/outputs.tf

- Add in missing dependency on `verify_code` module
- Add a redeploy trigger to the deployment that SHA's all the IDs of the resources.
If a new lambda endpoint is added it doesn't automatically get added to the deployment. We need to redeploy the API gateway deployment when new endpoints are added.

BAU: Add a redeployment trigger for the API gateway deployment

---

ci/terraform/aws/sqs.tf
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendNotificationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/NotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java

- Modify NotificationHandler to send MFA SMS messages
- We have a new NotificationType for handling MFA SMS so modify the NotificationHandler to send an SMS via Notify when a message with that NotificationType is pulled of the que.

GOVSI-468 - Modify NotificationHandler to send MFA SMS messages

---

ci/terraform/aws/dynamodb.tf
ci/terraform/aws/lambda-roles.tf
ci/terraform/aws/mfa.tf
ci/terraform/aws/sqs.tf

- Create a new IAM role which has permissions for Dynamo and SQS and assign it to the MFA lambda.
- The MFA lambda needs permissions to talk to Dynamo and SQS. We currently don't have an IAM role that does it and want to keep the existing IAM roles limited to the permissions that they require.

BAU - Create a new IAM role that has permissions to Dynamo and SQS

---

ci/terraform/aws/dynamodb.tf

- The aws_iam_role_policy_attachment for lambda_sqs_dynamo role should be name instead of arn

BAU - Fix terraform error

---

integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/MfaHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Session should now include an active clientSessionId field
- Authentication requests should be stored as map using clientSessionId as the key
We need to re-structure the session object in order to support SSO (logging into additional services without needing to re-authenticate)

GOVSI-493: Re-factor Session class

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/authorize.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/login.tf
ci/terraform/aws/outputs.tf
ci/terraform/aws/register.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/userexists.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/verify_code.tf
ci/terraform/aws/wellknown.tf
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/TokenServiceTest.java

- Add PrivateKeyAuthentication to the token endpoint and use Nimbus libraries to Verify that the PrivateKeyJWT contains the required attributes.
- Construct the Base URL in terraform
- Return ErrorResponses from Token endpoint
- Retrieve the Public Key from Dynamo to then Verify the signature of the Private Key JWT
- Private Key JWT Client authentication is used by clients to authenticate to the authorization server when using the token endpoint
- We need the application to read the BaseURL so it can validate the audience

GOVSI-445 - Add PrivateKey JWT auth on the token endpoint

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ConfigurationServiceTest.java

Add additional session cookie attributes.
Attributes required for increased security.
The attributes must be configurable because they will not work in the current dev and test environments where the application is split across different domains.

GOVSI-494: add additional session cookie attributes

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IntegrationTestEndpoints.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RequestHelper.java

Create a helper for making API requests with a sessionID.
Removes duplication across the integration tests
One-off requests or requests with no session have not been changed.

BAU: Refactor out `RequestHelper` in integration tests

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
pre-commit.sh
serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

Read session cookie for existing sessions.
The session cookie is first set by /authorize when an a user is not logged-in.  If they subsequently try to login (again) to another service then:
- Read the existing session cookie.
- Generate a new session id.
- Update the existing session with the new id in Redis.
- Delete the old session key from Redis.
- Redirect back to the application with the new session cookie.
Added integration and unit tests.
Changes will be made to the redirect when the complete login flow is available in the application.
Support SSO to multiple services.
#175 
#177

GOVSI-494: read session cookie for existing sessions

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistry.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java

Add post redirect uris to client register endpoint.
To allow the service to support custom logout redirect uris for a client.

Add (optional) logout registration URIs to client registration endpoint

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/logout.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/helpers/IDTokenGenerator.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Create a bare bones Logout Lambda
- Add terraform to create Logout Lambda
- Create a IdTokenGenerator to create an ID token for us as we require it in several places and this will reduce duplication
- Add a default LOGOUT URI
- This Lambda will be a GET and be used to clear a users session when it is called by an RP.

GOVSI-523 - Create bones for the Logout lambda

---

serverless/lambda/src/main/java/uk/gov/di/helpers/RequestBodyHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/test/java/uk/gov/di/helpers/RequestBodyHelperTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

Use an (already included) Apache library to parse request bodies into key-value pairs
It's more robust and handles things like URL encoding

BAU: Parse request bodies with library

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/WellknownHandlerTest.java

Fix well known endpoint urls
/ were missing from the url when using an OIDC client it failed.

Fix well known endpoint urls

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/entity/ClientSession.java
serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/MfaHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Store clientSessionID against the ClientSession in the users session rather than against just the authnRequests 
- Remove the top level ClientSessionID from the Session
- Generate a new ClientSessionID in the AuthorizationHandler
- Add the jackson-datatype-jsr310 dependency 
-  We need to store more than just the authentication request against the clientSessionID. Create a ClientSessionObject which will contain the authrequestparams, creationdate and ID Token hint. This will be searlized and stored in the users session against the clientSessionID which represents the RP which the auth request came from. The Id token hint will only be added in the TokenHandler once the ID token has been created. 
- We never need the ClientSessionID at the top level of the Session so lets remove it and …

GOVSI-598 - Refactor Client Session Storage

---

build.gradle
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/resources/log4j2.xml
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java

- Add the SL4J2 runtime dependency
- Add the AWS Lambda SL4J2 library
- Add configuration to include lambda request ID in log entries
- Replace all uses of the lambda logger with SL4J instances.
The lambda logger has limited functionality, lets use SL4J2 instead

BAU: Use SL4J2 instead of the default lambda logger

---

ci/pipeline.yaml

- Rename the environment that is deployed in the pipeline from `test` to `build`
In PaaS we have a `build` space, but in AWS we currently deploy a `test` environment, lets make them match.

BAU: Bring environment names in line

---

ci/terraform/aws/logout.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/src/main/java/uk/gov/di/helpers/CookieHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/helpers/CookieHelperTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Extract the session from the session cookie when it exists. If it doesn't then we just redirect the user to the default logout URI which is `https://di-authentication-frontend.london.cloudapps.digital/signed-out`
- Move the logic of the cookie parsing into its own helper 
- Validate the ID token in the request. 
- Put a placeholder in for validating the signature of the ID token. We can revisit this when we're not signing the ID token with a key generated on the fly. 
- Validate the client logout_uri
- Send the state back in the response when it is included in the request
- This PR implements the logic from the RP initiated logout OIDC spec - https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
- This creates an endpoint which can be called by a user whilst they are on …

GOVSI-523 - Add validation and logic to logout endpoint

---

serverless/lambda/src/main/java/uk/gov/di/helpers/CookieHelper.java
serverless/lambda/src/test/java/uk/gov/di/helpers/CookieHelperTest.java

Handle multiple cookies in a cookie header.
Update the cookie helper to retrieve the gs cookie first before passing it to HttpCookie.
The java HttpCookie.parse method only reads the first cookie in a cookie header and discards any others.

GOVSI-495: handle multiple cookies in a cookie header

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/authorize.tf
ci/terraform/aws/variables.tf

- Add API gateway stage to custom domain name mapping
- Replace hard-coded redirect URL with calculated based on environment
- Allow the passing in of the service domain name using variable
To allow sharing of cookies between front and back end endpoints.
https://github.com/alphagov/di-authentication-frontend/pull/133

GOVSI-606: Use custom domain for API gateway

---

ci/terraform/aws/dynamodb.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java

- We store the scopes in the access token. When we retrieve the accesstoken in the userinfo endpoint, check to see what scopes exist and send back the userinfo based on what is returned.
- Change the projection_type of the GSI on the user_profile table to ALL instead of INCLUDE. This means that we can use Subject to return all information relevant to that row whereas previously it was only returning EMAIL.
- So we only send back user information which the client has requested and is authorized to receive

GOVSI-635 - Validate scopes before returning UserInfo

---

integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/Session.java
serverless/lambda/src/main/java/uk/gov/di/helpers/ObjectMapperFactory.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientSessionService.java
serverless/lambda/src/main/java/uk/gov/di/services/SessionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Store client session details in separate Redis index rather than within session
When issuing tokens, we have no way of identifying the user session in order to store the issued ID token. We do, however, have access to the client session id as this is stored against the authorisation code.

GOVSI-609: Refactor client session

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IntegrationTestEndpoints.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
pre-commit.sh

- Ensure `pre-commit.sh` exits with the correct code so that GitHub actions reports the failures correctly.
- Update `LOGIN_URL` in `pre-commit.sh` is correct.
- Stop the Jersey client from following re-directs when 
- When running integration tests ensure that data in Dynamo and Redis is flushed by adding a `@BeforeEach` to the base class (note this will always be executed before any `@BeforeEach` methods in the sub-class ... according to the JUnit docs)
- Setup VerifyCode data correctly before running test (we weren't stubbing this data, so depending on the order tests are run in, we were getting failures).
We were getting random failures of several integration tests, which were not being reported correctly. This PR fixes the issue with reporting the errors and, hopefully, will stop the …

BAU: Fix integration test random fails

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IntegrationTestEndpoints.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
pre-commit.sh
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorisationCodeService.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientSessionService.java
serverless/lambda/src/main/java/uk/gov/di/services/RedisConnectionService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java

- When issuing tokens from the `token` endpoint, ensure the issued ID token is stored against the client session
- Refactor code generation and storage into own class
We need to store the ID tokens as they will be used as hints during by `logout` endpoint.

GOVSI-522: Store ID token against client sessions

---

.github/dependabot.yml

Add docker checks to dependabot
These checks are not enabled.
Localstack version has fallen behind.

BAU: add docker checks to dependabot

---

ci/terraform/aws/authorize.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

- Now that we have a domain we can use for the time-being, let's set it in the Cookie so it can be used by our frontend which is also on the same sub domain.
- Don't send the scopes or session-id separately in the redirect. The session-id is in the Cookie and the scopes are not used.
- Now that we have a domain we can use for the time-being, let's set it in the Cookie so it can be used by our frontend which is also on the same sub domain.

GOVSI-647 - Set Domain in Cookie

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

Support 'prompt' parameter.
https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest
Add test scenarios for prompt = none, login, consent and select_account
Update AuthorisationHandler to support the prompt parameters
We do not currently support consent and select_account so return an error if these parameters are supplied.
Need to support 'prompt' as part of SSO, so that users can login to a second service without being prompted for their credentials a second time.

GOVSI-495: Support 'prompt' parameter

---

serverless/lambda/src/test/java/uk/gov/di/matchers/APIGatewayProxyResponseEventMatcher.java

This matcher was previously using the description of the expected value in the output, regardless of whether the match was successful or not.

BAU: Return correct description when matcher does not match

---

ci/terraform/aws/token.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientSession.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/SessionServiceTest.java

- Store the email in the client session id so once we have the client session id we can get the correct Subject to add to the token
- Get the authRequest out of the ClientSession and extract the scopes so they can be added to the token
- Add Redis config to the Token.tf so it can access Redis
- Because the email was being previously hardcoded 
- We were ignoring the scopes in the Auth Request and using the ones in the client registry. The ones in the client registry should be used to validate the scopes in the Auth Request against.

GOVSI-650 - Read the scopes from the auth request in token endpoint

---

ci/terraform/aws/dynamodb.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistry.java
serverless/lambda/src/main/java/uk/gov/di/entity/UserCredentials.java

- Fix secondary keys for Dynamo and don't follow redirect on integration test
- I discovered that the way the secondary index was previously configured didn't work. This was discovered on the UserProfile. Make the same changes to the UserCredentials and ClientRegistry table as we did there
-

BAU - Fix secondary keys for Dynamo and don't follow redirect on integration test

---

pre-commit.sh
scripts/functions.sh

Ability to run startup.sh locally without tests or the rest of pre-commit.
Able to start the apps and apply terraform without running any tests and then stopping the apps.  This means you can run and test integration tests in the IDE against the running api.

BAU: run startup locally without running tests

---

ci/terraform/aws/api-gateway.tf

Use api domain name in api gateway
The api is configured to use the unique api id rather than the generic domain name.
well-known is returning a url with the unique api id rather than the generic name, causing stub rp to fail when authorising.

BAU: use api domain name in api gateway

---

serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/helpers/CookieHelper.java
serverless/lambda/src/test/java/uk/gov/di/helpers/CookieHelperTest.java

This enables `CookieHelper` to parse out cookies from either `Cookie` or `cookie` headers.
AWS API Gateway sends lower-case headers which was breaking some flows.

GOVSI-651: Support multi-case cookie headers

---

ci/terraform/aws/api-gateway.tf

- Add correct perms to API gateway logging role
The permissions we added we were not pervasive enough for API gateway.
#234

BAU: Add correct perms to API gateway logging role

---

serverless/lambda/build.gradle

Add Log4J dependencies to enable correct logging in lambdas
To enable logging in the lambdas

BAU: Add Lambda Logging in build.gradle

---

ci/terraform/aws/dynamodb.tf

- Add permission to global secondary index
The `userinfo` endpoint is failing with a permission denied error.

BAU: Add permission to global secondary index

---

integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/test/java/uk/gov/di/helpers/StateMachineTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java

This PR adds a state-machine capability and implements transition protection on one of the user account registration endpoints.
We want to ensure that users, whether accidentally or deliberately, cannot jump between parts of the journey and circumvent (or skip entirely) steps.
- Is `SessionState` the right representation of the state of a user, or will it be more closely aligned with what we eventually send to the audit processing service?
- Do we need to provide another endpoint that can rely the current user state to the frontend?
- Is throwing a general error ("Invalid transition in user journey") sufficient or should it be tailored to the endpoint and previous state?

GOVSI-500: Protect user journey transitions with state machine

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/lambda-roles.tf
ci/terraform/aws/sqs.tf
ci/terraform/aws/variables.tf

- Use `aws_iam_policy_document` data sources instead of heredoc style JSON blobs
- Make API gateway logging optional
The use of data sources is tidier than heredocs.
API gateway logging, is a useful debugging tool but probably not wanted in all environments.

BAU: Tidy up Terraform

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/AuthCodeExchangeData.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientSession.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorisationCodeService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java

Rather than store e-mail address alongside client session data for the duration, store with auth code as it is only needed until the auth code is exchanged for an access token.
The e-mail address is needed in a client session context after the token has been issued, and is stored against the session anyway, so the duplication is unwanted.

GOVSI-653: Refactor e-mail address storage

---

ci/terraform/aws/dynamodb.tf

- Use pay per request for dynamodb rather than provisioned units
We're getting Dynamo errors, we'll use the pay per request model for now, we may need to size this appropriately for a production system.

BAU: Use pay per request rather than provisioned units

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ConfigurationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java

If a user is logged in, and no specific `prompt` functionality has been requested, skip the UI and issue auth-code straight away.
This is required to have proper SSO functionality.

GOVSI-498: Allow skipping of login to enable SSO

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java

Implement state transition protection for `CheckUserExistsHandler` and `VerifyCodeHandler` (email code only)
This prevents the application jumping around the process out-of-order.

GOVSI-670: Implement state transition checks (1)

---

serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LoginHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/MfaHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SignUpHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/VerifyCodeRequestHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/matchers/APIGatewayProxyResponseEventMatcher.java

Create and use a matcher that takes an object and compares the `APIGatewayProxyRequestEvent.getBody()` to the serialisation of that object.
Remove duplication and tidy up assertions

BAU: Create and use `hasJsonBody` matcher in tests

---

serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/CheckUserExistsHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SendNotificationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/SignUpHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/VerifyCodeHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/SendNotificationHandlerTest.java

This PR slightly alters how control flow works with state validation, opting for throwing exceptions rather than if-else.
The motivation for this is that it cleans up the code at the callsite by removing the need for an if-statement at each check.
This PR also includes transition protection for `SendNotificationHandler`

GOVSI-670: Implement transition checking (2)

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java

Add logout url to well known endpoint.
This provides the necessary information to service teams integrating.

Add logout endpoint to wellknown endpoint

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java

Read update-profile client session id from headers rather than the cookie.
Add additional logging to the handler.
client-session-id not being found by the handler as the cookie is not passed to the endpoint by the client.
#261

GOVSI-281: read update-profile client session id from headers rather than the cookie

---

ci/terraform/aws/api-gateway.tf
ci/terraform/aws/auth-code.tf
ci/terraform/aws/authorize.tf
ci/terraform/aws/client-info.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/login.tf
ci/terraform/aws/logout.tf
ci/terraform/aws/mfa.tf
ci/terraform/aws/register.tf
ci/terraform/aws/send_notification.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/update.tf
ci/terraform/aws/update_profile.tf
ci/terraform/aws/userexists.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/verify_code.tf
ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/UpdateClientConfigRequest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java

- Create an endpoint which can be called via /oidc/clients/{client_id} where client_id is a path parameter. They can update any number of parameters at any one time as long as they pass in a valid client_id. We will then return the entire updated client config in the response
- Change the lambda terraform to add a path_part variable.
- Add integration and unit tests
- Clients will need to update their config. 
- The endpoint_name in each of the lambdas terraform was used for the aws_function_name and the path_part for the aws_api_gateway_resource. As we want the final path part of this lambda to be a path parameter we don't want to reuse the endpoint name for the aws_api_gateway_resource. Create a new path_part variable and configure it in each lambda.

GOVSI-277 - Create update client config endpoint

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java

Update existing consent flag when one already exists.
Handler was adding an additional consent flag to the list rather than updating the existing one.
#281

GOVSI-281: update existing consent flag when one already exists

---

ci/terraform/aws/update.tf
ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/variables.tf

- Set method_request_parameters and integration_request_parameters in the module variables.tf and assign the value in the update.tf.
- To fix the broken build

GOVSI-277 - Add the client_id to the aws_api_gateway_integration resource request parameters

---

serverless/lambda/src/main/java/uk/gov/di/entity/UpdateClientConfigRequest.java

- Don't initialize an empty list for the PostLogoutUri when updating Client config
- Because it will delete the PostLogoutUri and replace it with an empty list

GOVSI-277 - Don't initialize an empty list for the PostLogoutUri when updating Client config

---

integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientRegistrationResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/ErrorResponse.java
serverless/lambda/src/main/java/uk/gov/di/entity/UpdateClientConfigRequest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ValidScopes.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientRegistrationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientConfigValidationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientRegistrationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/ClientConfigValidationServiceTest.java

- Validate Client config in Registration and Update requests
- When a validation error occurs then generate an OIDC constructed error and send that back to the client 
- Hardcode the response_type as code in the Registration response
- Remove wildcard imports
- So we can be confident that any public key, scopes or uris that the client registers with are valid. This prevents us finding out there are issues later down the line so we can fail fast

GOVSI-277 - Validate Client config in Registration and Update requests

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/ClientInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateClientConfigHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorizationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateClientConfigHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/AuthorizationServiceTest.java

- Add OIDC errors to the update client config endpoint
- There are inconsistencies with our usage of AuthorizationRequest and AuthenticationRequest. We should explicitly be using AuthenticationRequest as that ensures we are compliant with the OIDC spec as scopes and redirect_uri are not optional. 
- To be compliant with the OIDC spec

GOVSI-463 - Add OIDC errors to the update client config endpoint

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/entity/ResponseHeaders.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthCodeHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/LogoutHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorizationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java

-  Use OIDC errors in the Auth Code handler
- Create a ResponseHeaders interface
- The auth code lambda should redirect an OIDC error via a 302 redirect to the user when there is an issue with either the auth request or the client id. In theory this should never really happen as it would have been validated on the AuthorizationHandler but it gives us more protection
- So there is a single point of truth for ResponseHeaders to be declared and used

GOVSI-463 - Use OIDC errors in the Auth Code handler

---

ci/terraform/aws/lambda-roles.tf
ci/terraform/modules/endpoint-module/lambda.tf

- Enable Xray for the logging
- So we can see how the Lambdas are performing

BAU - Enable Xray for the logging

---

ci/terraform/aws/auth-code.tf
ci/terraform/aws/authorize.tf
ci/terraform/aws/client-info.tf
ci/terraform/aws/jwks.tf
ci/terraform/aws/login.tf
ci/terraform/aws/logout.tf
ci/terraform/aws/mfa.tf
ci/terraform/aws/register.tf
ci/terraform/aws/send_notification.tf
ci/terraform/aws/signup.tf
ci/terraform/aws/token.tf
ci/terraform/aws/update.tf
ci/terraform/aws/update_profile.tf
ci/terraform/aws/userexists.tf
ci/terraform/aws/userinfo.tf
ci/terraform/aws/variables.tf
ci/terraform/aws/verify_code.tf
ci/terraform/aws/wellknown.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

This PR attaches an optional log group subscription to each lambda, the default is for it to be off.
This is part of a set of PRs aimed at creating a one-stop-shop for Authentication logs in an external component.

GOVSI-614: Set up log shipping for API lambdas

---

ci/terraform/aws/outputs.tf
ci/terraform/aws/stub-rp-clients.tf
ci/terraform/aws/variables.tf

Use Terraform to optionally seed client data into the client registry for the stub RP(s).
By setting the new `stub_rp_clients` variable to something like:
```
stub_rp_clients = [
{
client_name = "di-auth-stub-relying-party-build"
callback_urls = [
"http://localhost:8081/oidc/authorization-code/callback",
"https://di-auth-stub-relying-party-build.london.cloudapps.digital/oidc/authorization-code/callback",
]
logout_urls = []
}
]
```
we can generate the key pairs and provision the client into the client registry.
To avoid having to manage secrets in SSM or hard-code client IDs in the pipeline.

GOVSI-679: Generate stub client details in Terraform

---

ci/terraform/aws/build-stub-clients.tfvars
ci/terraform/aws/integration-stub-clients.tfvars

Add terraform variable files, containing stub client data, for individual environments.
These files were missed from previous PR.
#292

GOVSI-679: Add client data.

---

ci/terraform/aws/jwks.tf
ci/terraform/aws/kms.tf
ci/terraform/aws/site.tf
ci/terraform/aws/token.tf
ci/terraform/aws/variables.tf
docker-compose.yml
integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/TokenGeneratorHelper.java
serverless/lambda/build.gradle
serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/JwksHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UserInfoHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenGeneratorService.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/helpers/TokenGeneratorHelper.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/LogoutHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UserInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/TokenServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Add terraform to generate KMS signing key for ID tokens
-  Sign ID tokens and access tokens using KMS
- Retrieve Public Key from KMS
- We were previously using a signing key generated on the fly. Switch to using a signing key provided by KMS.
- So clients can verify the signing of the ID tokens using the JWKS lambda 
- Split out the permissions of signing and getting the public key into separate roles so that only the Lambdas who need to sign have permission to do so 
- Add some unit tests for the new service

GOVSI-623 - Use KMS to sign ID tokens 

---

ci/terraform/aws/token.tf
serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java

- Fix BaseURL for Token endpoint
- The issuer of the ID token should just be the baseurl without the token path however the audience of the privatekeyjwt should be the baseurl with the token path

GOVSI-623 - Fix BaseURL for Token endpoint

---

ci/terraform/aws/sqs.tf
ci/terraform/modules/endpoint-module/lambda.tf

- Ensure we publish lamdba functions to create new versions
We cannot provision concurrency on un-versioned lambdas
#297

GOVSI-622: Publish Lambda versions

---

ci/terraform/aws/dynamodb.tf
ci/terraform/aws/kms.tf
ci/terraform/aws/lambda-roles.tf
ci/terraform/aws/token.tf

- Ensure that the token lambda is the only lambda which has permissions to sign.
- Give all other lambda permissions to retrieve the public key.
-  Currently the token lambda is the only lambda which needs to sign so we should ensure are permissions cater for this.
- The public key is not a secret

GOVSI-623 - Restrict signing permissions to the Token Lambda

---

ci/terraform/aws/kms.tf

-  Attach the correct policy to the Token IAM role
- So it can sign

GOVSI-623 - Attach the correct policy to the Token IAM role

---

serverless/lambda/src/main/java/uk/gov/di/services/TokenGeneratorService.java

-  Build the EC key with the keyId, ususage and alg
- Otherwise clients will be unable to verify the key

GOVSI-623 - Build the EC key with the keyId, ususage and alg

---

ci/terraform/aws/outputs.tf

- Mark the `account_management_client_details` Terraform output as `sensitive` to stop it's values being output in the pipeline
This contains sensitive data that is getting output in the pipeline, which is not good. All affected resources are being tainted to generate new values.

GOVSI-680: Make `account_management_client_details` sensitive

---

serverless/lambda/src/main/java/uk/gov/di/domain/OidcAuditableEvent.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
shared/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/domain/AuditableEvent.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java

Create basic auditing component and use it to audit the receipt of authorisation requests.
Proof of concept for an approach to publishing audit events.

GOVSI-712: Create basic auditing component

---

serverless/lambda/src/main/java/uk/gov/di/lambdas/TokenHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/TokenService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/TokenServiceTest.java

- Add Nonce to ID token when it is included in Auth Request
- To be compliant with 3.1.3.7 of the openid connect spec

GOVSI-623 - Add Nonce to ID token when it is included in Auth Request

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorizationService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthCodeHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/ClientInfoHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/TokenHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java
serverless/lambda/src/test/java/uk/gov/di/services/AuthorizationServiceTest.java

- Make State and Nonce mandatory in the Auth Request
- State will help protect us from cross site request forgery attacks. This allows a client to validate that the auth response has not been altered to the one sent in the original auth request.
- Nonce will help mitigate replay attacks by linking a client session and ID token together.

GOVSI-720 - Make State and Nonce mandatory in the Auth Request

---

serverless/lambda/src/main/java/uk/gov/di/domain/OidcAuditableEvent.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/AuthorisationHandler.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

This adds the option to add arbitrary key-value pairs to audit events. At the moment, this is consumed into a logline, but it will eventually be transformed into messages for our as-yet-to-be-decided audit transport mechanism.
Audit events need to have metadata attached which is best decided at the call-site.
This is currently only implemented for one case, error handling for `AuthorisationHandler` but can be rolled out more widely at the discretion of the team.
#312

GOVSI-712: Add capability to add context data to audit events

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
serverless/lambda/src/main/java/uk/gov/di/entity/ClientConsent.java
serverless/lambda/src/main/java/uk/gov/di/entity/UserProfile.java
serverless/lambda/src/main/java/uk/gov/di/entity/ValidScopes.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/UpdateProfileHandler.java
serverless/lambda/src/main/java/uk/gov/di/lambdas/WellknownHandler.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthenticationService.java
serverless/lambda/src/main/java/uk/gov/di/services/AuthorizationService.java
serverless/lambda/src/main/java/uk/gov/di/services/ClientConfigValidationService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/UpdateProfileHandlerTest.java

- Update how we store Consent in the UserProfile table. This will now be stores as a List of the ClientConsent DynamoDocument object. This is because there will be different consent for a user on different services.
- Have a single source of truth for how we specify the Scopes we support
- Add an integration test to ensure that the consent is updated correctly

GOVSI-728 - Update Consent model

---

serverless/lambda/src/main/java/uk/gov/di/helpers/StateMachine.java
serverless/lambda/src/test/java/uk/gov/di/lambdas/CheckUserExistsHandlerTest.java

Modify state machine to allow multiple calls to userExists in a single session.
Now able to transition from USER_NOT_FOUND to USER_NOT_FOUND again.
User journey is changing to allow a single user to check whether accounts exist for multiple emails.  Before it was only possible to check a single email within a single session.

GOVSI-458: modify state machine to allow multiple calls to userExists in a single session

---

ci/terraform/aws/stub-rp-clients.tf

- Provision stub RP clients with `ServiceType` of `MANDATORY`
The auto-provisioning of clients currently doesn't include this field so may break the stub journeys.

BAU: Provision Stub Clients with a ServiceType

---

serverless/lambda/src/main/java/uk/gov/di/services/DynamoClientService.java
serverless/lambda/src/main/java/uk/gov/di/services/DynamoService.java

- By using a connection in the constructor it should speed it up when we come to use it from the Lambdas.
- To speed up our Lambdas

BAU - Make a table query in the Dynamo constructor

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-oidc-api.yml

- The inputs on the deploy tasks will now include the extracted source code, so need to extract from the release
The pipeline needs to extract the release source in order to execute the task, so lets just pass the source in.

GOVSI-716: Correct inputs on deploy task

---

ci/tasks/deploy-acct-mgmt-api.yml

- The `deploy-acct-mgmt-api.yml` task is missing the 'e' in the ZIP file path name passed to `terraform apply`
The pipeline is erroring
#357

GOVSI-716: Fix typo in the name of the lamdba passed to Terraform

---

ci/terraform/account-management/lambda-roles.tf

- The account management API will be interacting directly with the user-profile and user-credentials tables, lets grant that access by default.
- Only grant permissions to get and update items by hash key (e-mail address) as the account management API shouldn't need to do anything else.
The lambda will need Dynamo access.
#357

GOVSI-617: Add DynamoDB permissions to Acct Mgmt lambda role

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/dynamodb.tf
ci/terraform/oidc/ecr.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/kms.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/redis.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/site.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/oidc/vpc.tf
ci/terraform/oidc/wellknown.tf

- Lifecycle trigger for API gateway deployment wasn't always guaranteed to trigger a new deployment. Ensure the trigger includes all elements of the deployment.
- Ensure all AWS resources that can be tagged are tagged with, at least, both an environment and application name. 
We have multiple Terraform stacks deploying to our environments, it is probably a good practice to add some tags to the resources so we know which part of the application they belong to.
#357

GOVSI-716: Tag OIDC resources and better API deployment trigger

---

ci/terraform/oidc/audit-sns.tf
ci/terraform/oidc/site.tf
docker-compose.yml

Create SNS topic for audit.
Access policy (for the moment): account owner can send, anyone can receive
Precursor to writing code to distribute audit events.

GOVSI-735: Create SNS topic for audit

---

ci/terraform/modules/endpoint-module/api-gateway.tf

- Specify Alias as a qualifier to lambda permission
- So that the API gateway has the correct permissions

BAU - Specify Alias as a qualifier to lambda permission

---

ci/terraform/oidc/dynamodb.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/RedisConnectionService.java

- Create warmup methods for all connections
- When one of the services that establishes a connection is called, call a warmup method which will initalize a connection. This is so that when the lamdas are called we can maintain a quicker connection to any of the AWS services that we use

GOVSI-622 - Create warmup methods for all connections

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/oidc/kms.tf

- We call the ListKeys method when we warmup the lambda
- Bring the memory down to 4gb

GOVSI-622 - Give lambdas permission to ListKeys in KMS

---

ci/terraform/oidc/kms.tf
integration-tests/src/test/java/uk/gov/di/authentication/helpers/KmsHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java

- Retrieve public key when initalizing KmsConnectingService
- So the lambdas can obtain a quicker connection to KMS

GOVSI-622 - Retrieve public key when initalizing KmsConnectingService

---

ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf

- Remove provisioned concurrency
- As it is very expensive

GOVSI-622 - Remove provisioned concurrency

---

ci/terraform/account-management/api-gateway.tf

Reset account management api stage name to match environment.
Updated to bring into line with the rest of the terraform, however seems to break the build.

GOVSI-185: reset account management api stage name to match environment

---

ci/terraform/modules/dashboards/cloudwatch_dashboard.tf

Improvements to time-scale and averaging window in CloudWatch Dashboards for the Lambda-based API
Finer-grained information over a longer window of time

GOVSI-742: Tweak CloudWatch dashboards

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateInfoHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateInfoHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateInfoIntegrationTest.java
ci/terraform/account-management/update-info.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Pull out the principalId from the authorizer to check that it matches the SubjectID. The principalId is set by the AWS authorizer.
- Give the updateInfo lambda access to dynamoDB
- So the lambda can update DynamoDB with the new email address

GOVSI-628 - Adapt UpdateInfo lambda to update email

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Set Subject claim in AccessToken
- It is required by the authorizer so it can set the principalId

GOVSI-628 - Set Subject claim in AccessToken

---

shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Delete the original entry once email has been updated
- The current logic did not update the existing row but created a new row with a different hash key leaving the entry there with the old email. Turns out a hashkey can't be updated so we need to explicitly delete it. https://stackoverflow.com/questions/37854710/is-it-possible-to-update-a-hash-key-in-amazon-dynamo-db

GOVSI-628 - Delete the original entry once email has been updated

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/StateMachine.java

- Add transition from AUTHENTICATION_REQUIRED to USER_NOT_FOUND
- This is so when the UserExists lambda is called and the user is not found then the correct state can be set

GOVSI-628 - Add transition from AUTHENTICATION_REQUIRED to USER_NOT_FOUND

---

ci/terraform/oidc/dynamodb.tf

- Give permissions to delete item in DynamoDB
- So we can delete items

GOVSI-628 - Give permissions to delete item in DynamoDB

---

ci/terraform/account-management/lambda-roles.tf
ci/terraform/oidc/dynamodb.tf

- Give account management lambda role permissions to delete item in dynamo

GOVSI-628 - Give account management lambda role permissions to delete item in dynamo

---

ci/tasks/deploy-acct-mgmt-api.yml

- Configure NOTIFY_API_KEY with account management
- It is needed to use Notify

GOVSI-628 - Configure NOTIFY_API_KEY with account management

---

ci/terraform/account-management/redis.tf

- Rename Redis session store as it clashes with the OIDC session store
- To fix pipeline

GOVSI-628 - Rename Redis session store as it clashes with the OIDC session store

---

ci/terraform/account-management/redis.tf

- Reduce size of aws_elasticache_replication_group ID.
- Integration job is currently failing because Error: expected length of replication_group_id to be in the range (1 - 40). Reduce the size of the ID

BAU - Reduce size of aws_elasticache_replication_group ID

---

ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/modules/endpoint-module/warmer.tf

- Add an, optional, CloudWatch trigger for each endpoint that triggers a warmer lambda every 5 mins
We want keep some, if not all, lambdas "warm". This trigger will be used to trigger an execution of a warmer function.

GOVSI-774: Add Cloudwatch triggers for lambda warmers

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/services/CodeStorageService.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/services/CodeStorageServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Validate the emails are in the correct format and are different from one another. 
- If the OTP code is valid then delete it and return true
- If the OTP code is not valid then return an error response
- Although some email validation will be carried out on the frontend it gives us extra protection 
- By validating the OTP code we can be confident that emails are only updated for the intended party

GOVSI-628 - Validate email addresses and OTP code

---

ci/terraform/modules/endpoint-module/warmer.tf

Fix `count` variable on warmer log group
This should depend on the `warmer_handler_function_name` variable rather than `use_localstack`, as such the deployment is failing.
#448

GOVSI-774: Fix `count` variable on warmer log group

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java

* Add error logging where not already present.
* None needed on JwksHandler; the TokenService already logs errors effectively.
* On advice of Alex, added some TODOs relating to unhandled exceptions - not in scope for this task but we will need to work out a strategy for dealing with these.
* Only class left to deal with is UserInfoHandler; will tackle that next week, but raising a draft PR for the time being.
Will make it easier for us to diagnose issues when the service is live.

GOVSI-767: Add error logging where not already present.

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/services/NotificationService.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
ci/terraform/account-management/sqs.tf

- Change the notification handler to pick the PHONE_NUMBER_UPDATED from the SQS queue and send an email confirming that the phone number has successfully been changed.
- We need to send an email to the registered email address that the phone number has been changed

GOVSI-149 - Send change phone number email confirmation

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java

- Check if email already exists when updating email address
- So we can send back a useful error response in the case that an account does exist

GOVSI-628 - Check if email already exists when updating email address

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java

Update well known to support only pairwise
To reflect what has actually been implemented and is supported.

Update subject pairwise for well known

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java

- Add extra logging and remove userexists check
- We can do a userexists check in the authorizer so we don't need to duplicate this in each lambda.
- Add extra logging so it is easier to debug

BAU - Add extra logging and remove userexists check

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/lambda-roles.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/outputs.tf
ci/terraform/oidc/token.tf
integration-tests/src/test/java/uk/gov/di/authentication/helpers/KmsHelper.java
scripts/functions.sh
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/KmsConnectionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Retrieve the key using the alias
- Reference the KMS key dataqsource in account management
- By using the alias instead of the key_id, it ensures that we always retrieve the latest key. This will benefit us during key rotations as we can avoid having to restart our lambdas.
- We will need the public key in the authorizer so we can validate the signature of the access token

GOVSI-719 - Use Alias ID to retrieve key and configure account management with KMS

---

ci/terraform/account-management/sandpit.tfvars

Add sandpit vars for sandpit users.
So that the right things are applied for remote and local terraform usage.

BAU: add sandpit vars for sandpit users

---

ci/terraform/account-management/lambda-roles.tf

- Add query permission to Account mgmt IAM role
- The authorizer needs to be able to use query when using the SubjectID to retrieve the user profile

GOVSI-719 - Add query permission to Account mgmt IAM role

---

ci/terraform/account-management/api-gateway.tf

- Set the environment variable for the authorization lambda
- So it can find the correct dynamodb table

GOVSI-719 - Set the environment variable for the authorization lambda

---

ci/terraform/account-management/lambda-roles.tf

- Give authorizer permission to secondary index
- To use the secondary index to query the database

GOVSI-719 - Give authorizer permission to secondary index

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java

Log SessionID in all relevant lambdas.
* Needed in AuthCodeHandler and LogoutHandler.
* Already done in AuthorisationHandler.
* Not relevant in other lambdas.
We need this so we can trace sessions when debugging.

GOVSI-766: Log SessionID in all relevant lambdas

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/CustomScopeValue.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidScopes.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidScopesTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

Add new scope for account management: 'am'
- Add support for custom (non-OIDC scopes).
- Expand scope validation to check for custom scopes.
- These custom scopes are private by default, meaning that it's not possible to for public users to register them against their clients using the public API.  Only we can add these scopes to clients via the database.
- Return an error is a client tries to register a private scope.
- Allow clients with private scopes to authorize.  In practice for the moment this will only be allowed for the Account Management application.
Restrict usage of the Account Management application to our private/internal client.

BAU: add new scope for account management: 'am'

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
ci/terraform/oidc/userinfo.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/KmsHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/JwksHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenValidationServiceTest.java

- Move token validation into a separate service
- Validate AccessToken signature in UserInfo
- The TokenService is getting heavy with a lot of stuff. Simplify that by moving out the Token validation logic into a TokenValidationService
- So only valid AccessTokens can retrieve userinfo

GOVSI-719 - Validate AccessToken signature in UserInfo

---

ci/tasks/deploy-oidc-api.yml

- Pass additional Terraform variable, the path to lambda warmer release, to the deploy task in the pipeline.
The pipeline is failing.

GOVSI-622: Pass Lambda release as parameter in pipeline

---

ci/tasks/deploy-oidc-api.yml

- Correct filename is deploy task to `lambda-warmer.zip` rather than `lambda-warmer-api.zip`
Pipeline is failing to deploy.
#480

GOVSI-622: Use correct filename for Lambda warmer dist

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/verify_code.tf
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientInfoHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java

- Add warmup handling to all Lambdas in all APIs
- Configure Terraform to enable warm-up handling in `client-registry-api` and `frontend-api` (`account-management-api` will follow in different PR).
- Create new base class that handles the logic to determine if the Lambda is responding to a "warmer" request
- Make all endpoint lambda extend this new base class to reduce repeated code
We have a working warmer, lets enable all Lambda's to use it.
#473

Govsi 622 java warmer

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
ci/terraform/account-management/lambda-roles.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/sqs.tf

- Check user exists before sending OTP to new email address when user updates email
- When a user changes their email address we need to send an OTP to that email. We should make sure this email is not already registered to an account.
- Remove the aws_iam_role.sqs_lambda_iam_role.arn permission as the send-otp lambda also needs permission to dynamo and therefore this role can be removed completely as it is not used elsewhere

BAU - Check user exists before sending OTP to new email address

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks.yml

Small optimisation to remove the gradle 'assemble' and 'spotlessApply' tasks when running unit tests.
There is no need to build any distributable packages in this case, so 'test' rather than 'build' does the trick.

BAU: github actions unit test optimisation

---

ci/terraform/modules/endpoint-module/api-gateway.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/outputs.tf

- Generate an API key which will eventually be required to access any of the frontend apis.
- Add this in as an environment variable which is consumed by the api-gateway-method and default to false for now.
- Output the api key as a sensitive value so it can be picked up by the pipeline
- To authenticate the frontend app to use the frontend apis. 
**Next steps**
- Set the `api_key_required` variable to true for the apis we want to authenticate

GOVSI-790 - Generate API key

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks.yml
scripts/functions.sh

Enable gradle cache in github actions.
See if this will speed up the test runs.
https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
Gradle daemon switched off to allow the cache package to be created:
https://github.com/actions/cache/blob/main/examples.md#java---gradle

BAU: enable gradle cache in github actions

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
ci/terraform/account-management/authoriser-warmer.tf
lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/ConfigurationService.java
lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandler.java
lambda-warmer/src/test/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandlerTest.java

- Add configuration option to `LambdaWarmer` to differentiate lambda type
- Warm the authoriser lambda with the correct payload
- Add code to authoriser to detect warming request and sleep then exit early.
The account management API is has warm lambdas but there is still a delay when calling that API as the authoriser isn't warm.

GOVSI-622: Warm the account-management API authoriser

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/verify_code.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IntegrationTestEndpoints.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RequestHelper.java
scripts/functions.sh

- Enforce api key authentication for the apis that are only called by our frontend app.
- These are the following: client-info, login, mfa, send_notification, signup, update_profile, userexists, verify_code
- So these APIs can only be called from our frontend app

GOVSI-790 - Enforce API key authentication

---

ci/terraform/account-management/api-gateway.tf

- When we make changes to a aws_api_gateway_integration or aws_api_gateway_method we want to generate a new aws_api_gateway_deployment. This is similar to what we do in the `/oidc` directory
- It's common issue that the aws_api_gateway_deployment doesn't get updated after to changes to any aws_api_gateway_* hashicorp/terraform-provider-aws#162. 
- Add a trigger to kick off an aws_api_gateway_deployment when there has been a change to the gateway method or integration, this will prevent us from having to manually deploy stuff in the console.

GOVSI-790 - Add triggers for accountmgnt api gateway resources

---

lambda-warmer/src/main/java/uk/gov/di/lambdawarmer/lambda/LambdaWarmerHandler.java

- Add missing `break` statements in Lambda warmer payload `switch` block
The warmer was submitting the wrong payload to the endpoint lambda due to a missing `break` in the `switch` statement.

BAU: Add missing `break` statements

---

shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

Add missing service warmer for account management to the DynamoService.
Warm-up the dynamo db connections to keep lambda cold-start times down.

GOVSI-791: add missing service warmer for account management to the DynamoService

---

ci/terraform/account-management/vpc.tf
ci/terraform/oidc/vpc.tf

- The `Name` tag needs to be capitalised otherwise the name does not display in the AWS console
Without the name showing, it is difficult to see which resources are allocated for which purposes.

BAU: Correct casing of `Name` tag on VPC resources

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authoriser-warmer.tf

Use latest version of the lambda authorizer in account management.
Warmer was running against one lambda version, whereas the authorizer was running against another, so the authorizer had longer cold starts.

GOVSI-791: use latest version of the lambda authorizer in account management

---

ci/terraform/account-management/api-gateway.tf

redeploy api when authorizer lambda is updated
Make sure api calls get routed to the latest version of the authorizer.
#509

GOVSI-791: redeploy api when authorizer lambda is updated

---

account-management-api/src/main/resources/log4j2.xml
client-registry-api/src/main/resources/log4j2.xml
frontend-api/src/main/resources/log4j2.xml
lambda-warmer/src/main/resources/log4j2.xml
lambda-warmer/src/test/resources/log4j2.xml
oidc-api/src/main/resources/log4j2.xml

Use json format for logs.
Using a structured format will make the logs more searchable.
* We're not sure whether the AWSRequestId will come through automatically or whether we'll need to configure it as an additional field.  In any case, we're not sure that Localstack provides it when we test locally, so we won't be able to see how this is behaving until this PR is deployed.
* We've gone with JSON Layout (https://logging.apache.org/log4j/2.x/manual/layouts.html#JSONLayout) as it seems like the most straightforward way to meet our needs, but JSON Template Layout is a potential alternative (https://logging.apache.org/log4j/2.x/manual/json-template-layout.html).

GOVSI-771: Use json format for logs.

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
kill-all-services.sh
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidScopes.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidScopesTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenValidationServiceTest.java

- Send RefreshToken in TokenResponse.Generate, send and store a signed RefreshToken to send alongside the bearer and ID tokens back to the client. This refresh token will be able to be used to obtain a new access token.
- Allow requests into the token endpoint with the refresh_token grant type. This will request will contain the client_id, grant_type, refresh_token and scope
- Store the refresh token using the key as the following- "client_id:subjectId". We will get the client_id out of the request and the subject id from the refresh token to retrieve the refresh token from redis. The refresh token needs to be one per user, as when we generate a new access token we need to tie that access token to a user so we can get the user information using the subject_id on user_info
- Add the …

GOVSI-718- Add Support for refresh tokens

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/site.tf
ci/terraform/account-management/variables.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/site.tf
ci/terraform/oidc/variables.tf

- Stop request tracing by default, this should be optional per environment
- Only allow request tracing in `build` and `sandpit` environments
Some request contain sensitive data, we really don't want to log this in other upstream environments, particularly production (when we get there).

BAU: Stop request tracing in all environments

---

ci/terraform/oidc/stub-rp-clients.tf

Make RP's use public subject type
To fix the stubs as currently they have no value for this and throw a null pointer exception

Make stub RP's use public subject id

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java

- So we can retrieve userinfo at the userinfo endpoint
- So the build is fixed

GOVSI-718 - Use Internal Subject to populate token

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/dns.tf
ci/terraform/oidc/localstack.tfvars
ci/terraform/oidc/variables.tf

Pass frontend url to backend in the pipeline
So that the url generated by reset password request is always the correct one for the environment

GOVSI-642: pass frontend url to backend in the pipeline

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/AccessTokenStore.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/TokenStore.java
shared/src/main/java/uk/gov/di/authentication/shared/exceptions/UserInfoValidationException.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Change how we retrieve the AccessToken from Redis by using the key of the Public subjectID and Client ID. This will retrieve the access token which we compare to the access token sent in the request. It will also retrieve the InternalSubjectID which is required to query the UserProfile table and populate the UserInfo with the information relevant to that particular User.
- Store the RefreshToken in Redis as part of its own TokenStore object alongside the internal SubjectID. The key is "REFRESH_TOKEN:client_id.public_subject_id" We need to store it like this as the public subject ID will be populated in the tokens. When a refresh token request comes in we need to access the InternalSubjectID so we can store it alongside the AccessToken for the reasons mentioned above. The best way to do …

GOVSI-718 -  Change how we store Refresh and Access tokens

---

ci/terraform/oidc/reset-password-request.tf

update 'reset password request' lambda role
So it can access dynamo.
Resolves error:
lambda is not authorized to perform: dynamodb:DescribeTable on resource
#534

GOVSI-642: update 'reset password request' lambda role

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Once a user has reset their password we should allow that user to open another tab and start another journey
- So a user does not need to open another browser to start a new session and a journey

BAU - Allow transition from RESET_PASSWORD_LINK_SENT to action USER_ENTERED_UNREGISTERED_EMAIL_ADDRESS

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java
ci/terraform/oidc/dynamodb.tf
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- We now store the Public SubjectID in the AccessToken and no longer use the InternalSubjectID in the token. This means the current logic in the authorizer will not work as it is expecting the Internal Subject ID. Refactor the Authoriser to check if the user exists via the PublicSubjectId.
- Validate the principal as before. We can assume the Subject type is always public for the client as it is used internally and therefore we do not expect it to be pairwise and can avoid calculating the SubjectID.
- Validate that the ClientID is a valid client in the authorizer
- Because we no longer store the internal subject ID in the access token and need to refactor the authorizer to use the public subject ID.

BAU - Retrieve the UserProfile using the PublicSubjectID

---

ci/terraform/account-management/lambda-roles.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java

- Set time of expiry to 15 mins in the future
- So the frontend can determine when the token has expired and the API is the source of trust

BAU - Set time of expiry to 15 mins in the future

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/TokenGeneratorHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- When we validate the access tokens we should check if they are expired and whether or not they contain the claims we expect.
- Set all timezones to use UTC so make them all explicit and not rely on what timezone the server is running on
- So we can be confident that only valid access tokens pass through
- So we don't rely on whatever timezone the server is running on

BAU - Validate the mandatory scopes and expiry times in AccessTokens

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Allow a user to start a journey if the have maxed out password reset requests
- If a user has maxed out there password request limit (more than 5 times) then they should be able to start a journey. This may be because they have suddenly remembered their password or have managed to access the last password reset link which was set.

GOVSI-644 - Allow a user to start a journey if they have maxed out password reset requests

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

-  Set Refresh Token expiry to 30 mins
- It was previously set as 3 mins which is too short

GOVSI-718 - Set Refresh Token expiry to 30 mins

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/TermsAndConditionsVersionNotAccepted.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/conditions/TermsAndConditionsVersionNotAcceptedTest.java

- Add `UserContext` class which includes both the the `UserProfile` and the `Session` as this going to be required for the VoT work
- Add a builder to the `UserContext` class
- Refactor state machine so `transition()` does not need to be called with an `Optional<C>`, this aids readability
Pre-cursor to the VoT state machine handling

GOVSI-818: Refactor context for state machine

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Populate the ID token with the vot which we can obtain from the client registry.
- Populate the vtm with the trustmark uri which will point at our trustmark lambda.
- This follows what is in the https://openid.net/specs/openid-igov-openid-connect-1_0-02.html#rfc.section.1

GOVSI-817 - Update ID token with vot and vtm claim

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/BaseFrontendHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java

- Add the `ClientRegistry` object to the `UserContext`, required by optional MFA and VoT
- The `UserContext` that is required by the state machine is going to need to be constructed in multiple lambdas, create a base class that handles this
- Also include the shared warming logic in the base class
The client object will be required in various state machine conditions, constructing it in a shared class keeps the the main lambda code clean.

GOVSI-818: Add `client` to `UserContext` and refactor its construction

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/ClientDoesNotRequireMfa.java
shared/src/test/java/uk/gov/di/authentication/shared/state/conditions/ClientDoesNotRequireMfaTest.java

- Add a condition that inspects the client stored in the `UserContext` and returns `true` if the client has a `LOW_LEVEL` vector of trust, otherwise `false`.
- Assume a higher-lever VoT if none specified
- Amend the state machine rules to allow transition straight from `AUTHENTICATION_REQUIRED` to `AUTHENTICATED` if user correctly enters their credentials and the client does not require MFA
Some RPs will not require MFA. If they register with a lower level of trust we will allow them to skip the MFA step.

GOVSI-818: Optional MFA in state machine

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java

- Currently when a user who has an existing session hits authorize then they are given a new session_id however their existing session is copied across to correspond with this new session_id. What this means is that if a user is in the middle of a flow and hits a state such as MFA_CODE_NOT_VALID, and they attempt to start a new journey they will not be able to as the STATE machine will throw an invalid transition error. We want to allow users to be able to start a new session if they wish and dispose of their existing session information to allow this to happen.
- If a user is on a session where the state is either AUTHENTICATED  we want to leave them as they are so they can skip login
- To allow users to start new journeys even if they are in a middle of a previous journey

BAU - Create a new Session when the sessionState is not AUTHENTICATED 

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

This is an attempt to break apart the large switch statement in `VerifyCodeHandler`.
It does this by pulling out logic into other places, primarily `ValidationService`, and removing duplication with early returns.
Feedback on the approach appreciated.

BAU: `VerifyCodeHandler` refactoring

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/PhoneNumberUnverified.java

- Before transitioning the user state after a successful login, check to see if the phone number has been verified. If it hasn't then return the TWO_FACTOR_REQUIRED back to the frontend. 
- When a user starts a sign up journey but either doesn't enter their phone number or doesn't verify their phone number and then drop offs, we need to ensure that next time they log in we redirect them back to the register their phone number screen on the sign up journey. This prevents a user entering an incorrect phone number which hasn't been verified and therefore gives them the chance to enter it and confirm it before it is used for MFA

GOVSI-839 - Change State machine to account for drop offs

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/helpers/RedisHelper.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientInfoHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RedisHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientSession.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java

- Calculate effective `vtr` based on request and client defaults
- Save this into the `ClientSession` object during the `authorize` process
We need to save the effective VoT for the authorisation request in order to apply it later and use it to determine if uplift is required.

GOVSI-820: Save effective VTR for auth-request in client session

---

integration-tests/src/test/java/uk/gov/di/authentication/helpers/KeyPairHelper.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/NotifyStubExtension.java

- Cache the KeyPair generated by `GENERATE_RSA_KEY_PAIR()`
- Fix SMS endpoint on StubNotifyExtension 
The `GENERATE_RSA_KEY_PAIR()` static method takes 15-20 seconds to execute and it runs 6 times in the course of the integration tests. As we don't need unique keys for the tests, we should cache the keys a re-use them where required.
The `StubNotifyExtension` was incorrectly registering the `email` endpoint twice rather than the `sms` and `email` end points. This is causing random integration test failures.

BAU: Fix Notify Stub and cache generated key-pair

---

shared/src/main/java/uk/gov/di/authentication/shared/matchers/AuditMessageMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Send a basic audit payload to the SNS topic, rather than sending a string.
* For the moment, the payload consists only of the event name and a timestamp; we'll add other fields in a subsequent PR
* Although we're using a protobuf container called SignedAuditEvent, we're not yet actually signing it (signature will be dealt with in a later task)
Using a structured format should help make the audit logs more searchable.
Can you spot the moment when my patience snapped and I gave up on trying to work out the 'right' way to compose a method reference and a function in Java?  I really wish GDS would let us use a modern language (Kotlin, Scala).
Open to suggestions about renaming the offending variable, or, better yet, what obscure syntax I can use to get rid of the need for it.

GOVSI-830: Send basic audit payload to SNS topic

---

ci/terraform/oidc/dynamodb.tf

Does exactly what it says on the tin, we don't have this enabled at the moment.

GOVSI-861: Enable point-in-time recovery for DynamoDB tables

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/helpers/DynamoHelper.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/DynamoHelper.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/SessionState.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Update terms and conditions time to be consistent with times of the other data in dynamo
- When a client consent already exists with a client ID rather avoid creating a duplicate entry with the same client ID and just update what is already there
- Build the user context in authorize so that we can check if a user requires consent or needs to approve terms and conditions from an SSO journey
- Add extra tests

GOVSI-368 -  Add consent and t&c checks for SSO

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Allow transition from `CONSENT_REQUIRED` to the correct states should the user start a concurrent journey before giving consent
To close loopholes in the current state machine

BAU: Add Consent transactions for concurrent journeys

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/BaseFrontendRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/MfaRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SendNotificationRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SignupRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UpdateProfileRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/BaseFrontendHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java

- Amend `BaseFrontendHandler` to be generic taking the type of request
- Base class should handle deserialisation of request and pass it to delegate in handler
- Amend all frontend API handlers (except `PasswordResetHandler`) to extend `BaseFrontendHandler`
- Ensure all calls to `StateMachine.transition()` use the `UserContext` constructed in `BaseFrontendHandler`
Reduces the amount of 'boiler plate' code in handlers, and indentation levels. Ensures consistency across handlers.

BAU: Extend all frontend handlers from BaseFrontendHandler

---

ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/wellknown.tf

- Configure lambdas with environment env var
- All frontend lambdas require the ENVIRONMENT env var to be configured as they inherit the BaseFrontendHandler

BAU - Configure lambdas with environment env var

---

ci/terraform/oidc/send_notification.tf

- Give send notification lambda permission to dynamo
- As the send notification lambda uses the BaseFrontendHandler, it now required permissions to dynamoDB.

BAU - Give send notification lambda permission to dynamo

---

ci/terraform/shared/lambda-roles.tf

Adjust the execution role for the Lambdas to only have the following permissions:
```
"ec2:DescribeNetworkInterfaces",
"ec2:CreateNetworkInterface",
"ec2:DeleteNetworkInterface",
```
The ITHC report suggested the original perms were to pervasive, according to https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html, the above is all that is required

GOVSI-562: Remove unnecessary IAM permissions

---

ci/terraform/oidc/api-gateway-frontend.tf

Deploy frontend api without a custom domain
First stage of the deployment being done without a custom domain, which will be included after.
#642

GOVSI-748: deploy frontend api without a custom domain

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/BaseFrontendHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/matchers/AuditMessageMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Send AWS Request ID and Session ID to the audit service
They are needed by our performance analysts and our monitoring.
This is the first PR of a few that will incrementally add data to the payload

GOVSI-830: Send audit payloads to SNS (1)

---

ci/terraform/account-management/lambda-roles.tf
ci/terraform/shared/lambda-roles.tf

- Further restrict the execution privileges of the endpoint lambdas so they can only connect to our VPC
- Add same restriction to account management lambdas
Tightening up privileges before deploying a production environment
#638

GOVSI-562: Restrict Lambda networking connection to specific VPC

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml
ci/tasks/terraform-taint.yml
ci/terraform/shared/build-sizing.tfvars
ci/terraform/shared/integration-sizing.tfvars
ci/terraform/shared/production-sizing.tfvars
ci/terraform/shared/production-stub-clients.tfvars

- Add a `.tfvars` per environment to define Redis and Dynamo sizing
- Inject correct file into terraform apply during shared deployment task
- Ensure state bucket name is configurable on Terraform deployment tasks (will be different for production)
- Add a (temporary) stub client for production
Preparation for deploying a production environment

GOVSI-822: Add environment sizing files

---

ci/terraform/oidc/api-gateway-frontend.tf

Use domain name for frontend api
Currently using the AWS generated endpoint temporarily rather than the domain name.
#642 
#645

GOVSI-748: use domain name for frontend api

---

ci/terraform/shared/dynamodb.tf

- When using provisioned Dynamo, specify read/write capacities on GSIs
Pipeline is failing while creating Dynamo tables

GOVSI-822: Add read/write capacity to GSI

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/matchers/AuditMessageMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

We will need to return to this - there are places in need of refactoring to expose client ID to the audit service

GOVSI-830: Include client ID, if available, in the audit payloads

---

ci/terraform/account-management/sqs.tf
ci/terraform/account-management/vpc.tf
ci/terraform/oidc/sqs.tf
ci/terraform/shared/vpc.tf

- Ensure Cloudwatch group is created for the SQS lambda
- Add an active version alias to the SQS lambda
- Add log subscription to the cloudwatch lambda
- Add a `Name` tag to the VPCs
The CloudWatch group needs to exist before the lambda can execute. The log subscription is also required for monitoring.
Naming the VPC makes it easier, in the console, to see which VPC is which.

GOVSI-822: Create SQS cloudwatch groups and name VPCs

---

ci/terraform/shared/kms.tf

This PR does not (a) grant any lambdas access to the signing key or (b) update the lambda app code to load the key

GOVSI-828: Create KMS signing key for audit payloads

---

ci/terraform/account-management/sqs.tf
ci/terraform/account-management/variables.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/variables.tf

- Allow a map of Notify template IDs to be passed in to the Terraform
The template IDs for production with be different as they exist in a different account.

GOVSI-822: Make Notify template IDs parameters

---

shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java

- Check if userprofile is not null before building usercontext
- The email will exist in the session but not the userprofile if they haven't got the password screen on the signup journey. Therefore we should first check if userprofile is not null before building it in the usercontext

BAU - Check if userprofile is not null before building usercontext

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/ClientIsAnInternalService.java
shared/src/test/java/uk/gov/di/authentication/shared/state/conditions/ClientIsAnInternalServiceTest.java

- Add a isInternalService attribute to the client registry which defaults to false and cannot be set within the code. This means that we have complete control over when this is set by only setting it manually for the apps that we want to class as internal.
- Check if the client is internal before requesting consent
- Add offline access to scopes in token if it exists in auth request
- We can use the isInternalService attribute to prevent showing certain pages to the user when using an internal service such as consent when a user uses account management
- So we don't lose the offline scope from the tokens if it is present in the auth request

BAU - Add condition to check whether a client is an internal client

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- If a service is internal then just use the scopes from the auth request otherwise calculate them using the consent
- Because internal services will not require consent so we can skip that

BAU - Check to see if service is internal

---

ci/tasks/deploy-acct-mgmt-api.yml

- Inject `shared_state_bucket` variable at deploy time of account management
In #667 we added the use of the shared terraform state but omitted to inject the state bucket at deploy time.
#667

GOVSI-824: Add shared_state_bucket var to account management deployer

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/trustmarks.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/oidc/wellknown.tf
ci/terraform/shared/outputs.tf
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Sign the audit payloads with a key from KMS
Assert provenance of audit messages.

GOVSI-828: Sign audit payloads

---

ci/terraform/shared/localstack.tfvars
ci/terraform/shared/stub-rp-clients.tf
echo-int-test-vars.sh
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/CookieHelperTest.java

Add facility to share cookie consent across clients
Uses a new internal-only database flag in the client-registry 'CookieConsent'.  This flag can only be set by the database schema migration scripts in the build pipeline, and cannot be set by external clients using the client registration api.  It is only available for our use to share existing consent across the internal clients.
When the flag is set any existing consent should be shared across the internal applications.  This is done by the 'auth-code' endpoint appending additional parameters to the redirect uri when redirecting:
- cookie_consent=accept - set consent to accept in the target client.
- cookie_consent=reject  - set consent to reject in the target client.
- cookie_consent=not-engaged - either use existing consent or show …

GOVSI-843: Add facility to share cookie consent across clients

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelperTest.java

Add some default security headers to all api gateway responses in the helper class.
The missing headers was identified as a security risk from the ITHC.

Add default security headers to all api gateway responses

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java

Update email handler changed to read correct value for email address.
It fixes the bug where it can't validate an otp code.

Update email handler correct redis hash

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RequestParameters.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

Forward cookie_consent from 'authorize'
The cookie_consent flag first arrives when a client calls 'authorize', so it needs to be passed-on to the 'auth-code' endpoint for processing.
#668

GOVSI-834: forward cookie_consent from 'authorize'

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineJourneyTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineTest.java

Added a new transition option in the state machine to allow password re-entry from login screen.
If after entering password, the user uses the browser back button then allowing them to re-enter their password should be a valid transition.

Add new state transition to allow password re-entry and add initial unit test for state machine journeys

---

ci/terraform/oidc/outputs.tf

Output cookie domain from terraform
To feed into a frontend environment variable so that cookies are always set on the right domain regardless of environment.
#682

GOVSI-834: output cookie domain from terraform

---

ci/terraform/account-management/sqs.tf
ci/terraform/oidc/sqs.tf

- Add encryption at rest to SQS
No data should be unencrypted at rest.

GOVSI-824: Add encryption at rest to SQS

---

shared/src/main/java/uk/gov/di/authentication/shared/configuration/AuditPublisherConfiguration.java
shared/src/main/java/uk/gov/di/authentication/shared/configuration/BaseLambdaConfiguration.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SnsService.java

This PR is an example of how we can decompose `ConfigurationService` into capabilities using mixins, implemented using interfaces and default methods.
There is a single object for configuration all lambdas, which means all services have access to configuration objects that they don't need.
Configuration should be done at the API level or lower, with mixins used for shared capabilities such as "AWS Region" or "Environment"
The aim of the game is to have a separate `ConfigurationService` per sub module, with shared capabilities in `uk.gov.di.authentication.shared.configuration`

BAU: Decompose `ConfigurationService`

---

ci/terraform/account-management/alerts.tf
ci/terraform/account-management/variables.tf
ci/terraform/modules/endpoint-module/alerts.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/alerts.tf
ci/terraform/oidc/variables.tf

- Personalise the alarm description by adding the threshold value and the environment and name of the AWS service that caused the alarm
- To make it easier to identify what caused the cloudwatch alarm when it is raised in Slack

BAU - Improve cloudwatch alarm description

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambdaTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java

This PR fixes two bugs:
- Hashing each user data field individually based on their presence, rather than using user.id as a proxy for their presence.
- Pass phone number from the request to update profile rather than use the loaded userprofile, as it has stale data at that point.

GOVSI-1061/1062: Fix errors when auditing phone number updates

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks.yml
account-management-api/build.gradle
account-migrations/build.gradle
build.gradle
client-registry-api/build.gradle
frontend-api/build.gradle
oidc-api/build.gradle
shared/build.gradle

- Add Sonar plugin to Gradle
- Add Jacoco plugin to Gradle
- Run coverage reports in Github Actions on PR
- Configure unit tests to report coverage to SonarCloud
To allow us to get an overview of how well tested our code is, as well as linting and static code analysis

GOVSI-1053: Add SonarQube checks

---

.github/workflows/pre-merge-checks-am.yml
.gitignore

Run account management checks when gradle config changes.
Ignore .vscode directory.
Account management checks were not being run for dependabot or gradle version changes.

BAU: run account management checks when gradle config changes.

---

.github/workflows/sonar-analysis-on-merge.yml

- Add a new action that runs Sonar analysis on the main branch after each merge
The current checks only analyse code in the current PR, we want to get an analysis of the repo as a whole to help us drive tech debt stories.
#953

GOVSI-1053: Add a GitHub action perform Sonar on merge

---

oidc-api/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/domain/OidcAuditableEvent.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java

Audit issuing of auth tokens
An audit event is needed to tie together the end of both the sign-in and sign-up journeys; both end with issuing an auth token.
GOVSI-1067 specified that this should be done in TokenHandler, but in practice we have no way to get hold of the sessionId from within the TokenHandler.  It was agreed via Slack that AuthCodeHandler would also be a suitable place to fire the audit event as it is the "last stop" in the audit flow.

GOVSI-1067: Audit issuing of auth tokens

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java

- Add sessionID to state transitions and invalid state transitions 
- Remove logging the InvalidStateTransition in the Lambda 
- By adding the sessionID we can have a better ID of the users behaviour 
- We are currently logging the InvalidStateTransition twice and we should just rely on the StateMachine to log this error

GOVSI-1064 - Extend state logging

---

ci/terraform/account-management/site.tf
ci/terraform/audit-processors/site.tf
ci/terraform/oidc/site.tf
ci/terraform/shared/site.tf

Pin terraform version to 3.63.0
Version 3.64.0 has just been released and is breaking the build

BAU: pin terraform version to 3.63.0

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java

- Build the UserContext in AuthCode so we have the SessionID when logging State transitions
- This allows us to achieve more accurate logging by logging out the session ID with each state transition and state transition error

GOVSI-1064 - Pass UserContext to StateMachine when it is available

---

audit-processors/build.gradle
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambdaTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/CaptureLoggingExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/LogEventMatcher.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/StubAppender.java

This extracts a component that attaches a stub appender to a class's logger and exposes log events to the test for analysis
This resided in the audit-processors module rather than `shared-test` and we better modelled as an extension

BAU: Extract `CaptureLoggingExtension`

---

ci/terraform/oidc/wellknown.tf

It also doesn't need access to the events SNS topic as it is not user-facing behaviour

GOVSI-1055: Create and attach new role to `WellKnownHandler`

---

shared/src/test/java/uk/gov/di/authentication/audit/AuditPayloadConsistencyTest.java

This PR adds a consistency test for the SignedAuditPayload
We can't afford to accidentally break the payload format, so this PR programmatically fills out all fields with deterministic input and compares the hash of the output to a known hash.
This means that adding new fields or re-ordering fields will break this test and force the user to double-check their change.

BAU: Consistency check for audit fields

---

ci/terraform/account-management/sqs.tf
ci/terraform/oidc/sqs.tf

- Increase the DLQ retention time to 6 hours
We are getting e-mail address validation failures from Notify, we need to collect samples of the failing addresses, we can do this by looking at the DLQ, but 1 hour is not always enough time for us to respond to the alerts.

BAU: Increase DLQ retention time for messages

---

ci/terraform/modules/endpoint-module/alerts.tf

- Exclude error that start with the phrase `Session attempted invalid transition from` from triggering alerts in the 2nd line channel.
These errors are tied with a known, non-critical, issue and causing a lot of noise, when we have addresses the core problems then we will remove the exclusion.

GOVSI-1107: Exclude transition errors from alerting

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineTest.java

- Store a list of transitions that can occur at any state (normally backward steps), not yet populated
- Add builder for default transitions
- Alter the `transition()` method to look at the the `anyStateTransition` list for a matching action/condition before throwing the normal exception.
We have a number of transitions in the state machine that can occur at any state, by allowing a default transition we can keep the code more succinct!

GOVSI-1065: Default state transitions

---

shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineTest.java

- Add an `include()` method to the statemachine builder which allows common transitions to be applied to multiple states
- Move the common `USER_ENTERED_VALID_MFA_CODE` transitions to an include
We are finding scenarios where the same group of transitions need to exist at different states, this PR lays ground work for being to extract these common transactions into "includes" and use them where required.
#1007

GOVSI-1065: Transition includes

---

ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/token.tf

We will eventually delete the original roles

GOVSI-1055: Use `name_prefix` to avoid role name clashes

---

build.gradle
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/outputs.tf
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/ApiGatewayHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/helpers/RequestHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/CookieHelperTest.java

- Rename class to better reflect its purpose
- Make base class `abstract`
- Add a RequestHandler variable that will be populated by the sub-classes
- Add a mock `Context` object and an ObjectMapper to serialise requests
- Add a base `makeRequest()` method that will construct a request, from a given body and headers, and send it to the handler
- Change the first integration test in `AuthorisationIntegrationTest` to use the new mechanism
- Add new environment variable to `build.gradle` for the test task
- Add output to Terraform to feed SNS topic ARN into integration tests
- Refactor all, remaining, tests in `AuthorisationIntegrationTest` to call handler directly rather than make HTTP request
- Create a `TestConfigurationService` class to override the value for the Redis host
- Add new …

GOVSI-1105: Refactor of AuthorisationIntegrationTests

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/domain/RequestHeaders.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ClientSessionServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/SessionServiceTest.java

Support lower-casing of headers by api gateway or localstack.
Groundwork to support upgrading to the latest localstack version, the upgrade will follow in another PR.
We send http headers to API Gateway capitalised and retrieve them capitalised in the lambdas.  In theory http headers are case-insensitive so this capitalisation should not matter, but at the moment we get out what we put in.
Rightly or wrongly localstack has started to lower-case header names in their implementation which has broken our tests.  This is fine in theory if headers are genuinely case insensitive but it does cause an issue.  There is some suggestion that a later version or different flavour of the actual AWS api gateway will behave like this.
This PR provides a way to work around the issue by partially …

GOVSI-1052: support lower-casing of headers by api gateway or localstack

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java

- Remove now defunct code in `AuthorisationIntegrationTest`
- Replace assertions on status code with customer matcher
Tidying up refactor in previous PR
#1026

GOVSI-1105: Remove unused code & use status matcher

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/authorize.tf

- Revert making authorise endpoint optional.
In previous PR we made the authorise endpoint optional so we didn't need to deploy it localstack for integration tests, revert this as it is causing a destroy cycle in the pipeline.
We need to review how we do this with causing errors.

BAU: Don't make authorise endpoint optional

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/trustmarks.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
docker-compose.yml
docker/localstack.Dockerfile
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java

Upgrade localstack to 0.12.20
Set HEADERS_CASE_INSENSITIVE in the relevant lambdas, only true on localstack.
Change localstack kms provider: 'KMS_PROVIDER: local-kms'.
Lower log level for when header missing.
Move to the latest localstack version.
Localstack is now lower-casing headers in api gateway, so switch the flag to handle this when running on localstack.
Switch localstack kms provider to resolve integration test failures with kms.  'local-kms' supports more kms functionality than the localstack implementation.
#1024

GOVSI-1052: upgrade localstack to 0.12.20

---

integration-tests/src/test/java/uk/gov/di/authentication/api/ApiGatewayHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java

- Alter `AuthCodeIntegration` test to follow new integration test pattern
- Move some helper methods into base class
- Add new constructor to handlers that allow passing in of a `ConfigurationService` instance, this simplifies test initialisation.
We are moving all integration tests to a different pattern
#1026 
#1027 
#1031

GOVSI-1105: Migrate auth-code integration test

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/matchers/APIGatewayProxyResponseEventMatcher.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/matchers/UriMatcher.java

- Migrate the login endpoint integration test to use the new pattern
- Convert logout handler integration tests to use new pattern
- Uncomment failing assertions as these now work
- Add tests for missing scenarios
- Refactor APIGatewayProxyResponseEventMatcher to take other matchers as the `expected` argument
- Add a URI custom matcher to deal with matching redirect URI
- Refactor Logout tests to use custom matchers
We are moving the integration tests over to a more efficient pattern
#1026 
#1027 
#1031 + others

GOVSI-1105: Refactor Login and Logout integration tests

---

build.gradle
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/ApiGatewayHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java

- Use new test pattern for Reset Password handler integration test
- Add assertion to ensure Notify request contains correct content
- Use new test pattern for Reset Password Request handler integration test
- Remove static instance of object mapper as non-static instance inherited from base class
- Use new test pattern for Sign Up handler integration tests
- Use new test pattern for Update Client handler integration tests
We are migrating all integration tests to more efficient pattern
#1026 
#1027 
#1031 
#1037 + more

GOVSI-1105: Integration test refactor

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ApiGatewayHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java

- Use new test pattern for Check User Exists handler integration tests
- Add variants of `constructFrontendHeaders` base method to cater for tests with a clientSessionId
We're converting all integration tests to a new pattern

GOVSI-1105: Convert User Exists integration tests to new pattern

---

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SendNotificationIntegrationTest.java

- Disable the SendNotificationsIIntegrationTests while we investigate the core issue
These tests are consistently failing, and blocking people from merging.

BAU: Temporarily disable troublesome tests

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java

- When a user tries to either reset or change their password using their existing password then we should not allow that and return an error to the frontend. The frontend will look for this error and display an appropriate error message to the user.
- Because a user shouldn't be able to change their password to their existing password.

GOVSI-1100 - Validate new password against existing password

---

.github/workflows/pre-merge-checks-am.yml
.github/workflows/pre-merge-checks.yml
get-lambda-logs.sh

- Upload the `logs` directory on integration failure (similar to how we upload to test reports), this is useful for debugging- 
- Use the AWS CLI to extract and download the cloudwatch log groups from localstack. The same information is available in the docker console log, but when downloaded into separate files.
Very useful when debugging.

GOVSI-1105: Add docker log test output

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java

- Compare the new password using the Argon2 verify method
- Add logging
- We were previously comparing the hashpassword against the plain text password which will not work. Use the Argon2 verify method to check if the new password is the same as the old one.

GOVSI-1100 - Compare the new password using the Argon2 verify method

---

ci/terraform/account-management/alerts.tf
ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/variables.tf
ci/terraform/oidc/alerts.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/variables.tf

- Set up a Cloudwatch alarm for each WAF which will alert when there's has been 20 or more blocked requests in a single hour. This is on a per WAF basis. When a CloudWatch alarm has been triggered, it will use the SNS topic that already exists. The messages on this SNS topic will be picked up by the alerting lambda which will post a message to slack. This uses the same method as we have in other places.
- Set sampled_requests_enabled to true. By setting this to true it will allow us to store a sampling of the web requests that match the rules. These can viewed by the AWS WAF Console. This is particularly useful to help analyse the cause of the blocked requests.
- On each of the APIs (OIDC, Frontend and Account management) we have a WAF sitting in front to block requests which meet certain …

GOVSI-951 - Set up Cloudwatch alarms for WAF Blocked requests

---

account-management-api/src/main/resources/log4j2.xml
account-migrations/src/main/resources/log4j2.xml
audit-processors/src/main/resources/log4j2.xml
client-registry-api/src/main/resources/log4j2.xml
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/BaseFrontendHandler.java
frontend-api/src/main/resources/log4j2.xml
lambda-warmer/src/main/resources/log4j2.xml
lambda-warmer/src/test/resources/log4j2.xml
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/resources/log4j2.xml
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java

This PR uses Log4j2's `ThreadContext` and `JsonLayout` to attach a `session-id` key in all JSON log lines
This will make it easier to query by session id when doing log exploration and reduces the noise in the log message itself (as they no longer need to attach session id in the templated line).
Before:
```
{
...
"message": "Action happened for session id foo-bar-baz"
...
}
```
After:
```
{
...
"message": "Action happened for session id foo-bar-baz",
"session-id": "foo-bar-baz"
...
}
```
If the session id is not available, the field value is `unknown`.
There will be a future PR to remove session ids from the `message` field.

GOVSI-1144: Attach session id to all loglines

---

frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/CookieHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Create persistent cookie on authorize if one doesn't exist. If it does exist, then use the value from the existing cookie and put it in a new cookie.
- Set the expiry of the cookie to 13 months.
- Use the multivalue map to have multiple cookies under the Set-Cookie header as explained here https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/
- Add new methods in the CookieHelper to parse a multivalues map to help with testing
- Remove test data from the CookieHelper class
- To have a new cookie which is used across the GOV.UK Sign In and account management applications

GOVSI-1121 - Generate new persistent cookie in authorize

---

integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/TokenSigningExtension.java

- Refactor the `KmsHelper` class into an extension
- Add the extension to the base integration helper class
- Add code to create key (and alias) if it doesn't exist
- Create a new extension `TokenSigningExtension` that extends `KmsKeyExtension`
- Move specific token signing and verification code to the new extension
- Leave the base `KmsKeyExtension` generic as this will also be used to provide audit signing keys
We are refactoring how provide the AWS/Localstack resources to integration tests. This extension will, later, later be used to create the KMS keys in localstack rather than us pre-creating them using Terraform.

GOVSI-1114: Refactor KMS helper into extension

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthenticateIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java

- Initialise a new KmsKeyExtension in the base test for the Audit Signing key
- Refactor the TestConfiguration to be static so we can use configuration values to initialise extensions
- Use KeyUsageType enum rather than string
All integration tests require a an audit signing key for the handlers to work correctly.
#1083

GOVSI-1114: Add KmsKeyExtension for audit signing key

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelperTest.java

- This helper will take in the input headers and pull out the persistent ID if it exists under the 'di-persistent-session-id' header name. If it does not exist then we will set the value to 'unknown'.
- This value will be used for updating the audit.
- The helper will be used by the frontend apis and account management apis.
- To have a single place used for extracting the `di-persistent-session-id` from the input headers.

GOVSI-1143 - Create persistentIdHelper for extracting persistent ID from input headers

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/WarmerHelper.java

Lambdas do not start fresh containers per request.

GOVSI-1144: Clear `ThreadContext` map on pre-warm check

---

build.gradle
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SnsTopicExtension.java
shared/build.gradle

- Add a new extension to create a required SNS topic needed to execute integration tests (the call to `CreateTopic` actually reuses existing topic with same name if it already exists)
- Add an instance of this extension to the base integration test to represent the audit event topic
We are adding the managing of required resources to the integration tests via extensions.

GOVSI-1114: Add an extension to manage required SNS topics

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java

- Add a new SqsQueueExtension to create queue dependency before running tests
- Ensure each test class gets its own queue
- Clear queue before each test
- Refactor integration tests for handlers that send to notifications queue to assert on queue contents rather than use the NotifyStub to wait for notify requests.

GOVSI-1114: Add SQS extension to manage queue dependency

---

audit_payload.proto
shared/src/main/java/uk/gov/di/audit/AuditPayload.java
shared/src/test/java/uk/gov/di/authentication/audit/AuditPayloadConsistencyTest.java

- Add the di-persistent-session-id field to audit_payload.proto.
- Regenerate the AuditPayload.java by using the `protoc --java_out=shared/src/main/java/ audit_payload.proto` command. This requires protobuf to be installed which can done via homebrew.
- Update the hash in the AuditPayloadConsistencyTest
- We want to start saving the di-persistent-session-id to audit. Before we do that we should update the schema to allow this to happen. Once we have merged this change we can then start saving the di-persistent-session-id

GOVSI-1143 - Update schema with di-persistent-session-id field

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java

- Before we check that the users new password is not the same as the old password, we should check that the old password is not null. If it is null, we know that it is a migrated user which is resetting their password.

BAU - - Check that current password is not null

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/matchers/AuditMessageMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

- Start saving the persistent-session-id to Audit
- Put persistent-session-id and phone number in correct order
- So we can see the persistent-session-id in the Audit 
- - There were some situations where persistent-session-id and phone number were audited in the wrong order

GOVSI-1143 - Start saving the persistent-session-id to Audit

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambdaTest.java

- Pass the persistent-session-id to Splunk using the CounterFraudAuditHandler
So we have visibility in Splunk

GOVSI-1156 - Pass persistent-session-id to Splunk

---

account-management-integration-tests/build.gradle
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SnsTopicExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/TokenSigningExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

- Remove the Terraform step from integration test startup
- Ensure injected ConfigurationService is used for all dependencies in LoginHandler
- Create TokenSigner in base class rather than individual classes, to ensure consistent initialisation of the test ConfigurationService instance
- Override Redis values in the test ConfigurationService rather than get then from SSM (we'll change this later)
- Tweak the integration test dependency initialisation to ensure dependency creation before test code executed
This is the final step on the road to speeding up the integration tests. We now have extensions that will create test dependencies (Localstack resource, Dynamo tables etc) per test class, so we no longer need to Terraform those resources. This reduces the test execution time from over …

GOVSI-1114: Remove Terraforming of Localstack resources

---

ci/terraform/oidc/reset-password-request.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/NotificationHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java

- Move the building of the Password reset link to the ResetPasswordRequestHandler
- Ensure the ResetPasswordRequest lambda has the correct environment variables available
- Create a new helper service and add a method which will be used to construct the Reset password URL.
- We will eventually want to add additional information to this link such as sessionId which we will not have available to us in the NotificationHandler.
- The ResetPasswordService helps simplifies the ResetPasswordRequestHandler and also allows for higher test coverage which we were lacking before.

GOVSI-1154 - Build password reset link in ResetPasswordRequestHandler

---

build.gradle
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/BaseAwsResourceExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DynamoExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/KmsKeyExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ParameterStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SnsTopicExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java
shared/build.gradle

- Create an SSM Parameter Store extension to manage parameter store dependencies
- Use the extension to create resources required by the ConfigurationService
Improves test coverage by using Localstack to provide Parameter Store values to integration tests.

GOVSI-1114: SSM extension

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java

- Add session-id and persistent-session-id to password reset link
- They will then be available to the frontend to send in the API request to the ResetPasswordHandler.

GOVSI-1154 - Add session-id and persistent-session-id to password reset link

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/events-sns.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/trustmarks.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/shared/localstack.tfvars
ci/terraform/shared/outputs.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/ssm.tf

This PR uses the roles created in a previous PR as the execution role in API lambdas

GOVSI-1055: Use new roles in API lambdas

---

ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/token.tf
ci/terraform/shared/outputs.tf

- Grant permissions to use the signing key, not the alias

GOVSI-1055: Role fixes

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java

- Expect a valid session-id to be included in the request made to the ResetPasswordHandler. Make use of the BasefrontendHandler to handle this for us. 
- Previously we had no way to determine the session of a user when a reset password request is made. A session id will now be added to the request made to the ResetPasswordHandler and therefore we can slightly refactor this to make use of the BaseFrontendHandler to prevent us duplicating code and make it consistent with other frontend lambdas.
- The session-id will be allow us to tie a string of requests together and ensure that the request is made by a user with a valid session.
- Dependent on https://github.com/alphagov/di-authentication-frontend/pull/414 being deployed first

GOVSI-1154 - Expect a valid session when the ResetPasswordHandler is called

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelperTest.java

Log session id in account management handlers.
The session id is passed as a header to each api call from the account management frontend.
Include in audit events.
Ability to view a single session across both frontend and account management in the logs and audit trail.
https://github.com/alphagov/di-authentication-account-management/pull/249

GOVSI-1141: log session id in account management handlers

---

.github/workflows/pre-merge-checks.yml

- Conditionally execute the the Sonar scan if the PR is not raised by Dependabot. 
Dependabot PRs do not access to repository secrets so will fail the Sonar scan.

BAU: Stop Sonar scanning for dependabot PRs

---

build.gradle

Add slf4j no op jar to suppress slf4j logging in lambdas.
See: http://www.slf4j.org/codes.html#StaticLoggerBinder
We are getting approx 40K per day SLF4J log messages even though we are not using SLF4J.  The link above shows how to silence these messages.

GOVSI-1106: add slf4j no op jar to suppress slf4j logging in lambdas

---

.github/workflows/pre-merge-checks.yml

- Remove sonarcloud from tests
- This is the error which we were seeing `You are running CI analysis while Automatic Analysis is enabled. Please consider disabling one or the other.`
- It seems to be running multiple times so remove it from the test task in github actions.

BAU - Remove sonarcloud from tests

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/LevelOfConfidence.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevelTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Support additional vector values for Identity. These are - 
Pl - Low
Pm - Medium 
Ph - High
Pv - Very High
- Although Identity will only support Medium from day one, if multiple vectors are passed in the AuthnRequest and an identity value is present, we find the vector with the lowest identity value. If there are multiple vectors with the same identity value, then we next find the CredentialTrustLevel with the lowest trust level and that vector will then construct our VectorOfTrust which will be stored against the ClientSession.
- Amend the VectorsOfTrust object which will now take in the LevelOfConfidence in it's constructor, alongside the CredentialTrustLevel. The LevelOfConfidence is optional, so if an identity vector is not sent in the request then it will be null in the …

GOVSI-1161 - Handle vector values for Identity

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevel.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevelTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Update the ID token to include LevelOfConfidence value if that is what has been requested. 
- Only accept the medium Credential trust level when it is ordered ['Cl.Cm'] and return an error when it is received ['Cm.Cl'] to make it completely explicit
- The ID token was previously only populating the VOT value with CredentialTrustLevel. Now we have the LevelOfConfidence, if that has been requested we need to ensure the entire VectorOfTrust value is in the vot claim in the ID Token. 
- Add additional tests

GOVSI-1161 - Update ID token VOT value and enforce ordering of CredentialTrustLevel

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- The VTM claim in the id token was empty because we were only passing in the URI object and not the string of the URI. Fix this by adding toString.
- Add extra assertions in the TokenServiceTest to perform more explicit checks of what we expect to receive in the ID token
- Pass in the curve as null to the AccessTokenHash.compute method as the method with 2 parameters we were previously using was deprecated. The null in the curve gives exactly the same behaviour as when we left that parameter out and is not used.
- So the VTM claim is not left empty 
- We have more checks on the ID token which will flag up if anything breaks

GOVSI-1161 - Fix empty vtm claim

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/TrustMarkResponse.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/LevelOfConfidence.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java

- Update Trustmark handler with LevelOfConfidence values
- So we can correctly display the LevelOfConfidence values we support

GOVSI-1161 - Update Trustmark handler with LevelOfConfidence values

---

ci/terraform/oidc/api-gateway.tf

- Add a conditional rule to the OIDC WAF which will allow clients to use localhost in non-prod environments. The 2 rules which will not be enabled in non-prod are EC2MetaDataSSRF_QUERYARGUMENTS and EC2MetaDataSSRF_BODY
- We have external clients testing against our integration and build environments. It is common for them to test using localhost which means sometimes in the request the query arguments or request body can contain 'localhost'.

GOVSI-1145 - Allow localhost to be used in the OIDC WAF when env is not prod

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/CheckUserExistsRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/MfaRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SendNotificationRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SignupRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UpdateProfileRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
ipv-api/build.gradle
ipv-api/src/main/java/uk/gov/di/authentication/ipv/domain/IPVAuditableEvent.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IPVAuthorisationRequest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
settings.gradle
shared/src/main/java/uk/gov/di/authentication/shared/entity/BaseFrontendRequest.java
shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Add IPV authorisation handler.
Create a new endpoint for the frontend to call which redirects to IPV /authorize by building an authorization request, sending the appropriate redirect back to the frontend.
The lambda has been created in a new java module called 'ipv-api' but is effectively a frontend api call.  'BaseFrontendHandler' has been moved to shared so it can be used in the new handler.
The endpoint is only deployed to build for the time being pending proving.
If a service requests a level of confidence requiring ID then we should redirect to the IPV service once the user is authenticated.

GOVSI-1165: add IPV authorisation handler

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationResponse.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandlerTest.java

- Return the SubjectType that we have actually updated in the DB
- We need to add validation to the SubjectType in both the RegistrationHandler and UpdateClientConfigHandler
- We were hardcoding the response to Public even though we were updating the DB with the value sent in the request

BAU - Return the SubjectType that we have actually updated in the DB

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- If the cookie_consent value in Authorize is not valid then don't pass the cookie_consent parameter to the frontend
- If the cookie_consent value in AuthCode is not valid then set the cookie_consent parameter to 'not-engaged'
- Tidy up AuthCode tests and remove ConfigurationService from AuthCode
- To ensure we are checking cookie_consent values at the first opportunity and only passing only values that are valid

GOVSI-1145 - Validate cookie values

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java

- Validate that the SubjectType is either 'public' or 'pairwise'.
- The SubjectType is an expected value in the registration request however we didn't have any validation for this.

BAU - Validate the SubjectType in the registration request is valid

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/variables.tf

Tweak deployment dependencies for the ipv-authorize endpoint
- Forces deployment of the api-g endpoint for build and integration only.
Endpoint was created in api-g but not deployed.
#1165

GOVSI-1165: tweak deployment dependencies for the ipv-authorize endpoint

---

ci/terraform/oidc/variables.tf

Delete ipv-authorize to resolve terraform cycle
Terraform apply has a cycle so deployment failing.  Removing the endpoint, then will reapply in a subsequent PR.
#1178

GVOSI-1165: delete ipv-authorize to resolve terraform cycle

---

ci/terraform/oidc/api-gateway-frontend.tf

Remove ipv-authorize from deployment to fix cycle
There is still one resource with a cycle when deploying the stage, so removing the stage deployment trigger.
#1179

GOVSI-1165: remove ipv-authorize from deployment to fix cycle

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/variables.tf

Switch on ipv-authorize endpoint in build and int
Terraform cycle has been resolved in the pipeline so now switching-on.
#1179 
#1180

GOVSI-1165: switch on ipv-authorize endpoint in build and int

---

.github/workflows/pre-merge-checks.yml
build.gradle

- Revert alphagov/di-authentication-api#1149
- Parallelise unit and integration tests into separate jobs and cache resulting reports
- Add build job and cache build
- Use GitHub actions service containers to save on Docker Compose build/up time
The problem requiring #1149 has been resolved.
Other changes required to keep total test time at around 5 mins (if not under).

GOVSI-1158: Optimise Github Actions

---

ci/terraform/oidc/ipv-authorize.tf

Switch ipv-authorize to post
BaseHandler requires a body.

GOVSI-1165: switch ipv-authorize to post

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IPVAuthorisationResponse.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/SessionState.java

Make ipv-authorize return 200 rather than 302.
- provide the redirectURI in the body along with a session state
- only one state is returned at the moment, different scenarios to be added later.
Simpler client-side code, Axios still seems to be following the redirect under the hood even though it has been configured not to.

GOVSI-1165: make ipv-authorize return 200 rather than 302

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java

Store IPV host only in configuration rather than the authorize uri.
The configuration value can them be reused elsewhere to hit other IPV endpoints, 'token' for example, rather than having separate configuration for each endpoint.
Will look to rename the configuration and environment variable to reflect this change in a later refactoring.

GOVSI-1165: store IPV host only in configuration

---

ci/terraform/oidc/ipv-callback.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IPVStubExtension.java

- Once we receive an authorisation code from the IPV authorize endpoint we can use that to make a call to the TokenEndpoint. Don't yet do anything with the token response.
- Create an IPVStubExtension to allow us to mimic the IPV token endpoint for the IntegrationTest.
- Add the IPV_AUTHORISATION_URI env var to the ipv-callback.tf which will actually be the base URL for IPV. This will be renamed going forward
- Generate a PrivateKeyJWT on the fly. This key will not be validated and we can eventually swap this out with a signing key in KMS but this will allow us to test our initial integration.
- So we have the ability to retrieve an Access token which will later be exchanged for the information we require.

GOVSI-1166 - Call IPV token endpoint with auth code

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java

- Once we have retrieved the AccessToken from the token endpoint then save it to Redis. Create a new prefix for the key of value `IPV_ACCESS_TOKEN:` along with the session-id which we will pull from the users cookie. Store the access token for 3 minutes.
- So we can use the access token later to retrieve the users information from IPV

GOVSI-1166 - Persist the AccessToken in Redis

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/AuthorisationResponseService.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationResponseServiceTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java

- Store the state query param used for IPV in Redis against a prefix and the session-id as we know we will have the session-id available to us from the cookie when we receive the response. This is stored for 60 minutes but will be overwritten if a new request is made in the session. 
- Validate the State in the IPV AuthorisationResponse
- Rename the AuthorisationResponseService to IPVAuthorisationService
- We send a state param in the authorization request to IPV. We expect the state param with the same value in the authorization response. A new state param is generated per request.
- We can use this state param to ensure that when we receive the authorization response from the intended source. If the state param has changed then it may mean that we are a target of a an attack as someone …

GOVSI-1166 - Store and validate state param for IPV journey

---

build.gradle

This pins transitive versions of Log4j to a more recent version

BAU: Force dependency resolution of Log4j2 to recent version

---

build.gradle

See https://aws.amazon.com/security/security-bulletins/AWS-2021-005/
`Customers using the aws-lambda-java-log4j2 (https://repo1.maven.org/maven2/com/amazonaws/aws-lambda-java-log4j2/) library in their functions will need to update to version 1.3.0 and redeploy.`

aws-lambda-java-log4j2 update

---

ci/terraform/oidc/ipv-callback.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java

- Add redirect_uri to the Token Request
- The Oauth server will perform validation to ensure the redirect_uri sent in the token request is the same as the redirect_uri sent in the auth request. We need to ensure we included the redirect_uri in the token request so the it can be properly validated.

GOVSI-1166 - Add redirect_uri to the Token Request

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidClaims.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidClaimsTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Validate the auth request for claims if they exist. If no claims exist then that is fine and they can carry on. 
- We will only return an error to the RP if there are claims present in the auth request and the claims present in the auth request do not match the claims supported
- If there are any claims in the authn request then we should validate them against the list of claims we believe will be supported in identity. These values can easily change depending on whether they are supported or not.
- The claim values will later be used in the authorization request sent to IPV.

GOVSI-1194 - Validate the auth request for claims if they exist

---

docker-compose.yml

Remove unused localstack services
Not using localstack for lambda and api gateway anymore so can remove.

BAU: remove unused localstack services

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/ipv-capacity.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/ssm.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/ssm.tf
ipv-api/src/main/java/uk/gov/di/authentication/ipv/domain/IPVAuditableEvent.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCapacityHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVCapacityService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCapacityHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVCapacityServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Add ipv-capacity handler endpoint and lambda.
- An api consumed by a service to determine whether or not IPV capacity is available.
- The handler reads a flag from an SSM variable to see if there is capacity.
Allows us to rate limit IPV checks according to supply.

GOVSI-1163: add ipv-capacity handler endpoint and lambda

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java

Update token handler log levels error -> warn
Client side errors (returning 400) should in general be logged as warn rather than error to reduce alert noise.

GOVSI-1230: update token handler log levels error -> warn

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java

Log updated session-id in authorisation handler.
The authorisation is where the session-id actually gets created so the session-id can change within the lambda itself.  Change session-id logging so that the session-id logged by the logging context is the session-id most recently allocated.
Old session-id were being logged when new ones had been created, so there was a difference between what was in the log messages and what was in the session-id field.

GOVSI-1106: log updated session-id in authorisation handler

---

build.gradle

Upgrade to log4j-2.17.0
Keep on the latest version.

BAU: upgrade to log4j-2.17.0

---

ci/terraform/account-management/redis.tf
ci/terraform/shared/redis.tf

- Explicitly configure the maintenance window for ElastiCache
- Unless stated, ElastiCache will assign you a random 60 minute maintenance window. It is better that we configure this value ourselves for a low traffic time and so we are aware of our own maintenance period.

AUTH-1179 - Explicitly configure the maintenance window for ElastiCache

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/LogEventMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/LogLineHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/PersistentIdHelperTest.java

Log aws request id and psid to logging context.
Use the aws request id to exclude smoke tester traffic from queries and reports.

AUTH-1253: log aws request id and psid to logging context

---

build.gradle

Include jaxb libs to suppress aws java sdk warning message:
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
Remove the messages from the logs.

GOVSI-1106: include jaxb libs to suppress aws java sdk warning message

---

ci/terraform/account-management/redis.tf
ci/terraform/shared/redis.tf

- Subscribe our Redis clusters to the alerts SNS topic
- Use the existing SNS topic in place so we can receive slack messages for any significant events that happen in ElastiCache. The list of events that we will get alerts for are all included here https://docs.aws.amazon.com/AmazonElastiCache/latest/mem-ug/ElastiCacheSNS.html
- This will let us know what is happening to our ElastiCache cluster and become aware if any downtime is caused by any ElastiCache events

AUTH-1262 - Subscribe our Redis clusters to the alerts SNS topic

---

.github/dependabot.yml
build.gradle
docker/localstack.Dockerfile

- Roll back from Localstack 0.13 to 0.12 as the former has issues running on M1 dev machines
- Configure dependabot to ignore any releases greater than or equal to 0.13
- Ensure the Gradle Docker Compose plugins triggers a docker image build before running tests (this ensures it picks up the currently configured image rather than using a cached, out of date, version when running locally)
There are issues running integration tests on the M1 dev machines using localstack 0.13+. 0.12 works fine.

BAU: Rollback to localstack 0.12.*

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/resources/log4j2.xml
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/LogEventMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/IpAddressHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/LogLineHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ClientSessionServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineJourneyTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/StateMachineTest.java

Put well-known fields like session id, client session id, etc, into the ThreadContext rather than directly into the message
Clean up log lines when searching

AUTH-1263: Use context-based logging in `shared` module

---

ci/terraform/shared/redis.tf
ci/terraform/shared/vpc.tf

- Add missing VPC endpoints for SQS, SNS, SSM and KMS
- Add security group to control ingress to VPC endpoints (allow all private subnet CIDR blocks)
- Add security group to control ingress to Redis (allow all private subnet CIDR blocks) and add to the Redis cluster (original security group to be removed later).
- Add security group to restrict lambda functions to just Redis and AWS VPC endpoints (but do not yet assign to anything)
- Add security group to allow egress as well as AWS endpoints and Redis (again, do not yet assign to anything)
We wish to control which lambda functions can can egress from the VPC. This PR sets up appropriate security groups, but does not yet switch the lambdas to the new groups. This will be done in a follow up PR.

AUTH-1128: Add VPC endpoints and security groups

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/sqs.tf
ci/terraform/shared/outputs.tf

In shared Terraform:
- Change existing security group output from default security group to new 'VPC resources only' group
- Add another output for the security group that allows egress
In OIDC Terraform:
- Pull in new egress allowed security group in `shared.tf` (the existing security group will pick up the changed 'VPC resources only' group).
- Assign the egress security group to the SQS queue processing lambda and the IPV Callback lambda as these both need to egress (all other lambda will pick up the change to the default security group).
We wish to restrict which lambdas can egress.
#1249

AUTH-1228: Assign Security Groups to Restrict Egress from VPC

---

ci/terraform/account-management/redis.tf
ci/terraform/account-management/vpc.tf

- Add missing VPC endpoints for SNS, KMS and SSM to account management VPC
- Add new security group for AWS VPC endpoints that allows incoming HTTPS from the private subnet
- Add new security group for Redis that allows incoming Redis connections from the private subnet
- Add the Redis security group to the Redis cluster
- Add new security group for Lambda that do not need egress (can use VPC endpoints and Redis)
- Add new security group for Lambda that do need egress (can talk to Redis and can make HTTPS to anywhere)
We wish to restrict the ability to egress from the VPC to only those lambda that need it. This PR puts the security groups in place, but does not assign the lamba, this will follow in another PR. 
(this PR is similar to #1249 which did the same for the OIDC API VPC)
#1249

AUTH-1228: Add VPC endpoints & new SGs to acct mgmt

---

ci/terraform/shared/vpc.tf

- Revert #1257 
- Set endpoint data source to retrieve the `Gateway` endpoint
It seems that using the S3 Gateway VPC Endpoint will be more seamless due to the Interface endpoint not providing private DNS. Currently, the Terraform is failing to apply in build, so lets revert to Gateway.
This has been tested with the audit processors in Sandpit and does work.
#1257 
#1256

AUTH-1228: Use S3 Gateway Endpoint

---

ci/terraform/shared/vpc.tf

- The warmers need to talk to the Lambda API, so we need to add that as a VPC endpoint.
The warmers are currently timing out as they can't contact the Lambda API, this results in our own API running very slowly which, in turn, is causing acceptance test failures.

AUTH-1228: Add Lambda VPC endpoint

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/authenticate.tf
ci/terraform/account-management/authoriser-warmer.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf

- Switch the SQS Notify lambda to the "egress allowed" group
- Switch all other lambda to "VPC only" group
We wish to restrict egress from the VPC to only those lambdas that need. We previous created the security groups in 
#1255, so we need to switch over.
#1255 
#1250 (this was the same change for the OIDC server VPC)

AUTH-1228: Switch account management lambdas to new security groups

---

ci/terraform/account-management/redis.tf
ci/terraform/account-management/vpc.tf
ci/terraform/shared/data-transfer.tf
ci/terraform/shared/redis.tf
ci/terraform/shared/vpc.tf

- Remove all usages of the default "allow all" security group.
Now all lambda, and other resources, have been assigned specific groups, we can remove references to the default security group as this is no longer required.

AUTH-1228: Restrict egress - cleanup

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java

- Add new ConsentRequired attribute to ClientRegistry 
- Default this flag to false as currently Consent isn't required for any Client in Production. It will only need to be true for the Stubs which I'll configure in a separate PR.
- This will be used to identify whether we need to display the consent screen for users of a particular client. Currently, we use the InternalService flag but as there will be clients in the future which are not internal and do not need to see the consent screen then we need a name flagged for this.
- Dynamo doesn't handle renaming Attributes that well in the SDK so we need to do this incrementally. Later on, we can then remove the InternalService flag

AUTH-1168 - Add new ConsentRequired attribute

---

ci/terraform/shared/stub-rp-clients.tf

- Set consentRequired to true for our Stub RPs
- The Stubs are currently the only clients where we need to display the consent screen too so ensure that there record in Dynamo is updated to reflect this following on the introduction of the ConsentRequired flag
- https://github.com/alphagov/di-authentication-api/pull/1287

AUTH-1168 - Set consentRequired to true for our Stub RPs

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java

- AUTH-1263: Log error message at creation of the response
- AUTH-1263: Remove unneeded logging in `account-management-api`
- AUTH-1263: Remove unneeded logging in `frontend-api`
- AUTH-1263: Remove unneeded logging in `ipv-api`
- AUTH-1263: Remove unneeded logging in `oidc-api`
Log error response within the creation of the response, rather than having inconsistent messages across the board.

AUTH-1263: Remove unnecessary logging

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/StateMachine.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/ConsentIsNotRequired.java
shared/src/test/java/uk/gov/di/authentication/shared/state/conditions/ConsentIsNotRequiredTest.java
shared/src/test/java/uk/gov/di/authentication/shared/state/journeys/ForgottenPasswordJourneyTest.java

- Switch code to use consentRequired field instead of isInternalService
- Add additional attribute named `identity_verification_required` to ClientRegistrationRequest to determine whether a client needs identity verification. It is not mandatory and if it is not present, it shall default to talse
- Make Service type optional in Client Reg request
- We want to start using the consentRequired field as it will not just be internal services where consent is not required. Eventually we will remove the internal service field completely
- Add the identity_verification_required attribute to the client registration request payload as an mandatory attribute. If this is set to true then consent is not required for users of that servcie and if it is set to false then consent is required for users of …

AUTH-1168 - Switch code to use consentRequired field instead of isInternalService

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java

- Remove InternalService attribute from client registry
- This attribute is no longer used and has essentially been replace with ConsentRequired as there are services which are not internal which don't require consent.

AUTH-1168 - Remove InternalService attribute from client registry

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/LevelOfConfidence.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Only support medium level of confidence
- To start with, we are only going to be supporting the medium level of confidence. We might want to support others in the future, so rather than remove them add an additional attribute to the enum on whether that loc is supported or not.

AUTH-1063 - Only support medium level of confidence

---

ci/terraform/oidc/auth-code.tf
ci/terraform/oidc/authorize.tf
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/ipv-capacity.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/vpc.tf

- Add a separate security group for accessing the Redis session store
in the `shared` Terraform deployment.
- Add the new security group ID as an output
- Add the new Redis security group to the Lambda that need to access
the OIDC sessions store
We are consolidating VPCs and moving where they are deployed to a separate Terraform. Currently, there is a rule associated with other the "VPC only" and "egress" security groups that allow access to Redis, however, these security groups are about to be moved.

AUTH-1292: Separate Security Group for OIDC Redis

---

ci/terraform/account-management/vpc.tf

- Add ECR and S3 VPC endpoints to account management VPC
- Add Cloudwatch VPC endpoint
Fargate needs ECR and S3 available in order to deploy services.

AUTH-1277: Add required VPC endpoints to acct mgmt for Fargate

---

ci/terraform/shared/vpc.tf

- Remove the egress rules allowing connection to Redis from the "vpc only" and "egress" security groups. 
In a #1308 we added a separate security group for this purpose and assigned it to relevant lambda functions.
#1308

AUTH-1292: Remove Redis security group rules

---

ci/tasks/deploy-shared-api.yml

- We have a new Terraform variable,`common_state_bucket`, we need to set this in the deploy task for the shared Terraform
The pipeline is failing due to the missing variable
#1311

AUTH-1292: Add common_state_bucket variable to deploy task

---

ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/spot-response.tf
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/variables.tf
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTResponse.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/SPOTCredential.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

- Create a SPOTResponse lambda which will read from an SNS topic, deserialize the message into the SPOTResponse object and write it to a Dynamo table. 
- Create a new Dynamo table named `spot-credential` which will hold the credential returned from SPOT. It will be stored against the Subject identifier, which we can extract from the access token (in a separate Lambda) to retrieve the credential. 
- Create a new Lambda role specific to the SPOTResponse lambda, so that Dynamo write permissions are limited to this lambda. We will set up a new role for the lambda required to read from this table. 
- The Dynamo table will be created in all environments but the lambda will only be created in environments where `ipv_api_enabled` is set to true. 
- So we can retrieve information from SPOT, …

AUTh-1315 - Create SPOTResponse lambda and new Dynamo table

---

ci/terraform/shared/dynamodb.tf
shared/src/main/java/uk/gov/di/authentication/shared/entity/SPOTCredential.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

- Use the dynamo TTL (time to live) to set when an item in the table is no longer needed. We will create a new attribute called TimeToExist and set that as the ttl. We will then set this in the DynamoSpotService to the same value as the access token expiry.
- Configure the DynamoDBMapperConfig with CONSISTENT reads. By default it is set to EVENTUAL. By setting this value DynamoDB should return a response with the most up-to-date data, reflecting the ttl attribute which we have set.
- Because the data in the SPOT table should only be accessible for the time the access token is valid for.

AUTH-1315 - Set TTL on Dynamo table

---

account-management-api/build.gradle
account-management-integration-tests/build.gradle
account-migrations/build.gradle
audit-processors/build.gradle
build.gradle
client-registry-api/build.gradle
frontend-api/build.gradle
integration-tests/build.gradle
ipv-api/build.gradle
lambda-warmer/build.gradle
oidc-api/build.gradle
shared-test/build.gradle
shared/build.gradle

We want to pull dependencies from the artifactory cache rather than directly from Maven central or gradle

AUTH-1208: Pull dependencies from Artifactory instance rather than Maven Central

---

ci/terraform/oidc/identity.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IdentityIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AccessTokenInfo.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/IdentityHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/IdentityHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/exceptions/AccessTokenException.java

- Add terraform and bones of the identity lambda which will just return a 204 for now. Restrict deployment to non-prod via the var.ipv_api_enabled flag. 
- Rename the UserInfoValidationException to AccessTokenException to make it more generic so it can be used for the identity endpoint
- Move the parsing of the access token from the UserInfoService into a new AccessTokenService. This is so this code can easily be shared across UserInfo and Identity endpoints.
- Create a new AccessTokenInfo object which will be returned from the AccessTokenService. This is to prevent the need to parse the Access token again and so the information required for both UserInfo and Identity endpoints can easily be passed around.
- Stop deleting the accesstoken after it has been used. 
- We need an identity …

AUTH-1314 - Create bones of identity lambda and refactor UserInfo service

---

ci/terraform/oidc/identity.tf
ci/terraform/oidc/lambda-roles.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IdentityIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/IdentityErrorResponse.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/IdentityResponse.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/IdentityHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/IdentityService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/IdentityHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SPOTStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

- Parse the access token in the IdentityHandler
- Return Identity response from Identity lambda which is populated from the SPOT table 
- Create a IdentityErrorResponse which will be returned to the RP in the case of an error. This is more or less the same as the UserInfoErrorResponse
- Add a SPOTStoreExtension for the Integration test
- Restrict permissions to the Identity lambda for reading from the SPOT table
- Give the SpotResponse lambda the permissions to write to the SPOT table. (The permissions were created in a previous PR but never assigned)
- So the identity lambda can validate an access token and return the required identity information to the RP

AUTH-1314 - Add functionality to the Identity lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IdentityIntegrationTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/IdentityService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/IdentityHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/IdentityServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SPOTStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/SignedCredentialHelper.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

- Delete identity credential after use
- Add missing tests for the IdentityService
- Create a new Helper for generating a Signed Credential
-  The Identity credential can only be used once, therefore once we have received it from Dynamo we should make sure we delete it.

AUTH-1314 - Delete identity credential after use

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- When OIDCClaims exist in the access token and there is a level of confidence in the client session, we can be confident that this request requires identity so we need to stick this OIDCClaims in the access token. They will be present under the 'claims' claim
- The 'claims' claim will only ever be present on the first access token which is issued. For RPs which use refresh tokens, any further access tokens issued will not contain the 'claims' claim as these access tokens are created based on what is in the refresh tokens. As the refresh tokens will never be populated with the 'claims' claim, then no further access tokens will either. Only the first initial access token.

AUTH-1314 - Place OIDCClaims in the AccessToken when required

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/NotificationServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/NotificationType.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/TemplateAware.java
shared/src/main/java/uk/gov/di/authentication/shared/services/NotificationService.java

Each `NotificationType` constant knows its template environment variable, and corresponding value of the lookup. We don't need a separate method to look those up.
This pushes that knowledge into the `NotificationType` enum and adds a `TemplateAware` interface to make testing interactions simpler by removing the need for a `System.getenv()` call.

BAU: Refactoring 202220128 (`NotificationType`)

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/LevelOfConfidence.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/CredentialTrustLevelTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Update loc values to be numeric
- Our level of confidence values are currently ‘Pl’, ‘Pm’, ‘Ph’ and ‘Pv’. This is being changed to P1-P4 for low/medium/high/very high.

AUTH-1344 - Update loc values to be numeric

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java

- Add identity endpoint to oidc wellknown API
- This is so RPs will know the endpoint to request identity credentials

AUTH-1343 - Add identity endpoint to oidc wellknown API

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

- Send the blocked WAF requests to cloudwatch so we can monitor and track such requests.
- When the WAF blocks a request, we can only view it up to 3 hours after in the AWS console. This isn't ideal if we receive blocked requests during the night or at the weekend, as they would have disappeared by the time we come to look for them.
- We want the logs in the new Log group to send to Splunk. To do this we require a aws_cloudwatch_log_subscription_filter for each new log group

AUTH-1290 - Ship blocked WAF requests to cloudwatch

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java

Pass the `customer-support-link` personalisation variable to more of our Notify templates.
We are going to update several templates to include this link at the bottom, so that customers know how to give us feedback.

AUTH-1281: Add customer support link for Notify templates

---

ci/terraform/oidc/sqs.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Create new configuration for the contact-us route.
Update NotificationHandler to send the contact-us-link to the account create, email confirmation and password reset templates in frontend api.
The contact-us route is separate from the support route and goes to a different page.
Three templates need to be updated to link to the contact-us page.
#1367

AUTH-1281: create new configuration for the contact-us route

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/NotificationHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/NotifyIntegrationTest.java

Remove unused notify template variable and update the tests to reflect the change.
An updated version of the account confirmation template was deployed which uses a different variable.  The existing one was kept in temporarily for a ZDD.
#1368 
#1367

AUTH-1281: remove unused notify template variable

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/IdentityHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TrustMarkHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PhoneNumberHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestBodyHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/RequestHeaderHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/ClientDoesNotRequireMfa.java
shared/src/main/java/uk/gov/di/authentication/shared/state/conditions/ConsentNotGiven.java

Reduce `error` to `warn` where the problem is caused by user input.
We want to have separate measurements for errors on our end, and errors caused by things like malformed input.

AUTH-1230: Reduce `error` to `warn` for user input issues

---

.github/dependabot.yml

Remove dependabot open pull requests limit
So we can see all the available pull requests the dependabot has to offer.

BAU: remove dependabot open pull requests limit

---

build.gradle
lambda-warmer/build.gradle

Merge 3 AWS SDK library updates created by dependabot.
So they can be released/rolled-back together.
#1380 
#1379 
#1378

BAU: AWS SDK libs dependabot merge

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/variables.tf
ci/terraform/oidc/verify_code.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Add separate configuration for blocked email/account locking duration.
Set this value to 30s in the build environment only.
At the moment there is a single configuration key that covers both how long an otp is valid for, and for how long an account is locked as required, such as when a user requests too many otp codes.  These are actually separate things even though they happen to have the same value at the moment.
As this value is set to 15 mins it makes it difficult to test that account locking is working correctly, given it takes at least 15 mins to run a single test.  The idea is to be able to set this value to something much lower in test environments to make it easier to test.  We might want separate durations for otp validity and account locking to make testing as efficient as …

AUTH-1355: add separate configuration for blocked email duration

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/outputs.tf
echo-int-test-vars.sh

- Remove unused API key
- This API key is not used and can therefore be removed.
- We only use the di_auth_frontend_api_key which lives in api-gateway-frontend.yml.

BAU - Remove unused API key

---

build.gradle

Update google-java-format from 1.12.0 to 1.13.0
Spotless was refusing to run locally for me because this dependency was not up to date.

BAU: Update google-java-format from 1.12.0 to 1.13.0

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/update.tf

- Create a 2 new Lambda role which will be used by the 2 client registration lambdas UpdateClientConfigHandler and ClientRegistrationHandler. These Lambdas only require the KMS signing policy and Lambda SNS policy as part of the audit and also a new dynamo_client_registry_write_policy.
- Create a new policy called dynamo_client_registry_write_policy which will only give the UpdateClientConfigHandler and ClientRegistrationHandler permissions to the Client Registry table. Before the had access to the user tables which they did not need.
- Move Dynamo policies into a separate file as it was getting too big
- Remove localstack condition on IAM policies
- To give lambas permissions to the things they need

AUTH-1174 - Create separate lambda role for the Client Registry lambdas

---

ci/terraform/oidc/authorize.tf
ci/terraform/oidc/dynamo-policies.tf

- Limit the permissions given to the authorize lambda but creating a new role specific to it.
- Create new policies for read access to the client registration and user tables. The majority of the lambdas only need READ access.
- Authorize had a lot of permissions which it didn't require. Ensure that we only give it the permissions that the Authorize lambda requires.

AUTH-1174 - Create new Lambda role for authorize

---

ci/terraform/oidc/identity.tf
ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/ipv-capacity.tf
ci/terraform/oidc/jwks.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/spot-response.tf

- Create separate lambda roles for the IpvCallback, IpvAuthorize, IpvCapacity and JWKs lambdas. 
- Move the roles of the Identity and SpotResponse lambdas alongside the Lambda 
- Give the IPV Lambda roles a consistent naming convention 
- So we only give the Lambdas the permissions that they need
- So the naming is consistent

AUTH-1174 - Create separate lambda roles 

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/logout.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/trustmarks.tf

- Create new roles for the Login, Logout, Trustmarks and Signup lambda.
- Create a new write only policy for the User tables
- So we give the lambdas only the permissions they require.

AUTH-1174 - Create new role per lambda

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/identity.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/token.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf

- Restrict Token lambda to just read dynamo permissions 
- Create new roles for the UpdateProfile, UserExists and UserInfo lambdas
- Give the Identity lambda role the correct permissions
- The token lambda will only need to read from Dynamo so we can remove it's permissions to write
- We can restrict permissions each lambda is given by assigning a role for each lambda 
- The identity lambda was previously missing permissions and had permissions to dynamo that it did not require

AUTH-1174 - Create a role per lambda

---

ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/lambda-roles.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/sqs.tf

- Create new lambda role for Send Notification, MFA, Reset Password Request and Reset Password lambdas. 
- All roles are the same except Reset Password which has additional permissions to write to the User tables in dynamo as it will be updating the passwords. 
- Ensure that each of the new roles has been added as an identifier to the email_queue_policy_document so it has permissions to write to the SQS queue
- Delete the oidc_sqs_role and oidc_dynamo_sqs_role as these are no longer used.
- Rename lambda-roles.tf to kms-policies.tf as it is now a more accurate representation of what it represents
- So we only give the lambdas the permissions they require

AUTH-1174 -  Create a role for each lambda which talks to SQS 

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/identity.tf
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf

- There was some crossover between the different dynamo policies for the client reg table. Have one policy for writing and one policy for reading. 
- Add missing env var to the identity lambda 
- Remove unused dynamo policy 
- Make dynamo policies clearer and explicit

AUTH-1174 - Tidy up dynamo policies 

---

build.gradle
docker-compose.yml
frontend-api/build.gradle
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeRequestHandlerTest.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/ApiGatewayHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/CloudwatchMetricsExtension.java
shared/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java

This PR adds the capability for a handler, through `CloudWatchMetricsService`, to publish metrics into CloudWatch for analysis and dashboards
We get a lot of platform/infrastructure-level metrics in CloudWatch for "free" but anything that's specific to our domain needs to be pushed by us.

AUTH-1357: Publish product-level metrics to CloudWatch

---

ci/terraform/account-management/alerts.tf
ci/terraform/oidc/alerts.tf

- Switch off WAF blocked requests cloudwatch alarms
- 
- We are not currently utilising these and they are creating a lot of noise. Switch them off until we decide how we can best make use of them

BAU - Switch off WAF blocked requests cloudwatch alarms

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/variables.tf

Add missing notify personalisation in am verify email payload.
The variable name in the template was updated due to code changes in frontend, but changes were not applied to am too.

BAU: add missing notify personalisation in am verify email payload

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/variables.tf

Add missing notify personalisation in am verify email payload.
The variable name in the template was updated due to code changes in frontend, but changes were not applied to am too.

Revert "BAU: add missing notify personalisation in am verify email payload"

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java

- Previously we wasn't handling when no query string parameters are present in the auth request so it was just throwing a nullpointer. We should catch the exception when this occurs and log a relevant error message
- So exceptions are handled and it is clear in the logs why they are thrown

BAU - Handle when no query string params are present in auth request

---

oidc-api/build.gradle

Pull in AWS SDK libraries at runtime
Shrink the size of the deployable jar.

BAU: AWS provides SDK libraries at runtime, do not bundle

---

ci/terraform/oidc/verify_code.tf

Grants the `cloudwatch:PutMetricData` permission to the verify code lambda
It needs this to push data to Cloudwatch

AUTH-1357: Grant permissions for verify_code lambda to push metrics

---

integration-tests/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/logging/LogEventMatcher.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java

This PR removes the feature toggle, enabling the change for all versions of the lambda, and also enables the cloudwatch service to catch-and-continue if there are any exceptions thrown.
Metrics are a good indicator but are not full-fidelity, that is what the audit stream is for.

AUTH-1357: Remove CloudWatch metrics feature toggle

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml
ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml

- Rename the `api-src` input on all deployment tasks to `api-terraform-src`, this will bring it in line with what the resource is called in the main pipeline so we don't need to do any input mapping.
We altering the pipeline and the terraform files will no longer be pulled from the Github release, it will come from its own resource called `api-terraform-src`.
https://github.com/alphagov/di-infrastructure/pull/176

AUTH-1293: Rename the terraform input on deployment tasks

---

ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml
ci/terraform/account-management/shared.tf
ci/terraform/audit-processors/shared.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/ipv-capacity.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/code-signing-config.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/variables.tf

- Add a Lambda Code Signing Config (CSC) to the shared Terraform.
- The allowed_publisher will be passed in as a variable from the pipeline (this will be signing profile from the `di-tools-prod` account).
- The allowed public in the sandpit shall be the signing profile form `di-tools-dev` account).
- Add the ARN of CSC to the shared Terraform outputs, to be used by the other API terraforms.
- Add a variable to the endpoint module to take an, optional, CSC to apply to the lambda. Default should be `null`.
- Pass the CSC ARN to the IPV API lambdas
- Update how the IPV API filename is determined, in the deploy task, as the filename won't be fixed when we switch to the AWS signed bucket. The release ZIP file will be the ONLY ZIP file in the S3 bucket resource.
By adding a code signing …

AUTH-1293: Add code signing config

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/terraform/account-management/authenticate.tf

- Enable code signing on the authenticate lambda function.
We are moving away from Github releases signed by GPG to deploying via S3 using AWS signer.
N.B. This should break the pipeline until the below is merged
https://github.com/alphagov/di-infrastructure/pull/179

AUTH-1293: Enable code-signing on the AM authenticate lambda

---

ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf

- Add code signing configuration to all remaining lambda in the account management API.
We have added, and tested, the code signing configuration against the authenticate lambda, lets add to all remaining lambda.
N.B. we are excluding the warmers, for the time being, until pipeline changes have been made to support that.
#1437

AUTH-1293: Add code signer configuration to all AM API Lambda

---

ci/terraform/audit-processors/sandpit.hcl
ci/terraform/audit-processors/sandpit.tfvars
ci/terraform/modules/dns/dns.tf
ci/terraform/shared/sandpit.tfvars

- Use correct DNS names for Fargate applications
- Ensure stub clients created for sandpit
Sandpit deployments not working properly since the migration to Fargate, also, we need some stub RP creds for the apps in PaaS.

BAU: Fix sandpit deployment

---

ci/tasks/deploy-audit-processors.yml
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/performance_analysis.tf
ci/terraform/audit-processors/storage.tf

- Add AWS code signing configuration to each of the audit lambda  functions
- Change the way in which the deployment job determines the filename  for the audit lambda ZIP file, when using AWS Signer the filename is  not consistent. It will be the only ZIP file in the release  directory though.
We are moving from Github releases and GPG code signatures to S3 buckets and AWS Signer.
https://github.com/alphagov/di-infrastructure/pull/180

AUTH-1293: Add code signing configuration to Audit lambda

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/register.tf
ci/terraform/oidc/update.tf

- Add AWS code signing configuration to each of the client registry API lambda functions
- Change the way in which the deployment job determines the filename for the lambda ZIP file, when using AWS Signer the filename is not consistent. It will be the only ZIP file in the release directory though.
We are moving away from Github releases and GPG signing to S3 and AWS signer
https://github.com/alphagov/di-infrastructure/pull/181

AUTH-1293: Add code signing configuration to client registry API

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/client-info.tf
ci/terraform/oidc/login.tf
ci/terraform/oidc/mfa.tf
ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/verify_code.tf

- Add AWS code signing configuration to each of the frontend API lambda functions
- Change the way in which the deployment job determines the filename for the lambda ZIP file, when using AWS Signer the filename is not consistent. It will be the only ZIP file in the release directory though.
We are moving away from Github releases and GPG signing to S3 and AWS signer
https://github.com/alphagov/di-infrastructure/pull/182

AUTH-1293: Code signing for frontend API

---

ci/terraform/oidc/auth-code.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
oidc-api/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java

This attaches a field, `is_new_account`, to `Session`.
It allows us to tag whether a successful login is from a new or existing account

BAU: Attach whether an account is new or not to sessions

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java

This will let us exclude test clients from graphs

BAU: Attach client id to metrics

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/SignUpResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java

- Return consentRequired from SignUp
- When a client requires consent and a is registering for the first time, we need to tell the frontend to show the consent screen. Currently there is no way for the frontend.

BAU - Return consentRequired from SignUp

---

ci/terraform/oidc/client-info.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ClientInfoHandlerTest.java

- The ClientInfo lambda was renamed to Start as part of the state machine changes.
- This was fine when deploying to sandpit and build but terraform state got confused when deploying to integration. To avoid this happening in Production, re-add the ClientInfo terraform and point it to a very simple ClientInfoHandler which just returns a 204.
- Once everything is ok we can revert this PR to remove it. 
- To prevent issues with deploying the Start lambda in Production.

BAU - Re-add the client info terraform

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePasswordIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java

Add integration tests for UpdatePasswordHandler
Adds missing test coverage.
In particular, please check that I'm using the correct terminology in the second commit.

AUTH-1169: Add integration tests for UpdatePasswordHandler

---

shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBSchemaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

Use dynamo transactions for remove account.
- Make remove account atomic using the dynamo db transactions api.
- Some refactoring of schema data to simplify the DynamoService and make using the transactions api easier.
Removing an account means removing an item from two separate tables.  If one remove fails then the database is left in an incorrect state and the application fails when the user tries to login.
https://github.com/alphagov/di-authentication-api/pull/1431

AUTH-1397: use dynamo transactions for remove account

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PhoneNumberHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Add support for international numbers for both sign-ups and account management. If a number is not prefixed with a +, then we assume that it is a British number.
- So we can start supporting users with international phone numbers.

AUTH-1364 - Add support for international numbers

---

ci/tasks/deploy-oidc-api.yml

- Remove the use of a generated shell script to set the, no longer used, `AM_URL` environment variable. 
This was originally implemented inline with the way we got this value when we deployed the PaaS apps, but we now get this value using a `terraform_remote_state` data source.
https://github.com/alphagov/di-infrastructure/pull/200

AUTH-1839: Remove use of generated env file as no longer used

---

ci/tasks/deploy-delivery-receipts-api.yml
ci/terraform/delivery-receipts/api-gateway.tf
ci/terraform/delivery-receipts/core.tf
ci/terraform/delivery-receipts/notify-callback.tf
ci/terraform/delivery-receipts/outputs.tf
ci/terraform/delivery-receipts/s3-objects.tf
ci/terraform/delivery-receipts/sandpit.hcl
ci/terraform/delivery-receipts/sandpit.tfvars
ci/terraform/delivery-receipts/shared.tf
ci/terraform/delivery-receipts/site.tf
ci/terraform/delivery-receipts/ssm.tf
ci/terraform/delivery-receipts/variables.tf
delivery-receipts-api/build.gradle
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/DeliveryMetricStatus.java
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/NotifyDeliveryReceipt.java
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/main/resources/log4j2.xml
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
settings.gradle
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

**Code changes**
- Create new module for DeliveryReceipts which will contain a lambda which will receive delivery receipts from Notify. We are currently only interested in SMS delivery receipts.
- Validate the bearer access token and parse the response from Notify. We will then send this response to CloudwatchMetrics
- The metric name will either be SMS_FAILURE or SMS_DELIVERED. The country code will be stored in the dimensions so will be accessible
**Terraform changes**
- Create a new terraform directory and create a new API to handle the Notify Delivery Receipts.
- Generate a bearer access token and store that encrypted in parameter store.
- Do not deploy the warmers as it asynchronous and will have little benefit
- Create a new task for deploying the delivery-receipts-api
- We want to …

AUTH-1412 - Create new lambda and API for handling Notify delivery receipts callback

---

ci/tasks/deploy-delivery-receipts-api.yml
ci/terraform/delivery-receipts/production-overrides.tfvars

- Add override files for integration and production
- Remove the sizing.tfvars from the deploy task as we don't require redis
- Required to deploy to integration and prod 
- We will not be deploying to build so do not require a build overrirde files

AUTH-1412 - Add override files for integration and production

---

ci/terraform/delivery-receipts/notify-callback.tf

- Add cloudwatch metric policy to notify callback lambda
- Requires permissions to publish metrics to cloudwatch

AUTH-1412 - Add cloudwatch metric policy to notify callback lambda

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java

- Add a `salt` value to the `UserProfile` object
- Use this `salt` when generating the pairwise subject ID rather than system wide salt
- If the user salt is not populated then generate a new random, 32-byte, salt and add to profile.
- Ensure that new salt is saved to user profile once generated
- Add missing integration tests to Token endpoint to prove correct generation of pairwise and public subject IDs
- Add new integration test for `DynamoService` to check that `getOrGenerateSalt()` works correct and stores the correct value in Dynamo
We should a per user salt rather than a system wide salt to limit the blast radius should a salt get leaked.

AUTH-1410: Per user salt for pairwise subject IDs

---

ci/terraform/shared/stub-rp-clients.tf

- Update stub client registrations to be `pairwise` rather than `public`
Clients other than internal clients should be `pairwise` rather than `public`
#1502

AUTH-1410: Make stub clients use pairwise IDs

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/token.tf

- Add write permissions to user profile table to `token` and `ipv-callback` endpoints.
The token endpoint is failing as it can't write the `salt` field to the user profile table.
#1502

AUTH-1410: Grant permission to write salt to user profile

---

shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenValidationServiceTest.java

This makes the public key id provided in the `jwks.json` endpoint opaque rather than the value we get from the cloud provider.
The underlying public key might change so providing an alias is no good, and hashing the key id gives a distinct identifier for the actual public key.

AUTH-1477: Provide opaque signing key id

---

integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/JwksHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenValidationServiceTest.java

Attach opaque id to signed tokens rather than internal name
This fixes a regression with a previous PR

AUTH-1177: Use opaque id in signed token headers rather than alias

---

.github/workflows/pre-merge-checks.yml
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
delivery-receipts-integration-tests/build.gradle
delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java
scripts/functions.sh
settings.gradle

- Return Void from the NotifyCallbackHandler
- Add Integration tests for the NotifyCallbackHandler
- The NotifyCallbackHandler is asynchronous and therefore the return type can be Void. This is to prevent the Malformed Lambda proxy response showing in the logs
- To increase test coverage

AUTH-1412 - Return Void from the NotifyCallbackHandler

---

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java

Return a formatted APIGatewayProxyResponseEvent to silence the errors
- We are still seeing Malformed Lambda proxy response in the logs. It seems the best way to silence these is to return a formatted APIGatewayProxyResponseEvent response.

AUTH-1412 - Return a formatted APIGatewayProxyResponseEvent to silence the errors

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/RequestParameters.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UserStartInfo.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RequestParameters.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorizationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuthorizationServiceTest.java

- Return cookie consent and ga cross tracking ID from start
- Remove cookie consent and ga tracking ID logic from authorize
- Authorize contains a lot of logic which makes it difficult to understand what it is doing. We can simplify logic by moving the CookieConsent and the GATrackingID to the Start lambda.

AUTH-1416 - Move CookieConsent and GaTrackingId logic to Start lambda

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java

- Only publish "NewAccount" when phone code is verified
- Update session state to "EXISTING" once "NEW" account has sent an auth code at least once

BAU: Metrics tweaks

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/queuehandlers/NotificationHandlerIntegrationTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/NotificationHandlerIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ConstructUriHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ConstructUriHelperTest.java

- Allow the ConstructUriHelper to accept query params and add unit tests 
- Add referer query param onto the contact-us link in the support emails
- Add the contact-us-link to the account management emails
- Where we are using the `customer-support-link` keep that alongside the `contact-us-link` for now to avoid any issues with the emails. 
- So the support emails all have the same link 
- So we can track what email the user clicks the support link from

AUTH-1366 - Make support links consistent

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
ci/terraform/account-management/sqs.tf
ci/terraform/account-management/variables.tf
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Remove support links as these are no longer used
- All emails now use the contact-us-link

AUTH-1366 - Remove support links as these are no longer used

---

delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/DeliveryMetricStatus.java
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java

- Account for Notify sent status
- Mobile networks in some countries do not provide delivery information for SMS. In these cases the status we will receive is sent. We will map this to SMS_UNDERTERMINED as we have no sight on whether it has successfully been delivered or not.

BAU - Account for Notify sent status

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java

- Remove email validation from ResetPasswordRequestHandler
- This will only be called by users which already have an account and a validated email. There is no opportunity for a user to insert a new email address and therefore we can remove this bit of validation

AUTH-1480 - Remove email validation from ResetPasswordRequestHandler

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Allow validation of codes from the `RESET_PASSWORD_WITH_CODE` notification type
- Add specific `ErrorResponse` value for the password reset code errors.
- Refactor ValidationService email code unit tests to be parameterisable including MFA and phone number verification codes.
- Add scenarios for the new `RESET_PASSWORD_WITH_CODE` notification
type.
#1532

AUTH-1439: Update code validation service to support e-mail codes

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/UpdateProfileHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBItem.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBSchemaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientConsent.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/TermsAndConditions.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserCredentialsTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserProfileTest.java

Use DynamoDB transactions for update email.
Use transactions to maintain database integrity given that deletes and creates are required in two separate tables for the operation to succeed.
DynamoDB mappers only support transactions on a single table if table overrides are in use.  This means using a different api which requires converting fields to AttributeValue in order to use transactions.
#1479

AUTH-1397: use DynamoDB transactions for update email

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/CheckUserExistsHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ValidationService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ValidationServiceTest.java

- Move email validation to ValidationHelper
- Remove phone number validation out of UpdatePhoneNumberHandler
- We can avoid the need to instantiate the ValidationService by moving the email validation into static methods. We shouldn't to create an instance of a class to call them
- The SendOtpNotificationHandler is called before the UpdatePhoneNumberHandler and we validate the phone number there. We don't need to perform the same validation in both lambdas

AUTH-1480 -  Validation refactor

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java

- Add an, optional, field to the `ResetPasswordRequest` class to indicate whether the reset password should done with a 6 digit code rather than a magic link
- Update `ResetPasswordRequestHandler` to check the new field and behave appropriately
We are moving to a flow where a 6 digit code will be sent to the user when they request a password reset rather than a link. This makes it easier for the user to continue their RP journey after resetting their password.
With this change in place, the API changes for sending a 6 digit code in the reset password flow is complete. The frontend will just need to include the additional flag in the API call to use this flow.
No changes are required to `ResetPasswordHandler` as this will work for both flows.
*N.B. for the moment, the API will support both …

AUTH-1439: Add ability to trigger code flow password reset

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/AuthCodeExchangeData.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthorisationCodeService.java

- Save client session in auth code store
- Save the client session in the auth code store so we don't have to make multiple calls to REDIS in the token handler.
- These changes will be done incrementally to avoid any drop offs for users

BAU - Save client session in auth code store

---

ci/terraform/oidc/production-overrides.tfvars
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java

- Read client session from auth code store
- Increase lambda warmers to 50
- To avoid calling redis twice 
- To speed up our lambdas

BAU - Retrieve client session from auth code store and increase lambda warmers 

---

account-migrations/build.gradle
frontend-api/build.gradle
oidc-api/build.gradle
shared/build.gradle

- Remove Notify and client reg dependency from OIDC api
- AWS provides SDK libraries at runtime so we don't have to include these in the bundle
- These dependencies are not used and can be removed to reduce the size of the package

BAU - Remove Notify and client reg dependency from OIDC api

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ResetPasswordCompletionRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java

- Rename `ResetPasswordWithCodeRequest` to `ResetPasswordCompletionRequest` (as going forward the code won't be included).
- Make `code` optional.
- Update `PasswordResetHandler` to work without a provided code. This will be used in the journey when a user is sent a six-digit code rather than a link.
- When issuing a 6 digit code for password resets, save using the OTP save method, so it can be verified by the `VerifyCodeHandler` (which requires this).
These are further changes required to enable the reset password with code and continue journey.
#1532 
#1536 
#1542

AUTH-1439: Reset password refactor

---

account-management-api/build.gradle
account-migrations/build.gradle
audit-processors/build.gradle
client-registry-api/build.gradle
delivery-receipts-api/build.gradle
frontend-api/build.gradle
ipv-api/build.gradle
oidc-api/build.gradle

- AWS provides SDK libraries at runtime so we don't have to include in this bundle
- Reduce package size

BAU - AWS provides SDK libraries at runtime so we don't have to include in this bundle

---

client-registry-api/build.gradle
delivery-receipts-api/build.gradle
ipv-api/build.gradle
oidc-api/build.gradle
shared/build.gradle

- Use compile only for shared
- AWS provides SDK libs at runtime so we can bring the package size down by not including these.

BAU - Use compile only for shared

---

build.gradle
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/outputs.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/outputs.tf
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/TokenSigningExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Give the IPVCallbackHandler the right permissions to the KMS key
- Sign the PrivateKeyJWT using KMS
- We will authenticate to the IPV token endpoint using PrivateKeyJWT. We will sign this using an EC key provided by KMS

AUTH-1213 - Sign IPV PrivateKeyJWT using KMS

---

ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/spot-sqs.tf

- Create a SQS and DLQ for sending requests to SPOT. This queue will be called by the IPVCallbackHandler.
- Add the ipv_callback_role as an identifier for the spot_request_queue_policy
- Update sandpit.tfvars with IPV values.
- We are going to use SQS to send requests to SPOT. We will own the queue for the requests and SPOT will own the queues for the responses.

AUTH-1501 - Create SQS and DLQ queues for SPOT requests

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java

- Add extra logging to AccessTokenService. 
- To help debug `Error getting AccessToken from Redis` errors

BAU - Add extra logging to AccessTokenService

---

ci/terraform/account-management/staging-sizing.tfvars
ci/terraform/shared/staging-sizing.tfvars
ci/terraform/shared/staging-stub-clients.tfvars

- Add Terraform override and sizing files for the staging environment. These should match the current integration values.
We are adding a staging environment to integration test with the other components of GOV.UK Sign in
https://github.com/alphagov/di-authentication-frontend/pull/559
https://github.com/alphagov/di-authentication-account-management/pull/400
https://github.com/alphagov/di-infrastructure/pull/216

AUTH-1427: Add overrides and sizing files for staging

---

ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/variables.tf
ci/terraform/shared/variables.tf

- Switch the default value of ipv_api_enabled to false so IPV is disabled by default
- Make the IDENTITY_ENABLED use the ipv_api_enabled var, so that these feature flags are consistent
- To disable IPV in all environments unless specified as we only want to enable it in our new staging env for the time being
- So that there is a single identity feature flag which is used by both terraform and the application

AUTH-1347 - Keep identity feature flags consistent

---

ci/terraform/oidc/ipv-callback.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/testsupport/helpers/SpotQueueAssertionHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/testsupport/matchers/SpotRequestMatcher.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/LogIds.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTClaims.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTRequest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java

- Based on what we know now and what is documented in this RFC https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0013-spot-request-response-structures.md, form the SPOT request payload.
- So we can send the relevant information to SPOT

AUTH-1347 - Send the necessary information in SPOT payload

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml
ci/tasks/deploy-delivery-receipts-api.yml
ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml
ci/terraform/account-management/sandpit.tfvars
ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/account-management/variables.tf
ci/terraform/audit-processors/sandpit.tfvars
ci/terraform/audit-processors/staging-overrides.tfvars
ci/terraform/audit-processors/variables.tf
ci/terraform/delivery-receipts/sandpit.tfvars
ci/terraform/delivery-receipts/staging-overrides.tfvars
ci/terraform/delivery-receipts/variables.tf
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/sandpit.tfvars
ci/terraform/shared/staging-sizing.tfvars
ci/terraform/shared/variables.tf

- Remove setting of `logging_endpoint_enabled` in the pipeline tasks
- Make the default value for `logging_endpoint_enabled` true in Terraform deployments
- Override to `false` in the staging and sandpit environments in Terraform deployments
There is, currently, an issue setting up centralised logging for the Staging account, lets disable it for the mo to allow us to move forward with the environment setup.

AUTH-1427: Temporarily disable Splunk in staging

---

ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/audit-processors/staging-overrides.tfvars
ci/terraform/delivery-receipts/staging-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/shared/staging-sizing.tfvars

- Remove the override flag to re-enable the Splunk CSLS filter for the staging environment.
The issue with the staging account not being permitted has been resolved.
#1592

AUTH-1427: Re-enable Splunk subscriptions for staging

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTResponse.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTStatus.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

- We will be receiving SPOT responses via an SQS queue. This changes our SPOTResponseHandler to listen to an SQS queue instead of an SNS topic.
- We are currently assuming only one credential will be present when the status is OK.
- Use UTC for PrivateKeyJWT in integration test
- Change the structure of the SPOT response based on the RFC - https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0013-spot-request-response-structures.md
- The token integration test was failing as the clocks moved forward on Sunday. We need to be explicit and use UTC

AUTH-105 -  Change SpotResponse lambda to read from SQS 

---

ci/terraform/shared/kms.tf

- Add the `kms:ReEncrypt*` and `kms:GenerateDataKey*` actions to the cloudwatch policy.
It seems that these permissions are now required to encrypt cloudwatch logs.

AUTH-1427: Add missing permissions for Cloudwatch

---

ci/terraform/delivery-receipts/notify-callback.tf
ci/terraform/delivery-receipts/variables.tf

- Add new variable `endpoint_memory_size` to Terraform (default 4096)
- Pass this value to endpoint module
- Override the value to 3008 for staging environment
Not all environments need to have 4GB allocations. This was missed from earlier RP
https://github.com/alphagov/di-authentication-api/pull/1603

AUTH-1427: Parameterise memory size for delivery-receipts API

---

ci/terraform/delivery-receipts/staging-overrides.tfvars

- Set `endpoint_memory_size` to 3008 in staging environment.
Missed from earlier PR
#1605

AUTH-1427: Override delivery-receipts memory size in staging

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/ipv-callback.tf

- Move the IPV Callback endpoint to the OIDC API Gateway
This should be on the OIDC API as this interacts directly with the user agent (unlike the other IPV related handlers). The frontend API should never be hit by anything other than the frontend.

AUT-111: Move IPV Callback Handler

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Create a new configuration value to store the IPV token endpoint and keep this separate from the IPV Authorisation endpoint
- Remove injection of non-secret values from CI task, use override files and default values instead.
- Add a new Terraform variable for IPV token endpoint 
- Inject new `IPV_TOKEN_URI` environment variable to IPV Callback endpoint.
We need to handle these separate as, currently, these endpoints are not on the same host. Plus, there are multiple options for the `authorize` endpoint in staging so, simply, appending `/authorize` to a base URL doesn't work.

AUT-111: Configure IPV endpoints separately

---

ci/terraform/account-management/staging-overrides.tfvars
ci/terraform/audit-processors/staging-overrides.tfvars
ci/terraform/delivery-receipts/staging-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Increase the memory size for lambdas to 4GB by removing the override
The lambdas are running quite slowly and the issue with the account has been resolved.

BAU: Remove the staging memory override

---

ci/terraform/shared/kms.tf

- Point the alias at the IPV key (rather than the ID Token signing key)
The IPV callback lambda is getting a KMS permissions error because it is trying to use the wrong key

AUT-111: Correct the target of IPV KMS key alias

---

ci/terraform/modules/endpoint-module/warmer.tf

- Add endpoint lambda alias to warmer policy
We are seeing errors with the warmer's not having permissions to execute the function using the alias ARN. Add this ARN to the policy.

AUT-111: Add endpoint lambda alias to warmer policy

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ClientStartInfo.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java

- In the client info return from `StartHandler` return the `redirect_url` as specified in the authorisation request.
This is required by the frontend in order to redirect the use back to the RP in certain error scenarios

AUTH-2: Return redirect URI from StartHandler

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/domain/IPVAuditableEvent.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

Add auditing in IPV callback handler.
We need an audit trail.
I'm not sure how we should handle IPV_SUCCESSFUL_IDENTITY_RESPONSE_RECEIVED.  As I understand it, we're not yet clear on how the handler should process the IpvInfoResponse.  I think James and I agreed that for now, we would just always log it as successful - I'm definitely open to alternative suggestions.
#1607 <- earlier PR which added auditing in the other IPV handlers

AUT-109: Add auditing in IPV callback handler

---

ci/terraform/oidc/staging-overrides.tfvars

- Replace the debug endpoint with the real endpoint
We are now in a position to use the real endpoint as this has been wired up.

AUT-111: Configure staging with normal IPV authorize

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- On a successful response received by IPV callback, change the final redirect to the new `/ipv-callback` in the frontend rather than `/auth-code`.
The new route in the frontend handles the IPV state logic without needing to pollute the `auth-code` route.

AUT-110: Change redirect on successful IPV callback

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java

This PR creates a new component, `BackChannelLogoutService`, which currently does nothing except log.
During logout flows, the client id for every live client session is pulled from the session, used to get the client configuration from the configuration store, and then dispatched to the new component.
Future PRs will add functionality to the new service.

AUT-241: Back-channel logout support in API (1)

---

ci/terraform/oidc/logout.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/BackChannelLogoutMessage.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

This PR publishes messages with client ID and back-channel logout URI to SQS for consumption by a lambda (which will come in a future PR).

AUT-241: Send messages to the back-channel logout queue

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java

It is currently _only_ logging errors because no-one has the backchannel URI set up yet

AUT-241: Log at warn rather than error about missing fields

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationRequest.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationResponse.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandlerTest.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientRegistry.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UpdateClientConfigRequest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java

- Add claims to ClientRegistry
- Make the backchannel uri optional when validating it 
- So RPs are only issued claims that they have registered to receive.

AUT-233 - Add claims to ClientRegistry

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java

- Ensure the Identity p values are not included in the VOT claim
- In the ID token there is a VOT claim which claims the vector of trust level. We must not return the identity values in this token as RPs discover the level of confidence only by inspecting the VC that comes from the single point of trust (SPOT)

AUT-267 - Ensure the Identity p values are not included in the VOT claim

---

ci/tasks/deploy-shared-api.yml
ci/terraform/shared/test-user.tf
ci/terraform/shared/variables.tf

Add acceptance test user seed data in the pipeline.
Provide a means to create test users in the database for the acceptance tests in the build environment only.
Pipeline updates to pass in the data to follow.
Some test scenarios are better implemented by having existing test data rather than creating all required users through the application during the test runs.
https://github.com/alphagov/di-infrastructure/pull/225

AUT-52: Add acceptance test user seed data in the pipeline

---

ci/tasks/deploy-shared-api.yml

Correct path for seed test data file.
Script was not reading the path from the right directory.
#1642

AUT-52: correct path for seed test data file

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/WellknownHandlerTest.java

Add back channel logout support to wellknown endpoint.
The provider metadata needs to reflect that back channel logout is supported.

AUT-253: Add back channel logout support to wellknown endpoint

---

ci/terraform/oidc/ipv-authorize.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java

- Going forward, we will be making our authorize requests to IPV using the JWT-Secured Authorization Request https://www.rfc-editor.org/rfc/rfc9101.html
- Give IPV authorize lambda permissions to the IPV token signing key and create a signed JWT which will contain the required claims required by IPV.
- Add the request parameter to the current auth request, alongside the existing params. This will be ignored until IPV start parsing it etc, at that point we will be able to remove the other parameters.
- Set the expiry time of the JWT at 3 mins for now. This is subject to change
- Requests may include PII so need to be secure. This JWT will also be encrypted but that will be in another PR.

AUT-262 - Support JWT-Secured Auth Requests to IPV

---

ci/terraform/oidc/ipv-authorize.tf

- Add key-id to authorize
- Otherwise the key id will be null and it will throw an AWSKMSException

AUT-262 - Add key-id to authorize

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/BackChannelLogoutMessage.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java

RPs will need to know the subject id to invalidate sessions, so we pass them in the message to SQS.

AUT-241: Attach subject ids to SQS message

---

ci/terraform/oidc/logout.tf

The logout lambda needs this to get the user salt.

AUT-241: Grant logout read-access to user profile

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java

If the user profile does not exist, then do not send the message.
We redirect to logout after we delete the account, which was breaking a build journey.

AUT-241: Don't send message if user does not exist

---

ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
ipv-api/build.gradle
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Read IPV encryption public key from parameter store and add the encryption cert for staging to the overrides. This is OK as it is a public certificate. 
- Create a parameter in parameter store where we can store this certificate and read it in from Config. This will replace reading it from KMS.
- Remove bouncycastle dependency from IPV as it is no longer required now that we are not using KMS to read the public key
- IPV will own the encryption key and then share with us the public part so we can encrypt requests on the authorize endpoint.

AUT-262 - Read IPV encryption public key from parameter store

---

ci/terraform/oidc/variables.tf

- Otherwise terraform doesn't like it

AUT-262 - Set a default value for the IPV encryption cert

---

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Use the correct parameter name in config service
- Because the param it is trying to get does not exist. 
`
name  = "${var.environment}-ipv-public-encryption-key"
`

AUT-262 - Use the correct parameter name in config service

---

ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/shared.tf
ci/terraform/shared/outputs.tf
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Tidy up unused encryption key variables
- Add additional logging
- Some of these values around the encryption key are longer required as we will be reading the public key via SSM instead.

AUT-262 - Tidy up unused encryption key variables

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java

Update sector id rules (for pairwise identifiers).
Create the sector id according to the spec:
https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg
"If the Client has not provided a value for sector_identifier_uri in [Dynamic Client Registration](https://openid.net/specs/openid-connect-core-1_0.html#OpenID.Registration) [OpenID.Registration], the Sector Identifier used for pairwise identifier calculation is the host component of the registered redirect_uri. If there are multiple hostnames in the registered redirect_uris, the Client MUST register a sector_identifier_uri.
When a sector_identifier_uri is provided, the host component of that URL is used as the Sector Identifier for the pairwise identifier calculation. The value of the sector_identifier_uri MUST be a URL using the …

AUT-273: Update sector id rules (for pairwise identifiers)

---

ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Use a placeholder IPV domain as the sector identifier. This will need to be updated with the real value when it is known.
- Create a new method in the ClientSubjectHelper which can take in the Sector Identifier in directly so it can calculate the pairwise subject
- Because we need to be using the IPV sector identifier instead of the RP's

AUT-245 - Use IPV sector identifier for IPV auth Subject ID

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/BackChannelLogoutRequestHandlerTest.java

`.toString()` is not the same as `.serialize()`, and the message is expected as form parameters

AUT-241: Fix message payload

---

ci/terraform/oidc/backchannel-logout-request.tf

The lambda currently does not know what key to use for signing

AUT-241: Pass missing environment variables to lambda

---

ci/terraform/oidc/ipv-authorize.tf

- Give ipv-authorize write access to the user tables
- The ipv-authorize needs write permissions as if a user does not have a salt, one will be created and then the user-profile table will be updated.

BAU - Give ipv-authorize write access to the user tables

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/entity/ClientRegistrationResponse.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UpdateClientConfigRequest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java

- Allow RPs to update sector ID uri via the update endpoint
- Validate the sector ID URI in both register and update endpoints
- So RPs can update sector ID in the immediate future until the way to register/update changes

BAU - Allow RPs to update sector ID URI

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java

- Only require consent if there is no level of confidence value in the vot and consent required is true in the client registry
- There are some cases where consent is set to true in client registry but as the user is on an identity journey, then they will not be asked for consent. This means that this could cause a null pointer when working out the scopes for the token.

BAU - Calculate whether consent is required using vot value in TokenHandler

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthoriseAccessTokenIntegrationTest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/ResetPasswordService.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/TokenGeneratorHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/NowHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserCredentialsTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/UserProfileTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenValidationServiceTest.java

Move to using `Clock` instead of `LocalDateTime` to avoid timezone issues. The OIDC spec mandates UTC and we should never use any localisation

BAU: Use Clock instead of LocalDateTime

---

integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AuthRequestError.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/RequestObjectError.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RequestObjectService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java

-  When the request object is present in the auth request and the request object supported is set to true in config then call the RequestObjectService from authorize to validate the request object.
-  Create an AuthRequestError and return it as an optional from both the AuthorizationService and the RequestObjectService. This will allow us to set the redirect URI in the object when present and ensure that the user is redirected there in a case of an error. The redirect URI is present in the auth request when a request object is not present and is present in the request object when one is present. This allows us to cater for both scenarios.
- When the request object is present but the request object supported is set to false then call the authorization service. This service will then return …

AUT-190 - Support request object auth request parameter

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml
ci/tasks/deploy-delivery-receipts-api.yml
ci/tasks/deploy-oidc-api.yml
ci/tasks/deploy-shared-api.yml
ci/terraform/account-management/variables.tf
ci/terraform/audit-processors/variables.tf
ci/terraform/delivery-receipts/variables.tf
ci/terraform/modules/endpoint-module/variables.tf
ci/terraform/oidc/variables.tf

This sets up a new variable, `logging_endpoint_arns`, that will allow us to specify multiple logging endpoint subscriptions.
This PR doesn't use the variable yet, but does use the existing ARN in configuration.
The following PR will remove both `logging_endpoint_arn` and `logging_endpoint_enabled` (as an empty list is equivalent to no logging).

AUT-268: Migrate logging subscription (1)

---

ci/terraform/shared/dynamodb.tf
ci/terraform/shared/variables.tf
doc-checking-app-api/build.gradle
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/entity/DocAppCredential.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java

- Create a new table to store this credential where the Subject will be the key. Add a time to exist on it which we will set for the same time as the validity as the access token issued to the RP.
- Add a feature flag to for the doc-checking-app-api and default it to false. The dynamo table will only be created when this has been switched to true.
- When we receive a credential in the DocAppCallbackHandler, we need to store this temporarily in dynamo. This is because we will only return it to the RP when we have received a valid access token via the OIDC flow.

AUT-303 - Create Dynamo table to store the Doc App Credential

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/doc-app-authorize.tf
ci/terraform/oidc/kms-policies.tf
ci/terraform/oidc/s3-objects.tf
ci/terraform/oidc/shared.tf
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/kms.tf
ci/terraform/shared/outputs.tf

- Create signing key for doc checking app integration
- Store doc app encryption public key in parameter store
-  Add terraform for the doc app authorize lambda
- Set doc_checking_app_api_lambda_zip_file in deploy-oidc-api.yml
- Signing key will be used to sign secure JWT in auth requests and signing private key JWT for requests to the token endpoint
- This is a placeholder public key and will be replaced with the public key which corresponds to the doc apps private encryption key. 
- So the lambda can be created in AWS

AUT-296 -  Add terraform for the doc app authorize lambda

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientSession.java

- Retrieve this subjectId in the DocAppAuthorizeHandler to send in the secure request to the doc app.
- Set docAppSubjectId in client session
- When a user comes from the doc app RP they will not have an account however we will require them to have a subject id. This subject ID will be used to determine what user information to get in the user-info endpoint as well as sending it to the doc checking app.
- This docAppSubjectId will be set in the start lambda once it is confirmed they have come from the doc app RP. We will generate a new salt and store a pairwise identifier here.

AUT-296 - Set docAppSubjectId in client session

---

shared/src/main/java/uk/gov/di/authentication/shared/entity/CustomScopeValue.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidScopes.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidScopesTest.java

- Create new doc-checking-app scope which will be used by the doc-checking-app RP.
- This scope will be used in the auth request and will be set in the access token. The userinfo will then use the scope in the access token to return the right user credential.

AUT-307 - Create new scope for the doc-checking-app

---

ci/terraform/shared/stub-rp-clients.tf

- Set ClientType to `web` for Stub clients
- A new field has been added to the ClientRegistry to support app clients. Explicitly set the Stub RP ClientType to `web`, although at some point we will want a Stub RP with an `app` ClientType

AUT-307 - Set ClientType to `web` for Stub clients

---

ci/terraform/oidc/doc-app-authorize.tf
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/domain/DocAppAuditableEvent.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java

- Add an audit event to the doc app authorize handler 
- Give the lambda the correct permissions to submit an audit event
- So we have a full audit trail

AUT-296 - Audit the Doc App authorize handler

---

ci/terraform/account-management/sqs.tf
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/performance_analysis.tf
ci/terraform/audit-processors/storage.tf
ci/terraform/delivery-receipts/api-gateway.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/backchannel-logout-request.tf
ci/terraform/oidc/spot-response.tf
ci/terraform/oidc/sqs.tf
ci/terraform/shared/sns-alerts.tf

- Use unique names for aws_cloudwatch_log_subscription_filter resources
- Now that there are multiple logging arns, we are creating multiple aws_cloudwatch_log_subscription_filter resources. Therefore these resources need to have a unique name otherwise we will see an error like ` Error creating Cloudwatch log subscription filter: OperationAbortedException: A conflicting operation is currently in progress against this resource. Please try again.`

BAU - Use unique names for aws_cloudwatch_log_subscription_filter resources

---

ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/shared/dynamodb.tf
ci/terraform/shared/variables.tf

- Start deploying the doc app lambdas to the staging environment only
- Remove the condition on the dynamo tables so that they are built in every environment. This is similar to what we done for the SPOT tables.
- So we know the lambdas are deployed to an environment successfully 
- Staging is the environment where we will be testing the doc checking app integration

AUT-307 - Deploy doc app lambdas to staging

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/account-management/sqs.tf
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/performance_analysis.tf
ci/terraform/audit-processors/storage.tf
ci/terraform/delivery-receipts/api-gateway.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/backchannel-logout-request.tf
ci/terraform/oidc/spot-response.tf
ci/terraform/oidc/sqs.tf
ci/terraform/shared/sns-alerts.tf

- Explicitly set the `create_before_destroy` to `false` for all `aws_cloudwatch_log_subscription_filter` resources.
This shouldn't be necessary, as the default should be `false`, however, Terraform state indicates this is not the case. As such, we recently experience problems with renaming filters.
#1708

AUT-268: Ensure subscriptions are destroyed before creation

---

integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IPVUserIndentityResponse.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTClaims.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTRequest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/entity/SPOTRequestTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVTokenServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IdentityClaims.java

Pass identity claims to SPOT for P2.
Retrieving the IPV core user identity outputs:
https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0014-identity-ipv-core-oauth-profile.md
Passing to SPOT:
https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0013-spot-request-response-structures.md
Claims need to be signed by SPOT before being returned to the RP.

AUT-272: Pass identity claims to SPOT for P2

---

ci/terraform/oidc/start.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/UserStartInfo.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/UpliftHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/SaltHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelperTest.java

- Create a helper to determine whether it is a doc checking app user. This is determined by whether a request object was present in the auth request, that the doc checking app scope is present and if the client has `app` as their `ClientType`
- If it is a doc checking app user, then we need to build the ClientStartInfo using the claims in request object as `redirect_uri` and `scope` will not be present as the usual auth request query parameter.
- Return a new property in the UserStartInfo called `docCheckingAppUser` this will be a boolean and will be used by the frontend to direct the user to the correct location.
- When the user is a docCheckingAppUser then set the `docAppSubjectId` in the client session using a new salt and the sector identifier which is the doc checking app domain. …

AUT-300 - Update StartLambda to cater for Doc checking app users

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/staging-stub-clients.tfvars
ci/terraform/shared/stub-rp-clients.tf

- Remove the localhost redirect URI for Stub build 1 as it is not used and avoids us having to add a sector identifier
- Make ClientType dynamic so it is not hardcoded the same for each stub
- Make scope dynamic so they are not hardcoded the same for each stub
- Add a new Stub config in for Staging to replicate the Doc Checking App RP. This will include the doc-checking-app scope and also the `app` ClientType
- So we can configure it on a Stub by Stub basis 
- So we can test out the journey from a Doc Checking App Stub

AUT-295 - Add new Stub and make config dynamic

---

ci/terraform/oidc/authorize.tf
ci/terraform/oidc/variables.tf
integration-tests/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthorisationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Use on feature flag for supporting request objects
- Instead of managing 2 feature flags for the doc app journey, use a single feature flag to make it easier and clearer to manage.

AUT-295 - Use on feature flag for supporting request objects

---

doc-checking-app-api/build.gradle
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/CriStubExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/configuration/BaseLambdaConfiguration.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java

- Update `ConfigurationService` to return an `ECPublicKey` object parsing the parameter store value as a PEM.
- Cache the converted certificate for subsequent calls
- Add integration tests to test for invalid CRI responses.
We will be storing the public key, initially, in parameter store in PEM format. Updating the configuration service allows us to swap in implementations if we decide to read direct from KMS at a later date.
The integration tests, previously, only tested the happy path, added extra test for unhappy path.
#1723

AUT-298: PEM certs and integration tests

---

shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBSchemaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java

- Set Dynamo to consistent for Client Reg and both UserProfile tables. 
- It's important that when we update Dynamo it is made consistent. The default is eventual which means it will eventually be consistent, this isn't good enough for us.

BAU - Set Dynamo to consistent

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/variables.tf

- Add the callback endpoint to the OIDC API
- Add new policies to allow reading/writing of the credential table
- Add new parameter to store PEM of CRI signing certificate
We have implemented a callback lambda, lets now publish to an API endpoint.
#1723 
#1729

AUT-298: Deployment of document app callback

---

ci/terraform/oidc/doc-app-callback.tf

- Add Dynamo read role to doc app callback
This is required by the "warm up" routine.

AUT-298: Add Dynamo read role to doc app callback

---

ci/terraform/oidc/token.tf

- The endpoint having tracing enabled but do have XRay permissions. Lets add to the token endpoint to see if we can get some insights.
To investigate performance

AUT-330: Grant XRay perms to token lambda

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthenticateHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/AuthoriseAccessTokenHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/ClientRegistrationHandler.java
client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/lambda/UpdateClientConfigHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/DynamoTestConfiguration.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ClientStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SPOTStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoClientHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/dynamodb/DynamoDBSchemaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoClientService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoSpotService.java

Don't initialise a new Redis connection for the ClientSessionService. This will have a minor performance benefit as we're not connecting twice.
- BAU: Create `DynamoTestConfiguration` for test extensions
- BAU: Remove duplicated constructors
- BAU: Create helper to initialise DynamoDB connections and configuration
- BAU: Use helpers in Dynamo-backed services

BAU: Refactor creation of Redis/Dynamo in handlers

---

account-management-integration-tests/build.gradle
build.gradle
integration-tests/build.gradle
oidc-api/build.gradle

- Add X-Ray SDK dependencies to OIDC API
- Add Gradle `exclude` for X-Ray SDK to `integration-tests` module
- Remove unecessary dependencies from`account-management-integration-tests` which cause X-Ray to be pulled through
We wish to inspect which operations are taking the time in the token endpoint.
Excluding the SDK from integration tests prevents requirement to provide extra setup for the tests.

AUT-330: Add XRay Instrumentation to OIDC API

---

integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/RequestObjectService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java

- Validate that the request object contains the custom `doc-checking-app` scope 
- Validate the request object contains the state claim 
- Validate that the client who sent the request_object has a client type of `app` 
- We need to ensure the state param is present when an RP uses the request object as we will need to return it in the auth response. This will allow the RP to validate that the state param sent back in the response is the same as the request and will prevent against Cross-site request forgery attacks.
- Only clients with a ClientType of `app` can use request objects.
- We now have a doc-checking-app custom scope which be used by the app RP. We expect this to be in the request object JWT so we should validate for this

AUT-321 - Add extra validation for the request object in authorize

---

account-management-api/build.gradle
account-management-integration-tests/build.gradle
audit-processors/build.gradle
build.gradle
ci/terraform/oidc/token.tf
client-registry-api/build.gradle
delivery-receipts-api/build.gradle
delivery-receipts-integration-tests/build.gradle
doc-checking-app-api/build.gradle
frontend-api/build.gradle
integration-tests/build.gradle
ipv-api/build.gradle
oidc-api/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared-test/build.gradle
shared/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Add a new helper to execute a funtion in custom subsegment
- Wrap certain cryptographic operations in the helper so that its execution times are recorded in sub segment (if tracing enabled)
- Add excludes to Gradle sub-modules that use the `shared` module so that XRay is not pulled into modules that don't need it
- Enable tracing on token endpoint
- Wrap additional operations in `TokenHandler` with custom subsegments
Traces resulting from previous pull-request show that there is bottleneck in any AWS related service calls, we suspect that one of the calls we have wrapped in a custom segment is causing the issue. This PR should help us focus on where the issue might lie.
#1744 
#1745

AUT-330: Add custom instrumentation to TokenHandler and TokenService

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SignUpHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LogoutIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/LogoutHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ClientSessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ClientSessionServiceTest.java

- Since October we have seen errors in ours log from the LogoutHandler quoting `Error getting client session from Redis`.
- If a users existing session is still valid and they hit /authorize again, it will create a new session, copy everything over from the old session (including client sessions) and delete the old session. The new session has a 60 minute expiry and is rolling, so every time the session is saved it was reset to 60 minute expiry. However the client sessions which have been copied over from a previous session will not be rolling and will expire before the existing session does. We save these client session with a expiry time in Redis, so once they have expired they will not exist in Redis. The session however still has a list of all client sessions ID stored whether they …

AUT-322 - Fix logout bug

---

ci/terraform/oidc/api-gateway.tf

- Enable XRay tracing on the OIDC API gateway stage. 
This will help tie requests together end-to-end and measure any latency through the gateway

AUT-330: Add XRay tracing to API gateway

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java

- Log exception thrown by user-identity endpoint
- We are getting an exception whilst trying to call the IPV user-identity endpoint. Log the exception.

BAU - Log exception thrown by user-identity endpoint

---

ci/terraform/shared/kms.tf

- Remove the kms encryption key
- It is not used
- We will be encrypting the secure jar using a public encryption key supplied to us by IPV. This will be kept in parameter store and therefore this key is redundant.

AUT-285 - Remove the kms encryption key

---

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTStatus.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java

- Change SPOT Response status
- The status on the SPOT Response can either be Accepted or Rejected. Change the enum to reflect this. This can be seen in RFC 0013 - https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0013-spot-request-response-structures.md

AUT-343 - Change SPOT Response status

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/build.gradle
oidc-api/src/main/java/uk/gov/di/authentication/oidc/exceptions/UserInfoException.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/helper/RequestObjectTestHelper.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DocumentAppCredentialStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/exceptions/RequestObjectException.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

Update oidc flow for the doc app.
Doc app 'authorisations' use a request object instead of parameters, containing a custom 'doc-checking-app' scope and a subject id.  This PR makes changes to the oidc flow to:
1. Check when it is being called by the app.
2. Use the information in the request object where required rather than the normal auth parameters.
3. Not rely on the user-profile as this won't exist for an app user.
4. Return a  temporary credential from the database for a doc app user in user-info rather than the standard attributes.
Changes have been made to the auth-code, token and user-info endpoints, with some supporting helper methods
A doc app checking user bypasses the authentication frontend journey but is still authenticated in the background.

AUT-320: Update oidc flow for the doc app

---

ci/terraform/oidc/dynamo-policies.tf

Grant user-info access to the doc-app-credential table.
Even though the path is not currently being called the warmer is trying to access the table resulting in an error:
build-userinfo-lambda is not authorized to perform: dynamodb:DescribeTable on resource: :table/build-doc-app-credential 
#1739

AUT-320: grant user-info access to the doc-app-credential table

---

ci/terraform/oidc/integration-overrides.tfvars

- Start deploying IPV lambdas to Integration
- Add placeholders value in integration-overrides.tfvars
- We need to been integrated with IPV and SPOT in Integration by the end of May so we should start deploying the lambdas to this environment. This will not break anything already there
- This will create the required SQS queues and allow us to supply SPOT with the queue ARNs

AUT-348 - Start deploying IPV lambdas to Integration

---

client-registry-api/src/main/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationService.java
client-registry-api/src/test/java/uk/gov/di/authentication/clientregistry/services/ClientConfigValidationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ClientRegistrationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ValidClaims.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/ValidClaimsTest.java

- Support correct identity claims
- Convert ValidClaims to an enum
- Update ValidClaims to reflect the claims that we will expect from an RP. These claims will then be passed onto IPV.
- An enum is more appropriate for defining the list of valid claims

AUT-5 - Support correct IPV claims

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Add the missing `throw` statement
- Add client ID and grant type as annotations to XRay traces on `token` endpoint.
This will help us identify which clients are suffering the slow response times and the grant type they're requesting.

AUT-345: Fix exception and add annotation

---

ci/terraform/shared/stub-rp-clients.tf

- Register the Stubs with the correctly named claims
- So the Stubs can request claims

AUT-5 - Register the Stubs with the correctly named claims

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVTokenService.java

- Set nbf claims in token requests to IPV and DocApp CRI
- We should specify the NBF in the token request as it outlines the time where the token cannot be processed before.

BAU - Set nbf claims in token requests to IPV and DocApp CRI

---

ci/tasks/deploy-shared-api.yml
ci/terraform/shared/grafana-read-only-role.tf
ci/terraform/shared/variables.tf

We only create this role in integration and production (happy to discuss why)

AUT-76: Terraform read-only metrics roles

---

ci/terraform/shared/grafana-read-only-role.tf

The build is currently broken because we depend on things that don't exist

AUT-76: Don't attach the policy if the role doesn't exist

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java

- Re-add the lines to associate annotations to the segment
- Add a main segment at the beginning of the `TokenHandler` lambda `handleRequest` method
A previous attempt to add the annotations failed as it seems you cannot add annotations to a Lambda facade segment, so we now explicitly create a segment for the lambda.

AUT-345: Add XRay Segment annotations

---

ci/terraform/oidc/dynamo-policies.tf
ci/terraform/shared/dynamodb.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IdentityStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IdentityCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Return the coreIdentityJWT claim in `/userinfo` if the coreIdentityJWT claim is present in the access token and in the identity credentials table. 
- Remove the other claims from the Identity credentials table. 
- Delete the spot credential table 
- So RPS can retrieve the coreIdentityJWT claim with the correct claim name 'https://vocab.account.gov.uk/v1/coreIdentityJWT'
- These are not being returned from IPV yet so we can add additional claims in once the format is known
- The spot credential table has been replaced by the identity credentials table

AUT-5 - Return coreIdentityJWT claim in userinfo

---

account-management-api/build.gradle
account-management-integration-tests/build.gradle
audit-processors/build.gradle
client-registry-api/build.gradle
delivery-receipts-api/build.gradle
delivery-receipts-integration-tests/build.gradle
doc-checking-app-api/build.gradle
frontend-api/build.gradle
integration-tests/build.gradle
ipv-api/build.gradle
shared-test/build.gradle

- Remove `noXray` from all projects except the integration tests
This was added to all Gradle modules, but we only need to exclude from integration tests (as it causes failures).

AUT-345: Tidy up use of `noXray` directive in Gradle

---

ci/terraform/oidc/logout.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/InstrumentationHelper.java

- Add the XRay policy to the `LogoutHanlder` role
- Set the `TRACING_ENABLED` flag in environment variables
- Add a custom segment around the call to `destroySessions()`
This handler has been showing some performance issues, lets see what XRay reveals.

AUT-345: Add XRay to LogoutHandler

---

shared/src/main/java/uk/gov/di/authentication/shared/services/RedisConnectionService.java

- Remove the use of parenthesis in segment names in `RedisConnectionService`
Parenthesis are not valid for segment names and, as such, the segments are not appearing:
> name – The logical name of the service that handled the request, up to 200 characters. For example, your application's name or domain name. Names can contain Unicode letters, numbers, and whitespace, and the following symbols: _, ., :, /, %, &, #, =, +, \, -, @
#1786

AUT-345: Remove parenthesis from segment names

---

shared/build.gradle
shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SerializationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java

- Use GSON to deserialise the `Session` object fetched from Redis. 
This is an experiment to allow us to compare XRay traces with the Jackson version to compare performance.

AUT-345: GSON vs Jackson experiment

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AwsSqsClient.java

- Use a completable future to send the backchannel logout event to the SQS queue.
- Add missing `segmentedFunctionCall()` on alternate path through `LogoutHandler`
Xray shows 200-300ms latency when talking to SQS. As we don't need to wait for a result, lets try sending it asynchronously and see how that affects overall latency.

AUT-345: Send backchannel logout to SQS async

---

delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/CloudwatchMetricsExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CloudwatchMetricsServiceTest.java

- In the `CloudwatchMetricsService` swap the `CloudWatchClient` for a `CloudWatchAsyncClient` so that metrics get sent asynchronously.
Xray shows that sending of metrics, in `auth-code` takes anything from ~100ms to 7 seconds. This is a "fire and forget" operation, we don't wait for the results.

AUT-345: Send application metrics asynchronously

---

ci/terraform/account-management/authorizer-warmer.tf
ci/terraform/account-management/authorizer.tf
ci/terraform/account-management/sqs.tf
ci/terraform/modules/endpoint-module/lambda.tf
ci/terraform/modules/endpoint-module/warmer.tf
ci/terraform/oidc/sqs.tf

Revert alphagov/di-authentication-api#1734
We now believe that this wasn't to blame for the slow down as we have identified other sources of latency.

Revert "BAU: Stop using TieredCompilation, it slowed down our lambdas"

---

ci/terraform/oidc/userinfo.tf
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTStatus.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Retrieve identity credentials using pairwise identifier
- Generate the doc app pairwise identifier correctly
- Put the SPOTStatus in uppercase
- We save identity information in the identity credentials table using the pairwise identifier as the key. This pairwise identifier is generated using the IPV domain as the sector URI and NOT the RP sector URI
- The doc app domain will need to be parsed to a host before generating a pairwise identifier. Add an overloaded method to the ClientSubjectHelper to cater for this
- SPOT will be returning the status in uppercase so lets be explicit

AUT-5 - Return identity credentials in /user-info

---

ci/terraform/shared/build-stub-clients.tfvars

- Give config to a Stub App for the build env
- So we can test an app journey in our build env

AUT-328 - Give config to a Stub App for the build env

---

ci/terraform/oidc/build-overrides.tfvars

- Enable doc app lambdas in build
- We want to be able to test the doc app journey in the build environment using our stubs. Therefore set the doc_app_api_enabled to allow this to happen.

AUT-352 - Enable doc app lambdas in build

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/shared.tf
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
ci/terraform/shared/outputs.tf
ci/terraform/shared/ssm.tf

- Move IPV capacity parameter to OIDC module
- Set IPV capacity to true for Integration and Staging environment
- The IPV capacity parameter is only ever used in the OIDC terraform module. Moving this parameter here makes it easier to configure the variables alongside the other IPV terraform variables.
- Otherwise we will not be able to test out the IPV journey

AUT-352 - Move IPV capacity parameter to OIDC module 

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java

- At the point of generating a pairwise identifier, they should be prefixed with `urn:uuid:`.
- Verifiable Credentials require identifiers to be URIs, which in this case is the pairwise identifier. Keep things consistent and make pairwises identifiers all have the same prefix.
- See RFC-0014 for more info - https://github.com/alphagov/digital-identity-architecture/blob/main/rfc/0014-identity-ipv-core-oauth-profile.md

AUT-33 - Prefix pairwise identifiers with urn:uuid:

---

ci/terraform/oidc/doc-app-callback.tf

- Remove api key from doc app callback lambda
- it is not needed as it is the callback lambda

AUT-328 - Remove api key from doc app callback lambda

---

ci/terraform/oidc/doc-app-callback.tf

- Remove the `authentication_security_group_id` as this restricts permissions for this lambda to egress. This is giving this lambda the same permissions as the ipv callback lambda
- It needs to egress to call the token endpoint

AUT_328 - Give doc app callback lambda permission to egress

---

ci/terraform/oidc/build-overrides.tfvars

- Change endpoint of the data endpoint for the doc app
- The Stub CRI uses /credentials/issue instead of user-identity

BAU - Change endpoint of the data endpoint for the doc app

---

ci/terraform/oidc/doc-app-callback.tf

- Give callback lambda permissions to LOGIN_URI
- It is required to redirect back to the frontend

BAU - Give callback lambda permissions to LOGIN_URI

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/RequestObjectServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/DocAppUserHelperTest.java

- Parse the scope claim in the token handler from a request object
- We need to parse the scopes in the request object as a scope so it will be entered into the access token as an array.

AUT-328 - Parse the scope claim in the token handler from a request object

---

ci/terraform/oidc/doc-app-callback.tf
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java

- Remove call to dynamo client service in DocAppCallbackHandler
- We get the client id from the client session auth request params and validate that the client is valid. We don't use the client details for anything else. This validation has already taken place in authorize. Therefore we can remove a call to the client registry and remove the permissions for the DocAppCallbackHandler to call the client registry so it only has minimal permissions.

BAU - Remove call to dynamo client service in DocAppCallbackHandler

---

ci/terraform/oidc/userinfo.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AccessTokenInfo.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java

- Identity credentials will be saved using a pairwise identifier generated with the RP sector identifier. This is and should be the same pairwise identifier that we have set in the access token, therefore we can just use that to retrieve the identity credentials. 
- We have a variable in a number of places called `publicSubject`. This is misleading as it can sometimes be either a publicSubject or pairwiseSubject identifier depending on the client. Calling it subject is more generic and appropriate
- Otherwise we will not be able to retrieve identity credentials 
- To make it clear what the subject is and isn't

BAU - Retrieve identity credentials using subject in access token

---

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Refactor getSsmClient to resolve sonarqube false positive bug.
Sonarqube is looking for an 'ifPresent' even though there is already one there.
Method could still benefit from some refactoring which should also resolve the issue.
https://sonarcloud.io/project/issues?id=alphagov_di-authentication-api&issues=AX4L6RppVQ-r2xrfs1X9&open=AX4L6RppVQ-r2xrfs1X9&pullRequest=1236

BAU: refactor getSsmClient to resolve sonarqube false positive bug

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/ssm.tf
ci/terraform/oidc/variables.tf

- Read in SPOT config via concourse into terraform variables and store them variables in parameter store. 
- This makes it easier if we were to move away from concourse.
- The values in parameter store will then be used to give permission to the require terraform resources.

AUT-326 - Store SPOT config in SSM

---

ci/terraform/oidc/spot-response.tf
ci/terraform/oidc/spot-sqs.tf

- Grant read access to the SPOT request queue to the SPOT AWS account
- Grant the ipv_spot_response_role permissions to read from SPOT response SQS queue
- Create a new KMS key for the SPOT request queue as AWS managed keys cannot be shared across account. Give SPOT kms:GenerateDataKey to the key.  
- As we are reading from queues cross account we need to set up the correct permissions so the lambdas can each read from those SQS queues.

AUT-326 - Grant read access to SPOT sqs queues

---

ci/terraform/oidc/spot-response.tf
ci/terraform/oidc/spot-sqs.tf

- Only add spot_response_sqs_read_policy if ipv is enabled
- Set right permissions to KMS key
- IPV isn't enabled in all environments so the spot_response_sqs_read_policy will not always be present
- We need to give SPOT permissions to decrypt our key and we need to give the SPOT response lambda permissions to decrypt the SPOT kms key

AUT-326 - Only add spot_response_sqs_read_policy if ipv is enabled

---

ci/terraform/oidc/spot-response.tf

- Add a feature flag to the ipv_spot_response_role so it is only created when ipv is enabled. 
- We are currently seeing a Invalid count argument error when ipv is enabled

AUT-326 - Add feature flag to ipv_spot_response_role 

---

ci/terraform/oidc/spot-response.tf

- Ensure module is created after spot_response_sqs_read_policy
- Make sure the spot_response_sqs_read_policy is created before creating the ipv_spot_response_role

AUT-326 - Ensure module is created after spot_response_sqs_read_policy

---

ci/terraform/oidc/integration-overrides.tfvars

- Disable IPV in integration
- The pipeline is failing as we don't have all the values configured needed to talk to IPV. Currently disable it to get a green pipeline.

AUT-326 - Disable IPV in integration

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- If the VTM returned by IPV is not the one we sent, then fail validation and do not send to SPOT
We currently only log if this validation fails, we need to ensure that SPOT is not invoked if this validation fails.

AUT-340: Validate VTM returned by IPV

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/LogLineHelper.java

Add context logging to IPV journey.
BaseFrontendHandler already adds session id and client session id if it is used so these are not needed for IPVAuthorisationHandler.
ipv-capacity is called by an RP when no user context is available so there is no benefit in adding the logging.
Log ids are not currently available in the SPOTResponse but will be added at a later date.
Monitor end-to-end journey for diagnostics.

AUT-350: Add context logging to IPV journey

---

ci/terraform/oidc/spot-response.tf

- As we have not yet been granted permissions to the SPOT KMS key or SPOT sqs queue, we are seeing an error when the terraform applies. Comment out the section trying to seek access to these resources until we have been given access, this will at least fix the pipeline.
- We can leave in the section granting SPOT access to our resources.
- To fix the staging environment until we have been granted access to the SPOT kms key and SQS queue

AUT-326 - Comment out permissions on the SPOT response lambda

---

ci/terraform/oidc/integration-overrides.tfvars

- Enable IPV in integration
- To integrate with IPV in integration 
- So the integration SQS queues are created and I can share the ARNs with SPOT

BAU - Enable IPV in integration

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java

- Remove `scope`, `redirect_uri`, `state` and `nonce` parameters from the IPV authorisation redirect
These are all included in the JAR so do not need to be passed as a `GET` parameter..

AUT-292: Remove redundant parameters on IPV auth call

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- Throw when VTM mismatch
- Raise the logging level of some of our logging messages to flag when something goes wrong.
- When the VTM returned from the IPV user-identity endpoint is not what we expect then should throw.

AUT-265 - Throw when VTM mismatch

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Update IPV endpoints for staging and integration
- IPV now have a domain of identity.integration.account.gov.uk so update the endpoints to reflect this
- We can refactor our config values etc as there's a bit of duplication

BAU - Update IPV endpoints for staging and integration

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- Return error to RP when P0 is returned from IPV
- When we receive a P0 back from IPV then we should return an error back to the RP. This is because the RP needs at least P2. This will change when more RPs connect.

AUT-265 - Return error to RP when P0 is returned from IPV

---

integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/TokenHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/TokenHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

Make the client_id parameter optional in the Token service.
- If client_id not supplied then retrieve it from the private key JWT.
- If client_id is supplied then validate that the client id matches the value in the private key JWT.
Our clients are 'authenticated' so according to the spec client_id is an optional parameter:
https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3

AUT-363: Make the client_id parameter optional in the Token service

---

ci/terraform/account-management/api-gateway.tf

- Remove the unqualified form from the authorizer invocation policy (we already include the fully qualified form by including the alias ARN).
AWS have implemented a policy change that requires policies to use fully qualified function names.

BAU: Remove unqualified function name in policy

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Change the `ipv_sector` Terraform variable that we use to generate subject IDs for IPV to our root URL for the environment.
The sector ID represents us (as a client), so we use our own URIs rather than IPV's.

AUT-332: Change sector ID

---

ci/terraform/oidc/spot-response.tf

- Give SPOT response lambda describe permissions
- Describe table permissions are required for the warmer. At the moment this is causing lots of errors in the logs.

BAU - Give SPOT response lambda describe permissions

---

ci/terraform/oidc/spot-response.tf

- Give SPOT response lambda permission to audit
- Ensure the SPOT response lambda has the correct permissions to send audit events and has the audit environment variables configured.
- The SPOT response lambda needs to audit and therefore needs the correct permissions

AUT-335 - Give SPOT response lambda permission to audit

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/oidc/sqs.tf
ci/terraform/oidc/variables.tf
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Allow the use of multiple phone/numbers that get written to S3
- Rename `ConfigurationService.getNotifyTestPhoneNumber()` to `getNotifyTestDestinations()` to reflect that it may contain multiple values and may also be an e-mail address
- Rename `NOTIFY_TEST_PHONE_NUMBER` variable to be `NOTIFY_TEST_DESTINATIONS` to reflect that it may be plural and could also hold email addresses.
- Rename associated Terraform variables
- Change parsing of environment variable to handle the empty string
To support end-to-end automated testing

AUT-331: Allow multiple test OTP destinations

---

ci/terraform/oidc/spot-sqs.tf

- Add the resource to queue access policy
- Increase visibility timeout to 60 seconds
SPOT were unable to connect to our queue, this resolves it.

AUT-335: Add `Resource` field to queue policy statement & increase visibility timeout

---

ci/terraform/oidc/ipv-callback.tf

Configure spot request queue for ipv callback
The request queue is currently undefined so ipv callback is failing.

BAU: configure spot request queue for ipv callback

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/spot-sqs.tf

- Give permissions to IPV Callback to encrypt data for the queue
- Increase max message size on SPOT request queue
IPV callback handler is failing

AUT-335: Fix IPV Callback permissions and max message size

---

oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ClientSubjectHelperTest.java

- Make our pairwise identifiers VC compliant by implementing them as a URN as per RFC4198. This would prefix all identifiers with 'urn:fdc:gov.uk:2022:', where 2022 is the DateId and would remain fixed.
- Use base64 url encoding to generate the subject resourceId
- We previously had a prefix of 'urn:uuid:' however our identifiers were not a valid UUID and did not comply the UUID spec.
- The VC data model instructs that subject identifiers MUST be URIs. We want to make sure we are compliant with the VC spec as much as possible otherwise it could cause issues for our VCs being compatible across other trust frameworks.
- We were currently using Base16 to generate this identifier. Switching to Base64 URL encoding allows us to use a lib rather than have to write our own as well as reducing any …

AUT-397 - Update Pairwise prefix to make them VC compliant

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java

Start handler authenticated should always be false for the doc app journey.
Fixes an SSO issue where a logged in user tries to run a doc app journey.  The assumption is that authentication is always required for the doc app, therefore the session cannot already be authenticated.

AUT-382: Start handler authenticated always false for doc app journey

---

integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/IdentityHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/LevelOfConfidence.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/VectorOfTrust.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/IdentityHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/LevelOfConfidenceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/entity/VectorOfTrustTest.java

- Update the `LevelOfConfidence` enum to include new value `P0`
- Update `IdentityHelper.identityRequired()` to return `false` if `vtr` contains `P0`
- Update `StartIntegrationTest` to test multiple vtr and ensure that correct value for `identityRequired` is returned
- Update `VectorOfTrust.containsLevelOfConfidence()` to return false if a `LevelOfConfidence` is specified but is `NONE`.
We need to allow passing of `P0` but to treat it as if no LoC was passed at all.

AUT-364: P0 level of confidence

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/IdentityHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/conditions/IdentityHelperTest.java

- Make start honour identity enabled flag
- If the IDENTITY_ENABLED config value is set to false, then always make sure that the `identityRequired` property in the StartResponse returns false.
- This will allow us to deploy the IPV infra to Production whilst ensuring no IPV journeys can be performed.

AUT-384 - Make start honour identity enabled flag

---

ci/terraform/oidc/start.tf

- Add the `IDENTITY_ENABLED` environment variable to the `StartHandler` lambda as this is now the feature flag for identity
IPV journeys not currently working in staging or integration
#1896

AUT-384: Add `IDENTITY_ENABLED` to `StartHandler`

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/ipv-capacity.tf

- Move IPV capacity lambda to OIDC api
- This lambda will be requested by RPs. Therefore the API needs to be publicly available to them.

AUT-384 - Move IPV capacity lambda to OIDC api

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

- Skip phone numebr validation if `07700900222` is used as this is a Notify test number
This will be used by end-to-end tests but is currently being rejected by the validation.

BAU: Allow Notify test number

---

ci/terraform/oidc/ipv-authorize.tf
ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/production-overrides.tfvars
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- To ensure that Identity journey cannot be carried out in production, add a check on the IPVCallback and IPVAuthorize lambdas to see if identity is enabled and throw and exception if it is not.
- We currently have an ipv_enabled flag on the terraform which determines whether or not we deploy IPV infra. We want to start deploying IPV infra to production so we are in a position to share our config with other teams, however the Identity code is not yet ready to be used in production.

AUT-385 - Check whether identity is enabled in IPV callback and authorize lambdas

---

ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Re-enable IPV in Staging and Integration
- We have removed the feature flag for IPV so we should now be able to re-enable IPV in Staging and Integration.

AUT-385 - Re-enable IPV in Staging and Integration

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars
ci/terraform/oidc/spot-response.tf

- Swap feature flag in aws_lambda_event_source_mapping to spot_enabled
- We want to keep IPV disabled in Production but we want to connect to the SPOT queue. We still need a flag on the aws_lambda_event_source_mapping resource, as we don't have a SPOT response queue yet in build so the terraform will fail. By using the spot_enabled flag and enabling SPOT in production, we can test that we can connect to the SPOT queue.
- Users still won't be able to use the identity journey as we check if Identity is enabled in both the IPV Authorize and IPV callback lambda and that will remain disabled

AUT-385 - Swap feature flag in aws_lambda_event_source_mapping to spot_enabled

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java

- Add logging in SPOTResponseHandler for when we receive a successful response
- So we can tell when the lambda has received a successful response

BAU - Add logging in SPOTResponseHandler for when we receive a successful response

---

shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/ConfigurationServiceTest.java

Change session timeout to 2hrs.
Support long-running identity proofing.

AUT-401: change session timeout to 2hrs

---

ci/terraform/shared/production-stub-clients.tfvars

Add stub rp client for prod.
To be used by the restricted prod stub rp
#131
#135

AUT-386: Add stub rp client for prod

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/NotifyRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/RemoveAccountRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/SendNotificationRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/UpdateEmailRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/UpdatePasswordRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/entity/UpdatePhoneNumberRequest.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/NotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandler.java
account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/NotificationHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/RemoveAccountHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdateEmailHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePasswordHandlerTest.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/UpdatePhoneNumberHandlerTest.java

- Update handlers to use `SerializationService` rather than Jackson
- Update entities to remove Jackson annotations
We are migrating to GSON from Jackson

AUT-356: Update account managment API to use GSON

---

delivery-receipts-api/build.gradle
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/entity/NotifyDeliveryReceipt.java
delivery-receipts-api/src/main/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandler.java
delivery-receipts-api/src/test/java/uk/gov/di/authentication/deliveryreceiptsapi/lambda/NotifyCallbackHandlerTest.java
delivery-receipts-integration-tests/src/test/java/uk/gov/di/deliveryreceipts/NotifyCallbackHandlerIntegrationTest.java

- Update entities to use GSON annotations
- Update handlers to use `SerializationService` instead of Jackson
We are moving to GSON rather than Jackson for performance reasons

AUT-356: Migrate Delivery Receipts to GSON

---

integration-tests/src/test/java/uk/gov/di/authentication/shared/services/RedisConnectionServiceIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/RedisConnectionService.java

- Change the `RedisConnectionService` to use `MasterReplica` connect and to read from the replica where possible.
We store the replica hostname in parameter store, but we never use it. We should provide this to the `MasterReplica.connect()` method to allow Lettuce to operate in fault tolerant way.
We should also redirect read requests to the replica where possible.

BAU: Open Redis client in a Master/Replica aware way

---

ci/terraform/account-management/api-gateway.tf
ci/terraform/delivery-receipts/api-gateway.tf
ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

- Enable metrics on API gateway methods to allows per method API calls and latencies
This will help us identify a baseline for potential provisioned concurrency.

AUT-330: Enable detailed metrics on API gateway

---

ci/terraform/oidc/ipv-callback.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IPVStubExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IdentityStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/IdentityCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Check the IPV user-identity response to see if any supported claims are present. If they are, then we will persist them to DB (with the exception of the CoreIdentityJWT which is sent to SPOT) 
- Return additional claims back to the RP in userinfo
- In the user-identity response back from IPV, check to see if any ValidClaims are present. Save any claims who's name are present in the ValidClaims.java class apart from the CoreIdentityJWT claim.
- If the RP has requested additional identity claims, then we we check the IdentityCredential table to see if any of these requested claims appear in the additionalClaims map. If they do then we will return these to the RP.

AUT-402 - Return additional identity claims back to the RP

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/testsupport/helpers/NotificationAssertionHelper.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/BackChannelLogoutServiceTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AwsSqsClient.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SnsService.java

- Use the async client for SNS
- Use the async client for SQS
With both our SQS and SNS use cases we can just "fire and forget" our calls to these services, we don't inspect the result.
The calls to both these services provided a noticeable block of latency on the Xray traces, so calling them asynchronously seems to be a sensible approach.

AUT-330: Async SNS and SQS

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/StartHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DocumentAppCredentialStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ClientSession.java
shared/src/main/java/uk/gov/di/authentication/shared/serialization/SubjectAdapter.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SerializationService.java

- Write a custom adapter for searlization of the Subject in the ClientSession. 
- Add an asserts to an existing test
- Remove debugging logging
- We no longer use Jackson so we need to manually write a custom adapter now that we use GSON to be able to searlize the Subject as expected.

BAU - Create custom adapter for Nimbus Subject object 

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/HttpRequestService.java

The spec requires application/x-www-form-urlencoded but we were sending nothing.

BAU: Set content type for backchannel logout requests

---

ci/terraform/account-management/sqs.tf
ci/terraform/oidc/logout-sqs.tf
ci/terraform/oidc/spot-sqs.tf
ci/terraform/oidc/sqs.tf

Remove sqs queue delay seconds.
From the console:
"The delivery delay is the amount of time to delay the first delivery of each message added to the queue. Any messages that you send to the queue remain invisible to consumers for the duration of the delay period."
Sets back to default zero seconds.
Removes 10 second delay for message deliveries.

BAU: Remove sqs queue delay seconds

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Set the TTL for 3 minutes from the current time.
- Previously we were setting TTL as 180 seconds which equates to 1 January 1970 00:03:00 UTC in EPOCH. Dynamo states that The TTL attribute value must be a datetimestamp with an expiration of no more than five years in the past.

BAU - Set TTL for 3 minutes from current time

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/ClientStartInfo.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/services/StartService.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/StartHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/services/StartServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java

- Return the state param from the Start lambda
- If the user selects 'Prove your identity another way' on the '/prove-identity-welcome' page, it will redirect back to the RP with an error. The RP expects the state param to form part of that redirect, so they can validate it and confirm it matches up with a request they have sent.
- The frontend does not know about the state param so it needs to be returned from the start lambda.

BAU - Return the state param from the Start lambda

---

ci/terraform/shared/dynamodb.tf

Add DynamoDB resource to shared Terraform DynamoDB file creating new common_passwords table which will contain top 100k most common passwords 
A list of common passwords is needed to check against in validation of password choice in front end registration and account management user journeys

AUT-30: Add common user passwords DynamoDB table

---

ci/terraform/account-management/build-overrides.tfvars
ci/terraform/account-management/integration-overrides.tfvars
ci/terraform/account-management/production-overrides.tfvars
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars

- Disable auto-scaling in build and integration
- Enable provisioned concurrency and autoscaling in production. Use slightly higher numbers initially, will scale back after some monitoring.
- Decrease memory allocation to 2048 initially (further decrease may be possible)
We want to enable to provisioned concurrency to decrease our latencies
#1991

AUT-330: Lambda provisioned concurrency - production

---

ci/terraform/shared/build-stub-clients.tfvars
ci/terraform/shared/integration-stub-clients.tfvars
ci/terraform/shared/production-stub-clients.tfvars
ci/terraform/shared/staging-stub-clients.tfvars
ci/terraform/shared/stub-rp-clients.tf

Switch off ConsentRequired in stubs.
Consent to share is not currently in use but is switched on in some stubs.
Will be switched off in build-s2 when acceptance tests updated.

BAU: Switch off ConsentRequired in stubs

---

ci/terraform/account-management/production-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars

- Reduce memory to 1024MB for production endpoints
To reduce provisioned concurrency costs
#1995

AUT-330: Reduce production memory allocation

---

ci/terraform/account-management/dynamo-policies.tf
ci/terraform/account-management/update-password.tf
ci/terraform/oidc/dynamo-policies.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/signup.tf

Add read permissions for new common passwords Dynamo table for three lambdas, which will use this to validate whether or not passwords is a common password and produce an error accordingly.
So that password validation can consider common words
https://github.com/alphagov/di-authentication-api/pull/1990

Aut 30/add roles to common passwords dynamodb

---

ci/terraform/account-management/production-overrides.tfvars
ci/terraform/oidc/production-overrides.tfvars

- Scale back to minimum concurrency of 2 for all OIDC & frontend lambdas
- Add an override for start to have minimum concurrency of 3 as, according to metrics, this is the busiest lambda and sometime peaks above concurrent executions of 2.
- Add overrides for the reset password lambdas to further scale back to a minimum of 1 as they have not gone above a concurrency execution of 1
- Scale back all of account management API to min concurrency of 1, this a very quiet API, except the authorizer
- Override the authorizer to have min concurrency of 3
#1995
#1998

AUT-330: Scale back provisioned concurrency in prod

---

ci/terraform/oidc/ipv-callback.tf
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

Add configuration flag for ipv + spot trace logging.
Ability to log ipv and spot messages in specific environments only.
We don't want to log these messages in prod or integration but they are useful for end to end integration testing so are worth keeping switched on in staging for the moment.

AUT-323: Add configuration flag for ipv + spot trace logging

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java

- Make it clear why an error for invalid claims or invalid scope is returned to the RP.
- So we can identify issues quicker

BAU - Add clearer logging in Authorize

---

ci/terraform/account-management/authorizer.tf
ci/terraform/modules/endpoint-module/lambda.tf

- Increase `time_sleep` resource waiting period to 45 seconds
- Add explicit `depends_on` to the `time_sleep` to only trigger after the lambda alias has been provisioned
- Add explicit `depends_on` to the provisioned concurrency config
- Add missing `time_sleep` to authorizer lambda, with above constraints
We are seeing errors in the pipeline due while trying to apply provisioned concurrency configurations

AUT-330: Force wait after alias change

---

integration-tests/src/test/java/uk/gov/di/authentication/services/DynamoServiceIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/MFAMethod.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/MFAMethodType.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserCredentials.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/NowHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

Store alternative mfa in the database.
- Draft data model for storing a list of mfa methods in the database.
We will need to store a secret key for a registered authentication app in order to validate OTP.

AUT-430: Store alternative mfa in the database

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Generate TTL in seconds instead of milliseconds
- Dynamo expects this to be in seconds otherwise it thinks the TTL is something like `18 March 54410 12:06:32 GMT`

BAU - Generate TTL in seconds instead of milliseconds

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DynamoDocAppService.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DocumentAppCredentialStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/DynamoExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/IdentityStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoIdentityService.java

- Only read records from the Identity Credentials table where the TTL has not expired by filtering out the entry if it has expired. 
- Add more integration tests to ensure that this works. This has meant adding a constructor to the IdentityStoreExtension, so we can overwrite the TTL of the table as required.
- We have a TTL attribute on the Identity Credentials table. At some point after the TTL has expired, the record will be deleted from Dynamo. This does not happen straight away and consequently we can still read the records until they are deleted.
- As per the Dynamo Docs `Items that have expired, but haven’t yet been deleted by TTL, still appear in reads, queries, and scans. If you do not want expired items in the result set, you must filter them out.`

AUT-452 - Only read records from the Identity Credentials table where the TTL has not expired

---

audit-processors/build.gradle
audit-processors/src/main/java/uk/gov/di/authentication/audit/configuration/TXMAConfiguration.java
audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/configuration/TXMAConfigurationTest.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambdaTest.java
build.gradle

- Add version 2 of the AWS secrets manager SDK to the audit processors module
- Add a new class used to retrieve configuration specific for the audit processors.
- Amend the `CounterFraudAuditLambda` to optionally hash sensitive attributes using the TXMA key if provided.
- The optional properties should have a different name
We are migrating to a new key, provided by the TXMA team. We'll do this in two steps, first dual running of keys (which this PR enables) followed by switch over. The dual running is done by hashing with the new key into new fields in the message, just to give us some confidence that its working as anticipated.
This PR should not result in any functional change, yet, as the required infrastructure configuration is not included. This will follow in another PR. …

AUT-435: Optionally hash sensitive data with TXMA hash secret

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/configuration/TXMAConfiguration.java
ci/tasks/deploy-audit-processors.yml
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/variables.tf

- Amend Terraform to add the `TXMA_OBFUSCATION_SECRET_ARN` environment variable to the counter fraud lambda. The value should be passed to Terraform as a variable as it will be per environment.
- If the TXMA_OBFUSCATION_SECRET_ARN environment variable is blank then return `Optional.empty()`
#2026 introduces the code to optionally hash with TXMA key. This enables it by adding the required environment variable, which will be blank by default. [This related PR](https://github.com/alphagov/di-infrastructure/pull/275) will add a real value for the `staging` environment.
#2026 
https://github.com/alphagov/di-infrastructure/pull/275

AUT-435: Inject TXMA Hash Secret ARN into Counter Fraud lambda

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/configuration/TXMAConfiguration.java

- Catch all exception not just the secrets manager related ones.
The logs are showing some `ClassNotFound` errors, which is concerning, lets catch and swallow ALL errors until we can work out what the issue is.
#2026

AUT-435: Catch all errors when getting obfuscation secret

---

audit-processors/build.gradle

- Add missing comma in Gradle `compileOnly` dependency directive
We are seeing `ClassNotFoundExceptions`

AUT-435: Add missing comma in Gradle

---

audit-processors/build.gradle
audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambda.java

- Add Secrets Manager dependency as an `implementation` dependency
- Swallow initialisation errors in `CounterFraudAuditLambda`
We seeing `ClassDefNotFound` exceptions for the `SecretManagerClient` class.

AUT-435: Add Secrets Manager dependency as an `implementation` dep

---

ci/terraform/audit-processors/counter_fraud.tf

- Attach the optional policy on the `CounterFraudAuditLambda` after the role has been created instead of dynamically generating the role list.
We can't use a function to create a dynanic list of roles to attach. 
#2027

AUT-435: Fix attachment of optional policy to Fraud role

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/PhoneNumberHelper.java

This publishes a metric `SendingSms` broken down by environment and country code, so we can compare "sent SMS" to successfully registered accounts.

BAU: Measure sent SMS by country code

---

ci/tasks/deploy-audit-processors.yml
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/variables.tf

- The policy also needs KMS decrypt permissions for the given KMS key
We need to have explicit permissions to the given KMS key as well as permissions to the secret
https://github.com/alphagov/di-infrastructure/pull/278

AUT-435: Add KMS statement to secrets manager policy

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/MFAMethodType.java
shared/src/main/java/uk/gov/di/authentication/shared/lambda/BaseFrontendHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/state/UserContext.java

Return MFA method information from Login.
Users will be able to choose between SMS and an Authenticator App as a second factor.  The data model for SMS is not being changed in the database in UserProfile, and an additional list of MFAMethod has been added to UserCredentials for a user.  When an auth app is added for a user this will be added to the list of MFAMethod, but for an existing user using SMS this list will be empty, and authentication will default to SMS.
This PR returns the user's MFAMethod from UserCredentials to the frontend from the 'login' lambda as additional fields on LoginResponse.  This information can then be used by the frontend to go down the correct path either to send a code by SMS for entry, or for the user to enter a code from their auth app.
Support …

AUT-431: Return MFA method information from Login

---

ci/terraform/audit-processors/counter_fraud.tf

- Add the missing ` == ""` to the ternary expression for `count`
Terraform is invalid
#2033

AUT-435: Fix conditional statement for TXMA secrets policy

---

shared/src/main/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ApiGatewayResponseHelperTest.java

add `preload` directive to Strict-Transport-Security header
So that we can add all of *.account.gov.uk to the HSTS preload list:
https://hstspreload.org/
Also so I can feel like I write code for once

DCP-147: add `preload` directive to Strict-Transport-Security header

---

integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/domain/IPVAuditableEvent.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTResponse.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandlerTest.java

- Use the 2 additional fields added to the SPOT response
- Attach the log ids to the relevant log lines so we can track user journeys.
- Add 2 Audit events which differentiates between a successful and unsuccessful SPOT response.
- The SPOT response has had 2 additional fields added. 'log_ids' which is the same as passed in in the SPOT request and 'reason' which will only be present if the status is REJECTED.

AUT-468 - Use the 2 additional fields added to the SPOT response

---

ci/terraform/shared/integration-stub-clients.tfvars

- Add config for a Stub RP App in the Integration environment
- So we can test out a app journey in Integration

BAU - Add Stub RP config for integration app

---

ci/terraform/oidc/doc-app-authorize.tf

- Rename doc-checking-app-authorize to doc-app-authorize
- Because terraform thinks it is too long

BAU - Rename doc-checking-app-authorize to doc-app-authorize

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditReplayLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditReplayLambdaTest.java
ci/terraform/audit-processors/counter_fraud_replay.tf
tools/replay-messages.sh

- Add a lambda to replay fraud messages that are placed in a specific S3 bucket
- Add a script that will copy a given list of audit events from audit cold storage to a given S3 bucket (where they can be picked up for replay)
- Add terraform to create the replay bucket
- Add terraform to create the lambda function and execution role
- Add terraform to trigger lambda when objects created in the replay bucket
- DO NOT ENABLE Splunk log subscription.
We had an issue where some fraud events were dropped from logging and we need to replay them. This PR gives us a mechanism to pickup the missing events from the S3 "cold storage" and copy them to a different bucket where they can be picked up to replay.
The missing events have been identified using an Athena query. The query gives the S3 URLs for …

AUT-435: Replay events mechanism

---

doc-checking-app-api/src/main/resources/log4j2.xml
frontend-api/src/main/resources/log4j2.xml
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/LogIds.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/SPOTRequest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/main/resources/log4j2.xml
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- Add clientSessionId to SPOTRequest
- Add audience to SPOTRequest
- Add missing context logging to relevant repos
- The audience will be set by the clientID. This will be the audience in the https://vocab.account.gov.uk/v1/coreIdentityJWT
- Add missing context logging to relevant repos. Without this the fields will be omitted in our logs.

AUT-471 - Add additional properties to SPOTRequest

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java

- Update wellknown to reflect token algs we support
- We only support RSA keys at this moment in time

BAU - Update wellknown to reflect token algs we support

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/WellknownHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

- Add tests to the TokenService to ensure we can support the keys we say we can support in the wellknown endpoint
- Add extra logging in the TokenService to make it easier to debug errors
- Re-introduce PS256, PS384 and PS512 to the wellknown endpoint as do support these algorithms
- To give us more confidence we can support certain algorithms 
- To help us debug issues easier

BAU - Test that the supported keys work for PrivateKeyJWT

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java

- Change the VerifyCodeHandler to save the session when a user enters a valid code.
- Add additional checks and tests to confirm this behaviour
- We were resetting the count in the session when a valid code was entered, but we were never saving the session so this reset was lost.
- A user should be able to request a max of 5 OTPs for each of email AND SMS however there was a bug which only allowed to request a max of 5 OTPs for both email AND SMS in total. I.E - 3 Email OTPs and then 3 SMS OTPs = blocked.

AUT-472 - Fix rate limit OTP bug

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/JwksHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/JwksHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/matchers/APIGatewayProxyResponseEventMatcher.java

This sets a max-age of one day on the contents from the JWKs endpoint.
This should encourage relying parties to periodically refresh the keys and enable us to do shorter duration key additions and removals.
https://openid.net/specs/openid-connect-core-1_0.html#RotateEncKeys

BAU: Set max-age on JWKs endpoint

---

ci/tasks/ipv-status.yml
ci/tasks/ipv-switch.yml
ci/terraform/oidc/ssm.tf

- Tell Terraform to ignore any changes made to the `ipv-capacity` inside or outside of Terraform.
- Add a task to check current status
- Add a task to switch to a desired state (state to be override in a pipeline when called), defaults to off.
We need an easy way of switching IPV on or off, we'll do this in a Concourse pipeline (to be written), that will call the tasks defined here.

AUT-459: IPV Capacity Switch

---

audit-processors/src/main/java/uk/gov/di/authentication/audit/configuration/TXMAConfiguration.java
audit-processors/src/main/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambda.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/configuration/TXMAConfigurationTest.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/lambda/CounterFraudAuditLambdaTest.java
ci/terraform/audit-processors/counter_fraud.tf
ci/terraform/audit-processors/site.tf

- Use only the TXMA obfuscation key, fall back to locally provided one if secret does not exist (this will only occur in certain non-prod environments).
- Only output the a single version of the sensitive fields. (Remove the `.txma` version)
- In environments that are not linked to a "real" TXMA using Secrets Manager to store the generated HMAC secret to make the application code cleaner.
We have dual run the HMAC secrets and are happy that things are working as they should. Let's shut off the old key all environments that are linked to real TXMA envs.

AUT-435: Stop dual running obfuscation keys

---

ci/tasks/ipv-status.yml

- Add the missing environment variable interpolation to the parameter name in `ipv-status.yml`
We want to run this in different environments, so the hard-coded `build` won't work.

AUT-459: Correctly interpolate parameter name in IPV status job

---

ci/terraform/oidc/token.tf
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/SubjectHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/CustomScopeValue.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/TokenService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/TokenServiceTest.java

This is needed for a spike into a service which does not (yet) support URN-format subject identifiers

AUT-475: Create a custom `resource-id` scope for non-urn format subject ID

---

account-management-api/src/main/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandler.java
account-management-api/src/test/java/uk/gov/di/accountmanagement/lambda/SendOtpNotificationHandlerTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java

- Check new phone number is not the same as current phone number
- If it is, then return an error code to the account management frontend. The AM frontend will then display an error to the user.
- The backend is the source of truth and will be able to inform the AM frontend whether or not the new number is the same as the current number.

AUT-35 - Check new phone number is not the same as current phone number

---

integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AccessTokenServiceTest.java

- Only return identity claims to clients that support identity
- Downgrade some logging form WARN to INFO
- Before we return identity claims back to RPs, we should check if the client supports identity. This gives us extra protection in ensuring only those clients receive identity claims.

BAU - Only return identity claims to clients that support identity

---

ci/tasks/deploy-utils.yml

- Add deploy task for utils module to CI tasks
- Note: Terraform currently not set up for logging to use the logging endpoints var, but this will be handled in a separate PR
- This task will be used in the deployment pipeline (here: https://github.com/alphagov/di-infrastructure/blob/main/ci/di-deployment-pipeline.yml) when deploying utils module to build, staging, integration and production

AUT-437: Add deploy task for utils module to CI tasks

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/LoginResponse.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/LoginIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/conditions/MfaHelper.java

- Remove phoneNumberVerified from LoginResponse
- We don't need to return the phoneNumberVerified attribute on the login response and instead rely on the mfaMethodVerified type.

BAU - Remove phoneNumberVerified from LoginResponse

---

ci/terraform/utils/variables.tf

- Add Terraform variable definitions for logging and shared state bucket
Removes error in deploy-utils-build due to variables being passed without a definition. These variables will be used when logging is configued.

AUT-437: Add Terraform variable definitions for logging and shared state

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/SPOTResponseHandler.java

- Fix logging typo
- This should be ClientID not sessionID

BAU - Fix logging typo

---

ci/terraform/utils/common_passwords_update_lambda.tf
ci/terraform/utils/production-overrides.tfvars
ci/terraform/utils/shared.tf
ci/terraform/utils/variables.tf

- Add common passwords transfer lambda log group to Terraform
- Add variable for retention - default 1, but 5 days for production
- Add shared.tf to consume outputs of shared state bucket, including CloudWatch encryption key arn
- To allow log groups to be created in each environment, so that logs can be viewed in CloudWatch for the new common passwords S3->Dynamo data transfer lambda
https://github.com/alphagov/di-authentication-api/pull/2089 - base lambda including Terraform
https://github.com/alphagov/di-authentication-api/pull/2097 - addition of some logging variables (as placeholders at that point to match the input arguments of the deploy-utils-build task)

AUT-437: Add common passwords transfer lambda log group to Terraform

---

integration-tests/src/test/java/uk/gov/di/authentication/api/ProcessingIdentityIntegrationTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/ProcessingIdentityStatus.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/ProcessingIdentityHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java

- Add an attribute to the session which counts how many attempts there has been at calling the ProcessingIdentity lamda. If it's the first attempt and there's nothing in dynamo, then we assume that the user has got into a weird state and we will return the NO_ENTRY status back to the frontend.
- This count will be reset when the user hits authorize again, regardless of whether they have an existing session.
- Add a cloudwatch metric counter to track the different statuses returned from the ProcessingIdentity lambda
- We currently return ERROR when there is nothing in the Identity Credentials table with the given subject ID. This may be because we received an error from SPOT and then went on to delete the credential. It could also happen if there was nothing ever in the Identity …

BAU - Update Processing Identity Lambda to return additional status

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf

Add a robots.txt to the OIDC API - Build only.
As this is a public API it's being scraped by robots which creates unecessary noise in the logs.
Adding a robots.txt to keep them away.

AUT-277: Add a robots.txt to the OIDC API - Build only

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/sandpit.tfvars
ci/terraform/oidc/variables.tf

Rollout OIDC API robots.txt to all environments.
Following testing in build and switched-off terraform in other environments which did not create the new resource.
#2109

AUT-277: Rollout OIDC API robots.txt to all environments

---

ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/production-overrides.tfvars

Tweak robots.txt redeploy trigger.
Switch off prod pending redeploy testing.
The api gateway resource integration is being redeployed when there are no changes.

AUT-277: tweak robots.txt redeploy

---

ci/terraform/oidc/api-gateway.tf

Remove optional integration_http_method
Causing unnecessary redeploy of the integration whenever the terraform runs:
aws_api_gateway_integration.robots_txt_integration[0] must be replaced
-/+ resource "aws_api_gateway_integration" "robots_txt_integration" {
- cache_key_parameters    = [] -> null
~ cache_namespace         = "it9eq6" -> (known after apply)
~ id                      = "agi-6of9f4amvg-it9eq6-GET" -> (known after apply)
+ integration_http_method = "GET" # forces replacement
~ passthrough_behavior    = "WHEN_NO_MATCH" -> (known after apply)
- request_parameters      = {} -> null
}
#2112

AUT-277: remove optional integration_http_method

---

ci/terraform/oidc/production-overrides.tfvars

Switch robots.txt back on in prod.
Terraform working in other environments, resolve terraform deployment issue by applying the same config to prod.
#2113 
#2112

AUT-277: Switch robots.txt back on in prod

---

ci/terraform/oidc/jwks.tf

- Set the DOC_APP_TOKEN_SIGNING_KEY_ALIAS in the JWKsHandler
- It was previously missing and therefore was null. This caused an issue creating the JWK

AUT-439 - Set the DOC_APP_TOKEN_SIGNING_KEY_ALIAS in the JWKsHandler

---

ci/terraform/oidc/staging-overrides.tfvars

- Set the doc_app_domain in staging-overrides.tfvars
- This is used to calculate the pairwise subject identifier. Currently it is null, so is throwing a null pointer.

AUT-507 - Set the doc_app_domain in staging-overrides.tfvars

---

ci/terraform/shared/production-stub-clients.tfvars

- Set the `test_client` value to `1` for the production stub.
We need to bypass the IPV capacity flag when using the production stub, this is done by making it a test client.

BAU: Make the production stub a test client

---

shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java

- Add check that supplied auth app code string - transmitted from front end - which must be parsed to int as part of validation algorithm, is neither empty not too long
- This avoids `NumberFormatException` when in these cases the supplied code must by definition be invalid, as it is unprocessable by our algorithm, so simply returning a validity check result of `false` achieves the desired effect (Note: NumberFormatException was thrown silently until now for long numbers because `Integer.ParseInt` cannot handle any number larger than 2^31 - 1)
- Have also revisited the relevant unit test, which I only noticed when trying to run it with an example number that it was actually not setting up an invalid code correctly (it was giving the correct error response, but for the wrong reason - …

AUT-537: Add generic pre-validation of supplied string auth app code to validity check

---

ci/terraform/oidc/build-overrides.tfvars
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppAuthorisationServiceTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java

- Get public keys for Doc App via JWKs (apart from Integration)
- The Stub has been changed to host it's keys on a JWKs. This will keep it consistent with the real Doc App.
- Try it for build before switching integration later on.

AUT-546 - Get public keys for Doc App via JWKs (apart from Integration)

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf
ci/terraform/oidc/doc-app-authorize.tf
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/production-overrides.tfvars
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java

- Remove the terraform feature flag from the Doc App lambdas so they are deployed to every environment.
- Add a check in the DocAppAuthorize lambda to ensure that the DocApp api is enabled. This is for belt and braces and we already have a check in the authorize lambda.
- So we have all lambads etc deployed to Production which will make us ready to integrate with the doc app service when the time comes

AUT-564 - Remove feature flag from Doc App lambdas

---

ci/terraform/oidc/api-gateway-frontend.tf
ci/terraform/oidc/api-gateway.tf

- Remove triggers for doc app lambdas
- To try and get round the `Error: Cycle:` in the deploy-oidc-api-build job

BAU - Remove triggers for doc app lambdas

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Switch DocApp off in non-prod environments
- To allow us to remove the doc_app_api_enabled flag from our terraform.

AUT-564 - Switch DocApp off in non-prod environments

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars

- Renable doc app journeys in non-prod environments
- So journeys can be tested

AUT-564 - Renable doc app journeys in non-prod environments

---

ci/terraform/oidc/build-overrides.tfvars
ci/terraform/oidc/doc-app-callback.tf
ci/terraform/oidc/integration-overrides.tfvars
ci/terraform/oidc/staging-overrides.tfvars
ci/terraform/oidc/variables.tf
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Remove signing validation of doc app credential
- Remove signing kid from confog
- Having discussed this with the architects, it was agreed we don't need to worry about validating the signature of the credential and can just leave it to up to the RP to validate. 
- As we no longer will be validating the credential, we no longer need to store the signing kid in config

AUT-569 - Remove signing validation of doc app credential

---

ci/terraform/shared/production-stub-clients.tfvars

Add client for the prod app stub.
A stub RP client app is needed in production to facilitate the Apple app review process.

AUT-562: Add client for the prod app stub

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppCriService.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppCriServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/CriStubExtension.java

- Validate that the 'sub' field in the /userinfo response is the same as the docAppSubjectID in the client session
- If not, throw an exception rather than persisting the signedJWTs returned from the endpoind to Dynamo
- Make this conditional on the environment being anything other than build - because the build environment has a stub running presently that has a hard-coded `sub` value, and this would break our ability to persist the `userinfo` response in dynamo.
- To avoid persisting incorrect data

AUT-559: Add validation userinfo vs client session docAppSubjectId 

---

ci/terraform/oidc/cloudwatch-policies.tf
ci/terraform/oidc/userinfo.tf
ci/terraform/oidc/verify_code.tf
oidc-api/src/main/java/uk/gov/di/authentication/oidc/entity/AccessTokenInfo.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AccessTokenService.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/UserInfoService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/UserInfoServiceTest.java

- Create count metric for doc-app-credential claims issued
- Give the userinfo lambda permissions to publish a new cloudwatch metric.
- Create a new cloudwatch metric in userinfo to count the number of doc-app-credential claims issued back to the RP.
- This will give us data to create a graph in Grafana to display the count on a per client basis

AUT-567 - Publish DocAppCredential issued to cloudwatch per client

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/services/DocAppAuthorisationService.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/services/DocAppAuthorisationServiceTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java

5d JWT expiration and additional claim for doc app test clients.
Facilitate Apple app store process.
Able to return a JWT valid for 5 days for app store testing purposes only using the prod doc app stub.
#2161 
https://github.com/alphagov/di-infrastructure/pull/321

AUT-562: 5d JWT expiration and additional claim for doc app test clients

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppAuthorizeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java

Use the rp client rather than the doc app client for stub testing behaviour.
The doc app client is not available in the client registry when trying to check whether the stub is a test client.
#2165 
#2166

AUT-562: Use the rp client rather than the doc app client

---

ci/terraform/oidc/userinfo.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/domain/OidcAuditableEvent.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/UserInfoHandlerTest.java

- BAU: Wire `AuditService` into `UserInfoHandler`
- BAU: Emit `USER_INFO_RETURNED` message on success
- BAU: Enable user-info endpoint to post audit messages to SNS

BAU: Audit user info endpoint

---

oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/services/AuthorizationService.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/services/AuthorizationServiceTest.java

- BAU: Expose `isTestJourney` method to determine if journey is "real"
- BAU: Add `IsTest` dimension to `SignIn` metric to differentiate test journey
We want to be able to exclude test journeys from some of our dashboards

BAU: Differentiate test journeys in metrics

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandlerTest.java

- If an OTP code is found in redis, resend it
- By definition this results in resending same code for 15 mins, as the code is only stored for 15 mins before it is deleted
- This should help users from inadvertently inputting expired codes because they have requested a new one in the interim (invalidating their old one)

AUT-393: Send repeat OTP code within 15 minutes

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/entity/MfaRequest.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandlerTest.java

- Add optional `isResendCodeRequest` field to MFA Handler
- This will allow it to be called and simply to re-issue to same phone verification code as was issued in the account creation journey when phone number is given for the first time (just after the user inputs their phone number into a form and submits it).
- The existing lambda when that initial submission happens - `SendNotificationHandler` - cannot be used because a `SendNotificationRequest` must have a phone number input, which is not available to the front end at that later point of the journey
- Similarly the `MfaHandler` cannot be used without modification as it checks Redis for a code specifically associated with `MFA_SMS` `NotificationType`, and saves new codes to that same type. This cannot work, since in the previous …

AUT-393: Add optional isResendCodeRequest field to MFA Handler

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
integration-tests/src/test/java/uk/gov/di/authentication/api/MfaHandlerIntegrationTest.java

- Add integration test skeleton to MfaHandler
- Add test cases to check new back end behaviour which differentiates between resending code and normal MFA request works
- Improve test coverage/robustness
Change in behaviour which is tested in new integration tests was introduced here: https://github.com/alphagov/di-authentication-api/pull/2180

AUT-393: Add integration tests for MfaHandler

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/exception/DocAppCallbackException.java
doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java

Redirect to the frontend error page for doc-app-callback session errors.
This only covers session errors for the moment, other errors will be handled differently once we know how to return them to the HMRC RP.
The doc-app-callback lambda returns a 500 directly in case of error, which is displayed in the browser in a rather unfriendly way. Instead route to the more user friendly error page when something goes wrong, where links to contact support etc are available.
https://github.com/alphagov/di-authentication-frontend/pull/687

AUT-583: Redirect to the frontend error page for doc-app-callback session errors

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandler.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationService.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVAuthorisationHandlerTest.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/services/IPVAuthorisationServiceTest.java

This propagates the client session id to IPV Core as a claim called `govuk_signin_journey_id`
This lets us have an end-to-end identifier across systems that corresponds to a single sign in journey.

AUT-596: Cross-programme journey id

---

ci/tasks/deploy-oidc-api.yml
ci/terraform/modules/txma-audit-queue/key.tf
ci/terraform/modules/txma-audit-queue/output.tf
ci/terraform/modules/txma-audit-queue/queue.tf
ci/terraform/modules/txma-audit-queue/variables.tf
ci/terraform/oidc/audit.tf
ci/terraform/oidc/variables.tf

This creates a Terraform module which creates a queue and key that can be subscribed to by the TxMA team
Migrating the auth-specific audit service to the programme-wide audit service

AUT-584: Create TxMA-specified audit queue and key in build environment

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java

Additional error handling for the doc-app-handler.
Redirect to error page for remaining scenarios that threw exceptions.
Additional tests and test refactoring.
Errors that threw a raw Exception would show the user unfriendly error text in the browser.  Replace this with a more user friendly error page.  The scenarios in question are not recoverable.
#2186 
#2181

AUT-542: Additional error handling for the doc-app-handler

---

ci/terraform/oidc/sandpit.tfvars
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/LoginHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/MfaHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/ResetPasswordRequestHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/SendNotificationHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthorisationIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppAuthorizeHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/DocAppCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVAuthorisationHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/IPVCallbackHandlerIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/JwksIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ParameterStoreExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/ValidationHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/CodeStorageService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/ValidationHelperTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/CodeStorageServiceTest.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java

- Increment and save MFA code attempts against email address (persistent) rather than session (temporary) in Redis 
- Make counter clear itself after 15 minutes (aligned to 'lifespan' of OTP codes themselves)
- Remove simple counter of retries currently stored within session object in Redis
- Refactor `CodeStorageService` to take in `ConfigurationService` rather than `RedisService(ConfigurationService)` in its constructor, in order to remove Redis implementation detail from handlers, and to make accessing other config parameters in future easier e.g. if we want to set the MFA counter's 'time to live' via config rather than the current hard-coding of `900L`.
Note: Whilst not directly part of the functionality, also in this PR is a change to Sandpit default var of how long a code block …

AUT-561: Limit OTP/MFA code retry by email not browser session

---

ci/terraform/account-management/authorizer.tf
ci/terraform/modules/endpoint-module/lambda.tf

- Add `triggers` attribute to the `time_sleep` resource. 
This will ensure that the sleep occurs on every change of the lambda version and hence the sleep will be triggered. Currently, it seems that the sleep was only triggered on the first run, hence we were continuing to get issues on deployment of new endpoint versions.

BAU: Fix provisioned concurrency deployment issues

---

ipv-api/src/main/java/uk/gov/di/authentication/ipv/entity/IpvCallbackException.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java

- Refactor all `RuntimeException`s to redirect back to frontend error page
- Add new custom exception type (`IpvCallbackException`)
- So that a visual error page is displayed to the end user rather than raw JSON in the case of 500 status.
- Mirrors implementation for DocAppCallbackHandler (x2): 
https://github.com/alphagov/di-authentication-api/pull/2181
https://github.com/alphagov/di-authentication-api/pull/2188

AUT-583: Change IPV Callback exceptions to redirect to frontend

---

ci/terraform/account-management/authorizer.tf
ci/terraform/modules/endpoint-module/lambda.tf

- Reduce the wait time from 120s to 60s, 
We have fixed the issue with the `time_sleep` resource not working properly on update, we now need to find the optimum wait time as 2 mins is possibly too long.
#2201

BAU: Reduce time to wait for alias to update

---

ci/terraform/modules/txma-audit-queue/output.tf
ci/terraform/oidc/userinfo.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java
shared/src/main/java/uk/gov/di/audit/TxmaAuditEvent.java
shared/src/main/java/uk/gov/di/authentication/shared/configuration/AuditPublisherConfiguration.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AwsSqsClient.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

Send the MVP audit payload to TxMA's audit queue from a single endpoint in build and staging

AUT-584: Publish TxMA-format audit messages to SQS for consumption

---

ci/terraform/oidc/userinfo.tf

Back this change out to unblock pipeline overnight.

AUT-584: Turn off TxMA audit pipeline in build and staging

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/AuthCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandler.java
oidc-api/src/test/java/uk/gov/di/authentication/oidc/lambda/AuthCodeHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/RedisExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/ErrorResponse.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/Session.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java

- Add the MfaMethodType to the session so we can expose it in the SignIn cloudwatch metric in the AuthCodeHandler. This will dimension will be omitted when the users is either using SSO or is signing in from a low level service and has not need to use MFA.
- Make audit events consistent for when either SMS or AUTH_APPS are used as the users MFA method. 
- Create and add unit tests for the VerifyMfaCodeHandler.java. Refactor the VerifyMfaCodeHandler so external classes can be mocked out.
- Add detailed logging of what MFA type is used and whether it the user is signing up or signing in
- Remove NewAccount metric in the VerifyCodeHandler 
- By adding the MfaMethodType to the SignIn cloudwatch metric, we will be able to see the amount of users using AuthApps vs those that use SMS 
- Ensure …

AUT-619 - MFA metric and logging amendments

---

shared/src/main/java/uk/gov/di/audit/TxmaAuditEvent.java
shared/src/test/java/uk/gov/di/audit/TxmaAuditEventTest.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

- AUT-584: `component_name` should be `component_id`
- AUT-584: Send timestamp in seconds rather than milliseconds

AUT-586: TxMA-requested tweaks to payload structure

---

shared/src/main/java/uk/gov/di/authentication/shared/services/AuditService.java
shared/src/test/java/uk/gov/di/authentication/shared/services/AuditServiceTest.java

- AUT-584: Use `JsonMatcher` for testing TxMA payloads
- AUT-584: Add client id and component id to top level audit payload
- AUT-584: Add user fields to TxMA payload
- AUT-584: Add extensions to TxMA payload

AUT-584: Enrich payloads with existing data

---

ci/terraform/oidc/update.tf
ci/terraform/oidc/update_profile.tf
ci/terraform/oidc/userexists.tf
ci/terraform/oidc/verify_code.tf
ci/terraform/oidc/verify_mfa_code.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateClientConfigIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UpdateProfileIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserExistsIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/UserInfoIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyCodeIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/VerifyMfaCodeIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/basetest/HandlerIntegrationTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuditAssertionsHelper.java

- AUT-584: Unify audit integration test matchers to make rollout easier
- AUT-584: Declare TxMA-enabled integration test configuration
- AUT-584: Allow SqsQueueExtensions to be programmatically cleared
- AUT-584: Publish TxMA events from `VerifyMfaCodeHandler`
- AUT-584: Publish TxMA events from `VerifyCodeHandler`
- AUT-584: Publish TxMA events from `UserExistsHandler`
- AUT-584: Publish TxMA events from `UpdateProfileHandler`
- AUT-584: Publish TxMA events from `UpdateClientConfigHandler`

AUT-584: Migrate other OIDC handlers to TxMA

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java

- Downgrade logging in DocAppCallback lambda to WARN
- These errors were previously logged as ERROR, however they occur when a user aborts a journey on the DocApp. We are currently being sent back the `invalid_request` error code which isn't correct but for now downgrade the logging so we are not alerting on something that doesn't need to be actioned.

BAU - Downgrade logging in DocAppCallback lambda to WARN

---

ci/terraform/oidc/reset-password-request.tf
ci/terraform/oidc/reset_password.tf
ci/terraform/oidc/send_notification.tf
ci/terraform/oidc/signup.tf
ci/terraform/oidc/spot-response.tf
ci/terraform/oidc/start.tf
ci/terraform/oidc/token.tf
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/ResetPasswordRequestIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/SignupIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/StartIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/api/TokenIntegrationTest.java
integration-tests/src/test/java/uk/gov/di/authentication/queuehandlers/SpotResponseIntegrationTest.java

- AUT-584: Publish TxMA events from `TokenHandler`
- AUT-584: Publish TxMA events from `StartHandler`
- AUT-584: Publish TxMA events from `SPOTResponseHandler`
- AUT-584: Publish TxMA events from `SignupHandler`
- AUT-584: Publish TxMA events from `SendNotificationHandler`
- AUT-584: Publish TxMA events from `ResetPasswordHandler`
- AUT-584: Publish TxMA events from `ResetPasswordRequestHandler`

AUT-584: Migrate other OIDC handlers to TxMA (2)

---

ci/tasks/deploy-acct-mgmt-api.yml
ci/tasks/deploy-audit-processors.yml
ci/terraform/account-management/audit.tf
ci/terraform/account-management/outputs.tf
ci/terraform/account-management/variables.tf
ci/terraform/modules/txma-audit-queue/key.tf
ci/terraform/modules/txma-audit-queue/queue.tf
ci/terraform/modules/txma-audit-queue/variables.tf
ci/terraform/oidc/audit.tf
ci/terraform/oidc/outputs.tf

This will help us further solidify the distinction between the Account Management RP and the rest of the wider Auth component

AUT-584: Create separate TxMA queue for account management

---

account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/AuthenticateIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/RemoveAccountIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/SendOtpNotificationIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdateEmailIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePasswordIntegrationTest.java
account-management-integration-tests/src/test/java/uk/gov/di/accountmanagement/api/UpdatePhoneNumberIntegrationTest.java
ci/terraform/account-management/audit.tf
ci/terraform/account-management/authenticate.tf
ci/terraform/account-management/outputs.tf
ci/terraform/account-management/remove-account.tf
ci/terraform/account-management/send_otp_notification.tf
ci/terraform/account-management/update-email.tf
ci/terraform/account-management/update-password.tf
ci/terraform/account-management/update-phone-number.tf
ci/terraform/shared/grafana-read-only-role.tf

- AUT-584: Rename queue within terraform
- AUT-584: Publish TxMA events from `UpdatePhoneNumberHandler`
- AUT-584: Publish TxMA events from `UpdatePasswordHandler`
- AUT-584: Publish TxMA events from `UpdateEmailHandler`
- AUT-584: Publish TxMA events from `SendOtpNotificationHandler`
- AUT-584: Publish TxMA events from `RemoveAccountHandler`
- AUT-584: Publish TxMA events from `AuthenticateHandler`

AUT-584: Migrate account management audit to TxMA

---

ci/terraform/shared/dynamodb.tf

- Add a Global Secondary Index to the `UserProfile` table that has
partition key `SubjectID` and sort key `accountVerified`.
- Index should only contain key fields to save on space.
We need to index the new `accountVerified` field so we can use it to populate a metric of how many accounts we currently have.
#2232

AUT-621: Create VerifiedAccountIndex

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandler.java
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyCodeHandlerTest.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandlerTest.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/UserStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/entity/UserProfile.java
shared/src/main/java/uk/gov/di/authentication/shared/services/AuthenticationService.java
shared/src/main/java/uk/gov/di/authentication/shared/services/DynamoService.java

- Add new, nullable, field to the userProfile table. It should hold a boolean
- The field should initially be `null` (not `false`), as such, it won't be written to Dynamo and we can use a sparse Global Secondary Index for to query a count of verified accounts.
- Set the `accountVerified` flag on UserProfile when confirming verification of either phone number of MFA method.
We need a simple way of getting the number of verified accounts (i.e. have had both e-mail and MFA verified). This new field will be used in a Dynamo index to provide this value.
(P.R to back-fill already existing accounts to follow)
#2233

AUT-621: Store new `accountVerified` flag

---

frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/VerifyMfaCodeHandler.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/helper/AuthAppStubTest.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidator.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidator.java
shared/src/main/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactory.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/AuthAppCodeValidatorTest.java
shared/src/test/java/uk/gov/di/authentication/shared/validation/MfaCodeValidatorFactoryTest.java

- Remove usercontext from the MfaCodeValidator
- Currently the MfaCodeValidator is dependent on the usercontext being passed into the constructor. This restricts this class to just be used on the frontend-api as the account management api does not currently use the BaseFrontendHandler which builds the usercontext. To add the BasefrontendHandler to the account management api will require a bit of work as the account management api redis instance does not store the user session. By passing the emailaddress in the constructor removes the need to have a usercontext to use the MfaCodeValidator

BAU - Remove usercontext from the MfaCodeValidator

---

build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/ParameterStoreExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/ConfigurationService.java

- Update SSM sdk to AWS SDK v2
- We want to gradually move away from AWS SDK v1. This moves the SSM client over to SDK v2.

BAU - Update SSM sdk to AWS SDK v2

---

audit-processors/build.gradle
audit-processors/src/main/java/uk/gov/di/authentication/audit/services/S3Service.java
audit-processors/src/test/java/uk/gov/di/authentication/audit/services/S3ServiceTest.java
build.gradle
frontend-api/build.gradle
frontend-api/src/main/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandler.java
frontend-api/src/test/java/uk/gov/di/authentication/frontendapi/lambda/NotificationHandlerTest.java
integration-tests/build.gradle
integration-tests/src/test/java/uk/gov/di/authentication/utils/CommonPasswordsS3ToDynamoIntegrationTest.java
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/CommonPasswordsS3Extension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/S3Extension.java
shared/build.gradle
utils/src/main/java/uk/gov/di/authentication/utils/lambda/S3ToDynamoDbHandler.java
utils/src/test/java/uk/gov/di/authentication/utils/lambda/S3ToDynamoDbHandlerTest.java

- Upgrade AWS S3 to use version2 of the SDK
- Version 2 is the latest and greatest and offers us more features. It also means when we migrate completely away from version 1, we will only be managing one version of the SDK.

BAU - Upgrade AWS S3 to use version2 of the SDK

---

doc-checking-app-api/src/main/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandler.java
doc-checking-app-api/src/test/java/uk/gov/di/authentication/app/lambda/DocAppCallbackHandlerTest.java
ipv-api/src/main/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandler.java
ipv-api/src/test/java/uk/gov/di/authentication/ipv/lambda/IPVCallbackHandlerTest.java
oidc-api/src/main/java/uk/gov/di/authentication/oidc/lambda/LogoutHandler.java
shared/src/main/java/uk/gov/di/authentication/shared/helpers/CookieHelper.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SessionService.java
shared/src/test/java/uk/gov/di/authentication/shared/helpers/CookieHelperTest.java

- Change generic exception (`RuntimeException`) which is thrown when no session is found in the `IpvCallbackHandler`, to throw `IpvCallbackException`
- This has already been set up to be handled with a redirect to front end error page
Note: While not directly part of the ticket, I have also changed the `parseSessionCookie()` method in `CookieHelper` to be an instance method rather than a static method. This was to aid unit testing, and could be a pre-cursor to moving the entire class towards being instantiable rather than a collection of static methods, but doesn't have to be. As a result of this change, some other classes also needed updating since they were dependent on the static method.
- Throwing `IpvCallbackException` means that the error handling set up in an earlier PR will catch …

AUT-583: Handle 'no session found' error in IPV Callback Handler

---

ci/terraform/utils/sandpit.tfvars
utils/build.gradle

- Use correct parameter name for shared state bucket
- Add Jacoco task to Gradle so coverage stats are generated
The incorrect parameter name was causing Terraform to prompt during sandpit deploy
The missing Jacoco report means Sonar is reporting 0% coverage on changes to the `utils` module

BAU: Minor fixes to utils module

---

build.gradle
shared-test/build.gradle
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SnsTopicExtension.java
shared-test/src/main/java/uk/gov/di/authentication/sharedtest/extensions/SqsQueueExtension.java
shared/src/main/java/uk/gov/di/authentication/shared/services/SnsService.java

- Upgrade SQS and SNS to version 2 of the AWS SDK
- Version 2 is the latest and greatest and offers us more features. It also means when we migrate completely away from version 1, we will only be managing one version of the SDK.

BAU - Upgrade SQS and SNS to version 2 of the AWS SDK
